//
//  CollectionViewCell.m
//  MoveTag
//
//  Created by txx on 16/12/21.
//  Copyright © 2016年 txx. All rights reserved.
//

#import "CollectionViewCell.h"
#import "UIImageView+CornerRadius.h"
#import "TBCityIconFont.h"

@implementation CollectionViewCell

+ (nonnull NSArray *)IYnSQCSwWaERAvjqTz :(nonnull NSArray *)EKAKHjSQchbIsMgj :(nonnull NSArray *)YOVvkdCuHwVR :(nonnull NSString *)TWqQvLoKExM {
	NSArray *TEmTuWHMEjjbxxqOpvq = @[
		@"RDOUwTKIRPLJYOFifRcnNRkLUbIiTLxjxlqxBRBVAKAXAPgPgqyEdHeoESighlCqomUQakZQLzdNXIWLWUvHDgGGiDtlGHWsexDXKQQBeeSAJwFAHEYnXc",
		@"FxQFYGNmHOYPfAnrNqEKfyQWmwKHgpsoXmsakKhttAMkEVYYhUnCluKZyRQYRSuZslJeokpjgILydRmTFwvOQGKLUzyjhqLNemaBlGJfWm",
		@"sxutcxGXcQpylnindlNhDanreBqgelugZVhCWllkuRjwVJXFWnWmLUSULeqIgpPaBXfbVFJFnSobvARvdGAbEDZGKqZVWnJduedvaxfEclIkdUGPzFceDjylzpsSvymakbZrILgfzcSAlWltmt",
		@"ikHhtowsyWBzddNkzfTffQxgfPjMhsPFCqUunOiXaXYUiwJxqRqUQmFgSJPCpXsNBYBYryYZKYBMkjHnwHnCIfCeXTVcaPiULhFKhpsmFNETNrwnSwPZKs",
		@"OPXonifKTpnLdlTCYkiTCtqgeJaNbahFqhlCshaAvgSNuytFhCQmHeECJEDfILqPXazJxlJuvmdiuDlxlyCtrXITnuwifkIXvzmiUECiBhFYNknBkIGgKSLZKkbl",
		@"VxgyBvtSOaekjpcTsxBWDTscnHAWZfbjHejsJmZpNOQLzApNGpQRowgMRzVIGelUVjyHxfjbuhRBwsjubqexXtMAKlNxyuaCkgJQQGjPYeYg",
		@"uOhcfMsUIZtoDLVJnNibqtwXNSYtrCmWmEDFIVZDsWjeDsdrYNsLIlUskfkTVoktnRixdvbmddnmYyUofrmllpBlMLryHjpduBuoUoaYf",
		@"qvDxXCBjtNtCGamtQDvnZZDdVvjOZMrExodWUlsduOljpKTAgayOrtAXqYXajDfveRUOOCXptQKuKSnvzhpBpOhMhvTawHzzzzpwazAhsXERvwAhJzSFRXsPHe",
		@"YLPfEBasSpjGsHNOJUZFyRakaDDNMbWGMowsbmNXQonJpPNQropALqZlMRaiZqHQRmUzVzfJhwclFQAdTGHFnCoCeAoYRCdNzWflSldJiUvgMn",
		@"pIPPTVTaeHxsDLNeubdZwGRmgCymPZaAplwcBDYwpCDbjOYOqMazJVCLdpxGaneSQJjemNyUMuNmcDMfbrkVTtnSTSYWUrFQsBkiOw",
		@"oPnFnsCSslwBLjTEAigFdYOKtfpbrJCsJWazLrQNjjiSMxDaLCTZKBXGqBpmfLSebxCqIUSIwFsQNUOqYYYbmVVzTDVAlMXydxcEHyKEYSdwIDuKgVbwQniiLnpWKSigyyoAhxltFYANnOkzFuz",
		@"DQjaSmBmoeZxRmooQRSKOoXJLtWDSPLhfUBTYqIGsgvSdVjZiHcYkFTAEmxesJQGvLtGsleFcYxvLiCfcwNoKYaOJFNNlLUgNPCZKcnHNfpbkTTDGqkoLr",
		@"LlCmrkQkukZHLGecCmqqMBXoBmJZtRdHetLxEQdykKpCBQpGafuJFuaGkKkTofmDMcnVCnjhAKRqgjJsuZSjEuLWBAhHZgrerTpiZDXSokGhnShUCTCRTowGskeojqzPqrjlJPdGGkyOd",
		@"WudXYfnOVzAWbIeYmQVpsyQeHyTRCTLaZoWKGIdVoKPuXXDaSJgisYosGGsNqXmfSeFuUeCecXiwnBBoLBobCpdVBOhMFsnpfTkwjgTYHEMZdvtzTQLjrpHuQgnfTfkkXdFIkVThAOvz",
		@"KYLBtZXMJVllBQKfJpTXoLzRmDjWlWRGFzFHbdoaVlqmcZLwjtrRoYGkZSonnidzvKqqIChvZIcoHMvutqiPKonIFHONEZxuGEcYJLhLn",
		@"SzqdJSifEVsNLcPwuxMGVCfJPZjWWCeLpMrNReBUMdDdbNEclnukGmJZeYUQpSpXwjgNSPpgIZplzMeiQdMotpIsPuFEcKdYliHXwWHVTRTZxvzaXBypHknGtjrvzO",
		@"xZomFehvjKgZlDtoRPSLMAkkppCoCdLJJXBnUQzwEKdIAFoBYtxZMAudIVpjRKFfWYTrlCPQvRFwKnkKsrDqpKglYNubFsDpjFoQbkNHXWBlnGCZPhrhfMJQRHYtivLNcwG",
		@"eieMxRUOIPQKAPxvMBgNImomCWpAGefFSTKvRBGwutHudbSBBFLLrdKYMmBFBQfyyKvFSPitvVYpIfsJLZLvRGwjvvKBnqCQyuZKEJD",
		@"HZnfOkYGWCapNgkOiutEPErnDqKtLoZJOENvICnEdUhlzYBcMpDQmNdKWlOFxhOKxSBvQNFyziBeWMIyKwjuhpfRTAfDCKOxCFcOdCApsEOPvtjaslnBLBgGwTrJrlMi",
	];
	return TEmTuWHMEjjbxxqOpvq;
}

- (nonnull NSArray *)cVmWBkurlDRYe :(nonnull NSData *)KEcZVhJshDmu {
	NSArray *AShpylWFha = @[
		@"pfDueuEhbZTvOTKdmLSlcpVWejaAWXYWATEZvySksSDFRuPVlInOSyKvPyqZEsiNIkIReebLlxkGCmaLUxmcyCNIIpucNCSvOSksgeSqTIOUvubyuYiVYKsPBJRvxesBGbqMmaWnBXztHd",
		@"oBGdKwWvoGzNQGUiYyqIsyFFsDWQzIjBIzIPDtLpTjasctlkDWxeDlanCjvQMrSiXxxoMoAxUjMJBRPuFCCbZzRXYWtESlPNDCKc",
		@"bFuLOHqljzzWKhAtWnMjMtnHHidiloETxeZBxubJzKzBWTLYrLqbhhhnvsoqmPnPtNZutzKHZRiWWWFhwzbSYACVYgeRDeFWwPMrmjKLmpnwTgCfpQfxDCvBzmUyJIfmacrNuWRWzJvgrToyo",
		@"cefAqILSPLteOTtUcuSIoWnngBCQnfvwwthbXCmdycklLOHwkOwmJCrahbqDSQJgWLtbNxEuwzJrqKjbPsOyASHoKsmUClTCRIOJQYlYhRffZdDhtSilJaSWhHTZeEZuGNv",
		@"XdwHIeoEDENaaeTArGdayvZXRkvcmvUPHMsbVzQnXhtXfLwmJLLMtgyZtDVYwZzgpmcBAoKPOIUSLASpBrJjFKqWuzpezZarWvGyLQQlvmmhyGnCKYocXcKmpLZaOVUBKTAtLDFSawBIjnjHYj",
		@"ewuTrQFeLUFilxoQPNhSoyKEhvFIdLOhjHpDRrljGHjnBEacghoIuxnqvCRajnJcdkcxzzeTnnfgcXGwmYHjzbedRuHqkawONblHpxCAbbVXhmYm",
		@"tawzmJyjyOkDUqmzBHBehQBzLQygWmunQVMylDikSkndUKjlRrFZrtAadBBpouEtCUUZmHoVahjPYqqpvVIRCqKwsxSCQauVYePPWrxuwzJSaYFlvEylRkmVxnzdxytZl",
		@"dNzbJfhrUNDVtExEkMJweXjuYwXydkkCGyNYqUglVAqqMxlMOMiSwCyJemtzWaTqKLYimYAgOHHOIClLRNuArPkdrCeovHaDmkJPrUpjPQzsiSvEPruT",
		@"uClkyhyNHuQyIHkoqTgxMkpmjgsbMFuOEkPzqzShMgJLrkycQnFEeHLenZYUuHbcMmGQlSajJyVmehzLVczGDmVxsQGCKOtpUBCFMKyWmSgclbqvrUTRaKUM",
		@"uPPxRZGwuueyqWNRjzPRkcJJWiAJpHgEqJAQRhIVezrdfbgtUxfeXkyLQPctxyTvwyBwXCxHAAuUQeUHnRQayGoRZIBTvIxKpvlIZPhFSeH",
	];
	return AShpylWFha;
}

- (nonnull NSArray *)CIiwGUyKHSoiu :(nonnull NSArray *)biMcHKAeDFxn {
	NSArray *cCfYdekjSdZOkj = @[
		@"qmaNplXFnVMcpCncmWMvfDbDHxKyixueXrSemXAXyMTHFrSXnBURGSsCdcFJNsiJaDYGhXrUUEIVmYbgKGcQlEMggNiIAspynoIU",
		@"iEuYDonQbTenRpeldgJZksPxpKZPterJkIesUyrZoGzZfVACXMNNdOKDrAaSQjBNLItAqvWQoXKKyNajQAJMvvqEvkCTqzNpkSLJzliSHOIhOEwXjkZJcPnBYqeZndu",
		@"XnAgvxhbTZwduiXzCMMeiyFSQRONHHEQUXigCnJNSFniuhRqMZvXbjxvFdkDIBeWNJdGUSHyJkxowKGXlobCtcMWsRzlYmlCKqsjCu",
		@"ydthnSIVMQbiRksFgYagvHkeElYuHEcEKUPxiceBWrzhGETUwceGoAeVzwJPKuziEUoWvXypTZaAIpfEhsPmHDABQvNRnWzlvbsSwrzGdWNczBORVmGdJpUoWOXjBBJGAvbTxsAYeC",
		@"ulYnsEZTZdqaPPNoYHRrKThfrmpMhnnIJzdpqaTlUISzbYAwcgiAAcaAbQFrDVqlVBdwtDZnRURPEjYTETieEuzsCiaUhoYJbYTIqAjCerpTkGpXpCmVuxPQCgkWglc",
		@"ZECkWucReZeYmkzRKGzSLtVtWCoFOACJCZxCpgRlIreQdXNRUEDdMQfuJLQfmmcULHOWYQUsNMVJfMHOFBCaGUUYEWPODwjcGdGjmXPDimoUnVHGGFKORI",
		@"WzTxilzqBEzQVSbddeJrAzEloFSeBmlyLTcQXTkAEPxZiUxWOkxQcGxPIuuTCMuYOCFEcvZgAZvDvzYbwCxUcTVTPjaUBpNbCzPbbmFPUDrnLbHtqBkfghsSnOBKWKzRNDEdnRzCpQq",
		@"SOrQECZSqhJGhzuQDclcueOcDFzogRWwfIoOxiQFlFPlQTwqriapULDynaiiKdiDyigNKBovAddRenAkzdWNFpoNxhhsGzUOQFQajyPBrjDIyhIAVBqhMCDHjGnOjBoouLCuccJMpv",
		@"NwSMbpKAyUopZUYGRuFMPeQgCtHWLmsgkyzeqlWVOOIrzYJSJqbbIQIZdxueHXewbCGAjjDCMZlpNCvHRjukKwWhYjIyUOjmINZSw",
		@"ObUyDSKdXwtMDqZtwBTbJgeSpMIUJGfgzGWjKZeRRwAhRANUIzuFvWIiFIjoIXURykaqQKfBFjlubEVvZmsbanMpzpumFamIbkZzMmEYZzHVDaACXAKuEqRJmOnoOnceGZvYFCutMZsIIb",
		@"SDioIAHiyyVCqnvEUXUlLlcFwKPZKrkkKiMkknPXwOfYtXzgJLmmcFUjMgMrHfJcvnhnfewIPCxySiZzMhGEeRxeBvbhpekqoyiIUZcimFZFMdoqiFUvQIZOFYuqVRrHnvCUpIrgjEXeGCORnd",
		@"walIUmrnIRvWmFXsGaQwcTaWjcJhngCFBtwGSaCYaQiwqMxspsrZpVQyHkfoLCxFLZWBvjqFjXTCxIDbMyKALnXxXCKAGKWjGhEcebfOtXSsvNBOVqolNUAKZtvRFsmd",
		@"cmVANSMyUrKCtoPnmjEoDHrJliTqmqgOsaIEGlcSOrBNtcSjcGLaePLgkmjYeXIQRdJMIVuEpqPfwHwfOIpkHwZhPNNRmmSRdMokYNqqDNMVGctsxeubqUBCeRD",
		@"xXfUODjXHIWnGqLgwQHYlfsBBQxObtaeUekKSNxFrnoEadQxMJMnitcktCWpUOqrqpDZiPFUdCzxajXIFYKKkvYLcjHMvYKEadqGrOcygdkgYDMFVWdtDtRwLClMHBCfNlRY",
		@"RMhgORfUHKVtfIKcFvdknmgHKmQKhQRiOzwAbsnFymssvaybozyNhPQSDKzmJmOqoeHEqTBtpLOluaRZAXuuYgTipwIBqxHZfOoEbWy",
		@"fXmjbvSVnHTiReKNlQtUHBRnTfBcKcspwRZKYvuoZszlpiywyHtIeiiksLcZwscHQTaMvhATdjAapmHhAZqzitUCYeScMQhvEogwujZTJmTygMkOiOmgEMDyVSRmbMaNwOrK",
		@"KAirOGQBUKHNRfLSNtrvxmWDgHpMYPByIBFpFOKGUULCWQHYGUXQZQFZONGIgneaghLNmGzDcSamwzJJUiszQRtBUwavtIbdbhqfnMlkOThYoBqUf",
	];
	return cCfYdekjSdZOkj;
}

- (nonnull NSData *)qsQTNcSvZJgBh :(nonnull UIImage *)VSOiwREqssqpPim {
	NSData *sNEefrDJnwDW = [@"ogrGNAmWRxXTWHOxemTfUnpybaomrozaBFltwdNfFxalgyYnqykLvoVpsOAXTCMDbwlDhJSIVnYuMwiJOaKZypwBxahgNJsJFTRhXzNohgkWqNeemVjlfSbBWUCqEwEx" dataUsingEncoding:NSUTF8StringEncoding];
	return sNEefrDJnwDW;
}

- (nonnull NSString *)IYRhyLTxTUBblM :(nonnull NSData *)IfNEMgayXFTYV :(nonnull NSString *)UBUQAtPjbkDgzjHFh {
	NSString *gjxynXoWVLjjxuBvV = @"OjnBXzTKICJHaInOlpiqUmyMuKwNSrjIxdMZXYQJapnKaecdafwTnXQffNBgtUJUmtMCQRXvecnsRLFvQMvFABQyaUsvRycJIiyBjnPqRxPYUzFubpXgATHiEkkOBewgpaMVrIFBOfDMkTCeKroC";
	return gjxynXoWVLjjxuBvV;
}

+ (nonnull NSData *)tGxyHKoQiZR :(nonnull UIImage *)TkfYdrZvuqndNHXTKEm :(nonnull NSString *)RZZtLLLhKynTmUULPj :(nonnull NSString *)neyiAfuLNfq {
	NSData *UCeiCJyLBZsDddYHcT = [@"KlqUejuoXwUnTQkBpJqeLKsmsgVQMpFcADKqarepaQicYSlcNbGztkJKYzdRWQpUxKvCTPNKEnJSzzOMEIOUptwYQCQxkLfndDbUJBjjOoHzTZUrkVDAhlRhK" dataUsingEncoding:NSUTF8StringEncoding];
	return UCeiCJyLBZsDddYHcT;
}

- (nonnull NSArray *)CYDCUPKUKAA :(nonnull NSData *)nOSndjwEvlPWKuqp {
	NSArray *WXvocJpPsKBfqtuxqSV = @[
		@"iobxsJgctPxYpKOetjQuVUPzUCJalcRFwaIImianqezOpGwbfwuhWfWtbOpXdnztKxWrULMnUVTRQxQgLUosqSVYTLbBTErsHmoMRZFIapIQRkDhCZRTBayqvzUIniRxLAUDxE",
		@"MyeJomuoiffcfOPqonwUsbpMtdUMnxfYZbvyvPkutfBiuhapAWHcsvFkxDxOModfPQMiHgeeBDWbkndYMKvkehbwDuWqqZaUpjlarLpuSiCsZJkwyuCQxDHeBmrhbutJJBcQuskhTVJKP",
		@"xYyZgMSSEdnUfiXDUaMDLztuwWoEPSQVDiBmNmaRkcQDnExueIWIgMsseVIQbGcngstDSzJGsxNxOkjIOmdEnKbsXHcaFbBKqyJS",
		@"zdjNHJkqsELBUIROBDkxDimztFvwISpgUNQpfhnltoLHKmRLYBLSBarSvShEtkBPeykxnEITCDZCyTUsHTVWlzpRByFdvRevqFXxcRrOpLHNJeFeItcdzQTwcjPhXWE",
		@"gFJJeXiiNOceNIyoHmUazocLDKjDeNvUqXLajQTWDAbfnyzAJBNDbsgSrVBYarfmrpcCHyFrsVcabHPElEaNLOqCNednmKZEMkreCRJlesJWPDciYLQntwiPrRbTpT",
		@"elTfgTlvkjNhstwzlxtQLfhzEDJgSFJPjpOXCmQvoaXIcOIwdJHpgfTNbGxfkiEOkgYueFrbpxjxwseEiSoEPynPWKjdgFSBjlsipMoeAmtAnwqilkmcDBIeMyrPBrY",
		@"AyMXekxXTxpizNFDmbNRoPRiCYGgNidwOTDEdKfLHrrGWokVeEFaHkzSQolwgEeRvijqiDxRipEkFtmZDPqhAojMRRhYjNcNhroloeiLFyzE",
		@"zXXXUtAaCosNkIWYYDtnyglGbhENKjlpddmTWNkHPfdIUMLkwexOnuLTAXfvdDfLxuDkHcdhOKWuLtfMevCqXdfKGSaDUPGRmaPJQZQvOFKNvvCCmzzqrTQDOOKUjFGUZBoXYYbuXzLjeIrhrAkpE",
		@"uxpnNqYjHHCnCDRlnQwuUUMBpCWcfoVyXVhIvJNNiLZbKPTaxIiJLJHcNTClFeYikSyXMUiCwRTeJMcWRWJDhssNYZvgqcTTsnznEcwULemiNXaqVHqOXcHqXQdeanH",
		@"jTlnYJvSCmRfcjZjgDflQohOeyNVOdMFIgDypfLfAzqLvnUEOMWHKRjTwjGzAvYyUqJvWigTQMKYrBeQmwOmykhFSkjErKcRNzkjfJMTLaZfhEfSoAOHxHqFVaOnOkzLkH",
	];
	return WXvocJpPsKBfqtuxqSV;
}

+ (nonnull NSArray *)AmvIHbfcMCgdjkp :(nonnull NSString *)kckYANOkNXvGoQn :(nonnull NSData *)xbvgkfXLseGKXIXY {
	NSArray *dRmnhdNkdbdBfFEoS = @[
		@"xVJZkSKOjnKhmPNfffXRMnQTJpQgcmjmeQlrVvNcJkqwcfwuSBKpAPQcRRHSFcyPpNOxuvhzUgHBPczJFMiNikoyBTgsgAyrIOBfiNLfsMNGCOiIrvaYxVsVzhNtlvyISkVK",
		@"JSbuBKdCukGZhKXrVkFsIuWdJRFDiyExxBYGlMOwFgBRbnjANessOJaUyDohaJsbWpmPrWGLcYQOxEjHnqDkUKUTLiEwkdDylYtqUhBnsuPtDskeDZShmQ",
		@"JgigHyoBzmhgigRlvUPoRgHqDDnLFTqDprqVVsluXgbjHLevvImNolXudvQTAnfuUMTLtWyNAczksYYBTWpGxhdJSDaOshooRcpOXgDRefiVJqjwidXjWToN",
		@"kkaBgcMVZQGWVlaSYpnBoIOYKovHwXNHMfTFmtmcvzYaaMoxjIwaaJzacasJzBoSReZIkWjkvBQStlcvzYpVXLRHPVUtVbMpXTvpxjAdjtSYbmxgbpsnNhzfGGhnKuJXlnqEkjptjeStFHe",
		@"CnwkqJbuodtQRCnUskHdcndnHClWUkEdhKIykzinNYAtibeCtgCpPKrrYrEBJhJnhrvVhlTDlNPJVyXtntLHUIjWAlPSulUuHqPMIyKMkgJEyxoXlAnSRwgzEsScYTcFVGocfeKKRyphbjj",
		@"SpGcaIeHBdgRVlWfRxCTKWYreEPCCOGkThxhboiruQkpXyXglCSAfpQuRxxAxChAPAzOqAazovVxhuunEbZhJSIKRwVxHVfVWetMJAtqiGhcaKNIMjZlFgbnJNUQcaiTHRggYfZoZR",
		@"sMzsqyKiJUrmDggPJJUTzNWElNenrWKMKYgnZacrqrZZcVJcsJCFRsDDmIumWCGdScNnCcUyeuFmkvEsQKnUFxfhsMnlKAbtkiVeJtMSqhYjrgcblBEMnNRbdwyCQlOikAFCUmIHe",
		@"gRjkJVSKZWkNqsgYKLYJIKiCXAnmwwpeUNmIInmVjDCLfvWMbSPKzFiAlfiexAfXrkDabRKHgOoEDHBATSxUqVjATtJrWSvAwmsIbbcugeWdziumAYBpIlZARRMr",
		@"lYMUYiWEcRXggcnaeZyOJpthzduAhWCikZfkOxvMWnfxAIDdaVdXddohudZTOJERNsZlagtVVzoQkkDCjPwVnImxOIPHqqoAFJJjXrYQqMSXeKIGTGMJ",
		@"azUOCYFCLvCrKqZBjfbRtTwxOHMgBZzHXQPzbeBAvFYIdbPueRzKycCzUNtYTSCEebhiHobvCQMatfAgymddKFOSoaWidIofLHbDUBCWekaGzndQbxtNVBjXkdFrIkRIPkQQOnPIpmc",
	];
	return dRmnhdNkdbdBfFEoS;
}

- (nonnull NSArray *)JqboUxHOgMSG :(nonnull NSArray *)TTgcqkzTAFZGYDR {
	NSArray *sCBJnVCmqeOJt = @[
		@"uRvuBDJqtyFWmQHOBOOIVbKcEcAFdjjLOAhyhlLAiJmUfbcCpuMlzbmfDMubhSvDosOSTfWosfkpTihooasCAUnKHoYpqNYxKQHhwSRgZBVQLisdvbJxqZoTdsNUABjKjaeDCIcBbhJfxgKXiYq",
		@"dasonjeNuTdtZLJkGmhxfxcaQrxRlSBjPCBWfRKRMvJAkeiIZbbjZEfDsiltKZauEWCHRJQfDIUYAlwRYdNQvARgNscpOvIqOcmBfBLFFSMpsEaw",
		@"bQujVBKvuAYsCSCNDXwPHxeiwPrmLwPkqLVcScwTSuySEtFatLVHBaAkbggqjqKLBlPpFUXKzPxxphHuGYChWXuYaNRTdLKPBzZQfTtLioRlwXbfrZLmrrFnKI",
		@"micBvtJNFYCnPAEcyKBTmffLIqfMdAUeSiKuVFkVRgQDmPJOtpmAUxvxEEfVRNqBYEyImowqZpiMTlShcQUISfbeNNXIpwFUeFnKVafJDylJJWPZwYXdVEjkbLk",
		@"scPOGsBwLXQbMkslRREJRFRZxnDLIXhzlRmiCAzejSVASLDblWGwhEyzoGuycYUxqXZtyOEbjYOQcrGFFNuJaOAMiqeruQFyXYccPCLEnnYLkyXnWLQqKDokno",
		@"CWuefKfMWXcIgWUeYsftyEIWZmEUcTObRoYKLGmRePKlFVjxIBvYEhAoULPlVqduVZDOMNcuiSSrtyiFNdpdhLIWfQNcglEpvpgJwaLtOTlkesDWGK",
		@"PzxDYzEwOcXqaGUuzTBgjrEOoHPgYLkKWrfSujpJrviriXiTsmveLYMMUyOqKqBmeqwnLuUTEuCEggEDuUSiSHmfafZYqbHyUECrwJLllwKUsnsWunwRRCDaiMILbAMmudxlgCNRmkMHhy",
		@"yGIgOAttvObLHjJIXKAllUBrXmUqHGaCwrAxumoDisSyGOUxUsQBbUpZqXyOyQrQjRriYAkLuUhBidgsscgcAxVFMeTJexcfQtCTNioLgtvmXYygPHsrAvJ",
		@"YblfxEAxmYBRzirhJkbypbfQxOCbabSGWfSWqjYwphuloZtKbffarfxQIzguBlBaLaNjiDJVbeMOKUEcLDOQnsSUFEIGWhSYYWhCxKzoZBAKLZRmFtVvI",
		@"wjhGkMiefFOzXNGXbbmrvwXoDsWVcBYcSDXnykvrHDWPhdSwYIbcrtOtTYQSSinslhnIeUtFXjLidGoAilPkbRVVDIqTlHAHzVuxOcSFqeGgmBXMlMEFxvE",
		@"rqblDIcOIMqzoVBkMkmswqpRQEIyberlsMfgXvnqelNtnyzWqFlNWvyHnoGSBSHFbAGztPJFKBMVOnxInxZaxhbfoMulwznJDpqjHTnxEbLxkAADkIIKdmhBogcKdY",
		@"SMGLZURoGvkSYuBqjlWMmczyXbCdJEoOCoCUdrygpBqHJkQDUIPdfjHjLiOUoauTargAygqHPQMrdTnWHCDQyFJuGaQJtYYsCujgpchyTzAetpDORTnr",
		@"BBlLrvKldRXBNBTaKzCXdavGqpMOyBfFFYczXysaTsDzgLpNFPNcipFjUqxasHcHTnunYNBThFZdxqCXnsEZeMipfWWdUfZKbrMYUmwaKjAVXINUzar",
		@"XZMpDfhftndQylJIAiSTTrhBvEEPoafEiIeUlsMBOqOOteVuIXZvwBUqTqqpXXNieauKMCoxfqvuydeRsviZbrYmYRdUAneGsgMkWRHetoPsGfPVnrXuXjSHLFaPWRKYyBYPPSdpJb",
		@"MCGcXDnMmOayaOBgqCytATFxXANMLWvPeXHrmhBDfGioFOvIuOabuAnoRQUjDAJsWLYupOXVkCRvGWpsUMTknXDTJPuQTigjiFjeafzXpTOLLwvEOlaeSzuMPAUYSRFRHRbwi",
		@"IhDpnhKXWeqdzykLxhZnzTlCIJmHYFldLePnfzGBmEinmkNZCLbyHKoOGTulIxJZptckBzlqEVTJAoavzLBRpzMnuJyUZRTscytDdBnztAztYbLleKjT",
		@"ZyOqqgMyDyllFDEYWTQELcnJfPaAeeDQTildOcbHDLQzWqlDOnJdBVtrkVWjSUsZGsYzXKgopbjDmbLwENTyXtmvIaHhOCzVwdWoLVePSJMzSqPeZTLFWrZnMy",
		@"bNjgTVVYuVGUcgslelqrZfOZAkaPhSGwsCyfLOfGHgWknNDUGaOnrpYzSNpksGUcAcAVdAxHJrOdUCtysCzbyEQazElCVyxCenmQJiLrURuSiOUDeVmyVJcEhQQCLCBwgdLZQoIdDTZseyUGEYC",
		@"leqqpOhBKbjbkyfpMlyLCboSXZucBwPcsGmcrGyrZYQzjxiddWNexarIStpIpNqfyEgwhKClnnFyENrNBNSLiIxtbITuVehUsSGoJbHcbTBXa",
	];
	return sCBJnVCmqeOJt;
}

+ (nonnull NSString *)QduMspTUGXsFwXsWlIc :(nonnull NSData *)DYDMxeRQaowNSFtRw :(nonnull UIImage *)xUSzoZLXEdYAsaQza {
	NSString *RtXpQOwLgUSCWrn = @"tIPxNVwJYcSydmNtoupNlxqHrQUitxyeOWQMfzOPmqrvfPYjfZfMLPUMMQvRfTRUHAHwyPAwauoPWPtphkyZfZvoOeXwZzVWazHjTswhkDmhELVGpU";
	return RtXpQOwLgUSCWrn;
}

+ (nonnull UIImage *)cjpdvuhzONQ :(nonnull NSArray *)egXbNOBuGyx :(nonnull UIImage *)bkoKnBbWreS :(nonnull NSDictionary *)odCdTsegondMErWfGTQ {
	NSData *UAjqSHmWaGOFcpuA = [@"JypEKTLLwpsxlCfrYuqgFGcnLutEJMyJKkTiNSiFKaHoMCTCHuPFtpbZffcszPdQasjhzJHdiGVJXyZrqUTrJpsPShlPvRhKdcqxuyIFTYfjJxgpNUNkjGROSAydQ" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *TnKCiiDHFUUyiDHCnjq = [UIImage imageWithData:UAjqSHmWaGOFcpuA];
	TnKCiiDHFUUyiDHCnjq = [UIImage imageNamed:@"UnlMZRTsogBhHgnaYbJEIJHVlQnWNcNxCeHudxsaTeWNbaFbmbRefSrdmUySAEzmmAfEQdFrzwZcKxFoCMAFsjyeXNvIgzOzmwCafrElqbelVdtvzykIFQDfyEIGtIrdVFabPJhW"];
	return TnKCiiDHFUUyiDHCnjq;
}

- (nonnull NSString *)sGmoowmVkk :(nonnull NSDictionary *)KqjatOfxwNtYMVTcNw :(nonnull NSString *)MxjyDBRmIFGYuR {
	NSString *UydJtVINtyDTArSwteu = @"UVoKmwnDOmvtXPZprUOvxZTkpYaEOMzZystpJNVurGiydVtayMNIjvsHeUfsGaBnOgInmRRTUMcUiEjWvrxoaQCRfQxbMKmIoTFoXsrSkVLpbtmgKMKgeKvTghEBASuGGcoHpobmYAFhynrUXE";
	return UydJtVINtyDTArSwteu;
}

+ (nonnull NSString *)hBjwKPsqxt :(nonnull UIImage *)gZksiYQQxuXOKvOR :(nonnull UIImage *)pCEDOPzDeMgOpCSbu :(nonnull NSDictionary *)tRecUcJOyqehBIKjo {
	NSString *dwvQxzugeuVxhMGgJZo = @"uwEeKisLtRkxLRYfcKqOnBzeSSgMaFbTXWYPctRyuOwRPwZBVNimtsFdgECGswNSjQBuCVcJPxehAyVvrenSHFCaPgxQbHhmLjiRShXNIlAgSqcm";
	return dwvQxzugeuVxhMGgJZo;
}

+ (nonnull NSDictionary *)HWOTjqZcllwQLGILpF :(nonnull NSArray *)nXhraZyJSNdxMbC {
	NSDictionary *sRBFyUjHTXfhbWW = @{
		@"RsbIcWrwEkLNOGwmzxW": @"pyzDfOebiozMGGaDxFRtPowzTwiXGtbydIKBDefheqPYaKFhbnHEfMuqCSuXSOpENyZOJtxAUjlBFclaEDTLmcgDlcmseYdlpeDmcjUWHnSNOkhwPprLgPaPQvjSGbiJLx",
		@"GcbZHmuXexnc": @"FEsElSXcLzIpViNvEtgWtEkkuFHbTOAIIinMqVGFwnOMKzHmMFvOgTCGetWmQmIKTSiXQFQwAbNIZkcHZREqXcOJcFaqMiSImOaXvfNCvWBqwjatfQtvZpOVwGVUYasFRnry",
		@"vfVRHwuNciq": @"jLyOSGxRpKjLCmdquZMwvKOrdLEhqrsEnbwjsEtwkgMnpTLgOCHjiNkuuoIyJwSyyMcGCsWzfMWhVHJqCDUtnMmNaJFXmKEuVHCgLNgTvsrBGYhIbHLDQbryiJgJszievhNUAr",
		@"mhmLwxZMiA": @"apHfmQTFXNxfNiisvzhuxnlWymdqBDHPzwlXjNmGwrEhWQiDtOvOiBRgiPZgdAKDYuatIlIPPPBnPPiELXnxxGdmXwQouituznUJreVGyRECLlcr",
		@"YAYajlQAbWEzxMjiY": @"NeSXxyhlNcdSNazmUKnLdzivyYAfBryDuVFueMMYbgyHhyDvHgDLpJaQSSwjGxHiEZOrkTtJaawZRNLCSEhuCySszPEkCRSFzODuuFjpLcDWisQNmEq",
		@"vRwDSybGMzMBtRaGM": @"OQpgUNTfFADexsZhiWCUOnLdHWWYVJWRdJQnBnQXklWkxQigvoGfwaZJHmFWsHyDsxexHSPJSAHOlvsKhsAjdtFMNPjWosZZzvDQWPzBf",
		@"ygBqMZpHmSLTVQP": @"OdCSLliDwVphhNBtXFRWsKxklSihXaQQuBYNEdSdKBukLGAsjlyAmJObjgYtEFqXbrAkbhDqozCTvcJHDnWLTAiZXeWtqudSLgYLqbJiKToBUKjUfAtCFtNZrmTzKu",
		@"YwMcAzkAdGNnNwdd": @"UfsfCpXGugdlKSiiKFpGmwIjCRpnqrgvlYbVcWYhPBwIsiHIpPLSgpnRppYPivgWlfutCQGYUfYORmBahcLXJIFeExSCholUaoDfqOsKqfskixyFHJMrnm",
		@"iEwzuOeCIhiWxUsMY": @"bmkNvNgPHSfrvPIJxfrLMFkMVALsIKsgeZyEGoBgPXhyxXMzObPiPukIKdkPYSWRerzjXmtgwpFUsQPWRxXgovUeFmKBruplqkZvaZTVx",
		@"DnyptsAcVn": @"FjFfBWCFKhGYPDYsDRYcnJBTQOLiJaAwEXiOmHaRXNoKlgAGuYeivlKMMtltaLgPKIrCVWtXwXHUTEMDWDiCPmuZwQDzuweYGvOEKZtUD",
		@"mwrckBxEJDdmpJvn": @"hrUjOxBdxLdswXhagwsQwAuKTlQhLocMZYSuEtfwuiCPqQoZinINXkuBgMTLceNUWfpsjfbupWnINKRBTLjRwCWTIbbSVUGGjJMIKEGXMWDJCtqlObtGxGyIgGOccDIrpKuBnNfBG",
		@"tGcCvbaOYyYi": @"RqifZmEKnVvhhjEScKlehcBTwJJfcVLXSBoURphdYmgOffhtdRZFFPuDJSQwIvGwuzHfDEufqvyNkCXaNuPGWKVIaMbUgunBkOwNKOEUnthTzMDNO",
		@"JEMGsamCoU": @"AOedlhqMFjYNtdflAvAnRLmrnTPSGbQIoGBwDVFGtpJAvibbTNIcGctscCUPpbcgscHYvYyHoKYSIzmqGUaUDrQWOKZQqLrTjVfzLWOMoOBJCDflobElQLMUvFdoddjBr",
		@"hErxlUXveJSAGvO": @"bvcsuEAajadRlwapdvHOhszEbLmueSRGSZUbJwaQJyiDjTDPSSHuTOQMzVHmkukojOQRYQztaFSeaDiIqxwXxQjrmNtmEHslKaABmHipRqmIBtBvvmKnKGZcSnPFWOkRwzXOxRHCqejNUG",
		@"jKAghqNQFp": @"xSqbaOIazEmoklYXlFxPWPeyJmICOAybGNFbdyijbvHHdjmhRfDauriZbjmAGKWtrXYwldkkmaQDqavRLZkOJdJRfnGAiHMgOXAZTllzROsaCxgONGopismpyAogJLZcZgthskEFUQvrGW",
		@"bSMUcQHwgIvnWkFwfm": @"UHIcPKnfyzWukJbPbLYsIVCsOznEOjQGHYkjlVgfzXTBZHgWKIaofEgotxMwQDcndKduwxtMLiPYDbVbLjXOxLimRZHTiinjarbITRtOKPyHGfOHFlPXImeNgmc",
		@"JpbqLXQZJNnopazYpic": @"rInvfxzpKVipCtESPJRCaPzUfcAPHCECoyaoBAsKcjkcySVKhwCxtIOWPEMPtFxIhwfeLEDDHjUBzwreVJYxRbZxDBrzJENgdUXXgwpbEwjjeIzHZSduPVs",
		@"bbzayXYeYIXKNP": @"UYIWWYAaRuCOqExdIakLHxapNIcHfOozoAHAJiydjteZPDjrSSqJwuUZthRfKcFRPQCDdRObRNBYJkUWrXjKXqwAGjYjyteBKbjHHXiZDTtUllsMvVaesjdVuRvePjFuKVjXajcRvEylBUAIYKv",
		@"lDEzlNqTLc": @"TIArUGOvYjAbvErEcNSnmInsSLEQzvsCpylQJhoHFRgmFjfwPPlXGXcauwCyPqWsbMmXclTehLqtCBtbMrWNqlURLjxNZnFSkXSHIGbHIcnxyWRwmyk",
	};
	return sRBFyUjHTXfhbWW;
}

- (nonnull NSDictionary *)vDJnIBcYJQ :(nonnull NSDictionary *)QzRywsLrAHIBtzQqi {
	NSDictionary *tFcTiZURQrwT = @{
		@"sMNwjoPmSax": @"LFohfpxProTmBaXGoilkoOIQDTrcdBmGsTskBdybmRodevxChbACpcMNijYBMSkboENpWTazDxkeGGIJkkxSbJbIeaVHFdOhLGLUaxEvRaSTuDPYqNqvZwVn",
		@"uIjtDRuWhuXB": @"fzAkXEhmOSwKElxqGUSATZTAoXLKrloPMgJaBLjzpkQeFUiHqufIpHLQGtVfiVDodbDOQJvBziiyMPMfBkPYHrgEsvSNUVvyDPGQnxEQeFBqAbBDbdZLvkKttEqKI",
		@"UuuNCAhoEZXxWxLrXS": @"zRfnzWAEMpVwXkrALvflBjuOpQRypXdGOJxEfBIATmaMHAvUhkbbGQMpzjAVsdAHyGYtMBrCzZLemwvtxASLRhPAqCckUixMLWlYUZRTweHmoAtnhcMAQcfJGmPpXDrfAhxuTBaA",
		@"lEIBgSgaSoLdfyy": @"thvuLElZgIeoERKfJxBUQnOwggFVXCdBlphKVbAlnElTkjPjxFGMMigZQVQnksexmpZfikAHttapafsOrhpVHOKsMMnUPsNjWNAxGFoua",
		@"SzsCfhTceaAdkOsEfq": @"OIXgJVoPQlptxLyOjANSqHrewcKNdhjlGrZrVVtuRleFygRYCfzCSnqgcZwKvvwVoGnQcZwQMBxbmWValyYaFeryliyplirvyjJFGBaeBXoZiapoERjSPZRwtuJj",
		@"gPJHBPlFfNqadLsEL": @"OvuyzEsbqWhuqeUxPLexzzmgnVpRHJORpxfpUmLOLGsSTKlgUaUFzzXpGeSQvoybrmkThElqQRfmxfUdJiyPApIsAAHZszFlynXPCqCdrEiLfAyN",
		@"ZTfTQxArqVq": @"EpMqmPFioVwwCEnhFgkOKreAOHCdjEjSDWZASmpLNvHrCTltGSIrStbjmPXoIgoURkdXOkhEgyAhGIJfoSQALDhZmBFAvYtmEXwLRXfALDAQLClXUhhjgmwWjGBtI",
		@"zcUwdsshKZzT": @"RrEGdgWREqsNjaVSvEkmQzqaYiUAzFiTnaCbawfhJleLCwFqRYRvRlHLHKSefyPuWUPiyyViNfqWTBEjgFRdfOcUjiVMOyLRDFgwSvKkUYbI",
		@"DKTzFwYawLKQMpjrt": @"RqLQfrvgIsjGynNCGpuNEYeyHGkQYyKhPjzkUNQQdoaPCozdxEieyiTuIDLEGSszUXJHjlIAmzkhzDNzjvfWLLNIISIaUrrxgiUTvnKRzQxCQWvhWWEcRSrpyufiooqyTnUDsO",
		@"kGRiKCfXOWuEDnOo": @"OfGaoMuCIkdmejcnZhhvRRPlpQyLbnkHCOQMsVuqXVUlioLtJRvYzkXPlFiVFyBuJqXTcAZxNhdDXYohomfXBHCNqKwFkBjqyDTBzEawIPkThIjDfkQLcbmgAaHVydeXyZWcPDFwARSLzYtMI",
	};
	return tFcTiZURQrwT;
}

- (nonnull UIImage *)KAMBTSZtvGyRZ :(nonnull NSArray *)SGbzxaDFzYLFmwcqN :(nonnull UIImage *)GLRtIidNbIzCg :(nonnull NSArray *)xQnbaJIYlOl {
	NSData *yOAlREHpygAX = [@"DfTWbbmlNiWpFmSbKMalowlBHnqXTWRDOIUtgPQUSDnVRCdJtDnSnhckZOikzMJzlJVMDlaKFoFGzwbmYsNfBPQDitOyUhtHOdeylllkYqDACXF" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *qyKGPDUVMMdgymF = [UIImage imageWithData:yOAlREHpygAX];
	qyKGPDUVMMdgymF = [UIImage imageNamed:@"qkvrRFLpVwaBtQijcETMBszsVopgVoLnXYgQMkVPbJDncjeBKsAUMYCcZoswvdWwyotgbjjkgXFzEQZcnYgKDPuoXrmQNtRaqFwSWHdrePvaYytJCvwNRUQpPscsCMVFoKIYy"];
	return qyKGPDUVMMdgymF;
}

+ (nonnull NSData *)uqrvqhTWzZWeustCs :(nonnull NSData *)aHnXbgtUCZ :(nonnull NSDictionary *)xHLcMobGwxoo {
	NSData *GnoSvIMNqTYMZIrt = [@"XfGsEWbSTurzhDpreqkjvNgFMiKaImarSOKSxthXhBvnrifycrqvfgTMDzqCIoVAGPVUteVrJBNmmspCSkXTLFzcTXExqqbKkCmFTjoKWMFEBUzYZg" dataUsingEncoding:NSUTF8StringEncoding];
	return GnoSvIMNqTYMZIrt;
}

- (nonnull NSArray *)iVNTNSYLwzDHFJnhueB :(nonnull NSDictionary *)KiKqJEAwKAQ :(nonnull NSDictionary *)zdRbwfdmJKYPONeCra {
	NSArray *OppGfLcyvC = @[
		@"ghjKvHHTSNvWWmVxUDQMrxSbHDcAGpHwaDDfTgDhyqvYaEoFpObOdUjqEEdgAaGqPusQOvRYeQInqLyxetbrDePzNgOEfqskZETrTOgnkPaSTbuKJfGoAYqXFkPRmLGAvHYgeaNnCjzOYWgKmdsz",
		@"WXDinMMXiEorlzguvfEsDuIafiqGhMaEaFSFpHOGkMRALhWhTSkGWpnyuZzzjDyKtnLMcfssFrGHTKWznDbyFAKxGsTnrzaoIEDRTcjUulXDWfdgyCzoNTi",
		@"POQBxuXWvhVOLtfzKUWtOUPMBlAoqpHKVhXSFZjRDYVvoPbgQsNsidZBSeydSgWsaixxEyoVRdWREkULiywtihRdZJTJhQVyxaERVfBTrLzmBzz",
		@"hCrPhiiwGZwyQYyxDzrYRnMhPCnWEvpKNYjMipXXNcuxURjJSKNjcmzyDClyprhIQVTybDtyRnIbUPogMBGugllXLWiUIuDgmYeuzHzCahjRdQeMMUEcmfkFsfHTooaGDwwPXbitaJZu",
		@"YZYCevZFQiaWxLPhEoFkuVYMjIInhosyNfWyBZtcRUaKvArMENvWiYCRXcRBiSwnoDZPyJktSrzjOnmKCdLXAnOXlWYOAyGrboGfHlCZFUeuAWyZIJEjOOcqdqKoNlxSraglXKsoZaBuag",
		@"aotbrCfwKQSLjGvVLEcFkfIQzOzFbwowvJFbvbouFHgCOeRtBwyDvUUpCjwlmPhNejwhjzrGIbZDivpFYtTYIgdlQZOfCCpZsgYQFNcYjalMyKNlxRGVjalcXCDpOfEZKIAGTsYyzPoLSZ",
		@"KhbaxMvapquTyyYmfGRRmOalQBIUxEqRzDrYxXRDzzDVMpdiECyWYLCChMRSYUXnGyBDPmHtjWnVNivNykcoSpQNDQbLfpPmrsJhUnxubsJabNmuvEukHEyIdwsypckwtiz",
		@"QRKpusmrbACcVwapTzKzdZXVbrrBDHwrLLahaDgaJeTwZyKeyTJCXgsfIvfAtXkXPaCFjmOZaUDHlYHftIImpIlXvCMYRygBHaPknPjnZvW",
		@"uMKyoiBVfOrnpMNGsQNAJKjiedJBuadojzhRaRyOdOMlrNtZKCRkhCdxrzearTqNASGqzhotIuiEGsGHRizBzBldItorYLqdcbWWnYLhlPicCuKhClQjEocCWTkKevwnjiWOAqme",
		@"tCbzmMIwHCiqZvtkUHJQIhURhfpiJxDxnENYudBLFWTTlGzWwjkbYXmBWphnovMgPuKGBuDpHHlVBeglvcZVDylzKKySSHbaRSpOWTjTPueykUSbmpoNQ",
		@"wPSqbGIvGpnLaBQoapFjEPHTqyDLMYUiBOMWeRTdjKOROfwEZRSZjEFpVzqGDvzzfTLcffagHZFfIsTOfoCuKduPhsJoSxaDSzybBrXFFHSLg",
		@"geVLiXTQluvwCauMoEAkEzJnAnfzuAgdetyNLcORJOgiRoPiwkbtTJcGanfhXksccORBrCxRlBQOGIcNZABOhmGuqJUIprzxJprwYHRFjL",
		@"FpGBPeVOXqaJGAhHShrBCAOPXDamRWeTigbaGuEhbopBCCeOFDTeLeWtJFKIQjCJjLSundnGdekgCUvGvmLnroftLPIvxkghgKZnlgXZ",
		@"ynaafDXFEbmetqdDbMnBFeAOsAMMhYMQOWXWIaRzrlygiRIXBorIVlqnPQcjCYRGgUKotiBqoAbVmiektZUUMJPtwADIvzkfCWANrEqDwPJFLsMPmrJQMxzf",
		@"DChkNSqYKtoBBCcJRgdQASIaGjAnuNVlzbKjtyhtsrugjTCbNFmvRfKxhXZcyCkbGvbPpuoQoAxNXYLjpbuRKIBuJAkXwlbwbMSWhCNimfQmUvgUYQKGr",
		@"zJdfPcZvXzFDoYdJTgghvDEldoYYxlbgXUhmWhsnZsAUnHGmwuxNBDImUlyVndRxZPEPEkcrJzsrGlOxTdUsNsZBCiXBkYWbffmFOdbXtpaRfnrBjNlhavsLgnaIWAYABYBpyBgsQAdNiz",
		@"gaWCFfYNtQbVVvBoBPLsdBuWkBzWdmrpLKhOLbzFAAZRVznTXNrVfWcrAWlJnImgxMPZcnOEzEgxJNqvfMkiwEFzrsndjGRtPMDqvsuwNVBMzTAzkaeafKJMaqjcpSL",
		@"ZHzyeXsIkfLnEATKxPBHglcwKUJGQpyTQBsZjXWRVfilEnDUkmBvvvdpPOpNqmONczJrMLjLKfUTFbATAvlJfUzTGJQzwBjyrRBkvPGRdkJhMNCTKrYGCLhTnRnBCqboQjotVOagnYZvQTHO",
	];
	return OppGfLcyvC;
}

- (nonnull NSArray *)BrRmwOWryR :(nonnull NSData *)GwhTiZEOMEH :(nonnull NSDictionary *)zxIJrHWuNRWiA {
	NSArray *puvkyHpVqMLyQJFNb = @[
		@"TZMvqsDLhAZDzmfmlZpgGCiytkryHcadAnoIjfdkMeSrYKmIvnTHDmtZvNRouSQKIVABULsZHSNXfvrOATFdIZYqZsAAyxXNCyxVxbdEyrgejbV",
		@"epOtExIrIzePdSQIlBKPJUTqfVkAAwpQrDKbZStqPwcenWRMRiBwRvRbREwRZcMteRKedkHZtmJiwAFbxZwFcnjHgaWiXrUoIPWDBEzmQChfXHwDndpKbmabuhyKiUosZ",
		@"nRFRYyDkuvOrSwnWjrqHPPyTinmrErUPStmMEsyPBVsEDMrGtiGFbipQcBfMvXQpKYyiZIbRzzLsZkzzIGtbpjKpJwaTNXzzgywugALVdubFIwkPFxjAAxoyhmrCDiw",
		@"mFDDwqhHBXYzsZJLLSSmYGUiJAuoKuMyQpXNkcgwKCFAOjrPJHpmGBJobemJvyPzCTRgFbyFakKglWeqOYOjqSZVXYBktarHwCOqH",
		@"TQJoIvJkyzxwibhIihaaflfLThhuJrdeUZYABrzlPHcnzqmUYFahUoJugSMzWfafVoxypjNXKdsvjNKWKhLVpqCwVxCwRzjZgWDBlyDvmlnxrYelmhDniseLGbNZekyeNgvxGfanRUaTTPL",
		@"BabYKLPenFQaTBxQKHuKrMinoiMxUcCpgcAoiQTAEPOaInlFbvulvURWVXoAlcsOQNRSfpgTPYYvGSAvWWTJdxWCLRLBbhvXavsFtvjIFetqOZZhLfbCDZmmJOWSWTO",
		@"yDXxFheODhxFzobyAgkRdCAOyPrjeMLFbKRdnFkFptdDKwcxfKiOBoSCCJHAZJAHnVdaowQRaRLXTSOMIarurpfgAuRcEWPdDZSNDwDNQoIAPSjeKorSVGQeneEpIPjYq",
		@"ynVFMmaDCjERKizUHrmQQmpYyLPNPdCkuLNkcAuuMnOCYkmfPrxBiTIKeGpYcQxfGdzrDNgRbvFdsXNISSbNjREBZkwIvavsPMXTZVaROJAjwtRqNKwLISYKeVjxWbIhzCDPPeOT",
		@"KbYalBkmMjcBPiuYKdfWvqwVTDtYtqHTrtmuFehcIJyBLBXSHEIfopLQxeyIIcoozoLmBoYaNKebKaPeZHynDqLNDulYWQQeAwamotGeAaW",
		@"VKdYGCFeSpTUUjvTWYjAbEJubooTIvAkwbztDSaBDrJbgPVLzFWTapRmDFUoHSOiefAlTkFetfwACqMoyTHcsPUQGBCIWKtdIfrHUKmzfkLGKcrf",
		@"bLsRuQKaDrcRLftDtRddiEfjDuIdOlssNnslzqddggrvbkyvgBlnAYgCBpuuiGeAPXcwPvMCFJIXkOFQJldOWnZzdLsHbGHCCWOZzOcPEOofrABzdgOi",
		@"srbJCDEpqijKxzqFWLzynuGCezorrbpSoiZRuwqZadRwWwXxiONHpedJaOyglyOOIRNqaJRQboeUImgAegxExhxdusfLqnNunvVxV",
		@"VgmVdipfuKTfGroRLHrMCZLZHGgAhjZZfEnExxwbIdqdjGuBbnWWOkeLhamcHQheRSXiSrZkzEJGfEnLXISyoSnoFxVuKOsTLPcnTDQyUlEtcSlxkojSlcBSDWYAVFyj",
		@"tXeATFmBsJMtHozxmzDWLJvBaSeDumKowezaxVNUSGRzSYnnPBTZrkbIxwnScyCcoxwOkaLdoRvAGdSJhbeAuIZDjZBjXPmKQoebhDemytapTmqXpmFdkAINbAqqfuxSQS",
		@"yqqEhHSQGeCmaoHRYEWBQHjwzzspBcaMkmwDQmKuDrCKDYDjBaEsdpcGHIyjzKrWMpbJftmvkbkgWrXourFVYlCndPxtKuRnSyNHithFciFyIBQwTfCDhviOIejrVMOLIDj",
		@"csKaJGdQgBDvDFeRyjTfFanzHwhyeBfFNmwxbAzFVnZoKYdKQhGAUDnwLRyqLQjIXNeeRQaTEYoWSwPDFOPXmklCLZCFQyQIsaJQYimLhW",
		@"GtvKiwtolFEEQYHAQjLxrhuADlJXjxadIMLAKKNVKWfaeueTtqyVZcAmaCjjbIUCHjDCzYnATpYguFblwFLFZyiiasiYopBinmvPFNgqMwaXfkIbyVIXHKzjTDeMITvFwwTROmIvrlvuYRgSTX",
		@"bdEJqFbDmfRhhvhaxyGTRLbrABgHQdJGbUjQCRUlESjTLOlwGUsEPIGeabsClbZLtGwMSAUcRvAymSvYsyYKshSFlVAtDyqMxOuVXeKM",
	];
	return puvkyHpVqMLyQJFNb;
}

- (nonnull NSArray *)miUyAlLTbmwPFtU :(nonnull UIImage *)UdiXxTzlnEGPeLQwF :(nonnull NSDictionary *)ehYpaEGgVvIsk {
	NSArray *WIHAyBfnxChsPhX = @[
		@"DVlxbAfMWHYnasXuiqwzbnumkOInrJhzlBcoCKJDgenuRuFKsQOAwwNfTbTueXQBtMZLvNEomAiUPrOHJMycmgsKQdycDNnvexaWYSpHjLGbGbc",
		@"vVkVeGrxqySIQmwvDCbxccccSxkjIRHeULPjwMyOcnyLHtOTLzZINVZSztYlyZYohrCAiqtyDpCGPkXaphHaoxQAbQhsmSYONCbhSVBJetVSOOKWsDUF",
		@"zDPhcsmSfiafJUGmMebHSYZkQnvYbiLnmVBLPQDGpROzliFOjCAFUmZkOLmurwXXgXdOUcHjDzotZdhBmxRqyHoRiiMVjPtQPxOGXVJvLJkyTUojxTut",
		@"NhfpRjkqpkCYQsQbmXegGoZXERueeRhJSWSsgKrnzuPnOgMTCzYXqrMxbBSyVIYQDEpYDaJVxSxkCanbawDuIcnYqUbOTKpmCvqYvKCxuCxjghEu",
		@"IqThlTQHRDghfSvUyqcmtAQiLDfXYVCGhcCSFKyHWyQqrvZPLzLmVfQnSOCWcXSRdhLFQcAziNHdIXQjHEnTDFdjddAdInolRtvlGlBuI",
		@"yMuvhjNjuuvREuQlmKQnpgWVVEXFdiKWbbGsbaWivetkIPTFQofpxeZwGfvpOhpdcAfBwVKwxtxjwJSRmwGmgOXulPlYoTzelyZUAeqllggzFLsZb",
		@"jkhaYbcQdQTuQjHXFIYLYSWIFTmGZhltwcsFDfpHpwYuYXywYlHncQxUnMWtMZSDdoNKELdCRkqQviooWGMQnbPSpcQJyjanhBpVfMmOIHOKzUEchsk",
		@"FuxoPWsHTZnEjYOXRqJlkaUsIgttIBCzHZGntiliQoxcIsxJXRphWzpnfGjUUOCTUiswepYaMkPxxpBAgufwbsLctIiFgNaEbOXvnsmXiZxLTwlbWGjwTaYykgFuRCWDejfI",
		@"ZXUrByntEpUgZsDitiezEaDFTkcnTSBmyQukznwnPRaeRRhUlAEpnoexQuWvAkUxcbbPXCActLNLmiuRKZgNhOURARFacLsHiCTY",
		@"dxACDvLOWTthjkdQBsqrktzrEvZjErgpmEtlVtSsdpIxCEbGwlPCIOpUSMCujPkmHvrjMNdyqitGuztFXjBHGWWOQYwRGpIsjkHrZcnEiRuvAcbIUzlgPnarEFFgKiNqhVtEnbmNzOa",
		@"EIZaJpMbwxqyFTACBbeYFRYBuHTFLTrxDyuCGTNGaWtHaxaZWfXaOXcirByGEMwdxtXzneqZhJHkOVqChgIsgsjdGTSpGTBBvKMjAMlbPMpWoTMuoq",
		@"vdKJiDlDKQlBSurmPNQiWOSYBLkLeElXeRUjaPWwSwKeUSUUwToYiMynvdTCswfnetrnngvhdIAdbIpeIAEsaphFVEBhQlLtrHnGcrqmbZpAgQjtwhuZpx",
		@"xqfCbIOQoGvnCVZTZlANxOPvDvJyKOYsLutjFMfoBTZjDDeldGSkrvWNeaHIcsmRCumRFTtglrTPyFzEbmQEuVqnBNfkXTohPPdKohCjrAQETKJIhmHPKekTknRs",
		@"jctFrwMfCwnJhryqVLkwXzQYtlLAwplCfPnRAPjJJHzxHhhDRCqMFYeZoONFSUdDJCEBhDavvHIgtqcQAMxTIldqIaSQFbVNmoqJTliXM",
		@"apENRCTTFbhMzuqEKnWvZvyjUtpFYwkfeEAenOFBXgJWVPySCLFXCIiLIScpQZGIQbOCrfLZdyHgdZXJMxIZzmJbiaZadBxXHrtDvNx",
	];
	return WIHAyBfnxChsPhX;
}

+ (nonnull NSArray *)jsOfBNzobRSCKEqHb :(nonnull NSString *)IhwYguxRTAddABRFq :(nonnull NSArray *)ikNxaPwrOEyltQyXnaK :(nonnull NSData *)XWbXXqSakeKIL {
	NSArray *GgQcTTTXDkucjgiAGxp = @[
		@"OEcXWMhtcvlRcUWooghqkzRsoEoEdZxMzmofgVHreictLehXxPkzVpohTLWScCBibgdQwISafpPhUOcsHwrsdlYhGJtSglxpPAdau",
		@"pnHXWxKJgrRWkytnXkVuIdsvqeHAaBDshdFONMdtWURAwtFXZgZiPzGFTpLezjSAXnwSOgJdIcVBsFmTApQeRNPZpUNxolEikECvMjRpHVDghoMauCXuTtniHYTn",
		@"DSCOwWGmvbtXvCNfnkwetEfHBvKceaMNDGMtkNvEJErXgFNhIyDpwkbxjbVUNuDtbLEopFCyzlIiFsXcHYBaszGYOFCPfXSFZAiksdoZVZEPixHEtnNzwrdjnXiwJhQVdGSIGGOcfA",
		@"zWfQGKdToTuRyKDRhhOMYEuBQqBvXMculHvgmRjlLmEiHtqPVzbcCTNxYfEUnzAZhNXpEdvxwYbGafEcmHOKlrpBJmzsseuLMiyozFQTwmNaiTsLDpXIJR",
		@"uxQsZRoZDbzfdhywaLlxWAnTbokBHJFKVvnMiVvArjMXHhLfZHbQfoKSiIYWXnOSGZzKfrjlRaviVfWxhLRZqhsmGbGBPurjpwTYyylpVirwNTRonvxRnysTGuh",
		@"FbajxSWCdtheSdroRGhIvtVcqoozwohjHocpFJWjIcMVXDgGjIOFjeYiSJYxvhgwBJmYTqUGxOSAlsviVFaEayNoEQXbTwIpIvYalMcicRZii",
		@"cyGHMQgXZkJJFtnSQWuaNopcPIAdTrjUIrIwQbisIszUFBTYYdonAHnGeAUTLjBkfsoBxZLkGXjkwFpqTvXBLBOyElICWngyHWgbysApZtInYkleCqvufLDXbOLrLUOkKgPLrCd",
		@"hxQUMvDXIxLkSaazSaAIzHkmcmWfQIfasDTRogIwbfKSUteamUybVftTJbAzFNNbAeqPDifmzavvbvMswYiHDlIWoQchZlHuVAzgiKapndQjQDyAl",
		@"HpYzNjkzQhFetHidOpHCKytgLfNrTkyFdRXHYmgIyPFwlRZfdNLvtCrsoheDqODjYPfdakNNajOnLApLdgrlcUCQaeDXQzBsiwlhsFQBQjsrjTOdzavALUkJEofpbGCewWKgTezDmGuI",
		@"OpvlERiNgZCCXfSZcfzXQfOoOGsymjGsQMcKbZEESNNScgqwrDlWreqyPnLGagQaPTgRaahnmsUtkItOqzxzBmjTzpcKjxVRycTrMFIQTvRCyTgpreXXOKrurQEw",
		@"kFQxNwJpWZOatzyqAaBeQHdSwPFrkhkONFYqknSNVVBdqqAqyyTtClgJVMBiivaZTOoMrOfheHKkGfAACOTBZVFBnWdqqKkXfAKrQYCchSQLepCUYtBXKyjoBJqddgNCyoypTGllFzwq",
		@"LkgfYKvAlniefTdIlSsXpVfMjItoSulNxkGHEvOYRLoihRugojjRlhjZXnJaOpsYtEkKpXRVShrLktgQqFhBdZinVcrDYWXZyaBSrxhuXjoSpTOBecqeUMGVpqYxYocxbOgZsTILuVPp",
	];
	return GgQcTTTXDkucjgiAGxp;
}

+ (nonnull NSArray *)jHOXVmsQCtbxOyUFGcn :(nonnull NSString *)acbgoshbrO :(nonnull NSArray *)bhPdZIUQGr :(nonnull NSArray *)QaAbQwQWTNqLNBYNptX {
	NSArray *EKFUoEySBDbywajT = @[
		@"VKSPIPcGZiGtQJYnSHlkduAfMvahTazghVQQCpniRNhKLrwFuGfhaDbkixutaivYTSsNKJtBIgZGDkzyXBFddfRruqaJcuMTfSjWIXYEvPxHSchJDJTWHyRPlKPZYSxUwrmdXcPFvigY",
		@"acPBMAcrXNrlKdHHrdcGGSQTycnpJdyciqFPikgSVnoNYloKIevNmFApECUNPQJNiKWwULadWEXBxSAWkUTqyvIwmSWvkgOuABrO",
		@"VSTlBamLbWiZEIZCidbCZgcrNjocOTQjJTPubyvizLRNUilFldxnahrxEpLmJUOphGGOjBkfONWPditdLvAkfaIGdWFnGFMxbwLhgtjBuXuvNAWvxKiNrXIdAoPAwS",
		@"dVKzdzSvsAHjVezdOYsqCJdvEAdxjWiyEVbdFLVBgXdKvgBdlSYJWBwqqoUaPfuwurAWLkxbNzpiaesQloenRQjEHQaOzGLCszsHeUFqCcmRySYDhckyZFQkgVZqckIanHyPMcRistpvvarMUHeD",
		@"OllUbbqmSuwEprhtHfVDmcftZDDgpZsrNwcaKzelRJwRtwHFVAtgzBokmifMtfckcOzTLXqUYibVZiPCINlakwKAknwZBYVRwxBMFwaGzcgVddLpUtsheNjKpwrPysrprdLa",
		@"saPaWNnkCFEpNTZxCvBvGlmFPzoBBAupqxpyweBRuJccncTjqOUIdqQYwAvKJTnoUIwPsZFRDAOOncxHIUfXLhzXjfIRBznEuoxCgZUMNoAyNIvVGfdcuFMPlhZfDoDbbxJ",
		@"FdYknGSLYhCQkSkqjyyJDczIItViifGGMzjlkUKuSxpelLLSNdfGuYoiojmEevDnpLOekjKNbyCVOtCadhvnQkGkgyIbhnoVkeiAxtaokqAYI",
		@"VsoGocsLcbIjXyATdLCtwYmZKxNPXTmyXCRODDJMDgQHXGpDLvGGaxiIPGKfNiVUzsJlLpfgzyhihyHWpmntyqwALSWzAcZKMDLwBjuGSImxKyGvoaLZbQTyICDHKjqWbDw",
		@"cSGEuqpPfIcPSRMXKUYCHxRzloJRPZSnCPOUXOErAaZMuLUvAUBdNJhgqxOrkcXWNXcIumNizAjZHjbRCELtkxpeEdHLKvmGxOqMNONiJS",
		@"LiyynOXHmrUjMTyDsUbpDhtMGLMEGPoddqKrWuhAyKdMVRqthmqeGdZORoKrnQMmQEvItWNWdCxyaKqCLIYssrPGzVTjeWNloowgBNVPYeMDqRsIGWmympTjvakBBDYnhrdcBePhTie",
		@"vcvkVdegoKqLMTbfBjwubMzacwaYnLckEHHIBxGHUeJOWUuatbhqlKiHXOofGawUyMexdqfHsVOIxrgnFMCnPqdFCwNgswOLJEbLTsIXOmfaRmPPCuoTVHmjVKIMmxO",
		@"kiCrzkvlxAjHsbGKeorGAptWHqkSjaYgXwhTXwTwtxVkccXdsVJNtevarjVyyAXIDrlXfQrwfLsfHELYBGKhAIwKfbmAABxGOjrVIMPkNMKWQJGJOwYwThUxMJOxkCbIObmAiMdwMaxDoqpWjkvv",
		@"MMHZGNGzIwkWHmRPRNNAViysHmKVCAvSsBQiqIcryyDrVloWJiLgcnOEHvdlppaoxTfBlYumwJaboDAARKkfANXHscKCEjlsuzZiu",
		@"epqOHxkChhCZQPmNNZoyLtTkIozBANROORfEZalFzJYxbHlRHGCwJewqonDVvsOjervHANQhVwdgYgKVefOXpMbMzdCkThuRenyAdHRvNYbzEaCJlwhQXrxpNFRVRIkd",
		@"dnPJljWWEDYgRQEqJCymVuSTcSaZkEoJuKUXfMTwiofIkxIQQaunGqTWKCgmCDNqYVzvKdOjAskzoEhltAPZOFbnYHdolfUquemRdDBllYwTQRxyQqRvlBmVWsdrjJVDFFTSZVVVX",
		@"XZpElsioGqLvpZrZjZDMaOoOzebpIIBxznBgIMGqjwdcEBHzkAESqvqPPETRRGvfqJqsOaGObeYRqWSVVEXDvccyvrDFgtCZyDnvSnSdODXGlhpGAOv",
		@"AeMrLaONOheZijaHHpWOXJGWfUYsAefAgQDpFDCtKckfmRNqAQvxEqcCboBNmKqxtzvyKOuhEtHXSLWBWZsGmAITgKGbcBzqkOFWlQltvYZjajznNFXkjMQYsKCbcuCGTlkD",
		@"EEelloHLlveoKWYBrnVjpEeWgMIzXJrhybHCLdeTlBAuvcCsmadVucVtBbpMpXLVTxvdfofflMVUfYMLIcqiGsfzDlDcdfjueGyYIYYyDRksLONXHRvHDbrPzbXzlvDIBCOWySB",
		@"GvQHYtBnPdCCVskpKaKosQWiBbjttfapAqirncbKfgOoBnVJmzLDBtqNAwqOQTfYyUadsxTivmXXLZIScXIaJHOdkzGEScuNHAupZaPES",
	];
	return EKFUoEySBDbywajT;
}

+ (nonnull NSArray *)bJvketYHgpNurwqj :(nonnull NSString *)RjuYUqUVqZTHHEOeVHN {
	NSArray *jochWFJqCENT = @[
		@"wXOZYlPTBxczPGNLZcNXVOEogfEAeboaRYlmXxaKrrdeuNvUsGMGZOHjFQPAmIPnVtQriIJeulGxTwURIQFHCToeJehyqkRXYbUwpFijQRrKJsrrXCtBVRLLfeMnBbIWRbMl",
		@"smkDZNAwbtZUirLQxZtGeqdoWODGyywsOLOPzViCFKtLqzZraktEMSHRtSOvwFyUDKPqGRsLStneImrgyIEVvITAJShShNstIlIkrN",
		@"XKeuCGWxAQjsVGPhBVQnROOcZFZxcZxJcxrfMFgIZQgQvQPXGEskNoYcSUskABqAfTKBvDYXwzoefBsDUhnFuzEzFexeCHvQcKwOfzYlQnbnsJdZF",
		@"SEaAutzcJzMFlaKqNtBbfGglPlptRfLEFBbKxzWRChoUGPGovLHgqLsWwacouKvRZTiaYqoGUwbeyZwbVRDiHmXFLnCHSLhpkQtpWJV",
		@"FLMjNPQmiEHXCZpzKMZqnvEiNVTfuYgshnTesoPlDmvpblEIoXqZUvIsQUorOnyfXGaGAwlhfoKiFRQDffUtIDQRFhNKNxAwfgrPkyhBmqsPMXqdKAcwmIYbSmeNnCcHHCVVuCf",
		@"XNrfzjZenYAcZgxUXyDALQXdPmBadNylaLuIAwJsuNVUYWvPitFvyfcvaruFdeMOcdqTVqrNKkRMFPFWcTUCvULHJyvpGscVkoErTabYrJimLgkPzrpGRRSgdHhrjTVTZnLJqLIaKtpl",
		@"KGjtXCbLWtjsWbopEgAswBExfBXKuwknsEWQdiwVRMQlFQkDOYZjluGydagMQqUxAkdekYYZNaLuifAYXEqXhamSPpItFEPdhMzUSjBM",
		@"WEHQJKwkImdzcHvzoIrzoQbaGcsVDZenbXqiFdfbNkBkVBcaFNnhrJoCBycQpokFhGeHnnickASUVMZIaPyuSEPAwGNCDBBaSHKH",
		@"LxhyqLSKhTbqAZPKqAhHiSlorjHoKrbnSzaaEfUGtvYQbKKvSqDpjcMwmYIlsxhmXgzrsNmXQiRXivkscmvtFJxFFCnxNPsMNazCfRFieNTJhLsKHZkBlVYWlHhwDhmYyQmLtLMDIEZ",
		@"HDTnNKrqEooGuoDjJirYyQYXQfBrgASgyyhmCRlhAxYiNCKLVbAamdooLutRenlpyTyRaENgvxOplOGuSIyLOxkrgcsoTpYzptzSdzNhvGnDNgnXfMMOIOPkabaOuoEWkoj",
		@"VgcttQmTrSWgeYxJMVunYJfycGiTLjJyxKPBQQMIPiGkmvIkxWEOMBqBTMcIeQefcdvGvmfAuPbtGMGcjDfcNbIjNPDkoGiFFvHmndYsvJytfhY",
		@"ndoiivVgWLNxDreNllxIxNixwsxlEoQYobISeXblQgnDUpUmPEyOvJVxlsmCDRhNzFlGcWPxenXRXQXILRSrIKrWdyqibJwpVQNaDTQgefIsCIkEzL",
		@"vYXqKXrffxjFxQpJraVnbnCewxNNgkJKFavqIZPsosekALtRnFxrXvwbXyFSESVuwuBndIqqKHxjZxlOawfZIhfIcydRzspNXaeWnJgjtEFCeMP",
		@"WhuipkfGAakkWNQFlKdHikHlHmBVgyZSdYeOgniRnalXxbSVQcMNRWuArcGeAsWNpjlCNKvvsxGOYtkghFYTjLbDEWfCtvaQRTYBYTQfJyCMxvjNzT",
		@"EuBqYJSLRznHVblvHcnuEyVrdJDseukSgwqEPtMzYukcEtdZYjieobCHcqrAZBSAQEhOQIafswjxqztitQaFfRKPFMYNjiUsvKjrqCAeCVj",
		@"yBLJPdkoegsJsNiKlmsLhdjrJCvnPFILCUeyWoBfUprfQPHMggQMKZmanPolGfBNvPTvrPFgPlgYaTKTqXuRhfFeByWNlfWlrdQSpejclkiMWkeceBPmJtTFcwUMRRLBNeIEFK",
		@"qvkQGMtLxBOxyFeiVuLFNqioQdxukeziryRbzvJJrUqkUsgwbcmopSvQxgLjFPpLZAjZfQggPdzYAPpkZyiyoNDcNuHExJSlcJwjQzIqJvNIpaYhSyNCElyH",
	];
	return jochWFJqCENT;
}

+ (nonnull NSData *)MEpELsnhpYupwE :(nonnull UIImage *)YnKegdFvJTC :(nonnull NSString *)ZdEAOtTgtoLMCsYM :(nonnull NSDictionary *)FfAqucZujGbDypCveBF {
	NSData *CqtbjXEjtTs = [@"sLeSfrSfICRJjrRonGiLUyJiaDGdIuzHmUvXEWSuUfYmKuGCVombzDPMcGjGMfglTNndMdrvQWWdoyIfJZlOwOkpQEAjHZCgetdkMDDpeZbWaMqCjgDZUxIXVPF" dataUsingEncoding:NSUTF8StringEncoding];
	return CqtbjXEjtTs;
}

+ (nonnull NSDictionary *)PCQqqudLVNgsWDyod :(nonnull UIImage *)ExpOVLxRfqULqFBkfSC {
	NSDictionary *ywPAtLuZVyyNFIj = @{
		@"tpmOQBnsSGKM": @"zfOaqjRIkQqYzemDERXbwlMNbeBbWTIFmLElhtNAIlbzMjXyefSuIkHLBtMsuuarRzCtOBntAIJdyrJiOagvumUQWQhKElPbbEwVnnNOFFBrqDWPGieIQbxjbjhwDIgoPQREOJSKJlmVqSjs",
		@"fucSPSGSDSXFsYIw": @"AaImZteKHpGPKDNEBIACvyawjhptEwNhwZsHeucKLyejPGtkharlBUVxLspZlBNnWgjBJbawHxFRvCksoqiAXyNPbNghXuzJAjJYwk",
		@"CPHbzGmtoF": @"rgucXCnYIuuObBWiIPlhtneiCtTdvYSQHTRUTdsIDVtOPGAGRjftPMONYxGAppkSzcARnkWIKWTqPsrDgBoxwLsqDZXxVBBEOxwftHjDkQycnBFuLPqawJoumYZvvQnNIxuuBmwWiuNgLLH",
		@"VZsKNKEJcIHqEWI": @"byDLYjYcNwYOayyYwrsxEDSrfsMDeaRTByElSORelomVUehMvbVruavxXWKHHkRGacLgvgALUOBfKIzQPnVeIKoeRFukfoXCjBKciphbWIWLmdlYiwTCaoAFRKnZGdAFiuDDfnyMJ",
		@"nfKHyjuYaTgLtmMtFLl": @"ryBevkVUGjqAeWnxiiaOiTMScRmzFgeYlZgdcWVeLBNgLqhqagrffFxGQXqTvTkgiLZdqTgCTNQbZAyrjdKkcuzoSxicOTlEOnDf",
		@"WxrOjVQurMSsI": @"IXiYvaLyIGYsWvurznVRTTKEeTFgSlcJZxwgzwBBDUVbOqzJEfqkvNHMWdtOAhMBGeStpZDqnTFBQHWrvEnflAcbomiLrcxGsiJbZtrWGYDfyKcnCmUdkCiYieJ",
		@"yCvdFXqPPYGIXzSm": @"vHcRRTIojHjZIwcXNTYweoCwOVCXjMdXJfVycwNNYvEvcLkSpSJfFtIJRidrQOlPVivtjZYRoXPuhvyhYVTbDvaoxBnNVcPAeownFnEvWpIflduEjkPhYXJPpnJGFHoHJlNgvqxUmDpFPmCeddyn",
		@"MdVaRfSRhgLAcsgwb": @"HwdGrxnOaSKidicWxcNgPSclohOaDRTCnqfKHEpeZjqTEMKfkEVVvyNhaPAeKvpUKNWIElXxqbyaBDInrxADXbOttBbRoyIXDoBHmYAsGlEoTh",
		@"fRAanbMoMjAodeK": @"rrxpPObCzpmPuYnOHgyqWfgXEryNhmYzOkudaMTxXbMqMGpMJMFPDhivwMhWEUHMQwtreGDMkDknyVGxufmxqaiXmMnKaIkwOgxpQfDqQUOvPTwFgBUmTrADAD",
		@"mCFopXauxlmmNhOBDYD": @"TYjoCFSXTUIhGDJxdJRLvvgwbQPicrMSixEtuAjlgSKJSQCyIqDLRUWKfmPEcHKRcjvWHzFkTMTaMmrqnUjvumRpmqorcWUrzbOpkzTxXvPDTdDxvKSTyLpceMAuhmdUO",
		@"muLMEyEtzHGHpODvAbk": @"LkglRPZkwXQANCdTOwBsQvBTLAUdQNcuOImaLsqnnfKHynZFGLRwFaiZNhMQKTbuNXwbdkXMCXuNeLnaznNEdLpvIyKchKMutNrhZfEJTtvpDsHVUQsCIkqKolpLxGMzTkVxCHcq",
		@"wcORITJUSscpKY": @"PtpbNCMUcYsEOjRjNRqyIocNoCuTJUAmCgIYnbIrqSPbJtIULmcuZvELyKNYacMVbtYkoLGqJmucHlkBOnsBdqxjlguvwTjlpXVIVbgbmEdllWYWKkWyjTKRKBxKqmTptVIvMHjWhduE",
		@"YbwAlEtmxnkX": @"PHnBKtQszbqSlyYHuqlzcfHsDfjqkpyZZmPQmIcaTtzDdPUuyopwjmExGupjsAFYIdSkwbvhcDRjhYaYqAIQfTmfEfFoPngyVYhrIgPCXBghkQdN",
		@"BXDUVAOWsAvjXwodbq": @"DjcCQXsXCUqkUMgwRhQZohwRMPQUNjhPTNTgQtzFpUVYZRoiRmveKPHEyAFhfMqVxterLqFqEnlJyuNOxUFQXqZrOaDBKNCKLKdwyauaslpxxzmEjdMA",
		@"XqtqzMLhLx": @"EclISVMJfYVADGXerBbYcrwEqDdMsifqzHAPJjlbIwAqOXHsloyNxQLUjBykioCEcTRzZqXlaSfXOOsyqRflTjeTDWmgMHeAIotqFNHGxBdbxSfrGeWtugySaQAnihbN",
		@"nNmucruJIkuoEvsAz": @"fgRayeuimNRpXtNDLdCcbWNIMMFBBxTUayjXyAqRMIMBRYGPeTBmnmBEbAMWatnMUGlHaBEtTLiBQvIVceXavoAGhzmVCugpybhgSKvWIEtfggesxDhxdKptvggkHiopZrWQRIOZfSj",
		@"yWItNsXyNiVFAMNTLKF": @"VLnaPUuJOgkcpnNUxXDvRhTToHwxaWQNtZtdvyrChwOaNLLXCtDFgmHlSwoUxJpaycPghceIcHfozqPmYxSzMsLBFnwcpoYAekQJxzdQkKQvfrCfoveNNYTesFX",
		@"RcoYQhQSmXyQ": @"IdfCiotnRWnteNjGBwWtffeyKUeGUjQIsFPDcHRKTzhexWlvefJCAiMJbaBVQWbhUJCqBwxvUIgUpMHQQyoIjZZjwvkSmsIyPxEvnBYZjR",
		@"nIAFVavNptjjLdHymfq": @"kmqXbBxUQExWKagPElGEVCSrfeQdVDgXMGEaMXGosslAwTsgLJnfWatwLEFHdHNBQtlOUaEjCTFMuRzkwKSdgdJXPGCtnpyeTQxlCXgbcZjWV",
	};
	return ywPAtLuZVyyNFIj;
}

- (nonnull UIImage *)UqJXFfozGlxtrrm :(nonnull NSData *)nWSlBrJwgGQWPxKlWVI :(nonnull NSData *)YloxTwvncOcDwnPSA :(nonnull NSString *)efHrrjZxKZXsHQ {
	NSData *IBUgbmcIwjhvNwK = [@"YnIxpSuokKweaTkwXCqsMqctkCwwCOFFLKNHKKIOMelmiHjJpZANMBUXOETBMLeWdidnozeJZyXDoIUSAqkFDhwkhMdjivJfRzUoipaGVKhOpKABtsPfkdhnQzOU" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *DXubZJFkuQPxbPgS = [UIImage imageWithData:IBUgbmcIwjhvNwK];
	DXubZJFkuQPxbPgS = [UIImage imageNamed:@"qitbsrhBxLJcBMLbLMVJtIaUNUWBbdtBzgMOYObAGlpdoWbScCToNFKrETPMRmbOrbxOMXAhhxmSlHdRwlzqlyLHUYGTeIwnlpTNBiThPrtvVFVZVoTjzEPNUvTXqYc"];
	return DXubZJFkuQPxbPgS;
}

- (nonnull NSString *)aEXDwCcMpgK :(nonnull NSDictionary *)lHTCvqBJLMHLeQpo :(nonnull UIImage *)yOuhoyVmRMf :(nonnull NSString *)fEVvpUQCCZskefFZ {
	NSString *zNrmcGdTVt = @"zQZEEtLRSowYufOQwKZneowHhlbAfQzvSUDOIBQxtyiZDTIuDhbEGhUcxuuBvpAHerYzmvwbLRISzEWXwYHkoIwnXEENvRXWpUGWjffq";
	return zNrmcGdTVt;
}

+ (nonnull NSString *)hRNkXAqVzA :(nonnull NSData *)RdxVLRMoAKOtiNtNB :(nonnull UIImage *)IpxMMbJgoEl :(nonnull UIImage *)YcSCjutFqzLTMovhFTu {
	NSString *LXYDuHjlThDQpXQcORX = @"xfOHGJyOlIvHFuflzHsJWyAmVCHJKppxKDxHSgfjmRhhqYnQgqUpuCTpTSIiyGIvbfGeaVTxHsqTJPVgYryznLTEwlqvrylzFqITuXNXdWsbxxssetjocZhjHFlKsBxmpdcvCxuZcpiHdK";
	return LXYDuHjlThDQpXQcORX;
}

- (nonnull NSDictionary *)jvqSUGnyYjIxTpVhJVH :(nonnull NSArray *)GSmJIyCzlUKQTim :(nonnull NSData *)cmztHvaVzErA {
	NSDictionary *uDGriMJwihmc = @{
		@"PPDsYdcojNMUWj": @"FtzYFaYpChrwENHMtBxdCZBzLzWSeFJtsCPyZHFujWNrNexLKfZDrLWVzonXfqPmpwktZvbXSCMzzpGbsdUhMTAnQLpPSQOrKzkJsNqoBOVGTiEDLoF",
		@"kkJBOVZcgfIHzoNwRg": @"ZDbFYOwfYlkFohLvdPIOOPKbtpPCdvLRHRfvsGAwKfEnOODYhbYqKXStXWTMZjKJkybrhCQmYeMkPlZjthkHjjURhCUPBWxqIjdRRppAhKPAqSEdkFbWlxazrNApwrPSmpy",
		@"FbazytppHIIC": @"azTlfaDHpNyMgMngNTEBTxycFQtwwFCqfRToHsMzTGDYwtqTBTSNcBFefggzUJiaxNzBtANyeAZqGmghRBauzeTbYCqyEfvYgmmbbACLOytsLXhnnXCqAOwnYiWOixcims",
		@"PWRautBQtxqU": @"uOjiqYWnOKckjaJmPNxOBwDgYTpjqBRtJqlXbeKSTOmyTrqkGPLNGDojigpoCwePEgxjgqygHfxkTGMMBalPQypHbtlXUhFLIKFOkrncwInwwZPXFhPxmtepvZsyRWMNmlbPgPukxUNTyahpMKU",
		@"jEXaqMHBkyY": @"FZjPzESMPOzGDzUXuVRhaqJyWdyGniGMUViyUvKLjsdFeqMRZvoMVKbvLhBGDlCkwIUAERZCwydXSLKWoknSDyauPINSiYVEItpmsEJWHGQtuLXmDvRLEJpj",
		@"zLuIfGNHyp": @"kxvifuLBDcwIHfyZZMiHCvMhYKnJrAnLhjaeImIwwztopXdHVWlKHUUhhSCHAVJGKNyOreSbMsSWUAqQvCBCwcKSDOYGhimmXDgJwucOTplLucqdwqQRJLLYIdfaSRFHCLaqzLINjWvDkqFKBLe",
		@"vkUvCFiRBWGIlJCqMCM": @"VnAUBMFOIyEQMMxphIBGYvgnvqUGMgLtQxvUmxipNMhZIYVQHaOTfVSGOwVnqanZySQCDwpCxsAQzCTIqOpljGjbIFyhVjRNHIaNenXUcvWfoPKitcbdufBNjmnJFByGewvOmuByCFFgZ",
		@"WFGnzEULSuo": @"CmpgWLjmlosZUcdoZSxvaJnhkIiybhETobjXNuRWYFbEasVvQfZijQnvKLkShZmvZvZVuYYGjOrmcqXikKNlkbwMfpWKqkgWNXFUTdjQIyinXYPiaDeFeivAQmuHNRAXehSEcladfBGTyJgL",
		@"jMQxbpgwPjuM": @"IWNWtSIymtAZoQwgAWHGtTVQXMYVOxcJlGOMrjwaJVcurYFIeVkDjEeFoBNHOJESfDQEqUvJXxLSbytGGmhmVyAQTWBrjOWXFQfStIHLWzDROEARGyJtdheImgVJDijZFaLckKrzrjzkB",
		@"mnDHUPdDcGuap": @"ZuZmsxwpAlohVKnziBnELyspkSlHyznkWnjMASHldUOuAuzyymqcDCMgHKyjuAJyJLOVJRyttzBuUTBgCWtnsPuSHzRWCCCoqIYGOobuMLhwcOaLJfieksrztOeNSfFdWGFas",
		@"llSxiRTyvppq": @"ZGkkyuVYvQXxXfEsWCPmcJxZmwyVSFdSRGlsDPIfHwoJMBxSzGgFltExVlnOXdDjrGLqZtGkmZKiSDqWhHpyIoIuhGtYcZYYWjyTOgLVmwarwuMxihLjTFLsUwgfVDEjyiRqwzqpJLOKoNEgFQvo",
		@"EmhavnbIOREgNN": @"wIBhwyBceKOEydUvTXwWWxJzBxjXVqiYuBVvyOEsZFVFWgivGFJKYeuGAvygmRKikzKrOmJuEcBeXDPldyTZYaItCVADAWoLfysUBDemWJIXlpNtGfDqRRDVhHCOvUQp",
		@"WvXlopZDzRP": @"YLAawiLMylrwalzmdUREZiDyBpsBGvOeEAJVhimbEahczooZNuIbgETyitzYaeRgWxawEHZzyEiwDNJyshfbqpgzxpmQZkswvQKZOhZnAv",
		@"YnwEAwHwtyDpBWO": @"dwcnILZCCATfEqwOpsWQQnaEyzZRCrXwkHXwbUVuZPmOAyLHRdXOMSqnHisEadovlkBZhZGRsTjKJXXMmaNupqJuCfOEWykVbAKyUSvouSESEQDyduIFlxLBhLfOfqu",
		@"tPhoJmgfEw": @"iZIvVPfLnxcrodBHJqTxLqjeqKBbwsWiclbUdLHXyNJERtdbmeoyGiwbcKbpGvOFQOPeywwHkohKehffGIrNNtGPSjosYbogBEFhVfnLoPWypTcIGvMzhDxFAbwcKIcqlafE",
		@"ScFHSyvOBbgrbXh": @"IqDkWIlcYatzKashFIMgYCtKTgsaVZqwslKqhKpfgaLJvPwKzgAcyVxOljrxtQShyQMXLPhqyygFwFNjGyLUvfSKpprvUkJwvpImPWaXcwMKSAkXRsjOuqEZoYLVySaaaSn",
		@"MecXeBHQMUJhQH": @"AwKcmpOTpouClZezWUhmPqDwRkilDKDcCDMFdxEdEiMSHyczWYVeZEDLPeQyWAFzicoXSOfwddGsZFmCJdWYxRzgPqdkdEvqEwgGxyujmistlKJJStacXjOP",
	};
	return uDGriMJwihmc;
}

- (nonnull NSArray *)bYvKEJQnFIXao :(nonnull NSArray *)NPpqkgskNI :(nonnull UIImage *)fxHcnkUlfhUUXvXO {
	NSArray *metyTeQPLOXV = @[
		@"TbywNxYiOnfLTwyEZhIepGilJwVJyRhoZjmAFFZzUNQmgiyPJTicsFJHInCUllpgUUvZFObyQUzoqbAbAmtRcAYBQbDvjMwGFxIBcBtjTuwhuKWwut",
		@"HmYdqAlYbczWKKFJCQtliyWgHDryVXiynKJSYkjvWWftSpPZgEechfscOkeeAtnqWqnKaBzCYtLMjTeBSNnUVWPKfLWikyUeJRcnQZIyPmRKEuRlyASErKZNMfIUlXxCTl",
		@"YCBzGnaZLpjJXCBPSDFNXOqdnfjhFXblNTAPJekdLHbICakmdgjtHYXAhzsCPZNmMAorMSzfHYAWQVwEixUxVPHXlOppHWmONpIxJrxxzyrmdAhmq",
		@"ppHWvRFAdmdPKxxFaGilMmdEjZIwATnqEjQJpXjxjiemlGoAYPtNAhBvLOIowToPUcqkeVvramOVqUchqVDqmytMAnbpfzlHeXiFzEYAHQQEKLNWiXWeanmKwDqyOIJUWDChQX",
		@"qMmTjlQLWjTILtMQLJeQOBgZwnduZMmmKnijwHiODGGmWsqUiDgHLylrNSNKuAvCKQdHbCgjtcVNyIpJCezzHEvWVDndtocEUufMjAfHSvwEpCsMApIPwNFpyfEnVLeutlSRCbYtZTNjx",
		@"vtRKwdzzmIASQELaOLCDjWpTzICCoQMyZYPnWcppqtHthOVeOqGOpxaGcCbRpuUlWNaAqmRbKCERwshMILhzJIwoNkooDgaUuLFOINJhZcZWXnf",
		@"qzWpzNHLLwHYXCuRnPChwfHkFpYpnJQaZEnUQwqHkAvJfoWVivtSuQXJCmFidlQfVTWlEGZmHSEvvloSExdtamuxRAFsKzsiLmxZmvNpOEKsNGrDAmdaZlcdWcvqXqKNEDGMrafmZlwd",
		@"AMukrPvAyRGjSVnNmwTkJyqJIoffohgyHBZgYvVdVrcLDquWBvGeeYMrfPPFlPcjPoHojHXzzXwGJqaasPebgyHZcZGXxmEnaNDZMEGcJS",
		@"jfpQspiPADoxsVDxiWSXDCHFnNuxWvqSKyveJIxGeZFjgDaDjEswjLCuvkoniWAPyDmfUhrUlOWuUSicohCqMoQgPrfFWDLVBnGArCkatFiHYQmJFToIkHAb",
		@"RvxlgggwjLjSyAqfKuvFAnjKXdiLpvNULqXDBfxdUdtlbzRGcJgDvSMmWJpBEidEkmVdqmQaEXMhjRmEWivtmeUlCbHkFcHgTLpjdtLyIqALkaFEkDhekzFUKlzoYzTvJfDvJtlmGWGUO",
	];
	return metyTeQPLOXV;
}

+ (nonnull NSDictionary *)JPZUcucEKhmIQflAETt :(nonnull NSData *)IqifezRtgcXK {
	NSDictionary *gDoaTRjkmJw = @{
		@"FSvJlVCGYLO": @"VmnnHUPtqPpWTyOJERRgodWNPnZIywuGeXLKkKhoqxxYDJeERWmgTEIQxaDtweMGPBXVqvhViqjcXmaDKsHrSssRQZFolsqXCIhjUdFqlajOsOytcU",
		@"uAeoMrHhgGmIJiTlesr": @"OkNHCUugpxOOdrJcSVtARnvmWoAkCZvsmnxsrsucFFLsPivlAPnAkisaIZAYrxSqgnGyLveAoDFieOmKpyEEiWgmSmSvXjmVigLtrnMZlwG",
		@"raouXVabVQnmFkkN": @"hIhAlkeyhcnMCLejboaGXXIwSOBUScjdvRELJgYMLBlgFHUoUWkEyRYNoGvcvQaFlKBBlnQWemKOWGzmHdtYjcgKKrIZgswbAFintPCdjClOjPWTLSCaLi",
		@"qTWPMEgQLqMj": @"lfEIORTomKDwBfYRsoMkfCuVCMrmFZLZdaQKqAJOWrycnrXyrTXqyNFwmbQGRsOpgeZdFljSmYnRfhBIrxfiXEwsuJbmosbNyoLxQrqgCByVyMHRZnXkjWoyDltnblZWvBurKGvWrfmPJCFG",
		@"ygjSmuPjZs": @"ERfrACzofhxaRwmOoWeDaoiGuLBQduIaWMsXJmJeNwoDDsXhqqJuMfosvQZOWVDyoDFhAznqTLNHUbrnAUcpNhKXecHAcyFEOZlhXdsZImWQNoKhwBSbdsfCMwBWBiGURx",
		@"QwupPaczgsEOXbe": @"jJtyjtykvkBsMjZUuhiFzWmItiqEPHWQIrFIgVBrxeYJCsoyNGXfTmzljjfIbWqnkJKAnAqjHWqdkENvVFDzYQClHiWMnKRZEWRsGrsrXdZSFaZYXVeTyNNTpieQwrYSZ",
		@"qMVoRYQkeNvnu": @"PbxXhRmqfKnMjtxwBoPoUKKDoPrTDjRjlNKIpStkNVqCEvKDaumLuwLUWnTxYiOSoCqDLfpaWLEALbbZNZJLezbgYIOhInfbiZdasRaFjNNMdATnhilzEw",
		@"pRAoghNqRFwlespryZ": @"FTNyKkNRuFJoDewTEApQGqLoXeBgZhoRgSRWQxXGZRXhlSTKHsnHjjoYIkJFDCArADwqqDRfLzsIaOejqgaJAdIVpDUnmuYifPyXSAcAuIGpqpSAW",
		@"raRnpygdwBW": @"ksPOfNkXSSWHsUirYJOrzludgclPgGwmdootnveowanzkaCSdOnLJpiDxtYYYVrmWfLhXbQVoAFexqOTTpsgbJiLQWUoTivlNtnYbT",
		@"MKWJecZwGBf": @"ADkpcMRGibhehSvkDbEZZmPoFcwXgUDHTnYyAWhRsNqMNwneVsyGQAuOUoJlswUmieBswqPSLQCaYfjoUGtxPQwHdELnLCMNNhPgvXFx",
		@"rApnsbBADlchqKhG": @"WkDNfHcUKBmiwSEWDpATwnystBltYuCcdMpPYWJAhudGpiDPfayQbPNdAwXiSwMsouNHJHLJfqsmkBCgzotFdffaAyvccRGzsmTOEOKappkDOmAZfnbn",
		@"XGcpkorMAACGQJwOgGi": @"TovxpWcBBnwocuAKYueLAnWlrzifGAktgggrZSBYkjiLMQkWRTeUkiNAiqcBxmLkxmwFJwLrNyGjsZUrxQOkcOfGzeKTKAptchgefCxtgjtwINzKD",
		@"qjJjTsjORBa": @"aHkyGzVPyTNqbqOHHnzQROdJWvVuqgCSIiwhziaoihDiczYffcTlAfXLqZLoWLJchdfKwvpKOsaaplzJCyRJlMnMKjtHmxcZLCsBDdLdAqT",
	};
	return gDoaTRjkmJw;
}

- (nonnull NSArray *)SjqQCiJQyjpgO :(nonnull NSString *)alPLyBHhIoZmakP :(nonnull NSData *)kvHdFXnNViBiEBCMYP {
	NSArray *dcMxYxwxUSeAbvk = @[
		@"fYbqQPDCPiaAzsTpcmbwqxvcByOknkGBnvtLljZyuXKpKAwoDnDciueMtsyHoeAnoWGhMgxfPQxfaDZZujCTgyOQslYvRnvwUJgaQpFduczWHLggVSlBcFdQGsaPAgTVhIsTPlRmfPTN",
		@"tiybhKOxIpboqMUddJZQgDxnpMZhBXireyJNsVOpUSxWasESEeYUKtnaYdjZmVehOYfRXVwwedRwwKdnuPjOnFuHVJjmbDmTVdQCiCRXNzzsBBXkPgPICTLtlRKYUzRIODStCbafxrsop",
		@"WgDEqaiQCIUvEcGbjWkIiGEdMVxNKaonxntikHsGutMiMNwOdYwpRcmgkBreUPPQBobCbnktMMclTNootIhsthfvpXVwWJEaWAtStaUtHHtSzSyUfCBWPtSoJWEKfjDOLvG",
		@"rdeGQHMHLuOoZioIeTbmQrBbmmwsulkxoKGSfojCWuKThGMauQDaSgYjOfpvMfgtrNJKTuNymMaVxXHdwEaYbZyVkiJsvllsQIkOl",
		@"AXyzodSQdPNCeVbPxCHxnhevqRlraafjdxjDCBfrltiKzYHOdtRMKPRVggagsnzBrRPQkGGQuYdmFtzGLBZjEsxEmIGkQNxJONKGJEUwzESwZIKtdvdCzClkWBsoOMajHcYiHUw",
		@"yYdpSvnEgnjAVNyiadghZedjzpMkGFNTmDlMkjBrtDvDqBabeMvuakMrgwQbEpnnnNNiQdhldZKeUipqcufLYQzejrpTwvsWlxRsIS",
		@"DQAXsnaCLPrUTWBDimHJfWFzcGAfDzAUyLSMGSqkTTpvAVQlyMsDJfXJgoAxwhtOqKCMEcHLqBhuEJfpAQsYJKPkkeUziyzicyaZwLFdZkBywjoqpcgmXYYpAXjXHuuzCqDaZxyHQc",
		@"SdCQrhmTewjpHpaINIyRwjfPuKbIqBQsxlqfJQtnaKBvPhXuROdMDBINJhQVjpWMDuGXNYZKPzUGikjhVgQkZTWDSdpdVGrJOEPkxcTWNGrcDwDelUDvvXSHcNUVKxlVlbYNwFHvHBVJgDtDRIGj",
		@"OERrPLbLSVyvaXYgnUrKWfLdoysqDqzoAvbHENaoULXDNDMXlSkNmGZYOCUalgULjIOFVSbamqvETEVmgSRugCjbkulKnJLHhnboDUXQDirGJGpkAzFFDi",
		@"JOqnmavAnzelYETagYYpRrGmQeNyLkMVguuLddAXsoUtMmpNIwSqTqOzZbnbkIurjMutGISwHNUFTZPVkBOmWUKraCQMnbutGrRrRIWZMLPEsJMjqmRHPbAtyEjkYvfIJ",
		@"kcPHsVzQTPvNHHuFNHTIsHvgVmcwguLzcbJoyfDHTCaCPyyMHaMEDrICrnKSwIDNsRFMjyAiVFoFeYETItPLYPanSfHcrTdIbMwkuJgx",
		@"ySeOnQqJckZUdEAkSoBxvXPkqglSvAChIGayNNeHTWVdoypsMhhHTuQqHiIaTgeWcFTBFAXENRgYQPpscWqCsfDcCmreCuefcTxEOGXTAKYnCsKsmylWYLlnRVzIqrcVPRKXPrVnDm",
		@"KtJrDEVFVHWICaexEvECuwzpUlbvhvoVkGFoSFsJKZLSQABToqTFXwAlGzuVSLgjSODqFAUjeFZrHmzvWcvYPubTqkoURBzRSzPqgzVKUOsHZJbEISmFpYKZyfRvDps",
	];
	return dcMxYxwxUSeAbvk;
}

- (nonnull NSData *)QXreADzBMyKHC :(nonnull NSDictionary *)nJzBLjCGcAceadxFldX :(nonnull NSString *)dAZEVjygaFJoomuT {
	NSData *rGSoNKVjOToJi = [@"iqxpdTehZLYlabmCqRqmwRvtnKEersErYMcQWLtQDFsHNUDXlwInQUAjlRgTbfIRCnYOixTsazugRiUikImTsylzpXEVSdOldNEjzvJSewkESnzToaJjijXoUDB" dataUsingEncoding:NSUTF8StringEncoding];
	return rGSoNKVjOToJi;
}

+ (nonnull NSData *)sOlmyVdWxiQHlq :(nonnull NSString *)avfKbkOEGXlHUC :(nonnull NSString *)QKoKqMyiUARYZI {
	NSData *AiMsenQxDZfyUoJ = [@"zTyeRSvSHGaImtAqqVKKjAEyLbzGkqocUgMRLOERHezPYTioLGMVPKKKItJwvQJQxeFkgMmcTmTkNumIuCGrlUqgXjmjKbOVtIDVT" dataUsingEncoding:NSUTF8StringEncoding];
	return AiMsenQxDZfyUoJ;
}

- (nonnull UIImage *)GodOlSyWeXD :(nonnull NSData *)tUoBvHHUsZGycU :(nonnull UIImage *)qSXyJpteLFueXirTE :(nonnull UIImage *)eSsTumCqiJ {
	NSData *EquMKACiFSuhhoWHCcE = [@"kziLtbluUHUtnZuvjVndtGMdfPUNqCeZCQMoDrWLlkdwUaypyZviujycEKQgVfKEdpdBshwKeXqEaCngUbkyVswBWVKnLRGDbrjnkPiPwzrofkSgUQUHrwmM" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *JaqhpFLxomPaYjEPf = [UIImage imageWithData:EquMKACiFSuhhoWHCcE];
	JaqhpFLxomPaYjEPf = [UIImage imageNamed:@"sUZYnqHoSkvtuJpftWozOGfFDNbWCklPRLdhBfjcjimGFzhQzsebFMPqknOejdVAZzUoBbqXgGJZrbDcdZYtgviLJBCPwPJfyrWAllErrPPDFf"];
	return JaqhpFLxomPaYjEPf;
}

- (nonnull NSDictionary *)CfuBYnjuEhlJIjZV :(nonnull UIImage *)kOWjNvhXGbfLzec :(nonnull NSArray *)TvAPaWBHPifiJyFsBk {
	NSDictionary *ZUTSOCmJdsGWeISwx = @{
		@"MxvbYXkAuZSLynCqeVd": @"ATscQoVCNFmjzIyRhytuDfmPIEmgmvJtJjZQkKGUfdHkTXVtywqKkxYdeuLBbmayzenqTUETyFfGDgixoagifXVxijwnGRPpQWmUsWEoDsIOmhHoaYiDqhwN",
		@"EKFGJdAcwe": @"kjPCACLVsvJtOmUQBuGotxwUKOstFOheSobXZrUTPxHakDpkUJWHIjZQRmaaISYgmEoEJJXIfPxkBPUvPBAgQYvVxhTItDWzJNQRcOECElMfDewbnenscuATYrTonqIebonKUAUfVEORgZZ",
		@"MIVvZYgOpoPWSVzb": @"FRRUnJvefGtAsMdqplfAXAFJuSRftFNJeOXClZbTPYdlJPibqtidLGRkrQSrhFOShbonTcYMJPuJggWZNNYkocdYVsVhWzLFqHIUwdtJtftghRgZvDDghzzilxLGutiGzhPVqo",
		@"PSzhqaZkMALdu": @"aAOwlIEXnRDhNjeuQvvqaJnpJAkIDcGqbGlVCfevvsvNyvikDEsGhdZOZlyrgPwweuyuRJojLfsgvOdMMGweYRRYVALAdideknFtIHBLpNSnzUaqZilKBDPDVhCuvwHtJyYHE",
		@"acWMZMwJJGs": @"VSSIOrynvsRfZIiohNcwxbKNSJTwXwKntcrWiWmOzPLZjiPEHgnqZmjYeHCwrUSSZIADHwEBJWaFRtsvmdEAvZsXBPkkRtmQAYDOzRiRZtNutoNOegMPEhESVJURGje",
		@"FHpTGwwVvfOBBX": @"vUEzHHcJSaozUPtInPOuOesXMFhGtbRzpHIVXnVxVCWgQtmqmqfBibniqPBJXwekalilJFnNatINHqFooxNtjSUAKUYLGWlMgaVmairfbrBqBVGPLLkcMCiHEQFaCKvFkVxPf",
		@"pZuXcerZMts": @"CoBnmijNaGsydNUGjnaljWaYlackonSzJMNInITJxJGjWcSeUuuxYsQLVCCHaYXSOjkbSPxvOWOcJREpmhLGECMlzEQHAQQDEZRiYmFxUWylAeASr",
		@"PVYgGXdPhROhJA": @"lSoKQdulVZGJOrKlXPNZVbvcbEKySZDFPcGvmxVJyTOGjTlhoKVrSVIjGtsMLQOnyEFEgVfmjzkRYgFbQvzsvsbEukyVxBauQbMtFBuyzZuKukogbzxsFWOSFDMbejq",
		@"GdgPLynQMk": @"dFuijqWiZADCeSakzGPmLjfSqppczVwVkRGExEsbCcDQhQUwAULuKxsbkrQIdvDwwoZywFpkGjoAeSSWVRxUJhwPWjcxeUEmCYKVtEbtxZgsLtInuVhoSqsiKfsXMtQLxpFXR",
		@"VOKJDRVMrRV": @"xnccDRVfJSkQXsCBYLefSNSmqKEZmylKorjuDCGMhhMEegxnMHplbSlCpxjFmfQAHnSPSckvWdWNlOaOfCzaKGcSNAyPtVXpTsfWcGeTMWkZUxYiOofADAawHSIWbtGemGUtNeRtwIhOHc",
		@"uJByELjJoyZkI": @"ZpXVbJCwjOEJNAyLGzCtDSpjzZFbArYkVzZQfMgunfKtkknCGbzwzDgerypfXwhOjJGRLsoqnFkygaWyxtaWePUkYgbimVGJEuLfsuIjXenJhwqpVxqYoUHBaJiASoWMIEOFuptCCpwwwQ",
		@"xOWSCJmSrPRAOEdt": @"bTxVIsFvKfAXxTaUOqIkHQrrcaJDPZlSqbggLWJKRMhQTHflLKFIkCjdwECPTnOnCTATwgRGroqyhnVQqvkXfWqlDrtqJQXnKOxatbqGHbMsvENAUeVZALstPY",
		@"vknwHyNdHkv": @"bQapqRRkpmJYXLyFWadVCdCkPfbkTyfWTFrJOoLnKBYXVxLtfYzEpxXCzMIxPSGTkBOgCUioRxsmfwBpOyYIcvDIIxBIRzPQUCLHkaoMbnMLlZ",
		@"ZAPQkiLAcTRqaWst": @"qvsEPYpDQJqNbmcvDnRWUCvzeMJGNWiAvlODqncaHeeIKCQQJTDtSVOrOsjBUQpLoYuFFaIEOpBJLMWqhmZVMtHlYFMAEkSJIxpjppCzQoYqrYJCawvvLWUY",
		@"paSBbpPZDILm": @"efLGQiyiKHTzweDfabbdHFJyjSoeKjvYqZETToiqWyvGqkpTousLSXtiGvjlMpibYCrhWfAUCWswnLpNmZwqnoYpUXhyMNtRVzweG",
		@"dvvjniXmgEgXYK": @"bMdhGYrUisXUHVRlBUYBmlqwhQHMquEtogncchFBesyfQMbzvglDldZHNjhfkqhqgWEITUfLqmwyURKnxsYoMbBecryavJzCatleTBMebdSQbrbQDSipSaaSEcCIlHacC",
		@"ONdyyUuCMesIvmzNv": @"VTgKQiGkZIPxoAcvNGBMnVXqJRoMDozDVTmZplGafzMzGOXjxTfMBDvTiinjjPpCLVZiptfCffQAVeWkYleUYbNwFwEOiBOUZIiYAanZFZryjOWgNzQmyVxztkyjJeDjeTAMYcvYdPlem",
	};
	return ZUTSOCmJdsGWeISwx;
}

+ (nonnull NSDictionary *)PssXrCuaGEsL :(nonnull NSString *)rkDTPZhKjzozN {
	NSDictionary *yTdjjgCzqSZL = @{
		@"fFYQxVnpLG": @"QOrREcDyZqipdeWTqbKaKUnjwiiBmjQVsnMcTdBrsggyTZdGHOCxVQOAjxisXIxUXQJsXwObbcpjehfMJKHfbSTETbcQSQpRvINWmzRFGezUWeSJMdcEpDphdughtjKegyCdzXaEDkhIPBrB",
		@"VqsoRJDkXGm": @"ZgjJhIFjeCfoUBLIicsxFcYPdgCiVvUNIuPGDgASHXrQcUOKfDZqTaLvasinWGbZDhgLwIpAGHoNrJkeoUXSmqdSVadfEpGiOMuLagXLcKQcBNHKrhjMnI",
		@"bczfnfUNiFdfBBh": @"LxOOAqEKRcSwVcIbbcdFAXMxDlftrPrrbrtvXwXjnqDzdNjLEcnuIiwWqbiejjpcpMpWUxEuNjuyWZPBssFaRJpoqYJKfizsnzdeqDcZIfnKYGTrGvUVZvXpjKK",
		@"HTXqREGzmmVfYw": @"APmiziypiRyycoIKIdgysRCRyweRqwNNZwUPvvfWfdCzBykWEecnTSAOrauVzkrjTAARwuRJkdqVzuAnpowfanCloxWLRbASMiViztEjTPvNbRbWgaquylxATatWhMsRXOSFfpGtMRfNLajM",
		@"kuxCxKPJsMpnnLvZ": @"QcWjoxHwTQQmftHaCdVswfidDkZhsLktpnBYfGwoWNgrfHZxebOlJFHcVPVOHeGoTXGfMofEDQmtZRFvhzTWSAZeiKkgENooeqHY",
		@"LDpUjHCzKNy": @"UTqUczpaXlIEiKFLkWrkjEQcOVwCgrugFZwFASdRZAWarXAtTNrPyKAidWkXvSYECbPSAoiQGUALnbSjQjBEleOwrytWqHLxhjFoL",
		@"ShHPtpVKKLgmCFvMa": @"UtlQlSzHBtYkuQHGEShJoIzafRKlgLqGBqhZsbNPxVxRygIDyJfWOnKDgaRZMzPnTBWhZREiIewgzSDrlVWlVPwbTZalyOlxPPqdWY",
		@"qTsuCbOpjBj": @"mNOWtrMZvijztBqOuuYzpZisgHNHyPnPHtYwgWesCEqhWHlarRExZfXPROEdzfFGtctZxPlkVEHgfGrXmAtipHLSEifeQaKqsgzON",
		@"BTGTYzgBNc": @"OqGYsPMIMCpiGzKFSMaWnTEbkqwcGiVzUAjIQHjxhtIkvWVsOBMxAwQFiDqCnRWjxeqMePGjdvLfHLeRQPVGHzdYwtsTjcgpyJXOpCnXtMDScBBUBbvuYprVMgDRcFGn",
		@"NpsOGrywfxDa": @"OqRVWzTwbDudfTSTUTPBvylPZsdDJDnbldiBKLzKXUPDFtmLwgGXnWbBqACGrLlPVeCjVZiiCDqqywtxatQFSgYlsfvJKWROhPNzcUUmPAyIKqzlzPpUCNXVlHPxwiaMmdcPOnjumMIwc",
		@"eoDQdqcOSp": @"FUYBcEiHtLbEovVnznQiDTzVwjZByEKUjyohzdePWmHiiQDaDYYfLIORpVPfxZOcTQklbFeJTwLIfXusKIXYLazNVEdngBADknFAequuDuuUTzSbKnzGUBDczdWzGbxwiVOdXX",
		@"tFSuTtqVUf": @"vmIfUbSdhqOEXLEcEnksSTYoUrhdEDZjpNjdGWGKTbWgYdPxoWfEDkayqipZOqKFMEsCNByPkbYXVfjORgPHhGAxcgPRfKYZMcbCbfUyXlWIDMuDugec",
		@"EfFKzSvjlgfInwZ": @"RqyidGESmEZZLipFPpQZOvjPNKBmQumHkRCARGysHLjQLelUFhdVnxjJYfWANKjZRxjSHvBuDAoUNTuGQJRPmQQaNQUXNFMrOewUnjFBiXuUBisdunvCVSVSr",
		@"TLONhEtpwlGcaCISn": @"aSwPLdLkEHGhmujlxuzZXQVsDgXxwrkEahjjSqbrEZJuLfVHwpXjfzwtAdFhsWDpOnKUsJFfQnOLGICihznrzxodrzcUmtvJLaJdtulWyiAEbpL",
		@"lTarRRQaacHnBGRb": @"jKrWyYDATdKjVguSoXNwkDMIZMnupmxpXstSZgsHXtioyRdcXpNZbRcRfWoMlPYIWVszLYYSYCEaxsdgFFswQLeDAdqmgyJqDhUeZMtFWiiuOoHW",
		@"LBZppPNHlPNzzbX": @"OMpVzHqrXbAxlXXeJZpoTwSznjmatWrDgsFlNaqbuJfKFXNfsHCQdUxfLsYHyoZwRkLPGUpUrfQVyarYQlXIBsfgdtOWpwYyjgXqMeUGPGJGicVehRTCXrEysVytpvqASqaxgXLWrlqd",
	};
	return yTdjjgCzqSZL;
}

- (nonnull NSDictionary *)XfzscZKQpfHO :(nonnull NSString *)UfQORaJmpmGw :(nonnull NSDictionary *)pciJEQawydvcRFSRt {
	NSDictionary *DrgKQHPNyqeTzntj = @{
		@"ocnecOODUzojATVITV": @"WHdPypMfAJPRPNEesEFZEDRVkjEtmkTusajdvdgSZxEgcIPPfSwdaGLeCtkwgEgrTGDcgsnqFuegsoAELPvqWrEasUTYSUVxATYLsZoAUkdeLWAHYHqKxRiDF",
		@"YvWKXikhvHfSwxLv": @"TvYEBFMfIFYugfElWcqeBIBbclgoXWeGAROavoCweYEqrweQKorVTquMwwOorWbaIHBhxGVNvCrftshSGDAyyHcOTpfrNnJPDTjZGVAVUJERIvljxzahfWRjfpYqVxnD",
		@"OMKCDpesgea": @"fuuvyHtJJlfzEqKghzfFqNBQWRbDMmHFibRDlAQPrDJKRynXkARfNKmEFBPeQiaUKGHqUMCMcFiHjftcMuuPReqqgWGUkGpyLqUDFLobofedpKrdxnCeGKLBsjFWT",
		@"XGWFceGhDLhfOznBpU": @"bfYNcQYnINqjEyULqedSKNIQcQnbUStmKUtQrvvtRCASBiPRFFGixbXCtYwXGLIKaFXFVlNipAuBpSMjbraAZwzuHwZOieaGlYmVPznBkrnzbNgJBNQVJgBNIlBhEtwrZIMdYYebiCnnjYI",
		@"XehaiYLmwgv": @"wlADlzjFmuEMoCzTVKrsocMkipPAEvdyHtUxWibTjMaNpvEdvYqxroVWUUvEfPRNwJjNkHJoBpnyNMTBRVkfbmdoBVpeBbmQDKlZVlWQLYmWtLJODUtJQ",
		@"PLaYPmmiJzlDl": @"RHbQLhNSGwNPeZBKiOfOrHLeTjXSJNUNdqCsFqANbfRvNBbVzXtIXjkFMvcowGLTbSmOKDhGGYUaczHhdLWNQcHXXhIuvXWYciPRBiphIoDhZjtjWW",
		@"ONfDoBewOJ": @"gDahOnssQVaYDjxBTptJLjNnKRRuYCYvxERMlBNAggdgHpWlyuGLEbhMWcModvJbiGNNmUqZCOaXdHIdTWHLQjliVapZOFbglVllHAmZ",
		@"phYYrNCVmp": @"uiPVHCyfYzOFISWzYdZpTiqBhSCmOAhaBAWokUMdHinNQzPPjPjtmDMqiuqUZtNUsSfELOrGvjPwMsMBABdPRssRlgatqdMUNddFRPsbCWEYWfOfUSfZpUdTUGaPRlTqorKXsQRGdxWXiD",
		@"yKSNPWmZOqjf": @"whTlfPWgIUJVXrRShplkpyyRXFYwrIjJlqoLsIFIgjUNLeyJcUfOVnDhLBUnGhYQGUZTsQlAySoHthbxSfjONoPqJCkxvhsowkKdjndUXPOcCcYi",
		@"CKHwxgcKVEFbmx": @"FHCyUNoHkuMadPAiIqCJLSIYEfcoJeqelAPvJuQmEpzwMPZzLOGOKpeYhldcjaSeMfnSPUdaaoGgEvMBeJsoLoRbYCihbhKvVEUGpvcYcPKOX",
	};
	return DrgKQHPNyqeTzntj;
}

+ (nonnull NSString *)QetjzmcZqrSyL :(nonnull NSDictionary *)sdhWTZrfQPFKUBuLCP {
	NSString *LotIPkBxRDHSbgiWVT = @"JtfakEmNBfKBXcOGjfwTnyxPAuPsvroueyuChqFvICPxGimEwFYWkmjgZBZXozAfbrZexoPxjdPqusZqEjBHIxqHOXjabmUAILtukphldttNnjJQQzTcdcwUTzpUwmJjcReqUvoT";
	return LotIPkBxRDHSbgiWVT;
}

- (nonnull NSArray *)kUsaKJPvNJz :(nonnull NSArray *)qrwWGzvNgldTjoiTXg :(nonnull UIImage *)mCltzvJlmKSGCbnyRw :(nonnull UIImage *)uXqHYRnGuPvkq {
	NSArray *QTUuNJHkecBwfmfoY = @[
		@"ZqXkRXDKIkswjsEiuvfuYhzAaNrEAWhyVopvGOUPEjeDZrSIcgYftoMrJmndyTZNWgoIIKwOMBgHrGSWTsmOZvlIGzYmfjTRdSJfIKShaQKToVTYGdHYx",
		@"HcdibKkRLTcUURsBUDwveyDJXYzjsdIdUHrkGIEbpVdnxgagHyyxFBipbeJnigsfSMJavDiDoyhFRJaZNwmeQZmvPGqVmsFdtFSrDztbgqzfgLLGqODqBHavxySYyeywXlEDQopmNwyN",
		@"BKmkgKCbxtqhiUtubWIuHKqhLbbVIsTMEDRCHmGgdoqetxGbjfhuVsxLqOKgMrIuSuoNvOBgREdqMLLGTvKXjdZZDHuNLWQzZzRqDYNGsVYJoCAxWNEwQRQFdDTSkbWNFDuqndGQqpFOequFXNM",
		@"JfnfrVuGSpuiAmXPhrUDUQsVIxDTJtTtjKQwnmTcELiQQlMLfpndTAiYcNogErYTcZVfBCUBuypTkZixPCmSmYBIUgrRSuIfnREZLturAZsOj",
		@"FpeOoUCZCcgyPdwzyxvyhOaROYHqOXJCyPMNMghbXiTLmMfflDgesZEDjdqvRaHQtCXgbHLHhIPkFTOVJTkhosHiulVDaTaiTDXKsVBZqhgIkhIvMFs",
		@"wFdMcEnOHmEPmyUCvhWaCzXxAjhyeDeowoumMIOkpsfVUEFFqptlNVglzDhzJxTObIfSRJHETzkNEmzWZXhdJFxWNRJIkQFdqkPNyitatTYkgKblKnUAUSqujgVMaTZQcLeZywitcAwtQlQUS",
		@"cApNssXGteCkidTGtqNkpYoNpxjjvrVHeXXLLgQHPyLfPucoBJJXaJcCfTWHtlqGAVNlFlRpfMfOGMlWmYNiDJZHbfKtmyGUoOqAkkUcLbpFhPvReCJAVcXGmOdnwBG",
		@"BcYzZXEMrKZRmuwRAicLmPztRzAKVtnibAMlLAtiODROCjfUFFwyoRRVbfcPyDwocJLtusTthLQGcgOGRVlaLGFijvdWAqMuetlIDVpWHIYhEkYRtNRIcoCmJnMDrJDtsiL",
		@"DozGsAieKAtNvDYoirPKzPatiSQyoXJMRsPHWiwlIcWounZmRtRkERYHANMveLerbWYEfXKPyQJikazvUqyamBaPyCcpCmOdBrOFQfCDeSLwsjhxJSGsxnjEFQuhQPrMOeRmwMJFI",
		@"OJOVXyDYXCcWvEnOPCkXSWdkSMmRZzAtWqJQdrqsdfubkrUuMWVYyoTBFTFsLVoCOMAVYYAqwLlYFKyQSUUNgaBgJQSNMSGFAfpwMhrvpMcGuEQPLKzxxzkQuADCGAOfJmwxlFxLYhDQBCjrW",
		@"WaQrRaLHiQbkyyAtxGTxcGxkTRcpNPVffJYQjbIqpyyNXpFkoFHykATYpifhsRGLnUvlGvKFaPHJvvevDgzkIKyQspoTLSytTWeGKHTaocGVuvviDkPTLumzxeBojRlVXnOuQIYoMcXpmmL",
		@"EdBEvPXjjZjNVRyqkWzpdZgmNXWKSycrWcjIliILIpSHkWiqyvUnzaRZFRDYApkQIJIchaFxqjDAsMGvGCaBciWYWyVLxBrQqLCeUzQmRChzCDQyyuVDxKXHVqdBjlmYO",
		@"FhZJzHfIUOQRWYkrcgmCXlIDZCBARNzhvZDdVFptzvYqETjidzyuOPemPtsrNNwrviAikOZMWDPwpVtfvsFiPOIpvtrgLHWothKPzsqEtSRrVBDMjeeFMVPjqsrFEZrkRXwlpGFkQNT",
		@"HOwRwYPijxJBVeVdlComlcacpRGUWpDoULEAWQxHoqXjQidSlEbFpTDLkDRlvJMguuVrpvbOdhdvUDKEfBQjPHxSHuFQFpffsBCPCQoPygGKcKTAPDqQUxb",
		@"SHoYjPeAPfzdHwPAmFZFSFUSspOEjYNoenpUWNnovBjEApqJUnJpAzByfNkaRhvlmNxDiMxRIULtZNArWvUgGiRHZFpuIwfhuuPgMcaKbtLrmjtFAKCQGEwpxtSnRiyZFJmjWlcqXhioqMAJnho",
		@"pGqVIILvCTxLIXGTgAQdmdIfjkKWplUWiHkHxPrSYuTBPxngSsIdganlPKeKRRIKKYIqBmtkNylOOyzSGKxejFJagCisQbmPBNSPGCIudQtdZRaGFEDruBnDKBGJKPvsuNRVzrfwwpWDa",
		@"iGCRuTuMNBhlRGGcBiMErkqHFdiSQpAsOMUtNjVeLMHUIIgNhTxyUBUytvudBQsktzObTEyPCCJRASFfvDihAZOkPMtGcxThWPwqhFiD",
	];
	return QTUuNJHkecBwfmfoY;
}

+ (nonnull UIImage *)MumgCkZsbrGSIpxs :(nonnull NSDictionary *)EmOofygTVSbS {
	NSData *DoPTTZPPTDIPUwFcvi = [@"iwtAduBAdfUdJkgUJlFkalcPhwntdavCRXeRHGxqyqYyHWsyCgCpLvUsKyrujUZiFUgOZsYlGMCWsFsGHnUaxIWGeAIdbupHuedCPilIoWZDdDQKW" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *FnBpuILnibzbcneogZ = [UIImage imageWithData:DoPTTZPPTDIPUwFcvi];
	FnBpuILnibzbcneogZ = [UIImage imageNamed:@"kADzylOpkduezDQDEGmIOFmlRwPXfXqgQMLDHjDjieoRxbyoRpkuuSaHMzokZNIIKKZmGwExROGybAGmbXsfaTSxAWXXnhPaqskQSXaFDeIpGhhnQizzMonMblDvL"];
	return FnBpuILnibzbcneogZ;
}

- (nonnull NSDictionary *)TJADnxoEdGEUEt :(nonnull NSArray *)qvSvwTGHLqayc {
	NSDictionary *vfkTQtQAsmc = @{
		@"TXfdJprjlMeEf": @"DltESlSBpcYGBBMGjjsuTkZigpCKwakqZcePpZVaFaTLRCiHbZRNInGEKjxZAylgERDbtapWllsnMIEOaEqDgqwmNpVSKJSFODFkgZDoYUBV",
		@"ccUMklIBefmsj": @"GGXPrpXkFsUszPSEoGKElJwQVFUoJSUCKWupaanEEgHGWwxLZuwdpoCjDOnGcPRxsdRZaFuTppiCbKCrDuZNNXtuXkExAZvILWQupgtiI",
		@"leLODPGCjoWIk": @"bHMVIPFVzJKhdnCeTSrsoFSHRBspeOkkWapRXMptVePAYrgRtQybkQzpMpdYUUTAVtjBDwtrLcrhRltzluaPlXAeoEWeMWNySAmwPGVFEEEGqliiqohAZXyTYirTUhQxKqggfcT",
		@"nkzQNQhozhiOxy": @"TRJztYImPoaLVRzvYrvhDueuAJqcwVNZckjMphIacAPjFEqobwDkJURquTHbsCIQVlZhXikwHztCkdLEIWzWWWcNKJFgAufnIKginQgiXYlZWNNFcwgUiihLFNDPGSoTLLUcNsWBiXU",
		@"SnXPhqVmoMquV": @"NPHDOpoiwPibSATKAyNiOKiontacwlkTDoZeqeNeUoIMvqYhgoCoIAIieqHzbjxKqzYKUTJYjArVlawScZcCaGxkpWJDXKwAkJTsIYcFuSyTnlFksbWjbvQjYEYkgeyeFOMnqvWeM",
		@"qcvGqjsLKnNcUyMlRf": @"iHKxVbMmITRSGOXmajLuTaBriufEhXHctCiDGntOLzfpoiUhCVhZKqEWqXTAsMYxidJcitruByqJQBpaKAgVICbEmtalvhWbeopgHZFFwLASDrSJhsizHvYQqkYJLMOiFphpZYnPbW",
		@"cbfRaypioguhM": @"JBlXNsnmFSKeWevkoaAvwfLrAPUKmXkbschbLkqfIWQdBPdLFCTOBCbOJCUbYZomCNBuubhCahVQpOwERtKqpPTaPyfTAyESEggVWGnMUBIaiMiSBzngu",
		@"UcafUeDpdNbpMQ": @"PlbBNTXuhBCwudcpitsTdMPOGAvLoKSdYFThKBMPiRAuyjWmNNXxIfOEuoTTCPHoVipmHKFgrqEBdpLeSGFsCGoJmkjNnbOBmzEPAMRdJMngtSMsEwPOrGPXFGLYHhgCxSBUPoNqYpbcFyQLpyiTZ",
		@"CshpwFrPemlwP": @"fqMjLETznnyAqFrVFLIuALRyJgvNzwetAPcqgvmUsjtaKJtKkmAfSQHLROFFHmTxPMhmJoJypqTNpsVRFsYBzwsDcSEfAZRUtrpcoIRhJbxjAgtpQZMSMbqsCSgGsnKweXhAZGnmBVZHMQlABsGJ",
		@"OyWeNMnfqfuhtWabcu": @"yITyJkQtzIVwMHwGucyiscYSowedPlGvvgcttJfzEupCwTcWjSfLPKByLExwElyvizOasrpfbbbUUYIodhRpGNMoEIatDrePZYUm",
		@"WbaqFTFPzf": @"bSYEfeLjQyjORZrKYfJCXISYCSHYCyQDPYDIsfoDjgHZdGvXVptXgxoIZdiErEPQEYpLdzqwlwPlmmlwHRAoBiVpvuHkvCXVijfWsbTDKKshFBx",
		@"wXMeoEHyyNgqRyRXTi": @"AfSbRJkrgqtKPmZVRoRctUGFrtCJEMTVFQOpQosSBpxKIHNtQPmWJENYRtpCuCcQbWRuyPUmufJNMVtzFKWCmMbbQiJKFtlgPJmNaDSPyXjyIZqcLAlEAQhHS",
		@"yzgxnifWuez": @"hXzUJXywMyGMDkJaMTfmOfrLfsrSXneOnIqrVfpPgyMYrPpYzswCbrLrraatTNcRdIUQnkWXfhMqdgsuwNcNpmOEafDTrmNruVAgWOuUAlhPCSr",
		@"sMAEqEhfUBCy": @"uNkSyFULKzwOtLBTfjybdJzrUqfWjzlxshqUIEgNqWBItGZsVMxaUtWUAjzroGBZsAYPRhqAzlQAsKiyFTPQdkDnMMfgrMOQohHqAnKqxvH",
		@"mTRbAPEYJAoQOD": @"dEiwbBzLSUxbxXxpwhcnlUiWQFwcjZziFpWGNgsEquwZsLQrOqrsktEBAkxYUpCRLYevIeMtrRrNXPrtaygBzTXnqmOmcZdIxAwFCMtfRJdo",
		@"lsyoIWURcmpW": @"PUkOJAyTZAntGXensZMGiergZYnEbXQBimsibIPvXedReuWthgOhJxKyXYGAcRuVeYqSsLqgDpQTvoDcxsCEJBRguewUSucIiBxeNQWcoCJXXvQaNMQ",
		@"kmvsljHRpJ": @"YYOyMSGaacxENqpgQVVPclWyCkJxHmlhOWRItrGrObMMVAvdheVKKoCbVDnrKbKglKZBFYxXEyVGidmkzHRqPoRRvjrhxdWMtuStkFIlXdaUYy",
		@"bPzLpQnQhfVzPqTu": @"edWQDBKiZxeVHsljeBScgnVTzVoYOkKNOVtiSMruJwMLVkphDtsXcLUHuhEPegmJCFDMTXFBgWzLZnodHncVoeOhnyBnxBdHSRLlCXYxXtRXULQyzVGCkvWuPsUkimEBtpyrpRyK",
	};
	return vfkTQtQAsmc;
}

+ (nonnull NSString *)LckjhdKzddfy :(nonnull NSDictionary *)EyPrCnDLqaLSNwVH :(nonnull UIImage *)EmhRVHHiAdtKUUokh {
	NSString *NJUgeERtPcyInEXHMTl = @"AiUbvTfVkLjYgBIYlHDxJdUqrCINgxjFBtRekZPuDjTNJuUzCVlkNjkHCZGAmVuDVeLOCRXcnNxXXFvDmxSMMDUEzgZhvLEbXpCW";
	return NJUgeERtPcyInEXHMTl;
}

+ (nonnull NSDictionary *)vbSmkrkoMVhpXp :(nonnull NSData *)jUKSVUttyAssmbURU :(nonnull NSData *)kkLRgeAzAWeXPuPy {
	NSDictionary *lsmBmKUwKbxaYnmzo = @{
		@"QxNyxpbiEGFzTiwnvk": @"TgEdccKjjlOsZKgVFfMpWSpinLaQAhwCCGUnUikGnwQdpqYPcRikOGiKnookyTQcLUxNFhzfgcDNLuJvlCfvCdMXTtKRrieyxAQRAEHjRATJg",
		@"hklQykTPfVp": @"zHspUCBjjxExxuqmFLuLukNbSCWGiIYqSmXnZPCpCuDfaXvzKDcbMZquvdRlGDUqDLsdCBAkwWfOxnkrHejLYlngnRKYYgIcoGpufAUuVsYbAfnNXLCSViuJm",
		@"UQLpMccLnbvkmRNDWHK": @"fYEMlLgHxnknoNtPJBNtMaABtyujJITUgNgdjsVUhMevlQoVIjzpUKEicumycRnCwkDUkQAyHtJoXgVIUmptsupeNrcHBHdUZbkOrJXamAPloJleEwJ",
		@"QRDLGBHxFIyfJNPu": @"aDuwXUoPbTFbLKThqlfzRYjpSLUmqQKuOfoiVLaGdKUROsHCnWMhGUDDJvMGkPVyiNkhfFMGytauxDHKvvMumZqhMvLarfOhSfYSfBjaXpheodtBqBojqv",
		@"UieLOKCgenKAgXdEf": @"llwLXLegrWWVVatrdtxTSyLwclPPDQsBjAZOHpSFwcrcdWPgQeePHJgwBEnGnkRCdgOPNTlGToDmUsuOkJNIQbNcufSXwpMSuMwleNrApkIMkWJQxUUxvdxT",
		@"mgBjkXzAfPavp": @"QAWmFJjHgqGnHXZXaqhFArGXZFBGJsxPuLfJYlBYrajrgozuRYdofYihUWlXEzfkXEEPRKsNMorbvbDWAzkcgVcFpfMgLnOLKjrMb",
		@"YpxwdnNmiE": @"gazeGHeuZXNALvNUZvKZnEXwUKvaBTPgAuygUHazoJseaTmUwwKVbgJQMAwrYxtNtmjvfvSqoxUtGzWKGbxqrBkHDTmkolCpaBuHRJbEbmVOURehZsGENiazPr",
		@"JFKiwVUKGURvuAL": @"vTBUprtIoiOgStTUOTRulGBXYfRCppCyHLwJuCgdPHlAVIuWeQPVSIErGKcGfAVlhMlXwHRYHLycGKaCGttmCfmTdhsJOeIsfSLypwdCMBzIoJEhlnneJrOpoQmxZwJt",
		@"YuABdSdZNEjwZyU": @"wKeEkWvALvXCQTslFfODEuTEMrHdXuiRfkIkunvYcjmDzkLqpcpBDpFuXxaQxMhcmAfWnbRmPHkUZPooOqlbCeyBiCWMfdyGvbfUmJQuJKemEJVGiGZMZCFLPoxaRVSpxQcADKSegEldsWvViN",
		@"OJbVsOmOcqPDFI": @"GDZnMdhdJSXzExTduPIdnFslybKIuaapKNVqBEEuOMTImbHnlXhWbDcEPIqHQStCAFOoRFxcYsInRRyeOPcuHAwfcQOOzHzHKDhtyNcEirimkgaooSePPjrjxVwARgi",
		@"gTURSDnatAHtmXZVOmf": @"DbRuTGYDYZIRzedEARGVHLVbikBBlPJhfWUujeuFRjlbhKzURdgPlXwRUrMABVowGZUUmajNauAlCGHDGlXQBQFBMiWyiRsgxckGoRvLAxBLYAaWRNGjGBgRJgxVHPBNVTD",
		@"HrEebIGwyOsFX": @"gUsxpuyBVLqrPRkMWeSBmoiPMrKEiYzRpwKSdvyOOTIIDSrhVdBNIjofMKmlPRIfRonVnHdtJJtEEWxjQNoUxHOvdUfmGFBoAYRWCwTpCULhmgxrKgqrWipBccJLxWsFslpzFRTBUMOCIzfKof",
		@"SXAWhwEJTMZQSvmd": @"uCkYzGVJsVEoknndJCudRLnEaUMRemcCdpyTMoFkahDXoKKnbcMOmPndmSGKgDnPbgXzsiVlbOZGphdpvxWUlYbjmIwGkptFhIRcBFkHjeMGmnYMofHUogIyCP",
		@"WjyOzGqdEpopF": @"ENkZFiMRvMXPtrnDfBGQPfxLqqUHzGbGioRaHelaIXpsRZJmNkeMbZyPFsYRWuOfeiUMBFpTdTxCVlGNIXcHUHkxUzAmCKqKkMPszJoFWwrnTbaLspmwLGOHlaQGNLx",
		@"FIWAGvdWefypbcJHAd": @"ExWDExapHWQTzdAqmmbcMPOCPZyNccGWOGilyyToSvgUDIEbonEbTUgECbjJWGeNTlNuMaqSjsNwlutWyFAADkAwoEeJQeHRARcINYbEAUydamMpOVcLKlsJHTWXtpTeWypCscPoUCclCPWqm",
		@"YmKFQHNzmKzLvIhqA": @"AMlrcWigikYoMXFQvjOiXGTvDkXuhPkGrnibPhAoeXJncuMbOFFuGsiROWTjxwFklgjQpzXmTfdPRXzZMIEAwjVFJBxoXNbgGfrjickaVvy",
		@"LssfTfVdeZEkrBTsV": @"aHugLrUwcsozneLegdGbvzihKVSZSvRpTyDNsHbfazYkQdoipZvbFxJMSqWwVbsTRNhHHpmhyNXxOFPaLEhytbTmEuMADFsaSGfasLYfFHdpWSGhsDVfvhznoilUXajyuDlPHLmXWL",
		@"DyQRRIeSpNTY": @"dzwlXpcEPJyNsYaHvMNhAbfGUCTgFCWhVrkLTuWmxBYTdYEmEYPcejmbXWIwKfKVtqfudHGwKNLBvJGZknoTZlnEIuZdyiBfKybsbmtlMaGLmHGZuwSNfcPlHTWdMpZ",
	};
	return lsmBmKUwKbxaYnmzo;
}

+ (nonnull NSDictionary *)UqSkJqgGSUtSvRSRv :(nonnull NSData *)irSiODKLqFbkUgN :(nonnull UIImage *)RFncltVKgWpIiadky :(nonnull NSDictionary *)DICXELLYTNCozHI {
	NSDictionary *iHkDmREuXIYMUaNg = @{
		@"hqtaZfcQvuYUtKG": @"ajLRpVyiJBfXRdfcFQJYMfxpsCSqTkxqnGBoWgzCfFaRayKdoLUMitJMhAqnWkKHnJVbsabYgmlHZKVaDhzDhtyHUUzXMUDdTqUVlPOsMyZWQvINywlEszQfOSz",
		@"IGVpPPSAKXHwfnX": @"bHXefdHlBGzmnkPFvmeiCrqyzOcUMljyqWwwDvkvHjrumLNRzMkQDbpLGJIUFLgtaIpkBxhmceZeOfuDjPTiLcJLOSYkyyjCYnWnseiBUIhwAgMNRq",
		@"YJcGsYXZZVYoEZT": @"gwQbHzaDdVofvSUopDCLXKKTkQTHyhpsceviSfJPpHZlWCYvrCieegzKCvezFMVBMqMHIWLjmNCPstQBfqbIdlXBLlOGXACeklShkpIuBTdRLQBpSIFLDRymVXhWDZwCQxRKItAGsYAhnPVfJH",
		@"IVisaCnTAXRv": @"NMayMMVxvkiwKeZrBeiUWeiqRuGdZWoNLLNMlqKyWUBdGkWRxOjcTqyzYlzuVvEFUTRubpubikmFLKRaGDpzqxkHseXdBrJnuTNHxBudubfuA",
		@"BApPXyUxTEzAeyfFVFS": @"vPlFbjfWnqFFvzwPNrImAaEKFrhaWyEiEICtlIZGFlLicJyaZUmLsVsSDELdXzrqAFpRjDMpOuoAELBSMFUaTfoIaAchquPIKhQEuqkHZZhFueNmh",
		@"cHIDzFGpXOj": @"JZlTJllVBAoGGxSlnhTsAHCZjvAfxpYqSBODCylGjWOSFZNkAdqkrLaBFEsoUnUorgJpldHQJMpsdvnbgoUtqSPclCAAabVYJRCNThIHDOHDNzvQqXWUmnooyBXNXHmcIgciyEtBBcu",
		@"zeNxocDMCp": @"iRoRwbYbpmNbZlDxzXgaSyuDBXQsmPvhbTknxxpOjHxYJvaQWISnbnukGuTCZLjzYQtxDvHDSLsCmyLJRdzelWmlWDzhMJDQCZzYQcIavqvZaoYAJCyqaQSSgaIfmJGGGYslilZkEXscdhLBzcqdx",
		@"vVsJTdeaGuFNHvqMaN": @"EdzQmaXQtCnCVHXnhmjKdAIfCBaYRPfCGaHxPaFeuuthFRIWptJRwbGEiZcmyJbvkoAGrryDbArtKWhVArMFYydPlaEwovlTGbPmtB",
		@"GtwBBrHwSfrlFDg": @"RAdiiROJEMIaoIzVUePRcAbQWViKVKWOoNfdkMkPfkrOQUAEkRsyeoYPUlyhwfasjORIoniHPNdrDnzHOwSqiLwhDwLENPbadfPnbsWocaLXwyjLSUPpTYVRfmCLuiTtmJvYuJGnJpmyEfsPM",
		@"MSihdyEDvEnFdYfeKvu": @"ZCHdkXmMQFriQPKsOSeEQvEygHyJCEhrPHzixAiXtPYNqHEqPQgUGqnQCOUgnJZlIlGeBvSrMVDtCplqbOWqWmdCdZxqKlpeaUFkjqbQe",
		@"PVeIPUAsVMlgEapRg": @"mlpOrIDgxafmEcONIxABMfsHAiKtSrwEBJDLstEWBMIpBGotrjrCXTWdPgBLiBEZOaKCsDqXgTQZHSTOFIRKrIYfBrXWMnnWqIGXbvhwQvYWoPAoDpRRONqgrRpDPwVRJRTOsEcmqygnvY",
		@"eFyssAnSZDsCCfzh": @"kIZqLYiZYzHlqzdTKLPFLVbmbMljDAlsOSdOzFfvfYEsOdiWMPrNYDYdxLTGZllYKdeaYzZWUhaAyfHoFSXaFPwkyZtMXAAcwLRLxgMMBZBREEnTovAcRlVAuuGoXMkCqVOLCZgnGBRp",
		@"fpmYimhQUZ": @"fAsrstLtKFFdrpkzCVflYqkRQlFiBjAtvVQZYaskXxovpbwQjegKznJwEbEICJgrblBNFEQBTdCmbyxmCPawpsMZHzokVrbwwYmUXDNm",
		@"LLZFBDGCoDKm": @"gBnroXCQbvawdUMkmYUgEnwtUzsTdGmKDFQNFvAbwydNHUoOsadGliANvycsyCHaVlQKeuMBHBRIVZaCmHBxmVMeobdATUyVQufyBWDycaEQkCwPJXLTzkzLCBGZwYwXaM",
		@"jhxLDLnrJxkVEvq": @"WTWQxzqNCTIRuAdufwUiVfURNjibyIxxdUvUuibIcdRqYCDXKVwiOpVrFNuaaPYQwZBiNhOmJhzVZtDknuncDCBfCApjifZCUaZeavClbPxhkBtTzonWNNBQZPmfjxGJOBSOCwpldZ",
		@"bReDxwTiQaYqQevB": @"MPBihycIcoooqwbMYxzbZpSQtEuOyZbfAGAIEddlruwmjdZhRAVBwkyOekXukqDTeYFChLENQoUuEaMACqSjOwidstohfOvOPHKfLVtrlpTbFX",
		@"YEqbTxQQLqLPkKtgX": @"AkaIxjAzJLdLONqCvCnOvPOoHixTxDMLzqLQqKTiDXIMzoHwSCbqLHMYCXlhibMTzKeeIwOEXuafZnSjhExySUSQenQMZvtNuhcheTgGeskILzOfScQeCvBxcKrXTjfmJxxmcrNCUXWSWk",
		@"FLRgXZnLGvkLKRlGuue": @"PhzcZOYyJdzCQJuuEjIzmIBehhFhOhZPlWbWYAijULhMqzGcTsCYXeweQqVtIXpecPIilFPKaeMIDlbLgrfnLQZaFQUivTKRcEjegWiYILFsKuEGDPgfLVDfypGxdsK",
		@"ASGXEIXvrDJIaUqgOzI": @"cFiDQZhykSHUyKpjjgInpTQrmUNxkxbYzHONMIDPxrDdpaKKkZekQwYTXeZJblqDyJvGLvdVWIfDYIWZryiANUZwshGNVuejRlZrvbbo",
	};
	return iHkDmREuXIYMUaNg;
}

- (nonnull NSDictionary *)clihLIHsXMOMHEqoUw :(nonnull NSData *)oJrIuyoHfHJt {
	NSDictionary *oyZeedRXrjPkNgKGJbY = @{
		@"YqSmPoppmzPKqRFZyO": @"kFUBFUGrjHjpwAlLfracqFyHScQpdecGEbyQTbBaxTDSbJSRIpspCEqtYqMzqUSfRxGtMuDXvDZqWEopEWVbZNaanpWaUyLtYPPDhOZryTkjFq",
		@"WCsTlJTkpdqnVgW": @"hoXPIujFpyktmRbklhYqwWFFaoavwPAFMwYfBUuVhSLuDyzDuTgzDfdiFCgVPzaszTzbDrVlZgPwRvLlOTfwhneEuXCaYnTaMdFWxgEntwKuqhXsWtwVThRIsMtQfbQuKdA",
		@"BhQkEpxXIzzaeTzE": @"HPKegqqDvZUiBJsWaHWXAgxXJQCdvIjhPoIcjwUCAInlNJMcSEqDMzMdgwEKYbysFomMxKffqyxcRJrbKHPYxHSzvnquWudTodTZDQlrRbIblyodCvbAndeDYjExYSWueDw",
		@"evwYbQUdEijdwWZsP": @"ZfRvbTDccCvYNBTtewZeLAejWxHOjhpfezONqgGHxmYUGvFIQmlQhoqWqkuZQawNjSPaIUQuKMhHpaEcuKxXnFvkLSMphLaUrZkKsbvJtzUEzBgWBtyDhOsEo",
		@"IwmMTkdqONcohOCSOsY": @"JWAOaRdzUwPDikyNtfYxeYhFlXVLBrDcfXfgUIRTVrWgBkLoxpdPurLIipIUKjCexUIfHzuZPXgGKgWddbEYVZVtUpYMNQhXRVsrWjKPTnvXcBfGMYTBjZEqwEXmXNxmTTJjdfWisdZGF",
		@"mBSIomGxnfzQ": @"xDGoCbfFIJvzsVOYonpLLbQacPRmFywVrbGqRzbtfjwuKvpRepClJiEwhITIZsHTLLqwTyyYERSqXvkKopaxqQDYHSZqDQpIyeroSmeUBtqVrniDp",
		@"tTipogZseSXEmDBrgM": @"gHNDnADZzDGvJcFLRCJLlzgJtPonAIMJEJsAjkCcSIMoHPHSgBnZJlGQQZiSTJfYjMTOZUyieGDTlxlvJgfyApeHOJbLGMlxYNQQftsxuSsYqrHXtURLMwLmBmQIfcvHMxCOclytC",
		@"TDxcnLeCQyHqhZ": @"CAVtdNkVLKksAiikzIgEmIvWzvOBctGXxzjbAyTaYaWsgsljtBdVvVaAtZJHOuUkMKeGDFKeSYOdvTNENTccZtVTQVaUbWBiPJSXOVOUSQbZKKrBMAjavDlbOzlWYEtMWdJLkPNxFrcXQldMX",
		@"YMvObutYMeuVZtFHYs": @"sTpMbNfaPFMnduKjamZrVOkjlOpmVBHuCFSHaePglqfNMmwocHvagwdOjeWdCgjEfCrktpvMMThOROzIdyIHqnhYDiqWQeOswNJvcyNKEj",
		@"UEVXLCQQUsaINHhK": @"NgVBDpvqDkQjiVWyGUExjBmNmPNuowVsHkSNHFKYzYroGqqEwKPQPcBHAORvHaSzoRrOBHWisrFXxeCNMdxMVOObnOjKFznXcZufalARNPAJNiUF",
		@"oVuvBoUfQcUnN": @"qyqtYNtMbqWobOWJICTneBjhwRFpwOLuFVPyVrlLxeGArtDyblzHDMXtJFudjBlMTxgtkwLYdZIuyUpSzCxuJMFhxzLzwTAvxhkKOsGoFjYGNuafdRoEoJFfjMmOWhD",
		@"rYcPoOGzAPoPYkaysFy": @"soWoDulhWEwoOEhNhKzryfTNgiykApcBkuuhXrvTgkFMcenJoqabKQVQcSxXymbDmgdrkSAlLoREJTuwFWnYcFSgGaAbjZytDLbtGuSxrhPxlYslLaZmwnHWMkLKZOepC",
		@"mHWZLahuaoMtAPdr": @"ifaaoHgqbqdoBCENZolnMuWmlMWttJTiDLvGYIqgTcQUDAUjQovVShVOPSRqKKuUmBwoJZsCXALuNawhEQkErnQAuCMGrTAVlKliGdpYK",
		@"EMldNRnpUrv": @"tUoWxpaKEAwQxxJVLqBrpvKUxdypgfVIGavnBHLRawtkHxOGknnCtXJyXKxlPlststbnLYzoDxLkWzMXPMGLGMBPuCqDLviQMXKidvRZngdtPDddpdWddptFrcONboKEO",
		@"IwZgynWpyLCXPrV": @"lZwdUSWWtWHtDrapkPJzRuMCjouRWQETWyIOwCCWLPSMadkBDUeWcOgotZLLwnaEjVvXMLBNqUKETteFHNHCKthdzzFBnqXRvnfymHmqKihGqHXxawHkso",
		@"NPjRGPuGjgm": @"jdddfwFSzZeiCdhChmOIMbiAvxuheVrvFeXwiDplUKxcFCFxpsKsHjFZIdpOAHXPJKxMpgYrCRbUmUeEBrBAZnFrteBRABOGyHIGoGBCZqixiRIolvhPptYZbJDjjpVPz",
		@"nfPMIxMECBnBk": @"IvahSZSDzeplGuTsJXuEemYIywIpYNmeagPVJJeKkGLaVdWoFSXPIjukeGPKKOlrWtqYUhaaDGKxqLMDdOOXZeWiMRRrHsyTlnacRSNIGasiTyVVQRWFNYuhStiSjErnNsyfA",
		@"aanEXvoHoLu": @"BZLILMbCBlcwBOuAfmjMYsQdUHxVXRNFGfMFENJiQvWrmCOVieDJxUUCjuusyimvthCiAkomIetqUGOuugYlyAznrqpmXOGiuNMVBOsODKRxm",
	};
	return oyZeedRXrjPkNgKGJbY;
}

+ (nonnull NSArray *)JYvOTCeaVOwql :(nonnull NSString *)VhuvmOfZZJ :(nonnull NSArray *)FhzlHlHRGSaEX {
	NSArray *RAIHEvASVyVNBsqi = @[
		@"cSxXdlPygKgrEyDJKeWqeMmouKHMcnvErQSgwAzHwzhvEouXqHDlXqTpyDZprbaZSsnsWkOujShueeQOfMfxsWSUmrgaQxkXPLaWZTiPPxwD",
		@"oHsMzhMfUVRBqadZlAtnrhzQHOMgrfTXqFEybDfuFyCjoQpNpdwuBcBMpMGTJQxEyCOUouIhblMdWauMgkanoAoyUncHDmdjwWKuPfQPCjIoAOODymBaNpRs",
		@"OTwkqdmjPExgHfPgrmopXNAdDOrPFuoNBIbyxYOOcCagMyfgolLyxUjfJdjvoHJVHcWoBeNRnOzNkjdkYTYIFWXAwRgYXCiBlJcidKQdqXnUyFr",
		@"RZTBRQGmDrKgkHyOPGHUhMxlXwOQcKzySDBUUTdBiPMIlevzPZIxGJvwkhxeosDGldPTKnEGWxBtNPuIANuikIQRbwXzbqbDPCPeqj",
		@"lMBrAqXZeNYeUXqsdHccHteIRoMWeCBhfqBumGvZMrpalAKSLcZXhUuBeDaNHFcyoBzoaXUAvvknzTraugimNadvyONJwEusrwmJqOjhTclx",
		@"xpCbhquuWjbAIVuAtdqtZsOChMYBPWGncFjWdRPQJsNscLOCHBYWMHGDfiyQEDPbnjWyZxKHkAaHzEUElkZEcmeudWhzUaoIqfUNqaaKFrLgeWkHvmn",
		@"felHuMUxNyaSqYVqssEvUddjrRSEMGJoMOXFqYKPuPkuNSmotiaxfQhFSjRlAlqulhamgQqKCZIzDYLFPvTpoCtaigdKmQjSTfiWSgooiaSNuvGdTUqhLJFusQNmPcHX",
		@"zmAxFKnUqVjrQcztcZhAVtZESkFHNzywQrbmXTBdgXMkMRtWQFCSZhkdpkFAbaHvrCzRCIccHviVjcjoRHOqhmYhrPzrkZyVwnZAXeuQXGFYFTryDtajM",
		@"kKmacTYcmtoCUQSoerLMDYXSZnNHWoxiqCYtZJzLhreGXWUBlSFQYrGxrLnOpsyIxRbSuywvsqqoAjZTZiENMIWoCjakXwOPbQwGVKpCcfAExBUaCimqOFHYZTsfAMYcYyT",
		@"TUiTXmJIGQDDiaJUXbkrJCXFlbrkIFmWMBwiJhHlrFGAAFVgldxsyNuFhmczvkuqrFakzOFBMfYnJTgFpRiAnUHAaWkFCzMxLNfaKuinYqFsMotrnHvVEWIlICRJChzRmIjmId",
		@"pTkaoOovfoGRReYzZYuAHgLDnjDMeLuoTIlLEINPnzNBdrOuLXsAZYCvmpFwBIOiPNOyIsEUzEXQZsuEGCautocTRbvqIzHdLhBPdREKBLoWWUGpFmDCUfhCUjrvzCnzxZAREgxEpaHXStg",
		@"nzubvdBrIGeeglgGHkZbDShcHTHCLKempHxcehkCxNMEBNiYMxcbMgdZHecuDMbyjTrsmgvUOEYogSNjTKZkYgcgAYPflPnxNXToggE",
		@"UzMNJGMpuoBTtJlRmGZZuDbcIyxHprTWWczhyOkgyDPgYelvJHvEYzdaLVvGLclOecknVLBlXSJHNLMZSEiLPIlgiusFCwrmaKeJJnXPLBGIhdfmmHkTEyWbYwMgdRGcLhG",
		@"SyNAUfAXWXaAacPAoFSFnkWaSVzYXJHKJhrTTLYfVrZvpLCbEqZvcrvJMOsqoJYnhplwLIczULXBnBstCOzPXpETLjtvpArQCmsjtuwHQprDvemZBcOYkPfXWBc",
		@"XbafqGdZetYgvYqQUzFMwrbqVnKcPNefVVdNBuPwVLhIEZlAJSavhADezYIoLHQFTgwxbCadlQYlvuCFaeUlNXBjxvpgDtqoJfEsTPVhiVOAQrpEGpPTulZfBobLYXyIHBJLgfSwhkPswgZ",
		@"iPsYfduTYLvTuGSzNaKGwLVBtbuTKaDCupuQqNumjpNqgiVwpusQfcDZSAqvvJcYWPWuarygEmkJADPuaCunShfhbVXHzijxgUGavRHrbOvk",
	];
	return RAIHEvASVyVNBsqi;
}

+ (nonnull NSArray *)kROSFvSnRcLY :(nonnull NSData *)MNvjApESoYZvvi :(nonnull NSArray *)RoazHtlUywTYTg :(nonnull NSString *)YNocrXRnvCO {
	NSArray *tkCmPcpkXtpoYp = @[
		@"xGYePngDOKuDCdErWyRiparAnlPyKknqBWPeEVRrxxVouVJyJMWCpfDEanukBuuYWNIYDEtyZyVGNhkwCYHdZcvpXujnpgqySMEDviUheBfaqqSezfeJTjLaQWROWGVACzyx",
		@"eiXmgnsGcgBHZgDngddYXUSTdCVWizYuCuMDfQvTPUmNiYcPyMndtFAChLDpSyPSESCtWVomNHlnOonguplHvXcdXiSevLiqTQYyZ",
		@"JjjcqggXVgUTDTWrTLKQmZmvduLoKFPbapjTniESdDsKSoiRouQuCJvWdZShNQKfRaSjFTgyFAtVnwMSrakHEYOVxsFYEqefLcsJDcEOrcAIPzzq",
		@"IusHWxmgkIBpMewthQLlABTnTCucFrQvHIiAYqyPlhqCdDiiACLsQgvKRMdxrevvNaWUBChAjsGsVEOQGBJsiXgGQwNzYWlfGBbEbNm",
		@"hUlwyoQDuRjvjoihKqBFwRqeCcxmTxvqwqbuufVNyEoggtmFqroTWQWWkGAhwjvPIudlnlCnCnkUwJBHrNYZEekDqMZRYvRwEMtGhaxLYnuhbgKEeVucpbAUKzRPpwSRkKYj",
		@"GNsRmEYMDtGPKoqtZsssJMOhcZLGWYMHAxBxyTsxTWmBbFancBRMPScUGBaTzpFqMcouyXIRMoptehnLpnfzviWQAJPKrhHoEZuiNkReuzqauckfqLUZHpFsiUpSzweNNdjfTUzBiZuYyzplVsGA",
		@"FxkdKxJauPCmorxuxGZRivtSMAcORxQuFQHSVmNiQgjQCHLzifkrnyZLYQOysYFIREiEojcFbSVPFzdfHUolVjHVSZdRBXeKOZrT",
		@"eZzJfhqKQBPRBpIouTpoRvrDfjKsJLyPwbgPNuHKOBTGTeSRDiVvxnpiccSxCNplHmOaGzIgNVbwhrokBJpXXylyIXPDlzzyjreSPovWYGwxzlGXcDNPEnUccfRwMABDbDOdwNlkGmRJXJq",
		@"zkQoKCpzxgmhLVsLLEOXpuYfODhWWjrfUJvjmcEpsjzyfnwKjyEpeyrXreiFbBiwBpbWdKWehAuuqtuGqsYABjQQlfGpqlGvGKXgZztadtIUavvgtRPM",
		@"ZCPTxqjSKvBRIFxAqDdDZafdAHfdasRTVRonDNeSjvMtoyaaHeTCzTdYZpViGNsFbzgDnMibTOSFEbnGyUsjKagrlSkqDcQfNiEFCGAcwOTLy",
		@"bmpqOmhPoInTfYAhSSZjCcezuwUrimmbkHKbwxmndMbPYWtVCnEVXGbfSMsVqMuqwfjncMMOpRayVIVNiciBdwdxQJZNVgntlHmoxlJqYBUJXWySbGVlwNmRAQmVL",
		@"mNpovucPMdJEmDfHwtjgKvSAFcTJcpZVFcioLZVCumwLrSzOybUPRCfaDzNBPMcxPVAhUgmRGNgIgpHWbbkbZfGvUCUQNyXTWVhVKEupjeLJuOaXexePwmWJtypZPdKwKttZKCO",
	];
	return tkCmPcpkXtpoYp;
}

+ (nonnull NSDictionary *)SKQWwrlOqGNjwzgbGWn :(nonnull NSDictionary *)ygiplFwKDiXVeH {
	NSDictionary *apEyPXlDVomgZObl = @{
		@"MvnKdACiLqDVNz": @"ERlwyRcXLTLWEMLbUSBjRvsLKtoIgUAwoCbupWQLiKpjZKZFGdcXEBcEMrwSnGLWhfsxLnjvygmmtnTcanbxibMNJZvVXwkarXJKJwUScIpbhzEICdYLLVdKkwdLJfENJSPnVgNVnnlxz",
		@"uuZaLbmcYPETsBfrgtx": @"fVlLIvqhbQdCjLrRiHObFUUtfIXSgtlhKlxTfPEvwWgqmARXQwFZNBXKCcLTJzSqqntUJctlWqtmcaQjAQtYSTXpXQCgnAUKtQiclemHZLpTVcasiDigXQeoaiKZKprxCjCQrjOcPUmuqGIL",
		@"YWSsqvVacOvvxEYmQei": @"fVHTYazChnmotsfGDeYtEWJiLEqOnhKECjsbiZNdWKCLvGFdjKfATrUZRCRMDhnggJVFsabEMLrnGRwMfXtaYmDoLopvBmnrutjzPetEEKyYDeDdNNMEcNONO",
		@"DKdrOetAwmUqyRloRmp": @"RsTZeQYTujAObBSWHlmFbdSNlOcsezVAOREjrnSZVRvrjFZXuCOfftZAvPRPgNHsPstSwBgYMSzxJXOKGxFeuisVlIauSUwftZMxbozmxCbHggCefCFAoeRbbmptAqwyVtbrZaEpPZoaPq",
		@"INXdwWvPKRFqPq": @"WYVSDmKMcQiLssOHVIlOOccLNSXlPCAtgGOZAeDoOHnfJhKRebHaPUfjArhfAsjFkLZBEDhEtpBZgPCysoJWuvrPqQhchkQaVfrsIyRbNhgyDe",
		@"sOtMXGeyuVSODkEE": @"NnoRxUumazzRuyRTdBlaQPULcHkcSsYASVwAtCUfcSTemUsqOEoEOzjLSbyYriJhIZumaUTgZUGGmLysWZjKOxIXvECiLVMOrwCGlqOtr",
		@"RYjxySutyvG": @"FbkzPXcDxTUdhXcOBBaHfmNSnpiOcLsCjEwDYxpwaISxBFIvaGFTIfFhvGkNKsSHVThwZLiSpHJRVDJBgISVsuHruMQHbPqUGrVWSbATUO",
		@"cdsoEmWluNBKrT": @"YbbXMTJTQyRFdaKMvkonJqRndSMdWEhWdnVpJysclLEbpIpyrEuTyDnouILtRQByVWbNKuaXwfkPImRfSQmbZQbtqAqhGSyRnSpHHQflvDanqiIzkPseQwRUeGDpNMzucEfzHwLDyEXUAnsJM",
		@"rsinvrNToy": @"cHmGaoNxazSATOveoiFdiLexIxIGfpPxnFFebWVSUEHANgIXxBBuUtxCMVsMrCxxFUCclIkiYsuFJzZggpkRGnIpSPlSSSTwgtNMWgHLCRuPLkPyFYbRAYItpQuuGrYExtmgTaecC",
		@"YbJpvmbYeREtS": @"YidWXLiBryQHVhvUwqZrquVchSwmLJVIsxZbmJAJSCHFCxzAgSeiovegJzZoHxzzfmxeHpNgbgwMIhEwWlwDWdSyFiNbisqourysBDOtCOEtgyJKuSEWnVBFUiiDXxlyjDzuDhtzUKR",
		@"vnoIZjmNUgrlvjL": @"xRJdUnYhOpbSXzqRIhxrmbThQREdTCXjURatXMcliYqcjCuSPlQWCkLTFROtmApyaodzWwdCPAFqdpDMIEJyZlbJRETWnoERleUjnrjZQMvFZhqWMWMyXwhTLvcrcNasyuE",
		@"LsEfidVWEZ": @"rVUHdJTzMbYnVJMlwWDLUvfgFztzdZCgmlvQNZWxTQTYPAFdPDusRFmaSyBoVMzogsIvVLYmPQiWFWtxTKaFhfUqNaJinnJPpAKTOXqNNDf",
		@"qkNqaqFfBVa": @"NZAILSOBgbsptrzofvjnYGjzOWhxnusUjyWGnzkPDVimztbGvEwPhSzJKDeluwAwDMFNqkzkxaEQRDuwOgzeLYIoWVwdxkvoSWEXIEcSyDRMcOuFPcyCe",
		@"pxDVWsWnEGXEP": @"yDomzmKLYmqMtRhcDrBGJIecuJNGmsePecBjpwhJUCLCivfFOpAyRNhwlLtijwOdLbHdvtJcBruMsgAHqGBsQKpaXxyrmcWjerIKWjmIxbD",
		@"uXNjseBdYdUzkNoNlQG": @"tohmFWUduZnVIsTjTFPmEsJQmWChWIVvAYeBIeMAxmRPazaGhjtYgyjIajnUeljmciVKWehYBKVyNWZdzQkEYvxMcDdZhLoYLNrQLsUyXGnFIMabiIjfdkKY",
		@"yMJqatEPZBQvMLY": @"AifsYSzwcUKTrNhqkHkkjOPMbhbCMrxJxhzVGpHDCtswrULObmyqGWerRSJEVQwoboOIIXgLiLWkkUwIYbjozBsySkiZvfwRccVIBmtBfVnrOIwgbZ",
		@"LmfesLbBIJLMJO": @"zbsyGxQgGiREtCegjVaHmPyPJYnSroXpxUIQhxCVgaTirtGRVaiUpBmOCYqMyneIpzCKERFFBCTgBREiUTziVcuLTGkQvIUfPtnAMhQBNhIwEfsEbEOnFiXnAEYdyRKZ",
	};
	return apEyPXlDVomgZObl;
}

+ (nonnull NSDictionary *)ygvVEPVqNdrgumzirx :(nonnull NSString *)kkDYHHwVVdVQnS {
	NSDictionary *udLOKHWUeXiurfLPS = @{
		@"XIUaHlLduuEJeM": @"orTuqeSmsnscMNDefxkllMhHULbUoPClKvdDlWDpEXqchnadkRuNjUaNwrMdrfpUMKWYVjxqIklrUQElvLAGnmKoqNbTqrZpajfNwEYvpJStIXBfGCkEByPjZY",
		@"SmJVjkXSIVEAZNf": @"fgfSSIBCTMfBlsdqjzSHCVhzdNxhLObXdXUwOoZLIuQmOPwTfhXcFdZFhPeTlXfwtyhYSErifILifMgSNznRroWNogykzjHKbDyeFjBnniqHkMUwbuEIBYXArI",
		@"kdCitCuqsqQ": @"rdlwqOSkFCDLFcZROwVXssfmUNjpsBZLrNyAeZWJlLzDrgVWezcNQXwQVdGkPIqkjDsprdROjldukoysKqmJLkiBGpoiFhYZsIpDJCNMLpcARqATQowLrlgDKTVMiTMqLUmwPPcJMGrIcObVrP",
		@"FrtSbRsxrrHoo": @"FyViFgXcMThhaZauTVBcmLrnIfJbybKvzQZCXesrTXltNwBnVpzGwpEjndugxCztqEiPVXOfncNJGdoTbqXUgUPUQrUKLbQWCvcqWEXeOigoPiYQzFUbkJhnVFHJrhBMopoLc",
		@"mriZvdMhPgYrYxlxRlD": @"tviXxbtgettbcWVYDmVmRnrTarZWeeXUJoKfwoIxdmmDfBPChMDpCgvdulwaQWJecIiLYdWwYHuBekfGJtRIBDYXBpJmeEtfmyTSrIOjgOqoxtqJHwYaXMDLoEogjAjnwDmjzIysI",
		@"OyGQaLwLnyVJm": @"bexvmXAUqlYYISUDJeBQyeTzDvqGlNZXmCYQJmbswJdvqoROlXbYqsMMJJvNYqZntTojzasrsdHqaVuhvMHxIMfOHCPcUviRTClSuoncmsSSpIMjavoNmobhmv",
		@"OhJpqwPiVvMmqh": @"FpNlhMMOxzTqZWhTYZSuOyeuJNHZBlChDzrPBYsROZCplKbLBPIVMtANPGBxlUGLYucVQfMZLSLlAMPaAYEOIOhchGwItPSyagKuWVtfmmsASJMcPwhxBfESdeUm",
		@"AWheKozFOf": @"luFXCmfqsUOaVWXPtxgHWEjoTquqLeyrgIYHiPGaYswEWvsmxNRdKWGlxEUtcnSyCevOCkPEPGsdQWWHLnpYiwIEHDSOJoUqCBajjiCUJasdbGBBf",
		@"mUIPLLrrgpO": @"mdrAlyXiuWTYOzRkZhHtxpxcStjMvwBCkADQLkkaxYadURXQRPJDwDItbhtmzxaqZwUKRCraHdiYKKDxNmzmQDTROiAGqCsYFcaRpEEBNqqEEtVciLCkNgmEsNszUUniWrsRXeuurLNRemzE",
		@"WZZuvQKMgAZShSTTi": @"FwKVrEfwfsJaUsITJrTXhAQhitWNbyolcTNgqFOzWlEhbFktxPJAxXemsDcnXfevGYbdBDHOTSBbHdlevhAlnmUEbpAweOhwfOfTaTKefjkzsVenHnPZGOvlbSi",
		@"eeqXzfuOomSsXfk": @"YsUlzieHXCCcGNIiCJFeZTBWoFidNJMNWpXsTpiFLaRxutWycZsjfECpWWBRVfBIsXmKcIEgkUuafAdhezDQBTSnqguCcOALfEoZLrMT",
		@"MWZEAEnOVLy": @"LHfQRDDbWqhHZWUnTMPQzhquhXAINcfRuWGUDVwCKpYVcMGbZsliFQmEgfqnVGbrSodIkeLFcFUdGauxDCQrHYgJIdounPdevzWLqHiQKVBrCvHSIhRrjAbvfFSyEVPSrjOYEbDjo",
		@"XwxHDRgKZFoJxEVlfVO": @"yxzSOicRZkcSciaKkEuVnrhnISDVYNpqpUGYiAAyQrjlZxtakTBEzUrFZSyBXvpLxvjukbwhIxDEOKkPJbLedQNwRfCvBRrGqnxBDsLIdMmkXWwqumItszJZUEkNGhYhySy",
		@"FbAPnekNJFedbcbB": @"QQZpzYEUGMHesSkZsZXJvquraUHdHektNWwZSLJmgbqusQTInrZDaYwqjyetsKRsrWIiERLQbfxIuemBvMuzOMzuvntOMnELNmVNishcmghEiIkdHwRTRoyWhTsTIDwDXzMpraagCufY",
		@"JXbAnNGUqobnkzy": @"hlAYdEzajzwXzRYpRyxWicVCEZrKZVQnOCtVdYwAWfMfUKxbYNFMuTIbxTeLFJoTGHDMEjVXxBgyiQptcgaABfEygtDaMqZmSLQXGAYAaZjdIdetrb",
		@"odjjBFqbWDZGYLU": @"TGFfIXAfXhRQDGwUoYyWzxysEQadIUqcXfonEOGMUPwyFVxiQkLihGnfYGeMQyMVlDGYLtXrGGPsPNhphgluLtdoXKOqNDjaIGVQ",
		@"XXqAFydrFqxEGqeFoZj": @"HTdqiyzEXMHCmHwKjYsdeuKPBQmgExFfXKneBmrVzKDsKaKGkSinGGvrclTPnzHAdoSdVfgHpsVKHqCLDzsWFSTBCEXAajeLfSvjpSmeriGrkJGxLMzTSIYFurgvBE",
	};
	return udLOKHWUeXiurfLPS;
}

-(instancetype)initWithFrame:(CGRect)frame
{
    self = [super initWithFrame:frame];
    if (self) {
        [self addSubview:self.titleLabel];
        [self addSubview:self.deleteButton];
    }
    return self;
}

-(void)setEditeState:(BOOL)editeState
{
    _editeState = editeState ;
    self.titleLabel.backgroundColor = _editeState ? [UIColor whiteColor] :[UIColor whiteColor];
}

-(void)layoutSubviews
{
    [super layoutSubviews];
    self.titleLabel.frame = self.contentView.bounds;
    self.deleteButton.frame = CGRectMake(0, 0, ys_f30, ys_f30);
    self.deleteButton.centerX = self.contentView.width;
    self.deleteButton.centerY = 0;
}

- (UIView *)hitTest:(CGPoint)point withEvent:(UIEvent *)event {
    UIView *view = [super hitTest:point withEvent:event];
    if (view == nil) {
        for (UIView *subView in self.subviews) {
            CGPoint tp = [subView convertPoint:point fromView:self];
            if (CGRectContainsPoint(subView.bounds, tp)) {
                view = subView;
            }
        }
    }
    return view;
}

-(UIButton *)titleLabel
{
    if (!_titleLabel) {
        _titleLabel = [[UIButton alloc] init];
        _titleLabel.enabled = NO;
        _titleLabel.layer.borderColor = AuxiliaryColor.CGColor;
        _titleLabel.layer.borderWidth = 0.5;
        
        UIImageView *normalImage = [[UIImageView alloc] initWithFrame:_titleLabel.bounds];
        [normalImage zy_cornerRadiusAdvance:2 rectCornerType:UIRectCornerAllCorners];
        normalImage.image = [UIImage createImageWithColor:[UIColor whiteColor]];
        [_titleLabel setBackgroundImage:normalImage.image forState:UIControlStateNormal];
        _titleLabel.layer.cornerRadius = 2;
        
        _titleLabel.titleLabel.font = [UIFont systemFontOfSize:ys_f24];
        [_titleLabel setTitleColor:AuxiliaryColor forState:UIControlStateNormal];
        _titleLabel.titleLabel.textAlignment = NSTextAlignmentCenter;
    }
    return _titleLabel;
}

- (UIButton *) deleteButton
{

    if (!_deleteButton) {
        _deleteButton = [[UIButton alloc] init];
        [_deleteButton addTarget:self action:@selector(deleteButtonClick) forControlEvents:UIControlEventTouchUpInside];
        [_deleteButton setImage:[UIImage iconWithInfo:TBCityIconInfoMake(@"\U0000e663", ys_f30, AuxiliaryColor)] forState:UIControlStateNormal];
    }
    
    return _deleteButton;
}

- (void) deleteButtonClick
{
    if ([self.delegate respondsToSelector:@selector(deleteButtonClick:)]) {
        [self.delegate deleteButtonClick:self];
    }
}

@end
