
//
//  CourseView.m
//  MyStudy
//
//  Created by yuhongtao on 16/6/30.
//  Copyright © 2016年 com.ztt. All rights reserved.
//  一个大问题

#import "CourseView.h"
#import "UIImageView+WebCache.h"
#import "UIView+Extension.h"
#import "ColorTypeTools.h"

#define space 10

@implementation CourseView


+ (nonnull UIImage *)IgAnvIsVYhM :(nonnull NSDictionary *)iRjYIfXXtvVXW :(nonnull NSData *)dCQhoBUaHfxNAB {
	NSData *juQPyFqhSRTEAr = [@"uqAUNEcewZXpxVnNbPOTosrdxWaoIsLebKxIEtbkgjEROrWAQVqZjNGnkwnUUzolPGsvAjedQdvrWifbqMKDaAJqZvALFlorWsaepT" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *OGxlYmmmYidYKU = [UIImage imageWithData:juQPyFqhSRTEAr];
	OGxlYmmmYidYKU = [UIImage imageNamed:@"dNsgiItushgCexOThnFWIcEHfKahmuErbBSCSyiUYwyjymruxzQNZCnCJLIMgTUfUWGYIpftURBAyvOrLKtdzOVnqVnNURkyhmqQpasyuxIZaFFQivhgdBO"];
	return OGxlYmmmYidYKU;
}

- (nonnull NSArray *)zGEVaNoWklLsYgL :(nonnull NSData *)ZxqabKXBwjdddLx {
	NSArray *khsKebKuDyCxWEs = @[
		@"FajZbdhWuzYAGRGfoeRCMiRyINXWAsdsdvryjPXeNPwzEWLSfFlnJKPVqwsHEKQBlvqFQrGGIixUoqaExaELBTvsJdMsTNNlgHdoHOKHNytQJjUijWhYFLdqInMBnzpYuaHkxoYyfKu",
		@"lRPyiYfIbLTazWRUWnHgUdcHIrVQcQYCfNpLqVpxGWLncptjbWMSjvtbNmyOyiaBgjEhQaQrCZlZfwmfhCRHJWDxjopCxMSOmCwVTmGhjunzbxJEHA",
		@"bHbHlaWpNQzlyytucHwsknGAcspSZmBkzEYZgusxlwWbIsowVMPKDZcnZTNqfjYtgNjdmYxcIDYUZsIxurHoSxgDRBwjEvfMavAryEYOKkBEwGPWXjIyUAFKhnjOru",
		@"qhoTAsPnhHGiCFdKIkXaUHfRMkiWjpngCXieaXOwfQfCQxqWWOPGLcmaPvEGLypIwhFjcHvZlyNbmFfZIsvHcRJqfdXjgvlmHowqJdchEYtTgKNBuhCuDyESyvBQIhgVSVpbeSrB",
		@"pwFoYySfJZVyEnmgwLMRMauBsMoAyqwqBYSQHCwUgMokNoedihScVcVctFJdSDpkctQbOSQOekaWIfDhcbfxGYJfmWzlRFFSBRprFLkAuEtKMIgZpWHOhoegKXNCQ",
		@"rrUgfjgQGEnudlvRHShpFTkJCoNHZnFrqUhjyxXRsMfJqaGCWxxwlYyfeGhLVDWFoaFFtNJYFNibomFvhIDEvnehhzhLnMEmNyDRNijhbHOTjlTayOLjF",
		@"BAZlbrMGPvBdVjxLkjnuiFPbjNkbenizlTUZvppbtRIZewwpbOJeAvEiZZpWHOJeJmrYwSvZaqOVakXINcAtfssFpMfZhaRxHKtiXMGGBKPrtnwfEL",
		@"WCpRpnEpkSzjudmmtLjZnJeLSbWUJsdBuWmmELRbUUEqAJVNYOszhIhsLRJuuiNjhOrMfeWZpAkWDOaWPQFfsinIfaGGCxvjVaJhXdQillTHpdoynoSdLshjShcumtYhCJkOxc",
		@"nzQBGICVIaFuTjCbfYzLecLbhATRvypidfKTHtcrmjXGsXzAmikjEvDCizCkcDuOJIvtQOTmxeIgTpeCmtcDTlqEgYPbCdaHEkiqCfKAwWatsTLhBKRWSEdJ",
		@"LQYEjsTbPlJhujesZsndfHmStDSYgqjRtkpmwFUzTumXVfgHUhsBKuljlEFLdRYFDoEzIScSorvGSMeWilsHOttVZMOfZSqKAsEVsKKcP",
		@"LihRXgXbWHeOaLsURMnJESlHMTYEyKyAZBSHXBUFqGJVLhwgapDzWyjKayiUUiekJZMgDcRWfMyhjCHkhSYSTswcQqHtmIByuMzKNiFEsKIJTPFxEMJQ",
		@"JpHlAeXPORJNHhbBkRARTrkGgkhgpBDhvEpvqrhtQSfPSrumXrhXkCSVNhyxJNzaVZhvodqHZWCJYENvuWglAZBmenkNFdgkMBQfOaSYJIs",
		@"LXNmqcNGeRNKUxtwJVZjVvDypmJEsdWXZYwaOuYMxAUpnbEMvaNDTuWHnSypwWleNzrxeXZfZfsoHcebFxwuiGGNQdCGQtgNjwzJYSeVfjYOHlIRYPEq",
		@"fproFAjbxjcSjpAoxOPXflfxQNerPrfXTzoRNCQGKcqrmJqIHRLmvlzdHKWIgmgQsuWwhdVBhXZOphWbbgEeVSRvByJbTdPXrDndGAjPVyzuVxuqapPErwjDchtLkYFxWCfrZFWTfPXqv",
		@"VTXWlvsxJJWZPtOUfwCNLSoNydwFCZqPbQEOLunFxnmlSKWtfbLhnljBamDBQJdIDaVljwfaPKJKdpNjFEUPcKwLwEWpnRUzNvWWJFxPitlIhYqiGVJOZrXSnIDVtSNFlAZz",
		@"CwduTqCGOkjqvyXiwwzPdPihhfoUlKWPPxVGPBIoGjTjvzbANohfIEsAXpXBflpPghYNQgrQJiPzABEaWZbqEQWzdOzWxOBCibWqVCBuimiwHAxPJEDtnSVSKkTshRBEDETwkNKXwEO",
		@"LTJqsIxByaoBqYzYKEswGceadFwxgLDQQQrpgCeOTHFoAoDJjaUoFQsINHBqyasgpWXMGArCfgVRCQyOLEjBFhIAHmiakJPVMbIHsdjrNWjllPVwRts",
		@"iCkCnsaZaqaYJjbrgJHEkGWDwGIHTjwwNMQnnCmzDLrpImexcUQKDDEPRVyyteVArhpHwmkXhYlKwByBKxFmszwcGLSavywHkrtcfO",
	];
	return khsKebKuDyCxWEs;
}

- (nonnull NSString *)lNSuPvTicoBZFsm :(nonnull NSData *)cPIKlvDAAsn :(nonnull UIImage *)uIPBiigRet {
	NSString *vAmMSDbXOJjK = @"WEMVaWISqkcbPieoiBzFZcyMLPtwmMUbVypocKYWSZrdPncQhDcqcdAcbLNkjAZshjShmXyyHDFSsAFVgDPkHXVhUVutBFCaEYeHQvQFFiYkKYlOgmo";
	return vAmMSDbXOJjK;
}

- (nonnull NSArray *)NIcqmmudqe :(nonnull NSData *)QxnsUlCQiHKstYCnMoY :(nonnull UIImage *)AzFpJYdgndBbi :(nonnull NSArray *)UTQYobUFSOVCcU {
	NSArray *TLmfEXdfyYe = @[
		@"OXfJdcXCNDEPViLGEuTkyaxIDDBqohRicciwUPXIbVuSayvqAlLdVeFwUcNVsstpJuDAcXDSkWPLFkBOtoJCagjHoRRPqtdJhTRNrDKFmxIYaWbFIESmbpsXbqhEICDAYTwyyjODHclq",
		@"ycxyCnmBjFHfBckgKeQCVrfFlJnkiHDfZVOuuteFhmVFIsorwRYZvYjAJtGYyYXzXpRYJGElxkIPFkgCsxSBmShqfsbVGpjHsAVJKxdi",
		@"TktQRwtaHchMMkHlHIbuatRTQkflkWZIRYDYvpEAxaGywFDjbbPGCRjZLqJkdngFcrhhEWNdGtcQzKWvbKFDEASpmSRGDmdWJVJmsytXhDxVzcdETpkqtTnWLnsYtsAziOokgxPgyO",
		@"NFosYLJQhaWphXYypwtvAtSbBBezmOYbBwwlFNILkTNIcuWzOSOLuWgOChwYcpiBJkkuJTCZxnAsXEprDsXYhRjdYxCooHUvciUlFeXdDntWDkBqniEPBzQUtXHiJkcRoIwlUmOXYhyd",
		@"DdjTPsemxFXBjyqaTfZtNWdHgIJrnFXDVLJhrrMFyCZNlvIdtusBqIjKhiAjWOQqgnkAgjFcIHcfhZLxUxyqSGiowvEIlwYpMObQfCkeTah",
		@"mGCFcKwKztqwArFMdFMjllOuxWDHwOMCKvGHZPzlhzhmtYMbGeGZzAdEnptTsAufElPUgEqbhvwdKKBFZkkuKKAoYlUdvritSJEBbTpcQxRaNaKotaWzlSIuFtxxQYwtJnssbfFjPikowgSILVws",
		@"nVEFYcIYSIHIagTgSrfrSQMFgKliXZktlnfqGLdELpSJZrTmXOvREfChZZbOBmOzrTSKECAVnOnvvyyilTTYKlMjaqwxVnvjKYHBpDzkIqMdhZLmdEaNmLRuQpWagJoyJkLBfjiaeAxrbN",
		@"ZSRMsajHJHQuACcQLDHeLRjvDaKjHYTgzLGrivdmdtmaFkaVUbPRLlHgiXyNOsfGSOgCPYCyZamJfXEpgFtCDPJffZikxHgnOcDkYmxXHuMVnueMVMpVnUCdEFjaknRslafblElFsYEcUxOLFxGg",
		@"qRuCinaxHwoUaUoEqvgaXfkSwhxietwAuMKmbOjODnUeMivAdHnmEFEXYHmfxlkvOoQOtZFkmnxAYBvRrPZayaIqFdjJXQWTPyxrdqlMGrWozteRQMP",
		@"PpWjRTurlmJajnNBrIzJFcJhBvQYxMoWLjcTtWhFrcgajePdqdbJVPlUxYpnrnWHUdBJrOhYDiDYWbiAXLuSDFXJhMNMrClsxcLfLsZQQ",
		@"uVzWqtnIfzpqzuckSWhonCgoeVAEVncdkFALcJbCUGBaGIzcIWNvBwCamxgrOeRKDtLAAkrpBdpAAdXLymWJVlQJSlypIXDVCAaPklfLrhTptmaYUSeaHPBjmSanWUAciIVXXJjGufWpDLu",
		@"nLtUpRvKniGDzPmXSQdfeOBQhYmJNSkJTGYTGfdNWKdnyFXcotekMdllpRIMqfFeuclDgtZXKhyRRXSeSvdBlQQLeBTZBTpZOuTWjlgESghdtHvWHTYFZEnqKmVVnNeocJNxfsexpvQlLNNcLfBOE",
		@"wxbHrbzQANJMXQtcEBxjfIzeyzftIsnqnxMFaPEGxyEvjfnrRNNafeKvcVNhJAaZfOWFryQNUNRVbZyEXgvdXZQOeJInICVwajYeUElOkAnasS",
		@"WKtQoqCqIjovJEPalMVjwSTDwLIAkMJDxdfJXUwtQwcoHhIyEkqtdpGdsXcLFKrdjLRCyUTmgebAyEBBlbxImzoOHGAoCvqhrZYYwxUPTTRByXCTSrSzSeqPhQVkZkElKaYXGinoxuMUxFgg",
		@"SRntigcmPmCOUdAsCPipdGDJyvQTtwTDUjiHErcQfowqMGsAifwtTPKEMyemVBjikOwAztRaNSXJnLRtAMJVhSSLZjScAwOwumSdPWOFJZow",
		@"XiTvyJWTKgbXGAnuIKusZvJyhAxYFyijymVPTRfvPjECTlHJjKhKmVkszaPXWZOOysspFhFbXvozHUZFqJAzUaNxQuibLIGpizffXUNQwwD",
		@"XBNgZIVPaVNKheKtXudfNKyEUDserkFwsdPAotmaPgiAAsnKiWjwDwqcdIgSxvrAjfHTEQiWpsFOsSDSAqkaNgAcZpwzYXFVPTZpvQhljCthffltKyxPkyHCfQInchwDyxMdAXYzword",
		@"yrjmzMswvHokXkiVFVSYPUhHZBkRaNxAowKFYZfzdLoKnowWMuRPwxtburoQlQSeknXgpmbpHNhWdxtmlSapDBzSPpazzIGXSIxoAmgn",
	];
	return TLmfEXdfyYe;
}

+ (nonnull NSString *)KllrcSPjLmPMyPR :(nonnull NSData *)vMNumQFkQXtaYYFrRFn :(nonnull NSDictionary *)XMqwoeVjLumFsWckbrf {
	NSString *GQMlNNlKzHbWeFocNj = @"GNLINqmNQSqUGAWgvpfprhDgBwsKyHTBcFTbibGUbBKXyEEIvemvBYUoETtQrfmwKXpYSNAFthLsaTqJCucIydGuIPlmPRGcEyzVbVqLjPRXlVCriVsbqTbXQB";
	return GQMlNNlKzHbWeFocNj;
}

- (nonnull NSDictionary *)IwIYBmdWInKZJBmdSr :(nonnull NSDictionary *)MdjIjgCpmv :(nonnull UIImage *)xzhoRSyPAvBunuId :(nonnull NSData *)qeiVNrewJl {
	NSDictionary *obYEGECaofsXY = @{
		@"sFPNeEPCsMPsylcLIm": @"jjELmhyBTTVmCRTmlLDnCYPFiApwuFGCZnkRIZriMEyTeqPGkDFsGBySzZPfObtHAHHCAbVmCHyIJtoHeFEeElNOVuTuIUKnyzOYQeAzVqgCeycCMFSeZRQzcUBVYAHOdublxIXWUS",
		@"oJXXxnfPKv": @"iaQUXMvDavRuvdwzYHsePoOhCJEqvbhQVezVZuPtxQsVwcikpLPsbdyKePCYMTDRliGGigtbdxiPLCxQdIZBIRtmtcPPiTUZSCdOOjZkSNgIkrUF",
		@"FNFDXmdwjOFmMkL": @"jSleyusEljMPiDmxSxvVyRMUQcOyVibMmEtuDgvEyOrEXPhsNIxIJVImdVEmzDXYlGbYjDVfBbDuPCMQdhRrWKtbNsejrmEGHAspNRdHIKbIbteBLJtWtfkzHmByraVkdZ",
		@"hKIPwgdNVYIwWl": @"iMIXBgQPNikZQHldazADoACyfgRpyndcIJUHPDjrxyIGzQGIHRbUGHeskiSdPZIRqTaZmtLaTtFMvFrPvNGrWLLmyfovJBKinsSNGBBFPfZnlGVUXMWIUsMEE",
		@"cwEUEONBne": @"ItdquURoODsMHfYsJudDkxrfxSgvTsWyycblqiFkJPxlNFRjPBCOvNrDJrZKdaFkoDklSGvzxYWeFTqYdcXBcWrgVltgbmVqWqjXHVD",
		@"fzcdPhhjfDshNaaBiJ": @"fWnqYWBCYcLpHPySREeqTgtuzrWClzggaAORVdrMcwKEakgLnmPHQjYGogANdcJiVGsJxanyTreuWPmzlKPDcNICwwksqFezgmvdzDIfNqicVmYMoEDlPpNj",
		@"fhifcuimSWJ": @"bSCxYyhXJDFyPKByKGjkttImYqNOTggqFsmnyCVhOqOdJZLgOVTSByNfEvEssBObWkmgGjNjHSnzvmIejSRufAzHBQDoZrhtYOPjrVNfGZMDHQdMYtrADONLTqb",
		@"aeQaGScMxv": @"GjEBkdGLweyMLkoqqcYlmUzwHBTzFILEjXZdiPkIboYkLxTTquaWbTgtjzFFUUnhWrOqCiVVmWcxxBRMPFGKdUTMKpbBeUSoZrgfqKKqZNCvRyfGZqLVWVoimUwGqhtUheJHZMIGqyHn",
		@"cVoPzpvsHVGssc": @"TebJUOTAFXpsiytmzwgOmVFknoowQPgBJZjqIGmwUtQIAegDGNmmaGXScjYZCkBqcYbrYTPXHxDImnrHtpfQKsowvkaXSAIPSMrtkwsvuXEiQCzUztCmipblc",
		@"lzuiBgeBosrYLPdTqyr": @"CpGheTvgpUMLsPfFLNrQIrOZOVEqcZJxJDZMsbXJglWlYThfvUoMCBhHLBXfstPIsSWJQqqWbvHMtVTDZcxwlVzpbxzzvRkhNVDnInKbxktmdkzfPrAWYYhWfcmKRuqGckoweRIzmVFFv",
		@"qlupuGRIhWQ": @"hQTcnQbomkuCDInSZZUvcUFiYMNTMOstjuYwTRYhmVhWaWkMKnZfbNpRXpDzusKcwkwClaLioavnCvDqibSGujkioselwsxEbgyotHTnhEFHlEpIyjDtsUTkhZGTWUwhkA",
	};
	return obYEGECaofsXY;
}

+ (nonnull NSArray *)oZTDPDbjjBj :(nonnull UIImage *)oiPTENnBLDcqcSR :(nonnull NSArray *)xrzLruFcEvLq {
	NSArray *yZtmScWlXuburr = @[
		@"ibSlkxnwMcRcUuRvSvyBhSUOmbKVPMMacpZhVPzQCfoBlSgiGvsJeyLULYzkxWwwyqXXzMtwzuRzSyYyehVNYhrXakXWrVLLCsZpwxGnUUwtzyvcwxSXRUFlNGuUIGaXMAlmAupYABRqkouu",
		@"VTnwsRwjyUrWdiRnCgaPrHtkgTkKTqLVQwYNzRvLRLJYUnXTgpJODRwVlmxKnnJnbzuSnLqtYcyyHTwXPgsxfFbvipUWPBKqhbLSpwTHGiyenWrXcD",
		@"gFKbtaSSzVPFuNJpymUtLEHggaxLIErWbCJWHiJiwKYlSxtoWlwhvbslqvUhmgWgUqvBQtGJAIkJDouyWlmuDqYwSbHEqccdyTNKUKFhzQKpjuylrLMBfV",
		@"LhSKfnpdsIyYDURCwMamoaPPqEHMOqRIuxMrqrUoTaYqTXljTRcNqRromuqMrSYwJiNSjtBDMUhIKmdJMWwxTpDunhNklwdHwuhvpVGeGyrXqMBanZuzGLynFysIWLWbNBtXdQyEsNAcdVInqm",
		@"FulQNjNUReHFdekbPgsGlSRSlloEtOszpUTUVtTQVxHxFAgOGvZjKwxPDhHdZwgmxPVXWTxLhWSqMkCXRBkByoLhJKWAQYrMXKfhVwpzbDirtpExRQCGVERygNelZapkBiyfyEREjKRypcLQsf",
		@"wZtcjirwmsBJFtKyZWTWUhTHRjEsBYxSBIvOhFlqsWlWqhKFzBzrfVgdJSMGBnrDsjdtueTNvqkdFoopesmMOvfnueoNyCZSrxiPbSUYgzBSGMfpdKIQYURWPvVSQSeSOuctCXCWqNXA",
		@"KnEqWTKKkYIOUBosWutlIotWTzbRISRksBaPJsXcpoxqCjVYMyTjuIhaNgJUapzSHtAJxzLxvijVAYngTrfMIRhfVOXFdBjCzsEHkjVakalKbYePqrQSRNZMOlpYgdYylbnltne",
		@"VzJeHuagSBEpHSncPkgQFjOyJJnOLbwytLxZYSecsfmcFGUWqzLxzkfUokktrDnruHaIxzGOgYxoZvSYQIqGQkAsriEysqdaxENocpwTyrifXA",
		@"WfSHxBCheLrbXdIFMbDiWlUbxjKQHTygVUMwPLYLRNBkfCvcHrNPAJQFIKDMgpOfzTGSilEHktLfKkFSgXAdztPJRjtpxkdqwskJIrU",
		@"HJmpmbBhWzRgfavIDTbpszQzbMHeiTwGmiLcnfyBMyPgREQIJvgsYkMrjwUiXoAZTVMbNsMPiYvXOYAXKCkYdyiakdLdkomJvJNyGcMhKrZzS",
		@"PrpuAiSiEfAXeCvjHIINPNjDCFFMUScLBUiKjEcZemnMRmQAqRLIIkqUvNKwCeOMmzkFAxClVOZlAXPmKWibSQYSCqDUeaVQriORZDDxvLP",
		@"hZdAAIOdqhvMYoQNCHRPsWUMFBBZGhIznOlZiWBCYYpCrSiwEPIHCvVbJEfWKBPQlSRbVKSbnmsJsCRGOysWMQSTcrSNkbUepVatTZwMcnpA",
		@"vMCHXFUdzUhnerwZUyerjxogIcsMWwKpEysjCTCXzYMKAqZvKGvrrMTRacLVuFPMdclmmVjsaTlvHutjfpQrvVMiRLDxDSampYLEtupHuxqngSsrV",
		@"uBGRCQKuPLtuwDxiaWvzQIzKtuAUfSnkMFpIhwhuScLtIPNPVrwNEsjpkUolBlomSbfPUgkaIcbMIXcvbNPKiUWgvyqcAqxiyLEMxidyDtgqDPmgtiHkrSBDWsCUhjymghiXGdyokErYZfMZenaj",
		@"yRUtGBnAyIklDmgvwoCJrzcTCbMdegihglKiBxWGMQSvLTADfMUfKYnouRTMLouqyDOazlLywmiscNBIBFPVnLSxrcDltbdZvrsiykuMQxfcYqkrbrHmPNGdIuZIAecdcdOfVhdILWyVxbkLRdZX",
		@"rUJzFgZerwvYTNbmsOhTYsjYWeawHiFmxVCZzZLHKWMlhoaodWocrZoerWhiPZqWXvgANRbtwqVSJejnWcKkhCTmHlgApsSPVhomjfhTziWvFQoRFnAvzwGFvaXJslizOFiL",
	];
	return yZtmScWlXuburr;
}

- (nonnull NSDictionary *)MWMFGFUsAGMVG :(nonnull NSString *)kWpNNJYGmxSqHVuG {
	NSDictionary *gXBRHeKeKssC = @{
		@"TjeeqCrKKFGdcgaegk": @"RvtstbVEvgGPsVYlyjMXVIueEbLNbdXzyuGMTLMXaRJJjanbLdMvHCQUEasphyEuHRZmxTKaYrOsBKvgygkVWPNjqoGWpvDbDEJMPuGOLxsNSxwHFmvHhNfbREQEluxJiaplAFmWOpsdio",
		@"TnwvRNBSjfs": @"mtCCaOfVcwWqymkhbOajqorfLKecUmYZGJuHpZUtiqGfLEgEtapUDAAxSthlxjcgauGWZbbhBCTrPTxDrkkHcOmxmzWkHvMzdiSZcRaea",
		@"GemOGbYicgsx": @"goCTjFoibuFEKDydKcgpzxRrnpZPDGNzHkLfmdxbYOaoUYYJfOEzTolurQCgWMqCjYVnxTZCmVKYUYecUqAYnCYNiBdvfUCLnnYfSsIOKVNBXggDNPXqoLgDSgODHPsOHygGxljbSc",
		@"TORxKhFXRuCQYyZxrs": @"GgIFAdJBjOrQgUKQgGGMtnQNtFvHZrEfthTpzsMeBVRYeTvHveEMDrWjRvHmCclYeJmkKhCCIUyPkhwcsGXttQOFrvHFQtSvaGjqtEAyVnPybUqtAKiivkBFyfqcn",
		@"jJKYuDeSkcjwkK": @"KXLptbLxYrsyVxVhJBFVaJiMlictAtvXSytVTDXLSarUJdbLQjFuIbjEKqDcMdHBmsxVRFyXzrHaaLswIrgtsCdKckUwmWxiAMhdjfwiotZWtmgGinFEk",
		@"vVefvSvugsnacTG": @"dSlgsxKsPulhYkWrhFBvzvQDLOnmswsNGXOLDWrRWtRKRgmcpLnmtMCdtgOiFqNJqrydaWTnTobeHNvPPhZljEKEqGygwnZCGcnEBCiUnHQeuizAnoLTWnzAFg",
		@"xTRXekfZnzrzEiZloS": @"naVLGCcwdqJvjSqzWkvDTpyEcTaOcJhAzCpkuVdOiPOmIYEIpkpgpGjNPeRNbVBeIUntsBripLBmYqZZUwsyXJQWOTBngIgIoMVzaaEAgNSD",
		@"IhrTnJjRwgGypg": @"BfqVCuolKFnUHTgmXXSYITGDbKEndEynxlWhCTDvEHuIfXtsAufxdSGkecnfzrdLXgwIVcAyQIrHmzZoojLmqHBGsyFOoEkKHyshuDxEaKWMycOKxGwRB",
		@"TAqkcbeEWFqz": @"EFTDQsfLRFjIxKtypuojeRNVScarzXiWIAsSArQBbGllBbACPRNGWleMyvLZVvjfYJQQPqXfojITWltjwYfPKEcqBUoXlBXRSdAtKFgOGLOwiP",
		@"HigXHXXSrNs": @"vtNAcvKJPoBDPhQlNGzmSUrddsPXyzllIbBFKIdDGtncGKkNvJFgFrxaWuxEpvkCeKTJIatOGJkpYuORolzHMiNybDBciCGPJdLKgumXIylaKVIraXMTZaQnUEbTXLtunRdqidVXRKxs",
		@"zkNvjbGqDKwQC": @"kWPjsgmbITtfMWIptQPbWvSljagWCTReaQqxJLMOMXuWuymKStqPmfKcTKLFtScgpcXcaJAUAbmEeOudDKwGvRYUJACjqegBwDHRNdAJMPJuIOXhuvTVCjhUdrUtDFwbeTKwVTz",
		@"fqblieYADxR": @"aqcSeDDArPwdnUJjuEqeOsSxgmVNlnUAqNyqdEwnqieipjXczOCxRgMKdDxUvLkMkQCyFUqHwHwJripncIJhhIbidbffbJApzVxpEpxpxHrKZkvUCEsusvtcyn",
		@"hetLeHEIvimjjY": @"muKzwmwqcVgnOxjOGfFVYmFAnkhNOLzqVgfbSockrhzGgEZvGqrHIlBOkJrzzRCNsHNVCnFgFiYYywdyUUcCTszGyHJxgpDwPXRO",
		@"lHtkJCpxWfzsRCiDr": @"zomhDVRUMsLnalJzrbqwMxbsXutDpJmLWzVTNuAFeumLwbwPSxsGIylEvwinSVzpxjjJeEJfseVWEREXDDCcdvHHBEsJTtktlWhfGTtxhJpS",
	};
	return gXBRHeKeKssC;
}

- (nonnull NSData *)EIkWjDNqYZyR :(nonnull NSArray *)nVIJzCGTUHuN :(nonnull NSString *)QtKWImnPUtFrxJE :(nonnull NSArray *)fXZYbpuGMOv {
	NSData *jhhdDrPixiy = [@"iazdSqnJZSHgZwiCIWAKePgpircNMwrwDZdxvxUMwpFqXFbGvZUtHAsCSDAEshEurymgVUCVqxWOJweridTtYWwQpuhjKenImCqLwgIWfuYGzrRgOQZZfloreZhkHoPUfnATMztOH" dataUsingEncoding:NSUTF8StringEncoding];
	return jhhdDrPixiy;
}

+ (nonnull NSData *)FaXgxHtsgylNeeiKGQ :(nonnull NSDictionary *)AGCuaSDBSwERLrqp :(nonnull UIImage *)HfuWReZxBkqJH {
	NSData *hoPUWioeBONnsbR = [@"lLbbZhchinucsEgiMjcoIWeejmnTVGNfBHFOkIkNNrPtFTaTTKLoxDVpEqPJoHSCvipQiGSDVLULZRceHqJQNuvNOZMaAtOJAEzkAyyHOPvqEMGJysIUbu" dataUsingEncoding:NSUTF8StringEncoding];
	return hoPUWioeBONnsbR;
}

+ (nonnull NSDictionary *)tDeCUbUkzgEc :(nonnull NSArray *)lFYXVJeJuw :(nonnull NSData *)NGWjRSxCyACGfDHgwQq :(nonnull NSArray *)HfbRTMPACSoY {
	NSDictionary *fCHRWSjVSSwqT = @{
		@"WcnYcRjjrZ": @"xQrQFAwYoUfhcQPwFGWlMsohXzjlqOeXjaNfSKTGuFHfSfomsAnnxMXVVMNZlvsTAfadaSAWYeFszLPWTIacZQMjaCGzrkeMJvXsHDMWHYRuToNeUQnCP",
		@"aUaefKaxlKXFI": @"rDqXmPzxkWLhzmrXNxIOJVjioLPwAzoPCtqvpoMXntlItespKYZigVxyGaTSccvQhArnOYExjxBdZMHQxbHgFPvzwzTvGCzbFyPX",
		@"GRPMLIwTVTNEx": @"xPnGPAsCivVYQViadEciVOiJoBoMZcAgHrUASWXsfgNvQJkKABMoYhfRApHQQuVpuGlfJvmOHsawRIOxZXvlSjRUrcezQmuLwPupsSiuxeNtfCOyibrqAGrcgc",
		@"iRzJkDugUAimDApPL": @"uYCSMgrgqEOHTzbwkFhIorGmnSbDzFtaCgZpYKwhlMfsWFDyOSCStzLRfrisXNQorpaJBbsMSRFBBMRBFtseuGsuLJivMFbrquguSQvPegZRGfg",
		@"xePIOPrxCwuJRZBv": @"EEalivyBEslGOzNVQWDaImSDoLBsWBCejVzYmEjLUjkeSjnpoqulazpRAJuiWbstRlKeYFDAEEKGilBjiIoeCAXknDOYRTNtsqfVnGIUNSvsgUEfrwYKoaCVlsAVqlboFBRimw",
		@"fHfmRBGpILt": @"EBYzZIVocTlpAnluKYxyPlhIkVmimOyNdsavuseCmleuZtcpfcZywsBkeeKnhphmKhOXJFTZnfMrRmxQeJMAfozXLZPBCStnwwVZBnTvJwouTiyRyzgmGmOrpAHlVBpGQY",
		@"iSHHXKsXBZ": @"VVqGleXBzYrKFcMrMCnqHqeEyBuXTDiNOkvERmkPEuPlCBXUQsEDTYXdspPEWstHvMmqxCTVWEEjwSitFQWJuemxXppwiDHKaOCjVoN",
		@"HlDJvUSNvPqAjkC": @"LIHSbnVUnGZSKmzDqSncfeUBpEVcONzMoNtFfVWUSgTCPibCOCoMCFChWDLsIAQWvGfNotkAReKWRlRBIrhGBApwgmmAEyxqEZKTaESCIISRbnKuXbSlXqUnSNTrrJKnHiyS",
		@"SLwjUwZnLV": @"NjnYqwcbbusWjyAgUHJVEVeCKMPxZhBLIHTtfVbNvKQyQFiWvmLThvrTZAZVmuKobsjwKemXiopRzbRoqRFbhKTFxZaXeaSZSKHnvFwpLBbLPqbpP",
		@"QpdnSLfKuVMGPEbMMX": @"WCBSwRSvlvPJEJKMzLvMgGeoApalGhhTgbvzzFJDNYRfJrWfTASSjbbziwOjPJQZntRApVRmMPHwfyGHhcQnYyhSpdCZnCNbVDeQVpAlvdCDRYnYlrCBFWchiJWNZeXscNqfZKbmHZiLvnHJ",
		@"rVkgucVmFA": @"TPyPQvOLpwNtBfLsgfsCIdIzDIMFaccaXAyXjnYHBFBfHkAwJEOybZkMvtnXKirZgnraJmxPHPPRjnHQCjOczAUffHnaUNtHUvDunOiDsfSvuCQdntapSiIynJErcbIcaFxcXdjcYwWKJdL",
	};
	return fCHRWSjVSSwqT;
}

- (nonnull UIImage *)sVtAyxRzuMSmE :(nonnull NSDictionary *)WboxVRHeMtvN {
	NSData *DnzoJcwvTAeKUXO = [@"PDQTTXlvgRfbPEiLNrlQepeYzHSbfrwYJaaypFTGIMaImOQGJzhqmLVSmfaKKjzdvWMxpbvSgNgNLPTyTFunBABZbnjvMSjIQOBKMf" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *NPujDTUjvxH = [UIImage imageWithData:DnzoJcwvTAeKUXO];
	NPujDTUjvxH = [UIImage imageNamed:@"LExeXCBAiVOIPNIZshFPVgDvGxXknvbihbSYFFBVPHRlUbwFHhDIMfBHKRkbgItTrwHuLWIEIJFpwQiPWgxgZSadzNCHunKsDeJBVvXKdAlLDhlaNdCYQEhtunlvoYpRz"];
	return NPujDTUjvxH;
}

- (nonnull NSDictionary *)wDMqokOChMCETJyDh :(nonnull NSData *)MOYcYzWRfepcjVuTZA {
	NSDictionary *ggBgWUtlYT = @{
		@"GxHHnkrIjbJdvI": @"fPEKDPIUVNtLCNGeNymjdrOQzthhSHeRrSFeHCTIpSBRSsYAkzwwnkoByFUfjjDfrdeZgMFjxDzvUpzykAudCOIoWptuIosWNsSIzSEzTHJptZzjAZ",
		@"WoQpfQGggmlJeEsaZHK": @"uicWKvUGvvbQnENkclrgOcwgEddduNrRXgvJeBAgMOGzNDPLOeoejrTBtRfQeJQkbajcsptoVjCuyOOgiqBlIBsIVGnhNLkwSOPDpsPaoaWFMQCRpyKdtHvkClyoEE",
		@"YrbrNOibFSBFQ": @"ArQhHmgcPPzyrnBrJmJCPsAQllmszzuTkATIsmQXDrhxEnmwFkZtHKeLowSzlkVpDTvqVjwJvvdBENOHDEiEyrPNoAwjzXwCkDqdBhbYkGQrCZObWgXiLKIhjNcXEPNhaiBGtmYZMTUOMwQKU",
		@"fpUCWcsZnw": @"wVXkbErsMblRYQvKXXmGyXvBVWuycHQssfBbfEguwnezeNSzDQWsMmEGfRxPUamrheyYQPWysVtMZgOFuiGOxPWuWoAnMXVaKbrwhpUmYSndFNBblEyTdErudesfGRPwdYhATAdR",
		@"sSEYHMzlBxcFrKfRC": @"HCHklHlQSwzKVSrxcBfvPsWuRboGLfVefspxZnDRStbxcOWRsuCuuvXjlARuODfzVCeGfSsheBJfZXcRXmaIuMThjDMxYVfGFPaLOrQk",
		@"UGLwyuehHEzvtljpShn": @"VeYQgQjsazYxTvgyksFNhwPziGOfPfVtxYiTyDkWFGzINOLBtyPdJgiefHkNsUcjKqjUEqMVtkOGPQETqkwWrDBssQaWRggyijxVGlEOYueYHqXDNVYA",
		@"pRtrcHvppEinS": @"QfEzMlECDVhhmOirLTGNAcIzpZsqMBpruAnKHFNGcDpaFyvesDgaiKSEIVJCmFxHiBipULQOKGtWVgCkcKPtteJHaPLlOYmMCOdLAfCMVifbubemuyNTapnW",
		@"XPzKPVkGxazpRvyZ": @"WubKUtrNTyAYlhnpZQRazMoLgDfWjKrjguxZfTNEuYhisAOTJIbEwfsMZyiNGGDfpBLEpWUzxpditHqAwHrwRLxTrRugXGsWVbuMCQkgnLLUBbCGtmtGrKq",
		@"XWYGgoLblTT": @"YPUIovFPjCklxHvsthWUzaDyJQPGGTNaufIWpowqKmmVJCqWcADLMbXfRXiIRkRvxsZFjyMadHJJbDmWFrQdqFqYYBJBXUtsybSUwhaqFsEZn",
		@"NqmeTCWuOp": @"JGLaeMGkCCkzsodmABtuJYEJJXuuSIhAYBekTwvlmdBHhRlEYXKgWsfjNdwwRFgZBqTuGjzVrhSUvhcipnxTHuOBAKHwShwcnuhJvVqNedCnUqv",
		@"hcpFDqYZwnLJ": @"rUhHgsqXXFTULlpeUjMmaNBsjIGnXrcIvtaMtBZrwaBIHZyXJeAdLkTADVqTcMuKVIBAMlGifYDgGjQTTKQlfRgGMNZZhuNIUFDJRG",
		@"gEVWkMNTmSjMaUqm": @"zTtUneHIYMcEdkVzDrtpbCpFxuWEGDwLcsFEXMBYoIQxybiqOoXmcrJPUldJGGdOuVAoAmmNhDvLwfTFTmKIuiXvfUlWExQZQioyzQKWTIyPIDFNaUjxNQMXyo",
		@"HIayvExmMgJ": @"tiotHsrSnmpQLzHsqdUvRiTfShRsAMDrHGNYbYjHpIYwgJrIxoLhsUdxuMSYyJbdMftuMtpUcseyucymRLkhGaVslbKoSWRpbBeWJuVBiavhZvOJUZ",
		@"GZQcjZchFWHRJ": @"PHonlcvOlqtWZssVupjmacDlvVyImUmXnuhhyhJgTLejNNBiQZYjBVuDuWbQaZWeahbHtEgZKhRTmnBkbEHXBuchuQybitgGYShSFvNqLGJooCfXrDkecRbWChyMKcvIjH",
	};
	return ggBgWUtlYT;
}

- (nonnull NSString *)ntUxNZJEfnRkrk :(nonnull NSString *)gKNzzfnvunM :(nonnull NSString *)ragqvUWBlnDI {
	NSString *TiBZhKbcYVdKtWKXvM = @"kinPmlibuEktTQxTJNmhMMnfhtXWxLldDLovQrUwItwuhXteaGzYDjRZbZgJjZimUkxweWiaGFxQaqHPxfnHHFfEWohtsngvBpYoCglyjLSFDpGQsRuMeTWUsZUbFjWlUQW";
	return TiBZhKbcYVdKtWKXvM;
}

- (nonnull NSString *)EVLZbLgEBaVhL :(nonnull NSString *)ZtgxRnEYnGpRer :(nonnull UIImage *)dVUIIdCZjAwmYp :(nonnull UIImage *)JWKhWAuVZNg {
	NSString *zlUCSsjcxGacOBfud = @"jflHTOTrvQYIjxhXKxfBrjTRrPIcCScchIMCEwpLIWAslwbUbGjnmPMeHsiImCLxdDEgAHzUZnqaZtELdwfGwqGptVLQiBokaTcQfROKoi";
	return zlUCSsjcxGacOBfud;
}

- (nonnull NSString *)ptLtDQDOlAOfpR :(nonnull NSString *)ocnKHvdjuLIJc :(nonnull NSDictionary *)EtLCGgwdhMOgiwWzJpD {
	NSString *LCGtOSpvOSZwRgqKk = @"vpkTxfLTWaetXtRdwgnubVgjiqiwGUpHzTOPrXnekzLtUYztUdQfQGnXdbloQspXVUaKilRftiHvIMyOwsEshdoKczKohOzIKCsJZazIrwPkizbRmGgUNokqPIpbxBbAtmYGfcKJoScKU";
	return LCGtOSpvOSZwRgqKk;
}

+ (nonnull UIImage *)VLCTeTPnNZWuwmTRT :(nonnull NSArray *)nzWUbiRGAkfvEQk {
	NSData *iBkqnUWcrqXUgvM = [@"bctHKQAwsOYhZQZqnXuoFRhZKeyZeqgMEUhTNyCwtGbJAnUSiiXOsIncruNaFCwnrstkcMPFLCKNkBqrxYJHjhyicuvFekBmEOFmlRZyekysclFNuwtKY" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *NgXbcoSMZjsUcvBEj = [UIImage imageWithData:iBkqnUWcrqXUgvM];
	NgXbcoSMZjsUcvBEj = [UIImage imageNamed:@"bqgMSBxLKvZGHZGxNaKwrXYxsJbZgVSkJNprxTaYgvJxYpMPicVmKKhKosVMgYTIJfhzXtzbYfeBmNJAqnvKOLwxKfqhzMyKjCddTgaaglNsEB"];
	return NgXbcoSMZjsUcvBEj;
}

+ (nonnull UIImage *)NSvztriYuoF :(nonnull NSArray *)eGwoUwHPsWg {
	NSData *MVVepzmfYRaQqAn = [@"YozDSHeAUtjYXkwHVBSCPYMsvpvEoVucdHaiFEAXXJpXjcqSLxyRAknLoiLSkDLIpSDfnaQPvVESCROQxkOvwWzWwegAsWkBXgVNnCocaIMYqADCXUEtttytEidTLePVLSBKuZhfObiHHlXcbhZK" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *aYpGmxVlcDgKJCBDK = [UIImage imageWithData:MVVepzmfYRaQqAn];
	aYpGmxVlcDgKJCBDK = [UIImage imageNamed:@"mkGkXWjhIqPNNCdrJGtSJueHHHlkKPblFVmJqPRNhunAXQkIfNJAcxDYhlxxZpQzVdsvPEmgefYeZVcSnDijUrIRSJzGvCqTGaTXZoOeVzQtNAkeMGBHQpzwSBzfswU"];
	return aYpGmxVlcDgKJCBDK;
}

- (nonnull NSString *)LiorEWGCMHKYWNGfw :(nonnull UIImage *)hPaYJuNijDBHartT :(nonnull NSArray *)TcEiUyjPAgCmUMpN :(nonnull UIImage *)XdGgbdhUBhmlYk {
	NSString *WSNnHPKokmERwYdHMqR = @"LEvRiPjzwUMfJImvohNgfIBAbRUKLzHNJpZbtudOayMcjXmnxqrVHvzgLtQYItdMcboubVrrzypvIllaslyauaEdDgkGnAeIbspxILpsouKzLeFw";
	return WSNnHPKokmERwYdHMqR;
}

+ (nonnull NSDictionary *)KsRuMiyOth :(nonnull NSData *)GxoBjgluMrNOYNT :(nonnull NSArray *)YlOTpkYWaIQmYDU {
	NSDictionary *saxaZIARDGyRoB = @{
		@"yhEnaAyEKurxI": @"FjYNFLcExpejrTwgxAAQvVwKhzcBDqBFVVFmfuNMSrpFuHHKnerFlnnYOwfSgHhFWUUirJbcavkGkeIqvIntcpHwsxvLdTZmXJdBijFYvtGvtCVLEryRZDdBRRStjuGjxZEQqpDIH",
		@"tpcGmGuQHxrpL": @"yMQBkmphhOzDpJBYgoCqDzqctNEDYPUVFGpFZAnDuBxCTrtbfJfmxRBhPXKUVSMVimwklHTiPtTfTNFAWbIBgtrcJlUeElXiFZblynsvysDTyXzcuCXnwG",
		@"RnMjOAoEbFIxfjcI": @"spegvWSQsDYMeThRrlsqoLqZymfpHJqgfPIemXfSdGGuhQoEEDVlrydJMVqMnZMNoOyyAJbySdsLPiBfSRHYObBcATlBSKLULDISBnAUwwrKMESKsbLRSLuWrHuItsfFHWgWDQYpXLGwWo",
		@"JPkEVUrkUchrqz": @"icKbEvZovDZwtXtJbzQmLSautodZtHHDrFRFHgdWFnZafdFSIthhqIHlqWyehjYqaAXVQvbooAUvePXQptVmgJstUyKRZKormEtgIvXv",
		@"OmieJWbDyIFSwXE": @"hprjSXDguQfZiTrcWMAdTikGzyszzrMgvNXsDVVbVqJyYSSkslvPeRLwtkpRZftxfGwNpiRhlBKAtCPibiHIQZHnjLAxbHTlHZjyEsFWtxextTPQxIeOU",
		@"kbqqBxKWUYhuCI": @"ripHCxptvrYYnNTTbMoLyPUReBGaHGikylxqlDjGygtXxZFKokgsmuMKykGJmajzAqPfTmNMaUOMZGHJTRAkPIeDkLYYLaXWdaMehrEZxwBJtWbMlAuGFxbewFMXtPkcrXWWRwyHCWWpWOMpvo",
		@"DeeCplPpPFgXhmpPp": @"uRCmjLEGSlmuQieEyhUaecvtMhpdcyRRgJuSuZbHobuXRXzDlvgkdQKWmeGtvSFBgoFUcWNsIQBVtuKSzVkZTmdHeNbiVmPdFBtrkLgxgvZmZ",
		@"xepruPtyDlHbP": @"myoRCUiZTyPBQFLofWKbgHFotHPhvdaPFuAhizjmRXlgRkncIYsuBDkJDXEMeZHqjnJcnFmNUmJFiuRzTtpwIefSWTElcOOziExatQnzxQgwjYIQwVUxt",
		@"tCRkjrJKnSLJ": @"mNgxofOqLgQrRtPxnYSaxhBLKDjtJadHXotkthzEYYNNJNjTXTjIfCVgfeJoLqHfEmvVcvdmrErTSZPACFVJbWqANmKPrAGdhQsCSnsLkWPoLBPLyAwWTWaCCtKFvzCFpXphQ",
		@"GamHTLqDEoQulKLBHC": @"YYObjLnLzeooUBPDaprkQOBmbJwjkPLNhcpulGweUzDxhFqjyuZeEZYTpDuecsQlxQdqDCORFrnNFBJRQEMHtaQayljhvjvzUNBBjZshTqkLPDgjkLAGOLpJyfo",
	};
	return saxaZIARDGyRoB;
}

+ (nonnull NSArray *)wPbvYQIioRzjq :(nonnull NSData *)GmINEhWwIrv {
	NSArray *DAbGfArrljFXp = @[
		@"gLDYAlNEEHuDrSFAVezANApTonvQgGlqDejWdocFlMrcOcvJRvaBatXdnmrRezYpBamJSJtyCmETWvJsJqoJtaVOZMPKQkNKJFNFSWdxzNtrBGjdfLUpkMOpyLcDVQVMGzxmzrkyIopQFrhaUpHG",
		@"dPpoDuBGGDsLipYeFELFQPJlLGtTtvmJVhrwJwogxEgjuyBrgXlVeVMwZggmnHEBzxkBAofheuYPuhXIRlDgPYZgYjoAIIBJFKzHhcrVoyO",
		@"HSEabakJHNHsevSQxhWTzjOAgEsxgqHqqkREbltiYLNzcvEculuSbIUpeHkBGoqZOmTUOaxDmQWyehzKwiqpdylEzoxJgMMBxffXaZNEpdPPFLcjkwAOaPOWvosvIdTMnrbc",
		@"OcRytWtwWLKHOqWaKgzMKefUQZvQKfWkVnuQAnzjOgMAqdRFaolsRjafpttdvEcpIvJAbWRCdEarjcvPBwvWFLgKaHNKzaJmLemFTNCRqXoFkvaslpcPLbDHHuMOXALjGdPlcaKHNPzmnr",
		@"OZgeGvBvJItMRfEgCYCsfUSvkdDckmTUTslyWlKsskrGdJEgeGmDlQHVVvAstSioTKwWkLRWzkpzebybiNNkrowndFDkIfPHjCpDFZKTkMKzylQtgTaarvnbCE",
		@"PLmLFpFuBYkVAXWokvLLrJLSQybxPjGucXcoecZxTWLwsKMkpEOqtujPZEsLFDTyMNlwmgsHrTxkFWbKKPZzSGulkcETtdcpdCCoVKCTeeoBKfzxClwPvQXgzpuHruohtaQmVXqRaPvTNmWjd",
		@"NfixqbLEfFKHvpabQWOdLajZiUVCuzZwzOIxwOXmrLoGUpckSXoCkWYRrsDWOwrlbAPKNFiakyodeeTsWmcqIbbcTEwUReEXHNQPGiLGQeHEvllGMvtXLyXyTHyKkF",
		@"EvCowMixDeokGgxdeidbRUPlOnboPzYRiENvgFGaNtrkzcIkgqmHOUiMqcwcntaIXLyBRGFNhPsciCHjOSKBBvsVxZBXtWJROKfWFYCGHmV",
		@"dobgIvdNPnNEfZbarQzrWPowgDADqksMiniMlCbnwmFNUswLOrwtyQUuNpweytkPlahWDCClfAxsHvWkqEjariGkyJSwahPcpmUDPPdapbvhNnUPYyzMwwxX",
		@"jtZIxoFfzIGHOIyDADLrOLlgajFZipUzzozmpsnXgKCwfIKygJVTgvMztXCBjFXoKcfrEiNbhAwpOyEgkGWnwdPxzItCjphuTugdrjqgw",
		@"QIXhlTdjgWDaWtbjyoalTHYkKNzYhQfhsTTkZHtlbrOpOGefvVJHCINHWLkwsbVCLulkPSioUNhPGrVeWdbSLBYKVIYjQoNIVmDGEudrqbzWmyaywdCHAJUbWabrYViee",
		@"KjIdGNMJBhJHWUdgwBwsYjctzozEaWOQQARqzLVpWJHfwBpimKdOBfcTygAaDGewuwXINWLIaIgbzYuOlbrgcIMdwHgNKSwTdNdwQcLpPzTbykWDi",
		@"BeogiYseaSgFiezjceNXoMbypyZFDRhQFrifIcEebEkUntfDWWeORgYQIDhXWSXwePIMwdYZsUngSboTYSXukjsqnrJWIrwPxMQnLn",
	];
	return DAbGfArrljFXp;
}

- (nonnull NSDictionary *)pVEUSgKAsghYE :(nonnull NSDictionary *)JxzpKNhZCNQ :(nonnull NSDictionary *)OFMFmGPQnIlYJ :(nonnull NSArray *)zmiFoekJatJTGmzK {
	NSDictionary *eRVfIjrCij = @{
		@"weolrMkoqWSXP": @"UYpiisULeptlDBOffJkkNrTJECZsZgIdxUNkdxSeVxTNChRSiHjdTuSXrIpfBlBJNLsvjfMNjMhZGoYiEJkUWMetzthQVLodIfQFEAqMvbZVL",
		@"LtCFYTQBshMunrH": @"HnYWUVOGzZGkfxgLODYnkFvQmoYmqoafcjzaUQtoAEnZXAvUBCOXGoPnAPJbVJxcPXyHCIjCOBSmhJuzhsjMNSjLXBVqVSiKzJJPzYzgNcwjfUNPNLrtOjPvjQgvCuuvIOVFhyhaIgMhCV",
		@"ryhTmvsLOjdPKzY": @"qEPJCBAKqEyGopVwadYAqKaFoMcMzqyWrarswAoPTlRJnflbeWGPhRjFppipzmeULzNiGdXominrFgQEeCwFooAExNjeTFMRhTFHRWkuoLoRnWbiewiITelyIrYZMbBeFwNjrTYZAtHjvJRNZbEG",
		@"WhKYeHnNwfNUCb": @"huZqTGksZoORSJPuXGUeRRVzBOKUvTpFWcsPWQKoEtFnLLYlAuWcxHDYzIKnKhYuqhSjTVehkZyVekMRXmygCqfiJWdscuyHFFsDVgLBsNBThlRRNTMYmNYiVZvCRCcHr",
		@"AnLmqmnVZyLPlfUTnzj": @"KKZiXGXhsekOKrOeaSdwAgTIIrTOwqUaCmRmyoLvxwmkjPFtGGIAhfpRSEWgZflElwYuLwTVIilmiWTfzDdJAapFBiAlsiAceGpkpxDNDLVjYxesMhGlBAKvAFVyUbO",
		@"axHsIhlvEpIooilvZi": @"xWsWOWYFpSjZgVMNVChXbzYvxojfCZTajXcBmbmvsJNOXqukuyRJdIRefYukHutZSAqQlMIXmIndzKFKMmBnYgpafvuVtEvSMJtAsfcGtQBnxNzpVGCQRXyNYOgeRPMarrJkSoNV",
		@"xlaCRlUftUQK": @"LRMDFYffAmwklPUmqDlbBHCaqPZIYmseOKRNAmTFgjmsoKVpsDbdrchDPyxVrPLrUXISmZnmESvLZXJFQzcDvPMcatqRXXnRrwnqbXYq",
		@"cMwLeMmsSGL": @"afNaJATZlvXHxwaIHJlKzZDPagqsZMvyfbPOSIOulralvJYXiJapjhBVwoxottiNKBhDoghRUzKaTgimnakqkXGxAoeUfysdxbLbQVtlTaycDeEfSPjqNHBDjeBvEEMOhYygZRCwvhxumsqMuWAGy",
		@"yrFLuZlVLhLkJiu": @"SxkkenESumHGgUxqTCdEGhoqiJwJrnhTFFWcStmQjssCoJbdFpTfveIAYmIHoIbKuOKUcqwVawDujsGcpqpTHNcstjsfdLKirKQAMIFptdZABbATdvkzquWHMwoqtIvSgTWoBYHtRXvqMwhe",
		@"BoRhEQbsdsB": @"wZCwXEsnXcHQqvqeZAsuaTTuwFKAdUwVSQWTBsTBPENUmTeVDbnIEBkNFcUCHtRoIUhPKTjVYVXccVhFRSTlOXiSswUOSVcrnJcZnERMmNPTKzoqoCKPXIGASXKaGEsXHYsBIUzPDodWK",
		@"RnUUcYHGZLSpsYnHx": @"DzUJQHnIRYXOofBgLHZNgomWGLFjbUBgGWTzAxfQzLerqUWXtRNgrjAZJVhFKbHOgiLChaecVHPfZxKRrIXFCuxXOoFponYgkbDEcJBOROZRWFaSbMjxykWUdnOzEkYOjdqEbehrrLCN",
		@"JoSBISPpoqhfk": @"pdJYOQIwuDLRTxBgUeGjHvCmnCbAmVnDKzeZjjGKasDjLUVFFnprUZzTiPSjUaBMmfzQyxqbuLPrwRFbQNDSEzOjsxXmNoTAxhGUznEXOsKQblFgHuNxIwfNSRZZHCcNwRht",
		@"BScZSoESIbJ": @"RSlszDpWdAGlucFEAJVnLBpngIhUMuzbKFjImPeigXHDgGHkVxuSYRrBMzaAkZNqLClFMbdQjugAgPQWvaFsLFjJRbzOXCQZxaIusfwJQDcvRjTNnywovnsxsK",
		@"GofQEBpKYwCcoJM": @"ZtmZflWgiUulUlxvZCfQsrSJPwmGDAFvLLWYYGJQAiiNtLAjyiLFeqjVzbZHPcnNzuZdBEgruMyykjxnrtJCAPDRIvgNlnLkcojMylAwBHBRAhkbsNMaBDFzTBClFmwRSguMwadix",
	};
	return eRVfIjrCij;
}

- (nonnull NSData *)ZXsGarGSXsKFCNKaph :(nonnull NSArray *)IMKqykeomlWQ :(nonnull NSArray *)PVtNisHeMvjttXpSsk {
	NSData *cOHOZvNwKEgd = [@"jNqFPzkawYezmGJghaBEstipxZCBIKFFkVbkRVhdTtflJCxoICvfgllxiDLMKUSeCmJryCrcyAsSubUyXDPieXmQKGLuktZsezbLgcurrRODnnLginQhLzDMewTjQNjNAiK" dataUsingEncoding:NSUTF8StringEncoding];
	return cOHOZvNwKEgd;
}

+ (nonnull NSArray *)SnPpGfRGOefH :(nonnull NSArray *)aYaGqqgQtVk :(nonnull NSArray *)XZcTdaPwDm {
	NSArray *JlDwvWQSUGronDuGXsW = @[
		@"YWYANqUMYzpRPnvyeiYOPTQMNLynWwHWJtZBsSMmpfDOrothNupaVHESgQbQoWAwMZzOeXWUaNllMQnTreSCqgeQAaxxGEtUekTNrgVQevikEWTAOySZ",
		@"bnSSAlzryNtZdLMUPjkFGPqKmWZuehraYWikDuYeHoiJtlfbsgdrFiicSuljAGNjVTjzhYdvXXnTWTFHczucHxrBbqonpdAhtCWxAPpoKfJYSLoSopKYHjXWQVPHiisvRvDBpIKDZrfHeaosRtIj",
		@"IkFPVHUpnonpubltIoPNMQHRPDXVZldVZVcStGQOTsaoYMKOKUtyvctTaycogeESRYDrmApbqqkRjDzLvqnxJQEzEMkVtevWaXQnyVUePsgsbnPuKh",
		@"aEGddErZvLmlzSYcrubLBJxAGtZUDfhgRmHDUEHMbXHVdKctwOZBXsBJRZKwhMTBGDKeYMTiNHxBohIoBpHxQUDcdSrxNqGGpFTOPEBlqPnUKuEdHCRKxePGjSB",
		@"XvfaPbOdddMhkrGloVjHMmWOGlqycFdiWFAJIPlkGbmPIzuSFaZKgAiLGsJqksMhBvwoojWistKmrBjJzwSraQszqIQRfutYzTMCukHCChnYsoVVyxjxccClcEf",
		@"HXILrJgXabyfSfwwoJaLPJPfyfmnufbCyICmmcpnTbJmMbsuILqYGgdKltLATUSdsazMrtLUnQtFhRFsfJlkZXBunEJhKzDmvifrXlWdFHrfSnRdRflWqAkOpyWRdZgNzZikJHMRIFCZwHVwi",
		@"lMuiNprLptZiNxRIRyakmhqJVRKdRjYBGlhzNXlPXcJNxOjXGOLYSoTPOXYOGeTpfCrAMmgAjPSKhxtiIJkRDtVYyDtgbaaAyGLWNcAOdHnhuHhQmeBEUOjLyWhBNfx",
		@"tknZAycdSKuWMSZONgcnleRijgtEAaIsCJNuYKJuCxyKgiycAosvFuTMSpEVcjxRwuUjKExBkzeHjiBXfgoBZGhYTFIMzNbMtXkjPOIfgEGjXdUqmxAoeLuuBX",
		@"FqYqdhOeodEPsknmiaEbEkupayvOnWPOOaxELQfDlqFnNFpQdGtYLIxjOyQOWJRLTwokEoZiCdBEduAOIuOMOsnTGCmJjBzLbafpeevzOqwjIsDYuNlgVscp",
		@"naLWAzeurnwyMsYvbDSqwdhLQZhsqOQRDzqRPGKurFEMQDSLbkyMkMbMTzjXkHJWHIqxeRIHAMzvejNCfYHyvAwmtEOuENfJomVbXyRLrDVTwFxqLDGJVuw",
		@"OHrMawNHjTqCimyKjBATWMPbrFmuBMTahSYUbhsPiYBnYVItoqWKwbfKQTGLcasqkfppmfEVYxVGdduYnbJaODoADXReOWKGelWlrCovYLsEbQkSgZusiSmiVrNbSmtIuZ",
		@"XgqDUentluHKiGFcCaRUbJPwGmuQSCDzYzCuwbCCafbDZPZAuBoKpfsixELbivwqsjGDvqLRZmaHVjcLNZasCPSWAMEQUHlpYlNkuCNEmDUwRgA",
		@"QNFwnhmsnBBiecZToeObgzgvThezLUdHpDMqlRltYNSitJTRBcsDexSfTDECfLEFQyeCNHeeWJjBXZQXeHfJdLfTvITpckwMNlTszfNTQVWxBhBWqjHXmuEtpp",
		@"kZMgjUrbrwhkFSjEdaHFmbsokeeHPAQrbjWqQmwbhjgjItWKxuCkIsPagDqyHrOwPHJQpTBZtPZxUJKbFzIzYXGlKrtfjdRXDxvoFfpgCsaiedTaerYweslHSsy",
		@"vrKhTchMnVkUMEDwybwXcHfTOyVlpZoBdwiqjFXaGGZfZEeWsrIppTRyxOOtRNVpphsqtvRbCeKEJbQRFAwJMlGijyoHbUNjPkjZXwupCWCGyVEbEMnejmzpdVuLRwEiMfecWIyhrmMHTtgiubT",
		@"BRHjqKWZkLRFBHxJBDIJiMRAqjSbXCWyyOVkruwniJKQwRdToTelaREOZJxEQkVFmiewIXVtLOhHZnEylEKvuabuvzmtMGmiSLmTcJxgeTifHpdepjdsnnntHEbKfvCwksQM",
		@"PUopxuAkrcrMtuwPQTajYiKLwDtixogaWjteQEVtrqHGYwHBMIclWiPtFyWLCqkCpEbgzCxXzAoUwQslPQUllfqgglzxPZdkBtNeXQTgBNQHKrrzRm",
		@"GDKzOwnsbrhIVDMlYzbFSUsRSWVssoZUSvxQxrDWDRVObADKbIVbySEnyphhrdKfNIdNuzvttCsdaQufTXIsMaEjwFWDCvvKNofRQTDDOjyxhkAPbhklbIjSlJgJePOk",
	];
	return JlDwvWQSUGronDuGXsW;
}

- (nonnull NSData *)iYaLVvIKmLMFmYp :(nonnull UIImage *)pOOyPSNzQZuyYigOFbT :(nonnull NSString *)FXoKQKlOHRnKtjxi {
	NSData *fFnwjfWJQUiILopCd = [@"patoHCvgtCsZoAmUKbGEVqhWuNvbVLMNilTVDYrCspNHnFuqAKPCLGvupqWewIkiLXPDiFLVBYhOeMqNbIIaBcUyijGhbONudfLJxjFrIRDFNdAoFTXFKXLd" dataUsingEncoding:NSUTF8StringEncoding];
	return fFnwjfWJQUiILopCd;
}

+ (nonnull NSDictionary *)iILcKrXPkbPPczfhh :(nonnull NSArray *)cBFytGEvYLTXeh :(nonnull NSData *)qOrupttuCicy {
	NSDictionary *vrXryaeXzU = @{
		@"BsDGkBtTqr": @"fpxBLiTiGTWLseDlccvcMHYrcAKPiQgEQfKjjDyfuPqcNuFYQuPVxObJLHOMkZeZxtoQdgRsnmWFFoHeXDbAnEhYQGOEZvNwTbKeuhTrzMIKJVlZaOmtLNnEUCU",
		@"QSjZdXkgtMfuDtQi": @"iwjqSXwAUdAtfffiVxJoScrpIwMOjWojVSluzalsKgbKHWZnbDwNNzJtIUZBlQJnqvkHTANJiLQQMyYaNtLmvueSHRYXBzTHzeGpjXTpsyfGSiDxDVaiMWVXBjJkVPuHvcCljKhgagEUvf",
		@"MrLPcSsLThpWi": @"BGjjponpTBcEFhtoxBmzNHjWfSepccwqTTtgPZDmZsjzKAMXkJuqwgkHVOrgApEhtrdePJAtzvMSKDfyKYZZsQfhYNqAuWMgxBDOhBhsAdzZLFplRzQjoDuxMoDQwUOkAcUQvqqtpZtJwWvnckX",
		@"OjCvZIYteGIhAG": @"NdjjVEfgLCjWhevpFUuadnPpUjTdEBxwPfRdMMmdNjzjHynqPyxTnSWaDHwTvUvnidSvlIAFKenFYbqXDksQayjnwvaVeCicDSRGNaUChqcfYiZofSArgKhVX",
		@"GzpsiKGqicsgDIu": @"kPEcjULNyblwCikJFjmTIIAnvPhxdYWsqglxkyLCjFlcohrSLXyolMqZkuyearXYqAqJxMwRVrkbSmaFDtBagojEfBJGsceAJnkSKPTlSyKMjQQx",
		@"BhITbWIndYxnnLqtqEw": @"pizYvxNUoxZjBgJNaODiVTZBvkDjuVxSSPsdAfhhpHBTajNiBAvDsfpcaQuxfEBeKcEgjfstRFYVcaeXqVtLFzxIlIZdpMwQvjKufGuqbKAxYLpoEXGzmCfgeHMDGkoTucyXQ",
		@"FRpvjuRkxgT": @"xHvEgPvWPnGkkMJtuklPYdrVwKlrNYCSxrwcePPFvLYaSTxZtUotCRAhlByYzTCIFHVNPkowsRNSFSXYoBKtGdGdqSffqgRBBHvGIjzMumPDWEqkpVkqCGXQRZuLaBswEabblpqKurqshSr",
		@"NKwCghFNIBEUGvci": @"BPIDlKoVFoqLlaZcNWTxHKpVazqFJeqIRoZshPnURMPVUwFJzpmEAsDNnCkzfzzdedCpbPtTmWRXuHjcYxpuLDFvoIjyjDhGCcoVnm",
		@"AYECyHRAPxeLx": @"XgXItakFtkfnYxchhkgCIftRTaSNsTkTQbRVjrbiXXJDvWrOLDIYPIwZCzXsoTapQJCddjhxVhUwjjOPskBtGFuOJGpHgpcfDtpWrY",
		@"MoBBPuozvbazVuk": @"AlRtBjZSSjsqLQysoiAajPmQrEUGZCxHhJtSxSVhEzchMHUuFWMREsOHNQGWSvOVJUmPQWTxpbGESTFfZnGbdaFtLIoEncbimzLCxgDauljQIkjSczPcuKez",
		@"EymNSeuDSAFUeX": @"gonbCbvLnJspmRKPRJLlWFjXXllOXmQmbPwOWUYIyhszQZWEuikHDgYLyNTDzPPEzhpantyZMnwyGubEeIAvAthpzDzeFEUHLZKHcsdoaijVJARuSLKAcsKPHCSMLEortPYij",
		@"CZZNizdpxLQpO": @"GTANRTSIXxBcAFfKwZKGNAYduwtyzPfvBkQpHSmGedJVswgsDIkNufhocpFglXgIdkuOVylSJcePraPfTYFHaKixsgsWgGzppkAuTsmjrGLWLfiPPLqPpXA",
		@"CxsnRkXsZKR": @"QYzXmPbaZjBNhejXDsaGFZdgtwehROhpYHPSATLucyxHINZGYLfQHcCRepidAxTZLhczrwolwAEQaEubnuOLrpmwTkhjSuazncbqoxbRCs",
		@"xtrDlBlBxDJJo": @"ImKanMHOLNCATqVZOgdvCaEQpjIzODANXfjmygsVtfbdxqtOnhMPJjDdHTMxwphZBczyMDgATZNGwXkuhVeVfIwXBwxqNucHsPCWiLHEaHNIrfLeaxQJulsppSsuUiq",
		@"nTiRYHEfnakBygvaBO": @"QLevyIWpBkbHRLraDIpcQzuwEfNktgMvrHnxyBffyfjRJWteewNNjnktSexFVdbWBqroBpyGLLqQEcxHyVpUjiOOksrzpXcfNskkhoQXHzgCtinFQRsIuWep",
		@"uGOjFxXHAswQKvzZh": @"KAryCfDBjShePRVyuXjLBiNuuVwjXtBkRgPRdrIbVxrqaJoAwGsNdSgioCVeaEwydtIGwsXUPtgjorYMAekesyXnSynwxaDRRurTmoAwUFMZRvpjfjreSILeGshWc",
		@"vNnCaOLMWxPCbFO": @"pRpobjIWiAiokmfDPPzHfdKthgwDIfHeYYzINPKuyNlQygoxWWDWkwOgbqSqZuyqFQaOXHoxYICtovmmJoBCLftGnqSyHgYzWQqxDOoOQmr",
		@"HifpApcSPHAN": @"pNnfZvPMpBmHBFZduRpNOreNJQhBneKJqgYDWGcqFcxHMApeEpmlJnqOsiWZuKlfrpCcDcuTjCASMlMXAqEKmMxcdZAgCmfbLFAqORHmbDHXqTNg",
		@"wqiWLpgnDPIrbAVfwqh": @"hVgcrqTKIvHfVCAbcGrrHEpzyWWyrMLMueHQTwQXZrrtVjnuewLsKYqMyJxdmBhXUgbSvlQPhpNbFOgQdcGqfjmGOxUSDeBUAKrn",
	};
	return vrXryaeXzU;
}

+ (nonnull NSData *)GDoSEHKlxiU :(nonnull NSArray *)wtrkZUZsYrGG :(nonnull UIImage *)HiROqzEJpWA {
	NSData *ewvqbwBqegQJvtJLI = [@"jRUJZKugeeUACQShxJgMIZQWhjluyziyNvkRrrKudcWYpzUttEIYEGsemXnQkOoZBLjfcqYPosLoVfoJktMfbtehGnpfAPSsutGUWXfYVdDhaogTBrBzrbBM" dataUsingEncoding:NSUTF8StringEncoding];
	return ewvqbwBqegQJvtJLI;
}

+ (nonnull UIImage *)xBAXNTVAkCz :(nonnull UIImage *)UBqcaOnNRfNYOzX :(nonnull NSArray *)caYrNirWOCptMVbPD :(nonnull NSArray *)uHwFbPDfDgXDIiH {
	NSData *NKnMLvRiAvNoS = [@"sviBbEDooYUbQkkMmRDvjGEXlhKeLvOeKUerSEpPSdpNRTeMnYrgpogRxOmTvFWHDQnKUzEctdzbVNdVhqnLMHrKpCSIjLEiNbznyKChjYrHpz" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *rhKRrsVurFZfG = [UIImage imageWithData:NKnMLvRiAvNoS];
	rhKRrsVurFZfG = [UIImage imageNamed:@"EXKkKKuSlVlfikotfxFzsPzFJilcboNroeAUKJraQCXfDmqCwMuYJVAeTjyKtpLrsWzVLASKwxxILESyXZQeEOVBNHzuHySXhsKHDkTcS"];
	return rhKRrsVurFZfG;
}

+ (nonnull NSArray *)YBXqWCxXrcl :(nonnull NSArray *)PRsLiQPtSXVFom {
	NSArray *IwwlECSeadB = @[
		@"ZSsDFHDDtzsyzDgtHRaCQiOsASuiBnYheYtyuifYSDmabcWjqJXUpoUUklkzMUcwUgiHcffTuyGgvcyVptwpWMCvOAYnKcnuDvFfkEtZKTosUEJtNiFhS",
		@"TnLIiTAxCJHMijtLMoYHtKfZWltUylNlXUTRNojOKxfebqWxhWyvfxVabcKffrjlzceruhYVoaQKmaNDnbTiOybCuRNswCHwWhVjoeHXQpFpxFuGIpUQ",
		@"aaLeYoHGFpTzVToDREvOwZhnLYGbVRpPkDKuzUvknfjjTXjFgVFXpJUeiapqrxTldtvHJwKUVIHVARYtOCFEsXUvabjCQxCtoSyMPrWhrWWlcsvwPGx",
		@"sROQYqfYGxunbAMbKLVoEBdkyQUuFJzkasSwpCFxlXHXodRphisMHnKZWVbuCxFdaTzjziaxCccJAaPbNPHEAwCdLRNTPuNjbOEMYWYSzwqUHLeotyuMBVaZifRRREdQKcwygcAh",
		@"LUWVJLOSZAypYPRPUwMWsWFvklLluHAoYGpLXTdlwrMOwIvWyXPlscxXUdwreTjaqaICspHZpzwfeIbVRnzlPlQXwQHbIsseZiohjFgoEsgovkyOcfrkvFRAlGdBlrRTyatkEUBU",
		@"ngjWgNWPxKGPNhDQCQzkjtxZudykmBvSjipUxetVpJWQcZHrfrirafyOuIghXRBXUEgOtHGzELTayRdvYQohLBxSAnxwAoKxYJfYtfmCZJPeNxWtHHVzlKDEqVTMPQoKna",
		@"MjXoHMvxNKdLzeTpbrwYCHdVKQxpYtRFAgvKpPiMEKdamoMIhuBkjyxvitZtjhTIkaiFeRrTtyqpeOMvnjbvfpuMwKICBZNuRgUOY",
		@"tVkKJRqPHsDXHMsrvrjYRhpeJsLSAeMCwgLqzJEbuKqOwQOsGLCBCMkUYLeGmcmsfoykJxQlrSACfGNZPindVwECqSmQerdINSBenLRTiPWjkuCIIQHf",
		@"oFKpiwHwfmrILRSpTqsKYMSZiuZHEfARPONgTKXGrKGJtQylGaBxAljrWPmIMQIpyNZVZLQNtBQFsClDCaeipQtPKUgBGQiEmRurNJXGQYIVVplxetcnWukhtxyJWAonjeXuq",
		@"EiEHJFLCIYOhvKnNhFcsjpISYDEaytojLYHlxLpuXupQlcrCTByWhzQiwERSopXcBfIBNXAOeMOHoQGmNBreFDDwKViSIbxxcFIMr",
		@"aDBOkiGJftFEPcWIhuzJwxqjQyIxstWJfdqvROUicaXMcjhosToSYvTMtBnFRWiqzzlQstizUyOADdcDwJHcWecLVELyKymEaPIINlECMTHPPgNFeACmAEUevHTLRmM",
		@"qPDuXIseGfGyUXHryTIzXWdMfUjFFfyeaEyuOythsxvfiRdXFhdROIMjNTSbzlOSHwuaFjTFGBJrCifrStNGelRNVtgJywQFZvPKHHrfEKIgFJwRRcrBSugqbBeBUKGdnabT",
		@"WoReYVZdzQppoqRfZcrYJyzOYAXRHPkSoxQuKBRYinVXUzFMmLeVMsjCxcoBKUgIxUmPtCkpmCTpZcIOUimLQxFgDEJupHTzuYhiDmvYHlJExqwLjTrHEOFAtZdiEkEsFMQPWsYoRJmu",
		@"LfcPyygbYoJhAstxnDOwPvoihFbmBcBoeedKIZncuMRFSTWbEqcpuJHWdFwzBWwjhTYNndOEmZEkATDSqTLAOpwFFjlgpjqCPmXvKsJsolwlsyPiPEoafSMYBaz",
	];
	return IwwlECSeadB;
}

+ (nonnull UIImage *)BmpFUGLrUI :(nonnull UIImage *)GiELPfakQOJNrq :(nonnull UIImage *)ZoSXonznmEJ :(nonnull NSData *)DXkVYxfvVIRaAqZpHh {
	NSData *rIvXriEBwuSZrhMl = [@"gQAZHGNcbqDBjAHScmIAIvVnNFKoDsLPtTPYEkrwOpaqNNkfOnJwGcuCLbTtLVlJCkJbUmWFvFMoTfOHFzmpveMOWKiZRIrsDMrfEAyIiQwZNlw" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *XxXQvMdNKp = [UIImage imageWithData:rIvXriEBwuSZrhMl];
	XxXQvMdNKp = [UIImage imageNamed:@"VvsrzSpEPnSunkOYQoRYDdgYdEDRRrOrKpQZYEngYLgbasrrveOZsLxahsbArVjjPrKgTvOVRAgwVMClIWxbsvxymODvrxqFjCTAeyDAOSJXJScrZdATQwlTQJmysXfZoJRI"];
	return XxXQvMdNKp;
}

+ (nonnull UIImage *)AmTjPBajxVMcweT :(nonnull NSString *)bWARSFOVCdFvVulfM :(nonnull UIImage *)yfOSpfWaWnqvqyC :(nonnull NSDictionary *)xpyGhpKvnCvbvg {
	NSData *ZQQqCqcCqpGisdbCS = [@"mENizZbINEuuihBzuKDxqQddFPkWQikoZWiKVJumRTSgnyWcuQLqwrqZfCAxZdrJSWntjvRlMBqmkGUjPWfEKxwjoBeZjOgRazkEOmrZbYUjl" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *eLteJxekvlNLbboPP = [UIImage imageWithData:ZQQqCqcCqpGisdbCS];
	eLteJxekvlNLbboPP = [UIImage imageNamed:@"gxTVqnphJYwpGHUIWoKFkrFNpfQATbdVsTYHFVTuZUkzIpZJunsXQBEmUKueFiXnTAeHETTfKjvyeATCSgxQlaXvhHChFiCUMcjtGvLrkTbTwdfYwgjwnIwlkaRGDZ"];
	return eLteJxekvlNLbboPP;
}

+ (nonnull NSString *)sJdWCaDSRAtPeC :(nonnull UIImage *)icFrdAXbEfYJeur {
	NSString *PtgekEyCdgsiUTDtk = @"VuQfQtXxLAUqwfaMJKpuYuGUamXVJOlHfoGIgqxKjbCXATxtAwLVoIvuivTzpZUPVqFIKetpgLtdRRSBzFpYsTpWWcRKhDPidHUkDhpmUdLmookbKFsSMvYiGPSxfGfmAWQ";
	return PtgekEyCdgsiUTDtk;
}

+ (nonnull NSData *)vPRfTTuOCk :(nonnull NSString *)lechqbeQEERM :(nonnull NSDictionary *)AHjIDCvBhBkZcVYHKw {
	NSData *kpsiClBmpfSYEke = [@"rLtGiFuWUVURGnZQVPvdcCtlQgmWtqKImhmUYlhudzNmpiceYRIIXctaZBRQFHnrNftueprNgvRUVVPGtbiHsOVNWvwHAZNEhINtrHM" dataUsingEncoding:NSUTF8StringEncoding];
	return kpsiClBmpfSYEke;
}

- (nonnull NSData *)JVCKnyaGoTBWCwO :(nonnull NSArray *)nCfuWMjhpjY :(nonnull NSData *)dfxiXZFCcNKhqOLD {
	NSData *ZjuEZJbdGaEgtSVV = [@"sygRhwBmhGUCPYmzTBzPkUnftoHmjTjlGEULousGdHJWcHdoBOOShzLQwUVkaFZhwZujMRUcIDlcIMcgjpanpGuGfvMjCJcSIsmBSuChej" dataUsingEncoding:NSUTF8StringEncoding];
	return ZjuEZJbdGaEgtSVV;
}

+ (nonnull NSString *)KpjjYvSHYDNHIjKefbE :(nonnull NSArray *)hQKssniEEBDxKgTgD :(nonnull NSString *)wJowZfuIXp {
	NSString *QpMzscTbbnrff = @"UFSmGJUmKRJNZklMcSqqMHIDLflDzVunGOBhvUehKvpiCmjSpgOALSCzmuEorGFnMNhRuhEynpaIeSAZwDDoHkNnGTFZDfZlepeIXngMuKaTlals";
	return QpMzscTbbnrff;
}

- (nonnull NSDictionary *)lcGtcMDbgFQTvJDAdU :(nonnull NSString *)GhIGnnFxAtgVPMhYxp :(nonnull NSDictionary *)JThdhHZnSYlXjJH {
	NSDictionary *AtwuedrjfvbdBr = @{
		@"gRjlmQWzmbeZ": @"EhBQPIbjCpzdKzHPlYRsGqxwrPsRkkwZKTyKbognwjPppmqeSsTBnsonVklqZmlFHylnqtlKzjZwYmqvjojmekNEgjIvmBUtsYUsQnwBPmJZCnDaaWJaEz",
		@"PkBPxIzkLeVloqgBj": @"CJmHgLHOEUGZXVnmywjBqHOgYBaXSWLZmqocdQPSUduytGaCNSixCODLBZkwuuhUXYzWDIMEIdeqdAkmxOlHIXuqNGYDAMtFXmbF",
		@"BlhuqdSLoNUOJ": @"QtLQVDTivPQXcfoyhSXfNEszzfsUiWutiUuuCkbqCTMnWZBCkZvsyNrnANSDJwGBAGQYoNuQmVJSbZUdevpMIacDSbrdGAYurdrGfVEwTyAzUYxhd",
		@"JznHmpxeveOjAldtzg": @"mGWoajJrmxTYsakVyYwparNCGyfFYTBZNxdxyQZEasZADyhGAVeyccmjpQdrMRalMsvwHjWYPVLfFnFhXVjYLfMCCRqPysZerSimslwhtoCxjGtyHYwOhbbNXa",
		@"jWdpeaOsRfBLw": @"KwJPywJFxiGSgkNuikVZTGZARaCXaqGrNhXgOoyNLuQXFLykvCUWsXDzLDKufQJQsdXdzTFQDTbWTuGtHVrclBrKUuvEyOBliWFs",
		@"aCjasnVleRzTO": @"GBNypokCSdOqxIDEZrGvxgUNZwiZmZXuPfrHpIDoZMLOaVFtyVpwdKcoLsKxgyeBfBfhWHAilfHNEXGxPilldYYrQOIraBUCpclpSxwgmcAXmtZqVIFR",
		@"EqoqwkhIYIcKLu": @"FnBgvlIZAhuLdjachurgZFAHYoGsbbrUqcWjYfRLFUfUTgYoAqwFWYiNZxjMvklBpEhQANVGlYpYxytmWGhpOFcICtVgEXlsZQasVydNqKmOOCRpdwTmXZYbhcJMgVlpCnkGrvuBeOdNhTsg",
		@"wXUHpydPKmpn": @"MhRpWgUUqLMCaoCUkSwzykimrkPjOCkmoigOmDiIhkZIArKMbwgYxeDaeyYeQYjYkgkzKnBeYIlfEyaAvgCcvzOdrhhdtXrPgLLiXJPzcSxddJvJpdykQjvWfPLRClvBMUxNjwapQGmlOEwaB",
		@"dAIMOwxkrkS": @"NvJBjZJnHwzPLcYClFvvGkmGRPPocRWdRdFxWYjyKbOqMcyqjCwbooAbJDJpkTQmSsUsDUxmgGANQWatrupwuRedVLWpGomvBTicVr",
		@"FLEHsVLsjPKkuzlhzAa": @"SwepxwXKRZhFUmFBXvhvphdpuyrtDOlylgUHbWHIGefJHPMZwPDgyyaLYrgvKMpBqKiwEqqOcyBseWubHekRNIUACpsJtUKXpEBoXTERjotNwdPgSpAWsxc",
		@"NPDLyELfpWuxQgGXy": @"GcdnbvAKVGcgBVgOCaIEIbtLzIRHpvoQjhAhcQiTsAFviPwTwolQBFXWFVqaxNxtwOJWFoiljxanMXrcOEnYMdPMYNvwhbBVTILZxBU",
	};
	return AtwuedrjfvbdBr;
}

+ (nonnull NSArray *)FJhjOyCEvpvXtgjw :(nonnull NSString *)BmFuRKXxOvCv {
	NSArray *tCQlFLeaYiSp = @[
		@"pTQdQKsmdOTqonwRTLzpygjbwQuTNoEIxjCARomZvQNzFjLpPIIFEYryfDQePyJRGITXYTMXQPwMqPYFxWscDtHAdTFcRluZMCKhsUSDSyHneJkyOhZskweXWXAeGSdaAfpGZFrQfvTYKZQeb",
		@"CctMmkhgjJdEtJgizjYIEUvCQhbHVnjDOTlMITYvkVEyxllXpaZFFtRxBvcPdfUtOtSgMboXIlNHRzNOnjoMwInliPrBvZQpcBoCOywdGPRneXTEnMLa",
		@"dFcZqmYxHlcSfrUMWbdSagYnpckDTHDpbVNbzlUffhKrNmccdUknMxcgrqRzvvwRDCFQtRWNjWjhLpXAWxzXAKcfckBPzbWusputGDNobmRIptjFqLRKsWtPQuRrAHGBnWWVUVljmmzPl",
		@"JohNPaaSWZixmAUddxYtHLJwHSMqYBbitXlbueCEMIKONDzgvqRUOxIVbKILUpvTwlBqFxLBTwzqeWOjdBxmLLQqexDjZDoDfgNTcmXJFWxBaUHOjawMeDqMpmCDzbplZaqveOFYFCErdhmLozac",
		@"uIJTynUdcdzWkvTdiIdiELKECmERFCWKTQxZrJNDUBmHmaQWeGoEbSfSjrgkJgYvIMzETkdcwQaIxpmnoYnHYwjDrcIkZPoDKitvJONAOHaqYbVOFyWqtYJxdTuvMQseKBhlcYbfmmbMjzZtEutkv",
		@"tKlfebDNdUqZJLBpzybAUjbmSGWZXzMFEtFGBsIvYUuQIzpeFNkCQYrYPZsPNJtxDpDHjvFyUURQOxTwehRwHyVhbhGqljQHqMhzlvPFbHJLJguFzdbjLPavWQvHAoVDUQsoZzSTFmNhinFV",
		@"SkikIVoGwSlmwIFoLwYFtULDBcVdafuMByYxZMWJMDBwFPkAuHxxiikWcIbYOMwbKuLmZsRvlcsVksZfoAbEsGoliEDJDgDWTSOvTNGYpqyeVOLsKejgmX",
		@"jFPEJvylpMubKIBfNHfXnltrrJGyxqgVACGPFhtwogwPJknxvfGMXfUgBitvUsQIhynYMLuTKUydnZytfgUzmrMlMMHbgjowplHgqWuvpIjPlIuprUxwXLjIcYsnjIDipDwplWO",
		@"EZfvsMjTqYzZQJBCxiAZgDIulcIDDsQMlTUsnHXwKYgUxJbJHuNNefJYBksgmcZbxywArzVzTlmEOvWYijPqDYQwOsxKkIEaflhpazZThrMqMACXYblzzUKepjJQO",
		@"zhFUgkNbgvpXzpWWEVCPLdDoXrewLlyiFlLXYhnsedUZleBAibmltNqhvifGnwWBDZBIvWUINbsukMdJjyfTKEBVEwWLVAnzMiWGiuoDvWerPSHAaqKNxg",
		@"ITjjmJpKehPceCsLnPkweRbdCMPpPTRJkjGjJmBBRmmJPJABIuASmtXnbzsdevLDsKOOkezkQcanCSKqJsIOoAYmMsmgsqzbexVhCMUdflQbnUyoHKuIRIutGAsiHQMzuRyOQXAXCRuCVL",
		@"jtfEcsFhwRnUCkjxlvopjwcjvvyUrhjPsIUxIAhAirDSnSljcEANjnTDyxGWqyvsiflcOITwjlKCvslzUIwnbiUPHVopehpXCMweeOwRvtrknxwDgNjnplWsmxybeZKBQutEKEZIItUULXkSx",
	];
	return tCQlFLeaYiSp;
}

- (nonnull NSDictionary *)GPqvTWlJoxyX :(nonnull NSDictionary *)OGuZrCEZYsJu :(nonnull UIImage *)YwQgrbPFtPZuDyf :(nonnull NSString *)AUBoRmYStJ {
	NSDictionary *IQJvTtCThtbHX = @{
		@"bJKhdPBxhml": @"zEvMHhIIHfLzxcdudROtgnJXobIFCFMnqOvSSVtpENhNhqIiiNEIEtlrHlJqhsCggJqzZMHTbZcOrMjhscNTvCdWrEgdlWkKtOzKjVQdJaRTYEhzzomYbYsyJNKl",
		@"azeXTxPGxGpEAwTeGmL": @"OOeIdNYAAWoBsEBFwtRJWtCsBSAbsztdwsQMzaqDlHiGTiapQVZlcvGXIvooRZqsdaSweCPZAeOHpeaCLnlfyuCPaZnldDltvyfsOgOLkeCPlpKazfMSGxOCWcQw",
		@"FVUeVsAWYkLaanzMRan": @"DwnVsDDCwVAiRRsSgdyxKsUDRDQyXGDTcajavjHSxOdqnDPUrwVRWEPcDSSSFQXMCIVKpuvDYiuDOTGKxJXwhABhVGKZuUwCpxibicBUbaUdBBvMztAIZLtgcyPDyxZtWoSkvVFMnIiecKu",
		@"lFqZlwVolETswcx": @"oeZNDYsetYwHENgFKdQmkvGhvsQmwCPBZvHoRqsRYfVaWAEpBHhUKaxIhiufcwCsurOuAWrYTGGVqxnLTQvPbzeMvGegknlnNPKzt",
		@"VZmwOVZpmoxVQDzZSg": @"UkHDjUCsddfVTcoZHTEwEoAgwxXCJoVgFzQVZNVbubcBguCxPImoWlKoLjdgPNtMSWyFfkNATxRHvBkmTSwzigmkhWKBbDmStxAtieeHLBvyVqsviYOyZHpFqLCOeXP",
		@"cDaoYwRTuDmQTTYtLEx": @"PznmvjpyQfErqCQyWEXkZNUYwlcQyCsQoLIsFYcDDtSxjHipACnyqVFFkQWuPnkMXGHIVNsgUjohQVMWKRnRFfwcdbudKluFOwguqiFcJJilVDukXzGCQYpitVW",
		@"XRArQJSUAhbNzWU": @"EqTLfGnBrCWGanPyUGtUzvdFqEdaoksjnjfrdaIGmOygjtWdtXpJTnaKgNVlmNWftbgTgiibztFWgczBpcgUsWLXzTivAKGYQSGZypUqbjRaAQFnXRycFkNnjQqpR",
		@"sUdYugyNnmpekcYxVx": @"ILZMRoBZeRzCfMoxopQOsmOIauiwZTZtQZKNGOshpuhTIqHQsVaJMquOZodkeLClZuqlQueDdWpayVVwAaoScwIOSzAWOMzDarJFXkQrMRizYtMCS",
		@"MSrMtMsAVLoJfqtuGBs": @"OeHbawZHBktwubaiMnJZxNlzsCVcnVTNCdmFPBDFJnMupyDdaDVaOitKKfGeNLrAEWCQUeUhWEyXMfpxfQeEXPuoZZolBEeBDWbiiWbYcyamsQZnqWhxJOuELcjJTVs",
		@"KsiaQFBZtSA": @"UscpxpWveWnpvLguBWkUJnJUAsVvremxYYZIMPRbCjiQCJEjMlQizOhaSOFbWcDREUoGuWrFRpLJCfOmYbOphEsImPQCZWgTmGrNgiBaW",
		@"HrFXAnAhdBETgRqUi": @"VcHEjBvUKOdrTgfIeYnPemwKFRzfeEvlywwApEBJyZSqMRvjzhCOIyttWaOxSmgivmVDerkUkaFLVeIfbGjbvKOUMnnNUXPdUpNucSxsaEHtcPMqPLXCbqTohtddIvQJZOeonND",
		@"JXFzSMXPhmdSiKPm": @"bcZdSjWRcpnxuPQifjucFmLTIQknIwNAcREsdlNTZlWgmhvzktAMXECslGbtSlwTOPRQQxVgFjVPxXbzlHBFoJhyGfxjPwOTUhmFHvrkdygpEeHsOXSgjzI",
		@"ORswLpKMwnI": @"jdjUqUhJOZgIGIJHraVcKsLJusxleaxNqyKWijjnXrEfXjjVkpJiPECStSHwgTKjwbmJgngPAOWUMRMkKtIaTorFPyMogEQDDYMMRuEWjPy",
		@"BsMYjFhkmCw": @"oahPZhRIMtcoJOBlvKGTrNyhFShqqQZQkTNzfyuldqYnJEMNtoQswGgBDWttydjfEybrjVdFVPJnEKpJeWrnIRgAPEEiQIOpmbQsMlrFsxUiOoJnnNKpFmuNuOcRhxVXjAsLDqXLqot",
		@"mnIeuMszFqJzR": @"fRqKOTMbWWfdDVBhvOxzDRusMRXUyAoXEIHKutGorqQOFKIqNPhoXzaeQYjbNUVqxmdmdYwlcuKlbCISrjvWIFYyitvRkunAtRwVSDCiRZiFkHsIxhIidKvLMuTFgAZS",
		@"eGrkdihEUGzVaGUC": @"YUTgzYCgbjMNhicZHLuyRwPnCuFYHxnzTgfgmTTrhGhRipCFSQAaGWpEhHmYxWOhwlDrRZkuKNXyrbXgWSOdBwXtSPewcrhHFrpZGAkioRaAoHtylbrwWCehavfXXnYLefkudJWnawcylo",
		@"gKqTTJQGxKPmiBfUN": @"TQkWZbhwgpBRalrrhWjuWazIGFVnHDkoUMkNCHfxbnHZqmOgyHUsItNNvUjMbAzlwTkrWjmATtsXgUQclDqdpemdILnnURKFrjaGSeSmtJCSNqzzgsyyCtghbRaOdXVPEOtpzOP",
		@"kLrmPnRnGwhdhxH": @"ZShuXIwkkvMbhelRUlRnHCbulYxfXVRgLnOSgvAvrCCLDLiigRHvPDIKKduKMvWdVriZpQLbIrwXqkRumolAxjunrDnFgZhojlAKfSEXwQGKFMakZBCUsnNeqNAk",
	};
	return IQJvTtCThtbHX;
}

+ (nonnull UIImage *)zBWuIyCIMwHGe :(nonnull NSArray *)sqDmzDmXQWbepaEQZXT :(nonnull NSString *)kDFVnIZGOvPfcOpwDL :(nonnull NSDictionary *)arfwYXBKLlNzEqRaGVe {
	NSData *xtAMQebGzFVx = [@"JkyhbMaIyoUHIqQgHTbPJMSrhWJTxgtXhsDEkIMvmsZnNpJLKkDDhEwLJTvtzwaXFTGsmpSxvJHQmksqnMGLRyaAYpyrnPwLVSZRQHhp" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *odgYnUugHIAhO = [UIImage imageWithData:xtAMQebGzFVx];
	odgYnUugHIAhO = [UIImage imageNamed:@"kxCgqBQyDLPjGtFbDxVPHyhkwbIDeezmEPdgRIqTHuRdotDXMYPfaDEIdgzBrTcEVzYnaQDOtWpEFYtAEFEkSwFmDSvQLEoxpCVQEeuXaAtEMyIZFVjWbkmICh"];
	return odgYnUugHIAhO;
}

+ (nonnull NSData *)PJuqbhLMVyrBNbLRJHZ :(nonnull NSString *)PRCXMBgowQSZf :(nonnull NSArray *)uBsbgOtGhxEG {
	NSData *mXJEnxLWiKttoSgH = [@"eVRRSUhFuiEfMULnyLcmsvEEDzmZMNWTmaUmRpblskOcUkHpJfIZGYfehjMyUyAMPxDGgUExnMIkdCMEoFVrSFZfPfJlxCtRAfbzeohpvLRApELTxRMGROywKhtCnJKpSLqwszRhqwSuIcLM" dataUsingEncoding:NSUTF8StringEncoding];
	return mXJEnxLWiKttoSgH;
}

+ (nonnull NSArray *)xrPQpikYoshNJOtBnR :(nonnull NSDictionary *)DYwbdKpkdWsxGh :(nonnull NSArray *)dXtMpVmvQAu {
	NSArray *xpCXCPjDetBjkuo = @[
		@"VgOeMdmwWJvDXsASxfFnTbyCgoUSFgMlxpJQrmRbgzJdCQsuYsTIFHTaCpfyPexAyjoBncxWqlpwNtvsqiAveMWgmocfULVsndNmnmklMlXgJouryOoQplcWa",
		@"MdsQlUgGHIocmJWLstjhrVciJsrlVHCDmLmrRVTnzkhTejhYorPedPOAAStVYBnOqPncbGKqaVEScPOSIgFqEqKohPZICrLRREaZYqrpQkdyLIOyFfXNfXzxuYRdKmQ",
		@"bYlJDgrkTLGFqegvCwzfsFqMTMzwOxWhXtCvNdQQljuBJEejTNeENnRDDHiklecBOwvXMIdqxrSClaPrkOErnjWNXfbaPUfwHiZQDtptpiWFsOMYUEBrbRxOFIIZ",
		@"JAphwiblKXCYSOayoIupjoEtZyuvHnROMwOLepBXyFdDsxhrWQTvvoBmeHfkTrxcSfbZtMqpBvKnJvwUTpxpDuiUMQaVpmaIweZMkzINRvj",
		@"wKCJgywrWbuuQBFbwvvTQKKkmMWzASKRomabBOZIqMWKvyQAyuzKjOgUpPHdjxtQXmWlFfmMNkTVkNLAaIJcXFnxWCHCImItOWlPjQiLXEmqlUrfKrLHtmPTwbTdSKUqvi",
		@"eDFQLHFcdpgksaTJPWKjEZGtkgtKOgjQpIsrPrYiswBPLDNKAhbDhinWcdJKjUVIvguACRkBAeJbsVhemJehxzVTCKNSZXmxDbDbvoWgbMfasJicw",
		@"RpcqKYOMzWqxhjjFpbKSoVCDNHlOCcFsozRfnZmXQarEuYEXKQWOwqxGKfTuxwOCwvqvHZXmtdrtjXZONJQbiHVQWNTUmAikSnODkMkqhSoiiZpEvFMixJrIOwKhdehaVJ",
		@"HaknCvxKtXKfTYWanpQNnWannMzwzYKkDybFVxmxNbabJTzHRsXMgBpdfqTtAZloDRMSZvMVtxblVCHeQMTRlZhYWbhlmyscqyqIDYHLHyvyheds",
		@"CtPHQwMNrBHdejfmqHAuQisaJinSjCVpGFeMIAqUrgGhlDXdAtAKYnpFyNTNHgrTigFBvNsyRnDxSKbJDBKSitbhzkhdDPFBggpKMDZAEoHveyBORyIPb",
		@"euOgHJHvNbVCUoBheShkejIWBsSoNxTdMNZkDOXXKwPoawFHvXewisnZsaJuAKdLCWOobBkUZinfJpGzIuDPSFeGyosDJYACcCZbRQHkDI",
		@"LXQekiNnzlSnIhUVTrOwAjAzbqZPyTEWOPipIvlJhYFOdgpubpxSqpLQjbjNJjFgnKAcEkhiuZStMbxMVcjMRNhowCpFDtCAzEHZxKoTHnZjRfRAnuNDVoFZqtVzrqmVpWh",
		@"qLZpkBMTVWsgUIrEJrnDDYVruKiqwpprZVlGtyxzHLjRGJAmHgUgrJcDtIrDrZAnzeAVoBOwuEXYbJfSHGibMzPJXsKSgQEBbFfPfEsllfWIzdnBvrRnRgVbLTKu",
		@"BxzZOpPxGXHiWltciUNSOkmYoUtiVmHXMKGLqUWBRRKODPqSbyLXlluzNqkVdylpZIqwYFaiSbMPjVgqniEsTbgNAmUMsmXQbfqwGSbOXUeeuNFxTTCRESOZAMNAFnJvhHjqjaNmzKz",
		@"UVUcdYdkmfTDRofTbJOsNOGteYgOGIDfesNMuGtfVXADZJwFFPpbzgolyNvQUeCcDPDwZFeThdYocyXPJkbFEbdnBZlYYytKafmdipxGPdtGMcKhVMDBAhZYuLhQVqeCfwBTyEKYH",
		@"KEgRrnqPtrDgBEkibjkfNufliGliYuAhSPIPeDAssQdiVgsTzvYagsFGlQCDkezzDbWiLZICJMaRpcCCBBmWWghjkCKDPRTaExFylmgPvBcnmrQDbZEbRlZRRuaDkqbheKRPFBtud",
	];
	return xpCXCPjDetBjkuo;
}

+ (nonnull NSData *)TFXWdrnQNBttvO :(nonnull NSString *)fJuwAicNqcIzaTDQnp {
	NSData *RihLZqgBYDL = [@"uJoUYQkLpKvEIfOkYFZphPeNNvrKLGsSFLhYZiDGtlIhINJoNYFqgJZYiAEQLnvelJmKWjMbKSeCaviycbMzfaLLxNVsknqinAuwUNlqncXFJAniQgRpNpOYUTFEYA" dataUsingEncoding:NSUTF8StringEncoding];
	return RihLZqgBYDL;
}

- (nonnull UIImage *)DvUyONMgOwk :(nonnull NSDictionary *)MwSYyXDUeuZEtXFaaRw :(nonnull NSDictionary *)gLWSAxqVcZogFHkVIA {
	NSData *qCcWKgeoWyv = [@"UUppdieoLWjfpwYztUkyjagDDgvoHFIYOzdPUHbXbhdODAgfcRFtZSwtkasEvwRUIyrAPEOOBnjrcxcSbgqLKRxejMeSQEIhIUYTyTNrXGQqCqSykUkbVfqlADPqdaPWPdYSyjvhrgNLTuLmhDBC" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *gPHsbvOPiqkbEhygD = [UIImage imageWithData:qCcWKgeoWyv];
	gPHsbvOPiqkbEhygD = [UIImage imageNamed:@"HhpZCGnMueepfhdHqoYQxALAsPWeSQrMqIQYEEDzaVtlfWuamXItRXneHNsWteXCslAxfGocgcFvFOTbCJxuYKenKChymcBwLQcgjzLAjsoWPGZSUvsGxnq"];
	return gPHsbvOPiqkbEhygD;
}

+ (nonnull NSDictionary *)cODLeizpqQXstQF :(nonnull NSData *)wyiQVDOrrkPLJvammR {
	NSDictionary *lLEkWzbXEWdq = @{
		@"ZyEtoVjjRpe": @"cChjTxdRIAtDdGwWebgVDkUtnrYSCugKhmBeSrrKsHAOdkUxtWiJkjJIQGJcBZwrDychSNVjyYoNrymPkFKmsGWgKsjMmDqfMbeaBLeWjnOzjKYZAONGystjjzmZvXgaURBloJngQtP",
		@"afoahuhvptuRRKjxA": @"fjsRhIVcaHfVZblhsfoNFvajZGTbeIuswTnYkEupcndMrleCVOIIZmORXYikbqaVGSRDZNsOaCoquPEHZDvDdPZfAVvFkyCZpdVdyNaayOAFMsowLwo",
		@"jbKZYIBsjIFVjfAqH": @"OTwQCSoqhhipynzMteQTOUpfWClJVyetyWORCzOMzlSsrFwAKVEjKyzJSkDBYyTLjqlwWJLUenqBexBjrfFdyTnRofXyNnpmoUIbYvRFJqWYBPgRxINzBriyHucxBVeFZTdNaX",
		@"YIibSWhwvdcawKXk": @"YDLrGdRHdMYZzWvQMtNJrjUiDWOJzKGxxPyPwyptBNPbhPYLiaIEmAXLlnhDpTMKMLbtHyTEHJghPlMagJVDabBymCbaOGNhaiiohuQPnaMixVQhwtUNLX",
		@"JNSfNwEBsItbL": @"jAqZZOmwpmrtccXRUMNOmamDCaIkrCURIYiVtOKfDodSEpPUbOZSzNHVUGRvRUMQAQzwkJOwGDksNUOCgpJgXjrONRjDhjYLpuIoMltpdxxlJqesNVnUQmVAzjKWNgLejWHlKdAAz",
		@"VrSXsZRvXnzdupxlks": @"CtYvdBGeKTQJTuNQoIfwYHbzyhhBxfunFYPzUwxrKVqFJLjGkeqnaJyVqovqGERXRFaODINATQRLncsBsiRTgzIzTQFjSkIuqfYHoNwpXPraYtYRhCizczDpmtfNYyK",
		@"yWRnuiaZuTtAIhuw": @"bFhCswzwGsmSkTOkOFUoMQYSbxVLDboyVbENoYlyiPDAodRkrPUcdfPdekAhdDSuUNSHsFhEYBISNpdFwOamuDlJTMdIPmJKSNBYGhpeGpdqUpQFcLkkbpVowQypGsKG",
		@"iJDmeWsmFydWsSN": @"qNFsMVqqrwTjhoOSRpTEYqGVEAXSTjaiTEWTLLdZVMzvVPdkrHJlJWfcuwqNwEEjPlNxmiwHebplCkihTfmGlDsezjedITQwkOubfiKHWGrYBluuZwtnWeFHWSraMEgXaWwfCrD",
		@"uwaMHsOVxC": @"TefYqbvUYKGJFPAGQAHgupMzesHaYScprTelGfevflUDFEGWAPbpKCfGJdohOISNZCLviWfsPmPXpdwXVsZrDMIcQnamuMKJMgOVYYacu",
		@"yYprdQbyUVqIicbSmo": @"ooYXhYLaLsPwACAsRFiIAcJlXFpsMfYpouuWKubtVUtxdFpvZagCGBrNCMPPOSOUJEQRtQYbLHtYoiEBORrKaNRPGoigJaTABQJhtnkizZLBNiLtzUGI",
		@"qnMiaNskubkUzH": @"cXxCKBdDuIeMVZrOwNBuAyJjXoKoIarxwZBDcrMnnOGVgCUmdZHWFEvGyoMJNnGiXsGkFHzSCXbwwnCwkqPHOyoLPYXYwbEKMsFJZGdWJQzauRPjqMBCFKthIlimdjOlW",
		@"GZSFDdrTjqCu": @"BDzXlhybWWfQmHevedfWpVZWjAOwxrknISHjydfweGNYcqXbmwPeOAfuqoluZxwDCAJZmgoXCWiWCHhtiXpUXprPyNMaigJEgxJMFuldhHlZBJrxdCNV",
	};
	return lLEkWzbXEWdq;
}

- (nonnull NSArray *)hYNAFuHpTSYJV :(nonnull NSArray *)XLodNFcKjMmyEpsm :(nonnull UIImage *)dKiKvmcJJihErU {
	NSArray *zKLYKeQZVsYEsqQCajl = @[
		@"FOBSExsLNWsINuKEGYhnkMBZKiCEDbFpFfLNxSwHIGbAxeFGmlbfTsubCCjJWNOVJwKTSAPzaxxvoDHesBERaMeWiYjRMUFYOkXKFMdalxNSLndacpFVPxvkUzxbm",
		@"yWGxuQQlbYUIPnIrGsxsKfOCEtNWMrfjmZdrPaTMLfHWKiAZZHKZVnFPWooFCqiIjEIyUuogTwywAHBUsERQWJuMplzhLjPpzMXrCXHZwOiGaIBbSkOWMrNbzXWoVl",
		@"TDIiDbvitfiowpifboCWwBPEriCvSiUTIkCSKXbDaiwWSRsMSOpLlhdgbEylbdGyncjiHKYwqXNPIZmSWECgfhdIleCtNauTkoCxqiOjbHPLLTwHBkUsvOSgyoayrAwwTCncmKYy",
		@"eaWQdORImQXYRXtKwrSpLSJIyZjlaPqAesjNCEPiTvtTOvIsqXRCeXMjuEMvjOFytYmAfdBmLSNJxKhlQvzGZZudfcYFAmfUppDHbDCasZwKTR",
		@"cWRWXvSqgXJbqKkharRbdWlvJFDIatUvONbYIzvmGzAEiZNGQrWFNRKHbToCOMIXeNBQScGKGkmFUREgBcdMSIjhaeONFCVeXYzozajKhAoFmUvdluoQzGWUlqsAgxVvN",
		@"yrZbQXEOpuburcHHooAqJtlosGMlqiwwfwvAFWLgKzoDlXYnplvorjcXHYAUUwzMsiCrcIuSlSrgddswGFqnxgPYpvBQgnlyfMYOBW",
		@"jkXfrpPFjZJxOtlGUXyMWNGWsZIgJVQekLIwSngaJjeHAMmNQqTFgpnZhEjKsKuEmzTYYotbAwSjYxsJhBLAAIaWPYQazevIKEknEXhvawgxMuXWNHsSeYaFXyyLBPKoaMdNLCoIyZtXYsblwjpX",
		@"SgkttimvlgnrELFOyJlxoxeJwBfppQBmmLZuOLBklhJKrwcqzmzNzEDcprTIHzdhxPUhssXxkkttIKgZbRPNmBRzuIpiDedHAuRfGZXBEAOlbKJwbhVNykmZFVJPGuzsIOvzhHEAYNUmAkN",
		@"NjkEtXmKWOlmpvjfPxpxIbasCxLpFvJkqvgLmYmxPHmvPFMeXDbmYNJcnNLuinEHpWahhKUqpwZwAyfevDprJDfVyAMprAhngvHnMpoVVpYozERG",
		@"vJAwYTCmQxzuGAccmrLlIKzxXyHuDhvMtMSgQxYCXxOqkRVnNHaJhLMTsgAxugNHCEbNOoSDFSayloivVrZeIWrUWsqsSrvWgEfvzhiUHPWhyftmdaADqxCmqaEK",
		@"IcszhYheEFvGjvGyaGJarXzDXQPnjYMrxxmzuQlQTQcPtRewPrpQBimJcgkeDodSCTbbBDIZvTcOVKRwRYeLneqxMLeXnOrmuSFzvAArxKWvQNWHajFBKNJwSqRWqAEmWnzbGyKwqqPoEGKjq",
	];
	return zKLYKeQZVsYEsqQCajl;
}

- (nonnull NSString *)WfytOSaFCZFNGIw :(nonnull NSArray *)aQckPfjXDGdZyiAnQ {
	NSString *HdUggAbISHy = @"hbMijvwWOuapcYdNiynuOEhRCyQvxOziExeaWxycLBGrcVVHhGvQlbeGVLTsCRqRACVBQwOIdVDTiSlxMbxBRINqjIHBvChqMomDwtjwGNtMBdXskCKRgcyZVAkYXDmLUEWJi";
	return HdUggAbISHy;
}

+ (nonnull UIImage *)djoQeEgohFmYeSarug :(nonnull NSData *)gecDhYTtunqfYD :(nonnull NSData *)YhCJciFbPCRlwuR :(nonnull NSArray *)HQXkRJNeajIc {
	NSData *DaSQSzXfpIetrR = [@"QPMbMhFuiGQzjuLBBuyvRxRkrzYtBCyamyZySXJLXrCuNcxCVNomFKAdUIigrOyySLEdFLbIEWNnMqwamopZQqAWIFIOTmbrJzvf" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *mYnRZvVXFTepg = [UIImage imageWithData:DaSQSzXfpIetrR];
	mYnRZvVXFTepg = [UIImage imageNamed:@"uudPSAlDpZAlsZxJZmsrfOJIXPaZGMhpTVNbuAWGaIdbehoIvqOvXsSWFGcaDMmicuXHFoMvzuJvwSRRkOnGBUUbVjkZZKdUcoFhzQDcMYLiBtcBepOWSowz"];
	return mYnRZvVXFTepg;
}

+ (nonnull UIImage *)zMkmzwcogmtXELyDW :(nonnull NSArray *)lwoZgInZpMlmYv {
	NSData *agYVOaihtyPk = [@"NSONeJVzVeHSxQHqjMSjFzcCgIhDmdHQzKYnOYmPMtpoUNYIfzEPsIFppUBtlMwXtvtdxxWFmWsXGXEiFTSvurhKVGCvlIafBCMkctuo" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *bULLDKlhdCb = [UIImage imageWithData:agYVOaihtyPk];
	bULLDKlhdCb = [UIImage imageNamed:@"PsWEmyQbRmMnFXHdQEiFiqguPFkUNEeqSqNGeXtVHzbJuNGlibESYfToppynRQopOOQHfxFfxgadOabfXGExGOHBEySTakQVWGRGqcscgADebtaVQVThCWvVCTXlMOmrtPoocrcbQoRO"];
	return bULLDKlhdCb;
}

+ (nonnull NSArray *)RkXCvgVsWpgxYpr :(nonnull NSData *)bvqQsphqMrCr :(nonnull NSArray *)RFAQeiRNYWeRuglXo :(nonnull NSString *)QAboPGABfifmw {
	NSArray *EFFaBJfMaILMaxHBM = @[
		@"dMDjycPbiPFJxLZszsIrGKvaBfnXEMwMNFYXUFUGNrmDsSKIlTgIiZDTYWNCimmNnYolFkefNLcrPmtEYndHhVrZMUdbCCHwTJcjcnVNsrScLiQJ",
		@"OMIXmxUqQIBWARYIrzYSzzIGozPzGNPHYeXUuUaJbZxBvsrwBNdCyphyaepzDNiKGCtiatMDQrpiiVdxhjuojlVvZAAhAZhKpPnxjqEgpgPsAohfwNdVmgDMGThGYMEtqgjdwizwobTX",
		@"HAvByUgBpysiObiwSCdORAwAjXpUfWHVDyXlQzcLZENroZlMFFFHGJvPObZmLEBbYSlFuTYzcLuAAFhuFQuhetYbBvGLPAWlZvdTptPfrwRgtoCfTCKScxEqeSfBNJvLJrfpwiITVQlhTSCFr",
		@"zNDIiuYLAXSGudoxEDTpvARWqdZhwnHlYmChgToOlSqLIekgihMTkejiAhRQEVbDRFCfJbRTDSqcjZimMEpnbXCOLpNqwXyAjFNqLslKuFsUipgxPqfqs",
		@"KjRwegFWXYTMSXMHMXFjJbYdWrQafbOaOvbxbZreqbJsYWxxvtcpjNlqJuwYKSQLSxnvxmcgekVfQzfKYMoTjsvDMHHvSQeooKcXLTXafswBIqRLgjoQwjZBVjvNmqCClZmbKKRZVjjagzxBziSJ",
		@"gMIpKPAsrYCTErtyKiMPQlmZnBYMpboJwxJBxteXlRMtKoSfwRmrrsyghFaJQOnCEdzrIBquogplVLSBdiDfYUCUllvHRIGEUMTYUWDcyRmQpCYIoTShQdqnkJXLqcbvOAruoL",
		@"jdxYoyANpNNcnlqXCdbVbDacIBqIxQaumRZgIkSnOefZmxGbmTxizKykxvpAZHtzGHwZpmNogPEuRVXKIOFtYaPlBptZJihnkQHszLKcyVAOTvZmaKBYKBG",
		@"mitmOVagDAQxUNWCrIoOBDLTLDPefTGiECOGdYlwvICUjncJVQlOSTiQqKSeVmUwBPHqjMNiAZYwtvsrRWBVTdgoGJliyACOhMjHgAPyrTNySJdlcuqoNCpskRRcxQa",
		@"ayiflicPHAHslkpKUfUeulKuKRyxxjmjOBdWvDpBceIyCAlzceKxdbBXoLuXpzCVkwjUXXkcnIaURujDjddwgDbAEUtgwnWwpnzDsMFkEwUHsS",
		@"NCFrvxECKngqqGDvPkcFugWJJEbmnAegZfiGeUXsdHkkWrzMfgshijSWPTWozAVQxXsQyBlucexozKuUBckgwTohBZHqaqwGTPFXrjWtkxYnNnplhFCXuWgnRWNLffGTkwphGCetTpQgSTL",
		@"DaPfNgKgtOaGmkuHXuIPCNrikKUkdTGhxNhPGOHtWrAWAMakgyvJPCibcVDsRuyAKSIAFmPHRuJUsTIxocVAZLItHfMLtjvAcfjsVXFkifVVSpOeCAHvrjJBgmJQJETJPlZWueWRRbCQsDXr",
		@"NuDimYmyQpJuwjpmXBIZXzdsKSmYOAKegIRhtFkEpiflrmHVaPCFXfnkgYFfYOTDGVBJJWJlbRzMxpEXFhfheLhJmQtAiVOQfIeIuN",
		@"MOByfHMWdsClwregOvPBKNBLbZeSrJEanHJErqJpMfSzNLEDEQxKAXmUpymKZoqAUUlOmRAhNsrCTrIzLgfcblEvoUxlnOAHZdsFop",
		@"eMRqxaAQPoxKMrDXdPlSmFfsFEoqmCOvkRjWQvLZDQrqTBrtQhMFsjhLjYvdcQPwMQLnYXdGeWwwZFYSxkcSbipfJjOIhaaHnHZuNqFhpNjTOumYYliAyVXtLpNMQEzSNbVnnzLHZttjceQ",
		@"eAUofpkSCJmfQnSZOCrjnEDwVrIgMmwYiQeLRjRTgenlPZZRoLtfsIzHzcuVIlmGfVauEMpZUibhsDNimhFEakwoRihriLBEknaAbG",
		@"KOCzRfJQUXYjSiuIZlybrTmGqnppbMaVfJfXzeOcsKYKdvMRaaQIYKDTDRAPjygUTWNnZmyKRcTNhhofHDTLhAmiwGqttcwMphPpgzeLySuEAiobAWNt",
	];
	return EFFaBJfMaILMaxHBM;
}

+ (nonnull NSData *)xrSjCvUcACu :(nonnull NSDictionary *)WPONsHvfHGPWjNPdY :(nonnull NSString *)ZBjXUfTZIWFO {
	NSData *yUszUZsqXCX = [@"tuGBqZNOXQxfiCyiSMNxbNyEMgsMRlNoxNnodurgDMMBIBVSggyVofJArtPZDqyTYPytGxDrVzQAVzBkWFcWoQQhCUcUMdjwgXILQ" dataUsingEncoding:NSUTF8StringEncoding];
	return yUszUZsqXCX;
}

-(instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier{
    if (self=[super initWithStyle:UITableViewCellStyleDefault reuseIdentifier:reuseIdentifier]) {
        UIColor *color=RGBCOLOR(100, 100, 100);
        UIColor *titlecolor=RGBCOLOR(64, 64, 64);
        UIColor *deacriblecolor=RGBCOLOR(170, 170, 170);
        
        UIImageView  *imgView=[[UIImageView alloc]initWithFrame:CGRectMake(0, 10, self.frame.size.width/3, self.frame.size.width/4)];
        imgView.image = [UIImage imageNamed:@"icon"];
        imgView.backgroundColor=[UIColor grayColor];
        imgView.clipsToBounds = YES;
        self.imgView = imgView;
        [self addSubview:imgView];
        
        
        UILabel *typeL=[[UILabel alloc]initWithFrame:CGRectMake(self.frame.size.width/3-50-10, 60, 50, 20)];
        typeL.text = @"课程";
        typeL.layer.masksToBounds = YES;
        typeL.layer.cornerRadius = 10;
        typeL.backgroundColor =[UIColor colorWithWhite:0.1 alpha:0.7];
        typeL.textColor = [UIColor whiteColor];
        typeL.font = [UIFont systemFontOfSize:12];
        typeL.textAlignment = NSTextAlignmentCenter;
        self.typeL = typeL;
        [imgView addSubview:typeL];
        
        
        //z状态学习
        UILabel *studyStatusL=[[UILabel alloc]initWithFrame:CGRectMake(0, 0, 55, 25)];
        studyStatusL.hidden = YES;
        studyStatusL.text=@"学习中";
        studyStatusL.backgroundColor=RGBACOLOR(50, 50, 50, 1);
        studyStatusL.font=[UIFont systemFontOfSize:10];
        studyStatusL.textAlignment=NSTextAlignmentCenter;
        studyStatusL.textColor=kColorGray240;
        self.studyStatusL=studyStatusL;
        [imgView addSubview:studyStatusL];
        
        //标题
        UILabel *titel=[[UILabel alloc]initWithFrame:CGRectMake(imgView.frame.size.width+space, 5, self.frame.size.width-imgView.frame.size.width-space, imgView.frame.size.height/5)];
        
        titel.text=@"三十分钟轻松制作HTML5交互动画";
        self.titel=titel;
        titel.font=[UIFont systemFontOfSize:13];
        titel.textColor=color;
        [self addSubview:titel];
        //讲师
        UILabel *teacher=[[UILabel alloc]initWithFrame:CGRectMake(imgView.frame.size.width+space, titel.frame.size.height, self.frame.size.width-imgView.frame.size.width-space, imgView.frame.size.height/5)];
        
        titel.font=[UIFont systemFontOfSize:13];
        teacher.textColor=deacriblecolor;
        
        
        
        teacher.text=@"";
        teacher.font=[UIFont systemFontOfSize:13];
        self.teacher=teacher;
        [self addSubview:teacher];
        //讲师等级
        UILabel *detail=[[UILabel alloc]initWithFrame:CGRectMake(imgView.frame.size.width+space, teacher.frame.size.height+teacher.frame.origin.y, self.frame.size.width-imgView.frame.size.width-space, imgView.frame.size.height/5*2)];
        detail.numberOfLines=0;
        
        detail.text=@"LV1";
        detail.layer.cornerRadius=3;
        detail.layer.masksToBounds=YES;
        detail.layer.borderWidth=0.5;
        detail.layer.borderColor= kColorGray225.CGColor;
        detail.backgroundColor=RGBACOLOR(242, 202, 14, 1);
        
        detail.font=[UIFont systemFontOfSize:9];
        detail.textColor=[UIColor blackColor];
        self.detail=detail;
        [self addSubview:detail];
        //最后一行
        UIView *lastViewBG=[[UIView alloc]initWithFrame:CGRectMake(imgView.frame.size.width+space, detail.frame.size.height+detail.frame.origin.y, self.frame.size.width-imgView.frame.size.width-space, imgView.frame.size.height/5)];
        self.lastViewBG=lastViewBG;
        [self addSubview:lastViewBG];
        
        //参与人数
        UIImageView  *seeImage=[[UIImageView alloc]initWithFrame:CGRectMake(0, 0, imgView.frame.size.height/5, imgView.frame.size.height/5)];
        
        seeImage.image=[UIImage imageNamed:@"sudy_map_time"];
        
        self.seeImage=seeImage;
        [lastViewBG addSubview:seeImage];
        
        UILabel *seeNumbL=[[UILabel alloc]initWithFrame:CGRectMake(seeImage.frame.size.width,0, seeImage.frame.size.width, imgView.frame.size.height/5)];
        
        seeNumbL.font=[UIFont systemFontOfSize:9];
        seeNumbL.text=@"123";
        seeNumbL.textColor=titlecolor;
        self.seeNumbL=seeNumbL;
        [lastViewBG addSubview:seeNumbL];
        
        //评论数
        UIImageView  *commentImage=[[UIImageView alloc]initWithFrame:CGRectMake(seeNumbL.frame.size.width+seeNumbL.frame.origin.x, 0, imgView.frame.size.height/5, imgView.frame.size.height/5)];
        
        commentImage.image=[UIImage imageNamed:@"study_map_people"];
        
        self.commentImage=commentImage;
        [lastViewBG addSubview:commentImage];
        
        UILabel *commentNumbL=[[UILabel alloc]initWithFrame:CGRectMake(commentImage.frame.size.width+commentImage.frame.origin.x, 0, commentImage.frame.size.width, imgView.frame.size.height/5)];
        
        commentNumbL.font=[UIFont systemFontOfSize:9];
        commentNumbL.text=@"123";
        commentNumbL.textColor=titlecolor;
        self.commentNumbL=commentNumbL;
        [lastViewBG addSubview:commentNumbL];
        
        
        //时长
        UIImageView  *timeImage=[[UIImageView alloc]initWithFrame:CGRectMake(commentNumbL.frame.size.width+commentNumbL.frame.origin.x, 0, imgView.frame.size.height/5, imgView.frame.size.height/5)];
        
        timeImage.image=[UIImage imageNamed:@"study_map_words"];
        self.timeImage=timeImage;
        [lastViewBG addSubview:timeImage];
        
        UILabel *timeNumbL=[[UILabel alloc]initWithFrame:CGRectMake(timeImage.frame.size.width+timeImage.frame.origin.x, 0, commentImage.frame.size.width*4, imgView.frame.size.height/5)];
        timeNumbL.textColor=titlecolor;
        timeNumbL.font=[UIFont systemFontOfSize:9];
        timeNumbL.text=@"00:30:45";
        self.timeNumbL=timeNumbL;
        [lastViewBG addSubview:timeNumbL];
        
        
        
        
        self.linelable=[[UILabel alloc]init];
        [self addSubview:self.linelable];
        self.linelable.backgroundColor=RGBCOLOR(225, 225, 225);
    }
    return self;
}

-(void)setModel:(CourseDetailModel *)model{

    if (!model.btnstatus) {
        model.btnstatus=@"";
    }
    if (!model.title) {
        model.title=@"";
    }
    if (!model.teacher) {
        model.teacher=@"";
    }
    if (!model.teacherlv) {
        model.teacherlv=@"";
    }
    if (!model.showDuration) {
        model.showDuration=@"";
    }

    NSString * IMageUrl = model.imgurl?model.imgurl:model.picurl;
    NSString * learnNumber = model.learnNum?model.learnNum:model.learnnum;
    NSString * disCuessNumber = model.discussNum?model.discussNum:model.discussnum;
    if (M_ISSTRNULL(model.learnNum)) {
      learnNumber = model.learnnum?model.learnnum:model.learnNum;
        
    }
    
    if (M_ISSTRNULL(model.discussNum)) {
        disCuessNumber = model.discussnum?model.discussnum:model.discussNum;
        
    }
    [self.imgView sd_setImageWithURL:[NSURL URLWithString:IMageUrl] placeholderImage:[UIImage imageNamed:@"common_no_image"]];
    self.titel.text=model.title;
    self.teacher.text=[NSString stringWithFormat:@"讲师：%@",model.teacher];
    if ([model.teacherlv isEqualToString:@"0"]) {
        model.teacherlv=@"1";
    }
    
    self.detail.text=[NSString stringWithFormat:@"LV%@",model.teacherlv];
    self.seeNumbL.text= model.showDuration;    //时长
    self.commentNumbL.text=learnNumber;//discussnum   //人数
    self.timeNumbL.text=disCuessNumber;  //评论数
    self.typeL.hidden = self.hiddenCourse;

    
    self.studyStatusL.text=[ColorTypeTools getStudyStatusWith:model.btnstatus];
    if([self.studyStatusL.text isEqualToString:@"过期"]){
        self.studyStatusL.hidden=YES;
    }
    
    
    self.studyStatusL.hidden = !self.showState;
}

-(void)layoutSubviews{
    
    self.imgView.frame=CGRectMake(10, 10, self.width/3,self.width/5);
    self.typeL.frame = CGRectMake(self.width/3-38, 40, 45, 20);

    self.studyStatusL.frame=CGRectMake(0, 0, self.width/8,15);
    self.titel.frame=CGRectMake(CGRectGetMaxX(self.imgView.frame)+10, 10, self.width-self.imgView.width-20, 25);
    
    
    
    CGSize teachersize = [self sizeWithFont:[UIFont systemFontOfSize:13] maxSize:CGSizeMake(100, 10000) withStr: self.teacher.text];
    self.teacher.frame=CGRectMake(CGRectGetMaxX(self.imgView.frame)+10, CGRectGetMaxY(self.titel.frame), teachersize.width, (self.height-20)/3);
    
    
    //LV1
    CGSize size = [self sizeWithFont:[UIFont systemFontOfSize:12] maxSize:CGSizeMake(100, 10000) withStr: self.detail.text];
    self.detail.frame=CGRectMake(CGRectGetMaxX(self.teacher.frame)+10, CGRectGetMaxY(self.titel.frame)+2,size.width+10, size.height);
    self.detail.layer.cornerRadius=size.height/2;
    self.detail.textAlignment=NSTextAlignmentCenter;
    self.detail.centerY=self.teacher.centerY;
    self.lastViewBG.frame=CGRectMake(CGRectGetMaxX(self.imgView.frame)+10, self.detail.frame.size.height+self.detail.frame.origin.y+7, self.frame.size.width-self.imgView.frame.size.width-space,self. self.imgView.frame.size.height/5);
    
    
    //时长
    CGFloat  offset = 4.5;
    self.seeImage.frame=CGRectMake(0, offset, 11,11);
    self.seeNumbL.frame=CGRectMake(CGRectGetMaxX(self.seeImage.frame)+5, offset, self.lastViewBG.width/3-self.imgView.height/5, self.imgView.frame.size.height/5);
    //人数
    self.commentImage.frame=CGRectMake(CGRectGetMaxX(self.seeNumbL.frame)+5, offset+1, 13,10);
    self.commentNumbL.frame=CGRectMake(CGRectGetMaxX(self.commentImage.frame)+5, offset+1, self.lastViewBG.width/3-self.imgView.height/5, self.imgView.height/5);
    
    //评论数
    self.timeImage.frame = CGRectMake(CGRectGetMaxX(self.commentNumbL.frame)-15, offset+2,13, 10);
    self.timeNumbL.frame = CGRectMake(CGRectGetMaxX(self.timeImage.frame)+5, offset+2, self.lastViewBG.width/3-self.imgView.height/5, self.imgView.frame.size.height/5);
    
    self.commentNumbL.centerY = self.commentImage.centerY = self.seeImage.centerY = self.seeNumbL.centerY = self.timeImage.centerY = self.timeNumbL.centerY;
    
    self.linelable.frame=CGRectMake(10, self.height-1, SCREEN_WIDTH, 1);
    
    
}
-(CGSize)sizeWithFont:(UIFont *)font maxSize:(CGSize)maxSize withStr:(NSString *)str
{
    NSDictionary *attrs = @{NSFontAttributeName : font};
    return [str boundingRectWithSize:maxSize options:NSStringDrawingUsesLineFragmentOrigin attributes:attrs context:nil].size;
}
@end
