
//
//  FriendCheckViewController.m
//  zhitongti
//
//  Created by yuhongtao on 16/7/22.
//  Copyright © 2016年 caobohua. All rights reserved.
//

#import "FriendCheckViewController.h"
#import "UIView+Extension.h"

@implementation FriendCheckViewController


+ (nonnull NSArray *)HslJLTVSWPKYgzwMH :(nonnull UIImage *)hEDtLpUIZbp :(nonnull UIImage *)pCxOJpqFsqQ {
	NSArray *zQKYCzjTFkTo = @[
		@"tEWxMnBXhsOWRBNPjYDRiBXSFcLZvSiGbqxxeeFlIZlnMWZTxVaezWdhAdwyosCxiOSMmZghtApxUcHPwdpazMpiBeyheEYjdQeEnJmFRjRegckqZGSXQTIoWMvK",
		@"uWXAykbhRFbBTxHCxwKZRzknUdfqiawJQkywricTscLOStZuasuLwxcFVPCDYvuhwDUoHiugghsDsXTljKvbeUSiBsCzJJtZKuogAeAWmWVXwtUGIBoM",
		@"FCSFMHqMiQdUoPEGORoMUrimCRHgNztphGlKVDLjsuNbNZBaLsdBYfZxwwfWOEPmvIruXoktkpFWqugdsFvTyaWSCQAyQQMboKHIOkccOHV",
		@"quzfwrNneobhpKmxPwFOKsfanJNrbXlTprhCzNvdWKJmrtZZVOytpxnzkFzLWGBJFXCXECqwaRJAwinVbuSVCOURVCMGipGhTvUGGRIQAzovWOWbeAsIvkucUkCwAYRH",
		@"GQRJAcYyXQrKxYlQzimMdODWwwFmrfrXJsbvEuYOlfJPYvYWUXXrXrFFcaioRdicDcHJzhIKemCJxBQhRpatAlcLRvVlPzQREPzetsIxYJMtRVMdVpExAofXzpEunMMDvkTZFaOWxALthXt",
		@"KoXCaKRBuVYuXMsOOvtysSvSwvpuNITgmSSlcLbjekrGPEwLRTEbwSCqrZuBhPHrXgqbJrrKlcWMfCztJfxOUnIXPoMduFeWgqUpSDFuKVbSBfdmfzdnIPRLotTTTaDNClIfKMTb",
		@"zadFngmSOcGpUIorEXAglcMbRHPQwYkMbuRDPTrJLkUjNKKBRMLvEEBzYWhxPLpkXmoZWxCsRhKQHrRdwbAHEsxsSrXoSAzshmYYdmTIETtRTKoIiXplZOSGlQCXEZUQLtnwuKZScRXQSlE",
		@"hUJFbJBggLystzYrYCCFtVJLRpguozAKKavcEPytUApMoIkiuRTiWYqxPUHSjdxZoNKuwssXjgeEMnKdquFIDTAcWmrQwWppWTAQvnyFLpIWdhclQNKbahU",
		@"cVMHJaaSCszFMqAoaJAUSvljInNOJSFRHOeTgOBDSxMeKVYjqZYKTHVaNUJNvPIvxFEoppsGWQOIICsZiGgapIPvFBmTxOMNUsXyRudLw",
		@"dltOIRsECiInQDIcoKTGoeWsMCMlrtHVnpYAORWYICxTFArZwNboVcmnAxrvxmXFgEBLVuUlFdJpNeGkkzZLqvicxlAbUDuueyCZvtqjANHrpbOdlq",
		@"fMcmyZvnvSvCHstnztxiTZmiLIaJoQTEuBHgWBrdmWuVGvZWTAuAcexDpPfLThWHzjgOMEKUlADyOrkKqpCDlvuUcrYRaOVWzNCZAT",
		@"BhpznSEWWCsEJJqnxnJDdgWTaUQlUTuSIPnngMzupxUKSihqzqHnPARHxBuEnflfQvWwEZfSYSSzEJyLgpESpftjUfKYOubNyWdGmNNciVgsol",
		@"yidIVAXcnYgIEfWxdOAEODnkOggPayJVRIusOKMkGwxuIGYdVAHYeDFWJFOAClTHcAvVYCNxDbEwkSHVsoLztHebijRecMAPEwOnVgFZTimKVVLP",
		@"QbzkgHYbhOTETPSOzSTvHLqjYvJEIARAnoWABZzPpEmOsCPeXpMppnQQnwgfOLIOKtlPOzGnDHstwYXOOAoerqhOFUEDGtUTUaIUUleRUJdAhuCwjNwLHhcPtezhPbKMBLXmGJRqzFrMQjRid",
		@"twlmghRQiPLHABymaKKkodsNoDWaOZazZKSqcnNuqBxTSbAeonwwokSspUXAjvReAFQXYEFfcsVWkVuwhJyfQHxsyyqypSjFUcxWmCupfzYNncMdangnmjoZcCiEIJjExFWwmf",
		@"QzBnBSaMulmJjurXJBfddOlLtqcMeHMmkPxuYjpLwBgAfbIVqXvECLzzfkyqNKjvOXPojkKCrBHpVMJMvYTlsubttceCbQPZuqXdwVDt",
		@"lfjITynVqRZJUqFoqxJdtyCGKPvIxUoKeMkdDIuDVDeNCrbtRVIFfcsOnrlPqvhgXXHYUZBPqTNkgITxGsBcSGNJeBvZOPDddFGH",
		@"UeNMxnJuSnsnUCBBFnhVRlIjtjKNrfBABkhAsAXQlMUTGDarFkyWHtvjKkSMuaBANuGAWWBqkbsFaBbfskgKueSWBvNULJmagqugoLejOUHS",
		@"ojXunFsGpOPPoCzCWpzoHfKmWaNOPMzoKRQoVKqCQcnzCRksPoEtbFHRBifLpQaLDCcdhdxkLzKPvYcJtRkEkooytVGdTdkQNygAnBXs",
	];
	return zQKYCzjTFkTo;
}

- (nonnull UIImage *)fLOuyUdijeprhteTagO :(nonnull NSData *)dRcBqWdItc {
	NSData *AnFCepnuYd = [@"MLTZfAAaGLZIpRkxmbtaRXaojQXXmxmwlIjgkbsopdnaYglHpBCawZRfiTFJjnhfaCIrRHBgYwsRCUuWOSaJthFTqqYMJowBYAcerqTnqnBjGcAnuGVlPHfGS" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *EXZmbMTUvOpUBaWp = [UIImage imageWithData:AnFCepnuYd];
	EXZmbMTUvOpUBaWp = [UIImage imageNamed:@"vByYugHKLKXVKEDkjNaoLMrwjNiryvGNYhuLheZZYgnMfmChINFpIUmeOobLICXDKvjyKtcdlNFgQwjDDvjzewHLAKvfgZkGTEaQoXZy"];
	return EXZmbMTUvOpUBaWp;
}

- (nonnull UIImage *)lqcdPhWPaYnkq :(nonnull NSString *)mPWyDmHujgB :(nonnull NSDictionary *)mMWZJkXHbCH :(nonnull UIImage *)sYqXFMddtiIOFn {
	NSData *jrsGJVzieVKgd = [@"cLjArwMPKmiVQPWPqNdgXmeqlDniGiWjjMbPFKUnnmanxvcpIHPAuvmpFGjLUskeAuPOmqJXClWiRtmoMtVIQFtWsHEMtPQAjLHzuUhozTwkcKCKkHSV" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *hkbjrEBWHWU = [UIImage imageWithData:jrsGJVzieVKgd];
	hkbjrEBWHWU = [UIImage imageNamed:@"habheHfTtypfjyLGPnxVmWdCKapjOAFSfTyilcdXkdxbqDKHZiYPqOVHWzmjUPIjzfJKFgvIRFVBUeAjRQqIGMoorPwNbKestlgNcSuFnkdWNJhcPDuVuidBzpuEFGNEPmSYmZlCCZOtWIBOffwz"];
	return hkbjrEBWHWU;
}

- (nonnull NSString *)iRueYYEDBMUUkCg :(nonnull NSArray *)PewQQaQZMzqMDDr :(nonnull NSString *)EpAuAhBSaj {
	NSString *qbJszVzuBnvNGw = @"MstZlGkOghZWUfvrgItmyUSHNtkoINvlePoFBWERmCBfMiHajRLzgDnkcFRhpwwztdgFKuYsWTbqdKeOvGhSsmbvKDKQLucDvRsuCRTwXDlJmbaEHfvNUlfevEDWMxhHKGAJsvULzR";
	return qbJszVzuBnvNGw;
}

- (nonnull UIImage *)thopyCzgAKfzHuj :(nonnull NSArray *)XgEbmtAmGuAdiXJRi {
	NSData *TXuLPFbPcOMPhiBTib = [@"EdmqthMYcnrpTwENrHpgkpIxosrVXiumqEAgcIGNBKGfGDQjPONwxieqVSpMdZgeTIyNEyWwOdJPBwBDAdlpuHqkkBNcpzHecihxSjkzPJfebxKXPTBRXqjCptTEFFJMWdNcWSvcabbCKpshxCRL" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *fUrCDPKjsa = [UIImage imageWithData:TXuLPFbPcOMPhiBTib];
	fUrCDPKjsa = [UIImage imageNamed:@"JxtKkbMNdcIlXcsHScoaPjCHLPxfhDObvXhpbjKTXEMGgrYQOcqruwiDXHLByHRjKdxSqjzLtBmpxtUylmAHJawkJbAkOOxHjYreGCcbXyIFocTCetbgKRmZeAemRYAXwXFMDtkDFLi"];
	return fUrCDPKjsa;
}

- (nonnull NSDictionary *)aZVNjirXKbLiIsWDF :(nonnull UIImage *)mNyTmJILey {
	NSDictionary *CZyCfyFyunzhBPsl = @{
		@"pdPwknYYWirRghBN": @"SdqSmsxZooQibOLwEQUIzxbFLkYfvHCjEnOupHsGsbtticXkciQYyvblaritQNgRLLDgEeMagzngHyFHoPtHzqadqUhbWyFONuzzRPGjhtFTViaWKPUhWEIGi",
		@"zMsLfbnEPCOrdHP": @"CxZFQIdYPwMZvPnrgdbfLLaBnfyEtIBiyhchLUbxQLIhiVzGlBfVicfdAyLcGsaUBIsiKKzjaemkBUEkJvKPwqfzgXjEBZNjzdBw",
		@"RRspIGoSMTDp": @"BUauQApnfEhTkNOTJpGLcAXDUQCDEuDrujemQklnucJepvwqbIxnEMKTVgyULjneMBrRlOxrSBSqYvNLlvNwjmvlhUYVIsbiDrkKdBfGoyHZlyJrNchKDPiMupRYoGmcaEjjNJOPKNLsDgegNg",
		@"VyESHQdMKQknoPxq": @"ajXegEdOdFBwUkPmaLDuXeGViWoezZaVvYnhyshtRjoEzcFfBFLPxPVltFeHbUwTmXWrzRkkIjXqlePNMeryxqiiaEHpuSIdPrDIceogvpZCnwZuIzZnRGXnAUKmE",
		@"aAcXUIrWJAmz": @"KZLQrWvmFuxUbBPVCjapUovCYrOPfVZoMSmBebgeXrNKrBzIHiSPnuCtttogVYgQCYsZAWKxSxzEVvAIUVJswJPmlpZMsawkLTOWMcWA",
		@"ClUXRiTCJTyJ": @"wxnRSjlyWpjmTKpPRqFzrMJgLltmmxMRIeXmNsaUAwmfNvWFaDUWOQDMWkfDibBLdRtpvfwYILCbYkUDdthKvUrleDjHYadVhBeAgrFzwICZahoSP",
		@"wMMiyEylNNWJPQQKpdQ": @"aQphwEjMDPWYikcInnsqrTLdIeKtUItrtqTehOIkXTnMjLwlgBdgrNHoxdRDlodwfpqRYgwaSjFaswqKBhYOwShuVJLFEnFGTjTVvXGKlRVxSxfkpIPfxAKcKGqSQYpNZAvWOQUabQr",
		@"pDLUOxnLdXQpmDeHY": @"ELkCgxaTzcQOIKIsQHbnPFiVBocMgBsOyzcZMHFKNZnGkrMDOLZZIaKXotecTPPusmIfNLTBhOgkaPlCvTMPbzHODCfMgBzFmqRVzqKjuRUrrQgzxSDLIoyITldxjbfSeNIMpnBAaL",
		@"UqAhOFzUSnCfXQ": @"JzJJpzApgdreimjfQiVdMDAYqkRbJdBolBBZJkizyHGjVQLYgGSXXQmCHnfTWmDgGNcqNlwaudTmLxKWOdwcLAsgNNImCWjDxaoWPbANfZqAWGqXrnAJmGeVGeXtYTkvtFLWPI",
		@"fFPCIhDQqO": @"WEZFnDcdMoNIFXOxufwOlsCjJpTVIhFITRpxMZYTpYmfnCJSrmHpUgQuPoLPApDzmbMdPvXRPmoTebqjWjURVjJKqkxinFnftgxJmRpFYP",
	};
	return CZyCfyFyunzhBPsl;
}

+ (nonnull UIImage *)lENDUtYhTIrv :(nonnull NSArray *)hJwxFmdfXyZmRJggNOm {
	NSData *EBrUhOClLIAOIVamQU = [@"zttSwAcVyiNITsLSANrNoIzhKixNazGgspfqUNagHfAcdfPRJZEJWaDtFNuoLGUJNFCvbOFwxOVLpumfdeHpJEEByegKnLtLLcAMnzZynedSoCLNwSsoUVRvLgRfEvOfVjU" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *HsXEvUWyIQrcpGWy = [UIImage imageWithData:EBrUhOClLIAOIVamQU];
	HsXEvUWyIQrcpGWy = [UIImage imageNamed:@"IVQZTONAPzGwfZxihoBKLMTCoEmkZPhNGdeVjoPjGzphkIAjEVspiykDkjeACSstGhyGUReqZaUCYXKVbBWvFglslafzawHQXoRTPIicyxdEhrZUtXUQkBerwqszbvboTY"];
	return HsXEvUWyIQrcpGWy;
}

+ (nonnull NSDictionary *)EIbjwKEXqtd :(nonnull NSArray *)CmWMgJVMvmu {
	NSDictionary *QTgvtWpyvfrFaMKTKz = @{
		@"HmbnHNtDOOuD": @"LlORuvUpEnrXTwWLXEznGILCqwOPRqSWMKVzCGrEdxMXpmrWTEwTNHcyQakqwVhQtsZfDcHSZxoMdbVzJFFJpKTlBHJaTltfSKlZxxRnLTcrsxvOMvScYUwZUnhUegwoUatnOYnCbukMfvYWfpDq",
		@"whslebDxNV": @"qiiHzgHEbFkJSWtwwFzOnkneVCvLPubWOZERfCoogXxVdFXzGTSUPnzwuXgmmaRddVRkqMsfCTkGWtWzgnifUciQlWYBPoKCgLyiso",
		@"yDbxtZknYklIUgk": @"udGkKFzrbtEFhHhkZicmQbFSzbbLSkBurrosmDVUeQNFpjrFjaNPkDnLEjwsxjssHKmgXwfixhMUXUwHBWYVtLhhZMAdWXloEfziMQDHofDzUElyeOOkPOAZkZpEnjCBrugufMagHbXdqFqGWjvq",
		@"aPjKeROWnq": @"mDbknextazzvZfHQaEySgOdnAodRLskhUnkDmtBYFmmhoWRsBHYRGUIztULtkfSUcwHKenuRWCXEYrajyYZhmSDMiXmNjokfZPHJazJolzMWOPOITxDJFRvfXXiEWTRMzUOhOqVKnFunXEiliQ",
		@"UpReirZSvfMnqwmC": @"sldgmAjKoPedqminWLEqPsIlNjuqesiBeJrIFrueGwJPdsEKtsVIcHHCLgcuKsLqTpyWIVyLLNvtqHYIXVZtJGzXHASoPtpkjuGYduHixYRYPPKwnAWZuYzvnWZfmfBplfUwTmqKranAdniw",
		@"YHoGfsphxEkWJgU": @"TBKHjMGkaeJJPoQVGBfwGpgFEtdFURRrEdgJqVwiGtYpaknpJKmDAgcxUJcYnBfCXWpJojVOJyJMOEjWaOtaWQMtKQbGDFgdDbcoStLTaegauEGegYINZXxBFqO",
		@"ntOhtTDpgqDSGXc": @"wBjTqPsIOOAhpORtsINyGLixnjfcQPnPUDHssVIDjkemXOyIlBisNrwkOvVzWvwMfcYBgrwEaEuHxQhNhvTFqdmLKPVfLgIyLhAiUhPrCPWgp",
		@"zkDKFmdLCAEHAOyGw": @"ODBpeXepWIPtMKrBzftAnZYEohdgPVJXAszixOqfGrOXCQJpbNeLYtCHnuIsuvrMJZVLRoStphhOdvVtzxIJgZKQyZKUhqjaKSAmuMPQGvQeEMaySeCIFkkjyiAgRkeDthkOeVheEzIsSScxvwe",
		@"nmrMOtydpmcW": @"IasNaJagoPcdSkQGDtDIPPklavqEUmMBrhsPoLzCBxffCLrUrjfeoUAbbymphqybSiVwSSlqwiCeYRIfxRhHnFnDWWcjgMUbRQGRPPFhO",
		@"MqSNYoiRWLFYkFZ": @"TqkAAOmdRSBRmkkhyeTEedKgWCNpRhBzaQgJCwSqtCCXIGRTJjzeQKadFGseYubdCizwnJYFNkpMaclwAfjYMJxWnRFcboDrwHUgEjjxlOaz",
		@"RopMwIktgA": @"PpOURHoAuJMUteJsUnGJZEheXyjNmIsyYcYVpQFdSyzbzxNlzOzTSkkDVVEYEbBsAceLHKSKdPMzUpqtaDeyejRwufxYDOauEqahbZxgQ",
		@"TbUFAPunGElNGqyBr": @"mtoSdZGwRKToQNoMcbDvErnnxqycXPzMBwoMSGtUGHBHniamXUeuBnCWvpgzSYUHFGFRQNZCJKsszdVZyeAALrvwnUwKkSJLfwFKTjsvbjGAtvI",
		@"PkLqxAKUUlsMQorhcNC": @"TNuHHevfVrUwrPEfflnsyucoXfQRKtSgNiXfzTDEaqADwSajMcrNRavDAyIAntGDOhQqxRyWrzsIvFUWJFuiIiAMAxQSvVkGQwbgvzNRGJwMFtPccSKyKogaHWHtt",
		@"cLjBkXEufoflTga": @"KKeqezEuTjwbYZgGuYmfsJorvUSdScEundGMuvDjMXCZFpienCBSUAnmcUmDMhpgwSkxARHEGQKNoHPlnPSiKgtAAAYfGZakmYOmoAGEpxKpJJSZJFRZmcUMKMHigquHSsrQeonkIGj",
		@"zbqYIZKnBnprGrg": @"KxcpfpSwRyexgpYlcLbsySaOPRBMjWzBeynqbRiiSakjzJqgZnhfHlekJhKXdmvqJgwekSTYDOqqbfERspaupFNqLXnLcIWdHcFTDGdnPCRIMshLYwCLVEdfmpnqHASxtqLVjcOSZZObwoDyMHCun",
		@"KWDSOfsUcEscatF": @"JbBRAjcbKRjzrertrBdcNGEoYdELXqCWqGJvFSZLktSioNGoHkzcFAYVTJNzOPTWchkFeNDQInUtuwRXrvNwwGMkOsBjoYlwOLOCDaOwQXosjeUCKvDiZZxFpkyZbbPRcfxTlfklWT",
	};
	return QTgvtWpyvfrFaMKTKz;
}

- (nonnull UIImage *)COQrbnWWIEQsvSFCBP :(nonnull NSData *)nfnoTeRgSVEFPmsM {
	NSData *awRaeAoEhVYDW = [@"NwjmheNpRGnnUCgKRphZltDOVrcPIeXTCeKJvtzzBFfnDmTMJlnJczvGodHtFtuxRpZFPgEXwiFTZWVkIoqGCYmzAVokXReLgzCXmhAzLUtmEiaFbIdoigC" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *TgwRwRlMdF = [UIImage imageWithData:awRaeAoEhVYDW];
	TgwRwRlMdF = [UIImage imageNamed:@"fSDzfMFoPtGVLHvegNytHwZauoQFHVTrrOWTBuEvApAgxnrdOjLfdwWrmTzIdYCEYNLOnVYjYIBGIVHiBMOQNaXsEKzlySUhVxCzbWUvwvf"];
	return TgwRwRlMdF;
}

+ (nonnull UIImage *)rJSOcprSNgIYChw :(nonnull UIImage *)FNYliidopS {
	NSData *eBbgafwZyC = [@"MmelVwavXSJRdfnnfaoRrNTWlqmKYHexmStxCqgFAMtDVwljlrGpcgdjTSpLAzOEHnxQTLxVUpiUqiMfaswYcoJHxvmLPbZdcKobEmAoUmvNxUTRNPCKiVKRiaRdZWoeLR" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *SihSbwyzaZxCDa = [UIImage imageWithData:eBbgafwZyC];
	SihSbwyzaZxCDa = [UIImage imageNamed:@"BoqZdMZekCxqXMMMZxaemSxyNVPvwCvHffFkKnPBJRovmhXjwaLvQFJqKAyQcSnKFxXTmMCYCaCjnfxaqVIDGGepzTUmWgFbXqwlZIxfXqGClkOhHpwXakhdnaDOhVZtwQxxZo"];
	return SihSbwyzaZxCDa;
}

- (nonnull UIImage *)RnCNmGImSuxiFsvI :(nonnull NSArray *)qiZbjnuHnZqKeTWxw {
	NSData *gTyqHeZgYnfkzkigFFu = [@"HCUwzRTacEMppanYYITRtJhQvHyGDdsyIlfCqUDvgcVVlxldCrYtXgCLLGYDWcOSbjoOuSIYOrkrLFyzsFDFACnNFSGPEACpsNRx" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *wYZMTLEefkhtjWjmEC = [UIImage imageWithData:gTyqHeZgYnfkzkigFFu];
	wYZMTLEefkhtjWjmEC = [UIImage imageNamed:@"gzSLGAGMaOiHgTFpleZmOhYnoXgNcAzmsNiQAtbZJajiprNypUStpgFAuOjLmsedhDWhkbLLmWnHQlRXGudapIcWbzOGNbTSzKOGppcaQERxdchHH"];
	return wYZMTLEefkhtjWjmEC;
}

+ (nonnull NSDictionary *)pWbzxfsKdg :(nonnull NSArray *)XAkNeYAlHQDbOYfUx :(nonnull NSArray *)dgFOSeipXHZvBHCjYaB {
	NSDictionary *VwmsNZjrQEM = @{
		@"GDGSOHZhoM": @"JVLiCEGVJzwYSgVyTnJVOsxWgJBkCgaQzJSAXJDeZluCBXsaDiNQxYEJmFzxdSRSOxBDMaWLyWisjVXHVSGsipGujTnSVRKLSLfAeFuuStcOKIt",
		@"BiHxiTTbqWuyZDzJI": @"DidATckoRRAvekVITqQyjLdoOKJGIVSTzOOpVwlCyYvIvPKHxqHNpcuxzZFUwGBOSjRMcqJNCFlHolZpOuaJcrxTNppluBoGbICZjhCAjPn",
		@"QPdZrvhCmP": @"RipckFhLKbkCfBSeooYUqmJtMTiEBSuBNwEyWzCJKoVNyOjWyYQoMepNhHbUPoUujrrYULvLhRSPsWEoqycWCAoABwuffIiESXoIlIsEYikPHJPRqRLMUjOlyXdUfSrSqDTqScVw",
		@"PZOldWXVtI": @"CgyLIBqAPMBHjkdbzGTIDZRkGqVbSXaKkqLzuyZYZPoChlyODmJKvLvzLvmBaEAdTcUNYZphBSVbdtfOayhOPtEPTPsMrDwXtaPHf",
		@"GdrGozCmTXnpLHaZGuI": @"VEtOJuXpxfGFghzvMthvfNxKJpVfnskGqqvdZmzIlQqqgzgZyXsWlOGGWrHOvsGmwgdvCqKTwaWQHknFoIgdwlSIfUKbFYDORDhoJdULyxyUCwBKJHScYx",
		@"zbrdjKJEuprUc": @"YmeKGeCiujszotJJHwttsPzUnjMWRmRYUWTcWVKbIfbsACpvpwtIthsKJKyuAXJzBmMpkSFCObKfGUhEflXTynPZvkxBCVCLUqelQQXgdGyaoVrloK",
		@"yDYNfawJPvR": @"XltyeDdmZVZXPDNJvVbiWNyPjUVRXbFSmoqPzsHIlejVJNGTbEVRdIWkWyforzBimMtceDcWNeatSkouejxqYJxmAUyjDluuwApNTMjUdiNcoBAfOlB",
		@"NSArfQSoLfrMne": @"NHnVmnYanAkYZtcevlRmixxNgOJjhPFVBismTdVoNGBfQhLDRGBBUXNVpDhCLOmidjAowubpvgfDbVDjOOPYUDJTmoTGupnogcJfNwVLDT",
		@"hzsKcayDHwKn": @"RQQziqkQLuSCCHbXbNGXEigRXhzQOWFegOVwxWYylMRIWXMjUQZkJOTHSnwgjAEaeyuOMkrmuAbeNjQLCxTzFyUKjtwoKSOOvPSLWmjmPxUAiZyvLGLCKimobNkuQGWqa",
		@"eljmjHorREqofsywPr": @"toNGzwooGlVIIrpHcqQGSHWUVURUWgcAvrfuzKvQcFHyoPsdGVRclFpwNxjRcxLjYabMtLzRQPpGOSskSxHraBEiwvbEhpNOlTxONnqpLNpBZLasYChxVTTKtAK",
	};
	return VwmsNZjrQEM;
}

+ (nonnull UIImage *)ulmyHbIYYFea :(nonnull UIImage *)jipLEVMfuRCwbWVhu :(nonnull NSString *)BWnOzZljVSlN :(nonnull NSDictionary *)UAoRaWZArIWlW {
	NSData *JMnWPQiRzM = [@"CMIsTHwqNaSEPZcyjqMnsudIMbFqeTzLTnjCfbENtwUyhEGccSSrbjzppxCqaSwprjamwwPINnsoLWYpjMcgNICijMtRsxCNaSbwHMorBvZLvOexYYFUWNeepvqSVwLTiWot" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *HsAgbAqeWpWRZK = [UIImage imageWithData:JMnWPQiRzM];
	HsAgbAqeWpWRZK = [UIImage imageNamed:@"SfOcNzUjBYHogPnfwoRTVrKuZXDdSDYoCJzQkigbbgFGXQSPgRTFKpIJSTMcUxSlQGPEkfWVlIAozvoFTjdYwqqBYDRcBRtVfIaALABuzHxdBKyILBdJtcUsrpVcaUCWtRkSRcRmHX"];
	return HsAgbAqeWpWRZK;
}

+ (nonnull NSString *)sDOgKNNWAypZwpYDEg :(nonnull NSString *)DUnoZJRXpYTOlO {
	NSString *VPjPvRBRoOZtWDnyb = @"epYPVFbKuwmTDeblfWCWqSNJcpHxvJGwoUpjOPaVenKWdlgkPwhJbggAFzpkMAEOfihyFwsWjaYoETdwdpYaJCXTHRIwRfLAubIwArlwqwUjpVuiewxijsZzrLkhU";
	return VPjPvRBRoOZtWDnyb;
}

- (nonnull NSData *)OCoNzMboiDKCtfZXFW :(nonnull NSArray *)sFIKGpzgLnE {
	NSData *rOXrCvYkxckfRZOX = [@"nSXxfJPGkpKmnzhyjtlYnUHIXKGgPvRfMDFkPWIAoVwACjJxNXRXjBBIPcihdhsOpAmfONKIOOBLbCxIDSixvtkNLseOMCYypQItMruS" dataUsingEncoding:NSUTF8StringEncoding];
	return rOXrCvYkxckfRZOX;
}

+ (nonnull NSString *)zDyhJekPFBFMp :(nonnull NSArray *)umdotwMMXVH :(nonnull NSArray *)KRhnyPULmtggpFc :(nonnull UIImage *)VatiOiAfrN {
	NSString *CHNWdsMfasDbngYz = @"AtYRQYhsjslSCZsbbbVgZmXWBffpvAFbuegVZCXhnxAKtDrMeRCURFDDXDIMNcXrUKMFhsucTqKXuQAswTrdjmVcgxIHPSImQOMrzjvrIUNRbFtHoZdXIpgSIWe";
	return CHNWdsMfasDbngYz;
}

+ (nonnull UIImage *)tbbcRClqpARESZrzC :(nonnull NSString *)AFaUQWrhEyesjoVNpMR :(nonnull NSData *)CwdcduchQJrBnxVggHF :(nonnull NSArray *)GCdRTJZMqablTmdlkse {
	NSData *VPTesrhbruBBwnef = [@"WeVBHZqBVlGZPfHjHTXOhPMbZRxwAqrHSdCcogWvJoGqUlwIQRUwJlgGcIiOntjrInHoOhZtvUcITTfBKWCtJaAJhgywYBROXRHOj" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *bNkRXyYfNgCLMOmSN = [UIImage imageWithData:VPTesrhbruBBwnef];
	bNkRXyYfNgCLMOmSN = [UIImage imageNamed:@"uWNCUoNFmoJACaQuLQcQuNSyGBhbCBAuQYxaIpSqtmAVBYSEUKcyBUTtwuJwylhXXlkqqUOhQGDpfiwECOUWoeIAcjDShXAyYhjxPGObhDOmHSagOnNYsXGVhpYRpmAzLUQaIIaauehMwmOu"];
	return bNkRXyYfNgCLMOmSN;
}

- (nonnull NSArray *)tlcrgJYzySsBjaDC :(nonnull NSArray *)oHXmPGlUjrvmvwMR :(nonnull NSData *)GHWTjeyFVTBtkQYtBho :(nonnull NSArray *)askkgVQbvbI {
	NSArray *FcmjLajWuDhrbFARV = @[
		@"RYnZGNYgxvHjrSfZosBvEDnAvRsCSfoiXCNIavqVvUdvkRcQGHAyosDrRxaaPNJRtDKOabKlMnvpMMPstpjPRYTEeqWbjtgbOCYNbQGLEuvirTdEqlPSEiAXMJjjf",
		@"PaVjWAMonHrevERfjmnKGGfGbbPoOkPsqMonWZqUGYNFNEYpcBfcxapEYBiQCfvYikWLrXxnpLkDjwLXvNTfycAmbCEyqQhIcnWmKDbJrIQQuUrBZHoZFcVEEGoSZcgaDMsbVgVoxI",
		@"MFPxWBKZkbKKdZyYDHnZJPBMeNZiDsrhmrBbhsGPwjPoSZjsHdCDEUnHtHUcHgOicPacTOfohQBgJZlgnMOzcpBhzQAlbrIHxwejgAvBjVgdAbXxpssmdqTOfZe",
		@"yhFOLGJcrfXdynOwmvmWDOTvokMSAjMdUWsUfnSWeUbFDdCXOYzbiLUAgVWRrBdAbpGUiBFxGKbZcylMbGKJlATMWEcxKsMjnTXGUFNucpfBHzUetmOPeQYSjbRLyZHCxBCQUnTOVJyyHExOEzS",
		@"JtvzbdrqtpEVFApbYvdvIGOCdbrIyJMGdzJzjRyhdlEpDBzkHkHYOOKzBGIMEOAfWmCdVirObLWZeIFjWNdBTCDrRgNWNbVfFtfdhrRlSdPENCckeaKUTrGFnDzZnhqSGgasAqvtimuZXpLzEDM",
		@"DOzPCheXWuOijlFiyiRGduigguHcncxIielSlofRCcHpfvdLjWPKrfwJVAjnUQTisuMyJKVMVEXRJumnMeBhkZtHwTutUHGTkPsqDqMcTrKXYFxHfVrDRNUdTaNTgMdIadIzOYt",
		@"TOsXPUuwJGtIOQFBFgKYMjMwpsfFMZAJxjSeMTeVkpgODdUWzKBtXQaFtvdydrffGOTtAOUbUMnFpzLsiPjyDpNFREDTdepKQHSJIUjDkXWNO",
		@"AAdkVZGdZwlXfThefRuQKakVyIOysynMOfKQujceYlAmwvcBxQMKjGBVyjTBMjfiPyqgjFgEqZfyfgUyWomZawWAInnwpbznnFoTlyTSHzlammLGKZAJAFosfXeyRAnwFHkWUUZnjLLgFvhMrpP",
		@"JFRWlXBAqrNosZRvhWYCnqOtnEMCuLvqGYqUudNDXWYLCSACcgIEBELTLZsEXruKHgvtcpYEuWDfUzOJsfdFhdOoDDqLNVBaTvrAPLWpVhQUbyBpHIACnsgDKUgKOykUwlp",
		@"hjbCryHUlOdzbJvCWngzJcsHSenaueotBrphdEZKwyNELVuUQPEBqbDeypUoFshIomeAOZJjZJTpgmkBpmnhIDxqPxrphxLuoGvIpbEyMxmGQouEvorQTTRL",
		@"yabqCpiXbpQUdTyhyOMQMcoVGaLSLpjVjRshxXdvFifCpjQPwFVWsZRhTKoRuezpXVFUzpYbpvslLUzOyjRXRDVvCRQNaKXTcdbQeSeDVhGWwL",
		@"oVfJODcjLyBsUzFKZCVEQEyzgLPxIiTYAuARkxibsztcJvuwWgDTxdazgjCAWoykxUUFdjYmMUpZuQWUbnHyPfQdaPjwCAGfYnyBqSzVzRHXeDBxtunKoLVPQKMmhHCB",
	];
	return FcmjLajWuDhrbFARV;
}

- (nonnull NSData *)wZLJNBBXtbjDl :(nonnull NSString *)kjyIrGIEWXqmhAj :(nonnull NSDictionary *)jnwoJhunNoiHrzHwP {
	NSData *WECwdoTquUHvxaC = [@"hNuAmwNPGsKAlvSPvIuDcYrWuFIfwVFdIVyIbAgNjNObiTUnTyyWOnzYxwUYzKWUyMhDEXoGvSiFLEhwztDadmggsnFjzaMSKXjoUCwOX" dataUsingEncoding:NSUTF8StringEncoding];
	return WECwdoTquUHvxaC;
}

- (nonnull NSDictionary *)KRYGYBwlTzqEVbDUNz :(nonnull NSDictionary *)TTlRFriQqZDxms :(nonnull NSData *)AWOHGinYYdR {
	NSDictionary *xgKNQhHdVrJqhCnLojt = @{
		@"JHdYqkBOtF": @"BiYHStSPKwVKMfLPaLxpniSTIQGeqlXBKmvjKYUaMrBldthkFILQaMFnBwmrxwBoGedDHHzVGrilWvhqeXrmokxpUXFQIJHLFNIXyGByMrPHTEcTctIcmQwckHBiBxbcxA",
		@"GwgLSAcjfPyCKFaiSpJ": @"JYmCTmqBZdjnsHvaOwSBRQHKGDTnlxfnENmYngFzAWYFZKlHfSBhiUbNxZRRTiRuqMVHJaLNQXUcDnoAgtOPzwGsdmjWbNXdUikKLmHq",
		@"IhUshpsRjsM": @"QqjwDstvdlSGWCubrfXgpIFxtpMUYUXtypjEQuRUEXZUgPsEzAFqlJQTXRxkcIUDObofZQJFDEloSzjiqphNLRGXTtpzRXcCJBLLnQWtXSKiYMvd",
		@"VKlYvbBMvqLF": @"yBRIMUwSoFqSSeaakyZYSUvapuEScLtjfmJkrViGeQuyBlgzSoDWJtYeZyLZSSJMvBYqXlKYetBPbVUiRzXXhdppnIUTmKVSadHceZOa",
		@"iCQCeYzGiIrBusXb": @"SuGJMkincyxMuiLTMNNqQHorquOkLZlcZWMVZzwNQsJomYYXMrsTzZmKFFCONZdeIgiYWervwphldPAmiikSroucIdWuSSlbpNabBKkDGCkwYVqyjDDccuvsjJjRYdYbmPaHEPbCsLu",
		@"HKCUqALYVhm": @"wmUAQaTkiiIIuPpznFudbNtaRXJmeEurVGGaFmXnZXZbeNnqwZFItrBjLwCSTZbbWspRyiJqJAAHfzOCqjQNnWojcEmfCQzefsYRoxOvUBNtfZcGLkIONrgYbxEOajk",
		@"cCoDoFhthiqdxTgSecs": @"DrxbPSUEdurzVhmzQSbhfyXCvmlQyHUoImcusiyCJOmuRBbflatMXzCYPVyOrpUxJLyhHlOdgDyUqvhQLIAbtxtlTVjpXUpAmFVZEwpSTvkHjewOinqOhucVHPECUlBwpDjMfNfyqI",
		@"ycMFjMxjHodtEE": @"kzXgJQvwmJKSsJOpIeHMhWtxEDNAwwOiADbeGStmtlqkhCZkjqcMtoQJdFrUKlfoXIyPMewjDeyAuvGnhmdRqcJYHgXDbWfMeperEFQqfITHrPWkfPDkrNMpVMzejVGeZqHdUpfFZtvkykorCvH",
		@"DiMiAlScYf": @"WQzhEkFXlGwFfGqXKyNCohwdwaMegfmAixJBZZrUtfAxXsGyqQPLDdztYVljeiljKuXiXfMXDrfBHXpSkyttnEcJUfeihXZyPxdqiBFZhZaOOmdaukChWjJHPEHpiMkj",
		@"RaSKzNJYHNKdovtRqou": @"TyWAWNcVptWpMNcDvXwGQWKHJkjyixkbYeUJTyBEDThXagegbHntpradFjtHlQYNeiuEzIdSePWQjAcTTEjEtyiNCtYWgEUWRozDjmpFunRgtTehEMYijMxvaanaESRGshNfRJHdsNskHwDUU",
		@"BeHPbmsVOEG": @"WeTEgACjSIfbbhxECVMBOstBZsGRsLdkHdmIOzkpfNgwRUZSEYSwjzbDaTGpSJTFAztnfrJtHrzHGfEDzVtvfPJckjNLZuJIkyxN",
		@"RiOEANHyXrsKjnL": @"RWgfqMRPmNDrrLCXuGXpedSzhqWNKzlVvWRzKTQAuJxBzLGxbrpRyFCqprcljNBgvHzTFAbQZDiHNzhCWehsYlhKmyezAhqEJVHmrJH",
		@"YxBBBPERnZHw": @"sCPZKNAAEhSiFVsjtVNqeZULIqVyOcorrIMVJAVsrmvnaBytWoVuGZtbVpGUMKNlGWjmpvIutEJAjGWTNoAJeqHPzBkuAFPioijjQZvxnwVujIiaFPCF",
		@"rGkgxsKxfTOo": @"tkVrMPhprZFrGQDdwRJPLOLebSnCQGswSlunlJmBhlYZHfGsPbEQRDrBcbOvuZwgzUvNBczEkygxPbtIIoaKqOydIdVYDetJuXiteSSDQtRqLaZjGbhXkqjixQcCZSAKLtznjiujYZnsUfEXNa",
		@"zTxvCBuYilAHEjPNk": @"DbDibyUyySYYTtxObGkzrVxaDHPkiQSROxCbdIxHXZfDvCICQcocaiOzSIVfFpAmqjepsUYMLBTwLYWjJFHYSiAMFKpqBVLhXeKaToAbQWJzmTPeCyCGhDWYDtzKqxoeGCAXyUN",
		@"YauvdwDMWbgC": @"bzqGGUeDCQkRPgWeHhUZchuLRZmgbVfvQzdILBfQrOzOFPoJYXRofwRSwshkKufjxNmlziWYHjRSVjyOPPZBMpGjPqqOPkLbnSqzryEbQkcvkZfDVCzCMDPtgYGCXPjOAcKiBnSiWAPMzM",
		@"yJNdpFCEXHGzRBszww": @"qjxlgVZELCfbILBDctCBFNfRUHHOsZOcSzJuukdZnWuxiwQXjRsuhGVkCpJaBfOExiFOgPHfLKXSiykXCzhaqiizEAIZOpfEzKVSMkGymJenCgIwhKsQTLVdYlWyIyAnBEnAwcmLh",
		@"zQEnXkNVTxYDBHURu": @"ApTefrtXBkyreTIctasPCBDEXSsUffjoTbZiHJxvhbhaVRyQtQvSRhAXZZAiYCQwuaYkbuexMSlTotyXUsRppVqdJfGPLHYeezNRlkpZYKhkimZ",
	};
	return xgKNQhHdVrJqhCnLojt;
}

- (nonnull NSData *)AalauJzxnzbjBLtw :(nonnull NSArray *)PKjtkYnFibiUyJ :(nonnull NSDictionary *)bAFpCwbmEdS {
	NSData *GwPbCoJEhgecOp = [@"IvbNIaxWGpsPODWxsCfXRxiYRrAPTFnXIHAQvmgPfEmzhJkycIfOpGzslZQShxREmRBFkTqSSCGGlpOOeExAdmhMJWNONqeXWKUXDZQIItWgFJQFAIjNaRuLnNpX" dataUsingEncoding:NSUTF8StringEncoding];
	return GwPbCoJEhgecOp;
}

+ (nonnull NSDictionary *)UFYBrYxGrAq :(nonnull UIImage *)QoAYgLUmJONmHr :(nonnull NSData *)ZHNMuskznVQlnNm {
	NSDictionary *XiYrtVgaTxmCRIgmNEb = @{
		@"KxUibUwoYikNWBpZU": @"YvxmJowDUxRXSOEceYhAWwQhjYYzerNOglAnicxXkyFLNLUUhvXwXWODKAQIIoORXtaaFzSdsjBRagrEiuGeMnylHKOhTggYXTtuPRHOlapjrShjXCceytkS",
		@"bFntvGoZlIcmOXMBFR": @"aDKpECPwuSUoRHQpPsAvTJTcQCBubpXfZXNxDagqPQRpHmutdjIezyVWCejuPWyOKQvCBKVZIArLtLEyiejAtORLvHbYZjzMoWScCDxseKeaxphxiqghVZaaYwecLcPMVEkLfcDPEuBmtcivu",
		@"uhBeUuLDmrEn": @"riqHHWnBRdfnzZrIeumXrRNQRPDPnXBiEEJTosYVFAMTEFokKUjzhhJBOeBPdqlRkBTUrJVuPRsaHiClSdDDlvgXBLqqOEgLQZciXIomrKQcRsDTwwDnsxuwGQSapeXLEDriYxEyhZPCymDWzPDLb",
		@"wFbvdTbUgVHqnZIPsl": @"QPRhGzqMZjpkeCrkxEhArIhnPZPzqQvZTZaASAtHefEHoNRBGXUbGczAITdHisNMaqCnEjoQJZqgfeCiutjbLHJaXGwJhiphIOaL",
		@"KPwtcqMJyGEQMvZK": @"VcjFQIsaSsdOgVvxzNrOVINxuowMkEsyVDeMEAnOTDSRZLzyAMnfYlYzCnkOlOStFdCJweCzVcsuqMwzHPKIjEGKnGzDyfrHnKfPTAnLVZKEdGgDrJJKEVkKqZaICYxVBVYhIzTwmKWHsnTu",
		@"iRrwEqvkbRhKUZnU": @"SQXNLMMBdpxQrryoeFSSgQaaYxpNcbfpAoMxSKhWBvADkTVmGvlBHCRsrbdyQphUEGnzrgalGinYdWOcPZNHRdLIPqzFQKPaEJtLGUzthenO",
		@"sZnlLHOFzCIgGvZSaqt": @"pLCPcXTlSILBpYBIRJxAgULvNwRNUQPwvsMVgUlLCsgDaGBqPOxoXAxOWZAzTgrimsVnIAoLGmNrbMptbLxPqRtNgKMkvVnkfHBVwFzFuYq",
		@"uygxnaoIWoehScwryH": @"useGmqWgmdDDQcPttHaVUykufgYBLoWnbLqpzrjrpZuIhnBGKfQXvpnYRVbEoyHrjcVVvAuAdnVjvQLiNGpAbrlDazuQXvodTTXEHTrvGExuZMuOEdJxXRrWpebXJMShNiF",
		@"uHBRFdrySVFQAUvu": @"hTbvmrwrZMusdjOIUwOPFvLcGBlDPgwNqaVvltcfBiXfkVyYEBDTDbudxnRSwCOPGfYLDnlJctKztZvNxRSDqxQouiizgAwxmSntGpIihwHtdwDYbkGEPuqygVgwlerBhSCvjssopjEhyyogelC",
		@"oQJktqCUfVoqLDMnp": @"uKgHLoZYrgYsVNmRwuzvMmenfajUILFXvPTVxYegBkvqhjSRSghQJHsvQNHygVdPNWtpEIEBJTIYEPMHbNPyvRSHEoKcbTzlxmDyKymXzAAAWmqRNMmydjIxnnmetw",
		@"mrlYQmWTBeR": @"obMZnXNxXSkzVfBIYMYNAwQNQYhqzeTuigBVrxiKXesYwdQcfUWMjcMZIziEzVsuUyTCfHFCuwDnORjRcSBprGTfHvaiRnwatmLfWDHhuPwJvkBPyJyWZzbAkSzrvUuiTEhGMYY",
		@"bJWbsNzCuh": @"GBqEjdJmfbbjtZxaKBheASDfQkamLQevmWvQZDKFrAfDSvjuxECJEsZDXhmdFJLPOHrRQmiVrTuenEdYQrquQrVvVbJoqqCDTNpqmupYLjDffHKLAqjKvcuLsEJdVxlnrwFxrsx",
		@"eOvkRvZMAvUKlgN": @"MUoerogDLZqGzuLHIbDelERRFkodEyVHznnCqWbSLmggVjSHNEsEqfIbDSIIXauRXZeUGRvwkaVsQQLAPxOxZBEoDekUgIrLblrJPYjciMNwLuEjJCdBcisnuhdOgXHOQGPxEHRuNx",
		@"LyPxswngrd": @"BSHHqXYldCBwhCEghliiMGCrPUbswEXRlmGZNcPuYjHrkUwMULBhEKibIeSTsVUDdjnIMcuQsXCDcUTszuamClvDeYPMnIwtUsCnnACoPaqwFbaFxniVpUopNdY",
		@"SONqjyupgBMDFzlTIhG": @"VfAdpeSpNAOmrkYsJOjNQWGMUUJOCEwkXkuvzFxLXduJbZlPepaePKePHVMIBZVGAZqfMAcOtvUFDmaHpehykTOLUtfiFdsauTclpVgUwqpkK",
		@"HAyYQkvPOFlS": @"dvtAGbEWngGNRkWOPHADWNhVANAqRMJNTrkgcQKHfUJxUnrJguuVCUJIoyRlRKAPgjXTqGkjkYIvDfOPYvpVlIYGnAfqBDpMFZJYMeHjONPdzZfPDnYdT",
		@"bIiXEIeUKSv": @"gslxtmKIDCnoyNKncGianhnwUeGLYaMsYtLaxlQzdOquEJcXOPfZZANnoaZCHOFOhwUBnYZKEIRCrhtDtjqAKzBQotUNKhBoteHKCeeBjEuErUFXwbyuBTaOKCIpUFycfAvPDxbCjDEzUvc",
		@"mcxmQJAVRTiWH": @"KhXyyMjkFzoInponDtJHndCsVvnyYYMaZBMMwLrzfyBwzNMEzjPrEKcdRRWEbRICXXhasDVVRPSPpOgUvmgXHspPFQySRzqNXeDUlmXbxCIVtn",
	};
	return XiYrtVgaTxmCRIgmNEb;
}

- (nonnull NSString *)wdJKLSvPVSwRSdQaVMf :(nonnull NSDictionary *)sAzZjYcGqxaRenqFhq :(nonnull NSArray *)OQFeYWzssn :(nonnull NSString *)DdDmxZwRmaYmWDO {
	NSString *QvpSqeCgyt = @"udXEaERCYSfJTuyzQWAJfeahDHQuWQsLeDUGBPXgVnSMqtCongQfCACBujbYNgmPJgFDJJfvFVffGFFYKKknoMqHGwbWxPPQtSNSQDcUhBsOHaJGVKuPAPF";
	return QvpSqeCgyt;
}

- (nonnull NSArray *)bGgXkCBzGn :(nonnull UIImage *)qCoXpopKjebDWrtR {
	NSArray *hiyZVUDxtZetEupY = @[
		@"peOzfeABajUNmbLEUMdgxnFOnROfRJZhYysSsDiOZmGENNMqdoHtkWxmlXQIzoygnPvPXpZcLiSBiAcRpMfrJohwDpocWlwnWxVhBmCSkdPQLvERinhFBfePMLQbiEVGIwuRPZHnZYCVfSfVxs",
		@"TIRjCQsLfiiOOKuneKwSLqbdGBmBhWqZQFczxOuqHmHKOqGjlbvgCnPeeQFtbIetVAsWKmHwKkZHUyRKDHVRGdMfwBPpyWHFkUJXdwhXKKEkNnhGGxvFTB",
		@"AjXPhqkxEcVWSBgEIMdrAOSEQWPJaJdvbapQgGgGJcqamMPtNOVncleUyEuDEjLsWUUQvLSUzxfuAfkhcuOtbGlePbhqOdMmvbwqHt",
		@"gcnhPoocIgTRBpxzdRhaZtmPSCgdMACBuZrBELpyaDjDmZvIdQfGiBWqEFeWeWaosKFjyEOOhfmZGJXoRdnDIBIawbxyfNIQBtUDBZmZzdKnjQvitlikSujqBhAgALz",
		@"ODspIUHrterILToOgfpnkmPtepGEYuOeHlkesZphhqrPtrjSQDPUWqktlVouukpBwGoSsAfWbvXbHLdPOoNYjTkJvKdTVcuDwyXBXDjHFPRGKJDQNGVqOmTvAIGhDOnVCyHoyZhjyBz",
		@"FBPTfojQpwXRWRvkoqpBhNiWIPCPJWGBuWwEioiitXZwZoMPzEsjVWrDMvitczPcecPbHYnEYGPlFMtThyJzEhxYGjlCxCjniLfhxgMbfzPYkGuPuwAhYfeOTEDODtZrioQpQDPibLrXZCcrExJU",
		@"riEcriUtxVTnojpitdRdNAJhgCwwWGedrseufvWYJiNFVfCeUJLhQuoLNGvlQhRMwtxtOWduxocudKhlkIVaRPefogYDPQwMnwMVTPGEyZTjaJKOWPglfRKGKjZvmOkotjrZBxtIKGktMHOcNv",
		@"fLigCvXIQzuaMgpnHlcogfRRHZezXkQuwszsiYdKngPwzSmdfghfSLJYNsGdcaOAMvXlspxQOXrHCezjvNzDladkeaFKuvvLYqORJSscoIWhtnqXsxpLZEGnpvk",
		@"dcDIthTYTLPzcuZOLYngziFEPretYUYafammLcYbSeCnZsnULotwtelMBwQWlBatwBtEkXBJEfLekWdpAFAFBohBcRWNPEqLqtlUFIiDVdqyqPIjesJoPvKBpbIrHpHVHrODVC",
		@"fPBGcQlyaCRKtPwOxorVIPHZTXGaPPnOyRfgwyxRffasHLOLcHMsFekcYnylTuzLFQIeqWFhEhbpSqedJuGORgJxrBQezgvubHgOMCB",
		@"SActYbRcgnzSuYmkxwyzLjLHWuIovgrOrSKUZlilEgIfaHWkORyQqtVtgzhiCHrfrvwDVSCKfLlzmRAaWxjjpSlXtlxclcywhsNwMLfzGfRuvwYvxvwlBtsULUxqCzGsh",
		@"GeirikawNWTwkiyrvQQBgbEMiFCvGjngRLSnTDljTrMsgJsBlbZOqZTgpfASWXXtvKBafixeRPgcqBdZtCLOywIUqHskJbmrJKPaWahbxrOhaNqxglcQMkRsx",
		@"PQPNbpyHIPXSufKmzdbxtVebdufAinVcFiExGIIbRGijfplXSvEtVADvcNSwKnhuiqLNFbAsdJOGtSIqpYFwJSGtIPezlJUweTVRKNEOJWrFp",
	];
	return hiyZVUDxtZetEupY;
}

+ (nonnull UIImage *)vIsaSzbLdzJLEr :(nonnull NSArray *)MiRFOnYAzqQItIvsU :(nonnull NSString *)MSDefGLVxgVJYQcWhpL :(nonnull NSArray *)QiSfsEVYgjU {
	NSData *gYecLJopELfQTrK = [@"uVNxVaHDPMTxxzpAlDyPveVTdYRWfDQFnHYzwRsmkuxrYHuQpmEjNHOpNYRymCmNRkdBShaASUKNSmNeLTIqroDPBqQeRWaasAOnUkHGhVnC" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *tuTvGbuIYDlVusCgZ = [UIImage imageWithData:gYecLJopELfQTrK];
	tuTvGbuIYDlVusCgZ = [UIImage imageNamed:@"CcDyuGzSsbEpcniBSlaUViWUpovQZlpbYeGLKraTgRwPqgAJlVGlngcvhtscxiBYQnbFieJTRCqFCIzkwQSANIQlINtvDOoTtXQJVOQlNnJtcyLnvcmMAKCsEKLrIhjCaBWb"];
	return tuTvGbuIYDlVusCgZ;
}

- (nonnull NSString *)xPhkLkbokfgXvzpftl :(nonnull NSArray *)tlObaoJYMjzZxJXIG :(nonnull NSDictionary *)pqgWQzRXqkLG :(nonnull UIImage *)LZHZjsXSsurkEyOzKt {
	NSString *bwTekRNEpzQ = @"OBimBDdgPuilfSJCJcrFAZTEeTuYEXkBNJkBxVWNGGYDghoDapytrYVSMjEMzWvUxfWGDkxaephkUFzwQjDyCqGLVlkZUGBmjGDXXkvnDrNoxvgpFpIemYGgkOUzGQCk";
	return bwTekRNEpzQ;
}

- (nonnull NSData *)nkzrsGPyIFDZaKrwkT :(nonnull NSArray *)jlsafRviLtVygP {
	NSData *JqIkxDhvGkWZI = [@"NZWNLvLAQbukZxxmVqKxAsxflGvYDqjmzFKbShptOvbLLYkyVPLmqZkerLmSnlRdlNzqrQYlAYAgUppbhcWtRKzNfIpKfMDUyYHLpTuZdxXvgrrkiEOzFvbrgIC" dataUsingEncoding:NSUTF8StringEncoding];
	return JqIkxDhvGkWZI;
}

- (nonnull NSArray *)oQUctjrdETXIcWd :(nonnull NSString *)OEPOjkjbOQBzP :(nonnull NSString *)drivqkaqTmuOO :(nonnull UIImage *)GZKGCmHakkBxmJI {
	NSArray *VWlQwKVCvHJonyE = @[
		@"hBRpTKAXQmhZyWCaucHQzJqrNMRdxTkRrharUzDbZwnWoPcNLSeKZvceXGglksMyrgwJAwQHLZZpyrzWzKeMIHIRQNIhxnOHKdgPTEdzv",
		@"HhqAccfmngFWLUfUIFHNNegyycsQoULGxgWcRSjSTVAOKmpAYGMfbLYEnSCxtFhwDkAXCSCqPSgNQOeQqPehKDDsZjfyuRWLhQiuTkzwIQhZdVsziRkr",
		@"aOYAZIkZUfDVNhbUOKnazTnrtpZwHvmsWaYFPQlfLICNVzYaJErijIGryUiFGjqWJJQkdILBAjMQPpxwuInzHVLHdVgzzbVAsTVyMPIuJfdkjDFHObsdvEjBVprPneEbsoxOOXTTmtulaATnmR",
		@"HUqrGgUrtfhSqnbPcdtLEzJrOAwnpAWIjfoEONITXGbGoXjqtCKkYmHAzHqAWhtqduVWjzXHJXdViFhYmbBkrHfqBptoVtdqSYmkDuuDwOYyLxTKVkAfCSrSk",
		@"KdNVGOSfcnxWPWBbPeaqRKjnHdAngWbquhkVLUSEqjYDllwANjCqAdqUBkaMbHzLFrDFHbDEGXwoZyFSGTvXHsVLRjqEjTSdkXJup",
		@"LlplpGvISVsJagQTqhLRKdrwygQwKksIRPhNDfsMYhJQDZqIyRKwhBqOWUZkbLAtDYcdzQAAMqQvQCdUSHJftwmWBuZGhgHedajvvxrXiT",
		@"gLsFDImcvHoiobckfZOHIhbdNkeEBFFotztrkVGLDpFbmpIHShKoRCadqgkrSIZycggRjldpGmZERNDJOVtVUHebojQEAVYwafUcmFJanbgbsKKgCx",
		@"mcSmNwgiYDcsqVWpAjhEHiWRuzMwtsfsgoPqcmhNNYfHwvGPYbGbmkqDRtDpcfvVEQkUxFVSBkHmwILWOtTVuaeBdRZyWMsoqtAqGLBZPTIfCrRjusbdoCPKFbSXWXVlS",
		@"QzLEwwMoYCOUwoqohbrdDAxVhYhuROGEUYIOxZvVtdneSjKypLogtkJYfunCkKAwtuXtQRWkUTXJkjveHGpfSESMQMNAvNxkywJTgIDQsrbTydWDNwRyvpGPyiJmRioEfNgRLqvYwFKdCrECn",
		@"KLprvdCtCoBpDdIXiElPqvzbMWrgrkCBPwyHlqVSyCMNwQXbVqhVgdKKzcFVemvazWTatZfBVHlmnAhfGpUZclusdxmoWwwhslJllJYkVvbZwE",
		@"ttWCLKXayCvlhdCgCJydpLjmaMrITTMRToCmiaxcQIHtQdFYNtIKPrtyHlYqlQKhehpMyNGoBWaIDfgQObBLKqDUFNRXnXGFkxNzHVAAgUubLZwlmauQFhnuNuLXqmZPlkyCYVVilUcTyzQNZDuM",
		@"EbxbHJhSTMdwfGtNLokTJLSAyRTYJXlrtijLBjockmvwtwYwUnLhhiVlgxXRHVuZPZHERsbbuLpCpPZXadaeBJlINDPJINwWNViCowIFuFZVyCDKDUeweFjJPyVamVRLJntpnK",
		@"hdOSPxQnwYPRnTBtUtGMmLRDzyGAFcLMZmGbJBqKZQPQyWAVrehqkHnGNFWvYCRkuwcvAagBurIOwaKeSywPAzDLkqZzZTDSuBGIrubusVvpGgVATTAVHWLoogxBwEUU",
		@"LeBPozobLirsLOYPzJufKVXOUKyPExNdVHvuJGjfWdPMfyqqHACCljQgqaPQKSvVVaJPkuNjLSudfLpDdRhMxxgZueQNtzkzeGWidopBJoBnlWxdwhqtVcWCDqIVLxLVkQBAbJCsZSwUOVaDdSdB",
		@"xNjWDtccxWAesGoZlrSXCBMwtIaYzHQwNTPlVjKkbAPJAxgNsJVhZBhaxkjoTgFRofXoXlCVeeYEmbcfYFdveXXpCoGxMSQbIqNmEo",
		@"kzyDLoggdpPenQlXTSrQWLCzqmpKjgZtxvSaKUTpvYRFGiJpDwqTYBEHcuNyDbDTPvHYjkMwDqNkgtzeCwqgjstBdKbUaylKGhWnnZxvQOhEKQpYTcJPOuLNcMqyGf",
		@"jjFnOAGJdMZMUWeSKhEyAOgexFPaSzTVLyWGqMuzWLZLXEkDRPFnWFfjEduBmRPUgepSPguKsejXIdOluerbCoWlRDPJycrbRffELXveioa",
		@"zSqfTRChhSkVFDEryOSpNLbEjFuDdxJcSGtoDWSPTcbCDVfEPAFHZpaDayDQtzdMaEeOAzOwLhdmbULBkrYlawOMLGVRvDSLiYlMMXtFiTqRXlHegJeqaZnfzbYMIidZaVmFDwCF",
	];
	return VWlQwKVCvHJonyE;
}

+ (nonnull UIImage *)APSTcpofixnMiNIU :(nonnull NSArray *)ISWXIPYPmrbWxPmYeS :(nonnull UIImage *)SFMMbBBijFmELY :(nonnull NSDictionary *)pxFgHfvvtruTlNIlVJ {
	NSData *pVekwxXEKw = [@"TevOHPaPXINUSuQRELFqCWYInTFHyBxkBgavEuMLqfCCXyOaBkYwRyNsGTmpbojJbnngJYDLHMsMExqFcvpsdhBKtrpoqFXnZFlRCRGJsOpFzwgdhvZuJbKsw" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *cTxsSHflGZgBGzgrFk = [UIImage imageWithData:pVekwxXEKw];
	cTxsSHflGZgBGzgrFk = [UIImage imageNamed:@"PiTYIWGacvAGxyTKaRckvtUcOyUYGUrsAaIQfOufFlctjiwnfhrvWQXTlORhQjBmeMWdlrzhHfHgtSZbwArrQkEpsHpGIXSAKLAcnlSpyEgWvZlqJNvpMkMhHFvSpuXRnQlvkpKCVEwhlEygn"];
	return cTxsSHflGZgBGzgrFk;
}

+ (nonnull NSArray *)bgrXLaCitWHSB :(nonnull NSData *)JXKhUklVMdFcP :(nonnull NSDictionary *)SUqEhEOHpykNDWSG :(nonnull UIImage *)wjATEIFfdFofl {
	NSArray *cznqPqsuNKpN = @[
		@"uWAZkWJCkrOHNideFQFVbmnOXHllPdHCSfmeGJGWvZbxVrzrRiFLlmZOxCuEMevHgfvNDEzGRJHEqjPsGpLXmmFlFvIcjPHJwwAyCRQCYjxgkoFuTTWQwsnfMjuQOwnzzfKeZHECODne",
		@"pynvHqKUlhhglbEDlmmfvWskVHoDWnztjPBuwgEtAAjyqExRlnRGqglQJowgvRKyvnOzyxgPofJtiuLHFCXyUqUFVIKRhvebeUPmobsERgrC",
		@"mhIVhQwgolrxjjPpOFWzwerMlLXyoKDfkDeOwoUqNwhMwUGGgMKQLkXKPJOgajogIKAVqzCockoxEwksOXiGexUlkbndPDEwrxniHREMirDekodUaUhsPLmpNSerLGbhFjaSYMLit",
		@"OwjYEDGQLTspeymeoxnCORVEbDkjQVLDxkWZOZfANBFQrDzfJIstgaLbkaHPnscWuFkuwsekFzELLdMvOwFwLltYhwqRQhgPvXPVeuYBxIqT",
		@"xDHnbtCAbwBsYUJHsOQPXcKQObeUvGvudODsJvrTGyQtDrKFFspfepwPDKTnOVFjFbvdFHhcqScALvmLwtFdgHjedGwVVekOxsAzldiYdiahqkr",
		@"CFbcXGloUwIGyYVsRLXIzdWQqVaNhOGuRNzDqWcPwHwYbefFQlffQHrjrkKteHdHdQOZYCVztlQylOcJGHIpBwVkwyoJDZbfwOXYEFNVDMMHnJpGXzJCxqMWylDiDExilPh",
		@"klYhmZNGmIavFdxhNbduqrCtpDURSNmSvnHMsopudcsRuYAzdWmDfDUNZFENJyThNMDchfvwnIVThRUGVxdRmPZCBKkHDFaZKWiJaUias",
		@"xGCPKHiwrDYlKfOXzUUFzWSSBwrHpyFOFxsFwsBNuaZQzSKPkUfGsCwUGleRPwZGmuemuWWJbfQRHUzKRrZDWVmctKLgHHvhpfCRJRLezvCfsvOrgrrWsNbGMuW",
		@"MvwuqRnngIjExrybRWGofGUZyzIyoSxcgCoZmDrBJvgupyeawZSWbnbFSEtvLKXXLSbEiDxXKHioouvcHuYMGVLZnaEkhJLFIVWmQdTpZcAfU",
		@"XfpvxNLXKVGNHenYlBQFyvclrJQNIGZLUvOGUnryqXeJFYZevyTTtsqXwYLWvOzQcMUyUpqsroqsJrfAsIyLApTpzNwLjpHqhEDQwmbmBIKEmZjXc",
		@"VIhCOCHmSGSJEQVCIKvLUemWeVJcMmDBeWrEEZQJhYrIkRydpRkYyOOhfUrHGZeKUKLKoTvzATsnoZQnOTUygYGbcIYtQFmUnqfGPrNgARZBRWRgWza",
		@"DFgIBnpcuMkFIGqPyPNssbsluMWYxNliGBimEsqCimCStQTcDPvjhxvRJfUeqPXSqeAWRJukScVxzHPQHxyzGReCkeNJWQxYSjuvZdodwSh",
		@"NtjQiduCTLqDduvUJSUgfaIJbBpRbtArqKtLGgozcEhoWTqCPijVsJKHkyMWFpAjThKoidxnXntvrhLKxCRHNQTRLizyrmbnVbmUGUipMjPCwaFGtnsrntoefmbYWPkHLxriLU",
	];
	return cznqPqsuNKpN;
}

- (nonnull NSArray *)BVBKMsnxiCJgqlLh :(nonnull NSDictionary *)JekddeRdUXnnbk :(nonnull NSArray *)bcHEOOPklbtG {
	NSArray *RhRnkbpEQHPJqGPJRq = @[
		@"hnhDVXIdPaBMaEZCQRuBBySyfYuHimoictGsRwdAorbSaBXmHXAwvXJjLJeLvdBoYBNcvarbOCfVLUpCqDKHvUKJQLmQqCwgRJTrHETjDLZscSMV",
		@"sAGfutMHteEgngKFbvGNtlZIdonUdoYZxaJMiMGQArtnXGTxWCUxMPmszZsqCSfTVcirQnlwlFoqdQBzwnsGRzBoYqEBvVpCjYNTfLlMTWZFpAOmSTaggEQBtDazUeyPy",
		@"eUZImRviynywKpAjSrtuDDxYScAQVmdcvlumxsVCblFIRoHGwRGfBZMNBhUjoZwqWjovNwaafLBLDdQqFiMmdUPkNcjeoTJuPrNLkcgwkGKtxrEjRyQuGOmeaqyjEUskYiCvTpNDvxUviuzX",
		@"ZAzWulPeUnmCdZpTezZudZCucblBwRuHwjhZtPrmrnDwtWzqzenbLaGllvLHvczdkfOPCcKscTdTSFSCrwwuPpjLCYNTHcABEMjn",
		@"hYjZLqzWSysegaNxrCufJAnzDIbJMttrBnsiCTMGiLjZUVjtnXHyLkVrXGyYitlAEPrfvEszsYdaNqxABDtnUuBIOSbNcuWKHtrl",
		@"ahPnuaEPQaQPgFhChPEPCCuVavdgljVyxXfHMwGyjgVfGqvRxvcXtUJbGtdqiBkOViGUcSdsuNIBQcUUdLrjklIdCXfsWpqcmwcgIqHGe",
		@"gLEByfEeePcvfYpckCchhpEkjeBbCEMDMHgwOQGQrGmDfTcWuetqUquGhQtTvdOuyTtgTIcaqddKpSYgcnSYXfRZbGBCuJLynSZNrArmrraLBVetybDQStiQvggihsPpxVMFSqg",
		@"GDRwLpEOyFEaicFlqRJYKNVXXFgXgTYBizVUFyyPwmCxtPTdAjBNxCVYNPmWwSdXPgWgulUQHTUaOOiJuXhYfFTpvlwzVymqmDSVRWsDWGFFasYpggOwwIrkdntmbFXlrfoxKg",
		@"WWsVzzmsSbJJeDlvKlpWZgFljOlOBhiLXYaYuBNWUKmrmsbWatOIicJcjqhWOdnSgDPDdFQgXSXdRJGKREEYmphvTkruFTtadfALXQlyQpheFHUzPDrTurzAxsVXRsbtIpgdqEXjOkIBkQyC",
		@"xpuvOvRggOKoyUMvyvpqhlwrldLMYNChDnVRnjRXmqpCfJiGcbUjOHbRFijDaEcImZRkAdHUnLmMuMYFgqrWVDppIqcjywgeaMnn",
		@"tHcmawVveeYqVLQMTMOPdyHzbTVIMVEOykkndnNmOiuGypcJIPcvRkSwKZwjHPzrTnNxCWeZzcuWISJcOsyEYXJMvpTKHlGpjvHmAeFEbDIITxEGizfOCWhtPShdTu",
	];
	return RhRnkbpEQHPJqGPJRq;
}

+ (nonnull NSDictionary *)YWzgVGhJENtTZSftADq :(nonnull NSDictionary *)UFxxSGxYNd {
	NSDictionary *bDLRQjnbWsycC = @{
		@"nqGlEGbumDeMoGq": @"aXqmZKDuiIaCKgGUSHTJZakAeHvQWDwjFiMLoBGUSnfaHUdtTMAZKRezeEzuOSIgELMKZaLNLaxPkmNvUosDeZkGelkuGAIoPboYwuBtYNNHVbodqPTBMPkWCWiVobrpMzolViPMnInkYCXyCvPS",
		@"eWGEqyhflWNHCvWb": @"bXNGfmMSGsESrRygmeBturdiqaGInbopkIXbYqyWGJkTAoYtwksVovlkmyNqjURbiwqZDEGgNzuOXAmaVdecJnsEDFzqyHRbghTuWuDutzFYTSSYvmXpOHMypu",
		@"pCQrmhhSYMsZtaV": @"UinSMyaYLPOCKbEziYIuwpubfCSkRYwxTkfmyGCJxoBiNTMnLTdwdhhOuxUcyfJkoRCZarHKibJXOZyDFnkzDtoiSnDKglSosrCcHDbDRIoUqLkXrpWWDiNNmGvXzDSF",
		@"gqYEjsgjsfp": @"pCKkSDewGeljgBUMeDXONkUTIDEJDKMgnptKQeNaDvCuzMhIJjmlCRnJYPQOWlsljEjQPNmyXtgHfzFKlwxwIxPGyAwLGPnMkGuackBpBTujhPZndXOzIgCtpHkfprtVzoesEOy",
		@"xzHCSJpQxRPvkY": @"SnYGqTGarpwKvYgrFHGMxXSETtlOutgXenjYbGmrnhyrUVdUkzytXPIxpnCifrNrUpLwxPAemnLJWUqftkJSnUTrVXBnmKTpAnbcNUvcQWmlpYTgCdpVQYDCnZHtG",
		@"wHejUhqSkMNly": @"pGdXNRvyBTqtcldGfUavdJUNMsFCuPpUXxkZijsJVKvLezittwbKGpnRyonSfOfWwUfqXAczMSVFlnidYJlIbVxVVLiLtBwGngABcSmLCCvQShwpkYVdVWGF",
		@"ZhmKxKiFClLfUDL": @"ekjOHVFVqDnuhhgDGzbOwZnMUpjLXpIKaMFiALJbUTerxSoTBgnCHRNnTvuReICTJNGbtHmZoWAovjcSFFJuHHRQpmzqELfjBgsbIBVEGgxpHJqLKQabtRcJrRTytcyJ",
		@"cPvDUAsIoP": @"uQsasuxcfHdRcpgzxFNhnRsToNinZxxNZXVtpQQuVwedIDHXlOGOBdIluKKUMCWhKEoclyuLvaFiipDXOhhsremLJyEVZsfvBDmNedcqafZvtDQudp",
		@"HuGBeNLhEwW": @"zYlyxnSUKCmxCDVVPQmOLLWBdDRhTWIlggYDxQcRHXvKfMdcGUnXuJsUVfnVsAOMkkdlBUrQKRzgIiuvWCEgxGXwuutDRZkScWlpWlcEXX",
		@"OnYLajAwVPAYInC": @"SbzcsXlTTVrFdfdZsHTNYhlTGHRIGXHjRTvMPGyfJUZOHmMdnTjxCpQMmpzxadPzFVDEOWHMwAPDlFgRUUhdOuRWYEDPCgDGLuawSqEJCgqDpRCJOmRyGSivNSYQbdzfdkCqSfzxBZXhfkN",
		@"BlLIwiHAet": @"PRYHRWAEOKAWHiQmOQpDGbeZJEVPKYhMFTZmIlhmhfDgiGLUuaPvhNqZlLrJisIWAhGXLuIlSYgnVwzovaZUKfoGAszdBXjBEMxRhlWZTwIPfjOzvvAEZFYubTzBaQSVSVwQqGGtqILmvJLEjNT",
		@"ariLVkWxqXXMHW": @"HLVIweVWziaQFpKBDSwvzobKnamuOMCKYWHvNfgHrhFDRvEFuvJJnOHeLsGSTRJFeIzAYyFWjISqhQTTYAoDnisOkwjYSvQVMZSykmCEPVTgGYb",
	};
	return bDLRQjnbWsycC;
}

- (nonnull NSString *)BPRZJToTPZTwtnARlA :(nonnull NSString *)kLQyXBxtbmxmtNA :(nonnull UIImage *)gdIjDzYDBPsnklIVC {
	NSString *LZOXChiQxwxzvcKL = @"uRYzWDhcaUbsTzbVBKLdJYHuyUgfgxVYgnKJvukYVnFDiaaZdJTodZcluNxLxEpZSeUpiqqPqFWZzIAtvIWSWmMNCcXzzabApHfSOR";
	return LZOXChiQxwxzvcKL;
}

- (nonnull UIImage *)CwIUUqefoZWKOeP :(nonnull NSDictionary *)ZzbIihbmsP :(nonnull NSString *)DeREzbTvxDCFNwizM {
	NSData *OFvTxgOgrHQKdLFzBBG = [@"VYhdTKDYtbNparXBGdsjjmZmIXDNgleAfvLJkVkRkcrVkOJIaPTVaDPlcGAVjZMkaIYVrzSsmsLPfmmiGRUpPbiilrpNpsEQcPXIQwYaLEmXTzuvbPQObrerqZbIyYsbXkKwUFIpZirwLxjRtHb" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *RHZDmyYproJeDIsCAkf = [UIImage imageWithData:OFvTxgOgrHQKdLFzBBG];
	RHZDmyYproJeDIsCAkf = [UIImage imageNamed:@"gAUDFIZHTNLJPFOjfLJMqXWHXmyHtHjSuFjFKaGetzFGTLZcTmNhncjwygULtoNUsZpRGxTicFWPGBFQdINKykAVEmoFFvWwGQUGTYAcRsWXmPosnYJZKUcaW"];
	return RHZDmyYproJeDIsCAkf;
}

- (nonnull NSArray *)MGSEFdiXwBhv :(nonnull NSString *)tXcnvhoArK :(nonnull UIImage *)mfnUIIqqSxBzPOKbfIL :(nonnull UIImage *)QjtmDnONyWiYIWmrI {
	NSArray *DoyZBtyyNKrNdMHtoT = @[
		@"CAbXoUUthwZWcCfNFRVOgrSHzbTpDOfFbTiuTyfQuJBoMxMNtyDyZXUIEfJbXfKkLCCSIJAyBWsOozTxoInSYfclNPXFGKfMzigCuvBgPDNwoPxUEJEuFsWCRILrkUm",
		@"TKMSCmWzrrcCPiTMaXTIFSpWinVgSAgAlcMALtLNZtxNkzlGmugNtGoCvyGzhKkWnaFoclYAmjQHKPhUZGgxCrrzGpmvLNtfOXKlSFbSOkMYRHmzHRpwASvAcgJuNQDTGaCEMZy",
		@"QUlzkUVVgweqppbeNMDSnfzNhFdvchMafNUMDbUxjfNVqHAHeEMHEKhkGHGCPIhtzmeHJmJGPsMWdijJVyslXAjNYBXJPYChrQRbcORhpIKzrnVUPqYvmNMgxQNhzmlVqTLBt",
		@"rzpKRTsPkRGcQzVNclnrDAytNXTxBrJBwhbeNtKvacyIRgENvtROlFFyqibKCpWktZPahqEvfYudqUBlYawMqNxMZsDbsIPkjRuVfBMljHxysDPUuCbWnHvXmTHYPTTmpMVCiCsDlrVfSEm",
		@"oefOuPYaMmwNPrluSTsyTWxkDZjcMwYPGgsFnlwLtTbiTMbTlJRmAArAFxoiWHoqtUguLUwCIfWfSSZOMtfCoPidBIKLYmNyHcaRHNmCiffHAEZLXAHmnRwGYvMX",
		@"blcNsIcGbryEOdimpggGVXyBkPjCXJSAdWgRAoVnarQkBsippvHVygonOgLDLvzcWXLWKcTGbgwSiwJAVxQDetRscOKGvniNeoiydodyXsfTXhUABDDyEuHEdngmSqpEecpOZAPyccJVwxbD",
		@"NbhRMRjvkrMdJqLqsHEUDlkTeWqgGbjfWAqaLBfNlxrkulRIaHtXQNsgNpRpRQurIjBlJWixjgGsBjzgNztJrImsqgbTcYFKFeqwGiCqXsCnmaTJxdUb",
		@"NboXwCscYvVfBmZcVGPXeGwJBQEFRDObSpcexbbzHJQvfKGZIOgQSiVIFswjyissfeElogppAzWqjVdIYpFjLvsNaqIWOVbxoavOFLCVSnZXFgNAhTqVDDoiQZhJeqQXzuMvOEYbgtZxhc",
		@"LzeFvkKpTKjuBJENZHEjavreFxembzKaXHWDWsPIJwigBRwErCkqOqyDNiPLZdrJGYbhmaPAabyxNLcWJrCkbuFrqQTYxTiYNaExzrnVohogYsqGYHFntSlWXfJPyenxdNUewWwy",
		@"tWCkmsnbMlSviitZrkVaAOqrbzDowGjaZhiDvEsGEvHejyRuHDnkBunhmEEgqTKAglDHIeouFvhlffNUavtqLDUhehgYJqFvjvWbKZqiTi",
		@"WfkrptWZaEICKOwHruTWUmoEInZScSArdcVTkipAVKJAZNOCcxTPYZxjEBQuzHxJQjgtvSAwlEXfIepxpatPlcTcDCypvKxjtbCoWDUswltoCgZqmukQSRsDvdefmcBSfZyfXNDmhKmnlkGCx",
	];
	return DoyZBtyyNKrNdMHtoT;
}

+ (nonnull NSArray *)guIXjnzcFjuEBKeXB :(nonnull UIImage *)jnijYYfKRLrxvMVvnfD {
	NSArray *TcfPeWtlUNCENdRN = @[
		@"HUFzZPumpIByWMyOCHpaKdsTnZcfHBfModCpiqsaSoxtcslrcWZYNiRCZfBDpkmjnakzikEWwYUKocLiDWhYJCbrQYNFoJiwYodhBObMtXMWlXaDZvywTTBycXy",
		@"FuCQIPVDNLSLzEtOrhTXNUrIbsbTcRlSGiekhSOTQgHspSKOcwjyTiciAoidgrFIfXYlRgFappfLBgyJbMCCcmtTABzsSXChfmpFPEHzWXUbFWWwIeuIs",
		@"xChgjRWFyaswkWVyXejEEwjULzIQOXkDyNvYlAEpRcOiQmjwqsKVoystBDqHqRWWzcWsyiezWxdAEzivbDJUaiBSdcMWyutSNocuyCkftDOTDWoWofHJmiri",
		@"YpJPnNfPsocSqonosTWBxTwJvtnGZZDexpKnoYNbxpFqWlHphuCNzqIisrucLysBnSebQtSPouldlLMRhAetnXqGVjrDPnuNGBKdzRHVuqLyJDbQwueoyVpAuRKTFNVjmBcGaBuhy",
		@"dmmeHoIpCGPnGvurZBoLFNlLfJDwMIPblhTJcdkAZgmyEsqFVzwGDkhTfKXNdslQbJJhcDYfDXzfaRuPxUTfzDXcoKxOstMUyRMNQdpVXrxcPcHmXnyfDQWlsxENsmAtR",
		@"eYsWhuiRRzJjodFEMjFylGllKghNqDhTUWBGruyxEwwPikbPfSHEhmdgMzJyNKzxouWcueoVhHZroPyXKtKYSDKHIRLMGpWIToiDpDKaafuEEQTvIvEkiIktYFZ",
		@"GJvwgTNIQxCFSLHYDJfOClxYdIbbrTCHXrLyAPBnXbWKZSBQTgEdpSFlLCeqZYtGHKyNSZiBKUqUFtlbpZDBsmaJHyYtHhdIKwfOHkQJBPKipqljs",
		@"tJfVLzRHhcKrWcjbcZxlhyLEMermUYdxXHBGpNShajRkdWWttksdFXYmkFhinPEBqCbbbCXvjgVRJKoFOFisBYUYpDDPvozEBxUYFGVBGvFFdExriSADQNEzKNOoZXGaxGCxnASomY",
		@"KpPLXESRzNCgJMtOczyerwLKLlUjrMTvpXllzhtfPdfJZlvYOzSDPcuhDkOnefTSUuYQfkypqoLDEqClfDoSEMhQtrRlyPRYNUzpjwRsazhgxSAXPDGdIa",
		@"SAnhylhFLJLZsodvdIqXSVgDFJwvGzFWlJnBUfnBioLvUGemCBLYZIjWmLNxUAkqdvIhwnsRpSXiNdLDUToQoqwUBgDAeIhkdgkqCSPMIwmDlTLIpsbbNxfpaLCkKMUOgYGXoBQJBXBNwMy",
		@"EaDhKOmvjHKYXvBALKmSELVxfZdiVfHMbtgkTrTuAlNkJnKPBKyfTgStHygcBHSmKDKbhOzZiArSFeKlpMYRKLwsqbWUHEjbtaKPVXukgNDUzhufhIhUsgBizLNlnatk",
		@"hYCVDWcKtcThxovxIKPWGnHRiIkBeCaTEPkdaeDwWgQYwZBzdywQNWUYpzJuPbmEIuKIWYrkapvTRgclsjmLZRYPRIZYhYaYvpjZ",
		@"lUzDqGbNuBDBXCKhtZYrcnjqLfdSFUwrYpHOmpJeuFNSueqqtUhcxbqCANmGqjOHNeUOqmXvtzpFLcyyRZNOmLRXZihYUaLsSnvdBntbmVNXgnqOl",
		@"DuzFXNLuVFdXMivNgznMiqLgNeUmcMhXqoYEQzmoGpoOAblMpwJJCIrFhrEOMlBBNRmGhlAUXswzqycgVNemeATEUvDtuglrSRBuumegsrfhuCwiZTmhWKOCuHPuxiQq",
		@"DwjOInoCbdcfItWNbXpsiaafhqLQiUwUfONtumIYkUeDkLYLKrfxGaPdNJUwGEvpIMGWXatVdqUNHxnASikRXSZzUKeUQOyAHWBXlSpOhbRXHYnBfhobQzLhcZ",
		@"fCaHReDBDtRqNYVfnBKpiRDRziNukWkXfcRmnovoXflZIwsasJPYbEeqlYQYLBNiUjLlugBkFsRdHajtpWxaXhweBlsnZPUFchgVHTZUEnBGRuWeThyzraaQWaWmQgzqwka",
	];
	return TcfPeWtlUNCENdRN;
}

+ (nonnull UIImage *)OZCwKPYBJNtKb :(nonnull NSArray *)mmaEVZiAcEW :(nonnull NSString *)utRPATQxjx :(nonnull NSArray *)BZoRivmbyyPBDC {
	NSData *GMjcoCOvKQuyYNPFoS = [@"AnFkYILiBqeNvGWwwPAiTmtlcBSYBNrfurJxYPwmwiLkgUaszFWMYMwTZsaKoKCGWmXbpMcNFYNLhUgHVFhePxNgvITtVKrYCjPSGNHHeOkPglzrUPSexmBOneltldMfvOPsqCplROM" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *YXEvzJVqbxlupGS = [UIImage imageWithData:GMjcoCOvKQuyYNPFoS];
	YXEvzJVqbxlupGS = [UIImage imageNamed:@"QRVpaHwRFzEiFAvjjDnhISRSvBQRdiPGhhpjcoLzCtjOhjzbWRiUhUgaBdXnzNNBfHptuSxPccWeWFVHyFJppCPHrMmVUaXpkcnGoTWGuWBincOpBplMqzeGSfNDVd"];
	return YXEvzJVqbxlupGS;
}

- (nonnull NSDictionary *)MSMSwNFwnzRxs :(nonnull NSDictionary *)ChXbFwyuaw {
	NSDictionary *NqcwjlLCmCLXWDzdX = @{
		@"sDZdPCApmtLONFQo": @"NSqAoRTaWFKbGAZWEGpRqCdQoKBKPhfewTOblNKOIwsWjJJvjKAFEHFrkUTMpGCGPvZPZnNasBXvCAwYncInIRxIFpaZRZbPgibBbFSxqIOilEQpdsDmNyntWQBPQsTdbJeUmfPibYeKY",
		@"GuwncAvpqzRDvMrP": @"eygtzTKODaFeHiqqwyuyuxCZPbEZqLfusiYrhGMtfGbStSETmoGkdtebVytjramYkucQFvHKGFhunenbxbbeeSwiOsPALwwRPFfNsfQxZujwiKLAV",
		@"HMHywxnnkqMeH": @"wpjpJjMRtxZFFDpVPaDFXgfRkuNPhsaExoNbKKIKaNOGXcJemyUomnAJUvCaTrEloNsvmBAOsReSCpkuYzjhTDkCdpiKchvnBQrinAKsKShdHhzZGLetgKSbPMfCbWhWihLQtCy",
		@"YnmfTNwGvZRcAjPW": @"TFPogcceGIKJfPjBlfIUUXfoBqvjgVOYtzSRbxbaZOssVwJkPHjGbnkfOrSjVuYEvsTCXbSjLydcVHfnOyTfyHFxajtqktqpfDteYXUrdEpOryl",
		@"npsfIYuKRSDGnWiE": @"PtHLGFyExBQyDHlzlQVoznOtvDpseGwUKGMWZXWrrNcskhiuTKgHGzLzAKirdxtMQyKIwgbcQrDBFIUiLJpYTIRKxLneeNmcOepd",
		@"ETKqOSBxXuzBCQYJLrl": @"KWetMmoDFSLjHBNHdphysCbJBBiLIWXzEnOgZNADnaDkvJhrNEljAugkZTsgHOFLmMZUOUNywdssiPItHNPIeBaHXCjIUgMMQosLR",
		@"SGKwNnvMdPKiK": @"OEEOtOZqnWhcpMCxCexoYhfBzJWfcChijLRpIJPMVXGBnLYCUtrzyDJMeyQCGWmuToUItnqavAmlCraMTXQvQpIfyhwUlmKvGCcIfCwFOO",
		@"oHsqCFMFeS": @"wnCOABZrLljNHcvxXGADxrnlsVvURzxjcHWtYSzHVPPmBiBwsesNWRjjpyZIRvKzImslGZtyuzdDkBTzvsICmQBqbmfzIlcngxLbVNZCfKdj",
		@"fZIcUydUDMtX": @"irtEbnJMuMfPOBGJhBDOPXlPhhZrpBbVyGKiykhvZchpFNPHxFkpFRuPJJwmRxEVbDbTqSxOQsBCeWrlVcdVdJDGlDpZASziipSraDOnDlHdoFqALNEIohzwk",
		@"WmEaOjWwUQJRdnalUHc": @"fqAYhDYuiZBlmXPgxYXrfEGOlElmKuIwHccsunXlAfKPbRousemIzaDIDoadWPIyUCFfJLIipEcDpiWqERYNwNLUQkIvWuzFeEBJNOea",
		@"jVdZyEnwwKFFcrYwqCj": @"ZEdzVtSqHrhHzVykjzcMxDwyZZHaezuVtyAPjXlwkjYMUYajKwLrcKszGfrcLUuksugKrMDYSRooFTHrSZAuPwWyqkoznLiBwNcvlPTOJBLaxlPmxKcaYgyehWdnJWcknx",
	};
	return NqcwjlLCmCLXWDzdX;
}

- (nonnull NSDictionary *)bbvkGMVVwDtPZw :(nonnull NSData *)uARCJfNHWP :(nonnull NSDictionary *)psuHISDSHoSj :(nonnull NSString *)HGZWiCclrcJUTBsY {
	NSDictionary *ThaWZQVsipAZh = @{
		@"uTANhRxLQr": @"UNTjgNbNUOnQkWKqBiBwlqqvIAovKTxjLopsQDwLmdMdEAYvbUoPOKpmdVootaMYDqohegaCOHEzusgSVRPkoBMujPwWojeDPlAfPAvCpNZaTvTJ",
		@"qzkoLJggfmOwPia": @"VkZsyfcGSnbbjJhwUGNuEKcxGdnUEQLicQCQdgxZnCHdPSMZrrZFqeVcXGxcyrxlASVWEySzYbsNaahGlTMahGMKLRogntEWMVRQnXDSOezlOMrYVSAOkCWwCXTIZ",
		@"XGxBSTjMbcdf": @"LJAlmoDjfdFMopSodOkDjnIPnDsXwzjysZQKKAmMZIgEYvndQlynbpxeXPFOUsgsbOolNzCNSSTmUmYcMeMftRjSBsyGCEQBNsZCGXaJ",
		@"yYYFGSzwLWNannePCD": @"huoCnnWxPsUJFgtFWyZvAPJFiNhizuyVeiadSxqPzSXCImAIUXodvmaqpSZjccllwBjXrGEuIeEMVeqXivyGQClApaYAKBHFSsqDGZJRDOTleMvzwVzhQpdfuNuKdaIaQIShkmZeMYAesiqQTgUP",
		@"IuVwANvnRw": @"AhQRjtQODJRtpRfPyWWrLfyyAnkBImTyoGICmHQtajycdGxVzyBPQIQmiRGvfLLjntHaWAqSRCqHQWCMlMyfpyUvJEZhMfDsPxOAzja",
		@"EHqrwVeXAlsz": @"nUNGejdRltvcJSgRqTbrTWzEgFxgFfSjZgtjnjeyBzNETMqffKlnDVTsWKuMLsdjKNbtiKIHxtluBryfZQTPKkZlaYpcpqVrMxGUVLLCfRtuVbaxfBKCAmmpkiNuGwTdaEnfbmeRFrCzw",
		@"yvGCtEghTsuvcVooc": @"KhYOphGWyVcytxnzKrgwNASHLJRCfjJNqfQWFXqDOLInFGOQIGqYAoOaSUBymtHzTYCeVlhVIkWysHBCKIEFAEVqbEdexMYHviPRaKTedowdUJXJpyresYbOimyJnmrpFNugefheqRdD",
		@"NXWGMogsBuDxQlHRff": @"NAVQAqOstPShtVmtlhSZFquUnROdUqYKFvcqcmMWHHCAOirtoNtmKwKIeHJMEeDQnEjHCWWtvZHOBVXvwYsvLsORWIGKRyEJbTEvDQu",
		@"nloDVKxIouUerfc": @"WvcOhyjklclKxNbEwOreucOQBrMeqSuWtmILKwxfuRChmmfSejhJuqWKOSqAUNuTwBVhCJtenGbyaxaYqmJoekMKvFGBwvEUhKLywowaqCkAvIfHfcNjZkKgMzFxIJQQbaNCdHGV",
		@"qgpryGhWOyeeNv": @"JAdPQemWSTYZPORBiCQMuwwAPGArsOSnacdKxAijInRhOWwgRmXHPhNMfzUiCHajJJNhLTpEJmgSCTQiNNfxLBOpMSamSJsWFbqctwwdzSEbLxwpnErIjAidyxKYvLImCQZQplneBJTBL",
		@"ypsCMtFLYERhnCy": @"PjZKnrHDabrPJsKIKwEezMIXGGuTOTBwyDRLobTUFONWqjodIGbeDlhUmMVVsRpTNYuNtqggKSXgoNBcVnyGFyFBAXBFCoJgXHTDskoxLDstIVlEEgCKdNDEjPhrkufBwcwQNuGY",
		@"pjZjzOJchtzCNlLEFws": @"ipSVELVaqBtMKGUUooCLqKjOnmtqkdBUCOfJSXFVMAHFGAnpbUssrvlXxizDmHydhovtUcUTtKYkiPQQIEElyJwtbcFnGDWfOlLNMpZxlwHQnMairzuew",
		@"BSlGmEneEDumTR": @"ImdkmCibcYPmYlUEqiAhqJuncIFpHQkeRqLayRbQikweleykWqxXjSvZPrOfvmSiKVmOWpotmDPRYZtDdUVUucznEMRDFqMvbVIfvcdVkMvHhwkamz",
		@"FKlBwXUSawGKnffuoS": @"kgUKjEWypRgMCStIpefQbeTYMZheVIuukhJJFDAlDACpKSxiqJxcyFjGrzsuYbOqJhtgIMSpjaMBWNYZOjGHtPvKYdByKeUQLyzrYmuTZDZPAtWdbDLArpwEEmjwIZbaRGdQePqkvIRVGDW",
	};
	return ThaWZQVsipAZh;
}

+ (nonnull NSString *)pShliLJAbmj :(nonnull NSString *)LCPTvRtqvqBXSG :(nonnull UIImage *)jlDKtvuVgzJWvxO :(nonnull NSArray *)inXAZSVYzStbd {
	NSString *hFPqrExPHORS = @"vkOcuGsTTQTpvNSEYpgtBnIEjghVmeYSzBGANAJjzqOXFjKVAANHewGqFuBXvYlrkLNjHgJSNetIGVzXxJSZuuQKxxftWfCLJtSQdopxRjEkvVcGRPLlDKwpf";
	return hFPqrExPHORS;
}

+ (nonnull NSArray *)OiBlxtlklIxYFrr :(nonnull NSData *)yguGBduZbfkf :(nonnull NSData *)JRtBJhptqsGMJ :(nonnull NSString *)WnDBmfVSSld {
	NSArray *gjkmaQIynRGYj = @[
		@"xpbzxQhvjxQgbAhfQsZrwzstVIlxsXJtbXQJBJouVmbzVKWPfEPcepCCBcRNFjmwbTncEWaRAuPmrZlWoZIFdJhoNetltopqCTwuYNrkXMilyuMppUisgCaTit",
		@"UHaWeJMDkuSvhXgeoNAxwTMNOnJpHsHFgIawxXlxJLogAGvXHFVUbhlGXxnAxnJplnnDJYOUhqhkJemdFWmHknqnNzvoDCsVzovjqKekZJiEihHRBegIeUCTSbWWTApWxv",
		@"oAxUJpbdmJmHHCmpqFvOPGzHQLNsyqKzRRqRhJXkmSztKIuUQhwMdqcHmqKbhpdITYXwohQbHkthwiRZOlrUPsxKuHWoQvvpZIBUCwZmcVEXcXBByYqNykmMZYCkkZRMTmbXjYx",
		@"ndPpBtEPTyoBdUVgJbnsZPZRFhKbdTvqoYwYKYapKlaugMwtaNBrDuxJQVPHApdWNCWCEnWsVWdAquWdowzxoPQnjNLogMshSaZuMyXRbMmUN",
		@"ecOhSsCzLpBaGbZUFEsCcRKYNQhEkcVfdDshnuResICsbebvQwjffAkKZFnpnEGcoPORxVvSkIzDWUXvSWfwIdxKPpYstcpWsfjGRiXUkLrKkCDezDsGOZVrqDNmxxdGtbHUKoUAEjRYDJDvTEdj",
		@"vXuVGgNoKyUxJVuaOVQEYQJEEicOmERKnEmiYaCOTCzoeLKtYreBqnmjQprnjjFCFWjuSNAMAmzTgPQeQlTrKGdlmDGkGGbLQtpgjNbvyliKvpMGzCHcEPqFRKDXBrR",
		@"ISvfpZVuosZEvRwuNLKSHWEvakZWOWPnppROgRrQGLnSkxYNQtoKITYrYtlvAKNeZgXGxCCekjdxPXUZRXPJqVSKkYPCeOrWidHrIzZBYbJlRpNPYuQbpfHoyINQWcK",
		@"hnoymrsKlQKVWAvLGZbtrLfEeYMQptiGZCcrIbkWAuSeJuqUtUTgkHEWTgAPJEKlxMnDxNgoIQjRkjOizhxFIAjgLHtdLpAXvLMFuOhhrrhUXNLdVzxztMNCPjgGTQAfKaDrXBEjemVhEu",
		@"NTAGBrHTMMkZXgfNIOSIYomWLqrGseXYpltkHJkVdPQwrXTgiNucEyKHtZNROOBOWNrUMowUsSMFpsrvTaxbQkZsGYuQXklhwHEXQnlyfjlzTwXkYSrajAWmTO",
		@"kEJIzFdogBuaItvlWiccbEIYSRABaWqakGKAiVLgbiPqUkNpUZXptmKIscAxLizEJWKqQlSKarNyXcYvgljakHLmqJKnEITxtwOShnCosjbcUGESTXNXxNJfYp",
		@"SkCyqCEZjeqYXuAimlaxYAzdMAdKhKiXwKHLwZIAkHjgkACdNmANambBJGGZMoxmheIcqaaNcGApDvztqBOTlbeJWxcOcDkdUOigKhNXeETpoNISbyKabsvlSuTntlgIemwmBpuHUGbjRrJAoqzth",
	];
	return gjkmaQIynRGYj;
}

+ (nonnull NSArray *)JhOXTxXapRGoB :(nonnull NSString *)sZPFVsUfHguDvL {
	NSArray *xskasvOpXqiaft = @[
		@"TwtkiiEfBrKHIZdycsacHpGUPIpIcuXkjhhCpMJaGTEBuTSpTKteYzCUfnHQodCVyflBIgOnyOqzCiXeyZZSiipLVRHJCypOeTxupyEzOLdOtPodKpSsTvJWfvfXgWxxapSuMaLNGMtpEHUD",
		@"YTcBCwLrgfyCOTGsKcaKtVaOBkPXqymyUemBfTxltyNDcdaljEzkBDMXHUdOgnCatXNpbPWbUNWBLGIypjQxvYaixfiVGXmGHZITkokTaYY",
		@"YDaTrxbKQSuVjmvHkINqgafRQhOeuFChuMkpLYGxsOcvaeyOhFKBYUWZKBJyrbLVmehwgOFjFgoMdTwxgDfsQLsNaPLfZBxUlrKfpNNkcKWVJxuiXFrOMEgrJLFABcgrNeGFvLAgWjuZg",
		@"UugeHmFByDtAdHkUeSAqdAurnjMjDntxiiFOfiSganGCwLRmSLkieDUYQwOrRELrciGHkhanVFdOTZcCiIbNLeAzbPmXWYQlCKhrsAYQSqnKPvJgyxLWxqSLhQEhFQOMwz",
		@"yAGTuiyWpTDDtnXzlBVMWIVAUBFOXDlYpZcNJkfYcagWoWhrbzitBRXHvMHxkXbLMCLCOfkSWwvugYdOohLLwUIFaYIRXNCcGCNzxsxoDPZXmZBiMZpDTBoqiVoFAdFNUSpxHzocgrxKDyB",
		@"yMqXlehwwQbCftmHLNXDLOFLhVtxWgBbALuVWTDdbHoNBMLhMoRUmtDzoslsXUdcEqluQWTRnvwMYgRAFcsAregmjZefSQzRmmFlRGpYkqqQHNJIuz",
		@"kJZGOHdIVTylhEhfeWWzkAveVqMCEmmTFSJkxuZiCQlSXtQAyTzXmjsbsMrOvqBobjOXcntKNmpmStdRirTrHbeexeowHyDbcNlOrXGSAFqSZYZMYIsxHEZYiKaXOFYozxrdkUWgHEnsTOF",
		@"vUiGhVwjzYuFlpdJHPELDjeOUvdQWvloCZzXtjtLwTqUPqQnxjAyRtUpYewTzVzJtughPUockgPBHHPqteErdFGvesTSNZlWstbqjpabaeFCbIRzUFvzepDfksBvpMIyCxVKuyN",
		@"GclPxHtgKBRiJhwCaZTFNkYESEMPmsMHawNVQLjmWhIGJLnlMByqsJPFMHMfZwjiPznjgXwxmVeIdHrsHCnymUsDxVmpcZtvMcfeDe",
		@"BaIVsDXkcHvaUvuHuVtYOsWgyMvxusxSxmTyVYTdPQbMqtuSUDGPgXvZgJAencyZdtWqkZavTRmQYhFSUxDXVbXVvzPQmkkCQpjYQaEcDSYhDeSUaInACZjxhaRx",
		@"FSrTjewnjjaRYUkEpNfegsnxxrVHUeMtPqkKdUSkmSHlZhthTtVWVfBPdwZprsWINlgYUhGFTVwwwZUFcpfqraSvvDXlQZCOYqJeVhZUUBVQRuQPTMjwlqM",
		@"mOaMYpYGPoFniVQnZUDJpOLIxTrshoRKHXZJjhxXCkiKkdFPDTNxvJacTRKRlhtIBPHVYPGtldfGCPCyVMxuYDckuPoVZfoUkBTtxNfXOPjoiSUMvDIUTfgPsjP",
	];
	return xskasvOpXqiaft;
}

+ (nonnull NSString *)THVzJNZqKBaRB :(nonnull NSArray *)wvRHngNCEgFtn :(nonnull NSData *)MEXtgaLHvHtRUnX :(nonnull NSData *)OcsKZAIBFIGmM {
	NSString *yYECWpTAXcFHylyRBuE = @"sHUFUNkqzATUGtcihXmbAHdIqtirxnalRsOtqBBqJluGNGzSwUlTFNUJbufUSGWKhlObeLZlBgAGLEJMtjLtblnDXVbuQldLadSnnTifvZwZAEFIRbrjlemkjSFnPLXGUaOGQUEvKq";
	return yYECWpTAXcFHylyRBuE;
}

- (nonnull UIImage *)DGPhAfCTqC :(nonnull NSArray *)sHYGZHdEpH :(nonnull NSString *)WMaxaqRFpJtKVT {
	NSData *coXwAgKpkipOSsDAJzT = [@"iOczaAohkFYifwKyVTbnGyZAJWIhNJbVFfypGObulliqifHOREpKfpwaVzCdVGjBKtYuBkcEFVZeyFKMEtfjcIafBunJdVXwwxcEUzrQKCDuO" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *UlPSzovCvucYA = [UIImage imageWithData:coXwAgKpkipOSsDAJzT];
	UlPSzovCvucYA = [UIImage imageNamed:@"qAunquexXaIuHHaCXNXxWYaEabjkdcmbsxKOOYQUQKoChIHYuZUjFmutQxSogRQtlLNUDDfLKVBWxIgvhRxwSYfrXkgvDsKIunSDgUyFyLWtzSaJBxZVvhiGHcUgVGyiWSTUnOlZjiqd"];
	return UlPSzovCvucYA;
}

- (nonnull NSData *)CLLRZPjFJsoAO :(nonnull UIImage *)MESnJJgbYMXOJ {
	NSData *PHOgrqegquRLUGm = [@"TxOppOZEomaWGjWABbbUZpVRoYJYoQsRZhNPYKbNPlBoGkaRTgOHoMCFLkWNvwMMEiTvLtmzIRpVvucIxIPbbMNajYZAiQpHtrojdNWSavHNeKWjWuOIMLccPiCupDzrxmPJQbrGkMeIY" dataUsingEncoding:NSUTF8StringEncoding];
	return PHOgrqegquRLUGm;
}

- (nonnull NSString *)WqyOdzilbHgyB :(nonnull NSData *)sgXUyuTPZnuy :(nonnull NSData *)yBHjuJyMaRkbXrq :(nonnull NSDictionary *)FiiqWghdkkvE {
	NSString *uwNZHgWbYmbeKsNaKN = @"qCvyLzMgAsdvmbpCMjgKDMEmdjkRiremGVbLHFDERJHNGEELxrylNsRODwfztPTnzvnEeyXtMxuBhqcWmpVuiakGwlgfBNORLZnsfvqjgCapzWCNkhbrtWkshVumPamjYeaqZgCriefPfBzotjZZL";
	return uwNZHgWbYmbeKsNaKN;
}

+ (nonnull NSData *)OXTacZDkGoMcfWKtes :(nonnull NSString *)mIbUUHmFVkL :(nonnull NSDictionary *)SEuvCKNaawWfm :(nonnull NSData *)PNWHYIYdOAWIkUkrDGL {
	NSData *CbFOJOGclsujGR = [@"huYqVWdpZyVuSsLsxpdEnFcvqXOzYFijLIWchaKdykHwfIgbKOfxRgSiBfNNnMIGOlRVCVAzzXCaFNhTNjfbAFqEzVGatAxzdiIUzSJWerCsjdiJExIkKwRCHPGRyLCXIiZPfaWFr" dataUsingEncoding:NSUTF8StringEncoding];
	return CbFOJOGclsujGR;
}

- (nonnull UIImage *)trXyIamJcSLYhdGV :(nonnull UIImage *)vPUWszfmTa {
	NSData *ffBHDgNpNEmJlV = [@"TUuSvAVvkpgDkBNmOFIOyRVEoEKhTIddeuwmhzOKILKLMenvZZqoRYiySUVImPtQYqIMtEEVoiRdlPdbCqfxVaaFxNnrTFfBxkXe" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *YbOEtPfIuntrKUuTgjc = [UIImage imageWithData:ffBHDgNpNEmJlV];
	YbOEtPfIuntrKUuTgjc = [UIImage imageNamed:@"zEOyjaNvLTzyieNOHxffAhCuRaYzWYjCEuScsFsojsdVlCEgpdXCKYrMctFkfhqmwoLDvMNvHurkxHyaDlpzlAuQzltVgyZlLqVGzdRqZ"];
	return YbOEtPfIuntrKUuTgjc;
}

- (nonnull NSArray *)mgvgKsBaZRSyheBKEK :(nonnull NSData *)PKPoWuoooANuqZu :(nonnull NSDictionary *)cgzpwRjzOPzPjB :(nonnull NSArray *)AOqqApoEgDmuYcIus {
	NSArray *SJmfSJnWYMK = @[
		@"YkQMyVdWLghIkGKxoEZnNZsxIFwQKKrsqHkRjjWYpzLERzPkSusKPQhupIELAhuOsxsVoCbpVIlbJBrMBiAfsuDHsriemscoMDAdTuOTPWMJGhjeaYffrjJUZMkMqdbfWyDNRHyQdjl",
		@"JmsEdqxMHktQDOHeGrlKZYzeWkSnMnLnqgsMEPdHMrSorBnaAhHbbltDhscGgRKanyvEndqcIoQlriIcHQIZYAGhXrSRcYdPszokelKmLDYdTAgVxXldjOby",
		@"WLDYLzRViyzBsFmhAvdDGKVYyDNvbhIpKWVzUPWfCRxJprgpmLgmEUpGlUwsGYewEbWgdXbncboYtPJGHYUgSXgaxmfAbLEoVeMkZkwIgFuoYHPEyOEgHLnKTWPogYqxGIltXNTCZRmqJmUzjpD",
		@"aDlpPOXmpegMLeCDLGohdhyQraplsDXlfVeYyRLMMuMQjmaONCIscckblVdTjYgnwwZHobPMONVnwAUtpbdwwPWmrSAKLLlDxVIHLGAlANAYwgdfBchmYQQfw",
		@"LLjtFypKtzxXKtTTJyPyEVakMihXgaetVfHDTIUKDCBGxmAeOpIvCmInEUdkUXzvHgRBsFoZixhfymXmvqrOpBHXJXWfruLEHUvBkQGWJRjcjJMNIzbaUzwggcfHj",
		@"riNAmXyJMdALlAlWhRPeXNQyFAlTblldlBsIuaQohVgNBAwTcxEBELvBSzHLKvQyzUUYpzeveSzeoMZPwpAExRCpFFBZpnNQDyNzDoaivjtKmyyqyUNnmBCwuKZHihXgNYTKFnMW",
		@"zhVgMQSJuzLwqvbBakabQsNKjvUGaQCIxJxPINqStJDIayKHQBTBVmDpmVSZTizDeHgRVqnjOikauRbhXTssDpqYUqplVaENZbcBrCKHlCICseKUrkRnwfblmSTE",
		@"cdcBYxTmTcKGokpmqDnKykgKWsmYbbmNYqetnAitcaAIhnfKPxFVEyvhSdXjgLYAhTDEvlgUuDUtKkBjFEMZWdTQPwsYNMMuxqVZaaRBcYqFBDYPfjzuKJHatQcPaSeBk",
		@"ujQcXLazkCvptqwBwCWjJxWxVezWStJtPXccSSTGRqUrAywCBtbjoBGOQHBAdnHcvWAvCdUYJMYCzMlIJuakJMrphotAVbpHjyKaQDzhmTiMCXPymPTWiPJJwft",
		@"JIZMAYSZvCrxoKIRyHYLsIiRaaROiUAvVDYqysvSbrActVghKpDuzJFHEQlrxulIcDjqYfhadBOdtLkMskwbmSmxehqBHeoznwrLjEHiNfI",
		@"oSlWHJuENigltwdymXYZEBnzcDiVIwiAMPguSyoViUcsIbIBtUWxVOKpUIwUGZrMzHonHuCNJyHcKtflkYFJwVAsyarNJCCALqjPDEpyyJwTLwwaClDNDOSZaSIMRUXbUnkJBzNw",
		@"NZfJGZjvefwzUQdjafxksDjdpXKhhgVFHgzHAwjQCQzohRAOujLyGqYiMPxJEAAHJrzwDglDLDuUULJKNYIiCIBBHRGMusKyNinEYrRWvDCnnHEtkCwXCjnbKbYDImnExQRmd",
		@"ZNGchEPSdNHKasaQPxOHuFepccALCJzqvjsKZzhBEXuMiZYiDpHxjpXpPmgTzvuuZgIfiLkpxyIvOrlaFXZHyzDacKOlmgcOIkHsWQCwfhNDcVrKxyvWIwpGTnrHdULh",
		@"mDFLrRPxQzoFNCklEaRvqJHJxoPNdVgDOjaWwyeGwDJwnXktwIpcoWIJShBNwdHYAlRXwcUsdyGYcGWHVtMeTdpuZmMghaNjCUWVKaezYrDiMqXSkVIXMwnNjVUUTtgbrrbLJZYBQAQFYrYaRBrf",
		@"gtiqLaQbZItVDTYKRvyAjXVzfKtLnFFsLKfiyChJNVGEFMCVvKOsIoZwOXhoiweqDUcIUybOsgkoLHfNUuLyPCjDAGTYssvNHzNgNKvpHhpYOLVNeblIrJArduSdKafPwSnYSALsdLTTsmIzx",
		@"NfIaPHiMZisdeecUWGxmukzQaoakYCxlbytvSiDpvDqnbSPJwyKqyhQAxxkSOjBfFoVtNKggUjPAkzecDTHAssfukzFtBzVVQiaAvqr",
		@"wBCNcdlXgfEUzGULdvHDtxxWVDPDkxofVGmhxldTSMZdGhLZQtTaWJlSZsEqjdcmdPYfrXTkYiJKpRybQJQItfJrJLSueukJqWZRj",
	];
	return SJmfSJnWYMK;
}

+ (nonnull UIImage *)evXplUbElILKXBeWb :(nonnull UIImage *)jlerwtWsEYo {
	NSData *bEbROXeneWqtyvARVT = [@"ywxIFLlUVACJUhMIpEPwSCuazFIimUiwDzNKxaHrBlyJfpxaTWJArOtxUEFAOBodzknSZsBXZZdyagcmqLqmNzXiSQCCFGosCdvXPcxUfsPiHJAZSzLRCPcJyXDkcEquUONuNoIZD" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *iEREYpmMTP = [UIImage imageWithData:bEbROXeneWqtyvARVT];
	iEREYpmMTP = [UIImage imageNamed:@"HAIKWMvcWUSnzRMuFYeSacBCvBLDncqPVlzZOKwcsQqtyDtfEOAHVXGpXBQqNQzoKMuhNYatFCItEVvjJvxdoYlzAGuNJNkHHCKdDchQNNjd"];
	return iEREYpmMTP;
}

-(instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier{
    
    if (self=[super initWithStyle:style reuseIdentifier:reuseIdentifier]) {
        
        
//        UIImageView *imageview = [[UIImageView alloc] init];
//        imageview.image=[UIImage imageNamed:@"common_interaction_active"];//尖头图片
//        self.imageview=imageview;
//        [self addSubview:imageview];
//        
//        UILabel *name = [[UILabel alloc] init];//每一个动态显示的label
//        name.textColor=[UIColor colorWithRed:154/255.0f green:154/255.0f blue:154/255.0f alpha:1];
//        self.name=name;
//        name.text=@"发送消息";
//        name.textColor = GreenColor;
//        name.font=[UIFont systemFontOfSize:13];
//        [self addSubview:name];
//        
//        
//        UIImageView *line = [[UIImageView alloc] init];
//        line.backgroundColor=kColorGray240;
//        self.line=line;
//        [self addSubview:line];
//        
//        
//        UIImageView *deletaimageview = [[UIImageView alloc] init];
//        deletaimageview.image=[UIImage imageNamed:@"mine_delete_friend"];
//        self.deletaimageview=deletaimageview;
//        [self addSubview:deletaimageview];
//        
//        
//        UILabel *deletename = [[UILabel alloc] init];//每一个动态显示的label
//        deletename.textColor=[UIColor colorWithRed:154/255.0f green:154/255.0f blue:154/255.0f alpha:1];
//        self.deletename=deletename;
//        deletename.text=@"删除好友";
//        deletename.font=[UIFont systemFontOfSize:13];
//
//        deletename.textColor = GreenColor;
//        [self addSubview:deletename];
        
//        UIButton *sendBtn=[[UIButton alloc]initWithFrame:self.frame];
//        [sendBtn addTarget:self action:@selector(click:) forControlEvents:UIControlEventTouchUpInside];
//
//        sendBtn.tag=1000;
//        self.sendBtn=sendBtn;
//        [self addSubview:sendBtn];
//        
//        
//        UIButton *deleteBtn=[[UIButton alloc]initWithFrame:self.frame];
//        [deleteBtn addTarget:self action:@selector(click:) forControlEvents:UIControlEventTouchUpInside];
//         deleteBtn.tag=1001;
//        self.deleteBtn=deleteBtn;
//        [self addSubview:deleteBtn];
    }
    return self;
}

-(void)layoutSubviews{
    [super layoutSubviews];

//    self.name.frame=CGRectMake(self.width/4, 0, self.width/4, self.height);
//    self.imageview.frame=CGRectMake(self.width/2-80, 15, 20, 20);
//    self.imageview.x=CGRectGetMinX(self.name.frame)-30;
//    self.line.frame=CGRectMake(self.width/2-1,10, 0.5, self.height-20);
//    
//    self.deletaimageview.frame=CGRectMake(self.width/2-30, 15, 23, 19);
//    self.deletename.frame=CGRectMake(self.width/4*3, 0, self.width/4, self.height);
//    self.deletaimageview.x=CGRectGetMinX(self.deletename.frame)-30;
//    
//    
//    self.sendBtn.frame=CGRectMake(0, 0, self.width/2, self.height);
//    self.deleteBtn.frame=CGRectMake(self.width/2, 0, self.width/2, self.height);
    
}

-(void)click:(UIButton *)btn{

//    [self.delegate sendMsgAndDeleteFriendWith:btn];
}
@end
