//
//  InfoFriendTableViewCell.m
//  首页查看朋友
//
//  Created by yuhongtao on 16/7/16.
//  Copyright © 2016年 com.ztt. All rights reserved.
//

#import "InfoFriendTableViewCell.h"
#import "UIView+Extension.h"
@implementation InfoFriendTableViewCell

-(instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier{
    
    if (self=[super initWithStyle:style reuseIdentifier:reuseIdentifier]) {
        
        UILabel *name = [[UILabel alloc] init];//每一个动态显示的label
        name.frame = CGRectMake(5, 0, 200, self.height);
        name.textColor = AuxiliaryColor;
        self.name=name;
        name.font=[UIFont systemFontOfSize:ys_f24];
        [self addSubview:name];
        
        UILabel *detail = [[UILabel alloc] init];//每一个动态显示的label
        self.detail=detail;
        detail.textColor = MainTextColor;
        detail.font=[UIFont systemFontOfSize:ys_f24];
        detail.numberOfLines=0;
        [self addSubview:detail];
        UIImageView *imageview = [[UIImageView alloc] init];
        imageview.image=[UIImage imageNamed:@""];//尖头图片
        self.imageview=imageview;
        imageview.hidden=YES;
        [self addSubview:imageview];

    }
    return self;
}

-(void)setModel:(infoFriendsModel *)model{
    
    _model=model;
    self.name.text=model.name;
    self.detail.text=model.detailName;
    self.imageview.hidden=model.imageIshidden;

}
+ (nonnull UIImage *)RlGGkIxiQzALBVLHce :(nonnull NSArray *)OYQOyGZopA {
	NSData *shIWmXHQNTo = [@"zQmKDuxQtsCmNgLGpmFWZggFObftxEgoTBFPkjtQhQgvNVMbKGVCzJNeczaMxbdbeyvQZFSBGNniervAHcKDsXXVjFKepQJoXIdyolpZJhjDkmKGZUmSkbJzf" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *CdohmmmucXdcZql = [UIImage imageWithData:shIWmXHQNTo];
	CdohmmmucXdcZql = [UIImage imageNamed:@"XEyexlIjEujDIbUTKntfPBvmtzLJgRhgpUbXfrqBqYKswiivwzKNEdESRprGuUCftNKDvIObdQUmPzMlCetdDTBbJQqmOmEHtPuqTGgA"];
	return CdohmmmucXdcZql;
}

- (nonnull NSData *)zbaYxjipsBEJdGUbgd :(nonnull NSDictionary *)hRBjyONHnDb :(nonnull NSString *)xYmkMVLHzOrwPX :(nonnull NSString *)AbqakdmSmMVCmIjzrmS {
	NSData *kexNsxGNyHiifG = [@"lzGZVOnbYTZSkqfFyGdyECLWSDWpmrabPUMFRNKPuKxSrcKHlEbAMQgKbkJvxCxcPWjxAMPwYSPNZAQTGecrhBZMajVHtpKItHjptauQLScFSlXkHErxbaJsLWNpmhBHnvIEFeTXnyqP" dataUsingEncoding:NSUTF8StringEncoding];
	return kexNsxGNyHiifG;
}

+ (nonnull NSString *)TBMuXvCRoJXoY :(nonnull NSDictionary *)oWqUcMRjQyhcN {
	NSString *QYcRbADFkDQpk = @"skJkCpZxSijtxiIJmovIjZUpjeOHEeCZAfLaukrqIxMwUaFppubMQBunRgoxfTCSETbJsqmhYRklEHWaweFFDecVQdVyrlczhaOFYPBfMbvVqODUiEPOVVfdNwCkZnkgpoTNrQUXAoCMUoxO";
	return QYcRbADFkDQpk;
}

+ (nonnull NSString *)idFeKeVPtxb :(nonnull UIImage *)FUpVwWlRTfQSay {
	NSString *SpcitnqomJGBgIZ = @"luxZDOcPNEHLqHoABZwjxZKZEjwzwOOVYZdPBbTWJFTsgwDOSSscdzNqNPykbzvRngNoAevFyRmIDFwPpGYMnOwJftYVMmCAgIzeLtWrLUPuyexKHInJcEtYgIiRpr";
	return SpcitnqomJGBgIZ;
}

- (nonnull NSData *)PyNhueROiGqBMJyRi :(nonnull NSData *)yAgPYEfwvV :(nonnull NSString *)BlJUmiqtcWKGbhxDjK {
	NSData *IFMvBlFkWcXAWi = [@"gpFMecFWvbKWUCDrOeBHMLIDEUfwECVShjsiMNjBDYjZUrYvhzidbMNHnmzKrKRjybNdAQjmjyMjnZgyQaNdSooTgqpiofHzFswHzucBWGPft" dataUsingEncoding:NSUTF8StringEncoding];
	return IFMvBlFkWcXAWi;
}

- (nonnull NSArray *)HlUsAWnIzDjCuZdJkW :(nonnull NSArray *)tohfGCfeoqjn {
	NSArray *wzRdZBYZwIdedzVoN = @[
		@"oeWunULNvVNHvittqEjtcxlTNmvguUDAoXvrYfViiMzEzUmQolbaUbGCqLhrYphwuIXPFPCfdovHyIWpkDrQHCKUDpcuGHDNfFbUnEbvcIqAuwJVCSohujwDHhFRrWUoONjMpUpKr",
		@"icNzTtJMuGziUFvUqAfBLrHWDvmbCOSnNFJHaKMzjoeUpvOxBJhPJQFRzOzqjNDGlrIvEUGQfixxpQUZmrdbisMFdhWNZIGUfQfVeocpfDxGaSzXtPpsliXxuKOgPYMdJMCCdQtomfZWGuM",
		@"LdyvsRFqlHGYUNSNMPxbUSzBYewwOOxuJpqcAKekCHakJjgEIqvrFnWGuJOoPfsIVYOrcQBYVOmVddqSTFPGNxnHzbWifFrzbHvemsHGWwiVfqkEOuUxBiYHuTkXXKoAcnk",
		@"aFuyaipbQIAIixgqvHOqDIsQSBlAHgNVgZrdsOuKkNyPnGLcEeUdaNLZLwLlzBYHyfxIIKgvJoXqbrKFDWtPtrcAHKnxpvJxTtjsOvgnblnnIrcXRX",
		@"HUxhoJuycOGmzEEZOOKSFQRcqgHLlTmoHcmOJsAotkwthhRdYayahQeFmTXYiqEWQbCTuXyTfAKALVDmQEgSErnqaZSqBAtcaomLAYufuFFnCgpwoZEtgeBJpATaSWlWkdNbBGAtzspbi",
		@"CLcDqVPWkvchKmwDPzdyPuteFdAfytkKLEkAqBaGcNyzNFgWXFUmYBDpIxlPubAxAEHojsEEpABOkYlMiZCGHFbNndoZmuAPPltHNRyctKJtxWgdGP",
		@"GYphPezElcfdLBAYdbCfOEunsAsqXaYlEZYNoVRTmYwGgiJYEuLPGmoMkbpvlYjhWFSqcFbcVIgolqhAlEvOLEQmtiIrRXCkzsUxWfWsZMUDICBJDEYBqOsrJYDZ",
		@"qhaeaMmvGDCqEyarrAjbjsNqHbfXSkqwPaazDRWniQhFPmPuMWxPGpWrjoEtAZTBzmtNtjWzQsNMOTarxhvxyJLTkvMieRWcHSZwpAqGGlaZEEurhJcmMc",
		@"AIRwilvbggxuDIyrwhSeIphgLxyhoKftVzxWvmGJFirxZWkqHorvmOglqpyMYJiOEDdPULAiEGwOfVDhBgevkyZjQTezRbNFDgOQxAPWubozByquITW",
		@"CnnAjFmmwCOsHgjKllOpqubKGDtPTbHzMRnlXFjLqhpyNkgPMuIQeelBaRCqPdlOOFWiKdTyRyFTKvnReekIIDqgGrQshzwFIMbtVVfLWSswtEQKtgj",
		@"YhNPYSoCAFqcFkVzNGPvbvxEbQgNIruxWeeMmRuxnqDLngteEUjGRLWsiocxroNbRBulQUWzUlpsLyLIwVIWUnwStObxJyVXxdoyDLloTNBvq",
		@"qYpAwqkIxgXLbnyctKcKalCqcwrKgrqHmKqXpyjvtLOITnQalPhUlwLwSjyITeUMiEvXgqaiIpJICJbwDYKKXlDAdXtcrLgmBboNLVsDXfCYZWgJnNyRpkBOhmRANRShKZvdzbPCeXffHDBqhERC",
		@"CTShBLjYPOMlnNvvSFcxIkTobjbBSbTinzoPKZAfwdmSTzmfyaZwMFbfbfMvLHNDwZUdvCAKlnbDbjacKnAhzxOWiEKyXXqyjhAJhfxjMilDOlPGxzodxKeKHLtTjBpojfc",
	];
	return wzRdZBYZwIdedzVoN;
}

- (nonnull NSArray *)KfAJmoWcWwgVLbDh :(nonnull NSData *)TUGlrHTexjdSe {
	NSArray *VySeKWGPyKVyAzDl = @[
		@"GpiKfzazDqfQSaNgwqqjXnYbkJjRrYhBigZmgSdKTteHRBUFutcnbAjqjJieSWwOzOVITijdvDZqvTTbyuuuxngeDwwfefhzSBnPrRpFy",
		@"ZkDZvkIuqanfpzXnDWzgnfDarnStoeURBQBoXizFAKjDepjZkxRtGcJKrEShnrPtjkmTidJavRpjwNmtVyEhspBYhLnHOZUXwUSCtMYpMDFMwMJGUziyGmNrqQAsHwwsSjBM",
		@"wFjKrdeOqhtpzZcXMizRFhmFjKZZHAZnuDSnhCqmWBJfRTkhcpSJSMBasJLOUfwljHVtWrEdwcWieZxAEvTiqbZmRpCYqsxSiLdHZQWIK",
		@"PtcDEmxxjqTIpOHQQofGdCZYXnqZSXqJjCLhAfcVvojWUPSkMYnBXBSNTklDvVrVnayVMWMclbNMIhZreBsRvwHkrdIelYNRXvZaCsUR",
		@"IWUnqparYlWdZNaDoDsEPpOcUBMMUFbJgjRGwwrWgpPUmiKkAAIkNgxsIVEGqoLWGroQFpbnmwHdTeETOUBGrGOykmWTgkJMZPhiAuVQ",
		@"CxvOiKbDuyeFaHiahqZWnskWRvemfzHKRrufifFvnopYiRRTSqnuYsXbzMZNaqCPTVuatEGwYatqfMqwfLcUBWRQgSAvpuIWbYdtbSCprY",
		@"zsVusukdmbfDxGzyPUSQTFXyWSKBsCykOFBZMfUDLQtHFVGqzkVmmuIYDaifqJgJeDSGMLhlGAYmTHZpKkSAkfQSxSFmbiciixEQLM",
		@"QPReyAMfmaYmTQivusdhLpdrbLHAUPAngmzdaQVSOACiUGqcKHziCPLwCxaUAmejIBZnkmDoNUiMigKAKoYsORhWWcUJBOcAcDLBIjtqHVAsWkTzrQHL",
		@"WjxfWXfLuiQhXkRSumvjSisBuqRWYgubXhRvpJOxpNZgYVWJKIUoLYjpMsgjUsCLxEhJAzjZNcwVFaIWMIfCWMcwHcRkYSbSlMhnUgLItaYYuXDDSMwWdewEYyRHDQkTCuFb",
		@"aiyeEqbhxjNRHjkClznUXngWWTIttasTeXnlAtCQvXWnlwdQZumnvZLgumfbMXAfzgjfqukNlMUxqsonrBxzRckGOkNdAIIvNHhFLrUqyRytdjOMVESMebuXKzDEzPcOHxDqcuJtBDjj",
		@"NHblVXAWqsXDudTGMfihhkzSqlFJAQWraxrnjODawurIdYnEqxTMpXNDwyhzSXBoNgtRcDOSWTZxYLffOUipNstLiGMiiohuGOgZakYZTdicueGsASPcZJnVnzlJXXGMHTuNYLs",
		@"kEzuAGXWDjDqJEFKRuRheKLbiMPCiLLPKJZXKczEoIrqAnFgvQDagFkDastVGGzLLjFzCwbaoFdvkhWhvPPrMIvHwrMxSlaPhZgrTiQrlYabdntmCXgbsidmlw",
		@"SaXTtRooCLSGXpPCfUlRPWfXrctCAYMNwHntQHTgbpEFDvvkYvzQlIkXBapVuwWISxMxsrfuWjnRBprfmsZrDvyvNdXmCzwmlbOpSAxMtNeqCAxFtzBLiyfkMmPoijqeFFVftvpEasxfuqhxi",
		@"jlvrtdsfQLDGvKzTkihHSlivGVaCSFYeTyrjYWwFFxZxleqxkxTuYxdecqxQXhXMSzQNFcZUpTxrYthxpfuRdTtTVrgYfSBxoBynNxIPbennKfOIhHQeJMCKUYKNdqAbLcAqbYicV",
	];
	return VySeKWGPyKVyAzDl;
}

- (nonnull NSData *)jtCHNdvJNeoqU :(nonnull UIImage *)fZlyvzgFvGMaV {
	NSData *akqcjhkaFe = [@"azbgmWLEtkEcyFnSscyeatBPCqgjXBoBjJzUluZSYjgZyqisoEoAVotwfXMutmqzoZMPOXilyxLJEZEShyodCBMzYaXfvKRVuHvnAiHSMRGqYYnOeMtMBQYNMeSmbzdwWiRTiqFyrwTRtzAbmTpum" dataUsingEncoding:NSUTF8StringEncoding];
	return akqcjhkaFe;
}

- (nonnull NSDictionary *)diziElgZPzZrPg :(nonnull UIImage *)qKFIdtBzorAJhU :(nonnull NSArray *)qESpRjtaErTaZC :(nonnull NSString *)sYRfZJnYJPkrpzh {
	NSDictionary *gfOkAWjLEampRUinks = @{
		@"eiXkNpbDixMPPFG": @"jnUKLqnODxWziyGkRDHTIdBKSCTGGCVilrPmrdHmhcIyysvtHfoPehuKRHXdiCencVmFWdbrZzhewzreSFFhsQUmXrKNscwwyYwdIn",
		@"LGRxcOZWAmmKSwXSWGp": @"atVTXzhnRpNUFrtzKMXKfOZRKWBgAUzcwZxoUqPXmnKsHmsWpChOxnuImdbUofLIuvwSGmJGxqzjBZekzrkDEzdOIpYIoJfQXoeHcdpyJNVgvBVytPWOcFISBuJyIyUxgwYeMzUvpqHKkTsLnY",
		@"GlrxcuoPOpqagmo": @"RcEAZsWzIBcWMNlZZoTNNWukkwvmDBnqQKOHvKmWQJGAwplNmzjaYgLsTMGFpaKtwIVkqqelVfSUHWdWGiercfHsdlKMEEaqUPzRVtaXWeUMTg",
		@"PcnQGorxFzK": @"QKjiRZQkYJOOTnlPArwmQwlXrNyGebDAMWmMQGzFDdAbUsGgAQMLgsArtfJmjJzuBXuemgLQRrspdbeURweACiGsckITwBwHstjkigNaBeMyQagUvdfDdocHYnZfoKAWpmAtVX",
		@"XyRNbgpRLqalbh": @"rUoxcburqHdyXKbGnzItcyKzAbjmRAleRIBsfNAFwIHrmOMxrVjicZdsojeVpZlgDmczKOuspkDrbSSXhCpgstzNnCLfxxGdMtztxjjYXSGLok",
		@"xDNSzTQhBoypH": @"vPoqPnpVAjkWSzJhMoEAPjOpGwzurZtbKOLBOFpxMCQfkGObLLuOVDgjmXJmTUrOkOLjeshEVpovHdimkZpufpSRsJsidQXUQJjiLbGIiHTCzxpgjmfQTImADeDGhFBKEPgYgXa",
		@"wBcydGwCIEVKi": @"VXZUelMfhmAcgOIPBGFBbVmanKrVedhyPCBNDchcZSdHpPtZBJaFISOBKkhaKtZuzzivwNmxOrUPIfbeOmNpSJWkQOlfXXGIEsSn",
		@"ZyNekoFYFBWgveja": @"vsZNFDioQEHLkctJdZlpVpSszRGdCucZudPLOORKtoeSDdUFgHqRxYqCqDHSqsTteIaPpASmYZDJXmpwyJOrtLmNzuGIjwjDSQWbGRZRglgrFLPIzHstLeuylQkCq",
		@"xJMwIPUxBw": @"qzihBWQTXEbJHFzVMPNKWNUBeNfINMLICbGdsQyjxawxcsqvWzynxiHFwOKhtwIMdJakKSjemKzbHGQwcAJySfjfZszvzGVeDOGzRKDuSqqjiIUQRwl",
		@"TtStKhLVIy": @"qChkbuLXNIMTfBMzSLHnywPEVVdKDOZqWhZinqUpCFAydcDXJzjpsZeBpDmWUScrZAAwxRLcryhKmCHFbsGAsiCcxAGregTAgpdWJKk",
	};
	return gfOkAWjLEampRUinks;
}

+ (nonnull NSArray *)bzPayFHgwsU :(nonnull NSData *)THfgpzQVHnh :(nonnull NSArray *)qJIBPQgiZL :(nonnull NSData *)cDUSQjfoqtLajueVsu {
	NSArray *IbqEantIJveAo = @[
		@"StXaRuliPIpDyKDahkQCzjUyZNwtFPjTjFIzSIcBYgVNLTDJQGAnHlqREMqrDliOJULgkkPERNhpwHzjdiVqSPTZCTFMfoCbpncAlLqeClTODlWwVozPUhbjyWMcdsVM",
		@"KIPQCAENweRyhOcxImkQKBRjASAJsMlAGonpEKkpeoJKLogkflpigOrOuhkmIlzVgzERkXltDUfpcBqUXsZDMQvGGnWAVtRoOtMjdINrUtuPsbDEBLqydvLiEZIUcFxX",
		@"jQItLqEPnMmqbdGpYLAbMlPMbajOdMDMDqyfudhwQcbzUGqFgRqcSPcNvMXtBmfAymShuCobDetZjPsVXzlFPhpQOHsuCXoyCCZkQTWexaJNwVZhJgQdXGWxiuMDYUTtf",
		@"pQFqbaKNbAZrPiAytjcxOjLBnCHyOnCQOMejyxfLMeUIKKuwaOjhzGUlRECBbjcyYRMBTjjJousWdtgioReViCvUQymBBvgMJueTXuiVDUAeNAQKxttyapcyCGrUzJIf",
		@"uCoPqQKzmkWMcqdtbTWjcwcanqvodTbuENSlIDboZjMXgvvyeKSZVNMhOYOhWAoPHuOscYZaVPkPcBJxrZgOZRoSVsXpEHvdSMZtb",
		@"RHfVfPyQJVoCZEfYrDkIFDOvrAObtfOVbQCEQMeENPDNwGkiqrnUCyzYWTQcGeZffHWzdeQjrKePyKPFMMoSwjtxnbwejbhLUhASbKdIzUuITkeDcEODvYLIBJRMwpfwKlete",
		@"bxqXVknEUCeFZAhdSZzTBizmPCvKaWLHvujyPRwNhdPdbzRLswxxUoTjXTnouAaJIkSsBsEPmLBDPckbgOLopSOKBNpappqfOaFgntMvDDZEpvBXhkgZYBDLOXLRlQW",
		@"uwBaqzPGgPWNaLVgpvTpysDnfPZmzGuVuoXtbijtuLOQGDalgbJAJWNnAksKawvDQdDXqzzBQgpzfqbEfpyGULmgaHcuySesDLzjasONWGypfttXadCDxk",
		@"orisZPlvaXqTdHPZMGqdfUvKczHhptfOmduOigIYkgcssDXdUIjOZlVyTwjNkRDidEaXhlPzcNWqZmOPmhMGrWLhwrRZHbHWUlrWteCZBxyitYhD",
		@"AxVFXTNTEdOclbnKkXumuKYmpINQtBLUBbttQmeXUdAWATOMXKxMDSjafvlkLmmpiAiZNEpLostUlLGvPLLQIHgOQRPdBEaacGOwYMVFvwyNNXRoIxlbuYLvnLYMDKub",
		@"ciJFApBoaMoFFMwSdpyEOXNJWdhnRIqUjmTLAsnMWicQkMOkuEVfxYcspRnSalkATgGKUqDRPthvUvTHoflBREnthVJhzGmNrDfQjBCTTbNLNrdbqxjtbjhQxktpTErwKOmYedCcdYqUSFofF",
		@"YOMcMeEEJMhWQmuGHgUVDQewsiyXGkFgpkIpdRTQKmvUzYbZXByzMBbvRMjNLNkAgVFiTESWpMlQIvXjEyQutQYXDtpaAtXkBUPVIVTAEWNCKfIZlthp",
		@"RbPbuJVfAvEWusQFlZxslNwoZBmAKHtFqEFhHLbKbTyZmDWfMBySkNcmLxDoaumeKYbgPesUtmPOVRFpvxsWAWqllkyMeChRTLrUYsFkwyibqGVLMEoFWiL",
		@"eIYyKZNGbiTQfiJZYddLXELBxTkTbxYevcVVrfUuwxVRKtAoaCQrAVumyMEqmpBbwGvsMaDCynWXHaMmGTGLKNZvBwgNFUZDuQFWBaLroKujsQjWEOFibLAc",
		@"RhhHMWUOFQCoXgPukgwUkmzFfnPWwLEvrKBWGyCLSHLVovjuRHhRbddIqTtDOoGWkheDXdCQWUbVUrbwrRGkMudMahUhvrVWScWoMcbJmhWM",
		@"OaOTLQCwmaofrPIoFsVgkwNppTBzUWUhsqCYRjYUCxpGRYrepOGzujFFDdDdMjpgFMCIoRzhfIkDCkUJoJrQgueTCmuuoQGvfbrzzOOrsgeXPUGgnaZv",
		@"MkDKsbpEFFUVoMOxVWKhXuMlcnAXxwiZdLNVUwhjIfBLanptYNbuWGYiLlpQrFHlwcvFamLCTlGLuobYkvjdkXzNUyfZdKwbklTSmuAvnPMReGnTKDskApjsHSmslmTHZZUwxXK",
		@"GuXfWyoYviKsuOBqqmfzwAJYquYLzjKjDiLhRUaQaoWKkkXwnPCWeTNZWRINQXYzgwHcnxHMkRtyPKdOcDRHHbcjOAFhPrhjmwpXGXHNoCPEDoTLWmeCc",
		@"qCKFOrFJJEGcWqQEfPFKHewHwRanpMJfShsaysQUTKdgjPtHuKgPbhjrpZWantiWxOiSVBuYdjiOOOHPTvEDvixymySvFbJYiAEDlYxyOBBljekggRdwuKXmTX",
	];
	return IbqEantIJveAo;
}

+ (nonnull NSArray *)ZmIVDRwYtkUk :(nonnull UIImage *)IlBGpbymJO :(nonnull UIImage *)DLkcSmLUVvp {
	NSArray *XDpaiZNGVBKyUT = @[
		@"GPVdfBqrgoFRDezCmGsFIjdiktwWYWrgGfBdQaWBKKaDjvFVBLQsOvKKFePzMwrBMCFspZQHoGjFWFiPTDvTDeabDpmNmyEaiZgGkPUtUYJh",
		@"xjILtaqrDzTmnzRisjdcMbmeOQthUYrRqQSYXHdWJSzrRLcfKGBNAdwjJCjMxHILRAyRlUnZyksReQFgAYqYzAUnwVBXyueNPHNNfTPIpEzEAALnmVVoHgWtzLXiTcPgmGJ",
		@"EWrGHkxzvIUmigEgZlODBdbcWXWOKksEJPdCWNurlttFzDhUUoSJiHxQimJWdzbpIKAHJAYgPvqWTlptpAhEtKlUKUjqgqoFQGcxofRnxSHIAqkC",
		@"ZqqPbfmqspJEtXtGHihldrSIgoTNcVEXSgBnXtAQaEPAJEaLDavpKDFJaFYskphoaKCOzgirlKsDRCxirFHewsDPfTPzHpkDnalUaxVAkEoqrCWbgIFLAaUHSSWJgRWcpq",
		@"upCtRpcXxBwIwkqljAKdMSEuvlVmlxaWgTeoHtZWROkduLHhprtILkOcCyJZOyMROZyQQMfebGafdCZNhmBXDRfQJjrpgPUeFESKiQRoVZPqPpNrdVeanInzvIJqrZlP",
		@"aGFDuvBWaZGSHjqyDwhVswQGzwvNspqyDMowzbpYUYJSiNTLDeCEFCjYghyxwFixhuLHQXNtUqVPGnngjlXkwhkCKyGNrxrCTbFYMfFWeXdKddGcmeSLJJaayLDwGXXDXVgCGDGL",
		@"NchSmTDfjfSnbaeWNZCzhgzswMgVAygSZsDxsRHzmrgFZhkCgdsgTxKkFYdfAAdwFACmYTqwysTEcsVnJBMKrvvYHNGByMCGMZOWLjNHKclkjGvFFYrJQkOzOeOIGOnaZ",
		@"CrhvDtMfrmepAEbmbprZnAWogvjCAtzmkkgNbxoPjyOSPXcoCUBwvNCMIqEzAtYtQBtGlrZSYdOXLatMoATWiGHgKJhawjfBnMuwxXnutvdqGFetgyHuwRQUzzGJevCuXDhLlXokrElKfooXq",
		@"zObxoAMuvlzmoUJEYkonrtjyhChWDqHJQIhmsehvoxHJIRuyHdnKRDaxoutjFzlxNTrTCfAuDKGVKWRXumycHvWkLUEoTfVOWZphIrIVdSJFisQBcVmuSjyKzuPRRwoXnM",
		@"UbAZbvmEaQzSASVdKiBNbuffaWWfJURTRCbXkdEDZEfRvnFjeJWVDlnrFiZOSSyvRXzflQrwsfoJIPtDWHKZszNoArwtQNDTTTTYbKfcrDAuHQJfIBqHasYnfoxMyQnTGKQ",
		@"rhPujzQvvRSKhCWQKGptOsCPppGTmuJnlVGLNhaQvwUTrNRqZbwYCnbinnmjLTAZuVmmMZorVQnKNQnmvVCITVdOYmUyBfHcIFnpvp",
		@"ZuaESSRrKEEwyNshRcErVBgopxeIQndZRdhPKixuTofUEGVMyQLRAMUdDKvZuQAPAUoZuIJqfwDTOhjMGRsElGLtmQblsABjxPqDPrLVM",
		@"nUXkjsXcZbRaWrOivgNOwHkRVNPhhaTBXXYMudbGjTCsLQXbPWMSTyzzjRnWjvUYdEyrYgLnQuuNzqqfLnqgjoKuVMnzCBOJRYUZBjCNKHRxomoap",
		@"hfGfBCoiPtZjknbuqvXqDALQXsYCmCBKMxMlEMygJGnqZuMxkaNCUDHhDopTSHPgOxHCsCsMsOsudkMCKSGUHOATctqXPaJozQrUXsTUJpHBeECooXCBPAoTIX",
		@"WmSGIuUTWxxJkyEDTpMSrwvOeeTZdbgiAzujQernBHsTYOnVuVfTuqnPLhowiMwhCIaeFNZJZKFJuWFMJhWrqqgahaPfQEuvRNMYocJAoUSr",
		@"fBKzRfQrdNnykOOEsZbeMfEiwsGnAKnCVYFApDblWfUTIwJcplYytkHpFmjjCKORtDHFUZVOeqGzipaigHPasZadKzSeXroDmszruEnlMJlIMiPHTraJdzlMcAAKauNMaMYo",
	];
	return XDpaiZNGVBKyUT;
}

- (nonnull UIImage *)WrvRHocfcqT :(nonnull NSArray *)nCpFiXZdUI :(nonnull UIImage *)TeyNwPxDeuxkIx :(nonnull UIImage *)SatvagaRFKbhIIkwEac {
	NSData *EfdHLqMevRzuCSlfaxa = [@"cadbxOPtOExpTpwDyODjBpLZLmThagZWyhWVxePYvZGpbPrkbVdSCrQRadyVkMhUGuKCaXfaUuKHzJElDirqOdChlMSGmUOTDHdWHphvwjtKzfIiGyZZzaVcGyKWRVSUiZGjx" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *FxmDvyLrUnlMNIccAN = [UIImage imageWithData:EfdHLqMevRzuCSlfaxa];
	FxmDvyLrUnlMNIccAN = [UIImage imageNamed:@"ZagGVYwAGgcjvSntBuyBWonTDRKBzRNIvPjMkrlUOqKJGvDmTYtYsHfxZxPYjeVzihghnaOtzcwMPkvslLtyYNgsLMMYwbMrjPxaoQMnqBhKsanR"];
	return FxmDvyLrUnlMNIccAN;
}

+ (nonnull UIImage *)PAoWbqKQqtmI :(nonnull NSString *)izmfJVkoIBO {
	NSData *ieXpGSDzmcYuF = [@"bKFnURSAuBhyaHHPeQoXPABGhUMOXcjJumZdGtqtEiYAELAnLEUBGTYVtLYgnOeBGvZTOePOLXdLfpnyGMmSvYbHjNDASiyTzwLkzIiODmeFbGUqNkIpCgQDy" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *QvFjufXDsCI = [UIImage imageWithData:ieXpGSDzmcYuF];
	QvFjufXDsCI = [UIImage imageNamed:@"llHkIAhQWdfslkXvYCygBHMJIBcwBmrokXNBArBlDBilHnZfEMKmrJCFmhzYdfFexbiYNPLmmAwBicfuYBkflYyewjYDLqNXSzaVjb"];
	return QvFjufXDsCI;
}

- (nonnull UIImage *)gkgQdeeeTEltXREjJu :(nonnull NSDictionary *)PeMVdHqktvzLnry :(nonnull NSDictionary *)XDFtcJpOerKsBlIHA {
	NSData *XQtWcrTxgSwt = [@"whBfWvcbiUAEbTFkHbwUkMtCczcMsOPjIiUEbIpTalQXyrJxoeTpFSnbpiZhIYRDLpiDYrhHRaEZTIIkvRijnFtqbmCgrsUOgoODRmONp" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *jVKHiJEuAvOOzTaw = [UIImage imageWithData:XQtWcrTxgSwt];
	jVKHiJEuAvOOzTaw = [UIImage imageNamed:@"RcGIpdnuZvLYzkSMGYMIKVhdGguhXVJIUlqZRVoJDWhJVTvKkyknMkgornVUiIYIZNsAllderUMnopjLgXSEbwFKjjSdagMzFZGYfNEaWwbTNnayllmZgWsrDimfXOGHrpvwdSmmNLysCzfq"];
	return jVKHiJEuAvOOzTaw;
}

+ (nonnull UIImage *)QwTCEkgmtcwbzaLUmu :(nonnull UIImage *)IwnQORpSLJujRhYAZ {
	NSData *ugwkJtjwgdM = [@"TmhIqYCSoFRarxPAhnOpRsGLFNRTosjrNAsntzohPRBlGQWLBWUSsxttnWwHklRczmoesdowdJFeogITAaBpUeyzySWfYsyINPYUWZwsn" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *KMQcgpNdey = [UIImage imageWithData:ugwkJtjwgdM];
	KMQcgpNdey = [UIImage imageNamed:@"SqbNRJUbzUBriVGMNfCTtUzZTRGxlQiAwZwxmQRrseNAuHtADveiDJRlkOrNAytdHpoQOougjnrUfNPwXamPpAoatkdJaRKbHmQKjNuQMKjNaTZZkUmVaOZbIVxHREEhXOQ"];
	return KMQcgpNdey;
}

- (nonnull NSDictionary *)gPZDySSaTw :(nonnull NSArray *)hWCfnEfRoxGkOWbXTz :(nonnull NSArray *)yhgEgUejrlQfK {
	NSDictionary *MbnJUUiYFc = @{
		@"jFhTRscMHEeeW": @"pPFZRVCJlpZDHAjHOSRNwLUwnFyxEbZDNltQTaZdPBCrxJbzVJNpLIoGJaQAHzFZLZABZJoVsQtqQyhRbVPROKBSjZiZcjqtntTJ",
		@"IUDeaQByetGMZhGZRQ": @"hLgiOXTHXZBSQGTNJTPWmzGuTlztZxWEVxRkoxyBPzyZUvcwFmmYeTltHDoqPkhrKMofInGwjfQxDiOikrCSNLKawQDRpMLqnzDgalMapDiLozqZnhcKpESpyJFJvQycROJMhxsgpRzZ",
		@"yQWiHBGyHXyDNniX": @"AsoOQUgxrjVdiIbBShVzBEPWLMqaipXNoZcPgClLWuWxKCuAZZkpMacEtRitOcXzARzLoKTWHzIzMdPivFdVrXJIpPgppBPycIeTJKpIYpmVdyvkRCiQqRBkbIpv",
		@"FgMwTrKUQvLdHYVI": @"DWUzvqUUJgBOQGiHwBmxXZIdjzHyaajiaGcNmBlSTKXuciUAbddQzcsMNnFwSCxDXhgUEPFazChyCIpPOyvfeIOoIViGcwgyxbOyhSY",
		@"ZezEpQAJugpSSNuADhY": @"dHyrrzHlQKGVwvXqmIimowyvFrxFpSmjUiWyUEyHmDtzehTamBrTycviAAjXlblgZXWQBoAcyggFqMmwGnFFUcTThYgMnAJwakdfcLPIlPqxdMGLDwtkTcNMFSovwsYqroyPuAtLkRQDBMxo",
		@"UGixEIZsOywvk": @"bxQqzLMhIARUAXrWqxwnUJVKJIDXUQBWwkRhzoMvHGEDgQEJYjmzdoGUbFFtcgpHHRGPaeJFFWrhPIDhYRceQsWBIdUTriEzfFeCRuGltPgeXgIKZsdeXKwLXtrSFTMydL",
		@"oNJekyVVfH": @"GZOiHEikgdLetKUgfXEorDyNZmpmHZQkTbdcLaCylxbRUtxtOQoEPKYmfFoeJJDRNhldwKusPiULwzUUKPWrqZFXFHdzvPyjtCRmNbAylfIHThjIOTjPppgtyHWyMDhyzUrlSAFlzPXCMtO",
		@"CvXVPMxEBFJkd": @"EMiNijKGsqntkZuuvvYjAibkqVICoHAvkMyCiXZgxglUsxNATKSdlooTqXPHomzAIQzCARwIcHKNcprpzrMHxjXIKkeRswjqgshlrUfpqtttvjPIyN",
		@"EUJIVnkZObXrdiF": @"ImLskWsxkpwLKauMiHVjMrssiiQyGvFnLOVIxPHnpoubFLZxHxRASDohQJoOVyAkZLMSUhCOVqQtbgsxfCVnAkWjgUCTxIfMOgXHORzeFfyFDLkfDciDBxABUpiC",
		@"eCtXZPJnWDlz": @"UEssuWysWekZcDsUNROINpMnDbfNpFJwXjgFFULcqOuhlWoacOZriOozDEmwiInvmDhnwpAJBsYEvQJvhlMKnoGalAhAkYbzHxGTLhauOFyNpAqhjuWHvdMVYeYHjIIsceOLfUdsOzyoO",
		@"mhSbzNPaKaf": @"TZgvatFWtdUiWkWnAFDPjXGqAWExejxxUeBmPgalLEAxzLIkeceIGZGiZzKcoKEIUPwdDBheGvYqLxYNaYqXZhOoEfTosPDJTONUonXSlXOlxvUeFseMJNtAtdcPwy",
		@"TVilFcnXaUiDKDSjy": @"zeXRyCMyeBvgZHKzFWkDEqzZLsFkrbNFoJIcjXpdpPlmAuHecMoBvAxmtBtXtEOFLhGMRjrbUYgmoZyANFuopHgGUeTovvcydltQvhRtndNXCtyJWQKRoNC",
		@"houJIycCacpRnAuwneP": @"PQwFDhuKmeVgtOGMpazvaNUeEQWzylJXeTuEfmyAsQZNlZvhuMNTgsbCUMhrdDQOMRAwnheMnTWsrtDhmMXKjsMSFfbzVideJUPzqDzQSDwJnllWGylHmaf",
		@"kceQIDWJEsA": @"TDpQueFmzEZJITBIsgtUzfXruaIrRwiPqPbLmCSNLHiNyxZRXuAoRBpirPBziBysUkpXOdSKyAebPqlXeGUUdNaxzEKQigUVKLIkbUuMILpV",
		@"jspHVuDPUZG": @"MVZTzjhFlyBxytWVNfDbAryymzLRRKGGNpQxOgLQZARHuYIXFYFczKmtMXwKCytFMpNUhdRKfyqkYfpJTaiBybxeMAEIRPntKUhbnkXyLGrTRFYERXXnjdTCigVTLpGkhYKlRwT",
	};
	return MbnJUUiYFc;
}

+ (nonnull UIImage *)LWxrSPwqIqvKIOYwcUY :(nonnull NSString *)IqgANoPBPSFZJFQlr :(nonnull NSArray *)rcOnjvFTdWnEAS :(nonnull UIImage *)hQEPWVCdwcig {
	NSData *lmKrFBQqObkma = [@"bWDqKWKTlevkHFJkieFQfOobEsMZTjfyXCPKRoAsBWtJiNnWHINqRZZQijLJwGvuuQZSJPijgwmQELkLshMdSZUMKBzWLedHynjVNtEIiXjpXgNdZwSke" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *chsEaSrJEfVNshDZqQ = [UIImage imageWithData:lmKrFBQqObkma];
	chsEaSrJEfVNshDZqQ = [UIImage imageNamed:@"OmZuFaRhJrdXoPtmTXUuSSJZgTSBUNWUpfCVuzJHUGlXPKnxPrRtCfAvolYMPfFtzxEBTfZXitukzPPHrzMkApTpGYZTNgxcnZagbRfokdMrmEtoOz"];
	return chsEaSrJEfVNshDZqQ;
}

- (nonnull UIImage *)FPaqvQJUAJWNaf :(nonnull NSData *)hnoVygrSubTo :(nonnull NSData *)oPXbOVNXnOQnfHjcqWh {
	NSData *axMjtXbBSEKcIsPfBxd = [@"YgTRMFPEWBcImRJSfNhCNlkucKRXGEAiRkCYZAADgWHMNBUjAFVUDMfYrwvqjcZcXAfGksZSpFSvvWhpFaUKxnxfYpAYccjGelJKPKNDtlWPVYXTkEhMQwTexkmtEIeOMUUdEBGiNWKfO" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *evzWDvXkHiScYPeei = [UIImage imageWithData:axMjtXbBSEKcIsPfBxd];
	evzWDvXkHiScYPeei = [UIImage imageNamed:@"SPtKNzRETtAnlGwEfMKKEQBbiMcovsMXQMICKbvBiXwvaOTQhHsSLLJZydYDwiuZfNoXbqeoWCqEvTegMqjkUlLAplNiDMrWJANatWRSYEBBcYcCdUqmkFzLqCAQWdpbJvnrHXLWiWhSVEoE"];
	return evzWDvXkHiScYPeei;
}

+ (nonnull NSData *)drCMZXqYEQeC :(nonnull NSString *)JhpwtLTlvjAunXDrgK :(nonnull NSArray *)eZlMhJAJhHDqepY {
	NSData *CBxWuodYmPKGJ = [@"yXevTuFzEmhnyiCaUDNPbWzNtsfCqgdpcVRqytqIqrKhWtVGxwjjalKUKmTQyppMGlrGPyVAJxLEdHSDRvaMhpWqLqvQtRjzxhFEddZfoVuYuRUSHEvLbIOhmZaowvXymWtBlHMtgr" dataUsingEncoding:NSUTF8StringEncoding];
	return CBxWuodYmPKGJ;
}

- (nonnull NSDictionary *)nxBVHqbzEIsN :(nonnull NSData *)rprnOxdYpnGWHSk {
	NSDictionary *KRHteTQOMY = @{
		@"mYhJbuMIomSgZwnZwUi": @"enRKNNvUjUUvWPRynLQahgOXEdTDiGkRlcMkldcOEWArUNZNVHJbOStrUVQZEfupDshvAxnfbDsqyoyXMepZshVMdjopEwiCrAVhnySSLwCoQJSaagIITicWCcVFVOcr",
		@"xjACXrcaIOVo": @"RKUMkWrYPhdByGNuVwRjAjEELpCGAxghngTVqjOvqUkmolDEmXQzuYMYoirmKmjVVYozzOnTxlMyfTtGrCeqCsbunbzPssykVHZEbK",
		@"XnVIFdBaIIBenmFZ": @"FPyLEltDQDLwyYjyNdubjEllJfSSmiQOFxUtATePlwOUPcgtxSertrHkFpnfAeOjcwMztoTtGrhjhLCCiAeAjXUhsFYxQWRObWYosyKAVTFJze",
		@"crNyBHzrYKjKSmG": @"bfNhhgmvSFsixWicarIRIAsCeFYljgqVHOayOzjkDafSskgjKMDNsUmrHLzDgeHmMYFvgxUwBIKyVKMuULhnpVMXMUzLYvsZeBuzIClsYUBzpOoFJaiVZtJdumvPsrOSCuZXKP",
		@"bYjRfcTPGbHNe": @"rwzBuZcyNrufKeisSnbtWVbDuUjRvlxUtpjEsVALhWQHeegcrWCdfXbaNfnpZYzSCtvBqvUPJlDLHbXtgeCSxLivbfjnFiTBrsTvevopQSvVeKrLIQhTunZXtZoUZhXUVAlSJdtuKwwtx",
		@"GSuZdzNfXYuRjZ": @"fhZFVRbNWzwjlMYSAotBjGBzTcuOLqnAbeMtaOKLmNAlugOtsJMqYxdOBtcUOCgvgSmQxEnIHzFoNbEPonPfiLQubDSmNXWekUkLIDkSzDNAphTHcemxPlWlUiRC",
		@"AgNjCPkStV": @"izIsdWJeVWAsTFXTzqLYYUXXSfsyxEYdmrVyrzAozsSsrYyAREeEpckqpejXkOkYWiyTtsiLfeOEyktynWjjVAaynpVpBpWmNnFgZWSZhvyTeDDXwaBVVEaJyvInFxVMyaZwbjfdMfJY",
		@"PoCZlVpVQhRw": @"BeYntpLpvhMlvnRFxoHPXJlguvEVOBmbGICDsGNtsVgiKaIgOZmZhQpNiFgBQNASPAJlheWoPrvslsUCLAdWVVAKQYOdAVPEabIRDsyHiiycqlmfHIkjfvOhMDSkzGRSCcCc",
		@"mPSwjTmAsyCwNHNLfD": @"WjtzOYXYlnHWcYwojDryhZlZybetFQFVGMcRSWZvRNGqoExObfHrsWSzlRIHPLaswNJbgConeDwRulTUEFzMigcQgHOODCQhqoUDAcbuYFXkW",
		@"wwIXuiiVndOrqRWSI": @"qVXkBOmotftOIZfSehBqarPocyfjZINhUDmSZnfrGgJMDAPVSTBujRVAzGZUmNcXXosIXIuhpKevRnaoCfqJzhDPhoamcePGEgJEVqnnguUdbzLavgTLcSWjeNswXwJziskkXrOPhyQ",
		@"SOJMsWDYzi": @"IwUGJyGgneFocmnoezRnfmXDZqSfHzfHPhwgBBbEdbIkCgRlCPhGZmJBLlVMmrHyXBrHGRLYJAZtkbyJVNdGoDYmXWJmxRyZAoyCqJyJhQtHlmDEPLIMyThtDICbTdCRRvdIzxmACiDyO",
		@"wamxDMviAjT": @"FYCKpPWCqsphCGnDsTmgJgvkDCChwRvcrFbXtTfbYFBgjQsgSgUhFnewdrfRIXxtzmUdmqCrPvFcYulJGsWCDxmkTdXiYrSRgdmsImGuOzZwxpvVjJO",
		@"GNjnxQENcb": @"ubbagijoRowvmFrVgnKClpktRuGApfOULdoKKkXwgbEAMsgEEzJaqEUAkrKVwYaxgmWnjatxCMfHXUcWXEBjnpEborseoKyAexhyeJTpTmoxFEIhDpjWXCIZjfh",
		@"GHJjazILqCaaRaA": @"JVTsuNZUwrKQQgSIQyPCNNIpzwEIlplVdjsSCwIvwkPynAsarTgngNjGMUOHoZJyxOiwagTfcXFIltkbGYDwSCQbvVfsEuYrsFiPsnCCKdLrdxTznNgPYUxOMNtccnZMafLiQLzdgUnyqqs",
		@"yecEobDndjcIrNYvQ": @"IGmQNZecklJhXdXOdtwOUlEBwlVRykRpgGFdNedMSauJptzVfhgnBuNdKpNrFTzQwbKgecaFdhcywjYHAcYtfvckNjsXshUiReotAGzclRXVCehHg",
	};
	return KRHteTQOMY;
}

- (nonnull NSData *)ChiVDeMwfzt :(nonnull NSArray *)dZqCleZuetU :(nonnull NSString *)yvmixCvmND {
	NSData *fwCzAwenFUQGEzSbvD = [@"XbApMvmIzoLIJJegRlIQsmdNmmEPKWbUpgZOLOYJfjKQzMxCvhxoGnqKflTuQijKEQRBwLexXMCGgcxxoTMAtsvBnzTrmCoLfJWn" dataUsingEncoding:NSUTF8StringEncoding];
	return fwCzAwenFUQGEzSbvD;
}

- (nonnull NSArray *)MOFzfzJZzk :(nonnull NSArray *)ZtAAWGXxRFYYOOtUy :(nonnull NSData *)PJUSbYSLSsYP :(nonnull NSArray *)JWemXCKOqVBspbwSC {
	NSArray *sRUmHjfLYGstFKVxnW = @[
		@"yuMTZLWYRvxjulOtjmmSNNAZbzgplQAVMwSBKcxPACEiPXnGjXpMRxCvCXjSRiBHEPDHtCAhpCcJlyjYakKCPpwGFhfIxuOwEQzgGsAoZUUfnfvnuMxLhCnWFexwmavbPabKPpzRqRGnQ",
		@"ymzBuncvQQfDMoAZXUXjuqMUwpIbeFkHAoNGqoJAbVAIluQztuEOfkVAGGXLabPuKnYEZCNBubXLwffPfAgfqrTeiQTSnlBIQGzAezjcEQWcDklhFZaIhHCXpojytoQtOLoLtKVJNMPVEtrQtuM",
		@"nowBkbePfQnXCwAnvLeAmOHobDVXLhvXFDKzJrchKbZIbhwIpmGrRNMqBGpWVjJsjRXaVELcDUHWCYRqHAboAJfTUNBYrOdvMjpeWIJOZJMLVzGlLtmXNiYVwQEj",
		@"fUGvnuDhiTpkxVFxlfTMffCsFjRRjiuoMjHWcANBLgFsbTMbIbLQyOurqAyiZEDPzvcUNsrhMDEqDOHansupvaTzyDvghRLePLESBCNqmwhpHYypSgOGcOrTcZugQR",
		@"zQNRQZoclWWZPKdKjNBaYgGyxtVeDmlwzyNZGNuPwvEGBdwRJkTDojREuxNmUAFPhxcoswKLKieIbNoXZjbFJqocJVvOKHHAVkYAQJygtHnpOwFQyrnKs",
		@"ZEuqVmSCKZXDQvdLRTSPxfPvyBfsVeSQMFBciCNlrogeSywCikrZfDdCzVMMremDGPtLDvtoMmXfYdJrKBUDeWFbZismvfWvHerLqqzTEYmvqU",
		@"bgWiCZTICkNLzZzIumMPFjStfKYlfHaBLNjhOFUkDQWJyITympsgpIFfKLcVDaapEpLdvMIbgzseOsPtiXZdaudHkdiUyiacjpdvqtqkunOKysL",
		@"RqfbvowOUBIwujhAGRXcHXPxiywGNmaCBvGPwIiEkkPklJcVCLlLlzXrZRoOHmHMmOkKkTvOTzNljPZPBmUKAWrWhOGsENCmIqzIejqpvfNQlQVIyQJD",
		@"IwFlDDsShOXiZDXslIhYswuJoVacmghtxEctMrnyKAAKctbONUUBxqRDveOIIWSyyOAqPwpVDKUdfgAXGHkvZEMXyBeFLaZmkYFazZQfBFPjyZfzLwgyHMEGvyWMHt",
		@"ldYbKKrfnrJlqMLiRsQaOgGIHILOqufjupwNyWkqkprxwVAAXizBZJFiJStLbaKHTjkieWuWsNmfifygpEsGDPNxlNXRiozQvAkMbUjvedTAXvNwucMnTltELLvAyGDOTIw",
		@"qgeQXOdSNYcnNcKpVUMxfXTfwWKCtfJdkxBERRmZjyczUjSRMqjcdLOYCBrEViJvqTXlAzANxTifTVgsgEVgDTEJuPgGpKUuEyMdkbeFpcosNPUFrDeRrxRdvxsvffCQbRMmaAZ",
		@"EnisUzEjIFGpkZTefDvXuOkdNKJrjiWdDKDhVXhNQgvgfNrssfBgVzLfWjGkVcqlkXruuTZvQUlKOnIgrnpvXwToRrPUmYNITpGMTVJnLwjFkhExzqRZwn",
		@"GSeWDqhDecrGliCnmnnLiNWfCrhxwKrMoFqpuGjzkOakVnCWmJEcJNHQvfjdjyqCCNDRLqwJFNYwjbAZLVMQspzpVVMIQOOEQvLOzYybXySprjdWDxLGkALfPRX",
		@"ntFJJrYvPPFlGEFHtgCxKuIPqTYnjpxinyhrTsLhgvaSqwRHMFqynlAypDfacSceXWnqYcVimPMePpyRypUfZpsmWNsRwTWhcBvCxYqHMGrFoVJYLLsk",
		@"wUqjwvLpqYenjpoGQKoPejUfvbhVVXcjtGBXSfUzHdbBpQmehWnjefkaNnPAqzzqIyXSsFDwkWquhHeBYCCBViPuLyUYMQKwZoCaEBapdYdDHjmonvmfCpsNTpZMwOrbxYqTzIReLHxg",
	];
	return sRUmHjfLYGstFKVxnW;
}

- (nonnull NSString *)ZCcXgiQoryzTpK :(nonnull UIImage *)rdtxPLlZnIg :(nonnull NSDictionary *)jfnzWBWQhszqvmQ :(nonnull NSArray *)JfDHTppCMaBaUGzdN {
	NSString *CfiRFwtQQqQF = @"bSptwpvwFrQaeJNIWEmQrNZGWlrKiBoUoyXrImwnVCmLsFAWfhcklNOelsXaTXOkzERGKrearMscekWAdxpLzjdtnnZoYbeYCMXEXRCCCa";
	return CfiRFwtQQqQF;
}

- (nonnull NSArray *)iBQGhkDDbaR :(nonnull NSDictionary *)nYduYuPJJdT :(nonnull NSDictionary *)tNwPmFkOhBYtdvX {
	NSArray *gxlURJRKEeS = @[
		@"jDDKlaDLrkALvRPSgtOmqMWEFEmVCDagYmMPOqsVOROKHcYYSvaunhiqcYYZRjwCqMLimtowXmztmeCtLCTkWghYqEvlvZgRfHekcrCPPHDfireBchwfWtPeowVOQTzO",
		@"GBIuCJpWeBVMaaahtiWwtiKCtThVXeMTTwZPLvhIfvXpbCHjkXSKSSwtSBnkmkoiZXsTjPunCjoVqhDQtrVsKGwfsGzVSCywksCNBY",
		@"AhGuAavKjwbBKSYvenWUAwuIxyYaqWSFELwFTpsLqLNRUAHvHJsEiiFMjvazWlxiLNEunrdBYeutMYrfgaXCRXYzffjmCsmHyYYVMMnZHTXAwTqhuICzazqFnblgxtDnxipExz",
		@"TQYvOqbdGhfKizfInJjfiajAefzIVJRCpfQbBKGTnbrAqEZZlQjXWxrkyzPMFJjvPSMotLAdbZoKDndkhXPERGGyShtBtvCXpJRrACTbmXttFZJFebhkRHoxBRJVAZDVylzJvEdy",
		@"VWJSkTvRMBWtvhboNcSufemBZyBVBdCskIojJbinlLiLNMfjfSVUQbLCdlOSpKgbHjTHDFtzWLPgIzZUWjEXXSzTzBukNgaOvAcSIIgfvpmKMfwGNzAWVWUYaIXlqmdMwnEFxqGApqQBDIfJE",
		@"DjqvhOTRTLJJwidQCtZqxBixCsPoxaiVBHhlRwNrherOFVMEMQCQRvHxjJVtUGIWqWaEMAOfuujJSFcxnFryKvbRpLgvgBzGEvvSriqFJrLAPgmwSbtk",
		@"KyiFdYUwNHpjuVXfUYMiPgIgerMoaWiuDkEawnBlyhVmfujzhQetYRcgpECjXYbdCPtmjwBrOnLwsIUFWTZjKKZxxNtVWAkccfsnASODKaXbYISseGyNzHpAMqTSqBLgnIVZXyFu",
		@"appjcJWEIWsnwCoRkQnvhNnJyPSzkSJliBmBDuAFMKhSSLYRCbtdXtXUDszvVzfTaIgvBovTMLsLNGbTnMkkDvXHhtBgRtJyZkxLlWgzwqEKZRiedjorKjCm",
		@"EkxcFNevxIaJeakmjrkMjdUWboqTHpJEjzvybHXEUsyMjDZoCGwKEkxRvkJEuhwmdmkwoTsVMxOzeIuemsHpeJXxeKiSDVgMRfdUfGhXXiAtGHgtAMkjQzxJ",
		@"GOOhMKpriFWPYXIIsWXtiWGFoPWNvXJxLXpudENVQIQJdNDLhEqkHsjjKEnCfJrwUvmuyvYdTwmquNLQEzOUJAFakMJuWhVTaPUOQDMnQTUyanLuFPJROwAxQEhVQNQxYBeYy",
		@"JOGNOOCeUlGxVnpDUgQkBowSanKRTwrmUrwmyNYiqAFSPsBIXaupynAtAwRIJSOMZfWBryYjUnWDicJAfMGrxwYdmZIRLIcWstvnJjsVfwxuVRDXGSELigcKnx",
		@"YBfUEuciWBZrEDnhUduqUGKJMoIRSHTfcdmsjnFvTUDywBvgLmlVjtqCjgDrlriAAUWPQrAMrRiaUGWgdnvoagXFcHiqbptWIGtNHEpoDZCpUvLz",
		@"kEbYKcmWvGuhkyJMlIvaKqucgkSGpxfjjbQmYsrNfRDmWRXCpHnqGCclBIeJrOxSRfuiTEjsCpwyUIaElqskQptDGQjurWKFykiLTEGqEedQinpjeWVkIvLsPARUiCYcdjKscwlNvVeQDznwDhQJ",
		@"haHtgytVhTJJlozufybDKvfdQmHygYtCtDNxJisEJfGOQWRxvLwychmNWPUWWwiwxxFBDBVCvAJodHxAeEvSMCMsNxGPBBncRGVFJPIudPARKUsiYrImpErwNqmsng",
	];
	return gxlURJRKEeS;
}

- (nonnull NSData *)gapCqkMoGi :(nonnull NSArray *)sOdZjUwasJOpBAC :(nonnull UIImage *)JDHnCRPkbE :(nonnull UIImage *)SZgrlsPjXFfuBI {
	NSData *RzaGLOtqAvOCu = [@"LPLdMPlzchioLQVaOAbDqosGRjShjpQrQgwLgXOwpxyQMmbbqhYcNNhOKcIQoXeVjJOuAfSXhFDGkitRyrMjSdzNeVFFGOJAEJGvywYifv" dataUsingEncoding:NSUTF8StringEncoding];
	return RzaGLOtqAvOCu;
}

- (nonnull NSArray *)TQDhEXfItxg :(nonnull NSData *)ZnybvdtURmS :(nonnull UIImage *)xLorinonQJeEYTCOtw {
	NSArray *iUFvdiYPCpMjQhtgDrx = @[
		@"lKrIpkfQlUdxTJCYwokdYNWnWnVdQUrpDqxwICiFMtLIYsVpkLzlSTRQQFiFsFIgPzUObFYDDyNdYogJwEDlFOdVHMJueALNMiTXZHato",
		@"texlkpLZJFjQTuFRdIiodPDnwtvLyehNRGRnUAwmJnUdQXUTlZfIHpmjClnJJcFSuQjOAnCeRPXeWDwhVgcfGNhtlgSpxjkPnFRdvtHDRdmCbAMHxOdDcEpXHBqhEvjyMZmAWyLmBCL",
		@"RybsgtluwWhmcgyqrcddchXKorAViRKzQaiPnBmPMgRdfYQxYiHEakEmjklZIvulopQHLpmJSqgKXojyeVccAdlNOwCOonMeHIMfqKdhgpPpzFUV",
		@"CUVOpLNGicYXNaGSQtykPbKahoThAmbhnRPEyRyuvFMyANWAeqmnOWQtewcKIZpzTuEvuzEkFIfGTgAsRMWUGvbCKFxfkYVLqaSjDV",
		@"BJttRiELqYxSIleQTRcCysifOKMHBEvWxTGgeGdGAoEYZKxInhIVrDBSzgseTzeokBCxPeMfFuUJibhClbkzLdXZyXtvNtmZSQBCWVXa",
		@"rOWhveECUwrLrrIByaxjBHEUCZLugThKNOiUbNkegZLpxRHEJqBfcBguUxcRSqSyGZYZRadFdoRsZmoLwvZDQCnUGgOdHRNQEHHagrYdcTCADhVmfHLFfbQBvNhPTdBZkJxmfkoZkeUFCGKLOB",
		@"ENGcqyenroXOovUjwpEzgVzCGGhnpBhZvJgphCFlVOjBiXVLWQGCBITdmJKZPyKCodGgLTmOajVJCcwzlhucbbgDcFatjYcKMawNrxAJsGVziqglaxwYP",
		@"ssoZyHMqXJfCQfeBYmUVfdijEJIwdjcMNMfsDMcnEmKbumZCohOtqftPaglhGUShRJzleBqXwOCWqiARpYmqisBeZzGUdsDCmdvBLTWdTWBi",
		@"BrqGhVtKPtbsQKGOpkwhktFgwIPSeEkUNJFBVIlnYBlDWsoLWUXbGWwSMzhJbBdztgkgjLeRTCcZFKmfHtpMMUTuwIRoYYEtLwofqxauzWNEGWdyhDYbTKKHioGmTPEIetm",
		@"ktokxTiUtXAXHsPQFJIkFioZHnUKomZxZEGtZdFXeMLPceUTztKDcnErudGmQzrBpKzIPocwurqJksWWGwsMnxIUSUWvlbAmwGGHcpyHZYOyDNZavVOmFGoUAHQkpBggSkMVgNaW",
		@"FrXkRqaplLEhnyaOBpBnsKOydbSwXZaVpJMSpljZzmjoooCdZkVASamquTZhspFOqXkbFoEGJgCslOIoLGAgUqQZKHpLsjbAjQiZrpxeeoMOUzqZKPvkIHwnfNeTLwDfBOHvXfLVyfZTUPexCMK",
		@"eRTMvGgMHaLkXEYlDQSuJnIgzvFcBMbKWPNBuGOxRGKKayERpbWGNBsxawTbRUCskciHWmFyWYUxHDrcOdfMIBUWueroStjeuWIKxNjjQOEFrZcrwPPpK",
	];
	return iUFvdiYPCpMjQhtgDrx;
}

+ (nonnull NSDictionary *)FdAIvPuXcZsnqH :(nonnull NSString *)tPCyZUgDCPaB :(nonnull NSData *)iIRXUgcBTZTQWgYtb {
	NSDictionary *MaMipebGAGjTMKWhZfr = @{
		@"HCOjtnsRkQSScLvmRau": @"zYQSUllEUzwPuhouVJonJqXldvlrRUaEZRMdJPsPAxGTXvSFJABsrYYtkcLINMxAIfAREGYVFTYjcEHrwkYwjmKBaxOSZilnlwPvciNiseKxNHbIu",
		@"PNcCmXhmMSh": @"uFONcjexdXlldrLkHNPcwOccjlqaAsMLLaSUbioQgsUXkEDfXdEDYsXjicoIMsUPGunNcKrzpqYDJdSJsvpkZNrzAENQoJfvfYAhBJdKDVyXCXKEimBBVfptUnBxtMUqWsHikXUScyt",
		@"YgtyqoMyuf": @"NvsbIiFNiuvaDlDtboWyxbWiKoCHNigjUAGDwZqapktAIxoalihINYxpHJWdCUCsLANgYDPNBuLoYGbOdGIpUZEoKxQiIkmZQUfGnSxxYZTPmxnHeIVRWKUFGodsZBMKwdPffGYQjsAmgUfSP",
		@"WWqsXMgEKAaK": @"pFvrrFWCKgpWYSgJJZmYYJqueaYhOmeOeqZCnqBhyyNtoemXOIiWqXgeplhVuuVclAvIdeIsyXUwcHiWkemxQUThSMCEiZXvSRqtYTLYPcbaU",
		@"RPhCfZpQFYiY": @"TUBaZoeSMpAAQEtvSzrjLThKbNSrvZVYMVzoGVeoprJZXCkBLuUCWxcckgnMUJdLiZvvbdlSzSuyuXhqNtpkXSxaGCFXcWxzUAmWuoAwbPkNiaEPLuQilTFcPWjoUBLijILWEW",
		@"OGcFjhobDGpLRmIyGCN": @"nJINqIPclHLljRLfPuRHVNNsqpchBrbXTnAvOyJPtASihxblQkRUMHMvhzwaSYecYURgmklBFoydivvgnMtwawkBFFppKmFPAarQIInUnZbgLgdGYNnHukTOsdeXMNVIeaykTbMWtgCGh",
		@"zAtobMDedzJpqOls": @"ShsAwfrLibJqNZJImzEAMGXXjucPnRhemWkLUhbteACtdjIhpFcWyrBGVSIERuZAlxawQtTSpwQLsFixzdPPOLkagFRqJrPNmqAjhmZSfdNLStbWwBtBTulWFYxBavPtiuhgbpVbXz",
		@"QCTECAjzPLVMDNa": @"UoWKgEawZqCOhFfUyIESFzmeotPxCveEQLtquMENpzvfPEWrGxJkJjtYWLKxuBwLJJsbRQZhoVMwPRQTSmiayElgcVbUrgTpQJqkWyuaCKaxvkgBZdrIKHbMfNdwqtsMYzqEa",
		@"EHyazLCDqPMqo": @"EZmdBAXmWBadcGBUplYCzYdOiOaBAFkqRWZEnBilTeqeDgMlkZvXOqGZStgrArqqPXZVoVrTCfvHsNRpvggnGrJvntWtuzUmkAulVgaSXumHkgCndZcNFTHcJFAzucktZTvot",
		@"AIUwYdkYYwUDbUQUOn": @"FjWNfkrrpZffsZUBnqtRcYsQYpqorWqtMtMTrRaZRBogagGzisoObbeagnYGBWDsexLdXjdEsbxYlLEHfbAQHdXUauwWJZqjeXKMyphjmEqJBlVuyuJ",
		@"UYdKgWNGLQtWja": @"YhBWMHPtIULuMiJauqvxAUQxmJavqwusMuGQXcOQPfZyFCiRtlNEIdcGhXUjhDWysTVyYvMfGpEsCOORWhzOWAxHvdmXVTRdKlNCRnajUXsRZUWkcZKtAHfrjkgpEHejDUlTVVoFLHJhoiKpKVR",
		@"YtVcsBCfjLfvT": @"vkplxnreoQTuFINcMLnCBoIikKUhURJfMxVkkAgeRVfSixEnNDAgmXHmRicsExKUwKFdJtBhkJCQFWsIAcoZLQZBrBbFMBKxKQHBoZmzLJwJanoZNlQzfNviGDwPTihHMYedAQYAETErRpYj",
		@"ANSRlNPbdv": @"HjpXMUIBFzoKOcwJpjwjbXcxJHLXeuqCaCdLgYQgblnBVKJSfnnIIWbWXBMVnCzoHiVPUAHsdYKASHpzIvRfpQdCELBEzeiSHcuIRqIGHkvjyPRCpPSgUipViJJmEdUoXfByKnVJy",
		@"kzYTaXjCMcZxYZrwxn": @"incINxmWsZCbWvnyVUQNsZbzYvYbIdqgGbQRSFxMAjbmZGogJwRTKihqhQgXDXPLhXSbwqTSXZoPkIzWQoTYsWXIljfEvSqoCHKdEZohzfpHXLEokUtdDSKTzFCtrCjAJOtWUtLygAVCwrdQG",
		@"OzgNLkmRHNaB": @"WGxgzsjsYsGRiBtdFEWdELegvNtzcYSOqJjuxODkacKVbbkBWewkxSfbrQwCebIblGEFjIPZvxwzSKfXwzghCUFPGXniNXoWZPIrwX",
		@"OPoijEvzliJk": @"yXUkPJmbtVuuLTqtWGigIqPUDbpAXfEJCkKRKknfqqLnAHywnjOYpEYPfZhwMwlXNgbWUHNOfMOOnnPchYcqoUYDeDLiVXYDwScHfGcEWocaGnZKBOQdKyEwFmCwmdQ",
		@"nJPGYUfvcxrmaIof": @"vuoXGbtmddiMdVfLTBLpnDKkiZGdPioMhnLkRECNFfthigaMfuyaJMjzhyMkxzoNueGpFmpZfAdPtsMmrUvvGlJQRgVZmKGPitaIjTYUxdtbqyxhHNTbkBLkUTBABPmbUVMsFUDp",
	};
	return MaMipebGAGjTMKWhZfr;
}

+ (nonnull NSDictionary *)BfuhsIhRim :(nonnull NSString *)hpdMexNUXRSBYd :(nonnull NSArray *)YdnHgrvCJwzcK :(nonnull UIImage *)qdbRweuLuZFmhLUFas {
	NSDictionary *RJPomEZadx = @{
		@"ErQxnFNwrXuc": @"PBWJyzonKCGNvVLnfdyfUKBcoUfwpMWlDRVfclrtOGGHQdJoWzTBuTjVFzpiFvMBjqpnxzXsWnbeyyrhbtIQBrhpIzEsIZFRKgAYxRbLOFgpznquRXMxLvHgeQASUiifQe",
		@"gsrtRGdvztz": @"DXvxUDlZeWcDWgXzmJXinwXtzslqZgvNWnUxRbkutaXEFCtJejTySIWZZqLhJotYaiiUImDjJTMXejBkByVkWBfWmAOWYNMWIrESrCyDSBPX",
		@"zOOxvRdKVOu": @"EnqMVTJcSbLUMwKDkzigLrigoujczqNMvFrLFnsXpPaezRIcLgRzpaAAgmbRFUNRzfIixkkOYZTVKBTmIkOuPyLHbtegxolDiCBWzGaVgRc",
		@"wIetsbiOED": @"gvRyNMCqitDeJUjcedRBIArePlTDmOjDAjMPDQqcHgZPnAWCkkEnjRMQqiohhvdJuapfrOwUhwkEyAxOJfagWAQEZmBbcQSrLKbsGUPWTbJSUzoMACRLIplXvVwgySWFVpd",
		@"jZsGTbYsrsVnB": @"XzQTcuAMeupSTGmZYQxHQrrbEkCGZUDyPhZPzNsoBoDKUAiBscERzrrNymoPrSrrkBSgYJckbivHghMbTNkdaLcDOmHQmeNopyJiVwGuPzTOVyOTxWakPhSiND",
		@"jPAyfFblXgHDadqC": @"eSDwkMBxuhDmlBTaYxxdwORodAEXKISQHQIsRVgXSrysJJkzPVKKheFXVbTnizimDRffKafhGAZZRgOrHpccOSsQaFLHANLwDYZPXrEtEVnaXNfY",
		@"CjDZuWYUuFIoPjgynXn": @"qXMAnRJvxmtdaDrmMjqRhOkFbKEKfPlJrukuHSyJhPySzdtXgbNURwWQeiwRQWgtrAXeviLudgnzCihaCLTuRzWGwKFyecqVQdIzudTxKJZJdcDswakPDtEsUWuapMcbGk",
		@"LanvbaBIIocy": @"ZBGbyjKiEXeEqSyXeyEzgKXiGqccekUIhNDBmqlSpDqQaPlgjJxNFoHXYOcKzHSxHnmJtdWvzKsActsmZwEkcvmzdkRGxMuEBdiaq",
		@"GHHfRUAwDflqHqIk": @"QkuQiDzoFZbcyOSjvuybbNecVYyFOLQefpWnWTzJHeMoXAkoRCSpWuDLJZCKXvlYVmFGXcSBwQcOcohhFYGAmUrmUZKzqKProZgkHRMvAAtgbvt",
		@"GvdLCpPUyna": @"iYbgEuVKkqMJtJMzHLHHUlxJtiKxcptYVzlGdCOKIFexrutufAUFbBiHdtHvQEOFVAjXEFBodbnucaAvrqgyIxOETCWsLnGniaHgRczdCORBWJlA",
		@"KPkkIkVDlbuusIF": @"xbAJuhcwvJytvjmiJYgZSJUDkAvrqLgyFJZcMgHUigsWJKTiHWMQjvxlEnPVWNEcAuaVovegrpqjIpUymlHOiZWQYLHmOWwXhlmmRCZhmdZITlPcFGRoHhYdsETxWD",
	};
	return RJPomEZadx;
}

+ (nonnull UIImage *)NXmhjEwZmFosdITUP :(nonnull NSData *)pICEJwlFwbqtRAt :(nonnull NSString *)JttyRjTujB :(nonnull NSArray *)OkDpCHDcgHBStDw {
	NSData *OCWFSvwgCJdHUjMeM = [@"TgIXoPsKVrsAqzmuEqOSIHikklChjcTTkwqafRjIIVRMuIPqCvgemuMroXCHnIYKLOgtwWKWtPrzzegBikKDQLUSlLTjFFwVhWinPUuxh" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *MCbCDVRATEvzmyTEQeQ = [UIImage imageWithData:OCWFSvwgCJdHUjMeM];
	MCbCDVRATEvzmyTEQeQ = [UIImage imageNamed:@"xJcXHzkUwIdSqCWSuZkWWBgbXVyZPczGntCuvioSVdkZxprReyyapcexijYmwxgWVINngGcPLOumpAZMWshTIrjsUdWztyvmJRFgCUJAkArdkgafVJzRdcsbXFftVbdlLyjiCEdrXaFZ"];
	return MCbCDVRATEvzmyTEQeQ;
}

+ (nonnull UIImage *)ofKvLWKShLgj :(nonnull NSArray *)ufJpWIXcbZvkrNz :(nonnull NSArray *)nclSwmxwzfHTwMK :(nonnull NSData *)weEhxqhnYeacsGriaLM {
	NSData *IWikjaVQvoGTJqF = [@"AuhVbQjeltaYtAuycpdRRjhIBIwGkLaFzANJDiFxsMiyIoQvqJXZfJLXvJYYCEhpXysGjtdtLYWAQxqJPqgSDZAOlFSLRieGRzPNZLyYuiMWOaymAhITYeKJMNftsufWTibnizffxEGAhAEdA" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *JLQLyUTutQLCIm = [UIImage imageWithData:IWikjaVQvoGTJqF];
	JLQLyUTutQLCIm = [UIImage imageNamed:@"rRRqQpCqjilEiYEetxEZXaYYOpVaVyMpnfemjmpvovXEYOMSBnWeqmhSBolhqKfIsxOXMtApYEsvWMeXzodoRrxseiUmBYwHmLjAbByA"];
	return JLQLyUTutQLCIm;
}

+ (nonnull NSArray *)kLxVXjReGtsomd :(nonnull NSArray *)gFyIoHiRXRwvyhSlq :(nonnull NSString *)XYDrubktxHEEIdRpXDr :(nonnull NSArray *)DykGbCuizgFjYOuMRM {
	NSArray *HtTnttYZwWR = @[
		@"AReZgfmlGdElwSKEMAvtvCkPLBTgCacDGLwpMjLFUeWFSoJIyiAwUvYYtnAYlrBznckBMDzCttUrbflrCsQDpokhIbdcfawIaLHANVOYrSnUQZxiblZNRa",
		@"gDmXElMQJiarByzMlsyFsoKeobktVHUJCSPMJaqoeqLvxYDSZUzDscurjzpsjoclqHPDrXtvbEJgbbKEbYcYvYETQbFWhUZTGcwKKLUZHFWRqxcBVoYaIVfHGrWVpS",
		@"MaGTiwDXeHkezQeFmsxpIxoVXDyrBsdgoontTVGkHyMVdYQCQGEizQtNMnfcvKygDwBFSooNApdefRbfNkdmhvdCVjWlqsOaBdJNCSqoWEaIonHgWhLdtakDaS",
		@"IMkGSJNjkVNmZroMGgDeAnoLzDLNMblKLMPeRdWoPkjLTwMpoSXJAFqhgoIFpLfWEdoWMQviACrsfVSWvEtrKFkzZsOsVAvKdlDJJPcKCrlQFhXPWbqG",
		@"JrtXIisJQcKXOsZfFGSgichwBjJwjaXpXopZenXZjqWEvekIWKXLHsStTYIEKkaDrMyjozAWaYFTBKwKLCUzqyHyscqNzbdIWGRqPOaZiWNGGrahSMCEoEKT",
		@"sKDGqyfaUJzmMOKZIrPQhFPPsyqtktRuepzmzQeczvTmCOSqzJjjDwhDWwIbPqitFqlMpRkxWFIKznpkBxoVmcPXlcUaZqRPcgdxzskHwNpUDJUtwvodVbnYMqzIYSYpoGJRckEcwkdkzfQBB",
		@"KJiNihnDqnWSsCuekgLbqgKlzdNiZiECiXJBZPTmQNlqSUqQXzSsOgbXOFJKfNxCWxNRGeujBEdiJBlZSDOfIavOetVhIYXIKvdNxGFAHIzoncHsqI",
		@"GuLVPQoXCMlDVrgohKPQEPZBfUBsVJWSWyjhTTlyKeWWfEokpnJUTMODqDwwZsNGREqJfFXJXtTQeQhczWzsyJggUYawtSMDPLyydkPbNIdemNueaUjycMUYHfMDkuRjOLjsi",
		@"IXIEarekiTjERftiJyjECsTunmAOMUTUmRUZEwMyyvfjNDSoQzEduUgKsEIjAPgWyUKJvoGCiPcqrPbcKAOdGDjUOqwhTrEjeSKhrc",
		@"QbRWGiHWReZQDgZTHpgvXkAofRwnHjfopMDehjEtIOWdrfQzPTtdisWdKpesTNewTRqbFSKaxUSQIUSgIzrAkICLcGmJqhKgfpDXSoCzGcRbNEYRSSxyqMWiARfumNPw",
		@"buePRLFhBxDYRssgesahXpSKVxsEBjwBlFQxDNRwLZpPqMNDceiGDDDFNWIpULAUlZPDnfplMQLHkHBkPJpKvDFrPIzBefoHklCGLhGINBdFNIcgbqHVgCxwBHC",
	];
	return HtTnttYZwWR;
}

+ (nonnull NSArray *)frUuBQeMddRsyPru :(nonnull NSData *)rLKPMRUenalpydvGX :(nonnull UIImage *)HpQNaNDYEWXUkabmez {
	NSArray *zsKnOyJHIDLkXxX = @[
		@"pkUhCLOZBfeQBTKbSMquUrCpnPSewDQLYqdNINRFYhrEnwIPlhdKjgzUengXnfVbSlGnPdSDcvMztkyhwsUoHrhFIzcPphxrYhGkUZCbbefowtocYw",
		@"thSiTKEiRxUXQiIhAxuQLSNYFWkTuSPqsOHeoGGOHeFsDaXUeSfVHHDmizBVValMeexWSMssfWnwAYtLgjCzQdgvkBLsGiLAcOLFDGgYROwilkOIWgyzNwDJKAwRRptoIXLdOgrmRMQDbyhRxz",
		@"cEWQmxRyIelMSbHAyslWOGOdnUyqyBVtEhTOfaGPJSjsqOrAmdkUTkOSGiLpCKlQAbGMpHPKmCwXWTwlCbyYgEqwqIqlIEvfgjapkcNVaeemxTUbhBuoirsYGdvBmYINjATzqjhzIWouhSCMwdvxW",
		@"pBZDAGEzaTuNryqtwxOZJfRtrWgyauSynuSRmGzvOmPPFMXCKSPrlEKYmWaNyKFDOivEBLSLyINOdboSRnOmmnvXkuEECbfopVJWZZKDEGgmdWfagKnXhrTGuRhHdqsLjGzTyqBwvRF",
		@"TgCiKjYAGudqimhuyxeCmReYNxwqinbVGhukXaJbbfZqLwEyfwWZGaWPwpfyrkuIQulaVDPQFRaFBSpnwwHgivZKeGCPwvqvdpsYfTVdmJqERtIEZVoE",
		@"FvRXHMklATnLeaeHQKNqXBBiYZJIWjfMecTqrAaVyvqzbxtvRVfgapFiOthducDVyzaUtxcZaxmYRrPMQEYfjNnAOvvhvyUvRewCEKUVAIynIoDhlNApvsqcJvJmUxQiKXPBnwyaLZegzlujKxm",
		@"vOqsTeVGHCIOnruIwrHCibDOvaKtVtdoIfmLqxucxuLHndXfvIRrMOGDTLDdnemnUsYQOIoPlVcVdLnBkhPzNHOogWzGuKCyjcdUuTqMSNWnALAFmQJAHwqmLKMmkMvimLCDzSnUnJUdEQkFOl",
		@"lIxpTvcuGhahPIGwocLvwfIRTeXYXBdVEiByTAYSxUybKZmQiOlbTaSPmkPsdquBavcCPKCAQvZGcMNlXpkStZtWYRluobexOjsfcxHghhVOVxM",
		@"SeUUVBtAcoPJXbXUMWjtNPicygpxlatvBophRSePMRMDUhIEWeHQDIONoUVUTMQdRbeaPIjnnlvGvxKRYdBMjtXaOZoiXWNgFWXFYmviHDGpOTIIqKYAlQwVSkoaqv",
		@"AnxRWveyvnFJJEIVOQTlUmxVbpiXUXjoDQyxafCRDnLraQchlhTVjoTCLdbkKyjPWoLoGwJjffaGQOFETuFvkktsWnlYboDrOmRDcLPhUtgfQzJfgacVDkcgmfNuTsNWnNgbGqJgwvl",
		@"rDDlTbWkvbuucHBlJmZpfmEryIuOnjmCUbQPEzJMZqWZtObPZoCNvTSoZKEVvSnlcCzrjKDjLCCNiVLwLewBLjPfzIKjaplzYLPVanYANOrpWo",
		@"gPpJBVRUpxeLbCYgHSdlXmUIEPvMGznjEylYxvSQqlYTbxvVcfGwQnDnzAXyzaeFwhHAuRPFTnbLIFSClHTdSyugluFCwmMchzAjkjHiYQmECzAiKYFzNWKXVwQVPasE",
		@"UABzWnjLeSBDBmsxrrPjvoDOeENYPFOiCOgtxWMHeWGCWZdYSiWqMsdSaCcwStypscHYEKWheWFsANzmTVeFOferANFcoHlWCczIDlJsh",
		@"ANSwXCQjyBoLLIBZSRaLgTGbQAPnYDRTXdvWhXXjRQavkSRrijsxvSZJdEurLwdBPvnSytKJnwyfOiuutOhpGunRTXbLuGQQqYKCKBcospERMRwZZqtpgtKtvOP",
	];
	return zsKnOyJHIDLkXxX;
}

+ (nonnull NSDictionary *)WUYMymZvonhkvxpoi :(nonnull NSDictionary *)MvTHZeElLCkMOtlrzT :(nonnull NSString *)XGbPxnGmBAbnMa {
	NSDictionary *RmDQSufTwiWvGDtMRe = @{
		@"rChrcWqFEniaUFOU": @"AJnwnDdTmVHaHTYwcOGaUSuOKCCFpvdxNbMMvdfnpDhhAWTxUzQPwbAkYEMDlVjOLlPbPAzSkmQTQFyfuvHSpNtXpJzoGmuqipneHqbmPiRNXydmwKELwMmJRUKDvA",
		@"tKogLNaonZpDNRV": @"hpcENBcdWlBECmAccEoWVdstlelIcyhbQTvFbfmgrVGjbglhIyGVrCWVLpHEEuSMEdVjBKBFWwYbQKPNnipJRENKbyiYrdeNDMnhrxRTTcLlZUxdeQGMdRAGoHGt",
		@"JUcscISsKe": @"FFpzDqhWtTryiAUflPhbiSsmuKgOlQBoomenmvtCGvmthZAaigeXNELOjvYpCvdEMwhWFyemUqdxEOMVGlCpShhNhpSmldCuLdpJYM",
		@"CZIrmWEzndMAOFwf": @"PWFtjEnfWWcHVdRZdgbcZNsgNIqGyWIpGUypULalSbqyZbPFFstggoljeyUBTNbMqEmhXFBYidLyGPTrBvJCREAIFnaesXCtnZSdKLPUawNBvuixpyhRejNOdbUA",
		@"beqoEbOliRB": @"FNEeMlPvQqXgxwxWwSXFMmMmmoMeSCvotKYZSMcwqAedPrpBVCvXBDuPPjEoeedmFvVsHZiVTjnCcqCXyiuAEIIoFWFSMuNrrqfZeo",
		@"lfCAiyYWOJZB": @"auHgUyGuSnOoOjJciHtKuxAChrraIUiffofOyxiLxyJLdJeQnXsAPxRpgJQAfuQmJTATKSZZgWlmXaqroDwLUsFMxPuKbWmRuGvEbnbJcSHnUKJeZEMBgWYuJOwTHkVMDyVaOboJfhCUyBz",
		@"tZDLbqpDbtFIzVufl": @"fAzLRJWFDUOmSMDHBTNGeiLaOtKKmAfyvbmXZHAbteYAgDLdlLCTYSXkPKZARUvZxqAdWdynihutnwQCzQMNjMtPfvDcYePRkfMSi",
		@"uYqSEMuVneIiYGUo": @"MUfUJjVgTNfVWZaCvVXzsFKOTfVSHNFNGTdtdLlKEJyaovSaMrPeQRBiyyweRUsZyVnaiVsZTtBjtjyFbIjVAgWEtsARLxMkLkyvdlugXGyGcFIffX",
		@"ofjmgqeiEv": @"ZDvfowZFwLcgyKEfojrHHmpDgXFMPnFOeYRUdxzLPNnuOUbsAzJSgKaSgYnWBFmTbvCLSleFlyhKZSAghZsZVHXTcdEktWxvTtvldexFUKDSglcNoalZkmawAKaFpG",
		@"nTuRmgzMDn": @"GmojoDgqRUPAmvazZuFZXNnuUiKcgGVQZxxtNAvFSILEoaVGhHYlBOPLcyRsTlkPwerKZvzaOSSxzLdNhbEQnWGUpIMHOvhVcdeVksUwslyZcyOVdgHEIXIgJYmmU",
		@"qpEDRefvQnXaS": @"gIBeMxLsCOnlqzCSJhtkcHtkIFUeiqLoydsRPqZbpVHsTMFfmmrQQhJbmqUVYCaBBjnCQAxvHsMtTuxnEpREmMNfqElnPzMFjhqEIJIWtSvMmbwYzFBHecCTkNGIUkmmqUCYfafnJMgNHVvuPZf",
		@"VYRPhXHQCstzlJb": @"FHWeTEBENKyxRRCWDxAcwzDsipZKCWQxkiaKeOxwCjCDEbrvTTpuyCbpXAzBMbUZDbtyTbElRHZmGgZQIkLaYXhNlGlUBJkoUXpyFwkctAiSPhUdoiaoYlQjDzogBkGZrxarYUTKzVPT",
	};
	return RmDQSufTwiWvGDtMRe;
}

- (nonnull UIImage *)QNidrIqkETbBqzifr :(nonnull UIImage *)drASMKhAcP :(nonnull NSString *)GmpCWhveoOsiVuJjK {
	NSData *brkNhbufVfUI = [@"AjcroPAuiPUEVXOxdegZCfocaRfjZhhdqYJneNvyKrKSlsceJvnRwDTDkAcvkEGANsnCXJNazvbikTvfxChWwCiVrhFZiBEXraoSzz" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ZuCEgdWuchhS = [UIImage imageWithData:brkNhbufVfUI];
	ZuCEgdWuchhS = [UIImage imageNamed:@"ufiBsVgzfXMyDqrftlueEJsmXdQYoMQpMhZPGfbKQOeCLzCCVKXNsSPWdWtdfqDsQAUFFYRhYIfpDYJRQeVEvqwwlgzwVCYpxVzVWdpXIEKnklMWloPkZaQumYnaZtuxNyMuZmbzuV"];
	return ZuCEgdWuchhS;
}

+ (nonnull UIImage *)fbASEdYyaR :(nonnull NSData *)EqhtOEMGsqrcARpuoPc {
	NSData *WBtssjysCkVSfjqQUw = [@"zDYVuuGvzqUIaLAFUsgRwaaSzqBxdaucWfbrIarySroZLrguolqFumZTrfxyzLhkMXiDGzYhSzNDtGysNmOwawKtIiiEnOJFYRWPKlMYUGTIUdpwuOlFNVGKwvOzesBPULWIkMv" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *WwHinGktQsJlWbe = [UIImage imageWithData:WBtssjysCkVSfjqQUw];
	WwHinGktQsJlWbe = [UIImage imageNamed:@"RMrwqmMpokUymfQQyQKLDegTrEafGDcUqRbAyGAUsihiourxHRUHkJrzjWUUQuftGYWrnByAhIYOKGthlzFBjEgdMBrFZHBgIxfWkifIjVJho"];
	return WwHinGktQsJlWbe;
}

- (nonnull NSArray *)vLVXgtlFheDAVZ :(nonnull UIImage *)xwBReVAUTbqqPS :(nonnull UIImage *)yJSFrBUlFhyrlXUNzA :(nonnull NSData *)SOtVpylnjuZ {
	NSArray *acBVeMNRlrotOJH = @[
		@"OzMpoEAYpbJmibloaqaOpUkaPgVLjAwKVkQZEuupCaamQsnyNHoTGEhzyKsRetdGZawGplLAofhypCGjlGykkIZDJUsKbXPSXaYESKTDcgrUSAQOvYlrKQFuhzN",
		@"vSpkOHaEzqLbJWYwoFnsmynxHgoiTZqofOhsDIiXluLblmidBXxKsCxLoSmVVPUAOsmbqjCUYbtMfeTKsHSWyRKyTzUuTCYpIBVBHZOBlpPrXSQyqlDXbrMNDrsrLJLXyaiDwzgNQspswxfbBb",
		@"vUeXELdtHwUJGcyGSWXyoxsEvkjxODUCWmFjupPPmyRVLdVYpoHrTfLFzgsKqeYBAwRGumEiAReFpkdyTOyetacymdPOsPjREsgHxcxaqFyrNRlmDwFKTtaQXX",
		@"CRBjXWYlgEeTtLtHVWXzCSFnBoIMyQDAosSFZbytmSRzKAMiJeqfoHMonzsOeEhNIqguZGYiyDHONjCGBhfmWyBagiWvhxhpvBccnyqgFnBJswfdLAiasjdHHRjRCsAMvBuDlpXhLO",
		@"aylCvcmDskBKaaMCpNrEtnkobXfxdfYcISJTPlUKDTREWYDAiwWAVrCwegdXOLIfUYqLeeiZDBkqQZSlOYKDQtGjpVlDOEfwHEJxiSMGnabtGrsyXrxYmIyvrjeBRZyuvuEXDfmbzos",
		@"ArlCbETyxfzIadqtCJzbHghJtDnTCQwbqpViVNAdmljAFBtCHqiWajcjfekiNBCbxOkssBuGmDIhHybUDQvGhLEMglHAuzvXztYeoayljfg",
		@"IgPYDYMcqydgAUJoaXQljrUkYeRKaJsyZvEycYCGDaPTJuMBnliBWRHwuKQikBLSpHBWxVQcyHgLBchghGbyTDBijQUBHarXbSZiIgxKDcdrCtRnLzjMhTMWazTnnYUyhxeTxWWd",
		@"YaEbZWxvLuLVLCnSidWAEOPsCLTUtdQeWTrHiLRrWWjPdBJzplesiElQpJMBIDTlhWKeQFURQwTGEUrXlWqmlMjSctiPJQtKwcDbUTGoGuLdaarSCnRhApswP",
		@"FDESFRQcIAFLgawoEWLcvcNLGJJgRATEoeAVbQzoVgpWZjUMJvWmZnikGeoYqzWkFkjHMidEmEZQdKRPTrBWIiYuLENyKHUaSfphz",
		@"qLRALNobNRVmefGdcUQybRFCtKdXDoIjuWfCkNTsBbLseDDdniqWFiacqQUMHcqtbxfccYkpFGGqNufdlrJcpvHasxXZTZeXueTqeAXDhfboDSXheDlxEoiezJIMcFHAJVaXEfQJZjpqsOHw",
		@"fXUpmtTGUIeWhQGJJXDWjqWXHLjJblKYDemtMyxTcMzavJJXCpuOaJAlmJaefHsReoTIUsxUSNcADIBhcTOJxfHozAyoaJiHnlYwZdKGimbIiUJRGESBH",
		@"LlHeFOkxqwTpeEhYrziNGDUnnzMTmMhAJUOLFdIrkfqzlxOMAkViRXhbmhxCvLchdHxdnaZqJuuppoSkvhnCnRugCHjFgdYYYSnQYsZwaqEcixZuQTYgKvUIkp",
		@"YISYiCpbBgzyZDABYLkAdrDFGiqhYfLAyxhRDkORWqPzXNjUHlyAmoIbZMQlSCQmHukOHHWiGJaTzXITpRBVumVdlqNEmyyywziRWx",
		@"hRnaFvPScUmDchjlNBJuGgTCcnURVkzUYkmMKoeDsTtUzdZIqZUKSWUJiUfdyFfbAApIOZhasVYGkwgXaAoPUQcqMajjzHlbFZVJgMWnhc",
		@"MZcNngqorwAbcQHSceEfMLFVwhGRavxKWaCRpdIzSzNaPCGbPHgWjBHYcUTTlWqnoxjMGzqRhqCRjplBGrWAbICzwcVaJSlzUEyr",
		@"uhiPwanMxoBKHygpCRuaqofpFxXLwNliHzjtKazSATycNhYBuGZylePJaKPljlTUOHpCLIrzqThhxkYlQhdnHyYzZCkVJlYjNIVrMAoMpZEDJfyyctlwyYZhFGcPOlgJxLoPRa",
		@"JQbCjbNYnRjNNVVxLSJfWYBvUwXrtcDmTdBFDWizeTLHFvpbAulpDFuizElzLsIYWFJcOMOmempBaNWNLGfrwutvRrLRFDcazKejofSza",
	];
	return acBVeMNRlrotOJH;
}

- (nonnull NSArray *)PLmOQimyEZUiV :(nonnull NSData *)ptbmTieSDzRoeY :(nonnull NSArray *)jTIPPhAbWFV {
	NSArray *dkjcxgDEnfKOkX = @[
		@"RRIAeRraCbIYRakKiAHIaEyzoLuHAhyJNAPYYwmACeiYOelIpyPMJOkxFBOPJOqusLDkaFbClJFDCcUuaqLANmABKEqSihyeUGLVJxYZmHdZOhKKXdYgRlOHck",
		@"abiVtjFVWErZchFOzpFLVBjEcOQHpJhltJzuvAiepVpzmjPDuortkApjGvjUiNBtKvjqYNzTrdvLoqGvdVpXjVedxNMEPXZtwHhclsjdaZhDyUTqFrVcyiVkbFhlGwOJzcqnbcRrGkLflvEox",
		@"EWHEgHbCnIVyUymSYsGLgSCXCtMFEyYLLHZxXKwoNlHWjvGyEnraIeRQwIdZommMUZAYfSiWyYbTeyYHIOnPFnQEGuOpmUJBWWBvpjoGEyWO",
		@"elYIDGhUNBhKhNRrPokBKBVpEEWsuyHBlPmBELjeJloqFZtxyMHCZtoQWpKMeTSPMefctmoMOMAjUOrIoWVRHZFkuIHESDcbYtRhUAEcKyc",
		@"bgwQMdtpjpkDFwhqiojIyOPItDtHQAmLNMqdrQeUyKlfnlbhOFyMdSxMuzpnSoMyXeJNHIRjKvNgcvAnqhYYkssElTRhicmxsnwFmtqCtVSBcVmtP",
		@"ghxVxQiuTfLGzvqOwHInDaatNhokRaqjzwLgsQYJBKPphcbTgxtqmDzEAFuQwDyJRXXMkKGbFqDqyBTRjILyaItAYInjAWYsDXibkZNKr",
		@"BacifbLwLFxNVBAuRBXggZsrSfJUBHYGjMSrDjhuZtqGMFeSKFrRhKGxbCrYvESaVyqlrmhRgTldCLreJiEnhwZfNpMPTqbMeBmXigrdhMMuggntU",
		@"TUNPPaagJVTMrIaWEjIPlzlEbCwQBYXuNkLcbGBGHUdBqfOmwzoqLtjkaszVtNrwWtHiXehPAEJkCHicBuIwAMwbFDcrBBuOKYeQNoFvrNytoeowdsohtcXIauilrTQkPM",
		@"uVnDwokIkELHSUwSxGsBYcBuKIJRCpmXxlJmyRfRgSvqyHMdiaJGeYwMJcsBhXaQXWgrCTMMWiAjqnVJTjCKfRNMeMrnpYwtenrPlSNsCeZPszaHCG",
		@"fVIuWOhXDSluSkCqsbAHjthvLGOTIfZGSBRPAitmILLmtdJBJAQZZXATRgKCiAvIALHwjmohgTXISggJnOmADnRxSeOJKlBdaWyJMDemliaETQOlmcJIsTEuzHsPnjhDWiDlrFemBUZAtsVOmBo",
		@"gKPxKcoUIJGeFlFTVBpxEebEcQuljDyZRjhiVMuXAnuJdcjrCRswGJoItjOjrGGFytBjRLYjIrhpBCfVYbOuIpKWIwpNiaJZNObGQYwwuiIXdRwdpssVrnrxbpEamWdmf",
		@"ayyjPkRJPElYJYsrQxBgiqLnkOzMioLJtGXWTLaNfVPYgFKHimVTPBveSwYHwkplDraXAeEBoioUPjhdDnYKVsvBRkibFkrIyXUKJAnNkxQaJHshAQPc",
		@"trDfROIFoDSjdzDsndlwUeWPpNhhAlcWrRuqlhxsEwlcsebKRfjAjYFXvvGRIogjNNHJCdCgvtRJtHqEfMaRjGoraTsiNOygEKHiJFTfjrY",
	];
	return dkjcxgDEnfKOkX;
}

+ (nonnull NSDictionary *)HHNkkpfhdxrg :(nonnull NSArray *)ybFYvzuoVJkAxjtn :(nonnull NSString *)OUgJOOshprbwLkJVZ {
	NSDictionary *WhMCrhZnqaDz = @{
		@"mXCGHPerDaOyfFuAbP": @"KDDBaVtPIdgqwgqPDfFfxKdQEqpaTjFiGufXlREoyguIBmCRkCLTPzkDSdPmiinnWdArRxgHksTxaVoNQQKVMPWCRYLwfWZlwJcQJcSWwzNid",
		@"wnBZxTjzhRLac": @"kxwayOLHAavxaCAZXuATFsNPPiuVxuAtwLHjSEIxksKVxrKITmwJPeHZhhTydHkkRdzntStNOFfBjbVudCUInxhjVkPddlCFWKccpxqeVsWzLwERrIXlBypisOrxEcOTBxTJyivuLhfkTwE",
		@"ooTMhajjgOAR": @"abaiBDKkoeJfPnPASgtBNLWIoYCySBtnFttQoORCtqiiZRDlalMSxPkTikeqVEXmHwwRYEFUkxcVyYgQvLbVyVDCjaCFZfIMXHnRrpepHAEOqRZraFnZmekNUyZewb",
		@"kSNDzuAVxLPgGc": @"MSLLCTbNqjFMrMXdvkYHNPSgfFONrUDtwDALrwbcNPEnkovRmqgiUeHJUOZwWMdeMcGgBhUWycEnhPLYcOnOTnXIaLSjvwmCgrkDtniisnScUKd",
		@"TVNZTkOrhZhzkvagL": @"AcVaqixQNbcINirrVioPzarMFHKEEpQqMLCVSUkTPBOyKRzHyXAtpvcAEIJBwbqztVuPJixKOBXmiqekcMLTtMGPBeiNkLQGoByYvATAjgHJtYMs",
		@"zmxarpJxdSxELwwz": @"FEurLbKpQrTEHBWQXqtRevnUxCgKHrlUckyabksdbCriOQEWzgWlxgyCQdCNaoTMuoHRzVAuXnSGLtZqzGDJYxeYroOQokezdWWlHCrAQuFFuC",
		@"jKkEFXhtHd": @"nDSHSlHflcqxKGOKXcLMUewMMRXuHkynbtxAutesHaPAndsLCBRuNdYGqNZSCzFdtbwWTSCZglcFUmexkFrEnGafFyhLBuldTnfMCwiQuvZvGzCgfpmeCMZNS",
		@"TaHagrbtMuhzrWMxE": @"NIHIZwqxtmbWEJKOTxORKVrVfXqrBNAORPHmsqXKNLfPATPaKBxijMZEzIciIGaMzvDJvuWwXXlPNBoHVAZYqZzimnKhqxhZcshpBkXtIQmjuQzUbyjtlUZXouLqumaRgOVkSOARTDmgo",
		@"imuvMeLSeYgRTmccwKr": @"cavhFOUToTmBkksGbRiLmLtunZmweuOhkUpURDEppAzXxHuXhtrKBeSjZAQZmqobSIBkuBltsWYwQVHciGMGdfvFLnMsUAdBnjGjHzCGtNHkLy",
		@"ZAdxQGNJHDMOkSoGhZ": @"BEdILxesnuytXuivcwJLmqYWEmOpqsCJvYHcyIrXllTXTaboCbsEMEAxgQSuywJzCPykxRTkSLNbynVzZSOOZARTpOsePULpbALQQwPnmXTxEXXfMyUwgEnxZocd",
		@"rtlJxBaiiiSfl": @"xFFvWqeSCBsyrtKzxCvKyIPKOiLLEHZnCUAERpyKukWlFLJJTOOypzgXpLZRHzvEigQilvCayKPXYIvnUniYJgpHGcLeCEHkkzembnqUuvrTfZLPFkICo",
		@"WUJqlEahRyGFUn": @"ymIWlSWXOJPZedDFjblgwtRKguEFEMBGdpyuRvunRkuifOPRbCqjIRdIeraUkYCADrEJBVSWhImsWymQcaufaqRiTgumnVOQOUYtexBdSGHI",
	};
	return WhMCrhZnqaDz;
}

- (nonnull NSData *)vCJCXcWEDcwXjsBRh :(nonnull NSString *)ukQDLblTrmVWkbYHGY :(nonnull NSData *)cwHrmwmdtFz {
	NSData *EXQqUihgGqwkwMgK = [@"TmTEmbecsJRsHAGYbBBnBHyIOXZScEXjgiZolxkDAqAvkWpImBFbvXXLIqxGtaUfizphkTSGYHTVsidDPMhfETCfqXqGVQqMfHJzViNqpCvDMNmnkvEajbpMLFbIrADsMSYvvDkYCztRVabKA" dataUsingEncoding:NSUTF8StringEncoding];
	return EXQqUihgGqwkwMgK;
}

+ (nonnull NSDictionary *)XVReddFfZEKKXCqpaR :(nonnull NSArray *)YFlaxjFpuPo :(nonnull NSArray *)plGUkeHvZRCrDQO :(nonnull NSDictionary *)BXvIpWkwArKnlEZrFhZ {
	NSDictionary *rIdCdxIDMzqGyqgmz = @{
		@"wsLwSeirDTCjOmCg": @"POsYrLKaYPDcKTTPrjhSOFXByJwziwhSYVAJCJLEikwReCYtRapLXHGVlQOVZuGXPUuGlNcyUMDJQvUEZKKOshTrhbzloDajScwtWvSYwXB",
		@"xVwnsARZdqVSUPLCcQS": @"WcDTWxjFzjwDSGZLZYhyUoVHBPOZRLVGJPjsqVYoWvDlmZOFWnIyfnarKRQTTtQHVuyNjLODhTOsHhLAosatSXZVdAerEppffhGLwAC",
		@"cKbGjRLqAdnE": @"xekIYPTkEoBhGpRsmpDcsCSuLyIUSdmSCBugjWbWDgopBEkrgdiJpGgKrxXfDZAOJMyBMfUPMlcgpThTbvySHbOrBtoSXgmikTwXZwvNhgVbueYRaBCJdPdWMIAfJhYGSscRQdslJsbiKzzRQWg",
		@"ejPJqIAMmzEwld": @"PWLebUMgIYCrMexuabIoeiixfDtDFJnoMMENHejQUsusNeTBpYqUTQqDZBvNEVvUpMDIejMCXSLhRFXMYTBNpTgEKKctBifoMxFQWvlWjeCAKkGwICyBQnLIKKBabWpW",
		@"geqkgznPaACLdi": @"eSTIjvNEzNMZlqMBNHaUWzlsRPEeFyghrdWhfChmxknUvZiQpmBFMbUlabvSVHqHjqYDOCoiFEQBiomhxbrrgREUyiXOvsDthTabSsSFlWtMgYRQeGija",
		@"bsAPgmTXJwnK": @"dkqDNrsDphqNnKjTBiLfeDmWaDtsddUnTKNiyPmVfOZKRLsahybKLblyWbrDkVGIRVOQtfOgVqlCENPdvJNgnJUjvLlFFAlcgNwljcfOccORdFSiftRGGgeXIToghrouifOp",
		@"toMQfgmCLXWyVy": @"lVdEgXpExVNRXOzspjKJdUrvLgIPzpTzFaVkaGKbRvkVINSyBVDPjYpHjyyILJmlqhsluxjhavUXuYUKRkfjiTDenhcqfhCjKtnQuhpEhBiwBSSjyfgANkGkdp",
		@"iVBNnxJAUhfgiAjVg": @"IBVWTTcuyYBIRFcJkezXMcusWWKGAMecdcvitWiPteKgluoPaGsYEmrtlSVAqoJNIXKtCTaYaLxySrekYoCQFYQlLAUdUDzXCIMDRuHNBWlvsQflAZZKHYbNwfBPDpbdVDeDb",
		@"xaTXZQlfiCd": @"nNcxBGZKJSitIWvWGezPzCUriwDdTLGmMOeYndBguFDPaPtCmVCRygTaohlOOzsIjUieWAOeeqmsBvHfUpWiMoPoqpOrBzlpPGAEzpaYahGewMPz",
		@"ozfIXTfpYhVpssNtzKn": @"QoxDCamQPzcybpMGQCVMKIyiwRpGKdaKrUSufhdUtShmVQcpugPQdskDfhOPttDpHSfNSurDHSPdyvDQUgJqDoIgGKvApDKpAODznh",
		@"OPxisnHKKAilOniWFG": @"MFDSdwtPcOYrIQmUyFRIDnpQqYiPLYIVetRqLMBEeWwRKnLGbOXaOfrAhopCkindwKAkqzVRKJdjImaAbwdyoqQUqoliYvaPcFufVfUUdvUzGCORPTrZciFsXFTskIWpYHtFhKOmvkTWpoppD",
		@"NlyRBJNRAFxeoJ": @"YMrgtIsiAlyRTtQsSfpFUikXrYbjpUwxgWyYMAUmvbHkqRoBiLMPwDDfmGslbetzAVZXBtjIUQXRprywCwSBgugBFTdYXchzHCALOwAOlIUFKTYSjepeUTdJldmfXWSsHgUBhqujmGLieM",
		@"KjeioQdoloVwhtrwlo": @"aZjQjTQzqBChzQAPEvAkHBaNtjOEPRItqqqhvcbPykmphMhlgCWMMfTSyJPWtmCHvFqONKBWNJEwmnxEoMAQfoqMcTOAaIWPQvYLHnpBnivh",
		@"eHyJsMaOSGIlaukO": @"gwONqVMKVMUqiHNOEzAonYbDAsspKazjuaUlpECLsVuPvcqlerCosbRQKVYWezwRTOYNGyaDWpcJIFnpXpUUUhoqhIVVTmkOqnDrKwGaWcTyTJscKhnaqQTOYSWHdcnOmFtNgklyS",
		@"yMgkcKldVdTNWyqop": @"tVkMJuRvnvLTGSVDwppGUqcAeRQBMuEyVwOgCHxXVIYCbYlfPAsnAdUldBByxSBNeeAQeEOywFqrfDcYHJXhgQJGdsfZLgrzhRqoTipQyYpxy",
		@"SxzIMnsGyGZaOgHKlG": @"EvUkHzplijLIOmPDGQZcjUImzIEFOgNHhUbglCFOmyEFJycuhKRtITefSXeIvnYeYbUkdSJzrYOUKILwtwaVwxoyNuEzhgmyravKqZQfNexsIKmoyrn",
		@"xUnyyYjuXvvZOLD": @"fghthZpMUkgiAQQNUuGJgKNJSwJKlkuFZDnpGjXsnKqGjnzwCzQhheewYxcEmEbmWvKPEQejOoIXhqNVsyKFKQeJTwheAdYTbtVPtgKrBriEkaeieUuEIyqtLqCRoxvxx",
		@"ZBRHXdHoBOMeLR": @"lxwOmMzDKJflBuRQTfWAIXZdLbbIWjyToJeTnJWnoKJGmLtQWuonfnmirfQXGVscDvSLbPGnQRAYLWWylgQtvqoJtjLkmBNeKRBGyKauSnHkaT",
	};
	return rIdCdxIDMzqGyqgmz;
}

+ (nonnull NSString *)fRUxPwbCTHaJsm :(nonnull NSString *)RvByfJDetTeG :(nonnull NSArray *)CswNiCfrMPnAytTqc :(nonnull NSDictionary *)NWOEqIPfjvSEmZALoK {
	NSString *ydHpdjNwBsHGwG = @"MdgQDYVVakrcruTutqobPBpxmJPSmUMPcWUjVNqdaVaBvkBCnXNbzBrhKHqBaeAaQPcOWwxejqejcksoZtVVAjdrcCQWOqvqsohqtfxtajG";
	return ydHpdjNwBsHGwG;
}

+ (nonnull NSDictionary *)KgnQxNnixy :(nonnull UIImage *)nDgKQsmZyFdNYApbr {
	NSDictionary *aParSdfJZfbDdwghYAT = @{
		@"ZwtRXYAKabQyt": @"HthoMdOjsaRaDXpnODWbdalzJwMPcVJxhCJLhxSVwDgwmlqYMXsLPrxSnqbJBddwPChmutKNGmVCqvWHHfqUasDMaAzdwhbzBRnMcijxgEJNMApYAOVSCxfpTsqjgPooXOkSpoGqpHkQusMYThqO",
		@"oJbexfZFnSFBi": @"BfzMMFSFEYbtecmVAgFtxxOfNDtEsfWCbhigtDIfyFyMzQoPCNTNpqrGZCzRMEztAzWIzrGTERgyElUSZcJFNTgPrAfQzNqBNMwbrCYbqggbD",
		@"dzveJKFUaL": @"nyrfvMuLptRIUQgtmReEGIPSHxSJoSfFaYSgFRNivliHclDBMqDMMRtXsGhrMIETZdAnbNxevZNfSLHnvnFsjnywueGFvDKlTTOhQXeAOfxaL",
		@"gYRhPWEWpPKCWvHny": @"ohzzCFquTcosbCVvUMwyZCgGfaYKAbksxceWDwyCUYLAGuTmZDyCyfwOMOUjYJHNfBljjoMOvhAgBIqMuAioqOOBeVhpjvibnUplAzvhqKVOWrBAy",
		@"ODnTuuVXjYEZZoB": @"qDrpiyNWSsdWEGuMKgVDWYSetbaUsOtRNprtthQmraGcVqXKbpEuRptlGDLILLhWPsfSxjWujCaXDJXaMrIZZgYCghXvZkzVWIGTZcmfXUlliapZDVUiqqxgAZYAxVDngiHCDERWvE",
		@"QeIPViKsFobhYZbtT": @"ROLYFVnuDvZmtutPewThhIANkaKPkMLSfYYnQnPSyUJHBkJmwdbxSGOjTZTVqRdVwSnmPybbQlLTveOoCqSGJUjeFhdkllEXhAevyJFBwpfdHBkmTwyMDbrrENNHqubpGPiIkvLWr",
		@"rDJskuPAbzd": @"EqrIvPQsfFnOHgtuXrYGVdanZTeqTnIkQEZtLNfsodPZgXKLvZdvtOiLzwvHxshedVJejfbymVLEAtNpldmgUUWzLwxwudjzJQSwROTvJPzfyNzeXtAhJKjGLMPsCJDxgNzcVfOVLTU",
		@"eCHZgLwvXDf": @"OKPchbBZgRncDpqtzwHbhLZJHiuvYNDjycVtijehxNJpyfSOzwyqsvmfZUzqtTtbJNKnBafyxheEzMWFldCxhRlFktwYZsYIHWjvqpJoyTgUpgkPKSJWIHgJVzkYMSltARin",
		@"VHAJfOuohg": @"NRBfHVzNUgdAPhUVEDuEeoCWbZJvhDdiludLSqkKtCsAFQZqgElveArqLWauNynuoeuXphbcEuHHkTabYPLPyTiLshUgVNQqdQixBJcTsGerMuXnT",
		@"jhZKfyObDbpWArqeIlL": @"kwIBrxIJxfcHIhAmUPJWdLKxpkeovGQvnYtIjCfukbHciZshUSCIFjBRMlsZTNrxDTCyEGlqJyZtENTIzxgTCyONZbZTrWHdcwDluVRqcEKNKcapGUUSBYhdFmjC",
		@"vIZAVOOtwxCNwMLkXxs": @"moIqVjaabtLNIFsWheawndmAEOgYAAWCYwgniMqrKrSJOYhKLnkOCIOyOMQJcXhsugckoffXsIFmExyQeIiqshJJRegUiamuzUgRMkeUhREpEBGgFfovBT",
	};
	return aParSdfJZfbDdwghYAT;
}

- (nonnull UIImage *)kJiAgDRhgLImiJD :(nonnull UIImage *)LifHUqlwjH {
	NSData *AXjjtVwmPTBuA = [@"uCcpgRYYcNurPSnfGPFqzbrCRraDbnuUdAcNUByqIwZycCwMSuWVIWrAPnTRXcOHLaTBtLGYOJAzURRSOHOesWMKraOOsJWZZXolYUIrGbwnaGZ" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *NJqIMPmJdYpGqYHxNJG = [UIImage imageWithData:AXjjtVwmPTBuA];
	NJqIMPmJdYpGqYHxNJG = [UIImage imageNamed:@"nTVgKMBwXIkzmTpkgXiWKQOjEtRJEEFzzIfnLWPcxyAevjwqefsZNAmkzgJRNoJOewRcVJHKaxpOxIdyRLXRDdxTmOddWnzmknQnMuhv"];
	return NJqIMPmJdYpGqYHxNJG;
}

+ (nonnull NSData *)wUCRaffvaiN :(nonnull NSData *)oEpbZYksmGOOecen :(nonnull NSArray *)boimxPYUSdmnwXbLDzA :(nonnull NSData *)zrolCxRioqU {
	NSData *WHurtlHfPeITzJdmq = [@"CrmcBeoXVdeBqXXDoghBMUqErsnKOCBpsdlPhAlsiTcZfRjXfUkrptkjOZtPIIxaJVRbtHgmfPDjKPKgNDuHQSIBoKndLSwQoTnjtZcnZeHiqFuJmtCevgU" dataUsingEncoding:NSUTF8StringEncoding];
	return WHurtlHfPeITzJdmq;
}

+ (nonnull NSData *)xXmWCTDZTIW :(nonnull UIImage *)APjDvzfORLCSudHmkAT :(nonnull NSDictionary *)CsFaKgGSlXIFv {
	NSData *kERXAaQALKhwTochPnK = [@"VdJTzpHOkVCwmiRwodGqNqSkystTLZDdgvjXxgrRKekNpiGDqXUSwGNbjTExTklEKhnoUCRcFtzGWFWTUUnNznVtVHkkIJEpKPzHwUfzWaqpFfedIMK" dataUsingEncoding:NSUTF8StringEncoding];
	return kERXAaQALKhwTochPnK;
}

+ (nonnull UIImage *)Oevaaytojd :(nonnull NSArray *)AoXAGuexKPB :(nonnull NSData *)lbPGGktEEItkvv {
	NSData *CediKBuJjs = [@"ahfKKWfxLzzlMJoRnsdcDlHYXwsjQWOboibcuoETVAsRLRGCdssKqMBBlzFnfBwVYgqIPrBvjSIbUIjcwhdwtirdiQyAUZqHMmnyCuchQglSYot" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *SjOOBzSLDJUzk = [UIImage imageWithData:CediKBuJjs];
	SjOOBzSLDJUzk = [UIImage imageNamed:@"arUsAEHyilTGhOumAusHUXXDstUSsXaIxArcKAPCLqSBAjHlzkCIFbmsgKeBhoIHGTSaouVJSfIRwlZWBKvnUnWjUFqhtfmRZsBOasBZUQNHyoaUb"];
	return SjOOBzSLDJUzk;
}

+ (nonnull NSArray *)QVPxDbIWhlFbBhrL :(nonnull NSString *)BnYmRhsUdwgcCgd :(nonnull UIImage *)yRjuTDVQEzsEjy :(nonnull NSArray *)lyjXAjwqVakrwInS {
	NSArray *DOcHGJSevzmhyigM = @[
		@"RIUaEaQZFKRUVwAEmkPOOxzoFifkgnzUyBcupeZZXLOHyWuxyWWyyXjydKhCAYSGiTcTyLGquzWSyKOmehrocUHfGDmyPweaWyAUsWZyKYXZrseYPPkw",
		@"qRuikcAOsaPCRdnIbCHvtScrOWTxMNnvxnGwjwPymsFvJwcPfXzGzVqSTaOAaHWvmDegmohpFsqcxGVlGpRJuevSqjiCBrPIIfDJGXLPU",
		@"WAopMlsMEFUrBAwoXoJPHTiiIgZKMTGcsnYqDQjVkDgrPWOXrtZAmULAwWUdsAGmZBhcUXXvtNRnDcCDLPltqORgBWkuQYfkDJAxWLhO",
		@"xzvgcVtDuuDfIWbHgBkCPUUSpIhwJediNsEmcdvuFMgJqVYHCiFnoUpyCajKFVsyxbugWMmMeIajJRQTkvNSdIesTmjeSLWwHLYErOByeZcmfpfgreNwCAItrCLHkpTegYxEREwiFio",
		@"mHyjeagrkOxwsqfNitcvdquKfjjKuJuYgUUCGpctZJWEibfZqHecWfyuyclDEfmuMGOxnTzGfmKBCQvHMQwsbMRnkgpSRfceZUoxgGQFokLiZtpeeMvAcMyMFdKNDg",
		@"HnbnvIQhvRoeOBUVxuqsXtkhzjyIAbzsUFSGvvGVBXFnPnwZULLryjBVBvXUcwcAlZmZzlJvIdtTLQybAJnSkItxpFyXFzaNfEovLxhearDThDPChuwJnMrlaQmwZEkvkzLiAMIaHrt",
		@"FUuLkcqOSXHSwBhomVVxqWIGGyZFeVQtWHFCcsUqrHhbVqYAgVhyUONGLKuXEeshyZMNYPnURnKroOfwSpjnXkfcgrpkzYiHjKWuuUTNQXyZNsqgqXyJSiNuJTneKDO",
		@"HWqACgsuGULZdqsVJSmLuOdFfSaTEmSruuhNFDMTnUSDzSMhyKQjSjtxupkBpZQpXEcciDxlEVANXIcJSSpVxDTrZzXuwszntPMUnuoXMZRKjvQOCLpefmYHDrtudJkZAIQiQkhamptDeyJ",
		@"BqapdDHvjaTfrsiKpJcAalPMwEXSqokRcPvZPxbaQWDiVoEGpMvuItTvylEbKpbAeIQLTxkyqPmeaxqkpGQLWGswysoKNIkgKElFeshSerDWaOCnVZUJbcnqlLFMJVxbxhLvOOVjG",
		@"tiIXUsigoGxBtFUCCNnODqSzOzwSRbBUASBwMRaPRfkeESMidqxURXSgbUqsQnsYluvsVnHAZKLuGHnWFRFenctMQVlvjyHgqjPIWYbxvpxFZpkkozyaCSntupfGQVAFqGjEUAYOLGIaF",
	];
	return DOcHGJSevzmhyigM;
}

- (nonnull UIImage *)GbwuwCxwbNzABuEhwk :(nonnull NSString *)rbliSWfonyu :(nonnull NSArray *)oUEurrgzgcrU {
	NSData *XPCLfmMAiFfNOHj = [@"bNjDokMhwUdeyawrJCAfXehOpUsrhSiSoqSniUmRlgMILSUlZLRHcsppvsqXvBNjQNDstwBTSUHRPxzzmgtPkEDtykKpjdqUCNqontyfSDzHnnDOLJfKvacMKotCDeEIeGcEORKWQffpiMPOMrWbK" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *MbyXorfRdXQsKnWWM = [UIImage imageWithData:XPCLfmMAiFfNOHj];
	MbyXorfRdXQsKnWWM = [UIImage imageNamed:@"uBacBViExreaXcbIQsirBkVjFxXFTLdSIwASPVUMDaJiWkPaYVtdOIkmifzYrQcPoKCOqKeLFaGKLtgzpBgCZSbeuBZXbfBKQPhnTFdj"];
	return MbyXorfRdXQsKnWWM;
}

+ (nonnull UIImage *)DalCOoVPveL :(nonnull NSArray *)nCjZbZmyAybR :(nonnull NSData *)oQcMIvVyzzytXB {
	NSData *lwjDTfsWzrsLl = [@"JQYuolWLAIvTKLKmrXSCUGUDsSApTWAsGjIJHJfPKrhDFvLPUscqAMuLGdvxJHYGyVeKwvLcdMJYxwWhLtkbEURGQBJPnISzINXAZyTqlgBDGryfnWRXcHVRKkNCYlhCfHFGo" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *wJstmgSHDmiU = [UIImage imageWithData:lwjDTfsWzrsLl];
	wJstmgSHDmiU = [UIImage imageNamed:@"fIRNrbzdnHYdOrOiRKKJbVWYKwOpgExPsXsCDSDbAGfHzOcFXIVGyJkuhGTlJwpdNZnzlESvNaBoKxKqkbJwaultgtglycsdmIUkZuNknZFAspGDPG"];
	return wJstmgSHDmiU;
}

- (nonnull UIImage *)rXLTsIFIWBw :(nonnull NSDictionary *)AVNQKlPhvBL :(nonnull NSString *)cIaglDXPNoQVgyKyxL {
	NSData *GHoVfQSaRTlYvVNL = [@"umYLmaPsLVIpYuDYsEzUkakJtBFzvjQQcgjSBiMXPdNFljyUkIycLtAYGYUwTgPMqjnAjwWUDBnGCvBRBAUAHHfPTUpyjmAXiQrAEkIfdSdIYVmOsEDgcMxRnBGRrMckukStJg" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *rWQoePRBeqKhhvKpKE = [UIImage imageWithData:GHoVfQSaRTlYvVNL];
	rWQoePRBeqKhhvKpKE = [UIImage imageNamed:@"vYjkHPsMIWOcvNvqOYItcYKwCphrJDIAYtrFEYLCDDdrNrveUGMjOrgzivWjFbCxTZUMyTVqeOPhMwrioxWJrrEMPzZIwRKzqhJRurfiSrLtIILoiemKKkkJjalwFcwzbETWZscsMcsSxU"];
	return rWQoePRBeqKhhvKpKE;
}

-(void)layoutSubviews{
    [super layoutSubviews];
    
    self.name.frame=CGRectMake(15, 0, 75, self.height);
    self.detail.frame=CGRectMake(85, 0, SCREEN_WIDTH - 95, self.height);
    self.imageview.frame=CGRectMake(CGRectGetMaxX(self.frame) - 30, 10, 20, 20);
}

@end
