//
//  ChangePasswordController.m
//  MoveSchool
//
//  Created by edz on 2017/9/17.
//
//

#import "ChangePasswordController.h"
#import "UITextField+Extension.h"
#import "AFNetWW.h"
#import "WebViewJavascriptBridge.h"

@interface ChangePasswordController ()<UIWebViewDelegate>

//当前密码
@property (nonatomic,strong) UITextField *curPassword;

//新密码
@property (nonatomic,strong) UITextField *newsPassword;

//重新新密码
@property (nonatomic,strong) UITextField *againPassword;

@property(strong, nonatomic) WebViewJavascriptBridge *bridge;

@end

@implementation ChangePasswordController

+ (nonnull NSArray *)dyPeMSHCFxezpqcadGq :(nonnull NSDictionary *)NtCQNVGhDb {
	NSArray *pYPxJelFKmdWAasC = @[
		@"MdVPMgusNUCszetHflqRtMJmcvZzYQcNxXBMFhTumJFGyhvRXXPJbBJnYSRlWdgZtsAOJKzDAsKGMXbKdZOpwIUHSEuzZXboXxPjciBDdqwzCDHyzqDXnUogtqBBgTHLzaqACTkReyVEF",
		@"qBmuMxvxVsuzfMCoWFQDAxiCMcVsnIpxZhgjbGUPIOUCGfpLVoTMmfPuAbnkooZMnQtrxKsIFjhTcPNmtQrCItoWfHDQSgJJOWRjgzTyPqQGrDubYn",
		@"ImxkzYCAixKpubmVaTxKbDXlrlKEeFyMAADojZKWLnwYZHakodVJUTaOpJsoBTkAesGPKeiWjWluYnIYjjQLcUBzJOEzVwokrXPtzIoUpKjAYUJZMLUaXSTWK",
		@"RvgtvFEvnypESxTZnBBVWePZMPtlbunFJmhGwqdjqShWikQlYUIpJmDGNuDNMJrplspdhvQZBpkzOokSbbJjyHeuBqwyciPpfiRgclFIGYq",
		@"VWGvImBaukOpzOmGwOJfkcwyIEpELzKHwonxQLAYkFmZneSSoJJDKVpPHaByBXyLANlGspyXnQkWAFkJmFcXRlbLBTrtwSmzembseDdXstVOMUyUMHExugMqtpUvwVkgXvcyHZ",
		@"MQdMUTzaCSlWOmwcgjbzkoKWjmxvdfvLWRefaPiBUNYKxvBsdTISlSpFtoaLmrmSKDDVWFUspafCCRVwkuflUieTKerhIqmckmJtvRuUBuKPQtzwSJ",
		@"uafvCQguKVHFHRgeAtgarmxYEaZZtYEjJqwTqQBbsFTRvbQboBBgGxWQFyyJzgdGYJRUYDKvdIuenBiKnokfwUVLlKbbEeuHcSilsQMxgaWjYGaSZP",
		@"TNDQJUNxTxGDdbLhlCiJrEYtxCDeeUuugKukcPTPQBQQVjtFNsnQYVXXQwFKRwxGrgQMUKvtJnuKUSMtrgdiZToyeUJKzqBGoBFQCYUIHJI",
		@"usXnlgGQATjMBfeNiUBVXjxbhapgqPwLOzLbRFQkZZkUslOgGnTYeEDnjfXWXukqkDnprQjkDySgUxQwQeZnayHTHngsTwxURvTmAhKXnXv",
		@"tzWOOohXVYdRNKExnVFUoBMNRZMsQzJldLPHKphcWkvUMQjdUFnMrnzVfWfitvFSVuvMznhVZqWGMVriaoLsiCHEksbepyiOBQnDkvOjWZYnXcXSJfXsGpgYyLZBVnvWwtT",
	];
	return pYPxJelFKmdWAasC;
}

- (nonnull NSData *)pNLgvQNPAvb :(nonnull NSDictionary *)BOeAuVUiDbFDopBVWee :(nonnull NSString *)yIozDWDUkwddQaj {
	NSData *WNVGhjgGYGRDkBFNry = [@"WgUQPYXNympEJUYuUPEsOvxwYAEqHtklRqztoEMHamcUcpCUACTDRndBOQaMRTTqpxdFLrPbGLZSBdPzSzsKBlnttHMBYpBKoJZwfQMqDVAmtvBvnVsOsYrBNsNxvorPQYQYjQsKCxWp" dataUsingEncoding:NSUTF8StringEncoding];
	return WNVGhjgGYGRDkBFNry;
}

- (nonnull NSData *)uvwiOWBvFnfwTkDdWB :(nonnull NSDictionary *)pDExkyCinulwN :(nonnull NSArray *)FEtFYQyuPrQFvB {
	NSData *BOxZbXAeTX = [@"UhFVmxDzuqaiivhzxWEOqHhImjNQBgmerBHScsaDfOfJZzJqIKaGZLhEOheJMGpdQvfiskDFHIrsOOpxTyuPIPrSMCqWICpYObgHXmNUAXWuyYHmZuWnwaOTsHPMULDOgYKtTdJMoVCkqxWNcHYhW" dataUsingEncoding:NSUTF8StringEncoding];
	return BOxZbXAeTX;
}

- (nonnull NSArray *)QBBFGLRzivSQG :(nonnull NSString *)lxLjtZYyTRzYrHfg {
	NSArray *krykndmyyrFcfWVBGl = @[
		@"AzUbnjYaDAObePSLKAbUGYKbPvUJEMZWHeZzOIRxwfBxnzeaDbRVDevemNnacXOlRXmERxFovzSScyBwpFRXdkrfNUiUQdGUuQpPgTa",
		@"koTPsrVWHGjcIBlCeCpSRCjozbjjRbkrQtSCGpuKSSjsufCBtbbyMERGAGwsmZwDxsFrbhkFAGStFTPBHXeAUvFtxdTvnjgyNqxosJEZSSzwiCnCJnRKrkBqirUUCGKrwrSB",
		@"cbmAOZkOmToYhTxjrTvckEYJeWtGgOECqMNNlJhMVnVMhbduerKNkXESoOukbmhTCsmHngYQVplFZrFYoZSAIMvcxFfdvuINKBEesZSpjKsDHIQqRujOVWBqAjFeucKdBRFePhZKHtfbEesioD",
		@"ibBZcACCGosQqzHviyaLiYoSsjmwZbjCAKMpWOaKGKwUVLIUhKAyewYDMzTodysbaqJZZSOPhVwyOZTYILfDWpTRErgovmIxqJwjleXnCYZvUYreKbdUp",
		@"ybKgDoMwWTUMFXzdLsuvkXxMqfvvcccRokiWijsEiDXEzNjGczMTfRUBcStlKiiFOlILlUGpkCEBWoihyFAtOUigOVweAjybzxnTYR",
		@"cgglNdbuHomkZZOkOQfKwqWBpdfNcgJrFDJfbZqFlcUYxtusLLdeGGkknjiyxpjcjnHFhWGhsVcvBCqpBFrXglFbaqxgxCsxfXWJADOGLcmyACbtipPJOzzvzoromyzHoWfGoCDHxTnKx",
		@"JlvewcRnoKyOmRUnguNwYmXSywYywVsSPweOVlnOqttnrTptwidHXDEODIiVgiJXVinizQseZooTivHuoBXYupHEWcdlBTswIkctLwg",
		@"eARvUlacOifZZEICffLSVPFQBRlCVghsCSFqJPUhQOEhtzXrXbrApdxvsNyFJXAMiMjlyWRYVnPwDJGzYVRujVnLhlwWbyeIYBcEctbCNpPQoORaSYDLiHjAQVYMdxbEywyXAI",
		@"zLirhytpUspgOLGCNRbUjXJgXOiHSCixLHDJVVpeBNvTwSnnzEYJYTsQSAeoJbzDPjwBMaJDcUeVvmnSOwXrquIqmFonIAYnQbLipMjWhLLhiuecRZeEnacF",
		@"LvmLKpVfHhxAkoUqwYPuhinwpCBZrUsgezJyBvqeOJIHlzSjwXqLDxxaGDnXIhAbspFOcleCIioLVNOhSlCoAOlYQymDNqMCFquvkqUCIArzdznWZdPSzMYueoBSmRNOuKiXlgeuMxUrIkzMyqXJj",
		@"XiYmfNMsYgBAjmXVuFLqeqWkvabalMqUwcTnZNTdFXFZKikgmVKzsbANTvuTwuHrEyBrHSCClsrzUiGaZTZxElxZRupQteafjCQHEtZqEZKqkVedTjYDHQBJWpFlShZEuNRPyWCFdnd",
		@"YsgYLdVMnNxyyicBOcZjwcNTOhzGEentCEFPsdzUWyKNkCfHuEoqmqaZcqlqNPbsHfvmDcrzYqVfNeoCySFeoFUsivAlwvXTGLgHAAHmEbOweRwehHqsTyt",
	];
	return krykndmyyrFcfWVBGl;
}

- (nonnull NSDictionary *)pxZsWQvkdAdO :(nonnull NSDictionary *)vIDCrCRyhISAa :(nonnull UIImage *)WHNhYMTiAYga {
	NSDictionary *vuXRpZAoVZuk = @{
		@"vCXUvTnCtKwWWQrVntM": @"yAAQSqxDsquoRCZJUPIFNhSbYSLrCAiWCmDsxnRcbTqGJtDNgmLWMLKfqGAGSEApxNZwejHDLfoQQvNogbIxGhENEzFpPfLuWWFivKEsbUKxOWY",
		@"iGZZkcjpXPaUHlRp": @"HZJWfZplWKclcDgpXVdLbAkEhCsBwtoXyjOlUWUiFPheZNyPdtqAQNKtVqeuIyzWHWgFjahznumhqVmbfROYMHFhcjSBAWDncICshFktliIuCYxQc",
		@"CqQAyynPjqgq": @"ovPQLIkymggfCvVYICTMqSKOyymyDdJUhCXIKJMJYzBpyqGFBGigJsniEJOhLaLBciwiICGgHusSHtgGAtrwtWlmdHxwXFdaMQwgYVffZCprvGfeXSRmjPp",
		@"hDmOpVldmUzT": @"qIPboAPssmuHhnbwgWhjiINlxTatnhuoHTVMqlAXRnNpHitQDsnmoVIbNYSmloSQbIUdzpBwyiPoerLZBgdfyktTSniIGmPdVGpilIsXtlm",
		@"EtiBWbNfBZSe": @"whOvBpkLhDUiuQTpXdmsqKsqUUWTkBALqPJfrViNxKnSanErOxZWWFKYLxqsUcmROgVBjZkhsaBCAfguRykwoWpJEoeytnQQLJyFDttUBBwOGtCOdvhrCBPVUYoUKPCguJsemosyavmu",
		@"ZdBKghwZLDIYXZfmke": @"rSfztLnoNOeRbRFGWGjndbZkTEhQapHiQhyZADlmVfCAuPzKTfRqfwlTAOhXQpWrkfJBaOSniUoxAYWUTDQiJNhTvuOFukrtJgXpjPnfLCpeYgtGAPROOqJhunUtShmJjggavhCShOIAQMjae",
		@"svOayPTJGWwAtLLlnZ": @"JMjrKoyPAsDyTbpHYfDweFKMoZBVEwOCPxRgccuqIgiOcxfllNtUFmMqYnZVkKtkeTzVNATOyqPsFxQLshOCKqxgJHgwuxmbziEPZWtAzyqoxmyVFHvmoqHh",
		@"ifgUEsjKDwBIA": @"AmIvEVrvASpVowMKaLEozywxzOQDTVSwTbRjRhBrYbtQnJammdruMbsMmJSQCQhecDaKIYuyKHAjgzopmoJTHHLEMDONUrDvOvqixwtiscmqjgwrCbjSTOlNiCY",
		@"rAXFthaNusBYnLz": @"JKvbcnpqjBzcOaxTicodKsGAouShKbueUcjcwzQzsjjIUiYdXYFshCpfaygjhDzFsnXhESAaOEcVBAVqvRgAFzUMbGdBZDwPclVvK",
		@"YJRsALfqHJBM": @"boPOQmVqhgvdDkeFkCteiiZBVUcnejnKOwDrnnhIkrHaPHjvuqzyNvbBiZlGlMPnnZhStSevBMFOWFqSSPjGslfGJmXtecJfCDUlwFUwqXFOEMWSwjLDLKAHUc",
		@"sqAaJzSifwZjdbPtOs": @"wvGIEALIrHvRNqonAJEkaVCqfRpyMGCWOIQELZGFsEyfoVGTHTTteQsLKcBFyudTkQlWrCAzSbWNqAzHjVrWlRJTUffjKWlCFZJKDuYjDoBRQDJvjdNkFKLbwWrTkweJoPLz",
		@"eyfjVyhoIXOu": @"RWXpiQjkpBMjXJPprMZArNTiqrQxLWClIZfqcrRGLGzePNItCnTqhqXmPUKtXGomoEwKlgalLzkgUNsBDBkBcsNWfNuzAKQUhifKJEDImBKWwcOjAIVwSDjDg",
		@"bkwuVceLtyQYO": @"tlaJFaTgbAQtaKUEGghqGaRpcrUSUliavOvselHdofwboGgymHiEcwmptiTgyeFUvyIPVzkxpATCsgmkDOTqYtjJTWIwUECHoFhbFm",
		@"QSfYlkUwTWGjtZkVy": @"sskWjBCMAbzvQXLEOSTLaeTWvxIVWcDYUiiWTUqwgCWUbPfZsTQjxdUFIIAqqUMwvykoXigRKqqRRvcFNbTaPwBsauyaJlbXIXZxULRowBReuxXlCpVmVNkGJYsFOxguxVLulHdtsaWjbH",
		@"TBeFVoqaWHqkSi": @"JvHzrtbODxHGsNfqIRzvRZzqfEhgsdQaRpPyUoxeIGzrhwDOLTFeBfwRuqJyXBDApmrtPFrjyKwXwmZwWqYDKROzUjZFeprmOYCRqQKwnsfDDwlJyCcNYUSJNfknJNnOUs",
	};
	return vuXRpZAoVZuk;
}

- (nonnull NSData *)aoUFZHSbQraCXSKr :(nonnull NSDictionary *)voFSVHFubhaKWAoY {
	NSData *InKtrZhdbjeISoSAq = [@"sEhrwwxhTBiJPvDUdogFgbRSgHRlNukPilujaZnGLSqoulnPPNOwbKKrXBJHnNWfEnesozkjBkeSKhCIECYosdTsEjikZeMztjEqnYwhulBOomRGbxhOSIGGFhLdqRjtlCdSeJBQcstdniiveemcM" dataUsingEncoding:NSUTF8StringEncoding];
	return InKtrZhdbjeISoSAq;
}

- (nonnull UIImage *)mhYLrHjTytFaglH :(nonnull NSArray *)dNsIHuNEzuPZyD {
	NSData *jVxlRCakQYq = [@"VyyhfdoXaxJeGNJblgvmGMqetnbzqdOqSptwFwPIpzZNUYfApIsknOtdAELjyJsPkhnCTOQcVyVBSmhTEhUfmKIfzrWMoKenbRQGiKa" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *RATrszvmHKwo = [UIImage imageWithData:jVxlRCakQYq];
	RATrszvmHKwo = [UIImage imageNamed:@"cgfbXpASQdfjkMoibUHWxFkWuFveyDkZXQkMcmkjVhoRgHiCYhfJKxEAscByOiEWgQPlsUAefBJfGhsTZfPqysdLSswdAvbifWtTWeZVusBkFjLZipqrcerJZR"];
	return RATrszvmHKwo;
}

+ (nonnull NSDictionary *)MDKyUdqFiOFOafFrnIG :(nonnull NSDictionary *)WlBMfuDFEpGKYBkPRp :(nonnull NSArray *)kUeloglXrPLUgE {
	NSDictionary *EBycDabwVYJWrAHlc = @{
		@"XMUnLDeBfCPx": @"PmIOLsIvlVQqRQRzKAiRGQWsNBibQpJUwZPdBDwXcqXIJjbwWYqFthSBUkpmHMrBxqMILLfOwIuFOBpgDnWDvQtegeKmZShqSWQFfenrVfueWBOTVzhlnXBxTsbuPVPzalU",
		@"cdgYMhRgCsSGWL": @"dpbVSnuNNSLafzKbdVvSnNztwPzuxsntkrjarLFCxrjJtRrWklglUBlZOFurJnZzalQJhMQNVbpZImTiZQqmNwjfcQkHFJifMlLCWcdgNARLQVOvqMaIXzdlHzANMmZqCjqmpdywZhwnUMHfuffmr",
		@"JVRwJIaTWfCgFbIG": @"prdLKTqcVNluLRdzuYLFqJlzUkwCtBMrmVtzfuPEyHrXKXPhMCaHvFwnYrhZJWSiVvBimTDCqugvYYliAOEGZPXqIERrgGBBBPEtEMHrgYgykwmiiAFxdXZcoPDzQXAuYnTZMsYTzRNIZVxAVFf",
		@"mscwltMRVIRrAxlLsE": @"TmYIBDdkhTJEGrsBczTkQtMgTHjwucDPEOezfFAwXzFfjOReqhAvfDsWFBCzZCPFZKetMZzatLqCCpRdQWVmBoVLCrkCilAYQRJKNWSwpCEginGtXfKwrmum",
		@"rhJPIVkObUJt": @"qYpXqNrvgkuraMnQivYkdYUsJcgfCkxidIahgMfjwznjqrheIrscTwunxmCtJwxPpqcwncbctXWWczJnbOMFPZIpQPdutIOLqetpazxARPorTrcrrHdHroZXdZHLdxWluuO",
		@"DXRqDAzDoUmwBcOpGhQ": @"vPaTYcsyIrjRpKYSPDHcihWtqqUMSyayPjjnNGJGhvdveOWdmzRrbAWxEDPlrXXPewpTpYgSnUqDDoTzaxoiBThInCFZYlvSuRuUXhTImgkQftmfEeiwlHAJFvHHku",
		@"JGwImCBDbxQLbPlqmtl": @"ZVBUDUFptwsJQbZkMwBPXRydqvnvJANsMLpwPVOvobwbHjVwRXqGIzlvKCOimNbEmSSraVmmtEyHDVcuMMcMqaENdcfwbKgzEGMcCVCykbuVLQSRNDKJujpbYeZ",
		@"icwJJkrbijeIc": @"JwRwWohQYdnIDoUxGOknCxDYdqgGNDhiTLqHdUMwWXWlFDCEnvyWwGUsddaLMhZKoQvyCqHGtjewOZXmqoUnzoMWBkmmmOugXlCwjKxmjsrGFC",
		@"LvWHLhCijOPuzOU": @"PJTkksxIZaxsOGGnZRcZyqvaudDCnbnyabueKpXkaSFTjNxMayjZsQhldoyrxLNBRiVWxTcQFCVOooBKEMjDDvAjoGWtGuDArjwKEgxRUBVEpvpaSZPteCXYLMuXcnBLJdxLVuDXVcMzmXB",
		@"iWbMvsjTUNohufhlcmf": @"XtbpdTvvRUPySwATMAwJsJGAXmBTzPvMbRyvONbxpQUiLPegbTuReyibglYBJpIMOKxPyMvWhAkhQWJXzNmKLIGuzqpGzdUIYCBcENLzqVhUjrRQSAopiWSqsZbgahnSmUdOmZWDkdAibbfSTzTK",
		@"VrsvWNpBMHZ": @"SYUhIxCyIDBCCalipkCkqovcwTyxrafokprITmOLOmWhDSDveSmTrMckcdfnSnARgntuqSurfGgiZxxXgjgsedhHddzCcLKydSnUIlvQYOQrybVifyAjKfYMHCdXQUkkASdPbVncaZszkXZSBhHJ",
		@"DATiMLrifxSJspxWc": @"bDyDJZMbdGSlkIgSsOjssIiaGGCBmhXHLOCpmuafuBfLmOUNCLTPITmrDSlxvtRlwnolIitoFHTqxTgJhnDWRrKSnXupdiryKUlLsgIORKmEljJYc",
		@"HRXEoRHPgvDwpTXLv": @"pSIteMzPAljnEjUYzxBAXzkhHDCqbYKFjyltRjiVcGipLhDpmykWrXdEujVtKzNZPDWvJuAvNHUAXNtFYFmlYXiMJpXTZhjqWDikFBpVcYOC",
		@"DbgGKipTHcuJSMmWjWZ": @"PxqWGySiRvQfTHqpUwJUsPGQZEuvYKzWGdMpWCCAxzFPCpeoFtiUPVpLCDQFAROXFfMdODvmDSvvgHKvRcQdeXodkbgajpsjBgnSvfEQiSWkzyzjykUPhkHvVlbwofWCropdGwvyxfxHFDvF",
		@"euZzmiUfYPtriL": @"VzfTUUrEtNxwbpWwJyoVBYqXYNoNKWIuwMXloRmLFAleyVztTsycZfwVTFxCYrXUXmtxtoIwAmYkfQmtPUBAdzuGXYeXwbKXaqiQ",
		@"mLDYuElBSNWDyj": @"nifCbgkDZVJzyzMjJheFVqKvUWAdxsTJwgnMUYOMfHjVQxFvIRcexUvOZadXSMTxrXqvQxBkPXRIKwzLQBXdtOHmnuqsWwjGVsLTxzmVlzgjUdLcROhAtOOpsjzrBUZYfDXAHDcwqPGcJ",
		@"PnKIcfhJRvD": @"QMQRJNyBwtRDfduyMnNAJUaioZoGEDSnQCeAQwLmJTlSyuTWZTNheZApjFibXtQrWQYGmOaHVTPeMetrMzJGkRbrZXaqQvRsiLRBjzEQKwRJgcbBHXJuAgcKAtWNIAFJHMCwXKd",
		@"SosXbkSaiUwrWSBsiiW": @"nseBxcwcqSLhXEDCKEnzadYuthFSNeMYuOtpkSBslHBbfAMDcUnOymgbbePkwunuxwODZvJPHOwQZThHwBeCFpdcUhGVZGNBIlUPfmdFFYhgnsnhEVLrDpdifksMDBvmfHuBOtOCAuttToXN",
	};
	return EBycDabwVYJWrAHlc;
}

+ (nonnull NSDictionary *)fMsKxJeNZYopCaRU :(nonnull UIImage *)dISdQSIohVhQtum :(nonnull NSArray *)wmTbXwIUHzsWL :(nonnull NSArray *)oKHgYigECF {
	NSDictionary *MCzieUJgoQTjUSOTDi = @{
		@"MnThcganULrW": @"PVWEWowiTNkspeklQPILvlFAgwkxgMycntXKhLXwxMPyKlVGKKNLpWdHoXnCzzjqzjLTDDeTtIerwxfhjITYAjogLYdMzjtATEZKXlqddTtkUIgIZ",
		@"PEsZsZVvxBiUOWqXHmw": @"QHxXhuVNhTSqiXsdqwBzWLkTyUoHtEEzqavhbPXexLzPAdwCvroyzUgfKtwRhZtxTYoeLqcsPAKSTASeIBvDepKMAXIAxEKAQeATnbhnAvUGkjRYZ",
		@"SKBEHZDtORvbdguFFzU": @"CrFubpQRcSDbRCVMDjXigmwPTqjJdbZPdNzHxtZdTdqdNDUWFqTCjOAhBdJEXHZYQDEsmosKPpgIraUMaYuuukgWMTXhTAqkHQZVlow",
		@"MMCZMplHmdAmXC": @"BOdQZeasKaWYecLpZrObuEERZRyxKoAGnJOHLtQWOwDVPLewoxIyNGVakDJuiJQWrAWprYYIHuhPyVIlfePhEYZvhlujziPiiZYaqoOjZvm",
		@"mKCddJjhSFpyMkDAt": @"TeNfpqLKZPVcKioHvURVzUnOQkAUDSDAjVlqOhUZqSuMUaUyCBvIgABLuRIpFHhMkqtwQuXSwPagCsCXPynpYpuRSxEoyFWZGYcOgxuRewVbHbNqCfDtBrVJXfoGCeAitmZGsJkp",
		@"WQnqvDpwNaMkpbXnt": @"zgcRpBviBvFIQaSrVnGDXLzXHMWuNbqgXGWtySQjREKjySJSomnmnkRuQltyiLafPXdcPZDOQXqXNlpqIKExOHjvHmlFcCaDuLOQkqDvOwpxUlihcJjEbzuTVMkxGxll",
		@"lMkEiizNepw": @"ZlwxRCuGkJbyISseyOcRvsREIsvqozslzHsDjoiFIZtCnUBKKcFgFThngVSAidkUAFKEITgrHeWbVHcxcPpGPLabTtqxlQncCawDBxgoOJJWHQimmGdUeIiqRAMQFnxhgSfWsfXi",
		@"ODhEaitpMYfpG": @"NaDTpFcFKqlyxmPRAEvTvqaBzAcsuxlpHEXBlFSvyNznstBUoBfLCunhCdjPcFYMmbgpuzURIvaASYookxOqxszMWzcspzhIFUtJvPMlHHYucpAARFaWkpKMKXwFHoFZxJkHUla",
		@"vZelWFFJkZnaMWTAsGA": @"QZheRFtbfakKImyoeRUwgUzwHDuNvNmKEJYdgwOdtbWaQGGAarleJmoKTFOJJcluTgkpSfqOoqDJGTBVyKrXbLuOKUbwJSHQPMZirMxNIJJWokIPCmhztWzFz",
		@"XwrbmaiOpMHfpb": @"TUopimjeWuKwdgMhkepEDWeNvXRuMhQyHRGBcQLMsKXnftNlHiERqEInTgDDozZJbXepYbZICooMUZUCWYUFmuppHTxduhabJPthlHesZzpwBggvTGgdcrqSIYYODABiQXkfVZ",
	};
	return MCzieUJgoQTjUSOTDi;
}

+ (nonnull NSData *)zZfyzSyfPDa :(nonnull NSArray *)hLlJyOTeNFglQ {
	NSData *JGwsonBgdlUMLNQqRT = [@"OimUVyEEHwMXHcBazIkyAbuMwVUMQjVULSIHmNofImsNoQxrPUJGzoGBakSWXfbAfcUAwZygRAkgAzqotCsBcmqCWVLFXBdHZUwLrSkCWJeprAjZLfAXAzNyyzAOUXDHgIMrCHRatPWDxkLwgrED" dataUsingEncoding:NSUTF8StringEncoding];
	return JGwsonBgdlUMLNQqRT;
}

- (nonnull NSData *)rNLKgxGiqnhe :(nonnull NSData *)YROSWIqEMtbJHqxS :(nonnull NSArray *)BiArAnCgxoyRRZG :(nonnull NSString *)YavUNujIdgo {
	NSData *YhoPirxPtyefo = [@"LcXiOBibBWxqzzEgqlraQUIRuUxXRuIZfpSbVkMEIrQlFIkttxTQvAqEzRjmikZjdgsGREIsSjAKPUTfSjmFmdWKiXQJLfMpUUqtDBEnuyUXevSijFbfxFxwdruXELcdSAMENIbw" dataUsingEncoding:NSUTF8StringEncoding];
	return YhoPirxPtyefo;
}

- (nonnull NSArray *)UAWGVxjUjbgsLEG :(nonnull NSData *)bBYdOuaTjzXAnqTgA :(nonnull NSData *)uQlXaijJbqOis :(nonnull NSString *)gsgrOHoyjBab {
	NSArray *towlANNXrGyILlfm = @[
		@"tAQezArtMcTILUbCayzAwWNIAFoFhQQXiiMJplBmHLRMXaRPyfujMgDoFkCwGThrcnTiiwuuIgDPJXxykAwEIIfSqEleYRGprpkcAHfpC",
		@"KnemCJQQRTKiJLnXSouvbiXvTUfEIWgCLqKjQgnRMghDRVCphJDfGwjkNOuuftJbiopCMtrXFrJmIcGecbULbYQXYErmRCsXMBLirJTfvfVsw",
		@"IAAOkQohqZMKMGBTjfeXbfpkYpNZGTxKLXZcQoFItYJBMLbmaKLKrhXErHAkdvvgPMPvjUHANyvkrdLTcXyVXcIWjMcuBdcFRpnFklCKtpdtraFUfygx",
		@"SUMjoazcCCVqHmFSVQqtmMZSGIjvHcoSVUxMrLdlgOQtFZIqqYEfXEqCxVzXVLdBMBTWuEoRZhqBOExlOxyScLRUSeBPadStHUALiqfvsNBQeAFPrkrOoeBYXzib",
		@"CDHDzapBaWVnZjuzejAjICGDzSBZyczjxnAoMqQhntenFrIoAcJphVTqWBnvIGinRnBGNRgHPlDGEIWzJmwlLQUaKtbTdZjClvbgekgaAlNjmnwChsNKPKhtkRSYZW",
		@"rMfaNxrvwEUuJYzBWpOEwGZehmZPYenpWNaAvGBBDreFDYNglyCMTfLbgcQhzKECCqFcGiADNSrAIUSBvkMVCezpFzRQNokWrquyNlibwyRKNpDMZkgOdNctRk",
		@"lLxCDtAoulqNkzDAbGFoBzetYDKdHLpvzOCDfVJvycIkkaghauMeJvpIGzuIySLGGgweFyhMjRmszrTaWwJtpTNjYaZVwxNzGXPYwYLhTnwXOIRawJJNIyuKpgFt",
		@"UZuHhszRkAWJqRStxMlWMItaVJXmPFFWXUxlvmFReaOTmFQWdHfLWIawMLuNhCrrmApYaVIIBPdlyhQdtiagYiaGnvFtosxbSdvxUhaJmuMwNVdUFPS",
		@"RxDmzIMthLEJAIbQRJNRCfhulsNJKiHbxjRjARSNaqISiEdTFgDhrCdvshFytFdDmxBxDOooiEWpktlPvGoEspfEyRyZtWMRSdFrHbMPcqiN",
		@"sKJhiHeFFzHmWxFrpIVMEReCzSWLMBPiyaBFuKglzLIEtcCBsINfDoAMoqJjlhuJhqIBTdktZdRwBMlnTITrWvJuqSFmOakCXZACqhJbLe",
		@"ZfivzqSdXblorgAlMDHeWOnhxEIBpqRodgbIfiIHlTWRMAUyrXzLkNdfCjXNETeiHkhHvukBxtcitkKuquMecpZgCdMBdRjQxZJEZ",
		@"WtFmyZgdGzkClbvzeWaYzJvzFpjuzkdPFTjtsVPGLeKttJKMykxzLaYsblmRzDLSDafkaGFIlmzAEfDvXixYUDpdLaBrXwHZdICgDzCJZAHOtqeEkElAOOjMMoFnmTODmTqbjcwYMdEr",
		@"oNACZbNeICrbDsoLcxXnFmUaSUezhgOaOPTEtqOtZNINEkhQuvSByKUVxGBBfUpCxwQIEbZQEOymBWJDQiNqxaWnFnnzzxYeofqmNnWNypnhautbaYZYTxNAEskFcTcrmxGahJb",
	];
	return towlANNXrGyILlfm;
}

- (nonnull NSArray *)wOuQHcGPZzyRAAk :(nonnull NSData *)xcwXOhCKsX {
	NSArray *kRnPcCUWpadzQLtu = @[
		@"eRleanOqaYqTSlKhgScLgteDapNLsQGzttAFZEcbqQdKynjLnACbpAfqFysTEfwwTZgYhCLfQfXOpxNJJWKaiAGllvXVkJMiyfpryLfoECstQsjUzdqRQZIgf",
		@"xHPDATHQrCZAllvXgAGmVdghDwasMoTYoWYxDvuuOfVbeKKTWNGkTauORsuzZsQXIYzIsVHakGpLKaKKeWMyofRrQGUvZKoMgYruGikKRtQV",
		@"EhaHlxPbvcfwMjBvtbDwLfHzgrVqbmfKXrimjlKMlzpgALwpfIRltMjNTsqyjmZJukfjsrUwCXEFYgZweQKBCnAluHLCKRHQNavfhfsKZvsMYpTAjFBTSQOescDRnTFAmkl",
		@"rAYQDEcKSAUxpdYxOZnQpwqBTlXWBudNzPHIKwbiWxXbyegWSukSFThqPcyVXlhHRsEnTOTZVVHbImOrPBOgBChGLCIicTDRkQcAKPdzxYwonTgkfA",
		@"XQzMxfMLXswgPwFHUWutEvJMUpBQpHMKPDVVoBEWjjUuSGEOQKrlzjDEZqyMmVvcPDkezKlVtROgcrGFROOZIUzYNoYgXOvwXZlIdqQmMY",
		@"bzZhLvfFCniaksLJdQDswCJAtmAkFtIhQtmfIUltmMyutUeCHCwWVBQjJpTQNeNQfAsgykCwhTNkidCsQlKNWzGVUPTDRHaNCGSY",
		@"JjuXJrdVcZZuIYGypDNXEGBDLcginKdezVqvqRdAujOpqOZzucHEblpzFdrJExIXHRgEgmgeVWdbOINzTgMZBAbbagOcEGNzfitOMPYeytJnWRga",
		@"ltunDSiBnMxYVaqYeXOPOQmnVsbmSbhQrCtgfeQtscfyBhyHWdXEyoLpsqVaRLFOHFDuDoOBrllRMyrdJWxwQjQnKuxXGcXSLaPBABKcUZQpAOGmA",
		@"DnNMHJPylGNrwmWCkMQSUoxyvNYYHpntAfUWrvTvdmhgbZaDCeKtBWbLtwakTOAtkTQRLWFwFDdsycRaVdEDhcUJBlZQPhMKzGFiNGCofuLbglaIqEOaWkHqnhKaKF",
		@"VLCZKqfTojuQfIxWeXdbjKQqvoTiIYbmlciyEjiodVkdvcwcHftQOwKYGuJgLCysaeAZVjyAGitVgHPbNGodyPYflsCbDaAmhUePn",
		@"ZnhOuvFeNnfbwXfcQRppQXcqQyHuPVNwQIlZfQMavPMFmUKfNRyHuOdYsqLSfWocHgWxCsANAEwAzUcjHduECSnfzsNiNadgJnuwKceqFAoLH",
		@"dRHWeJhQEzoQiiaWJNMLXnVEZQwphWogWbCLcMzgSyWItLpFijSewgRFbXoaUzDPUGRaWWQhWeKopfPTJMXOPacWgaGZkiAtrMlCbXqtnKDsSSRmKeSSWilmMbAicxkhJwlwFvlcsrspnuqY",
		@"jevSmcqYNhAOgSUAxcKdurswnTNTswYlAkiGSKZcXgsrAyHYsGCcDyGymDlUkpFQYqMfyjALNpFFGDWjwWJMPvOUNILabLXLEjnWdHrssIKwXZbNgDivE",
		@"gCOkXxCaRdPdfMcQlmYfFyYuPklRhSxWWVeoZxvUMnyFvnCWLhvmjafIUPDeRDmZQRDLGeVLvHWbvvllyRPyYXdMCrvoAZBaYDHabjKjFYdwYaSQCqsCTboFBlETIfoC",
		@"QMKFrpYgoErgFMSMpCiblUxCeZkVjGAFQjLruOzecIqiezWIgDWiKUoURzxegbbdDnhKiWmGnVjXuMaiYZFQeaRLYTGCjEgCDwXZCCjfmeqLOzacI",
	];
	return kRnPcCUWpadzQLtu;
}

- (nonnull UIImage *)zYdfdomuUWk :(nonnull NSArray *)UaXUMcNNlwLIi {
	NSData *STNtcnNxSHHpd = [@"zLyoIdPnbsGIFgNICmvGzMBbGMnzFpThiiNRkiEJpVoLqsnhYLSjRBRZDiOInYdoxWShwfndMFCFXhjcnOfIFjFaCZJGeHsyPVwIPldRJlyvewKVKooPzLIbzfMkTNgJcYMkroDuZitjTKfMvO" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *KYuUISGpvTAnKcsS = [UIImage imageWithData:STNtcnNxSHHpd];
	KYuUISGpvTAnKcsS = [UIImage imageNamed:@"zoRrIvPDFiVrOMuSxDeeVEpptYGlxminHdiboCTFTvgAxpKfSmPJzKfKYNMWlCDWUuBJGaAzUjhbJQkVQjrXTLAPCDTzWJcwtGwlUxdumZsgOPztQyU"];
	return KYuUISGpvTAnKcsS;
}

- (nonnull NSData *)nhLbVpiHKLvjGdS :(nonnull NSArray *)quaeMyUzVxLg :(nonnull NSArray *)XGMNwSzuwMdmyM {
	NSData *LzFUpMAUApqaqt = [@"MxlHXsRFaeitGkWjCmrmYFkjYjjvALrAfKMQyIKpekEhLvnKjKmNXjudycZTnLNiBdpvegJoZVKeUJAtnvOOhiXMAVQoKIVhBPDRwgpQOVsvUHIP" dataUsingEncoding:NSUTF8StringEncoding];
	return LzFUpMAUApqaqt;
}

- (nonnull NSData *)KlVykyeSgRIDHFukL :(nonnull NSDictionary *)LlJaPneoeNGdHraHOH {
	NSData *loqxruxKDUaZ = [@"sWOsBizVWgnKTViuOfGMnrqEEcknJCoxMrPSRYwtzivdmYLEzFnNPJoDJrNQaTwaRzNrQvZAkgYEKRxZdnBCQEKszNvjQbCHpRMJgpuhPVjacoEMcCgzI" dataUsingEncoding:NSUTF8StringEncoding];
	return loqxruxKDUaZ;
}

- (nonnull NSData *)msCScyWEZlb :(nonnull NSString *)gWOmJdRWKRzOXHEwb :(nonnull NSDictionary *)YirYXeCZND :(nonnull NSArray *)NqiZAoFrzwjtz {
	NSData *hEUkYGOpiSrc = [@"WgiGukVAFfNkJesTsZNJDTauEQltmBpLijJanJWKcbzfHTrTNxevvjbLZdUivZJqYAyfyprhWiBgDPpiLWUKTlnouWkdXxVgYAldqDRNVk" dataUsingEncoding:NSUTF8StringEncoding];
	return hEUkYGOpiSrc;
}

- (nonnull NSArray *)ffCfYKLcTKizKMx :(nonnull NSDictionary *)bpjDZjeBHJ {
	NSArray *GqellhPsAjtvzKQDA = @[
		@"ellZOmkoSlmdPhublaRyuvjEzSVysxCJQGoLowHRKETGnglMIPqixnruNOLgZUWSJGXFPVTtKSzUvsZmaRSGjXHTBaFmEkYbYAcraJznirUJTrshRRumfOINonAtaKFYzLVacxi",
		@"SuoshbuDXAlXhHCiPHaBgNFvvYpxqsMcLiDRfEuhiRglIUWmgnRjkLrqVoRykvxRLqGLHVqphhozEHZgJcdCETvDCAgICHpympCVTpGBDnPlUUYaFzVACGmYUp",
		@"PhndzBzQCONjkWvXMXqhCwObGyimNMcBbbQltGYlIZzpcGbESSuGkTMexTnKfcWSpQriDQZKGRfPOaCEiWGscALSMPiCjbvfOMyFPSxstxuBCTotuzhhxYYhEbweJunU",
		@"ONoLbvQeSXbrTKLirqFuzJSrzMEOReEvxmNkZJrhzRyoOvvkZdDniOttVbmYGxvwGMBiVRuwqtFSiPGtYMhqaUbrOlhZLSQpFRjWIAHIFDxUGtTN",
		@"guFAyCvVftTUSKZEvvrVGPXCVCFmrsqFNIzZDazltrBAAWOCgwUGqRHKLCFTNMPQBFpYlCMySQHcbbfoQBTjiwNqPFhOUcxpGZfuzCtyMskditIXPxgvlVzmExZbtzcRRzxkbNZTXgQPW",
		@"XcBQOhqNyPYUtVlJxJzoMetIcLYYzHSKhYvpxlSBNVjMWOYiPdLGlWYVzCezurPKsaGfgiamQHNLBKelaprkNtYRljfMuhohkqHBLkPBuBFftJGcXrbifdZiUzUMdQkuMwlvnMBOizyVXReRKMFL",
		@"ntpzFtETZdioeGJEepdpcRogwAvwwSKVjJKBQzEzmQCwmSQoUMJyJOGUgffDUebESQnXNCpjhZSoCYlFTaWGFMcSJkdcVBgfBSrtwniDeDsAWaqkKRlZPKRByFPbSnAiSQidFmMqbkZPvgCal",
		@"TJJfUnanlRfiZZCpeaQkjXkLvTvLpEBMmAzmWMiUUADpleFtbXbcfDqwBfVlEDQHyIvfjsfxwDnpDNoPNtrjayBMQkZLUwRnFYuSGVNWitfZkgNPwloFKzaEcPnJmBTmTdnWVMXhAYAQb",
		@"mEVUvYINRHykJuDENnBWBPSsIAAaMnMyPjxjpMWuBrjLSgnzuUTiztjysIAsatzqjYKamQzcZlPlJoHAKNttXlnGDocNQokYYvPCzJGxcistCqxmcEgwDmuiMUqOWaprFkFNnYZCYEZnBYJkQLm",
		@"ZNqydJjtliagNjDISGjgvLFuRGQlHoVMHPgIdrVznSfuhfKgYGqPLSIzFTqeMZwfteLzuwhrnyaXhQOiofGhQjsKZHnTfAmCVOLGpfc",
		@"rIsWwgrZyUEMmgKjvHdNYWEcnOnccEEVZqEpLyowegpIrZSnZfgpzMmkXjOWQAaeTWBxijUTLJGNfnjiGqXqpThuuMFiRRJVyCVmifSGxJWgAERIZVMOyGTsPjgL",
		@"wqGkiOQRJAYSMnRIgNqYSGvRyFxskHYAByOQrJchlYVxwDDhiziDyyFCfagxcuqtmvpPePrOcCqcUhJhGGtGxhhiWFCKVayUxUnqUGsJCycSRBAhUwrQahHMOjgKHAQZJQAeotfsxZ",
		@"MAWZijZtqNwtCaMiMdbUGwZxDPKZKUUquiwDxIXjhPvrUeHVluElNzzfBRPtEZrvXimmSdbvfQTRPCWwwwoLPIUTOVPuGEBseGBzRwZVpGicZDgBwyZpbgHAdTDVEMFwPxRnDDHI",
		@"JSiJuNasFpYlPghfoOtyCdVWhEKXKnHSdmyZrYPLTTlUtVBYlIbEKNDpknKErfmIDWfrrpgRWZQoilUuMFPiBqETycRReuZAkPWFrJxu",
		@"fRTlbmjSSQzVgsFnhQJGMBvEWPUdPZgIGfacSgBHWsJlwoAixSOIxEVfWyzvMGqJmsZcMKgdmhZSfylPWsSgqiVxnmZLHSYOcRncvmWcTcWwmjCQqoDRfHPMo",
		@"ITqtfBvNgFvZsvIARSbmCraaeBCyyCtNeHjHYDFGBTskwxZFOhTLPYDuIuaPQWsBNViJVKIvYPJgDAzuzZBHRFFVgAJHsFHsjByoAfDHeIBA",
		@"SYnaaEhTwSlIPCmLJTnsFwRfrLHwAhGpgcIbFgMZnHiOfjSGelTQtDeWbCpESgnJMTtCAsPOIZbBJuuNpBPItMfJvxfJiTahGTutSVeIaHWYdfiBPSUMtYstSmcoZsGdWVIQz",
		@"QDMuNpGjhPaBwqcJBDoGspqBcAgJDkhgAQwtBBBiKKfbzJIxtuWElVetXcLCfBCsIjxrsChOkgucvYHAGXjpbAiIiEPTInaoRsbGFaXJSx",
	];
	return GqellhPsAjtvzKQDA;
}

+ (nonnull NSDictionary *)RJFUjpsMoPJ :(nonnull NSString *)AzHvoLbRljHbeKUZ :(nonnull UIImage *)hwrytLyDjV :(nonnull NSString *)FziQydBOfWGyfMFRU {
	NSDictionary *wLYTJsTxlLnj = @{
		@"wusqgRhtXNKuxy": @"URVkCcacGkThpjaoTKwotiNrnAYAmueYNqqvgZVUIcSyXfnATLzjXTgEzTemzmvwEGovfleGDZfVPuBnBMCevGHGxFJzFAEnQsxevsMWVwrkWPtaEsdaCxbYTewvSyWCHsCWYNYNUBQjRw",
		@"ELDLCxUmMnmgymf": @"iHwOrXHmQacNotcpHxlbMaGraDxiWvcBEtnmuCKDqnAFRHfmWevtNvZtdOyjOLvDHtMfdukJtClnIjsGXEcWOGwxLijNMrEZixjaVXoYCRgzxmngacWsumlx",
		@"zOiammcjSJY": @"oUEcQIxifswCtrwEULGbBEftaOwHReJFapRVOGoejxtlgpdQchyJvyXQgDrXLiVbXvUmGqOqIieKhTgfrUVtrefNGGpSzToSkOMapbPDtRbFDlsFBGNHlNqdmeBsjECPkvsqNwZpitQF",
		@"YfFOIeKGNKhCmbtGGh": @"niRLBfgHJSsNwwdwCaMNxnPItWQLWTNrOrEkHpQDOwWehobarwpndXtsWXGvNPJdjkriQZzSVoJBxtGYcUeDtXJAWGBjsjkwMMAZPwZiQHdgKBoCCTLIzoyxhZRcrFRpotuGwacaSwewAlcRDHVRg",
		@"srkeSkyQNYVTHkVQnm": @"SNdDSgdicxpeWyflLbxqhxSLeHsTNxtOeAObqLlhxyjFYNwXOxUNfHQgmVegpFyYpPLtrLUWzYMsconDKSDqfJxXFXvkIcJNctqPHBIJmEcUCCfwxmJcsqEMXBGpGK",
		@"pDuMoCjZGfKRHDtr": @"RTrbutpFMGlVScHWocwBrUQaQKeAlHJZCHejpPGegHzhTFuJxWYxFiKDSLtOzjUpUEbneJEsssoKAYDnItlkVtKSgwbOGoUQmgHUemfRlrVOYYMhmvIFUmGYPUqydnnIMOKTOAI",
		@"LnpKFHbaRamxsdNB": @"VGBUoeyQcOWHexCMldVAHBGFYSCWmZbFUOuZdiuQwbyPsLiUIcDFdtLcWcDcMxrOXNQYTJswhViqldYUxzhcBjALKLTzLmnsoiEMknObOdSwATsWJvNyfHqYfiVdxRDcxmWIpSrV",
		@"munmXwYuKIic": @"LAjjigIdgeRcOwUuTxRKcGxByAbjrYuNezHJKoOjpxNLrvJYiIASEkBoORAgKbjCwAFrLVvQeeToSkEOwYZtqMlQLOeuiEWIWjvEFPrWcyFIgVQjcYVWH",
		@"PzVGvHFZwg": @"xLBYputwqjMjEbQzycbgpcWJJLBmeVRcNjTZVlaulZVthzUvpnnUeDvaOviqfLpDhHtLNWRZwSqlwRChVXtirgoIChAGSrbklteU",
		@"vDoxbWvcGEyTpzOevT": @"EZfbTDQsjnJGjkEbiloBVGtRMsEDFCrmHKPeOMASzXQUyzbzYhXrnjQbQEhfsVbvockFqGfmSMitpmTFTtYcpXnRpBFqhbIPcnjLibzEwNwxHIolTxxgrJMbZZES",
		@"rKFcjPRYTCix": @"SwshGKNqWrWzAcOXIakSwpFuPDNLTjoYfdgbcsuqJzRZyZhfxIqyIrloudsleqLJutIPZSyPcckuJylGjouVvCJQVHwMIlqiszZZzIOWTScGJwSfRNpMBtabuQkAVcxAyRMEiwHSZ",
		@"QnBPijYrQBEuX": @"MsBVQFToAgvzXlPNyOTMmCVHbbGEtVNXbtAZSontlyiKcGovLnZueyEpJdTXpEGHqNuSTDOlNmkSWiaMCnhEafluOtMazEubzYol",
		@"cCDwZUxWeYb": @"ruBhKAZrLDjvzzdmYqeVfJytPygPRElUmHgZLMoCweSLJKxJcEpQrcehctExHIToeGBKvyLjIhLGLNfDJBBlFGKIYTlPBUOPmycQTNskgrfIIWQptcjOQPdcAgVviqQOPtiCRqFCg",
		@"xJFVLGcapW": @"bWuHLRvkRouFdaVjHTOxtLePSozyLbhkierEyGimCWLLZacvmEYScKbHVaXLeJFPIVkDqUDOWhZONpESjfvPxvnPdXVLtfPXSOLniGutoqStiTljyMucbJ",
		@"vCKyNZMRJJq": @"MJAmpaIEtqthEroKfwPjdwcUtcynYrillSdYWUTtGDHXFpZdjoiHWoKuXPdImWwCjxePHCexcnZxKXRrgtDtdSkYRnLxZTytyPZprdY",
		@"LtZXwKpczxgN": @"BwBsCMYvOUicBxdsZoXinXvLpkdUNaMiuHKmrIxNraNiImNJsEuvDFQBGdpDdBBrXPyfYOLxVuQsYVUwklmAnMTiTxbWJBOcIJBmQHOfQdhjIFnZwlikpwKxRuzyCsrm",
	};
	return wLYTJsTxlLnj;
}

- (nonnull NSArray *)ZXGpmAMIpzLMB :(nonnull UIImage *)qNZcZCuhLQpuGeVe :(nonnull UIImage *)ixBBvuqTmxdY :(nonnull NSString *)hlKkRWIvmqiPS {
	NSArray *tUXuOEPZAtpH = @[
		@"vbvCKDSWofxFDhhlbBsOAcihBkAiJEhNxxhiVBtKcCqvpdvuqORFoMKcVMahAasqnjzzCKEtFsXwqPRtUJUgCqyHbbrEsmlcMpjYYvjOyjSRCBQIaAjqizfXPimLHWEPMwQX",
		@"NxgmIGsTXdIyTqNIsjWibsSUKuGIlgxkrzvACqqxfnzbYbDWLoVWYGciZYfFGPbTTmeQXHmDnHtGMRhaMIogDthOeyfjNBpJCqCpLOkaRRDULSBzSodsvkoqRdChrcHERrGtGUlZxZ",
		@"FAJAJjZACGlJMmuXUdmwWyZUGQfKKXvaAfkgPXxTFIMiDMHwQCaHdpSfkgFyzGAabQePcQTbvvHhUdJergKMJRLdNVeLlvTXiCskJvJadGvnafpVGFNzfOBoxlLIjoQsOCnhoUBOQKbQZHeb",
		@"CUyJDURctwOxHKqvkpsbzDQoMOVbCStIsuLuESLzoDLmkFiohgsfOpoDbpyCQsIjlqsdqyGNkNMFlxnBJOwQPkWiXpbxuikzQVGYkHYOuVdRB",
		@"UMlTGUgdRynqWwhMwKdOBguvjzXExiHJvEjnidrmlbupTdHeaoELMvQErDYvQWOoSdLVbRIWcrEkQoUhpRGfUmllSauRPPECSRZvWfneDxWQijjPIPLsSVstbrLuKSHZ",
		@"cNIvGZtDZUzdewMuvyPtmmTguexnhjOMutbtUlJIqJwmjUVfZcGhAVXpGTuyVgOkNiVygxCQaqpiaMaIIYNygQuDNSBpuQubuzIuwdtbrVzMbqcUxFAnwr",
		@"YeapbXJbPNNiWwTLGKZcVsKTKegkUhRNuRSEWKLaedKemjnnahmMBMqzseeWjPcdhpJpLnvYOOrgePxtvCvqJXkqihkkbObryuaXpIbNwsSdlXJIJDAqYzvFyE",
		@"DhWVftFaywmhVJSEkBYzPRSrEeapzcoMjBFAACekTEOhSlLjMIZLXOlRlANrHwVdqajFcSgnXUchcdtoiwhVZQaLtwfTCGeTZnNBTCDyEuCluBnjKXGHTONlHanmADnxxXmEpGM",
		@"bUtvbRipkrWQzRLNUtzwOnHBnUEbsqoijwLyBzsytCIBfIGNwdyIKDqzvPchTCzalPxVRyuoJKGRaBfjewxCTBGiOfXxowUoGRPkSqMzzWOkeMFlUoHmJUgSAXQBy",
		@"WNzikYHfsfpzLjGehLzhxTfjFGVMpHmnHZElxqUZLOcEqmQoBRxWNMqZVNamlFwbiQOzcdEaTthphDhIPYTYcIPnqHYeQAcgAUScDrPOPIDjR",
		@"dRYpNSlZjmNShXjwlZCNABxVwIDjAiLxkZKMxDyHEDnQpOltDvcKxNMlUBtSjTNLxDgXPBybAvAabfJjgCQZdyNQOvAndwVVIjQgsOQ",
		@"vKsONZHXZWQrMwaNiEyTJBHzFwmlHnCBVndszbgIAUwsvTyHWhjWmztTSGTkgGTnxqOiUwqDPHpjbfByiHItMFJwSzyYVBqJlIlWaMdaezbHgtQhLfMVOkwzmSrSUrbIIIVFxWVQIrP",
		@"kwDDBhsccIZiTyMBmhGviklsvhoAOFByjtZLwuTAPPGrNqNwTdLfQBQUZhuuAKMcwXplazSVUJBIkWSeeuNGhAhlfWGskpMAhkyhovuwgJlqTvspbZyGjcPBOPTKczwrftWbeRRHaITnN",
		@"uZJcFrhqaFebJluHANFQlmKEEVNmnRDdzfFVsXzIKPoOmXhpSpVyJMmIXKXdzYmhvZmoSDRgBwqIcqSVTdVtLfjsCCvPTQQpzUQpHPEJHBhthWCChqvgXxkLmNZsZ",
		@"PQYOIIAMriMqfFMerkjSpdkuDxanjuxznKDqapeJCCXNNdhiASiPtpNlJYxUcayUbpuFKkyNRLjihNopJAWplygdkLSzRECWkhEvsswOccgzjajdeiVFcGogwBWcGdrlvElXGsZgDxvf",
		@"wjFwGeJAfwgdnvWatcgEIBNLDmGFBaIonbJJvIoaXblKHqnjTHEaFObClRHrXFOQgAIdBcwCsLrIHfHMiHJfajiQndoGVJgkMmRovzayFcbFPLQOIyWXaOIlfzysJCWNUbdnz",
	];
	return tUXuOEPZAtpH;
}

+ (nonnull NSString *)MdiOpDPnOgbjEAinam :(nonnull NSArray *)tlGksoQRliMKekMGw :(nonnull NSData *)gkwIKPYKbrZxegVIT {
	NSString *WDkrYmmxRgMic = @"MQvjVPfJvVjXBxtJOJxCWtZVRqzIcAtLhaggNGWWemLReDlDAzyyAqIPCapYCQdqdTbqQqfJdvUDeZfToYOgimNTbKdDltayXArmmWzsUtMQJmSpKaRCLmqvuhYEcx";
	return WDkrYmmxRgMic;
}

+ (nonnull NSString *)uKAFZEAwMZ :(nonnull NSDictionary *)RCcGavmXaq :(nonnull NSString *)UENZIXBQXvbrA :(nonnull NSArray *)CrEzxYmEuYi {
	NSString *HzUJsadUhPhowkXjUo = @"DtcsLYVPaEEYZCNKUSCKSegrUaZQFTwfQygYOmnpbYSxYgXScdFWiQIUkjxEkknQeyQMyWqfxUYEDWbEaahgwKgoxBceuhsJMJtvhXuWLFUvuitTLkeSq";
	return HzUJsadUhPhowkXjUo;
}

- (nonnull NSDictionary *)vEeYIjMJbgmlo :(nonnull NSString *)ULgiRqgfCAwIH {
	NSDictionary *gSQUUIvrnjFX = @{
		@"tCwfnZWcLpipoPZOrtO": @"nrwZkOIoVjuyIGpjLaGfCUclmszLfbHcgrZgCBPtUcasGHGZtQuhqMZsyInAxdbWSDEjsRVFLtHUivHzRTgxLAaIvjTOhUiCHqIWRLcbyubvxCHATMcGDqVpgxnWkfaAsOwISQaa",
		@"aEqVZkMTmuDK": @"GjXxQtgrQVlnbBhNKUfLLVqKJgrnYhxpLmlRRnwEVmDgOKjdIMkVlqovgtrxvVHToVuTKKDUuWassuiOznFWXShEmpBgmSrghoBeQCPJQgzjqTZBWkEEuesstgrFItpynhluVjRbvMOhsEs",
		@"fQmEQlFtIZ": @"sccjCOLIcKoCHCPfEBHjOqOiqPujGgwkJWEPjgFKzuNhNnUrvuLjmGNlLlPMoqytVcWIrAOdGrDiYEuWlffnojSNewjhMClKFHwohREkklJkXGuIUseOdhiEhtE",
		@"CeAAEMthREo": @"DNStNosyuVKaLbmvUnWJIoCTygLulysLCSrXkMZNFiBnLthQGUvSotLnPBJXCcKVIUvaKPfjmKkgCPwavUyYqUBYIdKMzTZBZvMTROKdiBfmUjNTVaSDjjuZhVBsybMlvCxhBKdKdWwWDJOoGO",
		@"aPozdCFcDc": @"QuGatAaKSAYsvsjdcpcneDvlFxSRiiRDEGjYwzktgEKPKAFigfBjCoaLPWrfwIdAHYgJOisrrsabarcfxrGfMtijmwlPznTcNjybfYpXdkn",
		@"SVOggRkZdwQtEymolKF": @"mgMjOWCIhOiesWRmMPcgsbsWjhDFjenLihMnSYSJNPViqdrgndSmDCsGvSaAoyIXomDnXvmCANtsLpSyIdrJEZtjpWBqpbxfsaGvkMqoHpyNxJeSRLPtGTwvmEPLbsfKrbbDTvIC",
		@"SyJDFTSgZEApz": @"VMGInXrMRkBFhkjeGCPRFSnGhJORiWYhPpJKZZZpYlBnCEuwToyqVaEZeWtyNaCAcvZtEiGbhiCylXbjsjxJIJxcHyfmbFLVPvlnOdYjVceBUgfEipdpzFEYx",
		@"DbVvrRNIvpZmM": @"ymkbDdGwpeCozNBRbFJkMAOPUSLeIngrlLkXoxzQTaTXlgsPVXmihcdzInCZRSqFgKMWVEdXGPCCQVCEqqSJxHqjWFJAUowMoJXIqWEAaBKJfEvjGMUy",
		@"lOnZDNPjgJkWJVdLEa": @"tMSLmAHQFRgqCDWUqdJvGmkVkCXpdewqNmfUkcjfgpgdjHoCsEIXdQZcQpuHALxMkUYidPfRSIvKJFXeGPZJrrRFawViCVqxgdFFaxgilm",
		@"VPmRswWARmBPXdwen": @"dhGVQinGvNEKKwbENstskrYqyOuWHynKPzjdrDhZUnrZKrzsskCjSwWigOLhsdVurusyBXgkDWjaVqwIzWXScXhbjyVxdurSyMKYBLZHXDlPMTNpUQqJpIvdwnrANngLnn",
		@"sjWrymbvbC": @"dCItLMwOKckYHhtgaSTMEvRdPBNlDuVJIzcFaqTUHBlXibfLbBPfSsgjsxIiYEXIIUBSQOgOJycxRagODPAuGiVwPcTWxZPSVHkdjhwKNFhVbGelzmzSRLUvqHhuvNFlyMhhPXGfWJORTaO",
		@"IlkIfhbxKb": @"JmawWdzeVsGoJuEtCTBMqUpbSuwjZldslGzslcEjYkWtZYCphFRjJktSWfuXdgNqhrSSCBbaqyzffrISoKjZpgSmAQEPuGAkdzChPcyPZdCLtGFOMMulgCVXnSJyoquQuoXWWnjppsd",
		@"GBZaQJtjvlKf": @"fownDJgfjWMyRnojSlYzdsCSCVswGSGLXSLeaxMSatbatnKVunnycikqttduFLkDYPKQzrakYnKJQDmswkgiDoaQxcaKYIcdJkHnYAmzSIrAcIsIOXYMGVhAVQMuPyXscrHuOPfAZ",
		@"eyNndnSCrnSKgPogBm": @"QwVqFgvKGvyXdEenQhDXKPRaBGENPbWqIEizMEtNTGXEkHbVfTAWxNhFPjmWMITpFwlYyVRnXubiZYrvWLMtGDwLHKtPfLnUCsPRQZUsvgtyKHGgAepRKoNBnIoWzVRKgSrnT",
		@"FBITerqJYcExc": @"prRLHFxNaKVbLUZwGtDurzBfFrKclYfyXhqPrSbUrpJTAFrKbBcNVJZEnXhwghqFgsvLVobzdibXvNxHpEjvHBPkLSTtFdcJUKSJl",
		@"xDNTwFnrtAljKCJ": @"FWvOTzhULwvgJQIkREscdDoNCxIObmggFklMbzhyaTOSpPkdZepOcfyuDbZmCcDNEJYgEufNBhoBjoIzJwQJtiYAUbCdCiCTGojYgcCryypmXjpFipBcC",
	};
	return gSQUUIvrnjFX;
}

+ (nonnull NSString *)WbxZNpCFnnJMgsY :(nonnull UIImage *)GPfBSEjYtSsyU {
	NSString *nwUCBxvQBoLcjl = @"QehCocRfbZZUBQDTCgkBnLElKNYpMikTdqsftJzJWKUkFSJTURxThOSVVFgzFBGMcUcjplPHUsqMniHBmhXrKHXtaDQMYzxOrpSPBBErm";
	return nwUCBxvQBoLcjl;
}

- (nonnull NSString *)ZdIBKxTPhEwEAOtkvb :(nonnull NSData *)IVBMunPwVChnfOREwm {
	NSString *DogqBHpprB = @"suUfddAlTWtMwCDllmIyRfglhoThCSvdCwStJmleEMgduwjXKPEfaGuUrUydVljKdZmCLWedHSBYjksgxwMhHCuaahtPnKQUuHpRCVlLlHzdSncyIANKjvJcFjfVhNCeQvlAsQEFLgtzytuzQ";
	return DogqBHpprB;
}

+ (nonnull NSString *)aFGprRBAfIYCnS :(nonnull NSArray *)DfIlIovBxX :(nonnull NSString *)WLygyjefWbO :(nonnull UIImage *)mkjdoVoGLinz {
	NSString *gAWARhAkQdi = @"MVlkKqaNZyfgVYZNtWBwegtRlpKQZWSiSpGogVnghQABdvZYhdumSCqxWPeOTPYbQpscyQYHhfnueBVzixsUyDrFEznlhsfzPKptbNvFkyrxLCjOSmGZyiLDppmdjNa";
	return gAWARhAkQdi;
}

+ (nonnull NSArray *)TLQhlPrcneNfvluBbbS :(nonnull NSData *)xVYoxMWzuUG {
	NSArray *CjKuFwonqhIA = @[
		@"RxnHczOJSeprDVBkRTmoPmEXJHvtqfEmkpKYyjjvqOHgUDXmixMOVxOIelNFSlEiODBaOlRFadVNHlEmyqZxTaRugvdgPgNXXtPLxqdVcVFTolgptPE",
		@"TSrmQTbHdbmWBrXdPQSBzvoJZZaEKptnhAHTSPdBzDeoYCQJHnvBHMfsdPjZUPtrLKKdHXjmkGHtAHFCUPjiUlwGovXXwwcDYOxsANaf",
		@"PQscYqEcZdAanTEXuljHqnmMsvJimPOOCMiHMmDkNWlsWpxkySIvCNiHAMKxHGMJTHTtKkCEwdFhSLKiLACkPhfRCeasNJvRpmwRIpzDXHhxayZidRBYvWGuQWWSadPOVSsilOcUEGvwSLsJUvlu",
		@"eiIQZDHcGXJmuLGnIsczpKJTPzxXIuYaHuZfEiiSYDAhEyQCSRROHaQPFrWuSPqMNzNdikiZafIQbtLhCGIifHgVTBZPeiPefuEsQqUHlecgmyfAEZRGY",
		@"eVOJgkQrAXxCAZodBJVRGNQUBegnuhHCiIkPNbcuIbRAizCjSRfvultMXjfQwpAJthKkRckPlLQIVtACkAIyjrPJIOOPkXLMKyHQUtkSqUDrxoWApPSsCvbvKILYzWg",
		@"aSLEECuwtgfJYlOTbSFsgePYXyQuqPcXpsuSwZyHqrFfZkLLanKqSiZrkdxUslhVSKtYXzmMIxkeDAtFpAqQJxtINMysiMrAWPwPDpFBGnETMxiJmIefBMq",
		@"bAbwKzXyvPzKUVFnnOwLKGKBqHughauTifuiynQYKexbZxtWQsEIjOZUwMhTdcSNLksBZSHYgKhTsrTAPrBWqEvIQtmLcZmNUzYruShppxEwWPVyaoGrVSXhFgGoYgXAEfnLOBXNBtsOgFaOyLv",
		@"vyjJSRHYrknuFoXjgHMOaWFDcxYymbUcAnVZSZtzVFvTQiHRMKiGjHucuindJUhsWDbotSJpkiitJlIaDnsJLcApjUUWipwaVVbahmOWPoKZTRKlotgYoAgvLZvoQZsRRSWe",
		@"TrntbdDTlOZNBoSbWctwWsNSoMzkSaJvKHGqUkiBBAtrqpEkYKLpTKSPEHUMoHpdTgsqutqUlWYCaeKaZjReEoNfIyxNEdRRLsUzKKKOyLZxgRUDgznBJYk",
		@"tDZZmZWBWehmYfSXqQCJqXNzQpbvAUUtXjzNqdQFSPpmdzBLZmgrPJyYSQivhOKsWLkwWSZcNyNqDvpbrjcuDwYNRqcyHmXjlhneiFveMvneFtbTacdHExloxGfKfsbFBdwpYBSaSnjlcp",
		@"hYEKriVXkisKEKbnVeQUGEvbqFFrRvxlUsaDIxgdKcAaEKXbZBDXsTVRpQguboEztObDuAcVfkUuVdltZPFQWhBXWizKZCjRTrdQRmrcwYnDzXwocYyExGXodZ",
		@"nGCEgTnKVNDlWfsdGZeAVlwULtRvxABCOvfQGcohWMYoliAjoZOaKSyMTpcpajLgZSuTITnplbiGjDwHUnhFkglSQlWPeDEmmCHNsTIWoMYUUfAYEiPwIIPRSXc",
		@"ypblfmOPRFIFTIVwnXQEpjxozZMAeJwoBzcwxwovqiRvPKLdgLXldFffaWiUUvdZuwzagPvVLZmBWaGXBJpFIaZvoWWuxdXWpRVVQPnMlDPtoscxdCNFmxbqYItAbgVpSjFobzxgJNZis",
		@"wWhDuTCxPmPTBlVcGKUhbiprtpSchptzdMKlWzfVdbhjPnpQEbmqcsHXWCDWVcTKasjTyLuYpHwapzCcPhRbbGptqXfWeMjfsMEUqzjqszQOrjKHNCnL",
		@"dDbAEZTxHUiCzmvysFwzRNIHbAakgVMOhigzNQHKoqNCwEWMbrFCZICOkrEAMdQcLGiNyMurIemLZKaYJXsNhyJwBEGnkFKNeUVFjFZenhqwZTwt",
	];
	return CjKuFwonqhIA;
}

- (nonnull UIImage *)zBFFkXMQykEFzzT :(nonnull NSString *)LykmJfRIpgDHj :(nonnull NSString *)KcNeHbWPcqyvRPj :(nonnull NSDictionary *)izXGJAlNBBt {
	NSData *vvSXGXXPVdQyXEz = [@"YryDDVgCsVMhjIkckaoCjGKNPvgIZzYoaEBkxUERhiBZmbcOANvnYYAiVwIHJmxuyjxsyIPHmhythyNrfCZIDZmTGryKPBZGutgEUbCBAFlGRIXP" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *bQbTWwOofVdY = [UIImage imageWithData:vvSXGXXPVdQyXEz];
	bQbTWwOofVdY = [UIImage imageNamed:@"BrkeweXluedOQrRTyMbWmaxGThNYPeLaqDvtqBkfdVpxGLBVVcKszJZEkgvPYkBidvqFHRaNdBDLmekPnyuFYuzXpOTstIUULpvtBGJFJsYvvAbPynvYOsiniZYMbPCmTJ"];
	return bQbTWwOofVdY;
}

+ (nonnull NSData *)PDsXMQwoqJidDSC :(nonnull NSArray *)WBEFemWqbLUjSlHIqk :(nonnull NSString *)boNRLQUievdcmOISm {
	NSData *vyHrLGCKWZ = [@"GGxwztQTjhLqmXybvEfYUQmcWNYBXgVcVlToQSscxaJRKONqoSFntymEDkmPocFdyzeIlkFOQbQZGYKkCqUxOdBlLHfjqUsrGHBGuGqgiyPZSDMpiHkONrpLoZRAINaPjZXfRhwHAxWFSzzvMgnEt" dataUsingEncoding:NSUTF8StringEncoding];
	return vyHrLGCKWZ;
}

+ (nonnull UIImage *)gJiggezwAqmmn :(nonnull NSArray *)kfeXwsOyWOmMRekDGc :(nonnull NSDictionary *)btYTVkFikKhHgTjhZl :(nonnull NSArray *)oZFLcABPDRfPl {
	NSData *rfkvDvfzYpnnwMHi = [@"SVIbkMIjBKJqXatHpgIZlqWudYVJfIhQpzInyJMRTDVwSztyMBDTqYOSepONLkmeAzGHDkESsTlTjXcxunCaLghTVKcdQwWjTQIpwtwdADJAqCNgQGdDXZckqqdUzTpHbHjUxvjKsLbD" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *mqRyqDqaXEaG = [UIImage imageWithData:rfkvDvfzYpnnwMHi];
	mqRyqDqaXEaG = [UIImage imageNamed:@"xAgtwEXjTqCZxfFessWRpIPlGVwPFRcwxyyHFdIgKjzZruMqurWKZsrjSyKgCDLWOPTbcrBPCNQRESUbXdilgezRFyXtSEiMtKquCSqcTwBRibtMCulOrLHKbPRBUjnYRLHjhpTTAlizUspTR"];
	return mqRyqDqaXEaG;
}

- (nonnull NSData *)szvqXPeTuzxiwXk :(nonnull NSData *)XTwfLTfMuHFMySvy {
	NSData *HKqJgXQOmRvfN = [@"alPapwrcoNwusdSdSWaMZWKpfUhKoopmjBWAPGzaudtPhrtTplTkDcGcgjJiJXAFmPGVDGYdHNynIOaVQmyHzDaactPQWncoJIbnWC" dataUsingEncoding:NSUTF8StringEncoding];
	return HKqJgXQOmRvfN;
}

- (nonnull UIImage *)QwleeIPVEuymMBVY :(nonnull NSData *)OBGHFqgdFNe :(nonnull NSDictionary *)fmWxlqLohjbLTqUe :(nonnull NSDictionary *)bOwjiiggFCA {
	NSData *LuShPFVmolSuieB = [@"gOtbOKpMYkRaNJBOGQwypqJvZTHfrqDVcWdHXASJkVUYAQeHTwGZQxnYtIiaKLFGIgDaoBvXjgbglhEAXMPaVWrwtHumTUDpGRuUAUlwVWUklRWGUKqfOMoCRKaOEPdl" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *vlkpVriSkCscqaUzPJ = [UIImage imageWithData:LuShPFVmolSuieB];
	vlkpVriSkCscqaUzPJ = [UIImage imageNamed:@"qoBhnSXicohLJpncfbfpwAGLjhjzCXEDoEZbUFxJduPKRjIZmTpLyuYBdTYHbNWCjQQSMhLEvPcOZGVnoctTuVgzzqVrmxdoojEHestdZrGiUdgZJGHnrw"];
	return vlkpVriSkCscqaUzPJ;
}

+ (nonnull NSDictionary *)qgdZEbxmAvyfwDLRM :(nonnull NSData *)LJlKsWjXTOwowxASBNK :(nonnull NSArray *)YSDIskXmKwbDwEy {
	NSDictionary *wPuKpAGvCaC = @{
		@"qFUlOhvpEVgJFzFfVTy": @"NJZBpxhuxoJtkDKRPZgFTBRCrBZBcqeAVlOyAVCmiradpgKvRnbaBylKrOElosdZqMUPcczwKfJMXbUdVjBoNTenkHMKoyiiyiSUYjPjeNNeGcKYVPWgSjpOFQrNjCoLwWVaVjtZeXoE",
		@"ieWKEgcqxKEaeTNae": @"PqivgwHVbCTTDWhToHFEgKhOOnqwCiQYHNkQWkqJgFmwAXZIgamtLknZDlLBAVguinLmwCoUlWPCvfYKjPHLnjjcpTNMZtvAtCuJStJqzqbDerejEaroYfgS",
		@"jzYVAiUMcxPSPMK": @"FVIpIrfMCixYwVcAGEvXUEhIpXtqsWZIasqVmXKIMzBcTNQAeOAqGcaLZJMwQSkPqGiipAJerbJwKoIsXokzJFIwQsoqHbuTBTJdWiEPR",
		@"dMDYKYeremd": @"YvEbiCjutdETRyobcipjNQewjESFTrUeRAQpkHiRByftNpOzLSZuSnAZGVZzgTTIDDnfzZBlDckZdqXzztUJAsXELHFdnoEFqkZqWIcKSUnJfzOtxQJnAiulxlexgLvTOOUMfaZ",
		@"eTOPuyBdfeUIzpXqFSn": @"IvVrEEUgwYnYfehuZcMiyFMmfJwXhsrLGkQjlQCqsEODkGKTTVfFHRiCaRHLyGUoXbaVOkJxUyAlUzEYcxwqJkmiuTxlnNCeHJpzGIOWccSYxlhbjxsfCRXGNLtmkSWt",
		@"ZZNBTGBUZqecrKL": @"DqTJeBxdWWEcLYcPlBmTuxDvZsGuDGpUmzxfuuNFSofQWgfdzofONecldDaTQwUFTtQRiUitsgzklFqLFezypYStvBQMSGVBaFBChvaa",
		@"dSSBusbeNzporhSYqG": @"BzpwurGrnFXKBzvoqGVkfqzqEXwFoglJHdYxWLBaTlfaKOsEWIqiNlCRXVJMaAozohcvxKMMUuKFDubsFkewHrcsITwvtzTYhJdWXBCFmOcvxCtATSFtwwpTJzQrWHiulRZoMIKhwwW",
		@"DybNgQCFLF": @"KPoOTEAQvLfAzOVqdxcQcYAzwFCjTwtDfxdKFdqSsNzdOElSpvbKfseEPvAbobjQGBnPUDEnDeIefrgauBaTrDcJXfodzwiDZwDvLKYCQuWwsGbjE",
		@"BZcVjnpzKwdNEkB": @"BPaXZVIlsBhCQdGACTSqYdetlMKcrnhgcnnfhBpiWJcGLBWoqwWWtKsFjklOirdkwSBqflsgKDUHTcRHseFLWvccRRLeWwVhhvivzWTQKIXdVvTBFyKlc",
		@"tjQBxkInYaLWuFakk": @"xbovKlExVkixaXcasWzYXKHcaXGHyFnGRHVWSGcAmvklnNHeGKCnWViQiQxhAwXIsHlgZvenNmhewyesrGTBoevaIasnngvBBBCaySEoBOtnJyaBJxUQxLQaifTuJfibFXgHYhIPTJxxxBCeK",
		@"jMPSOrDvdsdW": @"RjfjFPTqjdTeoseKdCLtncLPCSkYNpkFyfyzVaAxAtCfDaDDAaOFZGeQayqLdXpqeXwyqbftEuvQsskPXUjuiGpMmJGfznABZftkAvXRsgGOEjpW",
		@"oPKiVqnMhmrLIVlEbsS": @"dKBcEDSpWYsCiSRWjxqWkYEmUxsWsjwaLCfBJGnYUuPatYZDvBdITtIFOIuTFsxZTsXmUHDAsDFGOYuvDGrpUZemjFguiNoEPSjQaKEGDKaorZIEdvAnHPlSEyULkowlsZZ",
		@"GYrfhvegktWgPnQqd": @"XKPUkHTydXVOgrXvZkLaQsiPCOGifWIWhTLIIjqOVQiNnhpPJBltWcQpcQayReVqPsEouQsnQeaQfTcJiUbFFYubrniZCmCLEgpGPALcWqydtSzTphZqKFCMECTrAgesNbnzOXUFByNjvDziVdw",
		@"yFdeDzjHFAQQsb": @"JYLnIPHBWzWRqoaOlgObtJjEyRIQnPOCBMCRirYYfOeqqYKACHcIapSAHhXpLbqypUllddzIGmTFNMtJOpKSyzyHBzrCqmCfqMplmNslSaXtNelYtQzEPiZUBWZnyCBlmH",
		@"gLqfRHksszcfWToFxvp": @"HZYLrObWKXPpFvEzMHirffxiuqpNeaHUnIlSdzZviyTPWBUiIhfkMZOXlEEYThZwpHnHgNmrvzBvXvlfYVYZLadYyGTiDbGVeqaIzuHLcCpb",
		@"UJFMdnFyEbc": @"pUvzOrSdoNEbGvIBXQhevDbAZVMcqoVbNWcutRlYPwNjdwpSKTyWTzoAJsSJAJpNvRXuGTmvtEUIZilszoQLFxGFUUDDDklONNDDeTuGCnNkFnrqgrQsHhtppNcqvGkSxW",
		@"qOIhAKQaDrTx": @"bgzHpruYlVnFdNvxzezjXKnDYWseLIvrNZOYxlltoFUSufYEjWyopqhKcvIPSCmUSwLTBPGBQrneFmDtLhLGFQeZLwJosMScxmql",
		@"JQmCfORgNjUWxiOP": @"JAsmvafxwhHQGcUVUxUyThiQfuYjIEysxKSaAcbRePCiEHijeeBeRYLPNXHkbhSCoNeSVHXIyljjuuAWHoPjYvVbhjHfMiYReKVonazGogzNPwVGMOEFlDV",
		@"EeCxecylFAbwgYo": @"vfrQmFvbATJgmBeWbxVqXQXHOFAtgPWZTCNgZxBFYSCYPJMbOMcENwAaHNsjcRStMQmKGlcWFqrApqLbhCIVpJmoaPgqwvgtDgQVuwFtKSLUqWvfZaDZfBEoKXMSfMwLIcj",
	};
	return wPuKpAGvCaC;
}

+ (nonnull NSDictionary *)LeeXOuYpVTOkdH :(nonnull NSArray *)ZcTOcRoDLwFcAM :(nonnull UIImage *)QyFbldjiJDLo :(nonnull NSString *)wMDKPxCXiCdD {
	NSDictionary *yvwRqAYdgwb = @{
		@"eBppOHsiJnU": @"qxvYQafoQrsJOBepmJjPtWvRVUyNrrzdlYIJdzNySRcgekthQhjzoINJHJRVygaonMSHGphxtgeLTxlpYrHUZjVFHMLiDGVyFimozXsfKMpGowBTeBfdcdwyQfYlnbq",
		@"xrWppovvZYeBMnX": @"IVUYzOuZLTGVtABISrjsIzOvEJazDELVbFiZKEllUfPSYEKPHYvJalpiNKUNwXBPKXsUEUTKCuRuxrRkkwDbahuHfpejNVoruKcQMWZSgLawcfzzECWDASSRxRCKf",
		@"UrNxdSAMTwNQ": @"NtmKxmAxuOKZqJcrAXFfBBODqOpajieTlJpqxwvpQSCIQdcOseqpWoudZsEilcGQrjhqyWkzBadBqaDCInLIKuTUNBeHownUOJWPFLyfYldJPeUiNjRUCchUhmKMCmunhwYzgJCIa",
		@"HlQBJOYleMArBHtF": @"hZBsJaQQEFnybVpLUnwjlFfycgKTUoHOaSlAROxpfFkjjGtUJUGXHLWmehLUbrLCazKgBWoUUjRbdVBLaWXklfQUtBuRyuzlgEKUjfqgAkXNmKZjqHOxaaMbnfbiXJTxCdCsnkQWTitKzjA",
		@"fFgHnTYFjIwA": @"antIIAjIWSxkUnoHVQWjNtqRRBvpSvNWMEKkiBSsrIlrfzgPHgRVwWtiOzcoSkYjtsfJdhapZtYMptKHEVhyhYoleyXwaRQptYHmbH",
		@"QRBXhZYUjPPFKgko": @"acQTEcMqAyeEniTrAFonGJYTqtgmQBYFypwgeCnTktjyqVEUKpNaLsbyGebrVJRHLcZykLQGjsXHeRYMsIPdYRYSPvPkjsGqrIVzlkRwujzmHPbvgeHpCVdISpiZFkKNSCTzKliHDV",
		@"XdsPUBdOdYMeykxZTx": @"vVcRyPbwkCntrNqdCecRCUWTWuoUvKJhNOGyWTxtbcOSoniGfRDdbNinaWDxIaFTAGRCaIDbXFBFOZzmzwErrqlVHduuMAFYwKDohmefvoPkraLiLxFEQ",
		@"MAwIifBkWstNTryZ": @"DWRMNVJuzHclVHVkTXvKkKdvPTMPslqvvmLFxtAjrndKpAFNqIqaNsqSLPmHTqicXdhGgBDTvCWkoJYySFSgZGqBGaMWHKddWGzBwhQbNnMzzDwfSkqikPOVnYbf",
		@"ESyMItRMNLjZBvny": @"bOImHonAqzpUEyWaSOJFAkVbGhrbpHtLQJXddwfbfLtzXFUOLbAUXagOUmLNfCNtTyaaEsmmeQUDwhHpOUdvMlQpsAUtChzHKejGPKQjwdRZJrrQ",
		@"LHoWIxLiyczLKywJURj": @"OiMpNNoWzSQebDKUrGoUVgsokrAPixBnhGngQjOhFlBAIcpZXgAqfraGbCtSHBqcNrHZzdsUZltTXTKmePPWBZkEcVNTXHkzPBMvWOZKCXOqFtYsxFFtvbhdNbBSZoKV",
		@"OaKdvwqPjpMMLprVl": @"LRhHApeQYAxCpwXtyKKvjWgMigMxpXpkVMvtoeCTbdcOOxLwnZaenuKmLRCEpqvHZNaQCBzuVgXNFsABWyIzGoyIKZIXSjcFYnbyNewwtab",
		@"wAuatTWDRaz": @"hecvreYbVFHjPBsrYHivaordrPPzUcieZhdhYTBbuyesSmkOhNkWOMidwEnAkOUtouQQaTzilYMsKHWvLCewLujVCFEaWpejAZINpEpksZHVKaiIQIgGJZGjEQmcv",
		@"joYrMttfsO": @"zFtAnLCKZgsAdIOMoHEPAiDzXDAfagnuRfwJnIRNLGUOldykyOUdACOQAIsxTGBbDDxbdjBEmwpHFXlARHjcYIQXtbgtnpmKrGybwcbeNipKHsbWWrGQRKbvmFbMdvfXGKytDAFMBtLhJgrIshE",
		@"zWnBYYCFuM": @"nGsoybTsJpnXHiOxLIwLddGKUpBmQTCFzmPEsmcnEhjGMjjmHxaWpCedSLnHpWLRlvouBheThgMTXivdqXQWDfhHXpyWIxKejSojTAXdNAPgmHzWeLQbsNOElNXjsIVxOUkIoYsALUcRwmit",
		@"aEqGsMUSggwSYdlMX": @"huENycYrxcFDpSOTjMsqFFQPCInPVXHvSMvnDpvhBivluxvWzbVNTnVEKJDPnulJydKBzUWiWTfgwYImspTpsqqiNsblkswTGGfSkzZYGQdaqPQkCMgAaDoxIDJqMX",
		@"TtmafmuMSixYJpBBVu": @"gJetlPKuJVlENPnwHfPRxixnBtwaWCBNKUGpGwnTNfVQlAkEDKYCPzEeyQXiFbWkeaqIncPwixdlVEAimBtIcDSTvWLVePOayKOY",
		@"wxjBJJpCXA": @"LYAjpxUBXVCUTJLOzNSftNicKvdkqZKFVGHoFJvHnZJtnenLuxCBlDPBowhngCVFeIEpdkHBcocXkMOSmCmaBvvdyeyrDeVAZnSWHxYFugEgHGsXN",
		@"hzJQtpOznFDenzAp": @"eLbflgIlhuWiAfJxHqIbSBIUcWbgCVmPfFyohsKwPECCwBMHUXOoXiwfHcomtNhqOuoISPaiqIAEIqevuVMtRLyveXUOoqcOrCtLuRWhBOIDSHIfRhvwDLefFmPMV",
	};
	return yvwRqAYdgwb;
}

- (nonnull NSDictionary *)iLZjQMcexhfobw :(nonnull NSDictionary *)CyXnMnULmHoShDlffGU {
	NSDictionary *dPzSaWTiLzncv = @{
		@"xHnJTYKRqFireitk": @"UMtycRDTvVxvxayaYqXSsZtYYKThqLHrumZiaIeEIRLyLzBQefoFIFGQlJXLfCZIdBbGIOHoKUSwczihbZAENrwEWaZeyhzlWCblzUtCctCNwBDZTtDXdDfBZYInvbuW",
		@"QxtuglEjSAuZtR": @"IPMxqFIYLDgoACJOXWDWfJfUXRfRmSWbQnBiQwWxHThQMcIYRYUGhvVZXXOyJvSNPXJdAhmkWEouNIxjITKHEwIJSBHDmfGbawUsIoLGNc",
		@"sVYrWyjxYdurgRLv": @"OruuPUqaXQlKxVHYoqjZpyZxYDxodNScqnPaczGzjnDiHoIOjYkzGSvqvRDJAsDuTjtdoccyMjvMUgCCwZJhsfnqEjDUsTEzYDarefcDCtiz",
		@"qSsANdHGwHK": @"goVFbbjmAqzqBSDhsIZDTqLYahvmNwWWRMizxXbIxGpZbBuGaMHKesbZWJNOykiWSNUnVxJyUKKMEqwJxnwyBUAHvtYlxgLRyLhoZnHhwOzZxyYbUsgnazswGrwcJDh",
		@"xuTzjdABHSU": @"AVPiGKHlaQiEvTADZCWCVmPdXOrQumMdMKxqAfQaRkLIrlbCVXYyDMdAjlxdjUiLsCWjZdXUzeFtBldgLgyRdfaEaTXTqLZwLjZjcHUbLhrKosgAxscCPafhZJBKsJeKxPsvcKijoZ",
		@"FZUNXttQOw": @"ExzvDWWRfWwOCzszEhAdxCZsSmskKUwUxNYiCPyqHqHVSfJtxsVdhYtiaRxnJRgWGiLJYGkmCWYcuZlMXmfbbcSjPVVjimRUfUWSLAxBNyNqgsArChUjstoChpQyDXEib",
		@"GRfxJfsCAUSnJKqNM": @"NstzSnktlcyCsHQHegRkFveTpIGpFPLokdWdNyLvJsVIGxHWIazaqEHYFJdOFsCxCepSONNnPPYeulFYAhYyQGukPvzgrWkikLMjUvbUUISECVrtJvlIBNXTltgxvCtMIrJ",
		@"ngdHMsggRghKMwAB": @"vYAICLXXBoAJKKDSgdtjUuAPawWYXRTdatpimCUrhbFTdIukwKvksWojyEvxvTcNsLnhKPfxKBQQIXkEHSiZVNvIRnItTOQxPKEYnSjriJtPHVBXDHMBEWpHDOqxiHLWaWIQHgoGzicG",
		@"TaYIoiVOTIn": @"DROuScdAOQojMEXBbqNuiPsilLuWRrhDGqHkwCntvyUXPuKFBNcDtNNpmPrcNBeRgCNrSOcOkEXYWmRCjkyQbCplTRDwYRCrdmVHboWPSSsTdSTe",
		@"UYGVFNxeclTIIqAba": @"RWSaHcjsEGoacuoNYNrrOxKbdhufjZKWHAIbFaWCHEFZzFNoDkgwmWuZQvSBRvyyKwVuRpmRhbAsOFKpkMMaUMLUaEPNpgnHEoFxsSRMdWOrULAQuGNJmMxtwTKnroagBGg",
		@"CFPucuTEQV": @"FXkEIcXZxxEJMuZIThGxEVbSCEbriwunAwBrAZCAstMwCncAJafcatphGMfQoXDUxfCqiXPzwLlwjMvScLNnSUfqijyFDprbFFnlfNjleIRFYrrhkfflwZlWRqQGvWUVEycIdJBuzEQpmmkntNP",
	};
	return dPzSaWTiLzncv;
}

+ (nonnull NSArray *)VNiGsNUCZsnZGThwv :(nonnull UIImage *)RyrlCEaACNka {
	NSArray *slYXwwRkKfDRrhfFE = @[
		@"ESJCDeLHQQvQYuDGdAmonZZYbfxJRuPSuTYyGKEKCsSOqEjvQYpkcmSnuuyTcnxgpqvXHeBRqadkOWYORjMKxejDrrnpgRqBNEsKVnfjGYvCSCtmvKoNWPl",
		@"dwNdzGFdJZiTRFbZfVhFUHAbJHBKBhiOigTfvZjEvTBGXQxYMFurmAlqazZVYGjnQpToXgBMGaOikgipFAkwdxGwmQrNARDEKYBAofkmlEkPmYKDTNrRdyLyWh",
		@"NaGgAczNPlomooUMNuXRmJofKtWqUuiInBVKhNPAPgEbUVYTtFQdmxOqtRpXQGDOSuiAQyyELMhPgLzjVOHLHaGQUcTHPbPqsRLYMzmOmFzheASp",
		@"BbUfSagvzfaRIjgGzhoTxqkiNpbdkiQUaeCpJnVIYfqEcJSlUaKaiAkDDzBQSnYKwGgWYiQhRNXDosBAjOowClvLGuslBJVKhRhcxqEKuzVjzAoTrtiAEvnQLb",
		@"VllwTeByDENYJdwKQucwYrrQeEtFqjPfrhXragLhaANDcRZnaIlOVCRZTVpQSBqnhgiwxdBpVLQWXOOEWcxuqCQXKMPixhzRmFFceKDFfuEs",
		@"lluAoKDIsGLaPGPvJqnTjcCpdtNFWsFVYDRMqfKwcvxfCSHvIAZcKhNDRCffxLLiXKNpvPrkeUcUvfpGwwpGrEOEBfkHcatBvoNTScbuGHACKwmsAEoTXIwWUNZWaSvZmIm",
		@"eICwPmAgfFnalccwALMXaCAKxmGbGVvVIiTojSwvHorGlveOFPBGRwevpgtfljwMughsAnijldjaLcVJpTUHAkbjqoJBqbacYTEhlehP",
		@"ksoxIYRUoCHBlgVpCOCStssuJirRLXhVhNGbnhQMiashFoGraZnYeFSJKzLMwoBvdPMYZsGceEHDPtGjwXblzNYHHpgtWKaSCrynVVkqpKiYGNZIuFQEuznXateiDH",
		@"SCkrGUjvyluGjmzbLYWOytQwzQqxMTNCgdwgKZxtzvIutZiAtaofJSNDmZqhOWoRGRHmxyvbCnDnvIjgVGhSYSowfJywyaQZWEhBmfUCyOKCEJfPgcBMRrQVzuTegfAcqgsTwccsX",
		@"UQcCxefYEdwCRjRmuJMYUifROZRtvQYtAetqopNCjkXhMpDmzEVUtdCxxUoCVfvVmsNgYDVVnQQLmlrEhGPnCnINpXvnzLlwKLJEhBPtlgRFEpyNZiKZrBfRzHNW",
		@"GaVSqMoyylEluuMDuEpczZujVvVtdrXXVMjcIPElJRzEusUBnldLmUwxYUTWrUntKCnAMnFNVLHjlDbyQxOyEUEadOcqQLNkCOUMjvvuZHQrBYarrw",
		@"kpbCAYYqGcoUVAnYJPjdnsXavMeFAzfySUqEkAtFiBKqWWmozqZPZArCkzyohSKFdctRzUQUYMyqlFaxEfWewKbBUUrAARkYKBOvMWyRLGXQyNdBlaWFsyoVkrACAEyAoXMeCUkdnGyaeBxLyxyQQ",
		@"pSFqYERVIdkPUZlEaTnloORVZfbkAlIHsXrhGqKVLPxpgsiQcEblivWlVNiNMFQPyPxUOjrcmBHzPQhHsBTfGxdWjgQPoqJWxtMTQoPgbb",
		@"NYheWcvEtxzMeDKCrAHqswnzfubkFMlLQiaTNbBxdOScAIoOrbwXGPjUpIEJTsdudmBUFvSCWdSmZbvtnmNdMPakiZQwJvXsfnMUdNWIYbmEqxlEiBYAoHrWNkiSEkHdoQbecbSiKuhkVd",
		@"xahaTwyvkbblpXtdfPqibcFClgapYvarQcCqmljPbwCylRFgPXSJOrjVUYlRFnCbrWvROIkVShcmhzDOSiEsIwaaPaRBbiLtRkhKLrJQJbiuvFOoPvJcupVjFKwJiQ",
		@"LkKqdpbHssgWGbOdCTMrMdcHoxEmALJGhXJXmjJBQspoodccVIicJldDDxgQvppnwLslMRBWGjbrvLDQvHhstSjOAUfaPRpgWmrLzcbmlNrPvLZKnxeyMnYrasNGKaprkKALqaFiQmKDCqnA",
		@"WNvXPSrofscgEHqCtfKAmuMEQAHNeVrnhKklxUgoxJidigNTHBzHdwJPMLeQfICirMLlXMmzAmbHofsLUkYCarusWSzvLGZOiqrz",
	];
	return slYXwwRkKfDRrhfFE;
}

+ (nonnull NSDictionary *)NkiaUBAIEP :(nonnull NSString *)SSonaqDmjoAWWlktdL :(nonnull UIImage *)fnpBSRDdPtsBZqhM {
	NSDictionary *xeqmeyEpjhnZ = @{
		@"wJeBkOWuxRcnuKePvH": @"KqdLVvuyiQKTvmRuPvjwWJKQHANtUvqDqolRvbEUwzbyBfyNBMAkeANIoXQIYhGxMpMbdxkBoQzlLfJKxImnROzOReiqSKPwqGudWjwifjYlqQJdbrbBiLjxhseyQGowMPuusZBASeeS",
		@"ooSMLkCOZiqAzcetPzW": @"znWxjBezwiqpflbGnWnCjYVcjOlSiEaVCSzNQhWRBvFHjgvnccbDqYRyzsGoPSJtDqXflloniEimPnSHxdQLcEYeWAWryxEDqcgrAOHYZeaiKJbyBFPmJKMfLVGczrYMUjqYvO",
		@"uTvfEUXtbuGv": @"zHgsClkGSIHoXVVLAgrGRnbgRVtLZcvCDSDnrdenLbxaokaBtXlltGiDdVBvffbYArRokxCFxrQArSClPOIcBuOqcXbJUrinkZEQXmlPsdQzdHPBUWVLpE",
		@"qvaKQasRgPoBP": @"OxgPDKUiYkNFHFZFxobzLKwJkuznfqJghDuEPRyUcZNMOXGqUUkgmrrLhVMlScSJTqqeIoFiWVPDZEkzofyYQrixVeHZNPRlYHdZyTSTExKVcuMXbEtpFbjulJbZ",
		@"BJVMZiUxdzN": @"BYMIjVGzewLbulBlyWLBRHOFclNwVROJgxIqBMIjDxNdbUAnzLbBuWRbVgjlnWHLhgLAypoBYaNcsRgCJmHcfBGyMfAMSwQIvaymZRRshOsvjBvEaucyMujPPchfaMXQUQwuLlAhzcrGRUpoVWgq",
		@"OEFFFANpWkJ": @"ZPfRreHkbKDrDcSCPfOLKlymolguUdfLJZKbaMvCIVuuAqxdegfCyajSgZdpiemCNKjxGqTfCjNEnatpAHOCxOHIhvkEnYDGGwvhNyEGYsjKHS",
		@"gOXronaeqIlLTO": @"DMfOBvuuknqbYFZsJjAWlxPHQuvyxKNEtcptsViAyXQAgGsFAbhKSAIdoFkbAKtkBlToTyQsErKpfpzyNxsLsNLaRMSBbnanFHJQLznoAWKwlhXswtxS",
		@"vWBebDsVxrcWe": @"iylfmKVwjKuPRdyALEejwXIOIiORpDvdFKgDoUawZOzZiZVFADjhVYACDWHrhneXaIuJZyjynfvTUmtDIwxcXNeCBgqescvjnVMdISoQNIKjUJDlhRgCdoeJmWxlXUuQrcYuZpYEhXumUUVF",
		@"RtvyLyxsbbe": @"lBqgktiaMqVEtbPcrXFrnfWCmVjMzcMrAWwXwAqSVbAQDoksNnucBxBpIxOOtpwkdMgbskTLvBGSXfiqfHHObjdUfqEBjuQlQwfckKHtwHiLBKRXqQLCSANP",
		@"eERhCXgXpup": @"PKOWFofVTViCvgZSnYPSsoGYwaChQDUNYFwRpeslQyywmtMAPizUfSfYOetACUWiPfmsTYnqJEtaaKUlnsvhyOHuworhurKeLtdwFxDfz",
		@"ZokmByDcuMHZQfzqq": @"POzNIPHFCAvYInjplPPTpAIRWvmOYCVqEbBNwXJEEIhLeNvkIvHciGirUVjdllTKSOvfdfQaFJfRMErSYvenPhBxnIHCLzTsuDmgVNlE",
		@"yxiGnjixPdRZ": @"iKVRKMQbUijnLyAFzKzeyeTbuKqykvtidcARJNjBEEHgChphBnCtxtVMzBrWgpzhJGfJCXGFZIRvLxNnWLBUVqyZHSuKZxQVNjYHAFyCGaJYjRCearPPOXhAajzxAqEOfeWljzGbQbWq",
		@"wfbwDOXuVLTQIev": @"TVQkcdtRJsPGhIfDkhmuLeiDQkXnxJsGMHmGTdyUeyOsNhXOgdoiAsVrzPiLmlrLzrKWjiJJoJcqKjEDTabWkogEsxLwICFTEHBysaYCPdatHxtUvsR",
		@"dGrPkXddqQexf": @"baLDUqbjHOEajyWirLdZmdIiRCnPABJfSiTmvBpddhgdciobQHETMqooTzazqsYuyRtACfvpavvCwhxwFOSrZPEkbcOoBQAerkuPZRWeMHCyPlRKO",
		@"xyXATXFXYysmXfSgA": @"MzCgMoRawtUGBgSbabEhPokLxTihblUoiRqtxNzNRyPWizLMpOaKaZJhBdAHdhaLKKVAnwMkrBCQTuwCyJAQOMgeiJbIDJVUOSVORfnwObbcWdIHinppsBHmN",
		@"OcmffFerIfqnPRrfe": @"XYWVThJmBJGpmdsBqKRsEqOLXHLgpmrObnEmIUgzwqGMdemtRbBVDyAwWcSVLYWfEfdHyJCIYMepCFmhnqPtRTaOZnabQShOBdminUUuxpqfAnASyCodrKNNqQfDrlFJRIoFYsEXpIW",
		@"jRHsDYnEUa": @"daqzcsqqoUhPiyPPTHVaLjOXnZEzobCkXNXlqdmEuoCAlgoaEoEKdnsCgZrZSCoZOILPRifkkCTuiLQRunLxkVLzXOQJSjchQzdUAzzMqNGCEYFZrnUoQNaNbbOicLXRtLSVpkDruL",
		@"wYMlaMnrqIFbON": @"yAoSMXerkHnXJYGXyQCzysJkehhzCaPWnMayDIzndVZcQpcwlbsJBodXkpukQAgqyatIpOOhYfkFVjJLZftLnTdYdjpqqHkJYURqXgwgdkrrUMdzxsRx",
	};
	return xeqmeyEpjhnZ;
}

+ (nonnull NSString *)gccVYccxtBhfsxkHFhU :(nonnull NSString *)lqDGVGWBchT :(nonnull NSArray *)JoRrMCaeZpazifajuv {
	NSString *HOpZFgRTLybIpFvbg = @"zVZMveYyvJRYmFlxGtNJHxRhvbFnDqkrxvkiyIdjcNqNCWBNdDOKTjYhcISQquuPUnhIOtKxkBMsTTYXrPSaPlNnfwxfkfXQdXEPLJ";
	return HOpZFgRTLybIpFvbg;
}

+ (nonnull NSArray *)YWYeABzzQZcQw :(nonnull UIImage *)ljSywUzRVabpbC {
	NSArray *CyEdtwzleUjb = @[
		@"bqJSLQPgKIXnHKEwVVswQBMhtsqmXrkoSXfzdCfdAZsVFcGZTMkjjEahnJMBgMxLbvIlhiDMDBaYUfkbKWWLPrKwCdSreGeEqgDagLVcinIBYFLvttyKVmEjAPvSqFwfWyfkyVho",
		@"XBrUXWruDAhIvJiNoOVvIdzsInqoqWZRqWLKEduybNBbVbTzZnqnfjZbDtFmaGBngMQPgnuoWZHBiCksuOuCTdGtrnphgExPTYQdtjHBLqyeAETITyqMXOIzhDNkBDNubxgeSECGGtG",
		@"aNayoapxPLAOgRMyGgXFPIEcakgstyBqNiFKqPJmaJsAzaZkfuBAgkxdYDOkGDpqYezzCOxozfxnXAISNDMpzHEhvEWnLMlXdQEnXWbnzuIzufMZhQhMgJMNXLIFUuesISHLvFwVlQ",
		@"xXZzYCkHZdbptvKjJjFkupatyXrXZjZxrWZctZzTbFCeyVFMlXBbIjFuJASkOmjBfxkHqnPbEapxKCQFDCVzDFxoEPFXGsyKwRUhDFzgPGYtbcWhNrlEZOGxTxGlfZqbYsUgVO",
		@"mjRHNUcYPFkPtfADNbGVxQqtyHAMWAkKAwgygjJUskmINfMeCThEhMnRCEeiQMMmEUCKgNCVAainaxaKVripnfdtPigrQmRFrAiDCAwTkocsUyVNCsXVMEfQhrgvrIVJTBvwmubotTVAsIc",
		@"adXzugPFRuszSnpRIuOrwChyfRhKyUEPHyMoYuoVWrxoVZYiihlaHJwvawXWmTZpEPIiQGGjBOCxqPnaoUDsDSroeLdXdiCjEKWaTNFmNaJgWGgAkNgVslBqjPCztLRb",
		@"RULXImxVDAIKYeLiehCTXdzlkVUcQmgeKVWMwLCeZPuCrbWyHJNOVsXrNbMSyqmDJYipYZnhPVwWoBajNocnznQdzFSQQoFuTAtxStkeLUhwytNuCPbCGObipoFwIPXWkcyvGfcHVSZrmXwjY",
		@"NDIKmShLJmrooiQfRoOpmOjSnGWjukJRmryplMZRbdjWgIovUDTDadFcogpjBJJNTdzlSoPlaZfbYZvhPlIxBKrdiWPromeYNfYwXulOWBLeDlPVdbYZNnMBcHoZHvSeklDLowvssQbCZRJaKPQ",
		@"RGSbtPnoccaapIEBBSNLrehzNUKcngMOtynnhKAFqglkWJxvvkhokmbpOOglUnUIJfNXJmylipTULINUbtKUhBnDyLldofKEJdqNnvMMnHRgcBFosYeeYeorhBs",
		@"KIFMUilQcDPlFDdKJDbcKHoCELnFAHKAWtMsIxICsfnsrXpQQVzuUpGUiOwsoWAeUnuRIwvIsuNOxGiZESjwuLLITCOBcbWSgyMvWjWzAFJGyghynOyhO",
		@"ixtEYLfXrXfBixodJkGlTWLnJYCXRFNgasbQVjGKlkngvZcypfLqsEhKtfZODcwErFaUHZWFelsRLyUyTcLRJFJSUopRnoGeJkosrUdHdGrCQXDYxjYLZqrdfIUavBUzibwOyHoqdU",
		@"AuUcyPINNXnpZflYnfxBExayAJxDNnlDwUjQiOCcOZEnZFqnloNlKZtsVvwVTgbuRsifOhjSMbDLAbjBwHddIDsxbArxRTgsXGpzVeuaHrORRCvrZMpHuE",
		@"ndPTuYcaSPoSytWQUSQIFoOEXvbwnoDFwTvkwRqnrxTKaGOFTXqoAcdIVbgLWYacawqtEEpBWdftOwNMSypwDNEXWQEPRAAklGRNMTFiGMdOnCjLISKLfBmAFvLMnxoW",
		@"wLZjOFsqDWKKyMsVzSWNzcQduLOxKYPnpCYoVnAygrPVbkOnCgFVSWzyIIqRqkMvZAYdNTXOXxMUBJmSPzoOIWHqZbbhQTGuraUfbwi",
	];
	return CyEdtwzleUjb;
}

- (nonnull UIImage *)JRNwGwsaui :(nonnull NSDictionary *)eEBlsSHclQdYsQPj :(nonnull NSData *)KBtaBPnidfWzzcCnx {
	NSData *pIZPadrEeNE = [@"cjlglykQyGhLCueYgXNZJJhAKuKDqwoOLOYnITCwvYjpPdokwyFbIyBuJtGiGeFqOlBKHKvGSapBZiQkNWQEyIOPcEpKvWdICMuGxkSWAdAxZlIbzSCpjMP" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *XzfZrWrjiHwA = [UIImage imageWithData:pIZPadrEeNE];
	XzfZrWrjiHwA = [UIImage imageNamed:@"mLaZlEOhqNKDINipBdMOSlqTfpNoXNwsJKdDgsQBMuqsQuAVcqyCdMGvQhZYcsnsDUFYwEoourqwqhoHLVcJIsgRpSLBLGbKiJcuDYSQStCFIOImagDxgvQOffSK"];
	return XzfZrWrjiHwA;
}

+ (nonnull NSData *)imJGHfWddrS :(nonnull NSString *)hWVPyPVSzRCTZL :(nonnull NSArray *)WXQeRIufOzhPRW {
	NSData *zCDKAANHYcNQRODnjX = [@"EMhFhuteIvOjcInZdBfSYnEhinrKXtacPRDadoYbbJgzFpEuBkhWqjDRoSXndlxMUJIpWzuqIQkFngmQVREkPjWVaSiNZcUfzyQTPphjNVYjFJCCrKeYkiZVVwNUueJk" dataUsingEncoding:NSUTF8StringEncoding];
	return zCDKAANHYcNQRODnjX;
}

+ (nonnull NSString *)jNyLVZiEtLUM :(nonnull NSString *)kUrGURdYSLdKxAPid {
	NSString *yMecdcDVHnNn = @"FFUqtJmQsPJiunYLreDozTNtSDofysmllDXghMFbeAaxPgDLjMTndJDzVzrlgZKJoBRUOIhBiDXjmmAlIZzvGFCANwSpthcuIgRk";
	return yMecdcDVHnNn;
}

+ (nonnull NSDictionary *)MAMxhDJJSgQwXtHXv :(nonnull NSArray *)MnrVWLvmRlFkGFAo {
	NSDictionary *zLtFFbNzsfMF = @{
		@"iBVBDCQhnBKtaAO": @"zMJKSeLuTXYekzkeppVHuCYzdeWHZeRUkgKskZURdMgdTObKiPCqOxAtrkUzAOteWoWCfbJsgnObPaCRtwPPCDEmZWJcHLkTFeCpuLXfJ",
		@"tPovRZIjKDTbUlhbt": @"RJleKmbZxoZCdWvkOHdGlQFBcNlSGZhTPbxTCoJDFmwDzJVmBQrsBGzomfuVqgVdQsKiZSOfinoIadnjtqKFqGLJMFmpMRNkrEdXIQgmhXrFliZGsgpVyrSAJpCWpCUfQxmRU",
		@"qdJfEtQDKSyDmkDVj": @"YVOXbTjBYChtKKoLdMnDTnxgOAzPdoMbbkJFzOsExrLLyIfxDnwJVcZRkcCKWrqhSGFoPXYVhEdggLXWZIOMkcvvzLUZIzfxwLsufMyxKifWVNoDyLwXLScTnKCtPbgzupoNbsJqr",
		@"mvOjyyHBnPRnq": @"JjgOkFpfJeiPvJeNZqKzJkaSQdKgdIsoblEdqUAfgQcZnHCGLyJSTviAUxPtvAPGkhMpZkotMRPvljCVIxFDuHXkoaaIOFyKPXTNerakfHjjOnEnSvFTlZCl",
		@"mHrfmNIfJV": @"hpanxiEVUzxEwlelOlMFsebYybrmkBJyjcWfDwUYteKKBByEdhAbfcytpNDIkTOAKuVSzMohQyOvVQJvIzPWHPRCJtozqNBiXTfrVNcvxRBiwGLzwKS",
		@"plPJPpGejrN": @"etRWgloINZhiIRDwIfGobMPHmRPchwZfNDBJBfXeHhIlJZgZPgAntFjHEqdnUUlFojxzUQUbBZpHcGqBqOWRzIqlFLllBlDieooyByynxRksSdBM",
		@"YoEscwKVroSIMG": @"SCNzwoClQgISIeHNCfJWGmNskGSVndscRGGDQUccOlpAreaFmGecKVdZwfFTnuLDQoreCylbAqkNXEKEVEuYFuPgBOljUiSwkiAJuDlzeYNANohHoJuHamNrUANku",
		@"faHnlGcPoZTLEXER": @"LvZyxmJmncQnbTKDRmIFbMeeDRKqhfAxSNRQZjZpSHKFdADhEVdYBqBebXfwbZLXdtwXrMTerNIwAuotBupGaGVCEddfcKtVSHMGkbScHmBrCBmgsUIhIxJgFbnOllilQWKWCPcluiRaUfjiae",
		@"JsbsUQsYLagZqa": @"vRafpjMjyPTljccEJDzVZgLRoWZejfoYLBVbckHTqUxWIhzwUrIkmILDBuQbxPLenwBvTDgQQPmiDwqdlRIcWFKFwbjUFDmkgtwQjCPKZ",
		@"XzQqDciuJLw": @"pBUONONZpkYZUkxUesEydSPNJItvOggTcLqhpzIURjzWheKEpfVBAIJsoDPWUVFUdVvwzVkWoyDrwpDUEYCVZdoAPejilQAgPqgVPeyGqaBGklxVvWxtahSOcVummBJxfsXRSSiXJhmXODuSePS",
		@"yDEMsbHcgichxicAG": @"nHWviPayWdRWOliJGQHmrMhXRriZVrkSidocabYzUpxvzxOPhqIWEmnLErpKbIRpywpqFjIkAZHWimaCYriHzsCljZYHjzWlxSBaQPFtfTYbeWDKGXYYpFjFkNknKVJamRHaXa",
		@"eMAvlwBoFXOHBXpyKe": @"TExpjlOqNqcSVAgTvsYzWxmfmUXzGBvxSwijLUtspWDVfikuXkMTJdbNNrUuqkGUomdiJVLgCiPyYAloecwdcbvrOFHclWxoDmcLwFJiuXJZiRafRqg",
		@"XmGkdNigmkya": @"JRZNuLMgCnyZrxrvRywcjQilkDZfDhdaEylmmMQfQcQCYeYQNBPTFGLwBizqDpEuiNyXOavzuSejcBWXGDyGUmiffCzLwIBSZagm",
		@"aIMxoEhTFZbsGGNfeH": @"wUMqRhCDjwkmcoMUJVBgUFmCFyxSGsWnDnGzWgYSjjlpAdNnFzAfZmVonYvcNSAVZcprpOipbXJdNMIVZoRbLXyvsyORVdAAxtnWzXKGxxjveYVZfPQShunRvfWN",
		@"WgNmoYRjrhARmTJY": @"GVcClgFGocrQzSYoinZtsFVInjzsaRhWZJEqRjlwgUjLwcIJAwoAslZVDememEboinIOFDrFgjsvqHbSklPnZXsOqfdrZeLRInPYIUFOsVHzaOHXKMu",
	};
	return zLtFFbNzsfMF;
}

+ (nonnull NSArray *)yVwGJKIwOCopXwnBdyf :(nonnull UIImage *)dCnuFKyULEE :(nonnull NSString *)YDiNhANGuIGoKPqIgIN {
	NSArray *bPCmYNROQq = @[
		@"PfRpAHWLTxewtfeahaGHcUTsQDmlalbTUBbdluTQAhcBPkDEsmcRDWtSnUJQOTMeBralaArMLIPNhIeappLAWspxPwjteWlYsyoMuhAUynV",
		@"dsvJXGZWwwcyIvkvCYhCrLxCCaBbhPjpwtzaZidMQqugVcsOxZfvVxOpdzUfRaZhTinDuffkLKNDCphgdOJPfGRIKkGgnqwUkRnOvNkNeFuiPDXVrLtnwOPyGVHvrmDDnkqmvLkKCEXfnjlJSNRD",
		@"BlsTCTrOCvabMjTPLCVvmMrucobYfDdICvUJrrSzOipHorySmMtGZYsDbutSPqXUqGctJfxVIzmaGZBIihFtLuuvkNioCKWwfgSHzbXyQGgTufVChKfUOtKoiyZLRWhqFiXSrjrOshxi",
		@"xDmILSwAmkvXJmLmCzniuJCKNxnnPweDNNAltleJzkmVCRFYQdDnPimtHLdPkpbhWexmbMEErxGuJhmeqhssweFHRJKctapjvzszqGjjVndSQNDrpDuoiaKDi",
		@"ZzhGBKnfLSGyShGCjihvXsQsLUPVbzHdOcvxzvNdgfcsYvVtfDArbOisCqQpJyOyCIsWyPJMfFmvwNHYoYetkXrupJDZnetyQFcLdXJQfkRnYNHdEQcNnqWJgUncpandBVcTGIKgnGhevDXRV",
		@"cCTYAOCLYvOGXyNVMDjsIRZxyzHqLFLNBudTVrTSlOloOCMVMMfrdJnCqiTJQvumaRtYUIuNPlWkarMLNWByRUnRqDKxBLLyWniLXDmxHPvp",
		@"BoiGgRRVEyFMSgBWnigXULrtmCKlqeBtAQXkGTAngKSsOmQeZQURNnEBnixnjwmmOqoQFADIJpzfltsSbRXDCnQiIAzcBIMIbeeGBygzPOHCVrvPJaavUvnEtkHPIicHCnzC",
		@"OCaifVdgsnDELmYeTTnYdUVwoTyAtWTjTJRGtBqrRFBFdHCRKeFVxBVuEOnEuvkUXtekFXYuduDqxPDIRxRhmzRRelzmNxdTNOxktcqSBKVhpmBKZjrnJIc",
		@"QBONMkkgwmohDCawjrEwvHftCCNdjdvgCtaoHIzeslhIQQSYIrbypdqhClFIbrojslTBqcZtSAOHyMVbsqvPinVqbqGMUdWcLrYaXUdMmlGivfjtTeUTkwgWRqvaOwehCTfdqnfGVQ",
		@"pKaWKihBRxaWRFezhztJlsrgQRfdAznHUOglXLwDMPKSEkmsdYFBOEDXvupUDNGaPFdjkDgQwikXZcAmCBlYVbgwBQQBMdwkggvFBBoAbDqZZHuMXqlCmxLUJMCFRtUyQnAXQYdmOKF",
		@"pcAfDhDpswOkZMvvipMLIkgvQjUqCHZYjhohMWcEyFHUEhbCLBwmavWcGsdGFeSgtdBecBJEwMolOejrHKBsoqKelrDFAAlAOMXDNqenAeznYkWZbKtfOGOjWbjQNm",
		@"QOwPhoLwMhTGEAoyeFRvOuCQDsFFAXjypmXYGbixQOvojxrPlRQzIwxAuAyNCoielHbnYDTOSdOhZmygOffeRhkaQskhjrXpTSpqjqeSyyJhvfqgbsfMtzxFpDRmeRCBYgHDhzvXEV",
		@"HyzsoWZuEmQwrUbiXxmUoAIcxDVpHhsZsiDUzOvwsKrgEHUhKzQYggJDMGMTeAjyRALcgOWcIyZWdyOEfxTaYcUFTHTxCxszvBbKSVlKREmqkYzoPHWAMg",
		@"bQrvoqxjyuHnscrZuEBsOpuwmexJPshGKJgGPEIxAtMKzwlYDSNlBxLsbMjclKHxnuYesDvQsgraWpGBbHqstjHcDLtATOWfIiSCocAVOjFZbZrFYTFfjWHMYyzwvDvddZevhohyPVc",
		@"pbhiSSltsFDSCVkQyXfFZxiNYrFYGqDFoIaoGPkOIAynXXLifReaFfwpNYQfFongEDXesiHdCcXVgvxOUMfmpjSRCClvpAvgOgKSaMOSmtpbFRFjhILJaFayVwhmudiiUdcmFZbjE",
		@"igrFViTNItwJKZnDFvullWTbUAMfcyvVslSAyBnsUOXxRagDOpcNHUKSPHnvcUhQTIaSkRDhdiGTNOXXYQqDRApepjyGhjClXQlomiJgRGfAzyxYARQd",
		@"aSHvAGRnTNOdLAjUzRkIcUxhCyutsaAYdOUHNYHWrIuVWYWonUDOcDIUdgpBBZdQUQliudpSeGuoPGabXfudJhZskhSdkHbYPjpEKAVREKPcXBgzxFhKlJNvdmVvRsjdZPfPOGGgMxPw",
	];
	return bPCmYNROQq;
}

+ (nonnull NSArray *)IwfNeHTMuaCg :(nonnull NSArray *)aJVxhOelZdjt :(nonnull NSArray *)AWBUtgHbLQamXqlhAi :(nonnull NSArray *)zdmnIwQDfOrwr {
	NSArray *QujbWGLSVY = @[
		@"iqQYQAfvDZamgePJcmmUUJUIHbPBOWsRIPAOyMRSFpgikabFDcmUlhMxfhdNccHkKEYUnxHEiDDEVTIwskNdFgvWsLOccGXGTttHCvglL",
		@"IoYNcLZaWQMoJdWwTWEvukEPhoPwYAeicJqDvzumMlFUVeulbRxeMIJnEUcHeZNPUANKpfkVlHJOPQwbgdJCQbWzCmFqsGZZPaEUTazFArtMYk",
		@"dnTCXEeNjvXOOFMPiZRZVcAJVOYetYhbgCzCBkzexFHXsDXbhOMJhIKwCrLNfswGmtfgDEhBfCozUhkDTPulXvoaRrIdbOYCqMQIdkBbUiVKetDUdn",
		@"CnEvULEgfWfKspTpbKcdGwbUeeumalYufYEykVAMEuTBqjGnRpscSgpCWhqzNAAkPuelwuqPLnxSgwNQIiBvQVFTiGOyrkMJNswlKThCaSuHUEOJLNNKyCdjOIoLO",
		@"FEumTgLMCZVjHNJrJshDYUBRsRLYWIbmTvqaDlTYETIxfROoBloxIjRclskGzpuehpTWIqNndnObmHbgCfjaEKQPoBzFVdpCPoMpowIkVtHH",
		@"ambGgWiZAHUtYZOGjRqzyBhzwsKldMsbtDYKBaumAsFkKoKuCQLXABUIsNyxCsJPPDGCJIYKGmZcazRVKveZBMMbEqnivIrEWvbAqyoejLTcXtuOArUQUzTjCsqA",
		@"VVCbssiuyOTeGsylpmQogHKfYkcrjnHemMVALHlizsRVbRIQxWJlVDDsOLfefTuPhHLRibzSsosHvFTleYcIlrbizBhrijAfGWfizXexhVygbZOfmIQZvpPqdPVhVtzoAoFV",
		@"mOGJBLAuERoQKWPsEEbvbXfKllCnRGulaZTyeNDBSOrDPFXyMqsIxFyZtlJtxKOzrbztzPPgoukiOLGxFwmRCZqvvPCMaanftTfWSKHnPCjzo",
		@"SSiWgehFtuyaMNKEdNFDThxeervsoLyyVxaLjgtZbvPiibMejcnXhmblVdyHZVlKKFplYIqQCoMnecZtNqYxtptwAumjQfbQDMpomUvncMbTxOCimgisOXlfRkjackC",
		@"BdoQNkADNxKNFrhNBlKABHEQGWlHKTKsxNoANOBMhUWugZDgUFWUGrBzJkNJAVFYsoyrdFcLiHJkFZdAKTsmWUzZNSLckPZBCOAqElGNYNWw",
		@"gzRjfGYqTDehIXgvpOqzTthwRyAYwexCxFHqeJmNNhkARfBNFEvWCszwGIrswYxkadmCnpBTKpADhjsLBxHAhesmkmpaJNEBgxXZhEOM",
		@"tQOPOLOVLckJrsMXfSKXJeKFUwETRldsRRwWKobESpiqpoTsuTGPUFNQOwcMcAtPYUEwUbmjQLVRSDTHraYhtBWuhKeGwJdvYaPmiyoOddcxydmNBN",
		@"SUbxeMpRHLYrHXhafbUyMVvAZxdRQONCFgXLtBnNnSioapuwmkWjuSYmjyJPPmTmPcJvjtmNwvJjMKVygBSdsSeBvXIswzFswSSoDhMTvbQvsT",
		@"rYkPxNbOrdzdAOUxiaZmCNpLeraNkdUzDrhKfAScirLoBgGXFJeYlLxIvrsYoJNmjKuamRFOKfvbbjjvzumXdDALGlxjRBpGanOOwHtGgccqMROfTgEEBqTZseCwQmrpMaxBNJuimRuniPixthc",
	];
	return QujbWGLSVY;
}

+ (nonnull NSArray *)ZmMDMChkYHSfVBMTJqk :(nonnull NSDictionary *)GnLQawyePxVdtZ :(nonnull NSArray *)ZBfXQtemyKCuSV {
	NSArray *ZEpSCpmipOlxEyr = @[
		@"MeSaclYFheUElpuGCFfCHldTJonMScpqFgEnOLTAnEdsWoXFVvdfiFBEZVcHnMasKGcciNUqPMxgptYsFTrMufMKtctNngQLnEfMlIBnkjASxQDdAgYDhsxayvYrvfWtntnKyUmXftcMBZ",
		@"xlEWWuAhksizVPWuMHPySQKGlblCRpVAtcdOMFqsFgSJzOIQbVRNORkBfswGMixmhihvuJRwzsCxbfanRZKJabMMpnfcLKsYFOysMaePUihlq",
		@"nldKbbXIzZonokzTxpomDrfLSAQnLufkbuyrbkQvGmKqWiRcvtTSxgFLsrwvYEeSJGkhLaVflMDTBaQxmUmffIXpXDuyJzPFuXayOnHfVSckQUSFFLrjwGimLAZDGiZcmKMbI",
		@"OwtoIoqHWiKCTsGaOsdaoIryIcVOnvqRrINTTcrJZNSpEsteKCSrOwadIoODvejhrSvBUEnUVbmuOwIyVlfpZrzipSKoNfGqYHslIucUwdWDurLFpmDdngICsTzbfTwfleFJFIUFzmt",
		@"QaVjAlJmqGXZmYsCrvgGsjuOzSysFCvPoOfmWlZkdsvGPycMaaLXqkpvRnJYdAjoIPQkhvMZAXhRVBELvlriGqMPeBvGNhinRYhphceTgnQqBuqbYoGlhemFJzrNCjeeXdvMNZjFUzgLTbGNACIUm",
		@"IyNjjisjhhbcrKhnbUokLwfxyIBqPISbtfeLmkrEcEiZFGFdaSRZbnPsdlebezBJffKslLNDNDivkUtHOsjjTfdxSrJzfHfjFjJUiLiukPGyKLmguWREdG",
		@"qLffstnoZedTUIPtjIxqQUbSVuQGJqhPseuTXNXhZMlfhjTEahBlprOOTWMueVvlqczKQoUaOUIdwcXsBlhHSgEeTGsaCxSTDSgLAlkhfurCWuFFfUiPteqdzztJsYtfpmUTIciGYnKKxmAlTynZw",
		@"flwmTPvtkfsatARbGVKMoFpvgzDchZJOJILkvndcGitFZbqHDFvtOxouZHzUTVlFnqMqgxtSCRLFfAUqYZGisFKTpgtdYrBfgBcnYXFgQYILVI",
		@"FYyaixNPMLvQxTRFbmatrkIKzKWDOdFivJelXeAtvjaYEJSHeJLJJkGZzENuSHieAcQFqXRhmekwcAbxiaIFnLCmIyqbzFPsbIMKlEeZvpcoFa",
		@"zCUbWarXCJxrHXSFWCkpOoNEVOIEEqyVBdIvqvLQybMqbUeUUBOnkemrROlFQBzJkSBUgJapSQxbxuEKxnXgxkYxCAkJmWnqjmcnVRRC",
		@"eEMMfglWtTdlvqIOqozcFKwiCLgJAMMpRvTSUsBqXzyivwiEvTBCJDqkYAsljywZKZjIZZNisAOFthdhFFWrzfWaAkLUQGwyDwGrZoBbogXbRLkabBCEiwnPfosdVCaFcuABkBi",
		@"PrGdsWIBLykbVHRRKgvGrjwbMqxvAVPgEhYMMdKJoixuwhLNNvVhAiaGNShBDGpHWWZtTUMujTjuinbNtdGuuBgEaPETfCtSlAgSkbIUAjCSEuardarFTyBNNIzvBjxzvypFbRtwXUDuuDwWKBofZ",
		@"pNEAwvyghrmSdCEihYoKWqyEPxJwguiPHkTKKnqssoRuSjDqtCfatcEcEphVotyoWVBBezltlOrCNkSYmQXiotyYvyCpmvxzKfugkNbMJZmmlOdJMXGDIaezFesQGLTzOlsOjKfMAG",
		@"bDSddKZnHBFPAAmvDHwxBOfSKKUnRORMHrZZuJHAIWDRjASfsDVJoruIKKqhhcHtsLIbIjORaquwfQNPfkcDgMbvdbkfqeBhZxSuNoyEsDqABovwkRvkShgrVsZhYvKsvBAwNGjBZSzvqeMiD",
		@"IBnzJdqDxAzPzgkXbCpqfeKkHLGAZFzXygqBtYYVbYpSXlsfKBGWEeiFDGauKwONeOgfpadCJsIOFyeNECDcyxFxLFASBDKbmnYgtbqGGHmJMuEcMRZdlYoiEclApbcJhvekpGIT",
		@"uqemdpAWntkGUXztRcfIuTImzLkxTzBSsWUELIJJdhbtoXVYEmSKKgCasMRInAAoRSStXaDAdEhqZwKqONResjBfyIGwNRFvNayg",
	];
	return ZEpSCpmipOlxEyr;
}

- (nonnull NSArray *)ZDkkdNGCNwfJ :(nonnull UIImage *)YziOrrdyRjBSW :(nonnull NSArray *)oxVDbGLLgHWOnIDmH {
	NSArray *pbixWSpPCnzzeKn = @[
		@"PnbtZXGJDEhkFfLVlTkuPbGfWIDEavEXofwCCCKaOhddyXrNGnjxogAoYhnXCPOWIqNLNyPEnDanjNbsnHqJVujYoxOlwVQMHvdm",
		@"UjhHKnFLAbtcGHiyGNZwFupRBxmsmRKRifKXwomSIhfbLQJMEoGTRufdemZnGxmEjsjgePYzULUEzMIwMxJHgVmDEaLdXudSfivLdpBxSRotKxktMmbJAgThEJqTZMBOhWQCTKAVqGgRcCz",
		@"utIDRQojOVMUQhsvpEQaEvyynOEMzMTqlMxgRhFSCPvqMlRsCEHFyMpdNFgIrBYoMuemWHIkjMxLIaqmVcAQyhvsKRvmbntqrfzCbKiIjAnGCizwAMoQaOOpQoWNIbaANuIbGQXrKBeuetLjJ",
		@"OtPJDMCnAocKMyzCWKHeJFSnkhRabIwKzeTmLtTuoYzpMUxAVWdbdlcupMOblHCKnxWUvhAijgBEjLJcJkiGAuvjGkFLAueKDxbRnvjzlrhpZFbskTsRRzncNFN",
		@"kPGwtkirgPJWWgYxlycWlAQZZeNNbNlLyDfpgSlBJyRWSdOczqzXJzBWtRibYAZeNsYQSYgIcYRGFwUyyDAIfrujRuMhRYTSOUeEjjqjyLHHfcEBrBcgKSRtOcaePoxEvKdKByrmKS",
		@"HNNeWMXghNZNTrzBnIkJdfclKwxdvlATmQqHvJPuagQhXkUgbSlmjpsdCXMQoTMYODAxunnZVUmLNXridlgKKlUPpJxEkzeaDIMSChbjHWatFNtyWulsEWhfFnlFkTGXMLLPgYZ",
		@"AfCLHKojzZWFXpIfDybMOsgCSyZeUEjzvfgHwWujGtRiNAGJUbxwhfKcsLmGwwHSDkzqgXAOaixHsSeoiSXXItQlhRmyDhDwyxbiuWqNtMCedZjLZdmFUKrZWsjhxblsKURrDISJcpCiOxXuL",
		@"AmjsCiVKtblqogRYZUanrNwVqpAgWPqkNoTUkyaIwmJLUygHiuwoblxDDzsxJCBEOSejlQhqoloqfNciQursubRbDAsjKvlCoIUeGzWbJcLxTEclmrEZzJEjLRWQDSjUnkMa",
		@"KcGsrYwdoezazkzGDylNkhkGdfYVqQZgUSGPwQDHSjrlPBLLMSTXysaLBTzoNHKifjwNnasnFoxtLrZsMzhuquxBJByrsmkeLtwxZHBncgmCHPBZKVOTYozmYdXGYvQUKKrzxGFvflxoLEG",
		@"SuhmRARzXWNdxBFGhkopBTAOgnOWzcTaRPJWOUUcStLocCoMEHoLjCQPfTpJuVFqKQOamMWECFydFeOIaqHtXfJpvpzJZSIIejxkfIrBwcScxNHneek",
		@"AqnrHENzdBLqfOEeHydgERXHDBVWLhCezTghRHnJeoeQssCiNJbOjvSXVdFniVtNsBPeyPkIyOMvDAyyCJpjPehvAyGXgMQIKDuagRcEZgFFDuIesuOBAQ",
	];
	return pbixWSpPCnzzeKn;
}

+ (nonnull UIImage *)KHYkRkoJOrhvSx :(nonnull NSArray *)wwREoTPGydEb :(nonnull NSData *)IJVPccMLOJPr {
	NSData *ZVMZVmDJrurupNwPDE = [@"FTAPXriUMSHIJrtIPLONaHnYcAPSdmGMWdnCPOPuYTRZsnhGrSmTSCBaeZZdkAYUYIVKJgdixbJhNNPBIqwMkZbLFuzTvUKwYILTyKhpbnmZjIVdWVNdQmLNJ" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *GzjQdYhuDXDlbiNnX = [UIImage imageWithData:ZVMZVmDJrurupNwPDE];
	GzjQdYhuDXDlbiNnX = [UIImage imageNamed:@"ouKcIGodgsIyOQEIeUKWjRTSVghlYflPoTyGNddhkAMhECJxzlkhIzTnDJSKVvYMpmrkgkZQupOjvAEhfNMvBNbcHxjRxOOXPWLdCwwQBzHvGIHQAzjWNWnmgp"];
	return GzjQdYhuDXDlbiNnX;
}

- (nonnull NSString *)pxHqhSXNhd :(nonnull NSString *)efabKdpnTVnvWMXDyi :(nonnull NSData *)xHOFhwEjvgKQzykS :(nonnull NSDictionary *)JyiVhnvHsutbrpmxz {
	NSString *JkpiZLTotPFfgysrxZh = @"rrEWzrXwNZuypVyDVRUvSgVbNzvhjeVwQbTCcwAGFYYJzMJyVDkrxszHorJJXlKkUvuoHqbxbaONCwnfzfnKIsnzyzUzGqIsbSIdosYpK";
	return JkpiZLTotPFfgysrxZh;
}

+ (nonnull NSData *)gZbNfIqMXdgsnobuwi :(nonnull NSArray *)qsJSpATOqL {
	NSData *ZBQsrxqMyhMrrsfITIf = [@"tYljVbhSOkJQhmrwyhsGLIBQoidWklfpiNTLCoxWTVZztHcyNAIEDnpcXqAfXZNGUTsGxooNsWxAQcfbBiDNAmvMGSzrhDnfFkrdMUkJHOlNnDwLZGJcapRYzLaKkDogEGSmyxCBQfW" dataUsingEncoding:NSUTF8StringEncoding];
	return ZBQsrxqMyhMrrsfITIf;
}

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    
    self.title = @"密码修改";
    
    [self setUpUI];
    
    //记载本地webview 加密
    UIWebView *webview = [[UIWebView alloc] initWithFrame:self.view.bounds];
    webview.hidden = YES;
    [self.view addSubview:webview];
    
    [WebViewJavascriptBridge enableLogging];
    
    self.bridge = [WebViewJavascriptBridge bridgeForWebView:webview];
    [self.bridge setWebViewDelegate:self];
    [self loadRSAPage : webview];
}

- (void) loadRSAPage : (UIWebView *) webView
{
    NSString *path = [[NSBundle mainBundle] pathForResource:@"ZttRsa" ofType:@"html"];
    NSString *stingPath = [NSString stringWithContentsOfFile:path encoding:NSUTF8StringEncoding error:nil];
    
    [webView loadHTMLString:stingPath baseURL:[NSURL fileURLWithPath:path]];
}

- (void) setUpUI
{
    CGFloat textFieldHeight = 45;

    //密码
    self.curPassword = [[UITextField alloc] initWithFrame:CGRectMake(0, 0, self.view.width, textFieldHeight)];
    self.curPassword.secureTextEntry = YES;
    [self.curPassword setLefSpacing:15];
    self.curPassword.backgroundColor = [UIColor whiteColor];
    self.curPassword.placeholder = @"当前密码";
    self.curPassword.font = [UIFont systemFontOfSize:ys_28];
    [self.curPassword setValue : AuxiliaryColor forKeyPath:@"_placeholderLabel.textColor"];
    [self.curPassword setValue:[UIFont systemFontOfSize:ys_28]forKeyPath:@"_placeholderLabel.font"];
    [self.view addSubview:self.curPassword];
    
    //密码
    self.newsPassword = [[UITextField alloc] initWithFrame:CGRectMake(0, CGRectGetMaxY(self.curPassword.frame), self.view.width, textFieldHeight)];
    [self.newsPassword setLefSpacing:15];
    self.newsPassword.backgroundColor = [UIColor whiteColor];
    self.newsPassword.secureTextEntry = YES;
    self.newsPassword.placeholder = @"请输入新密码(6-16位数字或字母)";
    self.newsPassword.font = [UIFont systemFontOfSize:ys_28];
    [self.newsPassword setValue : AuxiliaryColor forKeyPath:@"_placeholderLabel.textColor"];
    [self.newsPassword setValue:[UIFont systemFontOfSize:ys_28]forKeyPath:@"_placeholderLabel.font"];
    [self.view addSubview:self.newsPassword];
    
    //密码
    self.againPassword = [[UITextField alloc] initWithFrame:CGRectMake(0, CGRectGetMaxY(self.newsPassword.frame), self.view.width, textFieldHeight)];
    [self.againPassword setLefSpacing:15];
    self.againPassword.backgroundColor = [UIColor whiteColor];
    self.againPassword.secureTextEntry = YES;
    self.againPassword.placeholder = @"重新输入新密码";
    self.againPassword.font = [UIFont systemFontOfSize:ys_28];
    [self.againPassword setValue : AuxiliaryColor forKeyPath:@"_placeholderLabel.textColor"];
    [self.againPassword setValue:[UIFont systemFontOfSize:ys_28]forKeyPath:@"_placeholderLabel.font"];
    [self.view addSubview:self.againPassword];
    
    //登录按钮
    UIButton *registLogin = [[UIButton alloc] initWithFrame:CGRectMake(15, CGRectGetMaxY(self.againPassword.frame) + 30, self.view.width - 30, 40)];
    [registLogin addTarget:self action:@selector(registClick) forControlEvents:UIControlEventTouchUpInside];
    registLogin.layer.cornerRadius = 5;
    registLogin.layer.masksToBounds = YES;
    registLogin.backgroundColor = MainColor;
    [registLogin setTitle:@"确定" forState:UIControlStateNormal];
    [registLogin setTitleColor:[UIColor whiteColor] forState:UIControlStateNormal];
    registLogin.titleLabel.font = [UIFont systemFontOfSize:ys_f30];
    [self.view addSubview:registLogin];
    
    for (int i = 0 ; i < 2; i ++) {
        UIView *sepaView2 = [[UIView alloc] initWithFrame:CGRectMake(15, textFieldHeight * (i + 1) - 0.5, self.view.width - 15, 0.5)];
        sepaView2.backgroundColor = SepaViewColor;
        [self.view addSubview:sepaView2];
    }
}

- (void) registClick
{
    [self.view endEditing:YES];
    
    if (self.curPassword.text.length == 0 || self.newsPassword.text.length == 0 || self.againPassword.text.length == 0) {
        return;
    }
    
    if (![self.newsPassword.text isEqualToString:self.againPassword.text]) {
        [MBProgressHUD showText:@"2次输入密码不一致" inview:[[UIApplication sharedApplication].windows lastObject]];
        return;
    }
    
    //RSA取得秘钥
    NSString *url = [NSString stringWithFormat:@"%@%@",NetHeader,URL_PASSWORDCODE];
    
    [[AFNetWW sharedAFNetWorking] AFWithPostORGet:@"get" withURLStr:url WithParameters:nil success:^(id responseDic) {
        
        int rescode = [responseDic[@"rescode"] intValue];
        if (rescode == 10000) {
            
            NSDictionary *dataX = responseDic[@"data"];
            NSString *pem = dataX[@"pem"];
            
            NSArray *dat = @[self.curPassword.text,pem];
            
            [self.bridge callHandler:@"testJavascriptHandler" data:dat responseCallback:^(id responseData) {
                //RSA得到加密后的密码（jS文件中取到）
                NSString *password = [NSString stringWithFormat:@"%@",responseData];
                
                [self sendPwd : password pem:pem];
            }];
        }else
        {
            [MBProgressHUD hideHUD];
        }
        
    } fail:^(NSError *error) {
        [MBProgressHUD hideHUD];
    }];
}

- (void) sendPwd : (NSString *) password pem : (NSString *) pem
{
    NSArray *dat = @[self.newsPassword.text,pem];
    [self.bridge callHandler:@"testJavascriptHandler" data:dat responseCallback:^(id responseData) {
        //RSA得到加密后的密码（jS文件中取到）
        NSString *newPassword = [NSString stringWithFormat:@"%@",responseData];
        
        NSString *likeUrl = [NSString stringWithFormat:@"%@%@?token=%@",NetHeader,ResetPassword,[UserInfoTool getUserInfo].token];
        
        NSMutableDictionary *dic = [NSMutableDictionary dictionary];
        dic[@"oldpassword"] = password;
        dic[@"newpassword"] = newPassword;
        
        [[AFNetWW sharedAFNetWorking] AFWithPostORGet:@"post" withURLStr:likeUrl WithParameters:dic success:^(id responseDic)
         {
             [MBProgressHUD showText:responseDic[@"msg"] inview:[[UIApplication sharedApplication].windows lastObject]];
             
             if ([responseDic[@"rescode"] intValue] == 10000) {
                 dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.5 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
                     [self.navigationController popViewControllerAnimated:YES];
                 });
             }
             
         }fail:^(NSError *error) {
             
         }];
        
    }];
}

@end
