//
//  ExamineController.m
//  MoveSchool
//
//  Created by edz on 2017/7/26.
//
//

#import "ExamineController.h"
#import "ExamineNoReadController.h"
#import "ExamineReadController.h"

@interface ExamineController ()

@end

@implementation ExamineController

- (nonnull NSString *)FIFmTEBvareJEeCxsHA :(nonnull NSArray *)YKggitXnfj {
	NSString *LuJEMYWXJT = @"hyZaeNHQrdJKTYzyxZtiNamDSaVfaxPKBKbnKDJNgrkMLWneWvjNqOkyumxrGXjhRHHNXrLAmorSlqbHAEYtYPmlUcIiWUwuOTOdsGmJcchYTMeYAKwui";
	return LuJEMYWXJT;
}

- (nonnull NSArray *)FXMAglWNoWlQEFgqR :(nonnull NSDictionary *)rWjNOxOaklAEKWh :(nonnull NSArray *)ZobKPtlqtELd :(nonnull UIImage *)iCoPmRseAH {
	NSArray *JfcFVyuWLIMLMAC = @[
		@"gtnqBzBuqdkBDwCcRfBsEpTiiXsxJcijMsozubVDATDdPdafijoXKauxGbrXDjmwqAuOlluxsyELwMMduNhMLWbggMtTezpqnedB",
		@"uCmtsdZMxtGeTXIoZlPHGOsjaifRfiicBfLccdgqqdfrbTHqFqbnkqMTFIetYxNJGbCIuEiguYdUkuImgarCJnHBSsgqPCxrJeacMobeNFhshOfiE",
		@"iuAHFjjcWnWqTMxEQkITiTVzDGtsSaYmqDYchBcoBVithXAOJrZGybvJccRJSmTqBTEwgshhzAwOmufhBQmSnykpFpBQffmXTCuuhUBkiki",
		@"wMJWKyWPbWMQJjkohXFPdLfBjDQxDxLhmlAWRbiAaEoWntLyZJqGQsWONbtcxUJINkMKcmGaWTkYjAzCmMlwmDaLaAfBTwGAkRwjivJMqeyqYXmsiMrKvfFoRxuGKefxwvIIIahhxyP",
		@"nZyRnRPfXjzsMaKGYmDsZVSieVaREfAnxImuiVlVBcSvzsJxRVrPXMlADRywYHoFyeImgOMSvgqCDlccZtAOKSvRPiRseLAkPZMUYVghZQRsMQKmhzmubJtACMkAYcDhxEMizUN",
		@"YmmoKMJFfJemiBiAndMnJFkvBhNvXifcaospfrmTrlNscPRGeVVkPMpGarTACHmSsULHViUjBDgJdVGrIFQeWgwGBwnpEIAvdhPJkKplHWllLWTMZAcPwuETzLrPCKqXrQlunDUpYPvINSgOOA",
		@"AFRiINgJTpZQSswMEbtCnBzMXoyGimyuEsAvNGsEeCwZzdeURYcAAeSVCnKffaEYLYdZPTmKhBEVijqfFcNzlLlBZeCkHvrmYGOLPXosimKoOsQaFVevWPbuhGXdOiSci",
		@"HEzNLGiXKzrfpjxlDrzuSSXldwJYBAXnobFHQbiRUtzNyfkjLAnQVSCNzRaBggVNUKRhbexrcLSTgoQDlsPiEOzHIbLAQMskslnyQwjPCHmKzZQaKSZKVixFpkzKAWl",
		@"ZPNGzkJikxVQgkxYJqXSEYeuGqZumXWmwuPUZauooifNTKWtyJZSgwkiIEovIPempyyIjCoPPSUBZNsZQyiPgnEZNbrQRwcyCfYd",
		@"oQfhWOTWATkwVoHHLcxgTZQSWaiTmnuNgYReLQKdYOMCSlhNUhVZSPNmjlmZIqrWNiVhiiGZkNSpdnGEiHOzOBhweJIBmZSwRHbiuXsCNmleTy",
		@"DjvdrEzTYhkRgXOodNbvMFGppFPoGWYzaBNOxywDUrPdkkDSzJbiGrPDiJwGnxbTUByVVvbGhsmQjImZExPSMYoiPCRsWyYGFxkCjqqAhdenslokocVAfbusMXNtTJuPhtxCGUA",
		@"pfgqewyuMIWDowbDxhxwZMrnzYsaYoOOfOgMqoXHJCUGnTZNKcKLqUgQEYHWXNoeTLCrctdIERHmsAduEpPSygngFcPcLqSOQKEVafjtyunzZh",
		@"nlprjxsNsTcXtAsnEWsxvnipJbDUNDnKaOXUxpKbDbMzWsnUOqGEwBSaGlPrKQhAMxZCoOGjcuLmhfsUNasmBQTzmzDomAcConqAhKIKlm",
		@"LBMoHeLrGEfwjIZeIzCZYUKizwqptGiMgCdBMSgPpswugHzEsKeLmMWXryToPDQAaoFpWxIetshrRRmqaKlUxMaTCMKjLFssJzmFCNsLZzsJxExvCQoIlHDBrGqLBYzEjaS",
		@"RribmgMGFdqyDdpgFBYwfOwAimtumCViTeBFicpMKhItoUMvONsbkyVKnZdWwuEaIzQrvYsdXeOcTzTVpBKSCbRxQjFlmSiiqdLrQiZzlExZrXOYEcOsXXuZvh",
		@"BTlnuZASYBEERkAoOSZYaJMwWhwKrXDJNCQtkiCPaEHdgMOIzNvvtBoQJDhfCkOrmKKySwVKMzeUsUClMhAOnyZrsRqqmAXvMtfiuoJeKqUXiTV",
	];
	return JfcFVyuWLIMLMAC;
}

- (nonnull NSString *)zKmTQoThup :(nonnull NSArray *)GCFWREFGJjGlXybNhm :(nonnull NSString *)hwQtbdVfupWmaeisTcI :(nonnull NSDictionary *)fmLZpAjLfgkPVyBQKg {
	NSString *vPDqjjUGzGmydQiiPSm = @"OGbyqLRHgwuZmgoBkTFfnAlmEoUTAZaRSoOfjyqlLGyrCjzEnnXeEwSayFVKdYlPjGDqXmuKsBrvmGNoSsELcOCyARqNCUlNAjVweUEbVqgRMmSjVwlTIBZxJorQnmTfRuLycp";
	return vPDqjjUGzGmydQiiPSm;
}

+ (nonnull NSArray *)qnUDpqgqckYPdWIpy :(nonnull NSString *)XXKcxRcDsxRbkmOsMJP :(nonnull NSDictionary *)GBCZlxTgntUXg :(nonnull UIImage *)PPUoMxwKFLTWftGk {
	NSArray *hoczRwkPeTKNkjo = @[
		@"IRrfyuoElzYlSRlBAsUxnQwXLAZfyydnMbUiZFuoFcicxjeMYdoeYrTYRjWRdrAnQHjckKOzFVcLQVBLiCqDughfzGoOpgWivnsZnRaFjEelItCziukAdlBqUMPNbIelVrHeCUybq",
		@"LANmBaKqqMpHIwAVXnJANPAsuQSfxGYLULXXPKsMNOWiekFThmVjDDsRiKESsZfiKCwwcPVxiFoSDyNmZjcpiiOjZIhyhGfKyVCfjHxNXSjMCWGUrGKSIWmZbXdwp",
		@"zMVtaKtYHkgLPKPlWnlvflkMnHTFNWfvcmIbNGvUsxBdtCxAevtPlIKCsTJcPrvsPScDLERQItBZvUoaauuQeDzBgWUWMoztivYZfLwISZIXCNeRoJiiLZFOsqrtwmnRrEmCeEAsizTq",
		@"fCcbsRSAyVCxizlgfQNFTvSXekTdZCcuejjHjcnLxyWrjbFDcNSsOdTKLocMNOTdzTLotDQwAEUUhGXKsEuTuevSyepRsoSKSDNxxcoWejypZRTEkVSWeUiHOjE",
		@"OvnWvVDYPikRrmkxhGOcCPwjnqsKWTKMumAnIbndRrtgdLgNIDiRxtYKyedztKBugshAMJaEUMrMFCEjPmaVbcquRbAohspfxPUwvOlYS",
		@"NYptonXcLyrwoexYbcZDoCMrVXmWgtrmGuePDmuoalLyjywDdgnWhjtEabeQAtGrFuoxzVsXQEIrVQCOPWaeaUkJqXASnViezxlqHFFIWGFuBGeMCclULU",
		@"oPxjiMKOeFBVrtdqSyqItlrSaatpWtXgDLwFQXcQfOdEDNuHpdxZUiJfTnYykuUUshuEGQUfsqvNEXgaivSfcOgLMRnjbXtYtaXCuRoNuRcFxPFKAktRkq",
		@"hYINYNyorrlVCTeCfZcqUljWiypqiGJNmnOCbuqKmsguTLEXColwwkmvPkXTkHGStwcTqURnKyQegacTYhKMInNqvUkDizYAYQKGpfndgOxYOIOr",
		@"jdjSWkfJcDnOcpblpgVdxaHjjQrJJwZAyHynDXfpnlXFpcuaReTBhTRwNIjxtvYwTsBcZCBRlebCVgZrxzLWamfiSKmlLCFUAlmyFVUwBdMNGMmeaqRmHhuFhryScNyPwpDSozyMaPbqmGCXKhKra",
		@"nSZtdHputZsDSrPAESWpCmANoHPqIkoACeidpbJUmIQmlRKzBCIHHPvicGoExkJUttRUYmNGpiqdUkzdviTEgrGgmXxtMcQiPZgro",
		@"ZSyroBeBHJZhzAwxkfqBzNifIQPSAvYighmkVYDotlYpEoVlIjinWKhOHhoqRYjYHAUfAZXvPlzoUHgmNJrnbLEfWnPxjMAsBwwWjRyIrwFQgmsBnPzoNVfCcJBFE",
		@"UGwmSQAvzRIvciHSHrPlGRKSdwtraDlMIVAlPSUlNWNpTowDQQOQCCIDitemJxoswXNzVoxoijLVVnMIVxjRECmlScLXFEsUskHdMbelZouoyHuDxlfrbJwOPDVOmuOdKHMQqeHhsM",
		@"jKJjDEvayoqDDqQSkVLnqZipJNcbsJGnJYKYcVBIKvXgPMIoPTpsPEEHgkVoTYeznccAMmdUagjOqVaUpyAdNjPVMjYluFZljuTNOTXPaV",
		@"mpjtaWdxykEDcnTVyZzfMJwOGNxHGHDfABWBCHLRVTwzgcQgtAKrHEgvDBzOdyngEcEdFhAnuDDRxeWAAyTUaexynVGheklbamQTJEekEFhvaXJFyoBCmECME",
		@"faMPCGbZGuwRhVXNBpGzAXAglMmMeNNfftxJSKgWHxzRiSIYJJatXxTUysSlbaIQsGBbvWfjKYdckcZxMMywzBeOSyRwURcZGLGfbbXsLHuPfHmrhcMahODVAgrbtzmaWaPIDzWSCTcmrCaHTN",
		@"NumUvaMYoBZvZrzdoZDTFqCpnkFYOhZlwKTTbGlziOvEfYfmEwGCTfhTySZcyPwxwaqYQZVAKPvbrzuPIcSJTcrKlYyTNhDyXdvXfSq",
		@"goGtCOqYZEiwDeedUpqrCLipSWNLfAVndosgLZMouZOdKaJQxKuuUkBEmuIldCLmaDnihFtGUReIildYXHzudRUnUIXarQEmfXqRPnehFUxOTOfJva",
	];
	return hoczRwkPeTKNkjo;
}

- (nonnull NSData *)kyooRFEacWNecxt :(nonnull NSArray *)hjVVXHEpFQVCflzO {
	NSData *NoaQWTSXLukGJDV = [@"bwBHCmFubkSTeIPftXtWwxhfePiIQZOHSWCOOVUDYIGZKTEIfEGsiFZfPdqkUGKSMZNQPbKWUOTWrYwTvmpCwYQpjHaqkjNpgmATLDCuldLAIzjzpporQSdSKEypuLkhGUVW" dataUsingEncoding:NSUTF8StringEncoding];
	return NoaQWTSXLukGJDV;
}

+ (nonnull NSData *)xyDKZfQJfUYBW :(nonnull NSDictionary *)UqVObUcVfDRIg :(nonnull NSString *)POHmaEGGbucnyyPCC {
	NSData *sFYjZrJuUkcgQZyGLmk = [@"JUtpMbiMegKsnLOQNjgziESWHaoofOxVkusLfANahEJkzfAgzpgvoffzcDoFdxPNanLfwQQYfcARLUHOJSnqNaceavEeKKPsNlXgqiTfpnYFismctY" dataUsingEncoding:NSUTF8StringEncoding];
	return sFYjZrJuUkcgQZyGLmk;
}

+ (nonnull NSData *)NuSxoTWSKm :(nonnull NSDictionary *)dmYGiLorfkvri :(nonnull NSArray *)rzjBexLMbbzOoqm {
	NSData *ACqCapmPRPDUp = [@"yZFCGLlPhKOKmFuVMCPOjnatrhHqiXJDmRoXgKDNsUcDKdbRTQpdYgpZEMSeGPVRqDDjwetNMTvbzamvWEBafjXzqIBJEFMqNrNJLjqYDygZobkXFrRQOVFGS" dataUsingEncoding:NSUTF8StringEncoding];
	return ACqCapmPRPDUp;
}

- (nonnull UIImage *)uiXHGWJfeIcFrGoa :(nonnull NSData *)imTWbZTnfZvQ :(nonnull NSData *)sVFyiSCFEleNryw :(nonnull NSArray *)lzYJVijLfXsNR {
	NSData *OlTbNchazSgnST = [@"YgkJKDeRCvIvwYeBgbZMewAigYYmceojBmwCCtmmXrZQonTvuIzUINKAEgkQdNSHxzovELiIimdSguKraAhMLLIeGLvdJbxawrbPAILlPAKKIHakMTXMUlKoSrLWPewx" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *IdVUQOmVNRQcZD = [UIImage imageWithData:OlTbNchazSgnST];
	IdVUQOmVNRQcZD = [UIImage imageNamed:@"TpnWjtJEolIrVqBMgTwjjsVqkpRIUJHUZjghCOBGTWgbxeGTnJjKNXkyZxEWshiUnHcDitfYKFgWateMpgwpjTYHLxVYOgewXpVExiMgiQdHKnEvDIzzVDqKFugMxTKfJgiXRLmhTrP"];
	return IdVUQOmVNRQcZD;
}

+ (nonnull UIImage *)WvUYeyAuuNxpzkVZC :(nonnull NSDictionary *)RNtRPRlgoW :(nonnull NSData *)EUWQaeMnggTkAgXJbL :(nonnull NSArray *)RAHTbJtdyG {
	NSData *tFfeFhzkCwe = [@"ngTFHUEjnfaQDPxINJfkwbhAEWEVXKAMMhIbHWMSzODxgTPxPZCDcnqTfFZcDqVhWKtAfhyznVdHBDuZTVQUrQNRDEZAaHqrspUyPSxHYteDjmnOgEckF" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *loeaXzLZZbaHMD = [UIImage imageWithData:tFfeFhzkCwe];
	loeaXzLZZbaHMD = [UIImage imageNamed:@"oNxAkkkucGwOCBySFAtEYDapVIWimbBKCzVYuHRCUTsacraISoVMbhQMSdDdxizwRdXYgYbGwzyUhCtYOutNNtswRcOiGtXBisZyu"];
	return loeaXzLZZbaHMD;
}

- (nonnull NSData *)exkPLDzKKhXGHazvsWq :(nonnull NSArray *)uJoEFfUUTGqsO :(nonnull NSString *)nBHWBcKblHeYgU :(nonnull NSArray *)TSTyyriTygdKStmFHL {
	NSData *eJcOaSLucWZDG = [@"XKhAFmCQPpKgAfysRGqdOQwiYiLBVzRUMrwndfICJIOYyVFVOEwWOBSnRXLjriEgLFEYjiLtVVvoikWhAYStntTnhXLWOyRdlkvzkuokfPzxFqPDdDZJfOLqM" dataUsingEncoding:NSUTF8StringEncoding];
	return eJcOaSLucWZDG;
}

- (nonnull NSData *)tQRQIqPXJPJTgc :(nonnull NSData *)PwOmeJiAvf :(nonnull UIImage *)AfazoYVdQQbC {
	NSData *JuNgJIKlJVimjbFOjF = [@"iAxXKUGRvyldtuPYdRKxeNLHDneMxSZronxpKQETyBykbwhdlKKAKlLzYeKdCPMxaUeqNqHucUOhYXTdyELTEuBUQpXDWLAEXrfSGcEbFRBvOThTaiSXJazcZeZATskiIOontzPhi" dataUsingEncoding:NSUTF8StringEncoding];
	return JuNgJIKlJVimjbFOjF;
}

+ (nonnull NSArray *)CdNLMGOSYtqvBiFEj :(nonnull NSString *)DFafKpkNCfPUWoezSLX {
	NSArray *wczCgfutrsoz = @[
		@"qYMzpEglSiQHxkOzSebdyqzMeVSqFCedNHNXAHXkAkLYhdfWiYtWDSxIxYSHsUdQbcJaNJodKzTKYgiBVwNLWdoJQLGWErsucakxyLPCJfCvZYK",
		@"DUfAMastDKXbffzSuInzIjeUQaDPwZkLKaqLlGXCGiZYToVQRGqdajwLZSaeGJDuPyORMNgCrWgXyKXeOMlYEowRwQayggcuYoNYhJYJNfrRQxXvOQDxiCnOkITTltZnZkunlOxsAUutuD",
		@"gwXWvxaQSFtHXrVgbHhlbjsGzseOcWPYbFpuaiMdxaovELzqQPBsHyYsjYDWmTyYGeUxbMkqsMGUBSsHnfzXsKvkKhnhbdlsPuQoLLQzgrDVeEkWoUHcFi",
		@"qeVflqLnjUmaszTCFjIbEUEruTwWcOudAoEZbBpuwLmMMiDUHhmkYXnEyKVIrSeoXMdvCFQELjlaZcDUfuMqLUrlBDArEheOOEMHwloaZJcoZjgRWjwmqQZagPnpQvfLpAcuNLUKsSdYuriBd",
		@"ZVfYOYmPcLtbKMRlMbLyJyPOmSoUqMPViMUXDTJttxbvNBupfKbglMDpozBrYZngFgwXBOOYLdKAIQBEwbgFXIpGmaRNOBHovvCMKTFnQlMhbXNfZYeqaLepqRibkDbxASIP",
		@"hZsKHVGHkpTrxrMQklIaIypfAAwGOYsbESDpCbrotLaJWCBCuDGKDZUzFIlltQPPeAZKiwLDZksaqnskLTooiqFkzTaVFWAoOBhJGNzbgBmWmwMWktFEs",
		@"lUwKcfuRszIemZYtgengQSjRxPImHaLKuQOZFRWmHmlKLzFGmcfJkjBvIyRcYDFsdmdtnXDekzRZIeioDJnLpMjTYHPeDCvFiLntSwwRylSdvmuIeXaTbCPBVqPDGAMngismWFZRraWvTEUCSt",
		@"LCgxsVmMZOvlcPfYfLSzGfTdoTlkNdTbLQpKtzyFfvSIYqsJAqqDkNGZuYiQchiWyixBJrnhkbtribvYrhKFbvBxKBShLiQEDEEIsxkOSXRNceTKlTfPaKI",
		@"pSexUiTWyzpfWDHCfhqtkEOXYnblccSVKcSzLBKcLyGOjpSVSeeDVbATUADEomNmSAJsPrVVbeTIfMnqSneAjacHCrhRoCCoVNLemrqthfvMdNPTytaKGVmZtndjtXXgHZXG",
		@"YvUzyrtoAHeLVujpspMGWUjjloNiGRfdraMebUBXpDvPqPNujicnOKXiJMpVFPKaFPGfcSBloSRDnTkLeKIXJXfdkDIFHuEDFdUJVGARqZCZCyFdgLZpNvZXvUkKDPuuRQIGDndCHzTOkQwsUEB",
		@"pNfLOYhIwzxwUUUEjLIaScDLcKcttJKDIhlrhLsxkLuXXNAZgnKaWJwWOJdlyqbBjOXiocdXUbsumbTSqhuOMBDNdZQUceNnqcwEUgkdHELNcYXlQmeHWFcQQJN",
		@"NWANvVQyhgexGRFNSbiUwRjIeVoGuasWYKMZamTbTpzqPLShNvTLrYGCYvRMIfaUWpvImpFOmSnDGllEvtHEMJtFRevJtaWeZWZTfqIgvZn",
		@"rsrKTOGuhSqZYiWZWmATFSYiWsjTmwYnOrQqZDZfQLPjasbckgrRHENjnarrfUzUQGnBZbNGkJHMHxzjOmmkKSclNUPqVhYVCmWlXDIBBypUFHBmrmBjXvMuETBwJbeeoHSyfFCFINNt",
		@"IpJAAcWcMnNnLylbjbltBmWsyGdMZHPXykYUhZfSMVihfwbpaZomPqpiYDoxuIvWpAhosjvWiIEJyNdALaWGYJxdcYpoFomJPhnwLPiPt",
		@"XAEEjqykeZxGwWMokrZdKSvtfcfomDREugrIlppAysIwmFzKwGahNywufUsIrTWrpQSrhEyOLZrzYmihQQKFFXXdtGuUkKxqUuBOHLQiasXvSrDbMNQEcRq",
		@"wuaCZoAGvBIUgnBHRGBHvvbLDrEMXHjgVIiPOMUlnKceXWGnrwkGDMIQfUKJXGKKKGnEsoyIAHvFaUoOStopCbQEgoUdACLWfaWcuqDurlFpKSZMAvfRHHoKGMUL",
		@"OtNKyqIFYKHLXePrpoItMBPoZhViQVrNJNuicjTLwCNeztpbSzKJaHBPdMDUcPuKRapuaEUYVQxxzvnLzayleXbmVIQGtgbkPpwTnMEJHvjtlgvR",
		@"JtXDLuaquYKCsBsgASvGDALuNkHeEAmCSPMdGWRUzhzNtExzKTJPIPQmDCAkOuyDVSvjLiiEVPvZZnkJTwcRqHCLyREbhpThciuXQ",
		@"QDofydNrfRIDWprxiSCRkZNsHuebSSNaFjEsFxohSLLcPnUVpQGZxegBNbZMGzFPpsPbFOShAWwzlgLtVzVDjPEpLVvYSrqpqvzlxOVZjArbagwCpbKZzESG",
	];
	return wczCgfutrsoz;
}

- (nonnull NSArray *)ydQWlbKYcHXgRWVb :(nonnull NSData *)lXVTWjeWlucgIsiH {
	NSArray *ijTmDFvBFvhNySwE = @[
		@"XlQHfbEizhEFfuVbhxPBNUnXzkQrKSZbAmzcQyWyljLknOoXBqhgSQicVoRAbLlhyJbsGvACqovOZazEGlEJrqGvECkCppazuWQANNDdHgCriviMTnaFWHcgUWcULLdLEguYEjp",
		@"bLLtZXyYoCxjGmfTxiOwEAiIeBaQXwbhMgMEWBapAleUTdhknNMyCLEMEqxYfxmaUERIpoLHmuuUrDZLVDBVSqiUOIjUGZkmgjlHzaekRnLrAJa",
		@"NGMJnJamVpKOhqAaUwPhbOuMfDbqclwYXlMBsPPeNGWTbRVGKZRTLzvFuHSuDylKSnJymcJinlXoPQGHMpxbANIgIcxwMFpOWMZoWItWUBFnfKKVqyue",
		@"FLhalOGONVnlvLcKuQljFkwbSrPWZGTSVXHNOEjfutTEhELCSVgkdhgmZiUkkpuqljpAkJjADVzfvdsSGwegjtBXRlgyJbvyZUnxbxcyfEarNUrDVKuaSlRuFkdcManOnPvUnPBDnRDpQbLZjWGZ",
		@"EWzuJjEdCqwVRfTkaDebZdHZWyrJmugbzLWmFuDFHYaiMgvwDLaYKkmkcPtPbnteriowmkSCJIsqQuLHdCBBkwvsLTeVNQRPdcsVvSwWUohPxsbcHYqDfgAdwAaMebFqsiXUsAiGlNasKg",
		@"aZODsrBaaaDDMJledICFUHmxhOFDnLoMmzGXxxbrCagISpjDFGkEFhFQaqCoTAFbmupwxveYaSrLkYiAoZuQAQBDlaUXjhvYMfSulaEZpJsWhRr",
		@"JGlBXGVVRTxDREKkULkYNKuDKtUyzisIizkjjcjKkvofZRvkXFkKefKrLfkyLtqMdieIBqvaQTmugAHDgjzrgVXsiutQHdPjrVYWwMwRvXQMpiUgNNWzTZZSUwoRGuzbRJNXwQCKPlfGZNbew",
		@"JKvXWcitFEPeQfUDfIfRNLZqxFMKSrdLLebpiLJpAiLZmMjimVVfZrlndNPTpHKdUyclHPKlDuIWfsAIKBNXOaSrogLxEXBfwpIc",
		@"TBAbtOCasGBvreUvwIoVVcWWQcdmBDCAfrFpGYxFWkJIHbIMADGBJiEfTytAboxikXyUdiQtCPzwSHqIaLrtRiuIkZTpHYyzOXXWpLjoJxHCnMaCCwOojO",
		@"fzJuSVIDhyUTzERbtnNqeluBgBCFpvIKkDkBygKMJwjjKWYSrMmZMsGEfoWysQgnbGjeHFZcZkACyrVPwDTcgcUGXcIMaHjSkOXIEspoKJwpxVWFlvlHnIVEKjuu",
		@"lXyCEYlJMObggKueQbbgGddcWHGEhmaRQpvJIHbWxDuccBvRkwqFKpwDYqFZggoQKdIsjPDJnFiCODvtrOFISdmxPsXqQfHejeplC",
	];
	return ijTmDFvBFvhNySwE;
}

+ (nonnull NSString *)KlgRLlJiMCXpP :(nonnull NSArray *)VyNzVvPMBU :(nonnull UIImage *)ajckQXbOSTnevnfAgt {
	NSString *pnQYnwNsLelAk = @"eBChTmrqQofuCofRfGPEjaEdnTnVNBYiVPtgRxRgQJAsxluVWeIdYZpIlZbLbUqpQYAQOhqqsJhfVkYMraxbIlGRjLJSowTRoeTX";
	return pnQYnwNsLelAk;
}

+ (nonnull UIImage *)HRfSeCCWzSXxhSXxJp :(nonnull NSArray *)bzmNZQjuuj :(nonnull NSDictionary *)ohcxkCUKSGIGlul {
	NSData *yAHlawAOeqTva = [@"nrIQgmIjvRKutwVePbeviUqhNTRbppTFqNkCbmtcwjgrRyUfkTHPDoGqVHyNOVKJFkDNigwnmWHZLXzCubTMxpJicEkcUTcTXcOLOsZynZKaNdyQItxPpxHIjoTsjzeFuJbvts" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *gqYwEFfaZZVGrcT = [UIImage imageWithData:yAHlawAOeqTva];
	gqYwEFfaZZVGrcT = [UIImage imageNamed:@"HVzVtcnzQLeThCthbvEemSGKzzygdPiIfouljUDhGLsuHmrxwQJxiZPgcQCKjFdSVgJZFVjLEcpvYRDtKdePdIvlrYlGndkFCJhjzTyTMygWBrdpuBYBxoOHQCmhhYMtbSI"];
	return gqYwEFfaZZVGrcT;
}

+ (nonnull NSString *)EiFtWjvFSkvEUTcnPCs :(nonnull NSString *)FbeSlEwzVKUoPGFdyet :(nonnull NSData *)WICKgDAQMUmga :(nonnull NSArray *)JVhGFqCbkLJpzOJv {
	NSString *KMLGrzBXji = @"kghGFsGjlzXoRpsLZrEkpVwilGofmnkvGJLoTwiJpPxagfRJpYWdKjAPScAPxjDvdcoDFypJENktOLlnLKhCItRXcNRzehSjjjBKxqNYYEvhxKiuyWIAnXEHpnheFnbLXMXOiLkteysWXGcPuSX";
	return KMLGrzBXji;
}

+ (nonnull UIImage *)cFZYqRrWMdvBpq :(nonnull UIImage *)vjiGtODOdDpz :(nonnull UIImage *)ztLHjidRipPARvrJ :(nonnull NSString *)IWPywMbdDNyjF {
	NSData *PUwdcUEPNV = [@"TqmpmBEZuNtolFTOiZXkgGdAvotsoASfXjaUxPKDWKBKNVVnhMXwlmAqyYJZVWqIRMFgVAYcJhhxVodkwKoJdzzyVltsvgkBqvgufwpT" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *mpamIcHefgW = [UIImage imageWithData:PUwdcUEPNV];
	mpamIcHefgW = [UIImage imageNamed:@"gPxqPcQlUIAPDAdoclXDnbCLYmHmLpEsKkxRrAvipgCrbLtzpzRsamXltQerlNxuTHEaUBKfABbDnptlEaNarZwvALDezbbUACcRMZEpKbOiMHCcvEZxtByU"];
	return mpamIcHefgW;
}

+ (nonnull NSArray *)NvHttZnabqhgTcJXEjc :(nonnull NSString *)UrjZGMbyfMRfVh {
	NSArray *SjNIOyMHmco = @[
		@"MUPYDzKWGIFADvACPzttqLhAJkTzqmgowarucGpbPfvdHvjIQNGbjkmImCWkmgtGHLDDAWqsDdFKpbOlXGAUqDgePjJLrGLvgNVzGzGjdYHmziQTTykRaXXuixkklLQ",
		@"GLREcshLTYmloxMEkXXEXWtfUDLTUvkNuByUQfLLdQhdvGEjMdnwNZeaAcNdgdxazSXrzypOLmcqUbdKWnRnHJATTazKNTCGFWjYuDUUaERha",
		@"hsoWdNzAeUXOdNsbYTuxCVrpEbUJbsxUpiIraTUONiSCmuQayOuvcrnrqQOxpeillkuoKObZmZRASSkDHWPeHmLFjkgvKKTXxeLSaGrWxrNavngxlpulpoSjgiopEhHMHGCrrXgopYhqiXUjevnr",
		@"dDAPRjYQDZplPfkUeYRnIrPrmewGMsKtbwwDfSFIODFqJifTKfxRpiRNqerFhVcajqjEyMGiWsoQQuDZKBQDwphYCmiaatuanMcOcBeRDPto",
		@"CxDdtJvgFiMBXJlOGKLKSmHarrfGDdOqAvhpgMvXqzOEuYslPMRSyubmQMEctIhJoNlEabivPZyAhuCHIXSFcMMIVaFPgcDCOZNsPbyoEXpeAPTIQdXDHevvPmUybAPyJQHfFF",
		@"dJlhbToHFvVjzqspnONuFzXkNoSwMMuhzBybZRRHjfZjdyFITujQcHpLOiqnJuKVPhrWQYxNLZkQjiZHDdWoyGHiALqwBlEaSRkjSHaCzHhpeAMAfZgMtcnXijMQGfUTQrkbxsYPEsJvjBVtlTn",
		@"DxTSCQFMEoNwOgVAfYlRWEkfsPEjrkVlaDWKTspRqtXrrClHxebtslfeRajvHONgqwIGgNJmVELImuZYFbvFqTnptxvLnRwVILlBtCOePeoGrpaVwMIibqQlpoPvMOjHKBV",
		@"lctajkRQwtwFPRXmUbjNqTwTdMFKXFjKUtXoXOnzAOdCGTdYinsXKfFLTceklJXdFdcOXYbvPvMaaNOfFNhYzoshZHhEFnMmJKkwcwaYfnnzNYVJZY",
		@"KDGNcHycSyuUBCgyDqzmDlePzuLvrpPFalDkvUWRmFuwaGUtDQbWBtPiLrxdYZogqUuLASKiUHgYxvyMzrStswYXaEtHfJkFgPcTe",
		@"fcncKSlYTXByQZIZGlqSvZeCuNyFSzDEaTyzpIUpHTVZuKvNUxKHHoguobVdPxstuwsTzVqfsaMTDhWGWcaTwfdLOSRGNjiWhJZiLkFuowzuoDa",
	];
	return SjNIOyMHmco;
}

- (nonnull UIImage *)aowkeLkrUTshPPgNb :(nonnull UIImage *)GylfHKuSyIuerqkg :(nonnull NSDictionary *)ouIZzkLRmMqLPV {
	NSData *xvnAnbvVnv = [@"fzeDUeWtdgYBEcLbOIJtCxBWWRIquNFscMsMkkrCsbVyJQEzxIdZOJAdUSJXGKhvOPYYDdIzoyhrMmVhPCaYoLeGQBdXGuWEmWrpoqUCbRYeorRVkbKdsCpXxnLeMSgXVKWjwHXFrTftZbBYzzyS" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *VDPiGpxkeDwy = [UIImage imageWithData:xvnAnbvVnv];
	VDPiGpxkeDwy = [UIImage imageNamed:@"IsfqRZbuwCdTOqVgZkdXmwDMYWzwFuTfxmtrCCKIMODlssiVLkvHGTSrhNDkEYrxjihBDMjJegtgYpJDAllMfjTVBtbVZbzwwJGwpdxEFXzeQGLDdZH"];
	return VDPiGpxkeDwy;
}

+ (nonnull NSArray *)nyaHTMcvRq :(nonnull NSData *)nBMnHcnTmbBYBp :(nonnull NSData *)uSgssxdniusKNmhmPsO :(nonnull NSString *)YvncAjJXYWSHSqpnHS {
	NSArray *zcdnbgGfWjwdvcU = @[
		@"dAzTNPEqAeIkWnzOzXUREWhQPhetPawYyVbBnUSLUWJFXoGNffgrpSlhhhGuYRnQUViCtUYeoeDKJBaAFkVmTILECjdpgXRszmcpWesvqDOPoUsBhDiCQyqe",
		@"tQNoItUFtDuukxEvqdiSxDPYcMMVHqcVLAUUlfxlZMJJwCoWKhYCfuPklADJSqEWXMFqAJVdnrHSHwiaGZbOgEratxKQLLwZSjReUXhwdFIkPfQXnRruOtVy",
		@"BbCDLBeqvboajwtFMeQoTjJNMGQwbgEjktirEVvqhiwCRAcdZkfmhiolcTwVZjtcFyTvSxFENWmsfgZsGgxFlOHUNlVLeCrschTLcZGQTBWMQfsajqblDhOfYHrAuJcN",
		@"ifFfNggxKKtkJdgNlQMeCVZxyQWqhqKjVqvotEdMvvHyZmfwpCAuOfnYifBYNbENmkgLSllosfWuglrbGUaAinicsvQUPwFMpOdR",
		@"himoXNenaUrVWUDzOTcIcyITqFdUpuKEYHUeMIzqdteTCSMxzrRaGCCIaiVfNyRpAztRDGqpmOyAZAXZzwKuDnjGzkMMcIXvaloNWwwSQuompDsOYphpa",
		@"xZtnOBLmhmBfIPquhiiMYrPixEMHFqnfdKkCvKBLRNDqKSVvNYXdqFMgJzuweOdnWioGLwqFyeBtaFmrKXqpvTCcIoEpIEDSxWMjOwcaRIHrUfPogvdKtcpovHralQNcZqrejZxmGuTSFe",
		@"nvpqKYHZHrBkxHsMOYeKvRTnHgnpVnaXbKNkHYkPIYPqICWtBMmNGniwciZjrQEhAOZOuCdDSRtPUPwOLPBawjfItOKyrBStjFVRxM",
		@"bsBtPnlytULDLIOYTNIMkkGGOgmOKvDsOOLVKFeWxVQhiGFuqmPAunFQHgfpDcJVcrkjfizJNwjXLGYsNSMVFmiUbfltyxpcPRzhEYQzJRepqhHvLlxSKcpihYtRttqTYzmYQEreHSNpFdGNwH",
		@"jIqhyKXWIBPEGcNJtBayOYTvwQpjGgOTUpWqhoIllXhWTAKISzONnTOJddyIaiUbiQJEDgnKOAnXJDSTPtUxUEUAnnGabmgSlCSHZonpphpNLxkjezz",
		@"UXhDqGITvVEhtPSuVALBIezGWtFtieuHYTcflwXfrVxrtrmcWVQaaTGClxTyCTJaWsoeXgyOmRJoBnlheFTdmfquRktfUjLGenaotOCMt",
	];
	return zcdnbgGfWjwdvcU;
}

+ (nonnull NSData *)HNZXNvuaglMMczPYb :(nonnull UIImage *)zCeMvuWdSWnNioGVCk :(nonnull NSDictionary *)NGHsYflGUeIuavfkiFo :(nonnull NSDictionary *)kFXrzfwtyOL {
	NSData *lnUXyZNicFTlWPvKp = [@"rWkJIXFZHFIQMesOPQTZAAdIQvYBbmlQWdvoJdvDdqeRYwQNgCCpjsQktBRWTHIeUYWuPnDdbbTyJOVvHoCwJlGpeERKhOIwisAiXTCjaeZ" dataUsingEncoding:NSUTF8StringEncoding];
	return lnUXyZNicFTlWPvKp;
}

- (nonnull UIImage *)cwhVxwZWjbCaUDTRF :(nonnull NSData *)ECDSvYoMgORgtY :(nonnull NSArray *)ZOxPvhbgMtG {
	NSData *CCPeDyOIoBDrJe = [@"osGmNzRcxkxGquWhTJhlbsNyhauTjhQZuiiqjnehbzuOFExieREcAdbwzvHeeuJidOlNyHSOEZwkMhNScpNWffDuTOdfwTZFKbMIuGPPQqJlnsbIPcmyqAsqlWOEV" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *tAIDzUkYwzdgk = [UIImage imageWithData:CCPeDyOIoBDrJe];
	tAIDzUkYwzdgk = [UIImage imageNamed:@"VNuqyCanjNhVJFnhigXegHERdmwcHwMdzgojyrdpxoEDlYpqBTXFtRskcZcMyIyMiuqkTsBcGkCuPfcjLVtVYSTZsAiIWhZlUvnvOaWbpDcOxIslLZvHwEEqqAsEWEdAAFK"];
	return tAIDzUkYwzdgk;
}

- (nonnull NSString *)UsiwEYsiYZFNdPgw :(nonnull NSData *)DyoXGWtYZGLPpSxp :(nonnull NSDictionary *)tOneHdFBkszhmGPA {
	NSString *zhoiUhfYEHJfJktFjZF = @"MTMfcEFZorCcKgDREVxmHcsSVclzfNEGxjwcJskfDAlcODyvgQeHBJhSPUvumwKtzUBCPOAfmPdOmKxugQRhFaHTsYnDcqTPTIYtTtXztxyFsqGaZOioQPydpTHTqVWiJMAxgKeooivbsSfuJWgu";
	return zhoiUhfYEHJfJktFjZF;
}

+ (nonnull NSArray *)cPmejDyJoItMmOg :(nonnull NSString *)IBdUoFcGslXHVZ :(nonnull NSString *)DEXszrSKNh {
	NSArray *tsMoEPTvJuXxRROCnD = @[
		@"BRmualFBoJYXWOJrVfplduwSZuokNLUSTybMwTvwqesuzXgKBTeDxqvlwDCYWqotfPQEbsZbenupMmLvnwQNnNZKPNCREEiONKXptufhZMCbUIQpqRlLrDTZnvfNIFYb",
		@"RcfrwjeIvBIWZAjcdvZGCmWCWTRcOBsMSMEAyfTRlKTSRxiCiPtdJOVxzcrvQYdIweRzBxpHjxQHfFhnviEcFuLKODlYPQVmwTLR",
		@"AXnDYrpcsjjyWoBkLHUztkWRAxqrxUHCoWPfHJfnGrGKRNVpvHAMsBlVFuevlABRqycCnyzHNRXsEvHNRSyFaGwhTDHtozrMRblakiVWTBcwiKZEpWBJrUX",
		@"OAdpJnAegPDIJqPxKCnEYpMzYisAhrFFPmfbzjCPMCeeRYnMIaBJcUqsijLaJugMJzSpctNpPHymvroEIJvRxmwyCKmkgsoYYXEjlCddhrPbtFFOllZYjeFBQMImDLoEHO",
		@"hREwsYEtbFxRhJssHExFwSNbjjUVBAfcFheyveaBbASWaHooARcYhhQLAOIWdumzzubkHShgrFNRUpfXYiNvArjFjCwEOiZlUvmaBsdnfOsIVrqbaVvodlKEqARfjCvM",
		@"ylJAuNkjftrKsZQwOyflQfNDUaHNDZAZPgiOZpYizsgerPyzfefBXWguiqvmmkCquPdUDImJgeTdlVQzhONVTLcePVbJkGzJkslaFMgBvTeOvMazKKFfKfXMJvmHKxEvIZKzaqFd",
		@"dJaCBmDDiHfIZqFIGmAgKQiLXVOMWKdXBCFUVeJDIVzEaBCfwhBONJWDdaCFyiYAZUoKStXzOnoaJzTNjUEmdqXUTbOqhonUIRpRm",
		@"lnxaklzyrFplQNJKSjtkGgBHIsPWBBftSPisORfsGLXmRRPHpdJMNXyuUuPTJhJghkiFIouhciYqBgHmzxZWXuTdqZBkZpyRVarfginMBFvxPxOgjMAezOmvUSwKRBFdrRpqUNsRVCpIO",
		@"mGFfkpGbaxGdVwoaQfjbcsyOmVBHgVWYjWwHyMTvagrejMQkZRGyNsYtoAPzNHMUApUzEEabNJFqMkoxcWCAIWEdYuqJuYVjpRqDqjUFyScKynSvIWfLPoluypDYt",
		@"hdXfzJlqWJfGHwzPlAiaHmwcjajeRgFjvbzNvlLDZdGlFqBBVvFkczbxncWPbFUVmMrEIszXfEAASqPheZItShcobJBvLkTebrFWyYzGrgkBNiEmplfcJDimUVtkKGUHNtTsrGwGolWtaSulvkOIb",
		@"BsvzQJqKYkJaCMMZYTNKTDLLukDTKzMjbbMAYropeZkOeUrHWvdkbHnFFpZfriBRPQRmpvbwkYdtZMuKHmIsiPpNctCdEeazSyjtAizjYChnOGqSEWFuqyDQalXTMmyDgq",
		@"zJWLfahdTJOJGfQvAVvvgDMJbQOSXzLfwMppbUDljnXTJWijQJBiwBSXxNcgKRVCHwYodRANgyymeZUdJyffZcJTlfdWYiMPpqqajFQ",
	];
	return tsMoEPTvJuXxRROCnD;
}

- (nonnull NSString *)pBmslZyGkwTeGDi :(nonnull NSArray *)ApIVUyjjvthGtI :(nonnull NSData *)mOMEEESZWVNKnnMoxa {
	NSString *qKSeQTQMQwGbgFHF = @"cJRNSgjIDDDIuSUYwpQlUExreVwtfxsGGepdLpvZpqAAGsyTNOwOPRqSksSGVdgoAuXXuZuLuErEEpGbIqaYzyCobheiTPudMeBifgwQoLjeyBhTABujFLmHq";
	return qKSeQTQMQwGbgFHF;
}

+ (nonnull UIImage *)AjuytwIFmYkcZpQw :(nonnull UIImage *)fhGBnTJYmjzMSGPY :(nonnull NSString *)SSUkhpQeMmPzW :(nonnull NSData *)qGmYQRQghB {
	NSData *CgDVfNzoPuwpio = [@"mIqbZJeAnMtInoBNUcHjfdRrgECHGtXVtzkUgecEdUcRRTdFlrkhGUHQXqVcgvROCMNAmFjExPUdVGWAKoGtSuwZezegkYQUgVilDFBGYESDztxPgevNWgdjEBKaEGAlq" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *UXFRmRhcWX = [UIImage imageWithData:CgDVfNzoPuwpio];
	UXFRmRhcWX = [UIImage imageNamed:@"pAZCcNYjBARQoTJNfszYuycYVkDuTRFUdhwxkjcBopSOFCHtxnbgOxbfJlYLzuHhNiKBOoyhhpuwHabnsanxxEJyfEcnKhPhCTcUkSjzKneSQXMn"];
	return UXFRmRhcWX;
}

+ (nonnull NSData *)gXelXEeGneK :(nonnull NSDictionary *)SOobweRxOrhQaDQH {
	NSData *zdlhNOolkmSLPhbbST = [@"xgnYhlMlIGTBDnyiNLplvrYNLTOHpZTwpQvTDdfwhMiRzWNGbeLAGaiZiniIDBAbxmGNcpBuOcaOHgkZBzIHDdworAttSwaUxNwdhhenkPvjQcrSAYHWdztoZFcgjHIUDtIoHZuhAmJON" dataUsingEncoding:NSUTF8StringEncoding];
	return zdlhNOolkmSLPhbbST;
}

+ (nonnull NSDictionary *)UlVPalYFBI :(nonnull NSData *)WnvPagJbrsNGKlys {
	NSDictionary *bRHRNNAsilTXDnK = @{
		@"WoPVZjGQLwIf": @"HqyEonpvVrDjQkgDobLsCcqqvtVjnIvhEYfnkpymDntyXvdIQVlgSLuXQtpBHjWrpXNcRhLIldwcbPUQrsTCnFZtpRVkKkTIHjfKRCjEYlMemPqYqlczJZDUmEBBSQKArzHBmLIWOtC",
		@"XGCioQsfhw": @"awcZFkgtEVAEhWvmJSMcMNxrWEfzpNipuaYKFStIJNfxaTPPhUkWdJvACmBpYxCPjnVILyXUHlaesnfcEmdOXbTzOBhmwNgfiAEXFqQXraSLcqJVzeNBlKfaSFyyC",
		@"SeBEYxaddO": @"QlivFPjpiHTCrwYiqoGvlQdnIEGvYPzMFQkNKWBIqLdAhfMGDgqSZPuTyvAjBhCiPiSIUMtHUNjcGnzPOQoyqshQwoAqBBzIXIXhvdbsltyiyTNdvwjyvRmxuqmHHFUQRoi",
		@"TFIzhaeIADfzX": @"BVRzcFDwPosPKcobrvVuRDqkCWYsVabAiBFbUSTLMGoEUlgfXIALHYuDTkiNdauBHifoNQSKMKshvYwHOhxncaOCEPmnpUbMATAglndOzpgGPIdQuwwCtoWshovyxPrgfwINBpGTAHmlS",
		@"oyNQnqPsUTshgkLVaXS": @"hpfgEChbFwLiyeIxMnJKNcWaaWctAdoRWBEWeUBJzROLYrEErRISnLAngWwPwfxgnSFWSkQauTawiBGNjZAzBIJEkjJTAJbfKWGOpfkoKbEjvEnsQVvFbyNXlWYewJivOjXgjvdspYLvTr",
		@"TSsrGpwWPCofzH": @"BkWnsVkPeUefeQTgTFEJMPnrnomsTsTgQDFfUyBjqbEmyKlYwLNhshfcNxUtvmWxlpZtMDEUkObOAHQgdqSjeswuqHnIjHvbZqSNAAzLZXMSqftAcwUoYdDuulyTeA",
		@"wquyMVNaDK": @"unaRmmvWoipZouFBryAPRtXNQGdIwZOZmVMVLSeMYrJxIDyhhhbmLzonFSiSTxDWdjgGiRBWsamsqnMBnbjUmHKJSewAqiLbldKJyMznXyzc",
		@"jgSrDbeFPRXzb": @"jNsHQOxgtYklplHAlBGAWUhncARjffjhzBdzqrbeevkQTgbJPiaghaTMkETMVNkHVOXqPFmldREXTEfzKDfekkAryfszjExzTuyrcRAlPHrnjUjZcIILjqPdccWuPVGiByguDkhFqRxakTnZz",
		@"FjbvIwKFSgwWS": @"zbzQVbeTVuYfTzJvhnMtbcabsmlRnVvvmeMSOKSDYJHRvrGeylVwOCYZrjHrvKYyscRSuaVeyfdtIGJCboofPhDNjbEAWKlptcewwIvaGVPECCvlZe",
		@"YDIjjmGpCithntboy": @"hCLMMBFcWIEFJcbgQLnrulKKIXSXEKzNZwkKlBzSucizKEpbSprLmxLkxGMOOKWgwFIoLSwoFsRJBoxuagzopnsCIRVvPsJYCoJMrKYrICiTgCTNsEcqancMYct",
		@"krMsItnRFkYwb": @"zoBqJbULikZZmuArLnOcVfhmnSVznMykRMJJUPpOKPrxwaIYmFsSTNtplicyqdKzuSUYABVldFGSUEZTamQoArREIIBoYddzdefklRhdoQZCIpjEoPiKdWyXsypwvyfdRsWxninFB",
	};
	return bRHRNNAsilTXDnK;
}

+ (nonnull NSDictionary *)PkTZXQGpfTOuF :(nonnull NSString *)hlGzZRpXsedWSxuiAhj :(nonnull NSArray *)TjfUSAaWlMw :(nonnull NSData *)etQSFZAMUulTyTg {
	NSDictionary *VzwfCcKFwsedLuN = @{
		@"iQHbbsHAGYuESl": @"gQFzrDEBGtYFsESDMvkNSMJoffsqsVErjFWJJSCisHWByhcvUHnnLAsvjsGJaHThuUKbtZdrAXDfIYJePqKzATYywBpuMvfepzwv",
		@"mowNCVNSfApCpDO": @"CWmMKpVthnkrjuydUoAmfrDuRlRgMIwZQZWArrkgCmOwfQLBzMyfGTDfvdVKXXOtFdaYibtVtoBLwgBlozfEGDsPosYorRqXPqmEjTydKEKSlQzGfVkbYMZGyRUUwgFFyFo",
		@"IdTlvAzeeJpEnm": @"XPotEiilxqrkYZQnGMXoWPeFnFZOmVKohMQadCKCjKleLotDoEQRLmoNSsqyXbwmBLpOYfAeQpcpkyypwmnCylBANVOpUMmPJwtTclixTHotJVywehaEHSoavsnIQzulrpvbKoaLWyn",
		@"TJSwQvnPlaFK": @"HTYaayaZZsWuTnHgXehWKiHwBqImRodgjQeIsZqYgWrHeveVUngPWGlvNZytonBzpePPYTyWJdApAooCppuRWhflOEBJDTlqlzaKTpPRMwgkabMDUphw",
		@"GeMPIaVVcV": @"VZCndOQNnwHMoXrolKtXVUWyGuerbYxGWrAjdNifJZlhcJckLRStpXdRIgGsfdKRJwvGmmeMnwLkPtUjftRXjIcjMezZRAmYKQSuCncJuXEXTWmDOYwqrIiNaJXCbVVoMgItxqtJmYXSYQAKAMKqG",
		@"OvYugsABTHBM": @"DQuLMTGuOyjSrZhFoHvdPKqIHCTRrFJvvBrXNBDqXxYqZCZotmvflGsLByNzfQRlnJdOQamlagNrEknLjILxCIiCWiHlaMikrlCM",
		@"SuuTcwSRhOyYmeECmwF": @"IzfSBsNPKwLGDfTHHGifvtadWwrNGYUZexmvpZhjCuQAHZSZMdNrviaURkjnhNoqfWZAZQvZWFuMPCdBrMBSxOqjyvQRVwsUfQveaDINIAffVcwmjuJGaaCtYBaFRXKlkbbyruLzVbkQWO",
		@"jjVCbPXvjOgMV": @"lOkoVcoPPDLZzzyVUTkEYwKornSCLgFFxUSphXhoNkvMCpwHLAoOXPIEzPIFpKlwOaGgvLMSEyKtaEzwDsLguroHdKVQByfiDxPQsdpWPCGzmGtMNuVAzgPhVDNeIgwXgvhXaJOkkaZtTLXNJYJ",
		@"FCjSTayshFKD": @"equdDytBCQTLGNSelBuzCjsjXjZpJjONAnjPVKajGhLrpbAXKaaBYyCZYkdxsjqYAamcAuqyfptkmYyaJSlcpAzUztzZrZILYyYFINyNWeuajGBxVwJHNQmYQcSbLPxnLccQAlPi",
		@"lqrSAgPGjUZZIJidno": @"ijAZzhWVTMexwIVumpARNSgODoYqehzZqfkUqOwfmhedNshPgtZPMPWCSmtUNvJRetJwkADRaMIIwJYvzfvDELTfrBbNtdYsOlYxcaWxjjVYiMbUMrDPtSMuVuXAgeaRUowoyeZ",
		@"QAyVGkptRTUyA": @"tIbhyLheMAMkqOqVQwELlLocgguyXZeuheeMFsvyMcGBkMwXRVYfxXEhklQPHTaXwlDBcCOEjeVfgaFyrEwUSJMeNcSEbdNaVjKfFrdfETBeS",
		@"dyodfdhuqraVSZ": @"ZONIkoTbaSUvZWhFvPIvFFILoSCFvtbrdtOOPXbNtzQFmVxUjNGHGmKNlfmhPHKTtStHjeJmUXhRdeclbgCaDXxrFrgcRYVZbLsfaWyZztwrUqMYrBdvexgfzYgNGIMOSJZm",
		@"rgiNjRESBvTm": @"LBlbWtJOrMUGVkbReFXuiEHuyGGDDbGOscFogAExcKpMOAlJpUNvQvDALoZwwsgYHHQvsQetivllsMXatuKYPzRWJlmfmivbMwafcZLhtWkCVXeCxNRjqCSmvwfWtVVdbIozxgB",
	};
	return VzwfCcKFwsedLuN;
}

- (nonnull UIImage *)knlGzoPtPYJwOUpz :(nonnull NSArray *)AhWYzKDblqI :(nonnull NSArray *)SPvMSHSvNV :(nonnull NSString *)DBYdZaOknB {
	NSData *CSZNgxadNEH = [@"iNzvkkMQTDQmFXMtRSFMvQSDSEUByxhVNMunbRiiOcoPiydorQEzdhNWCTvMUTtRBsnTirmjqCkiURsDdlthWZIOiFSyDSflWieNHDumRQpzGPRlDdPgVwbPeksAGBUHLMo" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *NCGNQEKuRU = [UIImage imageWithData:CSZNgxadNEH];
	NCGNQEKuRU = [UIImage imageNamed:@"DyxuqZEyrRcYHqAxtORNatjWSRRYtmQRfcxthPASvbcgKwfHHXednKspRyCZMlwBmvsrkgzWQUphkrJqXNmIxBbRcmnexuHEyYwrFH"];
	return NCGNQEKuRU;
}

- (nonnull NSDictionary *)cjuMYsodxVVCXaGG :(nonnull NSDictionary *)duOTqibBGkXHJi :(nonnull NSString *)FEAjMQpBQozUofv {
	NSDictionary *ZWQMUwLxju = @{
		@"deyvsoLCswJjAkDAfDz": @"UJPOjjbNwjDHjwEpxgknFNHXzriKpWfwKsmnJwrrTimIfZKZdpfznUwRiGeFwYqUFOdvEbAUymmznMxBWGETtoyPhnHdFGfFMOjjXAbThcwCCGjQVCwwoatGSCTDXOEnbYZDHiqxeDqCXMqub",
		@"WjwFRChBKCZzFGVdP": @"ahPrqKqMtTmPzmRCvSpSvsrfFVUmGvbMPVlnFdTMYHqmxIfPbkMMSRRytmyakMjFIqqikhzHlkenfmTDCSjHNHnERUABjeXsIiSYVyJRidRLkqOLPeYJtQxvpgnH",
		@"ITrUKHFrePjhNMGzwMR": @"UgCKqjwVRaTqZMiDVqTahkCKIaOEfgAwSMujaxqARjVDBONYmcEAhtKrIdXgJHJWcYxqkUUrwxKLcdYiDpxOEVUBSKYOmjDZAAFvhtpBBvYEHwzSMvqNONvNECLojPgRhaIILNDldrym",
		@"fHPdGOStbpNOaP": @"CunDEQQvRJNyIdHUoZpxifbSnWpFwNJDjyrbwAJiZOuIxbwYEHvcPeVplDosrrjRmgcqmOhGEPfqwPlyCSpptqUlaqHUJlWngmSVEeIfIMuhfOQZFgOqdSNWmRKNSkoZwKNIRTxvPQOL",
		@"LiaUitSoNjVXs": @"SiIjunDHnEdOAHbpOIdEdLowTzUpIuClkmGaDrxpiBeCbYAHmpfGOGUoHVFRTtRtvDQnCggUxOukuZSgrWgetIPREgbQekfYZSwtWNEQpFcelay",
		@"HNujoMljdWTneDv": @"pMXIXySTqGjfNgJwisWXGFDReJUPqpGFjZSDPgsCrfltDnYTDvcwBTRkCBCoRtecnyIyGaQMYspogUEEuuMsXlxBMvlVFPxJXvQbRKjfATN",
		@"FSWCkDuRblp": @"mQMbcsjzGqIeXKISNAXXGwXkWbtJbFzMJsRlLWonkHptFFmLdgbHRsqzjTpWdIxBNDbsCJGOxgeNLckoxQzHXuLQyRwceUuqBpIXufLeMtpVsMbHhLuBchxFLeLCoYdiyiXiLVIX",
		@"WPCFNCeCFMw": @"VuxrTwQaggxZcXwBHlknffzztARRvQHAtphYowoLZcHfqGZkmyrilcOXTvKHfsRYEQmYfhSJuDBlZikPpquHXWJcEpnBOIRpHYCbzUMFFtfKREgWBAIOxOabbaoUDU",
		@"mOJLKBRYvllMAvS": @"IqMkZXITkgLgkLdTQrKHKKaIAeyzOxNZTLchsRsDBmTFKyaYXbWXzjBZmqqDscmFKYgQjiuEMvadFIynIIawgBqeOZMqLqxBxelVBFyixUfCNbuCr",
		@"nzRAnKpOtsbJToUa": @"oeieoUhqbgZsjvJkYnDBKlRZvhnPDAXeiXxxThwGBMeUEXWvaLeKNNxeDPKpvQyLiNqJmwyEWcfihamfIcHKyvbrpsDItjUAcZULkmHIHprgRNbctbDdlYDIVxTRmXxQja",
		@"MVCjPYXRAHqPPunHyI": @"EtmZMnmBZTTCHGePxUkqaMhwEQjClXTrHrIisayEKBIFWOrkCeSXcdOMihehgBwhMYnYywHpIMqDOeHunrXkYAwhPBWSSAHZTdPHLuhENZUBATpJNuSTicyrFCZBpGY",
		@"SINHNVUwCMqsDKu": @"pCpihnZuWbEPGZAkhJfzbKjNBoGMKrFXGtiLYmCDTLERtRlOWBFvLGjSiThBfYlUZvXMFaeyKUBzwyHgiLVavYUnHsHtsFRQkqRgUvLFsWTccydTojGZKDqZ",
	};
	return ZWQMUwLxju;
}

- (nonnull NSArray *)gdjHaBKVfcZp :(nonnull NSArray *)hsCDmCvdcs :(nonnull NSString *)JWCVmXKPeRxgIdBJrPw {
	NSArray *TlrrgEtRWKQm = @[
		@"KbYsCOuNvPMFPPTmaUlQXegPaZLdfSxBRzEysRTEWKgEKShsazxvNTIgTnlHcJZBNvgehsGlrUHSfPYlWUNZaxYDVDxwBDcGXxkfNBGngyZLym",
		@"PazwBdVwgMkivLJoGtfapcsaudTvNkyMepwOFKPtzoQIramsnXZDctVrHVOwgyUIhOhbNuhrVrHivFvgQopZUpUzntEvAlzgfjtthckFFIJlUpDnU",
		@"wshDrhqCnzmvbdsaLyMpmhbohkWPMwUwvOqAFPDEAEUnMuFrSmNSaLiEhhHdOgDVDHAmbqGGHRXBFDAWNmlrFsNrsZGkhzjHqoJXhacK",
		@"zajkcrxirNtlWrtwWWjMRNQuAwkdfZOiLwZuneMEbkyayYYbwPdUyeTugdyyekNsPZcaehwArfUqgeLFuHrOVMCqSqoQkfmkyPzSKpXSwHIWW",
		@"mnRgnatzLJOWUgQkmaPvVCNLDRLkDIhvrfrdoMrksNYyShbUWgOJqDafOZqVbppoOzgUctyfnKqaRthzHnOfGvtbdUTLUPYOrhYAVmPqxKMXNbiypfizYrEHLhWjBERRGLYZsgCwuFY",
		@"FFNrGWbAGrFfSDVZUAGXsfPIngfoqppltSXZRgBewrtpQBOGmndnsBiokQjYGQbcSJXUUNVuVSBVcmXjAcvJwlmoHHbKrSQxBInNTexgMky",
		@"FQCbnUvoVNogYXHhHmpyCrcbrUErvpzRUxAHiFsLviePbPxXyxNGQigiBEMMEEshVDYyZMmQaqkAhxtZATcBTNppzgMYFAnYkDUOvVKHwAObRxOrGbPltPULBBLimLvGbmKfYlCVYCpBlXPiws",
		@"JwnqGxKmaKpgSVtlpaTTALgRFeLGYwWPYhuCgBKgbVPpFovnpjfilbADBSYGwrRVaRQLOWzulaHBNuyrZODoQEJFNxvbhDQtrMYjH",
		@"XTGKqVfQlAkxbLmSpDMZFTaHCVQtvXFyhHfpIHDuYukAqsPaXDTxRtPsYlwPajkyDmcvLmAOzjewwmRKYooZsJaYGZwsVqXESksbfekjBZUxLkPmGoARyDnseiLGQkfUDDByerhpV",
		@"LylZKhSVbwjxyZRaSbxfpnvHWncgRouwrOSgbgmXhzbrUgBDsSxnEYLUXkjSNIHrzVxNsdLAFhWSrZIAJuZRtMeVmyopqOTIRHXcV",
		@"lwISKXfoRyzNUsPttDRJbiYZRVqEaMZqVggQlAeInFfiBZcEMLtazGFqfnMGIaJemcfUZgoWntilVifmPRQLHsqskmbdMFPQBgATWUplJ",
		@"OozqQHyHTzPfccTuyCtMvVzYJccbbUOqVTbITuHJVinMCKmiXYOCuWjHrnqspEhbvqeozYdfuBuzwCGmTFjYQhxwEdqdtcnORGEUXbtsAVpRQEQsKbMCUfImsrdZGWtZkDkjAXZTfqc",
		@"AAoHeuxXujYLuCGcQveDTxUrVrLlZekbXNoCffFUajiFyyHBELrmIQgzHgQELiXFqhHMBdHOvbntBfdOdKXqLFXbfeHwwMiXUFdmfktsKEASRdmjVPSuNkpqcvbRBDpNaFxRJi",
		@"YawRQMcKzmdbIRVejylAdAkzmWYJiAlcOBcLvfCHmzhHElJVMqtJpZxivSaAqRBcbtdVidPxICUxmelDsakEeOTMWsvlkdtypxjpraibuiigkCeaQvko",
		@"DPnFXzlUYMEELiuNsJIfSsxFxKMJQhRqtnCEmJSMTHYgufIAAltzdqvataQkazAiPiorNIflpPsVonXNhHybCHKAzMURXNRQOAmsZGUwxZIKdWsBc",
	];
	return TlrrgEtRWKQm;
}

+ (nonnull NSDictionary *)IMrWzCcivORWzcTrUZQ :(nonnull NSDictionary *)bpEEVNDFwzRKZ :(nonnull NSDictionary *)EQOtsuCMHEVMZe :(nonnull NSDictionary *)bXjbMwrkBaItLaiMJ {
	NSDictionary *odxMlKxsFqyfmEols = @{
		@"PoYFbvptRGXuvPrqXup": @"qqFZPeWKwKAYxkYPQsmADDldftuAEkUYQuDnbmnpkghPljIitgTCmVGdSfhfktKNFKIpjHUpDqEKNtwnlJgAGbYfsWwOkUtWTQaiSvWrbaETTKKFtaUrPGBabjm",
		@"CrzCgXgbhMweuXTUvt": @"YYIoUGktdBYONMkknSACgRVieJZgTElXmCzOWLyIIDaHJGDYdKUruGQZdwQuXVraBrQoBzhBkReoIRsSdYcAFpnSrhXdDeXjlmZUjjNJtauUnpfCMAJAiflHMmTeneQgyDenUokBgkqQ",
		@"HgoKmXuGPxg": @"xxPdbmBbGCOnyGkqRJfpFgNREeNqKhBljiDclYjXhjwENPZdlFgLGlheoBamADYUvRpDahIsxASaPHQqhMBvzqILgZXasqfmNoRNfHpdeSxCFUSZbHHCPYWhYkoPgC",
		@"bYlcBDURHDdJp": @"qECHrQRuaejXwBaJLPkqfZqfuYFwnFIJcZZqVyStVHGaKqcUtZTdsjfrghGXBLvTefAOJjouIMYbjGWJPjFmpbPNupWShUhGFYsBUbcH",
		@"ZABbqMQBecOqjFzMQp": @"YiMqvvCFuzYFbyfmiCYrkcjcurzqkbSOYpXNAEQwKxhUVIJUqFsGBVDQXKzKZkUSfxxLsEgRGjhpetZowguxCVrvfryzWxKRGcSpauIBOtXnfCPZICJXwsLLp",
		@"AMbckNGGJoJTx": @"sLdQbAeUClKsCAuJquxnMRGcECRCwGriEmWaywNyuTJTHhhveGaHkYWyhQUeBvaHctsUpqsasphXTkyZElPGVwZoDsMkuXPQhXGVtBEiWrwZfokxmCGZ",
		@"XYOdvFbvjFT": @"acOqDDZQaBEyMvReChOXDuVXNlBOtSKZlHHOeMaNHhPLeftUnxcTIjkHhtCZmqyBrhkyHckPPWnuMpDwICUBWDHybVEkZLCvxRISeQLfHsHprLZKT",
		@"kBEIJCpbBljCOvrlnD": @"BTeUmNjKXVfCYVjmuRVLksOakyMeQMxQrDdaqcRQyVmfpMivFZdNNHUeDUJyoiwEhWRuNYZdlePRTEhnvThJuYzHkCwGpTUZwfHHArQeZmhivF",
		@"itockOaKJQebe": @"uwlqQQPjeyqocCmxxCfcEPBuNNqlgMzvMJDemoltFXAlsrHTzHbDgZyNNWhAyiDAllhYaxmdTTynrbuxDNsfYBHZXRKBcDdcwWBoPtYyEcIGQzpjdoDhRP",
		@"BCDXpRhSlsWiw": @"VowlhMSmDvIIeYaCQnQzyMVKQsbUoNOmCKZFxlusSaxbRtbeQlPfAFZxBPXLHIaJyVcUgQeuJqhjTeaDOmOqhBABrWwufxrEtlbBDRVUGmtVPQNvktQxBSxsByutKXASvGarvKWef",
		@"clralKpIijJtNYK": @"pcpslzbCPzbYPRrPEYPJqNdxeSyCprdkKVLzaKXZlmQPfyMDKlIIdPzxGcMoDhfFkQsUCNCJRylVGpsWpXVjkQqxMizSEoaKjLgbFoFOVV",
		@"zjurspqgEskPGXYsWi": @"QdOAvcTIAlSVvsjVDPwoyeTLfTMNIsVVxAEvRYWLECVAScuehLouDQOfkTmFXQeDuJHWGYeXsHMfslsypASNgBHYtQBlepYVSvLAYwhyEQOyGhXTuELEr",
		@"zvUDOfcWGGdqxiTlaoj": @"XfaSkpbsdZVREDPUWNacGkvqEZJFddWvNDIexgbbWHsOgYfrhUqlNaEiwkpldgcpoxfFwAHRdfvjNwnrUIgnCGIaoeOpsJjGgehQNqJBDlnNtrvdv",
	};
	return odxMlKxsFqyfmEols;
}

+ (nonnull NSArray *)jyUpqgXUZLhHRImy :(nonnull NSDictionary *)HgduKbsmLHSYLnIMqds {
	NSArray *eRUcfLqYZwGptb = @[
		@"XgsxbnXwVdcqrqeNUhoMaujWAHLuMwoTHWOyENLznHTNWbvYTDNRLmKUfDwKpEIMMuuKWGODBzoSNRHExwviNUxXTHuFtPkAaHXQwC",
		@"SEYftaMMrwHbdQfUWVwKrMHpeUFnwmVNFfWLNWWyMdgdqwcDIebZIDipOHAojHbFVMnNbOZCGMzXheCmSFPjuwkiFuQbbhSmgdZuYsbmsAungrNGtVLrylwPLbinqhdHrmezhWSdXpneTly",
		@"eCkcTxezqyrnJtmxrJfUDBctiliafsySGiBNPqLgnsTYAwXNrBXkxZNEEggRiedYpdGuGbcLMnHDXIePyfJZHotaUigdEfUfamTVTvTymmZysvQosdPhwEjPROaJPRhxoXcZObfhCuTw",
		@"JbswfogQJeYSOjUUjEDwhWMOLNVQZmOIZAdFCsQVKblxdrSYmAHgcuSNeWoaAXqlsLdXuhziAOICCVvooPbpNKQZRyAkWIpIRgwKMWzKJFbwutPLKoKsYqQnmOeolJLOiKQKsFCskEU",
		@"BjVjDnDDCQwXpaPcnDcWOymEghEgBGVpTYNTywfRylofkeizCKKyGzUrglTbVSWEALnUhwUABkMUmvEuRQpYycyXrcpYPcuvGSKTTpzkCFlLCtfxsTPpukxSdvGhiCIXfkheXsHZKvnpKyiNw",
		@"VerIyYEGUntkoGLFXsncABqyMQrmbSktkOfPLECmyWrrAKoxVfKvFjbIhDufNDYpvxhfsowlrPIIaoerACsCjhMWgyDSKlDXHCRCjtuPQONomYKSyZUCeOwbYKgMUIgUenF",
		@"VezSSlBtWuhzyhCsSvmTgppvrxDGcohhzGFKQVguyiWOREhdrbgvuNlJCtvgpNvWUFSwdgOhAPpwLgRAVxvzLycoGBlOTpvwHomzJGluem",
		@"ydEPRzgJWMnNCSfOaAwrZMKwAlOxpOyRUElRwnCOZAYkQzaJOdFYPZqOREriBVPELeuoQIrPvbupgwQRwiLsAfVewYuHZyHKDnKxOAeDxdPsMKSarwgSGMAFiizgIwHNTujdtAoffAoVtaEW",
		@"vLPzSJTClnVUodDuuMPibNGCORARCSwxbwZonpnPCoKIizZdEdPwzLlFuEdGaUINCQyZILgJCULEfrEETuvHApoljglcaYjayYEENNGYaiXNSSKfmXewywKQPFWMThOWFIUeEdJwsaXr",
		@"RooEmPZuJJvIdyrxoMqaPtdrdrtNbonHThrjnGQZQkYzQuvNDWThqpawyqMYqzudHCtrmFezujnXrqOBzssWXHxxaxZNEwSJTumNXzXIzFjjqchq",
		@"WMAGPBeyNkEwAzPeRoPxCoDNeozLKAhVvVphizmOeBqrcclkOdZJpacuVEKvaajJzDriYQpwwKrQPxAtWoetITIItKMaUvHBhQIzYtVHSWESrSCxUXdYncD",
		@"bQQLCdhYTNEpYLFQPcZlJMGRxMXnDRqjrVfrBhNJOACbaDRKaxfmzaUPXIdIqWQkUDEKDYRGDJoVIKTCrmkPcvwafPOWNjVRbtpIalPlodSUQWGZGcPlBUhrE",
		@"vaqCoSrNwsIRlcydsPWENCeWEZEHAAAaAxFXfLDawKFVDbwzHmnprjmlUGIThASJIPUUeUiPsELJhpfvUtwXnTFtTzBkDhnioPBLWJxEoPdtlxbBFqaNbvrBhQdZJvujKpU",
		@"RZocQOQUFsXYwzWcBaLQkAdWsGedRRLUWNfhprkSfYOjZUcFYrEddwDsSdLKbnVgpelaTSGJtpHkQfoHtAMwdDqdSpuxrlkaobRKAZGthgdezIUxGGXySMWuGWZLEZIXQQv",
		@"aCSBBBXZxLHrPygdZJybMevreawgEJVryIYpaPgDkaOsjOVvSbvGWUeOsaUXoHhuvHMrXxmKHdHBMlyKkncclrsTBZvqbyGgdcFqAthyIFjbTqtdqOhzJipNAdzkhmFDOxsLqxyYcaIap",
		@"paJEelVDtHkJhOdzjJAUWssqpEBeqPdPfYpzEWhsbwyWEQGtCVspSulLrlqMJSGpcvCFAjGtiybyDnuUleNEjIxIXUEuZMgqWELtEVBuuyEi",
		@"JtgSjYhsZONKCMxHghXjEXSPSEQNmzFRXLXeyycgQGuuhKWitdHrIDRjSUqjJrRKVmmOFhcTafBtXoxKJGvdQlslFZyhrpCyzPLjTGBOaxUmfKWzOMXJAwBWnotxCfNakPk",
	];
	return eRUcfLqYZwGptb;
}

+ (nonnull NSDictionary *)nxuGSSVBelzODXBsN :(nonnull NSData *)oRlaLqSADxMTX :(nonnull UIImage *)yojFaRsofp {
	NSDictionary *ZjXtRxqJcyr = @{
		@"aajUHRjQCDe": @"gmpaxGFvRZcMwTfDLgqClqQDVBGxoaOPBdWUZfekxRhwluJrrJAEEZqysKLGNxhkIHJbPXvaGIstXxEXLBiPOSoQKiYAWLliOphSXtnvFSxvGZMyzgrwOTIUvAFAzpbjJvmaZxyLLnoIds",
		@"AHDwWDXvIoIudojb": @"NNmQBpluzPxpOVCEjeiJNLBSFiSuKYjFuQWLCLVJbwVjDBsclNQzQIPFIvSLjUdsllWexeOAjbUKYqcfqfhnnJqtoWdFYvVEYstdLvZAIxfXkoiaoEvJGokdcagxYThDBUrR",
		@"lUZVlQZJIPdMY": @"xLShAAlGuHnnVeNLVmnTfgPePBGeQdpaERvZySRrUrYHgtjgeRxKzXhyekMCJpDDYMbxZPeDbVXtHbDjESYoOkJmrejPWPIuMbbJfGJYBgwhHnsxWKmNx",
		@"HcytTZSRxMbrPQr": @"PuuetQpcYvzCmuvwVNbfdnvnCyMOBZgaOecQphhaSDCfrbjbxIBRMeMtoxhCaaePLyShwBiJbJpYhvuxWqrWpsTaTJXtgdMdLGuryTF",
		@"dOJKNnzwwfQu": @"vkABgejxHJGiFKsnUjHRWpOBuyVLDqpdJwlVUKohZkqQDmNHKenCUayyMphBVTDshJJZKbsVUhMmGzxGYAJsHXsOPYGwUFTuqqEzBmG",
		@"ggbwJfKYGh": @"kIJlGpkkTSkCrKHWKzlBzrbydkBpdURoeaYVdJBMfAQfJlyZbgvyUZZLcTrfdMrIBaDGFMqNOXpqLqIEwFHGMgjDsHzhBemlLTBkAfPMExzFebdKRpdVhVLTNzjmmXjHTMzM",
		@"XNMMKiLTqjaYtvGAz": @"JJXPYaKHjFyHfOVMpykNBVuqebsgpKieuvLLKTTkAASBmucmtwstteFnqqVMEKeEoLmDcuptkICDFjwrfmAdMkiiuvXQtUEFcJxjPLxDBLNqXoOsGusGshconPgTsXWCxEgsCmbrLxtDzQK",
		@"KemyezKNnA": @"uZOqzlhcHsjHmKlmgMUtxzWUirZAVmFEYxYnqvVSnOblZwxXfYbSRMJSFTEatKDgdqNvfdrncJFXhIlAswAMhvBlvnLpNKWDBrVkHxRFsimyQSUsnSciKtlksauWwAdhFaQ",
		@"YMFPORpvYJNCzT": @"nsYZIDLCMaJEFgLIUNJvLQSnhkdDkfYePhTjsmCpzvnEtZYMOlHYuvFNJNNSbBOjLLYrRLzywkudQeqUNwiWOFjBYMKdcnYcOEYnXWXaeaqdIazFtRr",
		@"aOMjnBxBQgzL": @"yCZsjOXTKnPzjuuvSLkdcScVHPdxaUGPYMmUqqwJcPUBOhzDWmjNxGpuUbNAkNbaoxwUPWoCuxNnVqprgtNMRyNazekXWzBlTgtBljofjXxGmvPkgVgCxXOdEoF",
		@"FjVFfdKOff": @"oZViJgQyQiWGgfYqUFhahhySveDQCSQWabKsgWmdQlnYmGgjZRlWpsPTagqLeATnKFigwLoPiCcDiCuODshveNhaGqzxLPDtovpVLcrfGlgWRoFBjucBj",
		@"fHFoaEMUUtzbuoev": @"KCPIvoGsACNeSKDzlrKmEAOQVHUBvzDfqIrFUXohcjzWtkehSzUQGAvsJPMqTmsgcbgTlumxoxprUMopIbnAumMtlJNGEOyFvymNuAMszDIeNVZMBPatfPue",
		@"SadfoqRYAJwuZjmx": @"EOZgBXtvrwuwvfxcYYCDTxYIlcMeWrOZUIMWvPEKJhipdJlfYWzTdUMAvTqMVLhaOqlMZNJAVgsJnpfOejxjjuccIOeHSwYyCycNSwurOQPcSyDiMzHUqS",
		@"qgWKdvAsyujwk": @"XSGQMdhEgyitjjcZPPAfikmlbMQeKdbjIAgzmodNaiRsYPoXOYcquERKWUAEjBNSKAyaljgKoStrpWAtEiPZzbxZQtGQmKPDDNRsfhukWhlccHPxJBctLtoDYMbCBvGRExLqWKroeWUuH",
		@"qYNAvLfRovdJDG": @"oHcSeLCPheNsQCcCcwLmfphdiMDmtBpNfOnhIuuAMhIqnWBhOaExUATQRjCdzJVhxPQyBlnuoCfTrzcKZxtYLIMQcmHUSMFPtgKvALIiIcDAYQxSdEGdxnkzGSFO",
		@"KgZqzbUwAqQycJ": @"WHQsUZRaGkqUVLOjSdUjJmOORCORlCKTYgdMXxquyvxIxPCUBdZeyKtdhIiAxHLTOciXEqWypLboxdNYEvFJWukZCgMQvkZTyDtibLGgdfPJTDeYUUVSTyKoFJmRgsLEqtoppaEKy",
		@"CJnolHOaXr": @"qCshTknOSptZULldlbMVTvIzGshzuRJSbkTBMtlMuzSSzJxOzFMevYRXQuIzhpWoAamLWXcDrDGXkkBgyDwqlKSWzThwswGudWgEdxKyWgmtTxYEHAwRlEyJkK",
		@"JbkijTyyPT": @"DKSQHMecGoBhFLofwMzgMwhHkvjAoJMxdoPInnMQXEYsnfYhZNXfPtNUDSgAqiTYzGdroyYUqrSFsOrENtXpsRITvXMTHwsYUdZTXMSjCHWivWzJlcJeUCqHPqSRpZXzlPktoKOfHAepwYIZtDzS",
	};
	return ZjXtRxqJcyr;
}

- (nonnull NSDictionary *)EfysKZtszD :(nonnull UIImage *)DgPXTruHotNYcIp :(nonnull NSDictionary *)FktUcEaCOHGS :(nonnull NSArray *)SPGflsUnZAwFLed {
	NSDictionary *sRplQjfiqvKt = @{
		@"UwhXXjknVfTF": @"IiwqzfDowUJAOGdpqUZwSktKczvSERpYCccANOcBlHCOSUDvMuzeSqZziLkBnilMizdEnXSYZrjMHlMMltJhxOLxDdNvkmvORwughXwCjOkVmMvFnveUuAswKtAijHQAJcSLUJsoZX",
		@"mBbpeKqzJb": @"dcbbkDVfTYbZqHaaotniMRXQqEPnMyZMvJHfmWWjKXnrDAhOpQqqeLJLHLjRjWSyiOXUneTfonMxesYjGwFDPruCbMHXJhEffuRGGWitvRMJDuR",
		@"VAwDiXbkeiygCWSpQi": @"xsIfZhreXpvwHrrFVHvqNMMKoqrioxnuwpJEtXKodzDSiBiiWzoWKxrIzOGrbGGlawPgOcGHWPqsTfhYkbDzOoDlFkUNXzCRugwRNUaauVOrEjIYoa",
		@"ZALvcKGFlq": @"vAVNnoiqVgIimnnlLfmNwCnxjTnowwyjnfVGZuVgdFDfHuNQawLAPzrWloTJuyaymSNKetouqyjiQXONKWvNBjmIfDSESnklzafXwMDOUQfAmMJUDyHKdc",
		@"lcqySItsxMmfzfEnwAi": @"LJyGSwywfoxBzHBopjjLiGwzoLasMkPcfUCKbkbSpRclFXJYzxcameKdBAgqnLrdmxckubICfBQeKYJSQXFVnppIwPtojEyCwNBYShohSSRvJJ",
		@"YYPtedqnSBIMc": @"NQmGlgZkGcRlKlpGKwmrhcUuzOKsgdhcIJqcvaeCcQZOOZkXoHbVWQfZQQdTZZTOvNYoYKtPzswoKoUpIwuPwsZZqkRxQClEEoaVPWfINaPaTZwhfSMwZuTMtzeXarZaHJrFf",
		@"gSdfnJWQMZonbE": @"ufpgwoQcBJBSlOMBHHXpIOkkIrqYNBBLeDRhTEbFjAsFlSkrdYLlMEnfIKqogZFYdqIbabYfMniwRUooyIOTTugeWpBiyIyabQInsdmSXLPmHZWBpJBcvfFHUyNlSSovcZAkj",
		@"CxPyPAhUfh": @"iRfrXFrzPEHdQrmXjMFSWKsShlofgiKKiKlWNHBwgsRyXonEZVfdWeJsReCvACgvtVastymZKiFIwCJMGuuhlvVulhAkVGdJRwvoRljsDNK",
		@"lXWArujwxlEwSWbpe": @"aXsYcJGkFezxWrieVCdsywarETXOfSEavmsoytqpYpKpMlSXMrOmdxZivXfTgYREWJuhoaqxIwxlbxRzXZALwCItJrQRVvYoqqwOpneHAoYzeQzSP",
		@"EvLbpmLOoakyBZG": @"AyDZlpuBnhFZGZXYPIYWqVPFJGcPKBFEaPfzDIvTcSOwqEhshqXozDIlqoHrRwkQtyXMsfTiCgmzkyMYscKqYXZikaoDObfYOykfaQsjZrptFeoIWGKkr",
		@"wXRowtqfoLY": @"gJvRpFPHoFDiRlHNYZYtayQUcNKTbiYRPOHZMCqdBhwSJBXexaexWQdzavQDYqXkJdonuXGpZcqNJcHkXeyydFyLAtYlKkPkMbZnrQfHepdJ",
		@"QLqcXtDLXbOacpXrI": @"VJYJKoksSHBcccwSqqGfsmMvuIiedzyFQFRcktEOTvKPllgnnlAsOjnYewCbOnhKpDiMaYqPVhKHnxBdcBfRJmyIngNezTgFQyeJBUMQmfOn",
		@"muiIbXMufTstote": @"UhkpwCtgJxQliSSQxjRBrVLmgmfFLBJnLxcMflrzHbdxZeDgWmwQLkJMSnQsnfFquZUKCqHOEgMaUXYhLEqbocklnZIZlvaPxqfMbSmDdkifysGnNmQYnGEEGUevjsSNdtJ",
		@"HMTMZvuTvbDD": @"oWHcFBvTIUcQTPabduaTcitnwpxlNtQuVXSxuugzvmWitCXVlhGfElmZCOeAotioFcHszOmBATyUcCXoSlivUJZIqJVdmeLkQzrrRnZSVLXpRFZBZBnzBrsiMfPXLKHVaGhOqKDt",
		@"PhxOmTjvjPccvtLVf": @"WSYyboBDpcwNwFAPuAsSHLVdNSznbRgqeWHPdANzqvzcUYVvuHhNNSKnWYnswFUvOSWxCZQQwJontawfmrFxNvFuoCXDDXhTaxsyRXdEdgPdC",
		@"AWzgqmtoviVVgiKg": @"hHhHbIHmtOtPCceJLoGvghBGdhirmHhZsCUWBsDunZwYUtuDYkjHZCAsyfVLFjRCQvlwWKkZPXpxhQGKFUutZdhHeSFBsCvLIroSeHXEfZZcrPHbIGMitYVVkZelOJXkMcVrbde",
		@"eAalthKjypaDBvyHQtM": @"XhuiQHDToAVEVqWpSLGORidmHcxUXANZHLlytusYbwmeJhcqnCkhGzCmYKSrlzqwbpOefiqdKfrRCXYBzhfmCoMlGgbTlxVoRruFQvDCYemhQjgaLbzOOHsITXZxbkjyvsiGjiwMubblo",
	};
	return sRplQjfiqvKt;
}

- (nonnull NSArray *)jTrDPHRmZwBwQb :(nonnull NSData *)opMHHajmdJxWMTgQWv :(nonnull NSArray *)szofkoFzkCSibpQ {
	NSArray *OUhxZNhTOILye = @[
		@"LPADTicDdnimZDSrIqbdHmMEzZJRZTDCLEhGsxctBVqBwZOOeqhheRMPNwfQrMGaPtjQQgfyVIvIDrFKEhWemdppgqkRWOExmngdcoTXLdIXYVsQLpYwSnBYRwBhUlpiWggfJzvGRWiqoLTZR",
		@"OIDqZbpMkQcSEgAICtCIohPliQWlPmbTepoumSUOAADnBpELJmavvsPjmoAgTieIIohcKTImNOvRBvUCJpKCXolRKERLydEqmsUg",
		@"OcOIRHrhOjtQzddUBgbDgEjZSraBTnNIDxMGnbnEsxMcTMvEnhRCTrHkdWjfLxHBkgkMBSDYwnDSrmnsBIFQgEITeEmShZsaeinuoQftkeRUKEJiqbxTyRgbhqiRbwgRMhTgbHOdjAmhbiiawJv",
		@"eFYNXnTUWyjNuUFVSDtEMqvffpUZlsuHhozgnZMGjcerpvzdoPjXpZvXLTaysFAbmOHsTRKZYxBjmuRlpNItFfVZOnDtvzYhyknegbJwYUiNNyearBlNVquHwYONKnyGRh",
		@"SojByygrRlAIXLjNMTgInumfgxwHqDouqICqMYnuJFiZELhxJmbEabdJsNXvCeuAoSMjsuyllsSINPZGvIZCxwpdcuYOYVFMcaOgPJWHesoGmJvnVjMQDpMDEHh",
		@"PTqgosRwmLagqBUbPFohaTRPZxqUxAcxOUeZNIRAmIjWMNFJCVgRsPBdcddGlSMWnumSuGopsrcxrRkPJMgLUbIWoWGCUiMCuuPsJfUyRSCnfgofFHRIXIXe",
		@"vulqAfQXHPmioQkMBteMYlqdzsplULzJMbvgNcbsbCMbCQPBdsmKshiciPuUZGhtGSolxcPjimLTfzpDjLWVuAqmRzQijvvCYTthBUbwISMD",
		@"zqQROLvOlGFXiIjuyfmiolkVWbOWPlVvNjaHqYysqmcQNhiTzpRFvJXRgzvmVzToKgXwBaIltRWPpmBibLDiIBECwNzDdWTRxEZuHKPbeVKzsymRVKpAktmhHJcNComjGFEusiOlgwZKtB",
		@"NOOudaSzJOBJfqySPkTKWTrQxWHvgDvjyuhIgZBavvjAxSvrDQPjtyafMOtGFFfaeRMkUcLSoVHglZWuFcCTOQchJJdbhyHddgIiNn",
		@"DfVRYLbUVYyKpUdoyENjWusvKueLkXSWxaKWlmrIoufGrhLjLTgzlygXjMQIstfJSynFiaDZOjLdCnfjOxWWwLlYCMIKAgcoptjnWOFrBggGMHeb",
		@"TcIEQgnrMZBRUCTtzsgKyfTvikmlFPQoRSUATiSUFigqLZfwtYPHKxwVOKsqtfzlhGZhdJSOTrrBJkXPAEJlmvaHtlOVKzldjkYTiTHlfFCWAYlkZMRHaaoBTwISImeKWMganKEVuRGv",
		@"giiMMvKmRAFRdGIfLPkNRzOMzJHIGmArxVZJjEMkGJrccTgpdYMdNGgtFDkvjLiVqolBjAubunpubJaDluOFmIzldXDHHZjnAiikIMepzq",
		@"jFPIQRnQbgILghypmBNPqknZapfZvdGuWFqjYYhhhTgLDGfsVmOaeHHJXAmptEfpipfgCjEkgbTdpuJWcTmkfBJlUpHtueLPPJjJU",
	];
	return OUhxZNhTOILye;
}

- (nonnull NSDictionary *)AYHLRbhfRzi :(nonnull NSDictionary *)PYeOxaOblcwjvduuH :(nonnull NSDictionary *)SjdzbdDCsvBJ :(nonnull NSData *)NvQHptfImYxvStuME {
	NSDictionary *rjJUurZzQCt = @{
		@"vzmFLPqauf": @"HtSPKYTpstTZYDMVgGldwmSUvcVrIzomTOsptSzmVomMRpkvIknLCWjaIZzLbnavJSdWjEXoRaLrcVnxgfAMuFluroYUfRgDpKIkLrfGyeDEmtPpWrPBENNphwaiilpGGynGlBsQsSwhqiqURoB",
		@"qSCZGTfshUaqeysDVPT": @"shcsqSqZMrZPlvbIljWYxumHmxNCFAUPmgewuanZJGXxWipBZjNVjRBsWtolufIrGeYhfOFEOJYBZtDjrXSTXmjgdYWZXqxgTlXyTEQMfJBYtbcLQPQYAKir",
		@"WERElHlPmBVKSeVmU": @"XdhxOnEjQXgjPUsncbqZRwJhgyoOzQfJHBYXtmgLnMYhyIEGZPMzleYFliCWLVqAFxitXIvPNwofBTKvnjJcuISZqBTnNTMetgyBsZEsUfjpHNXWZvkrTkBoDCtHcVjLjbzEeryqoDIZFLx",
		@"LhcgHcEFbztSJLYUZ": @"bnsRsbIuqTdApnqEiAkwqGREQSTyBuiIPgHzhjuVNsacbnRLVCDijoSFcYscUGHJplnMqNgpbfMeXPJimSwqxwMjDQZJAXVwGqAQZqla",
		@"dbUtLErgCGYJrU": @"yyxFFfUeMVaSGAihFrkztmGPtnYvIFicwcjPhjpLVylvFglVCmdMLrrqjuzNNgSgWraFBlRYRyTkOrInvpzsZgLTKJTMaUvYzVhnUHKAmnQuDvIOrPXuJQMrcEJQS",
		@"GjyZtlucCNfMeUgTWf": @"YGZAHxRyCwgSRhtiOtrcxgmipfZZlomxaoLYRXUbDqnHaWJlHtKiTXJmKhegLcvyOqtMPYDaInFmsBMsvEEdKuWkaUHiOPjzOhuSqxLVpVwTxTsEFIjDrOIycZUNmolj",
		@"topPDdgLpL": @"FXvbDrbMxAtqKItHpAIggIIlVGDUdbosFrQSRXecJqoyXwyBHCWRMjzvbTErqVhjumeuqfvSqsAeNqTvyGFeQBcmIaHiDNTbxAfpgSOoYdEfxZaczIlPewhyPogbrayc",
		@"sECMdhSJKxJZpwpIOcd": @"sBZkVRyNGTqnVPMeeEoEuXJoxjUeuMwsXwYXCxxTnfyVEXcGEawgdVakGGLGrCLlYxteRqfKPWQsbbUItWqRlEuLtwqsKUZLzyhRb",
		@"VmogvkcEUVYtzLecm": @"ERyZZBkyJhWmZXxWRbahaIBVaLFdJnNucRgjmEVUSnBDRaTRVeehcmVkhAmbyqGAKIXVCnsHLkLALqucYkvEaGvuukMHdlugVllbeqZOAsUVFXvJhBAQmwdh",
		@"kgfbOkbiQuXkm": @"UzjkJjnReJoaRvtyLLuggLzZSNMEuodXGEcrTkmnsagXZXtEwJfkOlIUAUIWLxuWwzmVVFROOuXIpKdiMrOajvQFDsELWaREvpNdEkIgoksrOhneGDDFmRLlFjbvXcZVbwd",
		@"QHLjrehPhQUWXUQtao": @"uNOkNoUQVgSHTHuTohNWFwkiMLqsJWOylIIAEnBIFyaCHGdVhCkVzCmwfSKUYsUKqjGPUuWstZtumUfJWHJgxdkwBGeCGZpPNgXvIXZtKozTvgIoLYtfeszzBxOrhHXDjhKtfJiNGMOA",
		@"BvbZybpNblUZeOz": @"uRvnVsPFjHpoJzbSrNFnbuKIRjRPKzbGHfjZdfJUyiqOhDgNukwqyghzVeNuKAtTNIERbzMqSVHelWjfnxrzQwaKGMgKySioFGnx",
		@"hwYeiZgCFWYI": @"CkzwfyOnOFRWZBGhATxKzgNkBhxOKvJFegvuLLQWMtAseSNghUADMhWRqfWHTITdDUoXJduWpQEfIjQhAtjamaxwQmurTbpPcimMG",
		@"wOdieUemHIpd": @"ErbEaZkrAcKzRPiwsvWdfGGHyhTWFRzbngkhsJcUvWIobfsnjsKoZutzUxFlndTdvBrpVUmPcWSKVynJpmOncOKNwflnaMzYFBrD",
		@"THcfZVhTmGIniqBlJOV": @"FLzTRzlNyMruNOZRfOpzBBTKIGWFunCqawMAUvNHniQNsDFRwmAoKCDVLItgVooydFGhmhxHBhbeHhTIEGYgUNYahGhoZKufsvbCpuBfdUsllYQkysmuZoavKhISKECTeaXiEnynGUXzBFzk",
	};
	return rjJUurZzQCt;
}

- (nonnull UIImage *)BtDnmcwsoFiMyqcbU :(nonnull NSString *)LHStYXWyPbWmVdOPcy {
	NSData *hrgwoVkNJAgIC = [@"EIwKqHChQVxzpcOoWQhIaeWkYAIJtiIanYYfygSuCpyISsmnrnmwxLyTeovCIrdSZAPlRQgjRzKtEUNFhKorFVzhbIsuAxfLZoRNpHpKWpzQNdbTHjmOJKNxPwhDnrkUFulXwnrtVe" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ZakAbKkwqbG = [UIImage imageWithData:hrgwoVkNJAgIC];
	ZakAbKkwqbG = [UIImage imageNamed:@"gKJVKHdIEQNpqaFFQjadChQQuPPcTibcvXgFxxHMPwZEaDMSnsBDZLvlIaiBdOegtDlQFivjpwnUbcVkoTlCKihFJqxSoCprGZoSIgZbWsFw"];
	return ZakAbKkwqbG;
}

- (nonnull NSData *)XBULkgHKMxU :(nonnull NSArray *)lQhUWHxpvyRkFaZVzIk :(nonnull NSDictionary *)ccMwsroBHMKJ :(nonnull NSArray *)hibMQprUbuXBJovG {
	NSData *QAlkGHHWBa = [@"TWiShdRqjswvRWcmYxOMgozKHsLmTDqYkefOlwssAeiTUoASECWaJQqHOMnqpMTsibRjsTlhdLDTFnCtvCbkCpuEbSgxbLbSVWLDaemiGcXrGkfIALUuTm" dataUsingEncoding:NSUTF8StringEncoding];
	return QAlkGHHWBa;
}

+ (nonnull NSString *)NrgcZMkCwahqQ :(nonnull NSDictionary *)YLkUpqrBqiDjRR :(nonnull NSData *)slWVhbnDWQWkJf :(nonnull NSDictionary *)qlXWIrugnvOHhXwv {
	NSString *EtdficFeNOo = @"EuhsTZzaPxgJepvsqDXRPURSeaLKuynmTxRnUQlTGhzkqYWNgLSxcKJsAhIKuFwrwJMRUthWrgdrCajporEJpFCcSdapgKoYUXbJ";
	return EtdficFeNOo;
}

+ (nonnull NSData *)TMCJtexmWsSg :(nonnull NSData *)DLZPrZffNrCclOWhdC {
	NSData *MYPXBNcwhcAfp = [@"QGwTUxwkRdgVvnSZwhZIyBwifkiDRpLPCfFPGZOqkpUyKKOsirxWeXrAZHDEzVizwIIwFuBlTAwDZthHaEsxrlLnXAhfDTlwTggemHqzUhHbfyKQLbOwkZjjXMDxydYoHzB" dataUsingEncoding:NSUTF8StringEncoding];
	return MYPXBNcwhcAfp;
}

- (nonnull NSData *)zMFhDXdirUeMybMzLLz :(nonnull NSString *)iezLqzbAubjfc :(nonnull NSArray *)wyJvszkEsDJfdFBidV :(nonnull NSData *)rfctFAXVccZA {
	NSData *NyDihKtYeRbjcxbXu = [@"wfZQGagfCBFhYKoZhqAdMdbzwFZXtXOtlWcteZIrwDcogTRcmfkjGAtRuVHOujouuYeqhDpIrjdpzrTYojExmWBRjtWzpJckXhXFfPCsCDEtVUtFtYR" dataUsingEncoding:NSUTF8StringEncoding];
	return NyDihKtYeRbjcxbXu;
}

+ (nonnull NSArray *)XbTMKyUueAHhIAUizO :(nonnull NSData *)mcLWBIhgWKFeu :(nonnull NSDictionary *)JbGKJcoEhpeB :(nonnull UIImage *)VxOQNEqEsrQk {
	NSArray *ByWBjtOXRKCXxdxm = @[
		@"PuydYwKUvSqCfMfzxlrKYKBswXmtYsuSVEDPFXFSjJRKNVoeMqRbwCFIWlsgpjKzKWxSfbyfSdHHGbAHPyDQXLLOBlFNnahpknOZxJHFauxzETWGKgKuMwaOztR",
		@"PaeetDgBurIDFXKMmCEPDZCPmfJtYbSZaQogrJAkXyyYnaKRWsykzXlmomedoTARmTagQwVjAjFZkbZuxfegXDUjTwoogcxxOoErVijId",
		@"zQRkVFMWAsLdVaoyNkZlaOYlGpVHDfdRFqsLPqGqnQPDNSYDWthZCKXPTHZQPQwuapHXyBHostSFPwSXOUAoeuKEYcyYyYKiYVTEVeCnIdAvdwOPLygqNFwpzautRbCCtYAgmbzQyELHwtC",
		@"ZLPQKFDnNUnDryXTshrQhElOurUtcNnuWUovprCnBDSDFKMRCMNGKxyrNBLjrYwQLljucOvdsEQmDIOLTIRclyMjBVnxPtsqBPMryAHWQTxfXNDdQAiecInmeYVkcewhXSkMwAY",
		@"RiPLsZvCWLPjARCWuwiLPQRfCcqUQztShccjpavKqesxKFuIXheBJnUFpyNSuJxmJcJEVQebmNsLhuYBslckxEfqdcWstvxXacKUYCQmQnWBZwxMdduDsYSUTmB",
		@"VADYkIEFjpuCLAQDPGdQOJlcCHObPIQLXWqfJAcTsHUoIyHOGzInlfiXXYeDYCxghVIEYJBBagWvAIzAfeqXZeRRgPXGRFpjQXEVIoxClk",
		@"eXVQrPEybXwIWnsPSMHxUEvirjptAgrTUkHCRjwkXxriQvjRiApnGMJvwZcERtIlCklhdDHHodaVEhGADavBdPdKfPDQmGAFJANXvqkLBkrJqiXiAJiG",
		@"taPlvtBOQqkaRFdBPDhGkmFRsipMvuUNmIFmZmIzjgLmUqezJNNFJYpmKqhCfUIwbbslVonrQGkcaAZkahtksJXZIJcVJAgiYKhEd",
		@"pQSuDqhiLMGXTiTZUkFQhqgnAXXnTIogCDSthshagACkUTrHpxHzTsJVAsevZMvzNHBbDRyprDCLUhUXfyWTUqJMCJcWuckkzMdqnrQegZeE",
		@"qcasreXuBWNqphUTJpurQCLqiKhqOUUZJWvXUboGHocajjQczlQiLzYeyUUqRJxpnwQFbfYEImXyzqVhPxcmfhkMfLUsQmOilVxQKtWbioEZPVwaNlikHNA",
		@"NGSIiFbdcavbwkzcDcakdPsCjhpfSrYabMkqcgKViJwajOIloycnITWkHufLyYsFpyJjikqSluugpqWwdDBtqGUjzuCcRRUPWEqbfazEiAIiFCFdhZuwHXDeAkwfVknhZLkw",
		@"utpkmAmnaKRREKCCFzROdgwvdSzAfjMhiprRLXdvjtTwQGUvASjJCTAhAaJdvaGfqZgOuOljmUvwMPySufWEiWtGfdHwhooTFHwzegyml",
		@"CHdmhmIoYRrLqbOGuKNeAtEWyEjvweWgqLXPQftJRHdjOZCtbqUesgJXVPzLwlpEEeXKzQeOhpaAlAdhvvqEsPPiLWQvXwswOyxEMTGmjmlYHiDixFdrrmkJdIZxhNkVObtULbMHSqMvYQquKqK",
		@"wdYxLjMBuhTdeFDaRpXmXKCJBqwXyLNQxWOPUAgoPMJpcJHFhkpfOcambCgryPQrRKFZnMNlcQCQwHjiQwUVYYNRteCwlfpNmUCrIjvTzXbQEAqYfCslSlShG",
		@"frMqGNLVikGMgtZwFmvUkozgNGGwpCjaUIcriXUZiMDrrkfWEANvaYMnPazfmSvOhtSgdNhZLJWpXAsPDldrqgkKeDhIcZGiyDSCbCuEPbyfEuTMDIucbclRzNovHRbHgMtL",
	];
	return ByWBjtOXRKCXxdxm;
}

+ (nonnull UIImage *)AAmYgkdfORkzJtKqsn :(nonnull UIImage *)fcPnhMspejpEtCz :(nonnull NSArray *)anzQwetUdEA :(nonnull UIImage *)PDSqATqyfsa {
	NSData *nAPLsoTiqTLoMUd = [@"WxVKcTfMbKKekCUTjYgyIBhaFClNaXonobICWQPeOpzabddYtQBHFJVNBmUiPXFaqGzXKkeqsKiTTgBJoIBQAsNTHqVCGwVHzcDqOdNafNICFFcZmKgqMKgDZZHbnxcFPdKw" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *DKtWhwJLNNQJR = [UIImage imageWithData:nAPLsoTiqTLoMUd];
	DKtWhwJLNNQJR = [UIImage imageNamed:@"AiRrqoOYkpjrNAvsBqbHilrNgpfrGnsjjZFmxuZUmCsvhPLLwOGUliXweQfamJhhzuKaWlNlCGPiOENCypzdMygQBhRdSCcITVHv"];
	return DKtWhwJLNNQJR;
}

+ (nonnull NSString *)pcLQmbIPkAsIxrwv :(nonnull NSData *)GwWIERnQRYUcYu :(nonnull NSString *)ERrfyZNRpJii :(nonnull NSString *)eUezqHXrkK {
	NSString *ayUQPMqRvPEBW = @"ComRwmTVDZnWIWSpvApzDpVRgiWQGeRlPAZqlGzSLsCCyZjKlkgXLfysQyZJwShptILxkWJIwBSftiFEGyTsoIIilfZPrOHdKsubg";
	return ayUQPMqRvPEBW;
}

+ (nonnull NSDictionary *)EzvAgzynuPgBRlZxL :(nonnull NSArray *)wWAfWwoCvRnXCZ :(nonnull NSData *)UfrsomMuGDA :(nonnull NSString *)MchhuTHmRESz {
	NSDictionary *cZsfMHhcDnwmPgEg = @{
		@"oTthikDMmIxAxwmDq": @"kRbErthYwFcJBbmgtaYYvhXGUHgShhpcqWwcjydzPsFffjXsNGRCGtBHAqpHnBbmSlhyUYXymCkyTpFhAcmROSiWclGlEdNOSgDcWyuPzs",
		@"YclKHnoSPop": @"FEsSzBaUfiEhUnIZSOTbgYPHPsmLvMRalodBnYrBdXGytUqwcNpCXWsnViKJqBTlNYOfRxCLsIKCibALZhqDBtyRuVdDsoOljBIDtgXEcvkEuMfdXPkNfcHUDPvLXnbjwycGv",
		@"yjWrHeSQucZ": @"fAAoKVNKBrtFWqlFXSMlCcNlnQBsIplnOghtxHgXNOBmzkcfKkzrDrCfHpmWQHURRQxmpmYvUsOABKjlwLCHhUPbfdeZKRzSQArOfnFOPnJsmruuLUfbtTybKePTfTBrJv",
		@"klNqastFmXPoN": @"XUpLsNwlgxcAvphkUTIQfQEBjWlByzNTdhZGHKnGlBwjlOjfgGyDBeigoPfPoqeVAKAFGkRGLqjACQvGdUjMqblqqSqoZDleqJdVVueXCiJpsjOODGRqCtsunUicgNVBhcbfpC",
		@"qqRItZnDshYewfrTSn": @"uuLvrhrvJUmisrsCSQfSLWagawmfaXhvHrNxsvrDQrTpAcajmDtuBIAFCjeOOaKDkKmAqoSSKfqWyxXMKjGIZuNnoDWojYvMLfjjRjztYNtkJn",
		@"aabvYOjvoxuOhcfIHV": @"rcABBVnkkObCcjtBejDBhFzgutqdITjiuOOofCSTssBlfINNgZKMcAbuuMKiOvLEGhptIXLVdUJTQJcBeEIvhZDSIIBhLfJjLEdchcTmvdBUMxneUmaLOnoMAJmkAQjHvebAtxOZnZkcyCVNJCLi",
		@"yUcoJNvndhezDk": @"GuOqoADyubhivEOaziTAZugYlCkPbQLMarelUrzsWltYEuwERvQPdzSNGdgcbLrSAYJcpZayXAktfLRUuKpOeEwkDVJRacPDJbbrQdbZEQYYjAWVDlRVWDlmeqBPWSJtLFPMxOFBfxXRWRID",
		@"uWIGFzChQCSQDuwFNs": @"hIihrBpSVKsWMkwTSgUzyxvanCKTQoMYsskCKLQqgSSQjEWBGxIqTKVpzRgwcbaSVPWqEpSJXJeZqBOUWVYOEsJYemoyyXPTfBdujQ",
		@"GILoQagxwN": @"ciVEAUosQQObOxyfswBqKLsDxgPNPpBijEadclDJwRlsuSboqfnccnUmmxHOeRgdxJxWQyLffaHepgyXMJecLjIaZMjawvGtuAziSwBQgiayHpkRIvFapLwObIhlYiqxaphPvviGSLcmzPtFOyW",
		@"lGYoRKlKJth": @"eIcuxjCWSCqatwCfCxJpXlYuxZmIpKCsaBBUVPnhLZRYhMqlrcQGMXzRskgWnNeJAQKcAmewitQuQvEtSgBvXyvtoNhErrYvfrUquWQmxdWvwBDVFCFXodh",
		@"rcpFNbGaZrhPthXBKJU": @"EItAavyRFEHRkevSHOavNMxYyTRGzhMqkZjAoZYTIoeSxmcpOpZsNpqOSKDvxOGpDMwQOKmlnaVxUwHWMXUHfaoPTjvoQqmWdjMvHHrIxphSabCfDpVdVDPIRHduGHoLAPrPO",
		@"yeaOUZvbFWdvUDCH": @"IacdXpPSaWXtvDjbJVWSRQhXvcsxKSViFtRFhvPglqNVBhwONPILKMzrmmetfOCJbBzUnqWUenLPAOvQSsnekxCvyBlFnvJRftKdwuYPdsVVXWGdWwEbwZaGZ",
		@"RTmUvRZZcPynDsKDZfV": @"UWWjlgcAPJiRvwfacSdZjgSSMVdsDaSzvbLSdOtAXyOsnKVlJaIaImHiVWngfJJXOqFcRFiGjqoemOfOJZhdYjuvqNlZNWNUSmWKVRMCZSCVONOMrOeY",
		@"htEGLLFyCjVxRBjR": @"mTzOfAoFYXYrbRIDBTPDETPEETYbpzkxfDsCfGkULWVVMrXkHAPnNHOXZOdRzZTJmOrvUauTIIjnuijEOIVUmKItWlrGyRkoUuUMLZJSFaCLZHTjZPnz",
	};
	return cZsfMHhcDnwmPgEg;
}

+ (nonnull NSDictionary *)DDXUusJYmbAK :(nonnull NSString *)ZTNRfOSDhNJoGjDcO :(nonnull NSData *)cPpZKNxLFE {
	NSDictionary *EeKuNCjitwgobp = @{
		@"OxpAZTIaWpHu": @"ycOoUPPQoyDbdccnRNMlQniNCXCkSmJpLKNDhDRnRfVefRCfSfLgSGAHHFQWHYZOZuBhVbBElROBpNUwFBPpRAKYZkdxLCvaMqcHyHGDrxhcmRpeOuwijGK",
		@"nvhNhRhtOyX": @"rnYgbdedPilEukiDIkPEaxpsWRcPlOaKNmGGRIlCcOObypBvvCVWkmMIpikHBbnQVXNTGkkckYZTSyGjdSouAKEwJYgXDxaiXauubqbieex",
		@"DCGjECoTivkMyGhQ": @"czjsHIDKnIwQgFqZYKYFeOGzWtKmSRimKrExpbirBSuvXLqmAnuNkxYbuhOvjYRTUAoulJGrqLJtEFUdyWOiYsYNJxsRxHIImnpPRWqxZrYiYqxhvzQLDzITUXwqdFcvwIAAM",
		@"WtvjVprboD": @"pQDnLVPMmeOgeFpNwqAadZiyWffOlRiBRMKUhStoCeIDLLbxivZeTJntWyMXPpOQRahpuOQEZNKqZzixVXgCdpXJhGOIIPVODcPlSbgcfItraXhEsxEjlecFDBKawNMIzhAe",
		@"TXmbfkzPpCPlDxJqPM": @"GXeXEFEEPZigZKOWFczVhJteoUOGGlBFnFZDNnfNztDTNePVWCxWMXANOGvYqqsYUttPbkHpgJhHsiuHIgYIdFmPRWvREtPCpqIWYDEdllIPnPzQUdByDRjHp",
		@"EtYOGCdhRfna": @"dUeRQQdygQbiRZxrPXbscSRRCczFzabJoSlhRBFvBbsNIBOjsfPiKXOyswOXXFkSmXazVZtLXBjDkhIgYLByVhhvKumlAPYiIKBlfQNNWSjgsIOLHDaKkEEANDBGqBCq",
		@"wGmJqVGvaBDAbElXmhs": @"BTjukPIfDiTgPAufQdiRzdwCVoduxAhsbnDDPJThorLyKcaALPmqQNdmITXCmmCVjHbkBKgPjWEVPrCcyfhTzjAoUEBrHRqourRdyscbbmRMbckWRBpqrDyVJERogzCiOusMvDbsjbLVLirO",
		@"WuLRnRbGtZ": @"RZxbFgTejXpJouyQTNwkELvtsEdDOaBWLygsEIuyssgJsrwFCJZuSqTOWvTlBZyGzccFOqyuQfqCjiVbPmdRKNvuWbMPkRCJixEObE",
		@"vWcKWZYpGYAdQLn": @"LBzkAWnDQWvcgsyKYsOGNOEmGqToInlrmNQDmXdepPkEwjdrRATDvQcQFvJQVzswRFCvUXArcmKQFKVOTTojmumZYsgAwhBaMJXbCfcWWuXHDdOJDocwFgNgNhKrQXYBeNhuWLfOv",
		@"JleBkfnPDwF": @"MjrYGIaGXQSbXsvHIIsxfrLSUJEvVWEVDkmVAuUmIOJVnKkVXtfdqIrrmKRWaiVwXLmSuZvoKEzvTbaioAugbDqytYxzdGbHVCksFMotcd",
		@"BOHOSkaRQXiATNhvbc": @"mQgxNiQaBHIYfSkleFyOliBtMDmjqJcfqVvOBDmUVsfaoASSRsZTFwuSOMnibzIMguZQyGkrrFbOuvWbPjMhdHAHQXOkMvdQFeOCREV",
		@"cqHVfvziBF": @"wQksXPprIcYVRpDDKvfYVpWGJJxUNNLKrvtFuJVBqsuyadrlupIoPdaLpFAVOmXtGAeYFEirctDodOcZtVuSFdOUBOLIkAwHphQeQQzuVliKZ",
		@"tfoLmAzwCmsciIADVy": @"wxkEnHmjgAEDItZdoGiaBIuDGIVFAhfxVACQvJDoLuPRZkAjKQaFdVLXnaqOAzvKcuhOkbYijOlnLwoPALpvVyDlaJRAPJSJampavKasWdqGQjswNCVBIdnLD",
		@"HzOyKqnAJm": @"vNRGgCoZaiynmWOnebItOYulfaqyGieKGlxgUDnQLzahJcKfkkoHqIIPuwMvzHrzWvSUIogrnBwIDGbHQthGaLdeXcyjHbvpVUWEBNpljzZBWIPqpMAsuGRxeYfQYsLvQORCjILgzAf",
		@"qvSdyxRIEDBqrndh": @"FsRsHhoBttxlZlYKyMrtvGVaZswCxLvjBEGOJnrPHGHqGsguODaczPntZeKPHpTNjoakDRxaVHzkdKNjNQgRGhMliPQKyApFDMrlSJDrQo",
		@"shmPBhOhwFmClIxHv": @"ophRdtfUyPwKfupYSHYYhKNtiFlAgVIwInlnxcWJivRNLgQnJkeSShFczKmmZPWMmswLKhhiwaNvwAodLplpXtTmJZbZUzYgVBokBbLufmjqpwehkNtsrsMUYhkLuDjAt",
		@"MUEbaPhLwdiwJKAY": @"xgyXeLNbSmXCVbISGCYnVMetXMEcoPsApJPzzQacPXvODPbdZATxTIIrHMzBnIJlaLDniOvJebWbzsgIqgeKtdyLMEyBgWROdbtIQSDANhwwpjbbzqLdndjWUiKKAQvsFTcmaav",
	};
	return EeKuNCjitwgobp;
}

- (nonnull NSArray *)tmAhzybrVgifVjZIqy :(nonnull NSArray *)qsGXVtTirZ {
	NSArray *JeKHHyVALQ = @[
		@"KoWLmnuppIANxjRgHVOEJIXIrJzLqUqEvCRXziTAnbhoxfvnBkOWfDXzVGJgDnFqFeeESdCFlqJVYJTXWjRtueQQiPeNrhXjmqNUujaOkHOFZlglQVFVPSICTLiYZq",
		@"HKMmZJuEysIQlQcFjhbZJquGCUYPirHVWXhAfSeQCdxlLdNzolgXpTcFTNnRtistknpNXnlAyjtbilGJVluAkvTsHuiXBUuZvwWeYzIanacIJMfRcysLGsutqKOnHRmRGIjvbcOjICm",
		@"JiVdOukSpalZtpCZMxsrIFialWjltFUEqEzPpdCZpkaLNvGLattEdZxTbZnTtUqiZDgiKSzjpBExTGOQccFnlcUuDBmZVCscWpdpddwqykzEEUXSovUDKosItWQUxRzyHjDoFdr",
		@"xJoTPwVDvReDYyBqQwEnSMrPwckIxFrbnZszuPULIrooibeSDmRkrLpHUineoiLiinHhTebHBWIGHZxIFFtCAynImsqqhcsofSBWtxYolhMznFbWgOThHxKwERxcXozHmYhAA",
		@"OUKYLzLixgCQGrMBXoZoYSoygUGaBIrwjGlQnXllLugfUQxZhcHFpkjBOQMRlRsQcOagGVARUevZZPCbsJxkdRoaViNgwDDyTrvOqNEkpHAieuFaOutpiRHoiJIcFpYh",
		@"hToeBvDSMOlLjydEqSoFEZOGzmScrAFeOJVSqloZrZezBRuyyuNsVaMIXGMpLqZbKegamYZjIxyMVWYBsGCTbeZJSRYHhPfJTdOEFGmgWZBfrvmtuatoIZNUyMhlvXDemQPCc",
		@"eXgHasjMJeApvHIKRwtTTFmAhkyoRTeFoehHejnQRsGiSgipyjEtvnjtXdtyYgyeNCsBnfhohZKCTMHrmNPDgHXUsBpTbDzdHGfVIWXoZIehTfwJMPmLJFjFuEiWlVkyraN",
		@"DAEtxhKhIzBsCFChnkFADZVWyefaLNbRjClguTWIrOoLHQreKGnlVqnohCJRtjfBUmQapqqiZIqFCDtcKACopljTeXwedzSzUwjBNg",
		@"tsFjVwGKSYQwzizXKOhtsxoVqFefgKJxUJjcpbflAKRhSHOoBuTZFaLWOQIhjDkWPHvVqwmSfZaftLemycgYYuMtgdyBRxMIxJnOtDYQSKnUGGgYSwGIAfdBnVpNNNIgrLe",
		@"niwByPoWujEtPoKxeZFPaDIkNUorXBtKiJuXuzkXSlkifCAkmjxQMIVBTtKHxMqxLijHstzsNeAVHXiuydUivzEVIcVHwtmbdrLjkYkqSSlBgXiZvb",
		@"CrsynXnOQHxYrkFKEsLUzIunFMbZRRhQTnLVpnJUsZrzqsoowkIfOuMhHBowyYPylnDKPAlifJHpFDmNaNpHBYcOTLjORmjiyKKPyxZGGfhkMWIjEJGK",
		@"FFnvCDaCvwHygogUXodjYMAWfYSHHWcTIGOmFFmIbEHLrhoSXQMJKDuSlkYmyLwKxSCiIWqSmYriPqLDXxFYCgQAOWanezehHUDiJRgsUvtKUxtSsqqReKVKvcgCzREIqovBKOddtv",
		@"EmalONDIGHcnfFPseHxOHqNaCmRLPnqgEJurMHQuPyaBijCIfanCobwcrTPxPsPysxllPfYSZifBblkEiBfqUWGNknLRirWKXJyBvgwoNyVHyJzmrVfweatXKtsdiHOYKDaqUnMP",
		@"lQNSQquYXJwSbhPNAGulTCUPzpzMoQFYbOqUywkYbOyDwLODgWdzvgsqySIbKfEvdwhlpRHPMRXPwMVZsSWIXnpiioXQqerMIBFcHWkAcZDtwJliKKiGBucjeeCvfvdzGFF",
		@"MIlYbiEYGNbeKEvHScFbTuhXHmNYyTQwiHxVLyXPpMkRcjLwsptIhYKGnNJxqqFDKiUCWJkHSntoybXYiBfUWIJUQDhBJPtDdZsclKjHAvSMEzlMXaLysWoRaNlgJB",
		@"UsNYeaaBDCEyVObRnfhbfZXNKnXxVoZBmtijIgOEftHBceIaiZJQreOOKBilMvntQYEZKjIrKUKVboGwPkBMDGWUncuJFTVZMiXqPoWqdXVFBcmgW",
		@"OEyBapqdzFVzoDlqpIxCCrkyUtSgAsrevoXwDaeyyKONaiblucWxKsOuuueYiBJQEEQNVYSIFGrpJVWSqqqxCNmbRDzUtdplgCHGmMCypWyiPfQtiUETOCJdxVBWgRHnMPMMsBblWQkSLYaQslZJm",
		@"UoOiFRMHEJAgazCCApsRfPVMbDfcbXMyKAjhLDTQofnhUzYrLAirMbOHYkysjsOMnAGLKlofPFJpcRqzmwTtUnqVikKEQWSeVWnrdCVECnuxLWUJDIbKgwnebJAXuvBGluJRaInYnmcapgB",
		@"gXAyQgphwvYSpkaosApGveivNiPnmBEezFrllDiiRjgEcxrribmCZMQdifSOYuTauaIpVbBuiNfFTgPemzCPauIOCZHLBGhACPwKKXmMwsESOHuGWxyKjTelN",
	];
	return JeKHHyVALQ;
}

- (nonnull NSDictionary *)jiEyeNwghISnsMwzNy :(nonnull NSString *)TMMkyAdcaiFt {
	NSDictionary *wwLiemspCjNP = @{
		@"KKHiKXDuhAlQz": @"gfNfEZGFLwJhAegwZmkWVmzSpuebLYQXNKPLmgceDGmMXgXwIIewizHEZntNoZSFBOMXsJSUiAfVmVgiWZLaTgHNZKdfKzEDKqMf",
		@"LsxFcUCgQEXrrSPU": @"zXwwzmexErpjIGCiJkZMLHPChACVBnObjMSfpEHETtHPPithPrgblUEgKMuoSuZefffPIrlmqvHoAEsAgJlFNNnliyBqFagTxbugHscEUjjVwxPAdkekAEi",
		@"AlKTEbpYYLvCibDleeH": @"rvNuiWlmdRIaOBSPBSiGxzoRVROKAGloyeVZuwVPOxWhiCQhOmLaztmUYcEAYrHcsQrjEFnQmHOoyPUJbBqDOTRZtSTTLDWjSZQpSGA",
		@"FeaihLTdPZ": @"qEiQErtSKwMQvIhoLaaxmGkEaiNBtHPWISlEPgWAEkrvZGMCzSVrftwfYasUENCcODuTQerhUQSiVMTOWeuKDWjDaHbtvqAJjnTBMeWiiFhUy",
		@"VthSqApUsIBSf": @"GUvaoaenAOSgMQfjDBdRWJmKNBJsDCIAgJbAaalcKKNMqpOZoqgPUdbeOmRQJUSsubDHZAdcHMLGRMUjzkfHLqnhlYYXklWHpJuaUJynpurTQxHqVSzSfOPnzpmQBT",
		@"XDZDTtpGcHortp": @"aHBrOMRyLIFfWRemZhUrPxEsNzOAtMnavFRjbJjcXXWdiMIfzHFFWABqgILuQLnhDZANqeaUmHZiRghGojsszqPOufTuWCXaMMVmWskfsEvSL",
		@"BudwhiGepmSO": @"mUPBBbxEJWUwurKHpPErKGJXkxyMBkBXrzJIXXxsuqEiWYHzcvOfHkHZBlpabCRQeWkJZDbTpPxUvOvSaUxXnCNiJcIMGqeIpPAKfKiVMXCLFU",
		@"baxixSplULAXkG": @"PuNjOwKMuUQGfDlhkKxkdUyWqSCTTGEjCBoCKFjlvFUTuswdoVmpDsSfdXQEfthhPojCjzNjWSlBPhezbtdGoHztPyCqaWvsYHZUYRPFXBWHSqjpyCMuonXCEABaHPudXMDWoFZrwAimY",
		@"gpHhMYBKgEDTLgAKi": @"muxYAsSBLxNvJprsJsArvszCcQYypFrdGdJQPHsuKRjqZYfXAbBqxHOKQbadkRkJwqCfoKXAjZrJCZIvFWxclDsRkBnsNaEijYBNgDKtdsZKeiPmHXsCcQiXJT",
		@"fAHeLCfsbDtpvmyxQKI": @"QZFhKrsjIqSubExWVeomkUhQJMywjdGevZfXwcBErNxYjjKFuBBknoygLfZDEJfEIHlagzeJnXhNbMboVcwudjRnXPGCpWHXsrvAMoKczLNFxdnIaKkPiuNjYDClM",
		@"bmafUOaqOwAAgBPs": @"ENxuRFaWmUdTicVJCfLEPvlZosqScbfmEaUweDJtvKXceLVXbAnMrRfHdaxdkhurVzdTunbpemRhLGlySHepcEUwnqcngbmoOMXaazcYziWnkHprzoxSjjOVXPetCIAePBacIS",
		@"KLulCSStvKAiKy": @"QXQaIuqJWQOwaYimywlnRizMtpYzpAoJglIdMOAQUnQctyKlgYRNxchcfqBjgWQueLGrKYDHSkRdmbOHYObshgEgKpbfslHLgFafGbqDVehIHGocSpYbuBueTzlNTzNi",
	};
	return wwLiemspCjNP;
}

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    
    //设置buttonBarView属性 选中文字变大 文字颜色
    [self setButtonBarView];
    
    self.title = @"审核中心";
}


- (void) setButtonBarView
{
    self.isProgressiveIndicator = YES;
    
    self.changeCurrentIndexProgressiveBlock = ^void(XLButtonBarViewCell *oldCell, XLButtonBarViewCell *newCell, CGFloat progressPercentage, BOOL changeCurrentIndex, BOOL animated){
        if (changeCurrentIndex) {
            [oldCell.label setTextColor:[UIColor grayColor]];
            [newCell.label setTextColor:GreenColor];
            
            if (animated) {
                [UIView animateWithDuration:0.1
                                 animations:^(){
                                     oldCell.label.font = [UIFont systemFontOfSize:14];
                                     newCell.label.font = [UIFont systemFontOfSize:14];
                                     
                                 }
                                 completion:nil];
            }
            else{
                oldCell.label.font = [UIFont systemFontOfSize:14];
                newCell.label.font = [UIFont systemFontOfSize:14];
            }
        }
    };
}

-(NSArray *)childViewControllersForPagerTabStripViewController:(XLPagerTabStripViewController *)pagerTabStripViewController
{
    self.buttonBarView.backgroundColor = [UIColor whiteColor];
    self.buttonBarView.shouldCellsFillAvailableWidth = YES;
    
    NSMutableArray *childVcArray = [NSMutableArray array];
    
    ExamineNoReadController *noread = [[ExamineNoReadController alloc] init];
    [childVcArray addObject:noread];
    
    ExamineReadController *read = [[ExamineReadController alloc] init];
    [childVcArray addObject:read];
    
    return childVcArray;
}

@end
