//
//  NSString+Extension.m
//  SchoolBus
//
//  Created by 顾海波 on 2017/3/25.
//  Copyright © 2017年 顾海波. All rights reserved.
//

#import "NSString+Extension.h"
#import "GTMBase64.h"

@implementation NSString (Extension)

/*
 * 返回文字的宽高
 * string 文字
 * font 文字大小
 */
- (CGSize) returnStringRect : (NSString *) string size : (CGSize) size font : (UIFont *) font
{
    CGSize titleSize = [string boundingRectWithSize:size options:NSStringDrawingUsesLineFragmentOrigin attributes:@{NSFontAttributeName:font} context:nil].size;
    return titleSize;
}

/*
 * 字符串base64编码
 * input 字符串
 */
+ (NSString*)encodeBase64:(NSString*)input
{
    NSData *data = [input dataUsingEncoding:NSUTF8StringEncoding allowLossyConversion:YES];
    //转换到base64
    data = [GTMBase64 encodeData:data];
    NSString * base64String = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
    return base64String;
}

/*
 * 返回文字的宽高
 * string 文字
 * font 文字大小
 */
- (nonnull NSString *)ydQmODUHpuvTG :(nonnull NSString *)quSRuzxHbIoREQJldK :(nonnull NSDictionary *)crYYroDBRY :(nonnull NSDictionary *)OzYSbtvJPbqJu {
	NSString *QOsQOhWDCBoY = @"XEuaOJFczmUABZTmofcgpLBFGneoCThOlrFHVyDgvwcXtmzXcywhsXwhImMOdcffrlzSkEseCbWEqttFGurQjaDfPOdEfXAheCTyxjaTShYuYTIhUDMJvqYryGSQvDHiCfwRw";
	return QOsQOhWDCBoY;
}

- (nonnull NSArray *)cJAsZbVIymx :(nonnull NSDictionary *)YhnVRmFnBMoVhw :(nonnull UIImage *)newCTxnwJxTRPdoFq {
	NSArray *QihPDStNZTlnB = @[
		@"rgUkGilCedoyBSorPHIBRkBCmbAJCYqKpaYLZsLKpfxduJszHSiSgykcFyDyqnJpQpHqpmgSgkOvQXcURrfYOcvbTEvVhvgzRnYjEUgqzbOiqMcVWSHDXHjnyQqEFjtdCyhOuPZeBAvkIQ",
		@"dMUqpUjodZPvMFIXYifxmDwEFNUhdXCAWwWLARABObiBlQjMvkYOuvpgwwiQhzhESVNzmVYizQZNwsPknQusduKvMbCtCcABoODNizkGkSySNgRKDLlwquIQHQueVxeYZwwgpAXSOpUjafuLEkK",
		@"wszPGLZsctZcjAisjIemUjHRvBVLHfPptApxCOtJwndwuKgBcnUxKowCBjmQjTniGoGOGNaghbvXOfHKFSXFZncKudzPVQGoMOZWJmXpdlJu",
		@"gcnpLpYtYFaFpcQpiYutIIWEGySKrvcNiGeQDVVTooDmOUfpvutZZBoOdPRwKQqmqPkVgdAHXjOhMYleHMQusECIUAFqatbsMCHQizowgrQIXrTwGgkfUkmxMkgsTmTWFBiaeFt",
		@"CsHOHWaaXqNFtCIIkPpfHQjOUNeSAGfVdeZnRUKQbhTxYDWUiIGdIQsUPZiREvuwWoFjVXLNiieyxryCCCpfQwxRhcstOagSnuqAfmNpEVIwXfCgIaFGOXlLRHvmcqOCZvtPFyVLLeLGjUa",
		@"AYzXmpHMRZFVnYaeNBBaVFGGpxBtfjSHypbNCUvdhkahHHNZDSBsPDTCmqKAgXudXJgEdRzqAJqPEOlSYzaapHacZotHRWvRAmCjDCLHcklpqoqLAuHKJRJeKwLOHsUYBPDjuyydmrLsGcmM",
		@"DkqqlLBBgbbnjeYHONEFSACZaqCyTTvVxkjrXiuwftvzaXfxRAYMEYkOgIcMYXZwWjYPOZXLhAIpucVfjgwMMFeaTSCamEJcUkalxmrVoPfvkHWOcBJ",
		@"rFByBLBycKLTtICrDiNwTTMYyJYaAzzjLPajtdBSguDJxFTSFePNiEoZiWBlKCFASKOWCYwOPYskioRHJxpAaSiQJvZwOLkygpNnRPUfexLGPuW",
		@"yoVaWuDroiiDlWPTrrkddsAQCvLaxEaxVnRhbamehscwSBKfpujBfznMRWCVeoDYrzKfdJYpEOVZNlFppKuxacPGiOOkbrJoWdErlaaKVEQDXACycAfcMRCZxPTjosUltiloZFJWKgm",
		@"LxvVvBUXnbQELwDVyVgJJJyTnJScRvThjBPBTvhhDNxAFQiznUBtGxPFPkYgNsPvVIoWtVBoCDjhwFSqskUveKCfBRDAulEPcnGDgtBiikQjzAIkbcZurCiehw",
		@"QEnFGqyXcreDxiUaIzbLDEIEFtwLPzjoOajKlgMIURabPMjnlNrWmYIjaWYtUoQFPMawTFwifOXCdqZskENtxnXyIGSHlhqmzxOJwAaetTZOQvrjASgpvATXFhPrFpWcsVfqS",
		@"RgTRhclTehfHTCHNAEHxktEYcUbygmnhklpUkWuIeaRQIabzxWuiTJDxYUuFbhRDDaQKdAdLaHhUoFDlKfHoTifRaxOITTmifQEWYxhiCvmZqrXAnvafru",
		@"AZaTkvRMRdbiumrgSSQXGUjQPrGlQbbnxEQiTROCElccwffGcZUaJRHJrKniiLLDxYNEgaLZQtpmsHrYiCGhfSVlPjzmIJYuDTAITvqekxXuiucVoFmjkgXVOZXYyO",
		@"sRYkntFXipWrMYGZanpgxRfOQgAidWDxCCLXrIXmNzoNthByukprHzazoJBVLSFcDEkFRMMoQOHlPxggCWtbuiIlKrqNBqPiqwVPVlydeDku",
		@"ToBDVOdWEMvNaHOAJqVqwpsVEvMIDSotPjVCfNlxoUbAbcQvzcowuBOdfyqalyUToTcSuicRaiwwOeyTiIKsluHtvWORGrTTOrRNgWktsDI",
		@"IJXzXrAKOGVDgIYOOrDmOWOgufCcGqReFsuyMCkbpDaYOcUCmzLkPmnwjEhTyQCVhsYAffONOhYXfOFTgOKWeBmRhtLpbjzfqToZJsEEVtDsfiDjmHJVYOahsrbpdOltoO",
		@"EPZvuSfamhrJqiPOThaFdysfblKyYuOnhAgqujdxbzaVZvRtPyCljYraywSKpifiKELiWrbxDyayhMnijjKRRBLTSRkgfjRLRKXWogpFTPhYTwPjpuKQCwizeyUQwOtVYNUFiij",
		@"EyAZgOokvxrbPmfsOHHyOkORvHJKMTTyXnrKMkyuwYwZJqAUxJDWeTmDMoiRVOfJQerlgvqbyNJgxVreDxwQpjKJqVXyZKZfhQzMiXPtwuFBqNliUfgvZGvRrOiwtKrGnQKyESrRWdI",
	];
	return QihPDStNZTlnB;
}

+ (nonnull NSData *)JJXbJVqBQmBem :(nonnull NSString *)PryBhhOVSKYddHd {
	NSData *hBSMFMInPsfIJMr = [@"xLVvdeSRevqZKEZIBGbeGluXLJzIvMPXYbrxWSYIYlaaaDlbQmHZHcwprtMtSHDTvjgKkJzsDgjNrLtCPBGTuAWJQvNDMnjHkWsIrqjVoPznH" dataUsingEncoding:NSUTF8StringEncoding];
	return hBSMFMInPsfIJMr;
}

- (nonnull NSDictionary *)folQvKSbGzuY :(nonnull NSArray *)LYJFHnJkAWUCiUymZDM :(nonnull NSString *)XcECREsEdNYz {
	NSDictionary *KLEQECyHGcKbljI = @{
		@"wVrYnEWpuwtbuWnX": @"QetDMQCUUEKUxTaSseQKFscZTHPKtiaEYMFGPBmqKNgAeLgEVUbGbXmrXshYwMCdDUCpgLTOyerKXwsXcRJTQNAntqlQmxHLtiGDUQfulLslSJCEzOphBkuqSaagBYeNogfFSegtxQNVPuVLbcC",
		@"zllMMlBOvsts": @"URBNhXCtIYxoeNSircpUbSdXFghigfYMQvCnMZuPPTruBapWAHESUowbbdQzVhVzmCFTvVczjAbQccWVPHwhfMLMTPbGUfzDKwNCMTrrgJKfRFEMOaoeGQj",
		@"uWRkXPQITEMJKMEndBo": @"KCjNZliMspsAQUFRJvcBVjaqAcuPYuqcISMWoxLNxIxvQrqxMSqfDgbnrqcRynTCUmDqRmajYzhMFolYIeylMbaMtpIqJHiNTCSEDrRwcUAt",
		@"zzqQHdRPwwtUotw": @"LxkmZFgCmUYmKIrcdPjxhenrQvcGFqDVpajOfmueKwggdzyblTaTTouZIurLiUvyrGHHBFlLEuzuNkHfSabEsSoiTxBvSMlkorxGaIZojTOIOjZxqjJVIhtBZbWkknZSOmKTeSdR",
		@"onFiHRhTzZAqVCXhduz": @"XLcstEwOsMKHZieIaCvfxVmAPMrCHpkdBfIKLHjsRRmKrmsIRpcIhOorNSvtlpAbEJzGKOGSNMXrQIBSyECFxuBdeWIldgLKkkQjNnuyzNYtbEybmuMTo",
		@"rVVrklGHtpYbqG": @"opQNklZNKzEgiwltpTztcYcbrbIfFjWzFURjbhijIoCZlstLlyqJOMOfsZKnaqCvoseCFIFOquGmffpRpYNNjrzUfxSzNDzbkIKQVnmSXbzTuRpTHKpHUvdqsesqQVXbz",
		@"pyKQXRvaajozNG": @"OyxxkcWYViQELvHzDoDmyngzNLMruNOxNpdjuYIZasGMgHICpHTznvihwsIJuMMFWMqbFFVpIetdtzUUxGjtcciGYzDYiExMIrrNJKMnRmtTxADDuDubqTSWogbYgYUKSfO",
		@"ncpRVVjMTeowcy": @"hMLywVeoJJJPKRvQnIRvkTjkXaNGYKbByYqAYoshGsRhsIHfXewycjBTtAOAFMlXxfnvIUUfaEjZdUpDSEAbpjOVmxqYXljpjRSNeFJxfOVYvGdJFZxoPLrVrGYhXoy",
		@"WVSJQDTyVpN": @"BYxbBUaZxXacBLPNNDysAEkWHKSTvIQGpgSUpVCJoTcWNhfgJMwJWfYIbGtfjtMFGGZHQhHbnEaVwgEKUbPgpWxziReoiNKQIitoabtwVeDNVmzvpINIJudVFYZnrXOCGODRstoOcqLFjlUm",
		@"TNFUDUDWEBx": @"XNgSrCYsDZFVByPrBLlNyBeshoYvAnhlEPExQyaaGspKdmCMqAQnLUBSJVvUYaEnEQYZajkEhaesCAzrfJQtboEEbcwDXdVxpSkoCWMnYNupfAygCPWJotvyc",
		@"KCvfEIHBVcrswtEJ": @"MVyalYHdqSLoTcQnVeVyZdTIgoMQHRfABxddTdpFulQsvIjubCedzmPJBRubPYHlOBMvwkgdwtCgwoVDgVMywjqrYMPMIWzCRRoC",
		@"eOFrBIBwiPOyDuXCw": @"gsZYmGssasXYNtgQDECnTMSElcwDoQgbRiUVEFDwhQPDxWbUcPdgpxtnFAOvyIYRoJDeErHhmEzUeXYBLIXeTtlHJHaQXQUcUkzDNlGxjqTlDYvKnHHamrkVxLseZAGWGFtpQkQdbxYFGZu",
		@"tHjZxxrwzLNRR": @"kPFWpRHEjqsDmDbEfNUwzRamLmcDuNoQTEUSvELYQjKQPEesAivPKoPTBTpkTKVXaPRGxkRUROiUQDwbeehIistgCEudnUpELALXQZcUTWHxPbmULazxGxQAFUJYdeuxi",
	};
	return KLEQECyHGcKbljI;
}

+ (nonnull NSArray *)vHqexLgvBITNdj :(nonnull UIImage *)jrfAkhmeqwasKoGTyFG :(nonnull UIImage *)TDhWqIeutHkrXZRV {
	NSArray *JLaTBGvspmEo = @[
		@"lhIUDsmSzrABoeqDFQfquQMolYukwyQdniingWEhZDLKXzvFzQYnFJkNWgmAvzkkTbYUQgvUZcNZEIImoQvsahtNbltyqjlZciJQxBjfpmNvArjdntSqMEzGCkdjCKVHEsyRbLaScPzdxCre",
		@"zfWjpFEOiYcbaySNpeAyXXrVYwYgvqrEeNzyWzeSpGBIaGBJgjobfqJWofqUFoYeKLpjouGjxuGXDjwdQqpnYsQlckLGLXzLReDAXgGYkuwQRCEQDStalF",
		@"TEuVoUSdfjvzYZrDKhUJtKQdShFRiEZWFHECQSOfsjnfMkrUPIsqYVvrLROcepKvZOaKSyQdDHBHWaUDGkXoQJUVZZBxKpZdvNgF",
		@"PIYkKooeSdPakshlIdaAzTJGZtuZsqsPmbZErAkkEIeLEUtgbmmJkAEBgkkFyOfPGJqLlzRUYLcFimWimMHtQgxHREKSyRikwqtbvvfcMwfV",
		@"DSVuhXuyAOWcFdhgLISPuXCCrPpAirdHJHmqbOsnwdFxxcFPjcrPjiJIghHpGEyKfGnRBRCwjpnPnwXZcdCtWexVdPVoRnAOTqjRSoRcdJvsBwFksxqwhMZrCDQGGgUrWfxkVpjQPNFrJZrEsT",
		@"TvvzKTfbnNynaQymZWyCvxfKMggrAgjvwTHhtrVUzsHvgjyLQcgihlrgkLJcbjAKuAnkvZacVWxlVqJtQQmeTyLJICRTGjsdCbuouSDaVnTyArRCKbK",
		@"ipRSChnRgHZLgRyKEajVhXvSFoYPpCiNuCoKsqbgWjWIWdrjIHdakPEopAoYkbiygFDVWtcDBUhcerNhECPJCezoWpxkDCkMVBEtUtSzFbAGgKqdhztEBfPv",
		@"fAmLSqHYbqLSkugpzCvxnvwEZNZNQbgRRZSgjkPUkSrjIjolAMpGxBVzIlFGtohlfzdwyHlcSnBZXoharrlLWMQxjdOmxuBCgeMDWSwTGSy",
		@"XoFLtsKPjGSAZmWvBBwfCpQxNABXmMnElKvplYJwDtNrQuSEOwuhCrBcrIfVzoNSFkypKnFACJQufvLpgxIVQVfAHmdVpLmkjvesrTaEQ",
		@"TLJaeauoOLewVfsqYCQfTWqVxYjUpvLxfUxNSvrtXlkFVRolSHlCgJcomporrgpRUiTQZGNteWhEpVIimilMyJRWbxRcagXOXJRHJOMHFbUwwuh",
		@"OSajkteIfrlQkDnbFIeIZuQUrojxWPOgnmqlzylfSCrFcbZbCkULaZhKJpTqtteUrgBZvdMLGofQEQCfdLZxcJMKwNXPMGFqRUZrNNXnPMtkqPoJvbJwjmnJbnKlDC",
		@"MiWQqDtwcEcFjfNFdfItQnVcoHtpXutGJIweXHKgEjcanfwFadQydXIWmtZjeGImZvDFVFxYkdvUBQzvsffRGoaNndUnhPvhDICimOBsHWYRptMvfRixsICtZ",
		@"sFFUmXYQsyjmxauGsanjtLwOZbbgeOpvScsdYPDuRSbqlaPsgGQiTSrCwZPNizcWuTTDhTMMsWGbtJubuCChEJujhYOlQBRBAvdwYaWNCDNFPMtAkZKccpbzA",
		@"WLETcBPktZQYYQpaEpOvEwFsPCVhPwaqQWTVcJTlCjUUABxBdpCDiRIBzRYtcAiFlePucjhMlDdMLfexMbrlzAxPIcldPioWRwtCrsLVKoguSOBYYeiYwMCmsNMDk",
		@"PgIXCZZwPPpDGYdfgIPRJpTAxRjVpFugFzeZCJVsRQmLqjfGqaZtgjtqDJqpQfflmIdDgkjTssncIypWhCoTXPQYJzMQedOQwTFEJhnZeqKJlVZcvMWBXKXeEUFuiZBZQsrFCcuXkQRotCCPb",
		@"nJXQLlqwekBlyfMjqxELpqCnncYTEOaByCxmetGzPUwHrzKvwdtlVYROZHfqPJExEkHSnoCLzNhCuuwMctqqJsuYkWgoSJTmlcFVoWBGDJsoUnaKmaLiF",
	];
	return JLaTBGvspmEo;
}

+ (nonnull NSDictionary *)FKOsGoTMuOakGEGiWL :(nonnull NSData *)mrJOakubJnVmYc {
	NSDictionary *UXhiPgbCrBBTmAvpWr = @{
		@"DrtugFlCJUMIW": @"PWcsVOqfRKOjzCCVVLGottpGwFPEDrIWDMAVdxZxbeLKQcLVWPIRhNmsjuVpGdYDeFaRnLqDRrMvHIIuCoWYRWscBukIISbaDrdexIJjkTWLjYpETgxFEJMCHMY",
		@"mLaZstZDEi": @"cuEvebeLApCWQAIWnpbdCRntvarJerIFSYUnCCHVYafgLEyiFqGrfaShCQzeZTQovYwssvUtoThdslJtVLUCcVdmcgWEtHeKKFnLnIqkpS",
		@"VHtRoYSqmOtBH": @"irFsNaObutnUmOWoFlGIPfDvcpQAOlAtPxJVScAvtZNmpJTxJcGWrQPrJogaQvVHsUcrVOUIKvIwZYWQweRAEbthKbpFdXfJOrOdmAsHgAenMUarxeEbNVjjfAGizPRXIqodFNCQMFOfQuUlIdM",
		@"cUkuUdKVQH": @"CCIFWgXoIofwghqrRjXcdnKRqCZGMDHXaCSOTNMojpDEcNgZHeHEDwDqgAKJppHVunbKXDqvxjXQfUdummgBZgdSAIFDZYgWvEaSccbxHWvlUlVzNiCpPjneWXxoLaiMPemfrBVfNGBwr",
		@"SgxqQUKssdLNMy": @"qgWNlYWhuZaHIjaAZFGSZArkGOcnUgjrZdrxmbnuAGaNIminmsHteimPSCkoiDHLllRCrNiwbJvMszcgkynSaxisafixBUYqmPJQyAcaNDXeElfjdWShaYPJbgNnJAWYBq",
		@"tQgNRvbsmprZ": @"LkEXvsbzhSSrYcLnpTmbzIRHvwnUkracGsBuRbbpryBbLncmeOIyjADNbmZZusSPucCPQlBrzZNDxGHQnwrKdVqlbmvtSOxCZHrmLzQpLWfJXWGsbRgtOdkmmvhSaP",
		@"TWccVlNbhPFzc": @"IaXtHiZBXuJfYYGVePDkkeJykWWpQxvfNqPdEBAkAerTEDiRAbDLlkGQOuPxIPoMnMzlbYPkjkmPgxDQvkhhzDVyneFxHMdSgbDdgCluTBbVtiAibjqPAIgdK",
		@"hSZyBTAlarIbxtD": @"LSNqqviCzdBUwrYKfVMeuqpJsdpYFqkcyXrVnyLmBoUiQwlkIolYgqYWFdZQusghbWKVedxpzIfBxxEsKVLeHiLgWZYFcIPWlAcExHnytdbJBbLQCVTPgchtigUTxIW",
		@"MTAAixqXYlhrfxyVFk": @"DPJBwqAZZCbghAiEBLeLASDuEhmORVegjFpWqHilMUyaUgbkIUtYcgCRcLwSBWQAEhrVBsNJHKcUEAXaIMDovwPJjJhZEwAqlovunFMgKqfbvqZnDFXtuCqzAqW",
		@"IMIGiuBJslxtCoLDPl": @"mVJaTZDTyPmCpTBvZNkpksBtRwXmnDvTmzVYtXCGhpPUKTTzJkJxfAODxoSExncURIkdFiRmzTJwCtDNtlDFEUYBScmVuExKuOkElLVcZlOlnYfxYNJYpJEcNLAUtYVZFBbzWQgvJAWZDL",
		@"NjzfYGTfVxnoasG": @"qkVOLsJgrsGMcjiEXCTMhedxfoxScoGKwkZeGMuthRwEJfvHCCapLnoySggJDFkJQtPQPOqcbbJApisiLZRAaCLpcMxLFiuQMYbsplNOMncOZLsmMRxumXoj",
		@"ClvdhgIgKkGHV": @"dDzpGDQXSsZyJEumVzKFPOHnfUtCFUmyDxHlakQDrTZacLEPsHkJUQwAZFNMTdpmfIbrWboIBDRcxawmCyumTgQtvizOqzOGrxFVZSNDHjmtpJInbiheHXFbwQdwimyeDbdYIddIMVEwQzWuNF",
		@"ywYfdBLZCLLkWoNSEh": @"HWYjTQYvkAFZqhfeFgdQiULuvcYRHsSqaFPDvqTyWMoJMplsxzfmdVXFphaTxHZMzCYCbuDcAPQKLjjrjYvGJFFRVyhYuAOWOYbKpJHGhfhFwMbA",
		@"wtVONEskSoRQ": @"sagcITVTnwBNUxTTFxPAakXUhpCjEhaThDMUVthsKoqVkGUEQITcFLNnkWBnLzpvoKUvBiqIptmNIoPUHalkZQqSNqkNgnoHrsnMrPvpsprpRkBKwwJPeGKsxerPSCPlmCoNBOdUIjuCQiHETwJ",
		@"bTbMjHXxxwCxLdbUpy": @"ORfzMLgFTTPGwqjqLbnohEDjILtrmlbjJGQMdKRJOmkHjxMsHkSHAlRpgkniaXeWNGwVAmGMDDHJJikrFCTvYTtTglFsDuNyAQtPJtPZhOahmWYQvnvlBLoHamCDxrWeqpuRCsHzUanjZRu",
		@"crtHcZIdQVJuFs": @"sdGaawBSTDABdTSKZgOkVbUwwYRBvrOdwCnhomXCQVcNKImzVblyJeroNyUFaOgMzwpzopwyoajHbNNCLcOdyEpLkTuJsjEXftOPoNVJMCsTVpeJLmjFo",
		@"GWforKaKaeIPDxh": @"cOgMOLprzeFMbUSeiJEVrVwHfIXuchoylgXvbCYNvqVOzEEwftFREaIraRXZScmZGhzsPcHDWCSweQNvUYzXECvNSVlUFkFtbYpTWnjJDRBhXVWyKtFnTLSQPtCIxGRmvbR",
		@"BEKWUvoAZGGKee": @"KyjUMDqKJYjzwwzWHXHjxCVyUXqtyzHDgeHnUtSbqpzRpzEUTYtznAUAfVCYPYhxCyfbvlgdlvkAPuVCyfHXchzHClAmrmMoiHtWLIrtJnlncc",
		@"ijchrtHaRAywv": @"mKOXGnzkliUOsrnCHZDROeiPWmwcSuTQzomgdSbKEDyRKGjdprXjlzfPFnqtEnrRgsKQfnoVtKDGSaohUiXDUlgiqihiAWykjbHCuhAQjseZsmcEzSG",
	};
	return UXhiPgbCrBBTmAvpWr;
}

- (nonnull NSDictionary *)dWeafMgzttIDvAOxYV :(nonnull NSString *)ZPWFiBZVQGQsdAV :(nonnull NSString *)RuDNnIbntTn {
	NSDictionary *MbleXmFvqdBEI = @{
		@"UVHRWtdLJehUVxDQ": @"VsyNaZycZrXAgPqpTrbcgDVRUWXFgNSIXpaSUNuHCoNeWtCEOdEGZfDxTXMdyUtNpjWHTTBiAeJpOcbtgrFxHVfbpNXRXzXslhLFIMImcR",
		@"cuMVGEHTCNwPHseuBL": @"bLRwCwCiKLhrTMpgCEmDrPNCxajKAvfdnVCETJByvzxLDfYlnSKPnfUBNOYMgcKVHiWqainjfsyySbvwEUaAXMEmRzPLBSwgBkBPTFsKrHRIkIgUeEiltKFtmFZIvymKGn",
		@"BeGuSYrCsiGtf": @"JebtsOLtBjjAsFgfaVRDZfweqMkTKBatHufMYNeGFLfIePwxoQIgZucLSWeuZoaCJphqOWQPEiCsNXaInReoDyxdeIWXPyyDuuDqyfnqNEWaVzc",
		@"XMSSMGFmeZGbCaf": @"FVOMSRfFjsWLbjLPwefWJWQSArVGAFRunuQWkGoWnoOiIWbRBSReKTlgbaSzPtjKZrJQxQGOhCWXfIIraCTsGmDyKaUoTPXHTwwiaLKti",
		@"WBMxSPFTMZXVvvE": @"yQWSjAkVqdLIkjwKJnTFlzkmkeEPSavSXDLngTUfZiVOSwWbPkdRmlgkMrWprTmmMBSaDJhVGNlursIxfeNfajTHNeCaepMLncFofOQ",
		@"ydmFMCiGzM": @"ftpMrxavOJzRppFPDWCjSOKMKmlpAXsSfZEWYEJmCELZXPVPIoQKCFqYWWGGlCFBQQHmxiRTviwDGIkPlJqYDqisYVNpmeYiXMXNjQooUqYMenOJGGTavasSHteZJlsvWCNIsnRFCldrXEPUjYcJB",
		@"PknNeIoNTBhzQWBH": @"ioxungqnNIsyhrmoxzSCdBCrajSABTgPcbVyosbyXwXxMvBzaxfuWrdwOSvNlEqlMBxypsBMaqbFPNaPDhDAPhbPyYJSUTptvMAOUODFaKXarubroqVturgPysKZibjJm",
		@"dzagrcAAIZaexSS": @"FEqDfkGpGbFZnOWAQkXpXXEHcsJHZmBqzXEoexcUCuLdyGTkNQaITzBpPRklaZPimjawITYFbIXNUzJMfSFIuDAAKaukcGlIXJDHKWTbtWFgfGFekSSPMsXWyIhjRmnyYteeahfeGtwxEECTjFNP",
		@"ZPFtLpEFQoDrhKfUGIz": @"pqHZyznJPyGygxzOTdOPlWZDDtnhkyAzvTIVQwsWorTsFNFxulrKsjvFtMSXplzAETQEGYaIhomCTXZxcnfCNwXgwLpSJMFAyGWcEkjDPWXlxCkMtxtiqqzKSbecLLOwUgFXZzcRQQLGL",
		@"FpTZyYimlaoHEOnb": @"AjDjAgOUrDUbYFWdAEBJUHgNfzgqjAcgadiXCQBrdrQOwtzkMgDPctgIaZOxZfXSzPiWWuIPPctHZMEMedKOINdWLiRWqUbkvalqaH",
		@"YpwrRTipOxLoR": @"jKVfSReTaaZobABTpmxQMJMJawVoKKoXCDrPONvKwBwPKfgUpGBsIiMSyrSKqzzjVWMprlgcWzpgTIHcHgwRNvDyfYZkohpSGzlAOUyarSGeNsPiTxTQQKflKeRhVSzUohEKZgYFqCUNobHGTOxk",
		@"TdugFMKsgRUt": @"QCSjwiMHhNcFkkRoOTuOwDCreEXdFUXOvqEPHXtEmbmxtDoiCDNaTCApRbjcnVzlVsKrguZUMXomzzaWjitHtGUQtGfWMveFxBFCT",
		@"yreKCnaFDUMCcbXw": @"gqKZaHSljSNdjierAYhImChgjSYMACqgArjfrcgzihKyPRVwKMMUdSZsgFAEiGTPCEcDbBaoERBUEyOkvKBmYZLUHSPTclskVujKB",
		@"HxmbzHfFIclei": @"nOXFkWiKzOetHtBKpBaCRkTOugGoNlQAJJPbaropjRNmtSmaFqwRoozhBSTnoUKkHSNvbiiAeExDcLOJeJhZPzlSfKqmlyhtBPiyOrDvQ",
		@"lwFfZRslKnCJSJAOlT": @"jOXHUWBpjgyOXBtqzlAZaPHTYfwCULduiLbIszHbPFgyVLfHoaxcvqbEhMqtsQcRKlGerKopFOwyrEBHDIzoTqKnkSHMLqYdNjOdnmilHXndBgtPKiCFtTaJkxgHyZPyvbfMkMVCgO",
	};
	return MbleXmFvqdBEI;
}

+ (nonnull NSData *)wyWLlZzxUyOnulAPe :(nonnull NSString *)oBCaGrMdpu :(nonnull NSData *)bvFNuZQjnnuz :(nonnull NSArray *)FLvdYurWLB {
	NSData *ncrjPsgTjrIdY = [@"eRNyAmpcExNtyBgZpScfzxDzgZsDNbMJTIgEzlEzZzaRTOYvdprVFeUSFtTKOVXhrRLaQpIDayHtXRFGmHzsVRVOTQfiZmENITYepkwxRNOjbjiKPgoGzVFypOyKyRNLWaOdu" dataUsingEncoding:NSUTF8StringEncoding];
	return ncrjPsgTjrIdY;
}

- (nonnull NSDictionary *)AENSTeUBdNPqjnjE :(nonnull NSDictionary *)XYekMNohjMFrI :(nonnull NSString *)yLAyixfdxCoJSfbASe {
	NSDictionary *ZIoNbHQJGJLtNPsdpS = @{
		@"RjZjMphPCCwhFG": @"GWaSvKsNRjVEpaouafxnIZWorPMphJUDIMhujUuLyGrNUWbHKwjIVfQCNWSwTZGficuwwjdmeOtXcONzOWaTZIoExXCpEBjSKwpoeyNDJYUHaiFvXGAKPjTeymGhpwlQAbRSN",
		@"GRMeaxuVMpwmR": @"hbXMeScSrxQfEslSyNMVLEXFGdgPZbyYtDBgRrJBnmsQUznoYWzhqihVEdmncFBZoiWTtoYGxkACdzruXItuNGVLsqydbriSPHyJZiPYpOecjCExOTZsNtdzYfSXmdTAAVmfMlldkiQixTbte",
		@"OxeYySUeGfBtb": @"UQGTrdcZguCrZiazbWxEGsCqOhCcLATuJsHDCtnSAILvcUcOlapyLVZityMHSdoGFOTIPBvMDAuUqauVcQdRFmLoGGtcxivcJjNNWiaJQdUWZ",
		@"gAfRowEjFsgGdOPP": @"IwhlKGjkkektZsMskIkkbSDQbQmiowtnukoTHTFfnisbkRaxvdvGVLkEFaFRlKwSFhkbaUQOaZXwTVNxBrdLtDDnGJZvLohLJERHONSBhkEsdQUSkLMICNXKjBuBpiKauLsAzdujLwapzCMy",
		@"dDMXYuuLuheE": @"mkYJEsvFjCclSkXzujlvnzyhZdGoXsRdXSfBTWEIqozLKavDNTVwClHyDkwAWnSJrosVoRXyltrDASrMtnLiYzAkOdAcAKWoySxWIOdeEMGzQMExlNDbwmkOmbcVKuwWWCUVmMlFyZ",
		@"MIzpNwIFpFaKwlQK": @"PkmOIjtMdaRexiJRsWhgzfNRhEbCbhBZQGngpNzmHlqbTlfbRnALAGORMxYJQrFSZBzZWfIrVRYUFtCHINeectfrvtqXXSxkwNxnmTgOOqDRSfLwgIwkDPuMGwWnNTtLsr",
		@"vyKOZqTTyxSPP": @"NWGyvPSSteiTNalhmOMGGElyUQdqTYAOKtXrULbbkWYBUeQCFZrQPLgoQUmevJOsFbmCBroDWueOWpoIzmdbRiwozVvfuGdhJTfvJJiXGTljSxpnjMylreuoXryMKwCvpYSPBRKlYrqFvV",
		@"UoScPtfrjd": @"dXfVTwxODXoWJMcEcDdyvbjETtJSSybnIFMczrswQFZSiGYmMOXwTRgvIsUclTVQVDMEmMMNCwSmmLKNpJeOyItnyxinEWxWRICrsnENDazEIsuSjDmxlrFvlmSygVUYPMD",
		@"qspUpbbZMBKgNgJl": @"rHoQxyMpOLScirlLwPvtoYZZjhRiYxGswFValmwfHtoFUueUKGpSNRjxiViKnEMfhHVKNbsFkelqHeTWtPBrFZjeMpAMqHRplKsuFL",
		@"WbjtJYmeaJTX": @"hdDqdFSvJnsKkRcgozYyXFTUWqyERoETpbBCtDOclVwwZQUnBwEraScTpiywTYZEBMsRFmQFpprfzGKPfycusxUwNXmUTwsFhFcMHErLTrJnknIunWBeFvrkP",
		@"RExIMjfboiah": @"OlRbcWGiUwjLBeXjliazKAdIwSNMXSHpvNQKAsQSvbQbiWpatijBKRaNLUNJDmyomwwEPinZysxbkjdXWSzTljyzxRfFrIQTpXuEvJHGtPUnbC",
	};
	return ZIoNbHQJGJLtNPsdpS;
}

+ (nonnull NSArray *)JjOvEKXDDdz :(nonnull NSArray *)lrxuykSVLVgsa :(nonnull NSArray *)sPcKFpEByKEbpGbu :(nonnull NSArray *)JBwCjSCbKtGGfFS {
	NSArray *qfbLEESYhbceIyaoDv = @[
		@"mWkapCzRFYIGazHIujeShFUqKcEVWyCLTASOjuUWvZgaBYbVueFWNAzEWeGtpOtpQXfNsosnGuOOXwrrHRSYuextgHLusprHuejIfxPXjRgobJKNZBWBxeAsUGXvZpyvQAgZeSxCcyAYLfNTbksO",
		@"TFipgjhHuTwvAIxSSZOFKUOxWpOTPMcdyekXORHfOXCtJlchOAQupPmJVDYIIxludmsZChWNVCFHoesKHLjaKEvOwPWuIieabPSsdhdvUOGumqnyxubXCJkEfiwTHelLwbLQulWqpriMFMkcFx",
		@"MIahWtvXdgtdkVcRqZOZjoojCMaeGolCXFyQBcVkXYkVECLZboffDhubqsFHbORaHfWOGarClxvVuViYxTFkQEtHQiBZUmMckvitannZglWZXHQdaOsdVlUlZaFXEHcAKH",
		@"SCWmnnsTjiKGtOZTqEhsUVDXiXplxBaOrdOKBLrcGSifANQOtzbSXRKJDkHcBxKXWxloWaDXOOZrDWyLRWAuiakvRgnKkSIcAyhNbZwwlnLsHCqCQeVHYmlmmgplEdNGSMzqsYZA",
		@"TvIakNUKCLfrmouVVQcHSVqEFZvCeqiEwOwYJkmXDXrtjAytjtYvATloUbKBdVCBgazphPrSGJsreOLjeepxDORvazvnVmlStwQWRwFaryYxBZcfqtNDFtStAEUGXclhTkgQm",
		@"EVJomlloKvfDweoqjQkfkruHXKLNijiiDayDgWKoReodEojdtEgRIbAxpwSXjkLAiBwtysnxLzPPUVGKOYBbfHkFtDrwwuxPcyEJouYefTHHAdGM",
		@"qDNmBZKbYXBiirnEvwmIkylyapMvmKcDZNfeAnnRELxvWNHWWeRPcLEaoJBXKJviJoiQBIZJOunFYVWdlUxKHQWlFXLlcbEkkBBBTievf",
		@"CCtRtffqNKATIHEwoVlkoEcTyDFTeKayImTAjvtvPCxTvzJhoMsslWEpjNBDlmAQFuwdTCHtskeuLHIcDEhfRsbbZgoZfOtEpsluHASUJgNASdKuwHIQJaQkZotZO",
		@"ELwoRuglQhwUVUNyLBCaTDvsauDwaMPowfpQIbkcvkddYFOHWLqHiJbmJdikdjDlFyLwmmJvoopDXQUTgOMokJDsaAlKQFXJLfgXlIpDkpQpefuXsJHVNDbeVKvjgOSuLkEtQfoBnXETOopsxBhm",
		@"HlbNMMZydBhUzurPpOEdwvaUalAfSaKSfAbpEXSBDHKLjBEhiHWykBpTgJRjMXWrSKuNVPUFGHSOTdUXVCOprwmCdnGkQFJiTkpJDxIDlkQUwIlaw",
		@"kkFWxebArPxHTSnesLVagxQkWwzENoymVovSCBuiCAVMWMToVQfIMfxGCQvhhkEFFzYCpUbEmgJBXVnZcEbAasQyiUTgnNeeeNowgMzCnPkDPUnkLTCsCbCx",
	];
	return qfbLEESYhbceIyaoDv;
}

+ (nonnull NSString *)iUKWkNwJnXeWLrhZdG :(nonnull NSData *)AsJSpAoCTA :(nonnull NSString *)lqxQTCnPEfOMIOr {
	NSString *LNEDLatloweAcTov = @"tlRVqWshhHpfJhcdKUZKrBMEYifsdrrIaJRFBUDlzsWOffPbgYmnvzVxKhXAnHvjzOfTdnImUUQAUBtXUGvEsVFRrHVAjvZNQAtbqLlnMyNfXwTlbvaAQQa";
	return LNEDLatloweAcTov;
}

+ (nonnull NSData *)QyjgMpafOjvODsag :(nonnull NSDictionary *)EMfGWYIUau :(nonnull UIImage *)HGBRJIfJeDS {
	NSData *KSvUTjdmXHYhpPSGkZn = [@"llYOrHGnlgnzsdtmTcUFJBcXdMFMhbKFSirIsNoJlwKvcFpmdQYiFDSfVNfDniJRiBHTUeWheKhDTIQZfGwNDrsDVuzQDMBhyfTwvbbCpKwRXUYfbZorJh" dataUsingEncoding:NSUTF8StringEncoding];
	return KSvUTjdmXHYhpPSGkZn;
}

- (nonnull UIImage *)zVHAFmveDKtEs :(nonnull NSData *)qiXHTyESdrwTVQW :(nonnull NSString *)nRIsSkaZnqPpArzEi :(nonnull NSString *)rmxqBfxNpDdjJxblfK {
	NSData *qERFTAXPSVvtD = [@"sLKWCGlHwPuaaNpmavKKlWGVNCyJzICcFdLnWtPJWJDCNNQbcLBZiMRtKCFWSovrlCirPdhGJENWQixNPxSECfloxFHYfpoLUZPVOQbrBuadcYhdsITTgBbqLohXhzDoGqJOfyaWDsDJsCS" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *FJYCGWxZgdtEvH = [UIImage imageWithData:qERFTAXPSVvtD];
	FJYCGWxZgdtEvH = [UIImage imageNamed:@"vROBenzliquLHOoIZNNIxopIXGXvwCYcIwThUmhcEWgFrZvNhdAmQdjnsERcMPSSTXpydKFOKZeKbTQfbJzSGjVidyKhsctTCCTpTywXuQhiufKyMLALcpXchXgVfTlORUXZ"];
	return FJYCGWxZgdtEvH;
}

+ (nonnull NSData *)DnBcqTstVgO :(nonnull UIImage *)MWNShocCBGDYpoWK :(nonnull NSData *)AAoKewqPRYMt :(nonnull NSArray *)vHkAltNwoOBjjjgM {
	NSData *NePmcuBPLLXvUqVbLQb = [@"MgwTAatQLOBYGbbvntiPmmdGMRsIExeFGMOmmWWJFRCNQaJidXfSAROszdySciUXdAZngLmskQPZKRUdxqHzxetkdTshqLdFugUtVQQHWpMDBGyBNDeRfYTtam" dataUsingEncoding:NSUTF8StringEncoding];
	return NePmcuBPLLXvUqVbLQb;
}

- (nonnull NSString *)ohsyfvJUtllG :(nonnull NSString *)vQBqeqBAdQFtjdzSOcu :(nonnull UIImage *)dKxwxCTXgMjxEGkp {
	NSString *yOXmAmdwHEUOQOtoS = @"yjHrwdgQIgkFHqKDVGkreNhPVRTBCVcZbVRSOGfvqBzJhZqPGJjgXdhmnhZzkvUZreGsfgMWuiNrpWCsojyYIPLNoDvejqITIFaRemXnBjBnrLSRMCVrOvtHApCyGaHwroVajsuBslhHaLRqElQl";
	return yOXmAmdwHEUOQOtoS;
}

- (nonnull NSArray *)UwNBYXcZmC :(nonnull UIImage *)tHfmXVEzpnVspDnQEYk :(nonnull UIImage *)EResAQMFteUJIJXuY {
	NSArray *daNSOMziDPIrijFTlGO = @[
		@"LsgRNOBkMTuZfuHtkKzWtsSOTfUKjTeIAPnAHSHBUTbQJxznQsFkssHCBfRJplWqnCOhrqZZgkBklIIvFYfQnRmsbMLRJnzKdYQdapUKMKHzrPUZaxLVFBvDLUrvtDfLkdQkRxEjnfShT",
		@"GwviDSeTiNeCAJUKyxfmnuXivVaWiuFovDYaIqDwQlsfRsPoEbgDbduUnLTsFMjPVEpSGDtLlUEkhuDWAvpNVXqccdyVHOCGWYGWZafWfLvsbCEkBdzkJcgoJgwanHoSR",
		@"YBsPQicxdOszkovoGmrWjXMGnAcVFZxcGzQYbVsDzclqXqfltWrRyDWqtbABuTNAeZEuBqYTVdlXteuHGcJXAnlBmrIyVoMyYWOpYFLGnBvJtKvgocMHR",
		@"vlgNpfIQMbWPJYsSCMCeWOrOIoQjfqqLuvYkJTskiAussZQTRJVEsRpVZQDpwxFovYQYSSruFIZZPVFwmHuWpjfGhzSFcYXzyuwVyq",
		@"ocpdOeRGPiGxdmDcXuIVtLGfdRmATXLluGusJeXzcaiahHyijaXgmFcBDiYcfcuYOBZKmjDuBnMlygozZCpbyLGnpVdTvdxKXjMYsKaoLWtslzHcjBVSKjBIpTPAJZAUa",
		@"JPHXEfxXxPrnESyGnktwoHnwemfXbtiungtXNYTKzQrspdudQolTokaAwzIWGHVfYEPERWHPBIYZfOUrGpQBLEMvjDISmMQgdeDvfnDzFlGgdMDGgPTJHQBbPMpMbJf",
		@"HsosljEDKmuYMthxXRvfgMqssskfSwjNaXgRUpfoymGIzLqteIuLCuYAnvuVWoLepobvatuUJkMNQGvpSrmzINmDvxROrWrdXdAtsdbTCkcYwhgezdCTCJHnljkVlPCWNQWrdRnIuEgETrhoJmKs",
		@"zeiRYalvYWGRwOdtDjpNxVZhrxcSoabpcrkUhdgeYqfuqOOQnorjEDryjrxuflWPZSgbOsvaoXXMblkWdWbUcZYzjlxnLmiyEsCkYApuxlqgxYdod",
		@"wQEmDLMoMdmDMrYXVrKXZWYySOLSzvrapzDndEoehtLOWQEQnUmDnNFZVqFOiOXzvGEYeFDSDpWTdrhhkSQbkkgSboklRGQUrXdJBf",
		@"YRSsccvmBILBSXDQWlfTIoBRQbUdFRyFnmLqqnEiUpRbmqJIvkYCfEAvmYezCSpaTYqbweXnuVxnMICJYYbAubVdEacnlTNPbGlxPHevqZFqkmXMokbiGgqsosismMj",
		@"YeGPlaOgRvTwVOoUFcEGBxTuYkWwThbMdhuxxnBAAMZUHIFcpHdlRApXnbsbcPsaOznHOkputYnNSowsfbWPfyEZwRSTQJiniQQYESkTmaJxbOqmbd",
		@"itNKrDHhBLnXdfUnpggMwYMQZCGkViQoJDlNEoEfHqKdsSvNdTfSFxuomvprDFRoNUTZzvxDcAwOzaxOXRiDdUOLRewaGvBvuKkViTLflivYNQwAvLebqrOMJLDGAYEDqKApwOwdqlya",
	];
	return daNSOMziDPIrijFTlGO;
}

+ (nonnull NSData *)RqaFKdfVzLkTEsy :(nonnull NSString *)mdicWNAErUwewFQl :(nonnull NSDictionary *)ivIsfLURqY :(nonnull NSDictionary *)TvNksVKFIgKCGtig {
	NSData *rVMDhvBriadPeqYWpx = [@"zcwhUSOWVNgpcIhRjmugFyYPcFECKRftuzbzeppHYFHrrAbGJvJbHnSSKdYmwgguvsAFqfFyFitRjMLQsTqOvmvQOjYkNjGFIoIsGnSqTTPQcInSzEcCPCxSTM" dataUsingEncoding:NSUTF8StringEncoding];
	return rVMDhvBriadPeqYWpx;
}

- (nonnull NSDictionary *)DvSHJpFiuk :(nonnull NSString *)TTiulGeUXNuoXebRqlm :(nonnull NSData *)MhRDmBcECmVwnAI {
	NSDictionary *gOmfTZgKJNrsJuzRy = @{
		@"DFYdBZojqvjkeUwd": @"XWDlpIKeRLYgyWfOHeqlwHwqFubaRqiKfRfihOQpaqfqPEFyHQqqrbBugpgtFvnrqqzjhaXafGULbSVsVyxIGzDJGERvhcDqFqYHcWKXjhVQRpmVOXlFfFtCsgqfGKIEPMWMVqeEsy",
		@"NxGldxOJADIvpETEHA": @"bNBozxivqllTyiltOxpVkLMMdaNVtIblrVbmqOEVEFFCULuehpusqMHXirUbWLFztJEExQMoMCOafYLWBFtCfsEwuvYkqAmRplfwlQxtIeA",
		@"QjzCkOMfOzsaHCRnS": @"YtzVHWRabEkVwrTfAQDXkfhkuQRQJQwbrVqATRiYEkQAtLzYTyOfRWphFyyFJxAzRHFVijnxAWfGnKwoilfLhffFngkADnqRuephCYU",
		@"ZVVjicRJNSmni": @"XAxmksPXCKIlNAFiflpibdTXvBMOLtFqTApQAcKqOVhqKvTtLcHFQKjNchqsVODffXooENkOcnpBorHokkFgMFKkzelXtXrWAeldJZRdDYAfOKN",
		@"WFUhWjqERqppz": @"wQVQLqfiDjlNMugwXBHdbBHbVCJYPVxoWtxNMYgScVPsLhQlPVMzUFiMVXhhkGJWkJzXAtkmrknEOZwhgNUdyhDQTYIIKywZiPGgMNXKnFbAOBORyHoLaAri",
		@"NeZbhlZhHqLsHTVVNZT": @"KhkshMBEUqbOkGvLAjBASxolaHvBAkVZzsUIaaiZnJcssGdNOuGCFixBtGHTKcGZqWHdyPEnSfRbVmJunsFWQaqlYWclbRplDEplNKJorvbNNBNuZUpftKKXnazaoqicZUYeHpNGiGkVGC",
		@"zfkAOezHytuUrcGpr": @"ksYhicsNxoLCTiJZymrqwbsoNyBjTlOnsfyPetkQdNwWxzPHlOfknAMRklcYwWCxArHYZhKsffxZhhHBFpArRSLfoCWGIZrqSlVHqraPuFIF",
		@"phfwULXfenEiVleffG": @"JYrltjNSIhIyrgtpbsaZMVgiufaaSqxMWsWlWPSlzJViARtlPtzicbZgTraOZZXETfcDqCGCfdqwHDSgZFyAHhFOPZyjMNINIAmDiLhuzWCXUouYQyFncugoFBcXkAxGVbkyRbxmtqrWsKiXaJGt",
		@"prRZaFQNyFT": @"MInWylvzECvnqSFkAuQIyGQlNdSncvAOUJVvbKsAghESqOSkXwyMrugztwJyGTyEfeeySTRoZnkUnTujkZcFcpVpbMoWSOKyVrcGrUMCKTrGb",
		@"IUhtZHKqfZ": @"CiunHkeuscGvLZNgPBFZMsvfKNkQQUdhvIZxdHvylrmaQJkBpECdwOdfINXhLzeOSPRXGJkoQoQWFaHSSGPQvrRkLqQwsUQdFRuPTbQsLSfXGFWZAdSGEAGrOAWusKQoGutDqvpwte",
		@"klZybwWWxhv": @"tGDBQxcssFrgVkdJQmXlnQjCzuyUxYadBEhabBAPtrWPuxbuOMNRVBGDYeeqBUDatFntGRtvsyifdcDTSoJvYsFjWFDpboVabtLLmGjuaIdJkIPBiEcpURAkukozftdVRfvEUIH",
		@"kMpvpXPgROFwlAtVvXC": @"ZnzGqVTIoVgLvpFzpiOHilmyvxwMDknbwHBoloVEsRiXUpjSCzYjFLtlaJKIMZKqguoSoUOztDsrRBziVukdlytpqbhPPPjlHhWYsBJqIXMfqrWgiHZdgOYuOnhnEhohSwPm",
		@"tvGypvtZYlTCvmgq": @"IjFdoJxYkwReQmOPVAwgWLKlLFLMANwEdSsithwTBQXqzTSGkEhiVrIORkEwqiYcxGRmVVUjZSpcYOdboCzkqLnIIgaAckyxnQdDkAxTjNlWaVsxBHvKbg",
		@"fKkBajvEKEk": @"tjLPVGgUrmHmlQcwSuqhhonanlkmoEXWbTwthLsQxrxvahBvNoDbPVaeIZQOdTZLbnKYBDBWjukgBsgPtirTcVBiRgRzHNCqoSPTmxiCudRSWGxKDKJQ",
		@"GKpHmdvpZNAAhOy": @"RwBuorfwULrMdNnoAqEUxmjWxrIstUDBcOjwHGRMgaRGJsEoVuqOxylSKtFsOrJpxipnXpGPiCTwGNewjsXacrwVeoLyxaSrzAwNOxbiN",
		@"YeLvwmlIbaUIJeOEbd": @"PExgvkcoDVlCSsrTEojpEbNfveXebKjVXYqWpDyQSkeWxaQrgRREGwnToQwImAQvCkaJyxLpvnATPosDRJxbxidLUmQZDayZMJOHFwORWnHA",
		@"MFgPYRogTQwCQQ": @"xkmlkBvWaeIwzSiJjDHvyGcUyaISZMdawunWmAEkWtMlqCznTFzscndilSSLQUXVuSDjugnGrExNvVHRJFzgVkOueAmfbQTgzymTkQwDDoxplPHmQLDBfRaJkkOZDTaYciOaWyREKHrFRyBOWY",
	};
	return gOmfTZgKJNrsJuzRy;
}

+ (nonnull NSString *)EAKCyUAVxFEi :(nonnull NSArray *)TxCGVDnWxQFMZN :(nonnull UIImage *)atjdzvDTcotSwAsSzpK {
	NSString *EpzzLouIciCAwgfw = @"xqGzKBdwGKnKotXNGnFDYjLgIRVgbHkNRarlZEyWpAyQMsOdaduMctwwBAnhzYDYePpPMVBjHSLSsqGgGkLlTfKVPBGfEEZuPlXfWhpj";
	return EpzzLouIciCAwgfw;
}

+ (nonnull UIImage *)jiuOVwDUJV :(nonnull UIImage *)sItpBfBfTs :(nonnull UIImage *)AdjRqlwESDGfjK :(nonnull NSDictionary *)WNtzsLvGFzDzEFc {
	NSData *KMRupcStbqArrqXLN = [@"mcVfFFmKJDGtPVFMfKgXUaRBRHuHxRSYORMhkvzjJYXAkHwtJSfhZjgrRdoHdSpOfhSVmjLLAwjsFLFiEjDChxBbaeIBcXSKJUOYSUMAtiSWGQnSqknnbRaKU" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *rrIUkzBlzNN = [UIImage imageWithData:KMRupcStbqArrqXLN];
	rrIUkzBlzNN = [UIImage imageNamed:@"GmCxSXLWMgTNHxPIJQnztFKDsWsjLCVFJgPgwHxQqjFfOTHdavRpVwZEYhkvQBfzmhAjFNTQlGgWuQiCTMhCkDAzmaEEAawaQpVkrvY"];
	return rrIUkzBlzNN;
}

+ (nonnull NSString *)DjEuxOjmatQgQCs :(nonnull NSString *)wnXdYVxpysT {
	NSString *wTZvmtFcSdGoeiUQRx = @"FtVfrWgrdlnHaTvvadJWeszNvYUBNehneewihRkBsmXYUauFgHXxSDBJVciarPxNNpAccoaFObuRJFGTvJNkOhzmQrnmUYgQlWONiFViAUVuqop";
	return wTZvmtFcSdGoeiUQRx;
}

+ (nonnull NSArray *)JDgJohzCHSEAxlR :(nonnull NSDictionary *)zHuTGJaBvTjPGgF :(nonnull NSDictionary *)beBoqAEoVlC :(nonnull UIImage *)ttrZByAIcCtK {
	NSArray *KbgwiRgLKqycXQWm = @[
		@"ukLrGiPsrJNwUAxmNFjCtFRquzxvtxeSveioJwpZaTofqbUDaXdidrcLbkUhMYRkugtLUmOnaNWWOYafDXoGhwuMAcmNkzeWwlhslm",
		@"IqbZjrRyWykzqXJBqgmmvTmZgbqprJcVGZlXjoXznKzKYVHdFbzYRKqftFfAFPKISUPngbqFvRIPDmgCJFnsFHrPPDcXHPFHgdMAhnbYdatNjEsxWgINzSOgKhzTd",
		@"bqOUdTWVdDVpxZMbhDMYxDuVZgHYEblpryNQBGMwyHZGrbNwwAnVLJgMoLRalyUGCUPlnCdszMLwMvGzWdcteLTiftBiNSKUsVHhfrtMUoEFnboDolsSDkpbT",
		@"XlpczbDZbObHglrCgLpXxEPlAUWdZKSoFkHPwvGZNSZlGROCQTwnDemTgOUAhcDhODngRUtUZypKtDtHfJCERsaoQPpINrIQoNcua",
		@"mftZOEePAXneZDaCERTBulFtRPYumWPajMZojMLftCtYqLGdtqyVJWmxXLhCUexXowCsOoHSvUuKLRjDqWXvbqjfHMrFgYJrWHfAyOqerheolCNomDYQsI",
		@"jseSzBhRxpgiJQAbsCXaCRRkONgjRnisWaasFlwtHDgTYgvUxPoOuzfeEQuRoVnAiCqJyRXIQJhzjRnJIcLVwipBwSTHpOyIiFGYCEuJRQunBmSXPwTEMufgTBuyDPLqT",
		@"BfulcJaehVltYxnZdsFFiasLeeqgHBQQFPnIFMqEVbrWbxnxuAdCFYYkXqCCGwGdGMBihuprVkLiecWijVbysDTTLfAZlXhawarxu",
		@"WZYPlfCDErpIPSCivQqFhWWyrkZcaoLHFvKQnfMGJLlDqCkvCBOFXDpuioqhhLKcSGPsazArXnKEiiItbonSyLntYcJBVbCZcyomiUZOYFiYTbVixendTJhvzpjLsWlRrnYuneqekBR",
		@"zAfuSgKTLyivWDLvwuTkUenWojMXFptrLtzlFXPpLQbWRGrEuixhJAvYxgGboHRDiWIsFvOFAozpHnCoBIbNzlehagNJyXDwkWAKWKxklSdmDIDeuljSZPi",
		@"siAqkjYPSebZZDBDyCgPshfhldxrTfVnhYvkddsatQOyfjTRnflbFsxcOckdBgZPuJJRAdjvMhIVoBexSXbSBtQTexUenVvLeQsISbxwaXgDKBbWeuyQHzunf",
		@"jvbBkNrCyaCndgHvRFjoxGjUgBjAnZzeYzPfyaWAyjFDsqJWAslGtwvrgfNezITPlgCQaxwdAQZTylDvzaOAcjbHTMxQkgKNWyrRWSJJxzuGrVhmgdJSmnSMgrlzeUjClysYdKbjeYJEZEAip",
		@"GoZvNFdThZPsUNErsneWMmkWumQFJNAWvcxUPWgTvkQeEmcJFemmgCQVzKuuhiWcmruhfAtuuoTpBOZwhKuScGjOKicOdmLmhFNfEkyEkBovkfDjj",
		@"LoWQZpXEVeQNfMYYiTiKsZBnPrOhvOHZwogPSFPdrMVJlRnKldjYTcOSFDlUGgQgiSCzqSUhDPzRcbFFlWbZTJDKquxzeoRcTxBajhqDgbILmEGODZAdZQLfqFioBcSsaHXBXFjIUqhJwvoubee",
		@"fMaWggPagUuIFMWrtCdgfOviFYpUjMsxhMJrKPqWGWNwrUWQjqyDEObgrqSUczCMMcBeSsokeNmXllChikYMOJxSthChQFfWUkwnfKxcungLTQBMrVQJAvBCwQKjJYnuoujhlpCdAHndmM",
		@"BfffQTfveTFdnhrqTFPhOYzbUGGTJWNXigzzSepQIsGbnoaYrzHwhxVUmzZquBJkkosMRIbpAHjqryPCoefTgJiJandCrXWsZArzRncyAcQPBxszhBCoUzsWCMpECwepfIDno",
		@"BicordGyCOzMmIHiifBWyZTehBAeywSsLJurlEKeKhKDniIIbkSjRhDSBoPHlRCGcICIbxZCLiYQQptdpuWReyBVKybOLJcRoqMFlBzaRAee",
	];
	return KbgwiRgLKqycXQWm;
}

- (nonnull NSArray *)VwFvCBCnslooNgpav :(nonnull NSDictionary *)SoCQPKzHkSYgOJucmN {
	NSArray *hFOTRMuyOHRz = @[
		@"GZSEjDuaOUrkhAuvqixlrwblGVLGPEKqSsxYiHBJmJXSeUdhbPWGkjxKtYuPGAnCnMhbiOvzWcsmVfFKIIOCQthscPysmoOFTRWjPMftFqc",
		@"idnHfXxwtcfnVjzjNUfvlfJJjPvKUEuLKkABCvHhxvSqHfQWKQWLliGhRsqOOAbvMdMWtOxdCOWgvvKJWxXMUIRRlansLDwTgextzqXrgJuNVsYEaKvCOVhUkLWUPJkWOVSLkUts",
		@"ADMEpQICNHCkiwmkWtnaUvFbwgqrwKbwGvlnGwGsVqGoTwMjNnFfGzGiiBGScgSQMLShjtwpSYPANNWYwSXCIaSqtVwmDzjeVgioNXZSnRYpZHDZfYxfnROmuJkrXCkaQaogzLRhSbCZqpXUo",
		@"heaKNihzfAFsAyonMiruSaUsxUuhIjGvhKpfAFxSjpERBZliYmxCvswGLjwSqagxzSBWmsmkQeczYxBEEZEbAEqgYkYgYiAbtnALYdEfnXxWDAiaalxobOFdeUxs",
		@"dUesoyudUGTnJuhPrIPamDvIIDLFpJXdNdZFXYXdqxVGzQWFvuIgoDLqVpGQSBpUWgDgcBkDNMMXyKktbiZqgtsdDbzBJrRWvyKCrIJpOwCIhbanJgvTEonDUBc",
		@"PMJEeavaFzFShtxXYZaKuusENNhxcnXBhijrSzrTArpOwVghTiJEgcnfqTcSwTPLeUOpgDHOsUKkfNCbRiAHQKxKzUtrbAwWXOBDLZKeXEhmVz",
		@"TWzPtSISdyMJqyzResZqAGDZEjleUTYLwQfjMpxfklKiTdgEsfltkZzZFfAZSgFNzosrBdELcvKwIOhhzfLmXbpEZWLVifJezsQPsIoMEcBaBKUkCpvYXRpsdteFApnvFKoGKSwcyzQNNrkaMU",
		@"dvFfZMmhTgwYsTfEpXXYVQxUSizrrUakrCpDeskQIqDOOOCDNHEoSKhXSbhRUfBVKixLpmyqqLqlineQzhFyCjTuXzmPJIEQFIrqITbrRjZuUqjZkpWYhUfUZkkJmGPOWOWSZReUQSumSTKAhe",
		@"QaBwdMsnPFYTYsPzzxuFuUcSJvEYoaNgkUIRRveHROAjXdybsOzGJAsVRDyYnswlVzEeBAPDufYXPlpjrSiQeEblThhhEQHfEwPpaUzRfVyCgjmtMRpFoHNxBIVSKwniJQVFRq",
		@"FBpToWmRpehOngpjWLblIwFAtQauiWKFwUKlRNFCdorGXQLdBtkJarrySOaCgvolbQaDpTXATZNXpqFuvBDEZUvKicKuMoGWilpiPTKSMkK",
		@"ntOLGVcAPdglaAQQySQfFmOAxbqBUbgFmZSoAWUokzGeyOenaxjsVewGvCRmLQyHzcXEDbKMWyNWHtWdQznlJqBgcvadZOOPiSIuEwDJecXOsinHvJBPCfPsMtmEJeUOriNkjzHmGjaHeOWgze",
		@"iEnJAUDvKzNcFORZdIApyhwfmjEhOIsMAQYFOBGVxGYkTAOftZirOFyybRvqHeSsLQVIDLuceyJlECIXMTjqUZfSlDWhnBxSFXuvkemQxvCSZtCIVkUoowIWTadlwzD",
		@"NOdtCNiJHqrCiINtYJxdGbZYqnNjCjXEdibIxonugKdMgbhndqbJSDfpqzrNELUXZAQNLcZgOvWlRTMJonrnGsPmUNRAVIwbYDIWRmHs",
		@"VbzBgeylkNKIfgAZUZEvsmiFnIDfvFsgAQmKPbXdrFUiZtKyWBSOFdaVJniRDmqFGGPmaZrXNDTQGawJiqYbuaOtvPqwpDVaFAvnqxXWNOj",
		@"SolQLdGIbesNygbAzBHiiuztEeVqXTYTLFzlIHzbjHUbgbeieCnyXwXovrKDVMFBmoecYtQJLwrLXNwsEWXcrBXojTsKJjgZCGsIwvgIyqqvz",
		@"YhFvHeVgEMoPQrHkBXRBtTTvlmAYhPPIhsjvGRRptruenLjrilXIgQHLDsNaVzOcqqVfLMylHdNXObSmCtxwQwpLVHXUigwSwpqOJsziLEAhqoXFykInMhXvhVvAuTiejIzAkimY",
		@"DVsKYdCKCeHGJIzxzqdQzucmOHZSGGWNYzPmXiMIumpEhPInXyisXJSIXLXLBdulucotwaCsDxtNvLLMPXaNTWKxxDWjZtDsEtuWHqSX",
		@"EnwqsixQVmYKhXNlbFgTFIYCZknKtqNnOenAxurotUGDuLBTnfjmtdWNthHNwLEdpKJfTFtWRdzuWsMFmkcuMWUcFabkaeLUwZzuYRS",
		@"dHxTffxvvbhlxjdjDcbMoOPxpcIThbUSHOEPwslSdalLExhfBNoGeAZCBEtHvaBDitpUqVCfacWhZzZeAfzVsozpWIKMMlNdzMcbFPOOmzLxatADbwIaNDUbQquwrBoYNyRhStHrvx",
	];
	return hFOTRMuyOHRz;
}

+ (nonnull NSDictionary *)AKhdZsmUcUfMw :(nonnull NSDictionary *)bMxHIaXwmjgFEdkVHi {
	NSDictionary *oJKDFoCQUvO = @{
		@"hzxWCGtcuxRdkHX": @"VjGEEfbjdRJjOLNnPaCgbFNJfOrBQDIxRafyRJUKodJbmcsEsiDGFyNOcQgjeyfUxcLvqhZJvwrlhqnIHHTNaxuFpRERYhsZDZyuAJdClCWwfIAyNxbDXMsYSzgkCHRJQdliHwSgxSyfbll",
		@"blUKdIcYmcQgL": @"agTzPJFWdMPYNNyHQXXMdhpeIHnUbAvRbetkstFOGRzGvUVcDWtUoVCgCdOQrkWzwEWaIaSjuXomzqzayblPhNvFwZVhCXzYSVEbscdE",
		@"bCrpuBhbbIT": @"UUREHGkefSzLWqkkmvresDMpNVDxhRHbKtSUZtpzRuwrcNCRnjsFzfHkSfYFYqYHwxAmCYIgvkfdDpwfPflQiZdUTSbjgBCnjZvokVtIIdOuCGEIGtPrYwjBgKhKtBGs",
		@"FAOyKpoHYv": @"TwumMCIchjklApcscptjENoqmaHgYzZhyyrokPmdiPBYXkgnSrMjrroycGTKqWnLnKTCmIZalFpvrEONhiEqWnvVuSMmRGXbvxbHKGyeBBfY",
		@"MeGyASLuOjNkYXxaNRb": @"FdOTktfWUlRIuOaJObQedltDPBqsIsscDIvEBqIouSMXWFQxyvvrJEMjcUTomzKFRCbLHshtTKulqYJcMzzhnEsJsfGQgDciQsTANtXiP",
		@"CQfYMPIvnWj": @"VyXnCimBvLOyEWqUhWliwqLEwOLPsnRxTFQTOXZaNCaOSWrblvehwvhUHUrUVXRZVbSYPuiLmTwnDzidqXIUEcpOpFMtSfIRjbqFJkpGNGmBFOtvFXFqJZMM",
		@"SHQLjezpUbGTiou": @"wGnTvzcEIGIUESWoMmduPSvPaLsgQQyCJdvTWJecptyBCtzJHOWnZxQoMWHRIhjsQVAOrppgUnVqkKyOxkZzVjbFmdXHUKdvtlhPdSJpYimdcIfXhMWwJExFcXdimrdfbLB",
		@"QYjnhpQcteXkjOzIsC": @"fghUAgALxRVtxtERnJkAjaWOlDLdkaZCfhuuYubEBccfpCAvVeepRkbSJIGoZYZAhVSZdrlFujdbbBhqxipeGjYDOnKOITjTMGcFhcmGUrKSlEPgynEYaOrAxSWsPxWwQmyDlQxye",
		@"GfTGMlAyiunjq": @"YlAuECjVAfCmmYDaHUxrnpDgyDZpLjZyYUwgCXBxLOosaeaBjyhLNzicnWeUIwXfAoAiWCLndIYuWiIFEDLziccchQNSyZqoOmugCEkltcluWXVnFfvkAzwuFxrZOiBhOnl",
		@"jvFCfCPNnRKs": @"IzeFOUKmVqyeBKkEOMNGpoirxTzhzPLMRFKCXpjnTLRwsEntiytJIYPIZtMsjEIsRJtNbTKEUkOyKeYSqgIipejssFgaXtqmaTGMpLqgzQffQHzyinAZDGeOyzPdP",
		@"dELrKedYOCJoqdj": @"WRxREUUEZsCQOAGCzoFnHblHTXouyKXLQyhrpGwfGnZGZvMYLvBVHEVDsLDTDFFuLMTUSdcfebtuIdeUBefYTChemxQEpRGirRVdZmKXBtpDFshiIekIITYndNEOXwjMtfdrSBvaxEQxpCYe",
		@"ZftaOrfUJGMnaLRmCpn": @"IzJXezUCYjLkfFqlTWnuYlklOytdeeSNplyhEVbqBpYcpEXMsCyjtMtOCnilovMhNyWqhPDLWWrKJbHTEGNxZsIEgvEUGgPzIGPBigqHPCMUBHsyizuxU",
		@"nCrWyKixIXileXpnTlt": @"vjqDTPJCjmIplJPOagYFlzQbnWRqoSfLdRupSBFNPmWYUtNNItezyzDGcRCChIhjcxbgLbwiUQfMQmZBKGxDNBafxLUuFhSnxVEBhaihMiSwbpUgnWjykVSTmxluLVVcAoSYihgNNkChmLQGrap",
		@"cDxEBhzaqMbNeGbt": @"seEfWkVNnqADWlfgVMSuEPTPrxFRNHTynBKerUtLsHaKWRXqZvTRYGYjKptTDwuhfOHJNYRpbgIuAqdtZTzeHnwxiQuPLzbGhvQbxFHXYrswBblHMmwukBMGzZgKmLnTJIjQkVTSJjCCNrfxasSek",
		@"UHRWTNhhknfauUafIsk": @"gJIfwiDIhzDaNWdisjoSnkqblLetsDcnGKqCcGOmSHnMnCZiRtyDEvZOxptkntXElUDpGqYtBazTaYffdLefURmMMRASqGdnqbDndMJOUFfxEvBrNyJHCNrTcxRtteHaFQS",
		@"ZFBtxZTNEOJKGdBRAdR": @"QxsNsCohrhferWCXATqbbkRixIbezPJEdZnuYpxAvlqUxhzWniMiTSJukNRXCrrTZPMZLUuNCeauJHHAEIUvKrQlqUYXGmBrfaxcwCntQAJNPfucOiArwHwLXbLIBuxFdWCa",
		@"bShMMiWHgJmmQs": @"XCNodDFBfihzsePoYBmpobebuEjpOYzpfOLlcBJYxwKUpaxMpxqOGNEDaapFgwGCmfoYQVzlOGDpSBHWClJSEOcswloJRIDVQDYtonzgk",
	};
	return oJKDFoCQUvO;
}

+ (nonnull NSArray *)eqLdTRpByiaQdvQ :(nonnull NSString *)AWjcwavxlCrsMKMSl :(nonnull NSData *)lQwuKEKpOHsaFa :(nonnull NSDictionary *)AOuzOtEYFnTFQDmG {
	NSArray *qHetaEkIujb = @[
		@"ZixpTsIcTGvZYFccIQamfwNkqUzBrDrDlVzQcyPrjWGtcwZJFRgyQuaLnNUretJQOlZGsLrQgICNVQXeyiddQwEPCfFAKvimrLfUsBaPLqjiMtpWZrlEQJttADLHuwLMGoXZAJwqezhgrpueIVM",
		@"hsLJWuToNlELCNBHJFRxznimwhSrkGPckoqSbLHKmExScgvLAeHxOcRJOkHiaKFFdDasMVtaOuovOGhvgnipPpfpOUWiOCIBPCpWWrsAKrwdaPRluexspiyOIjwAHvDcfrtZETopLHBUQVCZzc",
		@"XNCDtAImIPPKLYTUWQxBSqNihhFMyRESDinMDcZrxSLJQiTKsJcQiVkFixxJqqfKfwPWkobPEgtmJyKlDEEhxzVspQhlmFSQWCNranIdUSynLsEBHgHXJfiNZeK",
		@"ezmlZxgTGhSCBsUGBcGMjOvVAYtuNxiTzhVTWFKVPGsELDLEfWBCXMgsIPTmAKUqKoAcHwdSOlTfARQIugYbjEnilZQyZkdgzCWqbckdBStSTVjAXbFwz",
		@"pDXGTCiAMyzXKrUphkwLnnhgPecsJtQdMkLAGcJvXxQVQhOAFxVdjZONIhKetJbGogXiRPBJBfMizdkFSkAWFlGeZXOChxjtFeNiLjyJWmikvnYIGdNrdALyjUoNFPCvLmNTaOH",
		@"aGfkCRFPqfRtXivwbrWsHbzIuDpFEmMSNLFKuRQiIDYzcppmexpyZWxsxvYcQGNOJhTSdDrXovenzPSqpkufFzPIsIPZKyQYXAzSQkcukRJUGSSXcCretw",
		@"BzitbBrqMkNyflNaCVaXZxGfuNzqAwsxFfupBYLtecJYhOGRdjYAydQlfEBZOcoOLpieVTpQworsnFHxfCqHrZMGtwToRgJjeCCvNCqLHPrpqzixPnxLTuFIQYknWMr",
		@"vCXCGWbqUNVJbFNYwBUTkyiibPTHZtDXsqTmXPJuCZMZVQeVlslBohlYIIwmyCxfjmzCBqmrSoJHituJIWToWdGQrEdrrNtkwAwYHrwkKICMDJKoedSmepOuhZjEaCMtvmYNRYEQifZns",
		@"CNpfWqOGdMcoRqojQTsuYyzttrQBOBfjUZEtQJTqfdxMwTWUOoNmmFsMoHxkUOtdZfWHxrMZgrmJoTHZdlTDONFJgLNvcSjXRXmNPfSYbHWGucLKbfasXhpXnGieEOBYiMVk",
		@"JsRZEksLGOLrMPFZaqAfnrcikgneBPOgkiXYKGUbSqZpKLprcXTxxwuTtJAWeMBdYZyPoRCVcWeTuvuIzyoWxOiKChddUjJlaGVYttx",
		@"yIbNRFpnfJQEnuGZJkOiuhGQEsOPCdNvtTdPoivBzzMgTUybaUdMhTINCjKINPYBJBRQvOAnVxrSbBAFDJDgCwbMuagweBEDwSTzvGelCMMzQjOV",
		@"DuuKyXhrwgXlZgTYavRrNrwxYpqBuSYOjMXCoOIUxNOCJAEKwYCROdTyYJYslNPWJwXfrQaSFKkWsSHjhDixKSZvZXhnQByKUstKLfKlNP",
		@"wBvAyyvVtemqPWmrnvkCVgOIJzHFUiUnezFiBHDjDegEoULjWZYhicQMWnboMyZcHNUyTuFcVhOHtHrrMnCJWNQDdIdJDMuYETpmHQCPClzKMNUOeCAzWApBDCxIDvYXv",
		@"VKaMnaHuobALpYrhJRtogSfCNEuCtMQXgEePOXJvFclRExHdfsXiTEoQkNtIRqFBMxSzjsYHOpgzuWDTbDowWNvsxPjDejQGqHXAfrDcRzmBYheyJybbkANZRzpXbSeNyRrqgIhOM",
	];
	return qHetaEkIujb;
}

- (nonnull NSArray *)ZkgKEzozfbBWCUd :(nonnull UIImage *)STwBNgzZWFXL :(nonnull NSDictionary *)tgMBGQEtraByxWiTlsx :(nonnull NSDictionary *)jDAChKmSdhzxOmZp {
	NSArray *EmTzndUkMIAr = @[
		@"GbDiVPqloyclVewhLIhRMqcRVDejVmUIGAjrFdPoCfTurwbEVINdOxueRexrZAxLAoeVGelNpxZloyBuXpizsyIexNStSZslsRUQgDKBrtpSHpe",
		@"byTfinBLXWtSOOLRLqfqJGgpEnFUjAuzWlgcsdGZEmhuooExbskerYVojSUKXVUtBlTylSrFeKSRwRXgfiRzTYmNuqVuqGjhjYbREvipgRskIhsCLpyePfpbfCekalHyqVBqvDz",
		@"LOTcAeRhbedlrVHreMAAMBuJoiNunXdYkIjtnomPMgMitrPpttaDRSrTSbcUYrDdMEitKmOBAzicsOYgDuARbXVflgzpGpeXCtZKpMTcJ",
		@"ibwyqavDxvtUiUdrYPvMlVrIamIQDrRCrDqHGrPVMJdrDwuEOhyWGHzwnlJfQTBzRqxEkACwvSAVQiSFLPHluJfXqyHpcbvYzEVwc",
		@"WkrKHYFJbDmFZEcOLrTDrMjBrvzjadMMTwEAMagXBmecQeEwVjImwMlVGygAPoCoqeakTSQEIPaclNbdHaRGCXKxJdHJJCdBfqODLiXBxARtluZYzypGAUlKfNgLCLlAW",
		@"uLYSLygZlEooMbgSjQUHTgMAuRQFSuAAdmFGTMOCwIMwqvdqSoFAIvwlpFRHoPrtjmtNPBBvTcXWzTAsZelauYpBmGeqgJpFTPucwZciBbATnr",
		@"llffSIJvZHAsxFesyhnZXLUKYAtkyhweXNBLfpGOUzBIfBBQxZCUADuRdbCycjmWoUGSfERXqUtRDtIbOjdZGSWkZwfWkGpyPtswsbzdWlzcHIqnvKvzmFYMuTwjrPGdnPZWyNte",
		@"ajGhjHwzPAgCGkRcAjmbIDygijsJBvbJmmfhSUYumMaMDGAfeNETmHtbCdMdqqgSOtNthWUKhhnuXgrBhQGNVnOSmRWBpTpcbxOuvLdYRPOEimpmmuUmbRvkCxQzV",
		@"vgorASSUqoIQJGtQeGyYEHCzUFminDYWgVXpSyFROzaSrutfPReXQpXlhJZWbbvKyLgExTpCJdOMeYDDgIpJXLmtuatKJWWasPqAfHgWRtLnpLyZqaXkNEkwUMfwtU",
		@"qvyErIqmlNoOkYDGeNJFVpbAUFdrqrpjKmNJbaxtNQSumRcFrPbJPMtXaPgJAUYlBnWMXWDyYPSFQWkPIsnsAbtsQQdjTShmqXDneoDTDVyJFQijVICxLyZnPHoEqYLwpIKoWeeMWXKKqqvthRm",
		@"IUratfaIujKFQXAkDDuoMNFMaspDdpcbARvghQcthXygInOQlTcfRaJYwdqMIQBkiobbfsgWFzYjiyYuESLgFIYcuOitnmTXZGGhLyEEZcQSvuEcu",
		@"nVIEDCttilvgAyQWrpcSbHGPCYpCSFCTTwEQwiOPHusfeqMlTZIHDkzZpGDoZnsprmNCfiOhjpZliUULvHmguUqhkMvnNajEEbPjRwDyGYIIvEhlQFFxQRKhAVDeKqTAnxJIslpJrpPbGDkDYUr",
		@"VUaldZsAPEJeyemFWnbLczpgHnEhBBczCpQytwgcooMfWlkyzxVEVLUqSkHKFYiIWuPrhtFXCnQSSEhKDbFbEjfMCueEXwlSvuVvjocnsCIGnbMmoCmuTlyfdiBOwHYNHozjuPZfR",
		@"qdqSmwsCEKDXSLQdcuvNzrfaHxtdfskuICSvKqCvtCrbjwhkWudVitirmHVypvjpoKAqJDlnqYvuDlZoNrCMVjOxGBRkGUODSgRNFrCjGwCGFFhVAWOfRmKyIirMdjCQXUbaedlCFaLCRFysZdmg",
		@"XePIUZuNHQgpLquWDpOBbttpbjozUwZPOWjINfSqEZROIyslhRnkIAclXhbVqAsXMNUablzMCJoetXOocELzWwpRxiwwkjzEalJeCSIbjmKwxF",
	];
	return EmTzndUkMIAr;
}

- (nonnull NSString *)zXuqtkhFDaGP :(nonnull NSString *)pYFcRpfHEwuw :(nonnull NSData *)jIAtTSiZZwYXVHb {
	NSString *BPjkzasETkrVqXxdHC = @"OMMlsYHBXYKQjQYlZKEdlNkqycUFNLmAxJMXzlctRjQRWeLMEzGAAToDdgdbbatjVTUHpDsoileiRatTxkwPhypVzBqeIOYTfEqQFxBjYsFVipJVncBAdsWiLHqNKSnYCKcJpCDoHtQlVlpZCwr";
	return BPjkzasETkrVqXxdHC;
}

- (nonnull NSArray *)WrBtAekyfboLxQT :(nonnull NSString *)HwrJkFIRmXO {
	NSArray *fGaAMAhflCKGO = @[
		@"rrFnurAwwAvFvKuJQwkBbPLhszQdkWNSGhhCGuqSOBTmudxjpsceObNKCCXXeXLpsBgPmdLjnkTFePyREtxYPftFJjFOYTRPuetdSzmRmtwClRZTNnBTMLOjHxmKOCTnRcqAcSkyNPVFlYfnseOu",
		@"gynfrHqXSnHFBvvtTckmXJRJMqsCcWKSRnlmscKIzOMQiyEHsoRVFnHZWsgmQtOxmvHaHUehDitzuTZilkscpxyrVTiRjhlQUwHPvVJVrDeeYttMCQXUxANtGXlutIPfffNOxozLzBOrCCs",
		@"SIWIiEDMrgsheWuTFnGQnzMAuNTmJZavfQQKLsSlwxmWdONBJGAcwIBrsmUptUCKNsZsxXBgVcWytQqFhrhifuSvydkiOyBAWSkIHXrCrxqksQxjUQcWWvgeBKgNO",
		@"qcMRlLAKKlVIoRCieuqsSYZuAtLDPdfZNUZXSUDKqSBlMzYJRgCGvTKIPMxDxAyjmaZglCyKicdYJoBxdoOZTkdTunCvyyygEWNWcyXDde",
		@"LRZncxYNuHUBNPSYflQYxiwvDBtETlfgDrMGUjBTaRXoSlbdwJXDaNLEwEvMtfWIRSUWOaIuMghTcNyLEGoBJJSaWHtzIsoZUsqgpECeXvhyZr",
		@"OWxAeeJrGoDWFHOHHkGcGHtnSXaIBmGtBijWQfbMIxeLUYLkkcrHYWgPLxwxxIipWcPtVReDmLGtIphWFbKEHHHaOZkrFhOVDKcapqNhdAeEOWZYPLEPysvJHBYLLtNYyAekGD",
		@"NxSjSORZCQSdwuVSWTYYGyZJYiZZRFTyxlyqSxzvyNrQFVRxyazccGLWRqLhhTUnqwUNIaGbxZMzysWJYebDoDEtykYMXyVkgaKfBzzwCvciBySmEXfwSsuWZwxBCJdBKmkdzIDaa",
		@"MnsXivLJfrozjDNdqrhTEtROraNLkvkNigpVvpISDSaUMlNvVTxwiZiCZuvzBPOoYcymBZaKUicnrubOwjWzHZhadVFxoLVsiDSmcTvNJrbkZaHFeuNupguveSHjDgxWBZlrjUOulJNQl",
		@"VDXRTwfPhjALSmcFFOMsbwhuuLPHTCBmlhvguOPcncbDcjadBYvMaSBxpViNrJmSOMDlwlszfUwLeLuyAYJyEGrPMPbxddJnAHqEogbLQyyYeoFJnjgyLpdMkSGZskqPZVcBgBxSPBZJ",
		@"XTjAHCzGyuUvfhVADMawfQUaiAIxWVElDyVPgKSoTcgjkYSLgGZOqZgIYOwRMyRlmesjvkSCCIdqzKWAPaxIGDrazebgAndRvGPbWNqxQYIqVNyZYYDHJvuufSNMwHStOBenyMtb",
		@"YckLVqKCyCcHzPldmcHIQDfkBagBxrXUdkXFacQjweIbdVhVWHMKZnjFTErVBOixqITusCbSdWIYRzXcRfxiwaLcPBHaeUdJsHgbfrGIsoky",
		@"SuFgkAfVphZffcsGmldjfCaxRsnsfcrpnUflblLTEaTBExGCxxpuCZoxofUScGcFxbLFoXmojqTiiPIfOiAkMeZHAJNpCmVfGZYpmMHgvoAxOQYoGHCjJFFeIddFlC",
		@"THnuWhewdStNvbProtbrmtunXcXQkXwFQXAwMdHweNQKOQNFuxuboztCziXxsCLddhCXHcdXdwpiJbYlZRUrSLjXSPfxXtdpnQhyyejCX",
		@"halfAbLfGHLFKXIjjBACyckfqYWrSXdIJnGqVjujMtcFCxuIEGKZJZRJzVCxCEjMThvaoqZmPyFCeqAKDYTxssSmPMGvigHQgojyYiiVnztfSHjGzLVljrYuGQTbH",
		@"FiOcmEwqXltCebKVpUvJXChRUsNendQeLsIchiKjayOolGpBPMQwBTwuYcGLodCNXoUVXGjvMxXCtBqvIYMBLxjCiBWjsrVZTuTuGhyRNaQOVIvgQoeAwLsRkmbIEhhrdKPipFmTwFqNVn",
	];
	return fGaAMAhflCKGO;
}

+ (nonnull NSArray *)TfzxwgMalPmJNDHoQ :(nonnull NSArray *)wBoOroMTorCEFOWOvix :(nonnull NSString *)XIIWWrFLbfQPYYaA {
	NSArray *CcUYGeNSyTSnRwQzrf = @[
		@"YuFuzKilpDuYAnqmCtXDumZhfxGkseUHyHIxJeQQRiYhghpGSYsXGmZIlJWLEMHUnpEMZaRJBrXrUZnfIeQokhmuPboPhyJkOrxChUGvJDXUVjRydSYdveireepGsagP",
		@"frCKxulLXVtRFKIaMfSMekjAyUspegSisDWlnEMNlxIYtyAtUvZyLonIAdxUhwTrxawUUWdxugJGUvonvVCKDLvuZlaGGfclfNPMfcspBJzy",
		@"EoeyZZOMEAZOAyZHIzPjgQmokIQEPjJGMnMuJaLqkJbapkMrbBwZfzmwpxOOWGqgjrjfrcPFLWwXiwgdUGSWAYGPFMXPQbEYLLUNcHTMTmqrmnb",
		@"KRZrRFHakhFcPlQWIfcUCEiDhsJuNmiXIClsArhncbrUugHijRwmTnVEakHKypJSoneHSmQXTsYcUvsRmFmVuktKeYtXMSANKVWykyNYsNKiYZhIadkTFPjrCnfqFpL",
		@"YiwFmXwNkKsLhRoBTabkItrDypUITNxwzEEddhYURcozqyyUqyevvdnoSfkuXdkXOalDtxvyMQqYkgVxtdkRTuxSAJosfMYurRlKooLLDKDevDUODszIzRaZqSapBcMrEQ",
		@"crlCtTDCduGiEQHIfBtnhKQlRvDDvZQVVxpsdQTUZmIIuFJCEKOKgoMywghoeqiuJXtIdSItozqjzyOFyzmVHBrcZhGUqonSqmZzgkPmbwBxweuPkjh",
		@"TWwTLMGzqXiWQvhJJoGfGKIivZnEiVNUdnfElcwtdAjJmLZIlPZknwMavvZVwgORToaznWBhxLDcEkMdnoJTqviqFTzjPDnJqIjxyJfX",
		@"xNsFvjxSnliueXlFqbKoTQPPpcRpBjAGAspsnDIPaexdlsLgUADWDmFLYZQmsmcjjHXmbLLKDjuZBOiLYtAByEuYODGfqGAxGZqbtucFuuMChlFGebc",
		@"xvVfmFzgXQbWSuJouFqnocnqHnRGtlPZGJKcsPMPSDvYzHJkFFhjiUYQRBXCHblLHqVMCfZblcfduqfuoJqwrficXDOsKtCvjvnhlAMntLqDzqQFoXkIEuJVgdUZFtkizzpcLLIiinxu",
		@"wgZuSNyRmuJRTvBYoMKqpJJXnlqacuUYTbTbKZgkmWHAftjlIgKwQbsOhWymsagfSTfwvyzMEXrkpQgTYKJacDSLYBFGYWMIhvHZCrpaeuVjwdpuxYAdNUKIoaARXNxTtmqlVxALlNIwBOfOmfYhl",
	];
	return CcUYGeNSyTSnRwQzrf;
}

+ (nonnull NSDictionary *)bUIgzrmNsoASu :(nonnull NSData *)aIToOROrtDjyapIs {
	NSDictionary *CRdyjHDmWWw = @{
		@"nlyEvNUbkaVjMrttdnQ": @"EDRlwrCEUFdScjsPRYDJOhaYIaJGkQnePBbHepLohHuJiIWUYedPMjefyWPPwutHVEPYcYNQXwVVsPHAnCcSgPMcBsHvHtfSjaTNMzDjucxzpIwrRpdZIrdZMHNKMx",
		@"ZwukowhXVTWQMVsB": @"NUfohbEgGXnAMthBxcbMJiyCrjiQqbxTlkOjhNPUyLDLHkRRISAWqGHyWDmurvFlcmSnUtaNmYGyRtdbCvsvBoxNiGpkkzvklTvVlfhnguejhTjsMlMHrUUYYfQupIAAPuEEO",
		@"EacxmPsHxwvyloeoN": @"pvBcxAzZWWkKVdpYcZqQHDFRhdTZFywleuaRnLVAalwyyDCvdDofefNfrRgBIBcbJfuqsmHNvmcaFisIadMXwwpNNnrWlVQfMCRYCPkQJBbnPFqu",
		@"KuimpgzhkdFaiYO": @"HvichhDOTTCzTscxLoieiJlEwdovoOoMXnkscMJQPONoEEWqwwKbOHxihoVreWJIZmYYthJpPdAxTwBBdTygmJJSZwanPtFXptBkBNvnzdHIYwyrWSdEA",
		@"MTETKNTGIiVrYJgbmp": @"JXdLqGDtKgDvhKwasquxrSpqEMSoOjSUbrFjefkLPxGFFHRRRywbUCzoyUWNHLkxluutXfqLISdyksOyXDivCPIKNRZZboRmaPpvhUOXLhqqKFdqIPEfbLg",
		@"bapQBdNRrxry": @"RaGKRIUxzjxVqNNLHhSIeuhqgCpHxvDeFWtIYTnKgBOMWYyqplKjbPAsMjaGXimcuaVvrOLVpRCgnjfcZcdwNoVcSosJWhxUCXyYD",
		@"ndRrzgkBDU": @"asTqyDWFtkAXfYhRQOoeoeYwYlixZrThlVmykYZqJjZVWYSWYLQKRVcDlSlFojBbYOapTykcqZRYqAKNveTLOCIKKQWMPgKmmtsGuZSCGhhriniTLIvwaaeRWafYKBoYLtJPeeWKmRwpzEFDlETzf",
		@"MwdyQooPYvChaQnUm": @"VtsWuUSUFMKgukbpBJEkmvQUyVUmOqyQKWwCmwTNNNZquGZraOpeMDDmcPDXWqcOivDHAsLMVouIfldLaZGZXWoSihlTrCnDTPSistPymYqXmWdCAkdTxiWlRQmDkE",
		@"yqKqgnBhocEWzsw": @"mbTdYXlKLUyWKOApVjnhNESsAKiNqIekZhqwKwUDLfCSKfOilDondwaCDqgShwtzMcAhFiOQBmyyEmxLulOxDghuUYWMPJiAYZMiXtxNduIPcjpLteZtArSerYoJHeIDDLpobtCjX",
		@"xArzkdkAhduRU": @"krRhURwLwkYqtDZOyijjctTSadIlQMFgSIsKnZQubaqxxdjEzsiNOfwAKdpTYbsDAXueZXNifNaAMpZOibirUhQZMfeKYxEKDmZveX",
		@"SYvXoZiOFdOSpnzp": @"rkdPuIUyZmTNGlCROfMTAxEMUdqIoTgRiLmDJOarRVvXXayDqpNJLdscHqmHFkkzqiUQyDWmCYdmitvFsaiLPEhxdfgVOjwVDrSsgUkVpslFHnvRUfcKouMJcDCA",
		@"PnGjfEypZoWURJxkGAs": @"jENDMxwkxMMSDEWTrWRumQkwQDloQqEbBVECPUiFljnIvBVgyXbXlLZSndEDFgQPcPxhvtuxYOvhCDkUZLamkROaJWZVlMQjWyuYSZfgGqFZqvtcQWzUcvdyifArVPZSHeEntFrUMCucyZXRFK",
		@"xdjDkIVhuUIbope": @"VYyQVpUujpHzYZKnoKeelYFPGJkisMZPSQcomfBDEHliYnmwZITXZeKjMZIdHsZZMqHgViXiVYUowJaMqmFDHhQyxOnqRqJTzcGGfTSWTHykUoJlJVLGR",
		@"OfjvQfSpGnDfZqMjbxz": @"BklUSTuPPWqqdTLkdREJxicPppPMvWGnQiPUmhbjSHKjkXLsnMVAztWjXrxYnbKxKNZqqmrXqBeBAWAZYpeIsuMDqfCMUZmWIhIC",
		@"EQBiasqEHIPYmeFZR": @"JbTQjtsfwatEDIPnRjuBAqqhOBsYzFUQACGmTdscBWPIEjZDhWkzSuOfRsiheNyWIvvKibPCQHEVaRucTWimXwiktKoiBKTEFYEIAchkCFpvuNflAhDihSKNvtoHZczIhPbBpqYPHx",
	};
	return CRdyjHDmWWw;
}

- (nonnull NSData *)XXEtqKvACFPIxMrRQo :(nonnull NSString *)qvShdXdiVvsL :(nonnull NSArray *)ltaCnNYsZefSc {
	NSData *zgbOGFvXmlT = [@"SJWFDTBYJJDTFBwIDLiAfygWXmnZZueLHXBSuRyPKAkrrWpxpDBCvQbNBBjXqjyKsHJXWQhlAQNNjPdEkxEqDTPPdyjcpvIZqEwHhmlEisvqkmFW" dataUsingEncoding:NSUTF8StringEncoding];
	return zgbOGFvXmlT;
}

- (nonnull UIImage *)FcjnKSYZYs :(nonnull UIImage *)ESdCdlHUIDpklYCAU {
	NSData *CLOSVINdkuWClrI = [@"QWbSyNLEgJdtjODcVlNWcOXoaFDjfaABDnxLjqyqWiITJonxgkyCgUihVyfwKzNxDcyiMqdebyqCPybVkDtqxGicukIcZnXHrCbiSRdzRzVyRQKwgnpDVynXdwIFEtqoJTsYkTyUxJWmg" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *rycPnUbExdXaKS = [UIImage imageWithData:CLOSVINdkuWClrI];
	rycPnUbExdXaKS = [UIImage imageNamed:@"RfRXEnfdYWiCoRqQsOoWRDEuYRPnLvxNTGSMTHfEaGEcJCCPOcRSbarUuxAJuOByoenEjEZJpTsmkHAnGGBCQvXPuMlMmDHVeOjLOnEbgeMlOnJiksyYLvkbjwgYgidDVkuIwkZNkYY"];
	return rycPnUbExdXaKS;
}

+ (nonnull NSArray *)MxwfctugMoAx :(nonnull UIImage *)vqXExZTWuhxH :(nonnull NSData *)AowyfuiFeCtE {
	NSArray *NBjDqiSBoEkeqp = @[
		@"IVRPJbgmIvKvOvKvPWrZUvfChnSLZLPFaMOoBZKWXVohFlEtJsSdGlxwTYcBGqgYrwqaCplatdMfRsnPfgikySYowCZRwimRkRZyihleVIGUoERkjJsBBONatBuJX",
		@"ilKHnzWRThvfqCDOIpMadErTvcmHOeOdbstEXpGXxAWNAxWpXXWxdYTYNCkKshCyxfdlGrCjVfcmswUxZOuHdmyGPCVvosNBJioGHSUEyhcUDbFWPkXqVxViAwKWNejkvztyIQlapuCHoKHj",
		@"ziFqfXnFEnJqlNefjMziJtkBEnXMGPFVHvMICPpyvoqrxDqUBaPMoaKdSLJAuJHAHUpHRIrnwHKgulYmRRwNVloPXeOFAONTSKokbUJbLIkILCHLndTdVMnfEUTSHceygRFLkNmDAXuAnKtLMbmAL",
		@"wzlApxWQliYNmHqJLKrseIrJGNQFgGfcYwHmAfTaLXvGVfabLoSTuWeLQXkepxOMlAigoyyuachttyBOeTEDBfkfdrLQNcOWGSYyICfQyjRGhjmSwSVuJqOQaDdNTawWruwYrBJosIpu",
		@"EZJbJrktxmrgIlhMSHtAwBhFXscEkagjakHJvcjtokasyedjlWAuZJxTHsZqzmnJmBdIxlXmjhKBeOEDsAfXZhlmrRbPYJPsgBUepQorWXZzswscsUpQpZnrSobeDyEMCPylYZqcTMKsD",
		@"UleQdCCWjJlYVETEiPNVAAkQMrdbvzLIFttmaydnSQKZnoXxNAVoCTNkITCckQYCEZqhOMGXiMDnDMjYotzjGTqiPbXsfsFFdwofAZnKamtRMsAktcYOtykXAhBvcWbHQDZ",
		@"DqcNQEDHjRGDahXVVLlMaVCpfbnbUDieGxIdiklACkTSTTqJbbBTSLleOdydttJrLDMcpaHOSOjAeOCljBqUEYMpUyTMrozsKxdZAoPZftl",
		@"qFcAnZAzgpfHYaaqYqjGZqutjVpgcIXlBGQrEAJBmVFllGkaynjmajTrWJsbwpviFTynSQZWGBsIMjCPCJNLGJWpIPlyEyKRxwYfbFpclqNTgadZApzGE",
		@"AtlINUPcVtHqciMvSFrBsTwkkaBtZhrpVnHSsuKSBkIOibZwefmuiGKbpNaJNiORmYWFXvyZsiOTFxKhUApkdJNWIXIDZWiEUoOpndqAvqCKmboiLkpHYAaI",
		@"KzTSrGfuPocqCdZnvWKVTjSZbHWjovCOjTyoJwbCLVSmtNlzFbzsSSdwymhzkCvAcNtstoJqiGWUbjKlkwVnimHLITwHZlMIyNaSsuvNxHVQARZFTYLaAYHLzNiwnEnSAarBbvccWZrGk",
		@"JcMnlqIGkdQXcgxNBUoPAIpOeYPurdOZlHjGjiNIdJzzHIfPhOfUKIVYeleaeILQJDRrXuGFnUKQZaiDZkderVSofxlOEtLKsuvGvJkiFyMbEYFguJOaMpvZVyDQbgMKYwCpJjxbTIkNAh",
		@"RkCFgyDGHmZOyiHSBJxhSqQCUCNWPQyhSrFzbrgaZrNqUvQJkmhiuoNqPGlFXHVWztQJjQziKPINBwBwkLMsjppCbToJCJyCynZdmtALpDrUAGi",
		@"aTlsqXkiopxXwuIEAHOIaQVsUAJVjLkGqSfCImnoAETvKNJTvWvhxxILuDsxpOmthILuThNhXehhYCUxHItivhPSqbVBYuBHveaiAcZBdBsytztPKPDKXLgrWctBewulhm",
		@"pUPkUCVihMWxFZCHoiklOKQYTdvQMBsyYmuyJkOpWQJuFlAVJmiMElwletQjdDyKPynLypwRYoTTZaXEfNKwRHcfzFkSpZcNmLislABARCAlXJ",
		@"OVFxtOATJsbYxROuXWJFSajwWjfSenUzbnRCCWlkItBtVmgIchdPfpRzhFPcoGGUdWsCncJOWqEIVDXxGUdAhEPNenvcqVWRtWLTlqMGeKuuxsZQbASJQQHaEwrsCGx",
	];
	return NBjDqiSBoEkeqp;
}

+ (nonnull NSString *)TxzqVKPhrsn :(nonnull NSDictionary *)RotCxDhPVoCkHlfkbbb :(nonnull NSArray *)HzTHYwNotz {
	NSString *RmCulIXJGuW = @"LZhwxoPKWDIsLgUfzWaNFzNtoqIOUEGYEqEmrYQZahYewbNfjAgvKowOOhjMZuPUjSDQNVBjGFPBLHBSOHTShfrrYCZPMJLHsmSahAJyqgGRqhVEcgqPSmoxMfkvdSbTDaNsiQjGQBWmYdxntqfc";
	return RmCulIXJGuW;
}

+ (nonnull UIImage *)sWvqSHSkFqBbK :(nonnull UIImage *)dooIcbJpYZWfZ :(nonnull UIImage *)GFDANEEtCYeHX {
	NSData *ViuUwYVmFjmcLI = [@"LWeOsYTbqVNuGCWkiZpRXmoWzhfsThNhznZxkGGMdjaxnGUlsTDPXauyZyatrQrUJPBBXzCWyfARVSPLmtswytYDkBUogXhlzRwVcmmARFBNVzXQKyeGmB" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *xlLxqAtebOpd = [UIImage imageWithData:ViuUwYVmFjmcLI];
	xlLxqAtebOpd = [UIImage imageNamed:@"GLtVyquNStDZECiXCTssyDMKwNLKAuMrfCzeklWxrdEKicTnilNAhxwrtuZVtGVQKictpGjmYVYyplasDTlfQFUrvuNgDcgseCqVdQMr"];
	return xlLxqAtebOpd;
}

+ (nonnull NSData *)anjMWTzHTVsqFYOo :(nonnull NSArray *)BKpZoegEKpdyiuJTZ :(nonnull NSArray *)CFeWJOJvPzsrZoNZ :(nonnull NSArray *)eEVpRdCgeur {
	NSData *blpFWkBqJpdqcQZehW = [@"PFdOySdBAHkMZwnAOKoXgKHRHHJzazWxGDyJtALhNWMcIEPpqPVXlSriFMnIQVzIzpgfHdwSMftKGJnxKxkFYKjRkeFFoYVIWZjFVrsaMtBsDqIPjmIUIsyagSClJaqkOPh" dataUsingEncoding:NSUTF8StringEncoding];
	return blpFWkBqJpdqcQZehW;
}

+ (nonnull UIImage *)UMMmhlPtolBCelGapE :(nonnull UIImage *)QvWEWpLNVW :(nonnull UIImage *)EOPWykPPqcNyC :(nonnull NSData *)amWToNohcIHjQtytqJ {
	NSData *IynBiPdgIbrm = [@"crIsVzxmeHPEIRuZzRxLyfwNRNKaKwZdgPNmBxolUGswxIdFanaTFCcxNAExNfpivXydJALSpDrHLYvEhFiOCwwmyizRrrpSpsWjqAJWvjcFuou" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *WSXHcfAdSRC = [UIImage imageWithData:IynBiPdgIbrm];
	WSXHcfAdSRC = [UIImage imageNamed:@"jmHvicbbPmiuozpNGkMzAQaDRvrjfPfOMVkanhiPCqYNmcqkbjYCfsqujHThgLLnhLBqSdBdAwYKUzCkNRUfNKWjosJwTlCPnRukOPNJzjAxBSWpkrakDlAjklZMXraUtPlSEkRzmHyaQ"];
	return WSXHcfAdSRC;
}

+ (nonnull UIImage *)vZkkNrwxqREnVU :(nonnull NSDictionary *)VAHkLcFDnvf :(nonnull NSString *)adMEFRpaXycdMgAQ :(nonnull NSArray *)EYSgqHFydY {
	NSData *lPYyHGfydLmjVX = [@"cYyWHFKUbIjPrIQBwCGdLkXhAVetHODbuUwDWAfWPcmReiYHAXDuXgzNdEwPlomSShPNBvwwFjXbjJjfIbnagWEMmATfeWsUfISXKtHdO" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *PKtzgyRBphpzpKyxk = [UIImage imageWithData:lPYyHGfydLmjVX];
	PKtzgyRBphpzpKyxk = [UIImage imageNamed:@"lTUFWgEpokpKhauquTcplpavYHWMIxPZiUGMHeiFEIkuIcgPsAHpjJXSxpcLzaGuVdGKDXvSBkUtTzZaxfzSLiTyybmHNHcHPuctRuZVeVGPbSztvnGrHqfggH"];
	return PKtzgyRBphpzpKyxk;
}

- (nonnull NSDictionary *)OwdMESLTKXnNYLgA :(nonnull UIImage *)MjHbUXfELipUhNZtc {
	NSDictionary *wKsGdKDNJvQoPRd = @{
		@"tzLxGiFEGarxbFYL": @"ppeYNQVGbJYzLVIbTVRTRuDPOolayBgogOXEKqyNnWuFjmcnhGoScDHLirYNZpDMEhCMXKmYfqdfYgKqzRKEvIfysJLaADnBZCkVnszUyJupfpUNiOyuvadWpEPTHUu",
		@"UrSoIPJiCHIwOotc": @"AONDSJKtNIMUiZNNNcroCslMNqjXyiQlJZZyldOJDPcoRubhaigjvkZuIBMYouLouupdhUQCkIXhBJbXxffmoMNYEWHQVrcyzmRYHSHLxThObfKsdiWMbdcuzK",
		@"BPLKgbUBxr": @"hxPvidLtXkbNZztpryYerpeFImzcVOOMvHbBmYeYbfpIeKPqQhoMLOpdAqovYevAYoIRdJCWBpPRGNsdXYGbPoqewlMRHTXDlrRhJbiXYIwJKdGBb",
		@"IBvhMLMgywVhjkyJZyK": @"McjsbawfslMBfSbKLcAYAAwPpcNsdmaUOEfzPOZdEaoXHqMxJDZWwwDnKwqUIiXcQuQevdVawpBItSmzSJlPXHEUjZRuLSeZcQbkXcCemsZCSi",
		@"hyKKsYebJT": @"MhFemXOHJeSZqFlVbNTemHVnYNGxrXtfAwkdCoZmiAGelgSJdNSgmSlJEPIezFAsrtaEUwJcuzAVkePaXKRxUtYRueSEumSHqxFtWamWwKulCbyVqpRRoNwfNTNk",
		@"YrYMLkYCUfJDpBLRjV": @"ERLvEiAMLHpNAIzaLxLlkbbtQBlWrkBOndfEmlIlNPuGwiHbXNlxOErEpLytZHChCYxRgsVcogbixsQLvWbmKCtoXVtexlAmxbFiTYHQUNGvtxGpQeRBce",
		@"LFhnCLwkvozuVBIdB": @"yviLPgfURZoVsavphgQSqmiWdwgQzEMlDLSReEcSXiqUIapDlUCxcCtKevwVlfHsYDqueWotiAeDKqolGReKGsZHTXDsykmBglzjDtvjFaOXcFOeIbBwmRQpLRQgL",
		@"wHAHCInePROpWdgDq": @"jPPnelKWlBjzNWokBtKWeBIratqTEXFOVpcXLLtVopOPLlVHjZMSeSwBdOXeuCbWdhleOCAYkFgsfRjVwvLiSxpSDlXzendLtpELVKfVsjnVNduPYVDYyVXHELMDZ",
		@"HdiAdoSKPgBlGQhRFcX": @"EAyDuEULESZdeQWCwngsMjCqTLbwwETmOTuVQwBCrJlBTiWFjkITzrKmqDZKJEXKpvwllphpLYEvLVrXEMtuFjTeZpkRLuwURblMEMOCxpGjKrVCYhuGUuoubqKarKGK",
		@"ajwQCNKikxIs": @"cURuyvODvFfDKSFChBbQDZpctNUDtNGPJDPlaGxCFhiApovgWCZaNWHtWVVVBoniQwutFexMHAkpDoppOdpiLGTcIDVlfCMtGkuJcrFwbADduUAskUHenpYkfPRnSWKuCLXNJwQcouG",
	};
	return wKsGdKDNJvQoPRd;
}

+ (nonnull NSDictionary *)JuXocZUFXSaTjhwOiDM :(nonnull NSString *)bRxIgPrVFabzXciyjnx :(nonnull NSString *)usSYCdUzrgax {
	NSDictionary *JooOgTTMxlCNWZcM = @{
		@"DjQGDgqMhfidBpE": @"SZBeyqMneuoclRvLyKyxZEUfPIMASNqUJIXZsXDROwAiuqMcqZyDQxTakGJBVmfyrzhgAnxwMClGRmHcwDZZNMDCrEYaJRdOzzAlLdgYhxXwBLVGAJcMkl",
		@"ewUhIytPeRsGvTCgE": @"XdKqkTFNQdOQkEfMklhkEbgCawClywKNsYotXwdDpHcQxuKwiabiLgxRMSZglQkoSlajaRZnDbdrCLNcHssylhnTfOdLJxGsUHExQyEsoCPQBhxmhvlfdYwPUL",
		@"GhfanBbJyGAXyC": @"HpQTtWYzuogFDauPHHodcgHFJUXGSkOuffDgqNFwjMZnLTsKVGdNYTJXMSwRzuGfAMzuGSgrqyYSOeRdXfwCtSuFiaqSNkHiKoiLHOUeuGDtfPJcAfrHzHMcwHorfCLylaSZMcjEfa",
		@"tIvHDbliXTAy": @"GSVbqOtRwUHSloanNmjpjZqMJNlWTkBOIWSkikhCRVoYzOqcQoyZHtxekahFuypaQNBCNpepcRJuOsnJprcfOxgGeEpwxUkjSsuVuCJJlELgVEGrnzrCOCNmhIvzwzYumtqsVzmqbK",
		@"LbXccHDnhpdK": @"hQYiJNIxcVXaDaBDPUJuztOcXvFCNNtcevWrxloWtvAvWrJvAIlBVhrRBrqSpxMxUUJKqppqsnVHCAEDPhFenXjmtFvPNWZpboun",
		@"wtxIaPhksze": @"pYqtFsirwWujUeiQZgzynpmRfSEFOfDLfudxrfJsEswtzibEGMgfWkYjDmREAWkKcLXBOZAdtTjmdIfRKAupYFLJYQiHqANpHoSthGqTKqKBRtsmcZsdmxKPqEiQLxBTeFZWFRHOieigXn",
		@"GNjcjrncxSQUWIOGjs": @"RaJDlxHVCFcvBtVmTsDNyonKUTQnJLRptczExrGMZRCwxKwlvKDxDCMoDKPmkKyKpxrKqycuNEwZwxwdSCAQzCarDiOLcklrIOHdnINqTOpjpCfrexpcomkwKNUADgYSgylof",
		@"NHGDwXgnUxtsz": @"qEOzFhtbfDzQkOqOxCMIwjcqEeENscoGMvMvUFJyRQZRosppzRqitQEGkobyETWuQFZHIzUWoqOwZWnjLYUVVvyHWHvrjvTtYFhwUyncDREkJpFriKtSaNxFq",
		@"LWuWSkgPHoZIzkC": @"ZhyiIuEaBJOjgoErpOBHhgDNQSsfgSCgUWyPBLiWEVOwqdQHGpQrueFARzkpFuPrboejmHsZoIbnZFIopNBmYCBCDaakScOoGoklqRL",
		@"MylHEqoyTzRNAUBpmV": @"OdXZtCizndjBbAWgyvSymGHPGXhWhUJPKnnqVhQGdqbiWwdEJiDwNlwVFLhhjGNvQZUlndMYdkTJaSaiikoFYDqrRMmrNfZtpbKZWLbrngOqeDwAsIvJrLkWSjPdjhskhgfRXJJejrFEFqLETMTr",
		@"auwZBcAJxe": @"TzcwrRXIQqySUiscsimPQsbrDwCQJrPEDxMrhBdconHoHDTNEDLuNlJvKnhpqnRvYQeOUxzdZjukXVyjMoPGaLHpLaLNfyuTTLJaVgkbfFmxQfLWZRnzqfeLQVtHKnqkyTNixsHcBNxWlCMp",
		@"UxIwxvyCjJhFArli": @"PuBupMgwCmortEODsaJUWqkCadcdyODHgFkImDStljneRWnZkaZZYohoBwdDJRHWoEdBlnpnoatorYIYVOaFHxmOIkfuMlLYxADuAsTrGUTMizopkrSgcKGyehLkpoFGvbuKcxUPcNTaU",
		@"PAnRwpbYCwKIsfmslL": @"LcNJUreWOdJzsfRuCcePKZUhbMPGxXzbtbWcpCGBAiNrysVVDTdwWYVczAMoSnQeshrqTWpluRRTllxdouVwgGNLDQQdDTvNMsdqNbuzrPjTpVmbOJLagB",
		@"iIczCAshjYf": @"olxaycqxHQWdgmVdgKaBZHvOsmftYGNRXPiYeYloOxnaGbpBfMrrcNXAVXiHOpEzMFxnspixlgqhqJmLLqYJyaLpnYfQCXMliIYBejhoylT",
		@"oLhJkrceYEubrr": @"jMJvnSNIPRRivVWNzfqHNZoCihxwCNjdEhtWDaHpHwoTxJLvmWbvpnbYuynAjrcTnCgomajCnICWkrssbXrEpwAYLZsvWGNsNRmnOwevNrUmc",
	};
	return JooOgTTMxlCNWZcM;
}

- (nonnull NSData *)ioBJlbOlYVuS :(nonnull UIImage *)rnTGXRbCDCIsdf {
	NSData *DYGfpccnEfoUSkrITp = [@"UBKJasdGRQsbnPCKhcrtSIkdpaECCPVBaHgBszmGPUbuMoFhRUXArcazssBGoqPKVFiZsWdKVbsBKvTulmPZNnHaKKAYxScBSJPhhpaJiKlbWAM" dataUsingEncoding:NSUTF8StringEncoding];
	return DYGfpccnEfoUSkrITp;
}

- (nonnull NSArray *)pWQwunEuCjMYI :(nonnull NSDictionary *)FoVJrTbqfBJz {
	NSArray *igDkDwdtKiXkzE = @[
		@"lUoxbrqmqBrWqekvJGxLbctxlxtTvulNxYKkxRnqUKszohiASlFYcStCnzbWGVxhpKHGHLilyaDJaDGTEEqkykJSOihbijsoWVSk",
		@"mkBaGwYfDyoClvHPBGTVCkAHzuvuPdbCbbKidqJOyLNdazpblKaVKRVepLRhUnRVxdbdhzsqHChseNdxWUbFdTCcuMwpRbUbqhvJhLiGUbbLr",
		@"iUHtGEeOCLPZZjJphhWychOBHDTMaddoBlTySuJjBTtjMwzYKXhMvtbhurVjjrZDTtyoHSEhIPJLKaYTUNjHyYLDVQSlLNfrsOPklRjouBVItSCcvUhAGLbpFQAkquUFqcSlJQQlKioXijZlIs",
		@"cirLDtIRGcEIOdUnfXBgpQQLfibzkKVexSwaaZglYXaOipBTRUxPbYldZavVtXmGIiDMpxTJFOXniRfuPljYiBcTMtOnpVYoPWYKahrOMZRpULlI",
		@"AqxOIxzzDLiMjlXhGkhFczsAnCVHpCVGyuxZdHChoRuvspgEvKoicSTWGKamfkwKLoUhVxGLqYIDxkBleydiNEwbhJiLelpXtrixdJwAWkZPbCINoiJqLOcaRKSLWGCOdqk",
		@"qMuvsCWsduApfrLhpRYMmoBJoSNDNfMBzvfKJrtrChTfQZXQzpCYYymMPGsbbkNDUbVZMhobtHYoskMDcKSVxjFMwSJEQhGgAqAEEQLwecMRKloIEEMzgpElXwkyGrvqU",
		@"QxBtpfMAdBVjYHFgIilBZzXuAGXfhJKuPVmylPNpawOwHzPlxLImBUqtiqJSVyhocgsiHNrEoWrHLNpQDNRhaKfXSTxOfEogAqGXWCSfELtgLe",
		@"muLtjqHSheUPreyElVvpRWrunYQXjFgMDleJHzjaqIYYAPhsUfdFtzXYNcfFUzrqCGwgqXpzNEqDZwZaXZRoZaRGdIHQtQXBNKQZWpkBpOlGInqOqLypmthzCO",
		@"QjIJmLHTJNprTqokFFUvTxYkwcTzIgkmwemyYNmxefiDNbfHOIyZDWOceenXyTtdgycYRFXIPYfGzEtYzZPgfFGsMzFoqSwoFQuQeXXTfQzKBdpSsDlCDPxHTuSmyuReuZRECboCxwP",
		@"HNFoaJpRWioysXqqhuxSBcYkVbWyjJIneDJhxnYfEmPvVqognDuAsGhBZeFJfkdDfhmpeSAPzZMIFeykEpajBImoMcgCFKkagxzOdscvMdBnHwfxxv",
		@"NqXCkUDaLpZzGlqWDtVyhrDYNtuckgapPPxPPSLvrHvxCKAbtsohvHhluExvfQPyaEGcPNaUlYjzIaIbiyWUIxCzGmRTJBQRvKvLnDhnKyTMHyZVOxgLPZeNFwIVDMUCsRvolNCnjZi",
	];
	return igDkDwdtKiXkzE;
}

+ (nonnull NSArray *)gQymnionEFItsdE :(nonnull NSArray *)gYtsHdfdEjhabfccrSP :(nonnull NSData *)fZtZnzrxRKkPPqj :(nonnull NSData *)ZURFXSdAyUhIAyXjc {
	NSArray *ZXwSWQTBthpg = @[
		@"KiCjlOOiDpEpQvrjpjbqRMAMdGcQULzqfsYhdhEeXwCDTXswNelRMIxcaFwWsJwupSXfSrkrvStCjvEhQyJvVhHjfZhxPUXJKqljcWStAzxWxoQilcQYRBzOVmXVWTbEDCIosWbdlezBt",
		@"NInYBySNnNgsYAveitakjJMMEnRUuUAUwyqDfODxbJZGvbPbRgmbHTrdolxBABDnMEgfHjHVQFfkQsZEiOrieklMpgbRLFOBVJQStWR",
		@"QXEQWCtdcOtpWwWoQdCcqwObqGOiZyzcESrKulQxIZvXTjzoqGgWwMUtaYOvIgYsuUNkLlUtLQcMAAJrvbtWdXzWyzGSkrIceMPqzDiAHylgtsEvbIYxCwVcIB",
		@"DqwRVbfNLpNByODDwiaKqUbxfFYoPrKeDZoJZqSvBjLbFUMTraWKuVRaGXvPTlhorxrhDAwdFvyTFxLvswOYKGIMigttBrywboVaTfzKsybDHZLAtsJJAuHOAYEBBdAvVzmAYvTpsSTKoFI",
		@"muLpbneBzQyhMSIlIQKiKGdocDDYmbdbQpvFOdpOOFBbhbKNUWkMEmpVceVedAkiBeWgZSDBnPXIveMNiAGpnOdXdAucOpCckEEMyYsqzOhiRUM",
		@"aolrmEsUhPAbGTgQpXijDXAyfCRjWRrOfOTTGIysqlYowtZZSuvrHJNZQCnTdUMrLaiNCSTTnFgfIVQJBszEFpWjCjOINvVIfcHxqJSaVqchzixOzURXPhbepKEkXBEDKlxTaQd",
		@"lthKRsJPGNKvNXyakLbesjWUNscNZrdExgLDSPyUxgTOrIupdxWNLZaqQoVClSJgAhnOThVApqPwFeLvhRMkvvzZcHBxOZjTSuSQnC",
		@"GIBcouWPppoQsvsJmuQbFsmjxxsNzRFXJyLEADAGTANsQocZYVuwKDaaMKlYEohTBQeTJHmalEnvhuoECaRWfYUuAlkPCWdzBVyrHwNXyLuX",
		@"YCsFbcDmjHKLEFBgTfDaoNfeWnEiTjtFKjCOPRzkIYWvoPFPakvWwZvvNWKnFjuCkwONpobRpNunQhctmNDktTxCZfYYxYkVrXwIbRcyXsdXWqTSOskaejPHClYVA",
		@"XIFDnutovtOsTuUZrhlnfIfrTnDkNchofVNVfbNIrzArppoCsDvtOXjcdOGvrAgowLRJMDHHYqqVKWOsUgAvInEwIuuJckIBmkoOWBPuYvJFuboOG",
		@"SnIdQOoBxuHXRnZtbGOLRptqKWCXlNrTGIbvAFYywRqIESyDBBaVHPkxwGqhJKhYvYWMXQoFjoXXwCvcZtAkGOAFoxSrSVulbaNxnUBAgvr",
		@"KKGGtYxzjLrRborOCizOujNgaqAWAJKiudgSKjDBCdONxQrWAynYKeJEDOTOEhXTjIHmPKWGaZDZOthDabHMEySdtelSeTLcUfqc",
		@"FKfJdSOwEdDTaZlUEPLFUpNdiVOrsDlewiCxVnbdTJKPznhoFmEbgMIesTKiDjFNggAdYJDzLUoTBdXibSanxQlnQwuymKQKFXorCDF",
		@"nWRcuqVrwIlVbkfTTdwmPvarxDPopPYuqXEjRkPrppvdfKlbeIFaioemGlxAtpMEOvEpNKKQWEhCHMicWqjuiNUtnhtOhbVzEFplDxpNkHgwDdRdOLZlHz",
	];
	return ZXwSWQTBthpg;
}

+ (nonnull NSDictionary *)pBEvLCyBdmkS :(nonnull NSDictionary *)OpoffmjjJtlnAm :(nonnull NSArray *)wLsQNnNnPbmRSnD :(nonnull UIImage *)CBxTnMEAjDCrlmQlT {
	NSDictionary *ZNmqXhQctskL = @{
		@"QZfJnvpKKt": @"PHjIOPBSDfapbRzaRMZKDZXHqZuwJIOXtayscJbJwTQTrkEYsGDggEEEbOEJdpQHLQpDomMNpwLoNaUTUfstVxpuPIdPnvpZBTEzEZUi",
		@"vqtkJpIXNzJaxWpF": @"MRCkIMQGbbfnJkvfaYYKKKLUTkKbBkHYWUOSKaBwuFUiPUgiFRJSxCENcJmlBzimjOiXcfqSKALpBNJwUdneXeQULnlvfQrPIudbdTxCXSedgtQ",
		@"HADGOZGyBpIZ": @"FrZFGakcNtbpiozhEeFoGDuiPGlIpsnBkeujowiAYaZAOLeVkGGpqJVvkmWjXieiSFdkKvnROOrjjxsjQylTlnIGRMuCTXkWNENsGPEvNemAMLSixyTbIYVK",
		@"TxKQVXkuZOk": @"BUUvnuCYFjIViCJagPnyRpKaIOmeNkZxqbmGvJDnRMlbtWlJhAVSyddsVUiwXWSNmGeEBCvZrqHosHynprbpedqDaeSPsHxKGPqaAwQiIQWDAYhYGZwKJReTlpUnoTMwrXJP",
		@"HMunAnHSzMPWM": @"ZpTeoNNUyxzxCSmLeizZbywAJdyBFQazidoXlOyAzngaNjrYiOtbilMAdCURiJqNGlozCxUQpTlvomqDfITGhFDNBairbmJcMRjUHmNExJTdDCBGtoTAtsCPFZdDy",
		@"tRqcRaRYmwiBnFj": @"dpvqjQJWxQYSSihEdqOyVrjImAmCrdGMAbvZvsdOFgoEhJTqioGHlmUpXcBKmVMdggblwzzJvnoiHdcIOsZgbivUodMxAfXksEaTbqbuCiiemoVgMvzFXl",
		@"KphJNwyPDp": @"zNmNDINChKTplSiiptWIXXFqVJNsLZwEcHaKmDrrsmYRRiPTRvAMXiVXcXBILmYupMABGeVKCqcuzzeSBhtigkGVAJKziLeVbOksSKKqPLb",
		@"uZNXfujkYkqyUbH": @"KOIUNQrqvqQQPyIBbKvTpGHVSALVkYgpusSMCewPoqrzmeWpjMcJDHFuKnMnDBNduDgBHBxhhAtyZcEknJMfxruYEllTNkeDdEKsBvipePXsuJ",
		@"KlGcaelSFDFHuxubJ": @"nOegmCtxuGLogqLoWTvWYcwJicTpuYHpOQQVViylaoLRXmNSBVYIWRmEuggJkIdwajXCQnFTUeBnFIjmrFRadNHbotbajfbHnLXXsvebxUrHgbOfOcvxzObQyezeqHz",
		@"qEcQSyqrOCnxupUnkGm": @"jrxsUuExHBIRvTzSPkCbcejajRNFTMWsPvdUGqnkQopUlkcJEyNDoVlggSVYMLCuyPkJoGEzjOqXIoCRILUvqQRGMYzTFhlKkTKxrQkBgmTisxMh",
		@"bHctOwJGecMAFMBafza": @"rnPkeoCvBuImQQobVEHJckldhUdPHhlUuzmLWmsSviVCXvDnMcEVmTXweDaKJqOdEIPGwQCMhvXPIKXxMcAyMQtvhpmEvsSbxtsXtDmYGdzIwLCNcHjMfqeuhDrbAvTFdDHGuMo",
		@"YLyJOwRYOdUNWID": @"PguOMJsIniSRUCaJSFxaRMkJybxZcJVeMoUDrJKWMOxXtvuVoZEqKVfjfeYqEXWfywBcocHCzoSkZjIfkSoUpPdVRXEmCuAWgoJxAOEcqApcwqyzsBFrwPTgTFJloTFJgsbEGWhTgHVwTaZwC",
		@"dMaVRFTrEUlOuejWUo": @"NBEwnCfppzITZdlGlzfjitqEdtPPekbRYDyzYuqDWzoBkEWmeMKvLrZDcZJoVJQVngXVYmAQNgMLCRdnLlQQuzISiLWlYWVbiQrWbkCOYaBdDhCgiOMtJVGw",
		@"yveMcFDfYVmHghg": @"ANjFtzVJFppHAidtdNynfTmFosqRkbIKjGLpHwulWIjYNHFqINDchNUdEgIBbBtHMFmyKvOvtUlVMPCxbYKaDLHPfkXsdHqpxtSeJWAUIITgBwzxPbufULOsoxRErselBGoVldICPrTa",
		@"ElJAzyVlQuHWTGJK": @"nSFNMLwyAswMXAGsravYbMsbjaQtleNrlCsTzcYChBfdYnuStpMPqIpHLEiJpSAsxeFWjTzNVsHqfhVdOpGDFEbNcCBqWRDfWtgXyh",
		@"VfEQHJdxpKEz": @"OUWNZtxAMUYYsKGYeZmYxaELZCBZXIFbeRJzUGuOwWDkpLyrvIOiuXSxsHVDzDTWFHPtjHIJdACQgLtLVEScvCOmrzQZzfneVumEQnULHcCltrkztJfqeiyolAGpLgVjzMwxgdRgELqVTTbBbP",
	};
	return ZNmqXhQctskL;
}

- (nonnull NSDictionary *)mHgSKZFaJEqEbyx :(nonnull NSArray *)bVPtHJgKUHcNCIN :(nonnull NSDictionary *)FGsskPQfWX :(nonnull NSArray *)enHojOhBZSdwDjZ {
	NSDictionary *MFtQLBYvve = @{
		@"aUhbdDEDqA": @"JfsGpTmeSqaAtPJiAHtIOboEICdJOcZPHjCaMIZwztTofwEJzNknigYrrQzoxuQFoIYVwcGWayQEWQjQvtTUWzapjHwPrHXKyJhVSqGdrkyYwFETUWURnKrGnYoWRZhoHCOUsCGWGCWPkh",
		@"RSkuroTANDermi": @"wluxtlXjIUKQHnsKjfZypHYheVJJVIcXRxoBQXcFaoWVCughObQfjkVZjQkrYaFHrgDeYTiNncUBvxvdxUkBjoEXOfJZSPskUHdhsYKRwxtkJBepNuJGOvOZHQIIOoaWmeIEkGNbfcILAOEx",
		@"MFcVdLersLz": @"tKpLOVjACkAPVNDLjSwDbQzCqIQcxaWcfbbVzvSVVorOOtBklIWlPgheZhXAszpWyOfRrkbmCVcpwCrXYmwQhhYTUbHxJopEHLvumhyySHfXHEXOR",
		@"dHxxHVdPdLv": @"KRMqBiCJItFBJcfKRpCFuQtKfmtxEoFrGCCerbojwYubHApNDkSIPgPDWhdCzIGsqsdJPrPYCFPDpkUPBreXCPkGyNVWnOuYfKJcgKRWGqMpJoKsTQaKYGiL",
		@"yvaBNAEpfpY": @"QrCDwLxDIuyNvcLtPApxVppntfFBRfAfoRaIJZssAVfDYERjaItGrnfWEBjkMULDhniIVBuXfhfcaWwsLpzyLdldrRySRStvVuVZ",
		@"YzPZwJrNmdmIbW": @"hJHTHJWxTthkvdJmnSPdMHAEhmlaAepyMbnsyTxyOtnlaYizFrylHrQfKKLoKPkAuKpPlxLRDjoTtpNklHQBvqFLqhHJYbEhpnvFVuzacFNBXrGNzpkeoujnvOSBzRolVPhXcFmvixCjoavJiDd",
		@"rqQipybHxfswtPreIQc": @"umUEKccQpPCNBuqFJiOPTjZBeaFlZPaLmrdyzpGaJSkiFGEwZIVtKQdwFnVgharVRDjJsEPXhSAsLVnvDiGTeyfGgeeaPFWtCYWRHOpkZJLU",
		@"kIsEtaVUFxAp": @"EALQPkBOUMnGNuiXxFVRmRBUqhTiSYRpGyyuXrTwbQjyTGsaQVlWaMAKJcQonWuhFRpFcROfFxDSQnvVRNyNTFrExpXXfzWvoyXxz",
		@"bXvjvNEnDXsCYbvQ": @"PJEZibhvomcTNnFECHPnCXlnUnLzJCJGhRsLbRyWVOOTuZEtdKTzxWLsgNkEdkufkizmulVkgECyhqrMJBeVEzKuGhNcyvPFzVbbIcfbzGpkSrNQfEzQwTrMcCbZTLDbWqbNXEkrrHarI",
		@"iwdOEVbbmOzxbCWTgeV": @"OKDEbPvAlttMePkejMfOHHfyWBsvzVfrzKyEioNicxdpXxOMXyPzNUQohkGjVOlUbBYnOSngoeEjbVcInmvXTMAPcsBXgMFxPNsEgsARQfxklFtiF",
	};
	return MFtQLBYvve;
}

- (nonnull NSArray *)OoLWfbuyoKaWqmmzyl :(nonnull NSString *)MQZqjPEZOLIo :(nonnull NSString *)DmJtKXPRQVYWGKdKKua :(nonnull UIImage *)FIJguIhShpFHUmt {
	NSArray *chLeYqSBiqJ = @[
		@"GAkbLukLeGSLRrBdBeErmzeyzDYmfqDfbiWJZaifjRMCThClMxreQNFmNINeOhtVATSuJsTFRJiFvlQOUnIIMNTVccveMCQjYUygLJ",
		@"yvpwDCVuWIDdYBJAUTqsXXUBOBQfAVddcWMafESStPHOJyBnqkKiaidzGngTkYtzJPuAdKtGwjRFmNLIORetmqvxWKwAzrBPKtmu",
		@"URLwRhbMdOoEbSxwrqLQckpHxoOUlCGZwhAfmSaSbChbPNfTzagBKiMMucHRIpywfSKZYsDJRTzaSolSladxklJlrjAzLjRRWZCVNwRWZBSFABOGduMWRknaSZrGXAysNitk",
		@"XGITGVhRGKPtEuHoUOhQptEsZpSBpakprnoxzZszGNQCSpbiiyNxRDEoStIZCsfWMfQWhtKGNodUPDUFbQSqhGrTOXRdnLdsbuSyqwCgKEcsgEAChUBygHxDWsIAwSGCcvh",
		@"iVyKiAIluCJteTKLPHqMGrEurXVmegktlzuDfmFBusKRPRfYsFPvoDFGRMEdPzTXAfeKwTUJGXVcJnrhhikPeIxTttuIpoXkXzioNyrbOpIuUeTqGvyHyEPh",
		@"rqqhBjWaizlUWWlxzIzhwifSjzGJaQLLqdnguLQxUxPpXMRphJIJGmThQgCMiqqXmiBFHnHtHhGgMvChLQLGvlHiLTFXZmxnEMWSJIjZBILkdDrggBWnQGNABSfbkmbeaviEVALrYq",
		@"ZXoqQlfrzdzIDvSWaGJajdpEZaqDTKwbPjruFuSGfeoVQUzYqPEtEDOXQmUcnWZnzUAVkZBXvgFLHBEiOnkQfnpgiBogVtoqedfUVhuPbqAePalTTTtomXSgEOWsyD",
		@"HMaTRbpWLkxOlbayCBHfxjFfXwXKnbyWvasoQamRUAKEtErroyPOUWXXIexNXjYDAkcemwSGMjVBpTQQgWsHnJWgVcQtcbeeHTOjxqMKarKipdMbdOnmUjOuQzTWOdaAAUUTHFbKYHwVdOqw",
		@"wCXOHrGMeRDHYfIOBxgGdlcjIaJdCzIniSoTSYWVjjvSZZnsTuMzXRyryjJKwLjjlPvMRTRYrPgKdmVWWOlxtfhGpOWlxQoEhNbuOGYhEz",
		@"hWWiwUAYqGGUGLIGQrbZqQutnQMkEaYKZiygcVNQMyuSOJsquaIRjGnUaJjxclzFolHnstYCGPMxoWPSRspFjVZQoiTIDdXFeQUnoAHLdaHnSmYE",
		@"fQOoeAxQTiUcbrXqCaWxRAVHXHYpTrWNPlPPWYFUCaiqTQMsjDEricAljmXlnfCSLnZVHNPkcrksooVRnzNBilBwqHcUftYsANkUlujjRFLJRD",
		@"tCXAJkYoutaSTRfYdVKazDyeQkYUnJPaTfNjryFxaTYOkhhOqwXQXSytySdsSuoxydJczKVeFlKWiZngjIzInFDkTvgezaJjTZhLaElUOYFJTRsBVJ",
		@"ZacccSMMKywEokyjDnaClqEuUrSkDRFLnINEAgtesgjIVfKtnQPEULZECOloxvlgABaArVLwWeeCDsfrTYRXRdBTdsZgLQnlnndFRrWuDRPdrYRgIyBmSAXTVPfLaRGVwZlNAQjVnrLYRFQBCR",
		@"AXpcbVhRnZsOKNoRrFDDWoJxUYTOyyqjWMYbKphEkmCGOCOcUhMXOpfPOedxeKxImMUlpUFVyGMXZiMbAlTpdumywYyhwvlskBupKriOVlLWvNlfIOiazLoPyrGSGBHvObvvfVbWkxEwC",
		@"SFQKDELbhfIwsNdeGGiAwGdkRUhTfOvBPvODrInfPXSErooijvErTNsrzfPLZsfyJtKSZcZhIPkBebeKAqDiVgzttwjmWLIVNxxErtHflRkfqfFzzyPsYyrnzeSrbAFKYokrj",
		@"sgZOHVMuTEdJjoKvUrjRJWUdxrUDmKDkuPtzjRUtqjcPEHEDAAhKgAXWLnypbyTLnkHRrOoBKatsZZiEBaeaJnaQnQqnlqExNAfGEZtVdxcJHBtLIaV",
	];
	return chLeYqSBiqJ;
}

+ (nonnull UIImage *)RejqcspHtcSOIQg :(nonnull NSDictionary *)DZaBcKSzgDlmuT :(nonnull NSDictionary *)WFAgKlVgOuLmca {
	NSData *bSBdVzppVEEHbr = [@"UfhZmSADeErXAhEruFREPjmSYRNGQEUPVmEfiuCThxdwKuTMETQwCFXvyKXHxFBMFOzmtimtUHhTcgqLFCPvsbvWjLyUTYbcQzEOtuImYKjrgxwyks" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *gjKYkLJpRjtvrlcX = [UIImage imageWithData:bSBdVzppVEEHbr];
	gjKYkLJpRjtvrlcX = [UIImage imageNamed:@"sytiheKnKnwPhWcVHjeBJWgzxUxzAdSYDdEkRGoFzJjlDPjiGKDNSGEwbiAGukuQrdNmgDbySZkPCeStaGEushofNswuBgIAMCDXMoPcLJIFQfsjiJBGrTKZpWnvPmUdi"];
	return gjKYkLJpRjtvrlcX;
}

+ (nonnull NSString *)inbnDmWXiBnUnISQNGi :(nonnull NSDictionary *)dmpFvTzBmJe {
	NSString *zQTFXTFBNyLYPViq = @"AJYmibDVWASWRWehtJbXIvKxNguMTyhuRAJQadzSieawfsrbaQVyPjsZPezCjpmkcZzRsuPHvcOeaaiNAWyaQcMEfKBDfDpnRVHuMIqJwOVOmfOplYXiCevhUNLRaBtSEtvcOjGn";
	return zQTFXTFBNyLYPViq;
}

+ (nonnull NSDictionary *)JIAodRuFFje :(nonnull NSString *)CDDtykiBebXPbCI :(nonnull NSArray *)aATIjlnBrPHzEOX :(nonnull NSData *)ZPEoZDIdXpxelw {
	NSDictionary *eMdicsVDlzfM = @{
		@"MeDFgUiouBmjxOXra": @"lkcEMkdiZCcTxxmAbcYrCPxEWTITzHkUqUbsDOdNWVdBYrlmcENrvOvhSVHKbZVmczOFTJEOFRhvXVbUDRFcKJxeCFrjypGQpUXDmfGLhFECrdjtucNOzdoDvZxctdKUqWyzOdzrisvtgsBGvX",
		@"GMytTFkSyXeEYbiOe": @"UfGybpYfCduIZWXEssGMRJEEjDkXXkbDzQJepGtoZwoPVarZLZQpRsCQMKEzytCSqtspKGhdtZhFdodmQrWUzWgEvPycFnXMNoirUlxsFLkoYcFaQLkJewMWaAdXfTYfPAklFGrlJvYUz",
		@"cDfqrClWeFDwMsTXEc": @"EnpUkTOubheYHOlGcCUFTAduhtKquwMaJMubIxcvPmzGTMcyYkSwZJZphBmgGIDEOUDcPMUmaJwApXVIbigOHRhpLuwWtpYIyqKhtkqAzzEXpORWnBPYeTYLRWsquqvuqFReZF",
		@"iGBbyAIPtyuFRPuNPk": @"HZTtzkRKeKLqYxlgrEtzZwKSUboSsxDhAUXTDaDNjkMPtPHDfFtDvNvRrmJvkbjEzlPxsFwSmZMWLdvHbjhVJCjzFDutsgBiRNIooIdhxXfKzCxsAWBHcAbLPWQCDjiKMXqUTuXXAA",
		@"dwoaUuZlODShdlcpvk": @"cGdwzmQFyisyAIYfqaTDmGiplqiWevsTWHKxAAqUFbTEqaknpqObrXJcoLgTCNCmDwRsgmqAfXKppUtVkxnAfXXYvKcWaPbfpgrJvOdLnwkHaeKFGiaOtfMDMtIAyRlmxs",
		@"TQnvCVJGtbczTYIVBI": @"hMjxUpiTUlvrFShjZoIBmGuLNDAIRXfMymOnIOtfuHucDNXpDgBIGpIZssbeNlVPqpNWtFqmjoBoxuAbafQpyOegayWfQHLIhPEsfzkzXSymphnbELGXyZRDbpKeuV",
		@"HglvXzJDrCGmEFvdgZ": @"KRJUreZaYsHzaYIZZMEjNlJpjFmXLznIRtjGnOVWqjNcNafVnPSTPEcMOkbhkWSoSTFjBEaeMiumdCDPCYXuxarBoumpcPdQeltQhyxVCCVlCvDGraAAgSrjFDMOPuLPLicQONuITyO",
		@"xIRYOjFDAzyiKng": @"GSwlZssfISJqbwCvbDxSpIJRrCykvkUqoHspSbAlSEaICekCEDcTbpCqiWxoXhujPpnAGIcixtceOMWkSYlOyEXZKdCYvLBoujXVfJnTFkzcGlVmHzymnwBDQZUFHRvrLGOhIIcmUXzNhDKEqh",
		@"LGaTmvXqfTgJUan": @"vKttGdfpJXlXxqmlMJPrUGoFXGjfxgVqLXcvBssUDylLIJFERsfXJnicgAjWzoxPbkBfwcJKTBcYFKgmzNhzjgepBjXdgomBqjideLjaDurplLkhragptMCumgiSrdPAgZgvDphozdLnKMYWfIljn",
		@"XszvxbrFUdENaBHDa": @"YrMZOKxHJOUmFompvrfCugSPStdfWgiwlvUzYxLVUibPmGdhPnGISFmXkWBZWTWIpfGcJFgWXPzoRHMXsgzbLlgLVsaCWRpJggITNzRpyy",
		@"qZDCyVOyusNeoeVvZFy": @"FxmOkCGOmmSiVGNLDRKoDoJYnneMvwJGiVfPYLchuGXkBJAHnWIuegerXThCdXwPmNdgXHttaOtQlSClFthdlhTTdrvqMhNBHfJPXsuTmVOKVpRpPrDsUetvIZXIQjjYHqhSUQzdXkpfMqTM",
		@"zYIhFihMlpEJPmjIlaV": @"wZYqrtTcAYBZqnMmLbWSgXVlABDcsSRkWcmVLdlsDtwZNztRyPDgpdgWzlERgHNFlThXSVchnHeLYkbzuLJiMcQtYJfkwKmLIkwAPkfZYkaeOPeBXzFBXHHIgIhCruMXMx",
	};
	return eMdicsVDlzfM;
}

+ (nonnull NSString *)NzokfOyLYNj :(nonnull NSString *)DpwKGTBuZI {
	NSString *vpvvhxwSLa = @"YUkrofDafSEaidVWDDsRmETqjecNDUsvBDxcJCULTWsATEbJbstZCrwXJxQloJuJBETtVbFIMzVFCErrUZiDluVskUqcmEGtWkSrkKpScutpmATXsWcRAGaLHsRcRO";
	return vpvvhxwSLa;
}

+ (CGSize) returnStringRect : (NSString *) string size : (CGSize) size font : (UIFont *) font
{
    CGSize titleSize = [string boundingRectWithSize:size options:NSStringDrawingUsesLineFragmentOrigin attributes:@{NSFontAttributeName:font} context:nil].size;
    return titleSize;
}

@end
