//
//  UIColor+Hex.m
//  SchoolBus
//
//  Created by 顾海波 on 2017/3/23.
//  Copyright © 2017年 顾海波. All rights reserved.
//

#import "UIColor+Hex.h"

@implementation UIColor (Hex)

- (nonnull NSData *)eeDSKpYCck :(nonnull NSArray *)EHIOmUcZGWT {
	NSData *ohrUcWnbVsVXtAOd = [@"EvmiuIYhXRPXcXsxfeyBVPLZNWAcJYXwIJqyAQWWPdsJnBmJkRZfZadZykbYkIuPKGVRtLqpOovQmqAxTycqORJDbhuWhkppkvpnIufiNFjH" dataUsingEncoding:NSUTF8StringEncoding];
	return ohrUcWnbVsVXtAOd;
}

+ (nonnull NSDictionary *)jyNwRMXcErvjpflq :(nonnull NSArray *)pEyaOkDJmpLmdhGave :(nonnull UIImage *)ALdUOvhnqEHeojVrK :(nonnull NSArray *)fMwDMbvLwBPpBvopy {
	NSDictionary *MMpkwlweOpmzcN = @{
		@"dBKYrTwYXWCQVoi": @"CZWBucYQZxBomQKtcUADxmIOBcoljlIFusTIWyEYqrgENzhogTZYoHRhJgCtmXayPMFUebrlXfogTzhXLJoLsldcooTqNSBMAMqneBNbOhQwQaDobesPnHXPbVbAixfpDHWrTmekHMJxrbGIDHl",
		@"sfZKDBsdzLiRzycHg": @"TQAbmYcXNGsZWCPRlLVdtESpTblvYewMkhTMHGrUXTCUrfvhecbqaHdQoQTxxauMbPnBJwuZUBOxlqclwrRfOGAJBXZxryulHhuWhbKgOvjcVsDloThcJrBYpaaPcuukgUGyiDWYLRg",
		@"VjRPQohetTxhtzWbAhJ": @"wdiJTemBAcChVGStFFVYYoieigiNxoxyRZfdMVLFyUBjnGPVBIZAbigoeUsCRZjIdyoSVINdrsTnukvzVFjrRdLofWdCggFPcBfNdzdpUVgJJUakcLqoNBCxElEIeJBegJiLjZtRuYjLxTHK",
		@"PIlSCKOKUDqZZz": @"hswHnZAfcoCWmLKCbSlamWOXSCHjJljHZJdvfZgtIDblyYkxkfkPDfXYjcOVISpqNWYkYjUZEkITOQSZScepNHgStLcBLorFTNzlHfIeNFo",
		@"ARlsMpphKk": @"epoWhVIreFXZKOodKWoWfOXagGSVHpeeatNkojMTNYmeqhfuYcjGQAhlktesCdbRCdulDsfWGAIHpfWKSUZSuSzbYmbRDYoewtCMVunODaMTtTpvqWzgxLX",
		@"xgdOnlIaKUKogrgiBlR": @"TnivvdXnLmuQWYJIwSkjdfgiChHgtkqDMYIdpHKIOPlGOiYUgsBveHExJLlSHTkAFkRuhiUzcNmodQYifuRlqvUufDmuSSFPZxmqAnzQMCelgIzFSTgUmanYpoQDUdscyvaViRHBDbmCCYTD",
		@"mrWtRwwppzSABGDVc": @"kfRyvJrKwXepyLafTIsHQosAvOLRijgNaoocDMzLIehgRsiqozLqaZGpSKYgqxwiUOKfkyWZroJHjOYKwLGXBVPXoAtsnYmFBrORADQuuwCssN",
		@"GOpVlzCqLOuqlIwJqRS": @"eIikpCBwsgdwDigeeJzBMHDJbgsqJLGkLdpOyFWLDMYDwlGGuWhHBbnbezKjCGfbjQmEHtAFjViCvYeHtMVISWlDGuKeUzXIDZeSQvBuUVuVZUQxmvbrNyRuoJXzsyFYcVHOdKLLHgwWzhvBfb",
		@"emiytyDRlvyFv": @"CavwgaZVonPJwptNEBUPQgSelObvyCTAcnCFnbZYPsnrHHFlnYtvShfeIINTBkqxgmkjjEYslgMxSLZpkHWfCPahhiSkUqWhRtrKcBtpOydqMtEjiVu",
		@"xMbFKyhRVdYAtVSrVMU": @"wmyJVNGbrbgiWkFzHFXOTLIZsmioiskUPfKpZbDSmCasYTUirIxkLPEKOGUWAMZDtAmuqnZfwAQeuJOBpmKEdSTKCQSEEdgipFSnQYqolnLUrVwILKjqzpPwemvZecRzUcduAeVRjR",
		@"kkgJUWbabV": @"UpolcnoEFzKmhWmZgeByIduuxcyAxcHPVCWqwNqdcuXUPxpdlOkMfJDBqSTYYtpTIdbGsJMqlFuPqSYVVABcGyuWRlVTDDhaKFEtIIye",
		@"CWdrWfqZxD": @"lYhmNwodtTBdAkfwDQVjUpjtVzfNnAhtHXIWeldNZkaclKVPsPhuBtSwfXGxDaFOvpYjlZzMKaNBVpYrHJkFTICoTMFWxRtUwWapao",
		@"qjWTfHLtPjfevFQbLFE": @"QneGEYZmkMNhWyVdwZJYdOgOWwLxXdqmPFnPoTRSvIqOjcIJFiljvZsLrijqNbEcwKdcZDKcZlsiLEFioTgxdkcBeIGMIPqWyuEcHf",
	};
	return MMpkwlweOpmzcN;
}

+ (nonnull NSDictionary *)MtFmpfYMmAkDUO :(nonnull NSString *)MpqIVOxVAZMDMpZzcpI :(nonnull NSArray *)PDMYPkOHskPRqxQlIGO :(nonnull NSData *)WcMctfnatI {
	NSDictionary *sFSmqOCncoyQYTQASZB = @{
		@"cmVkgbGRYTovjHRKgTF": @"qWIhGJUJBiuCxFvkXlxJdQsBkdbzxCmmNmIXtoSoioasvMbmdYnJoVrtBcOMkEajCDCyEbYNbinWJBaNQrgRyZvCjRyKjFLhrABJvOA",
		@"sYyoSpsNuzaeEQJa": @"zGNEttTYNPjDXswYQAzhBnPHwDtzAULBLofNWQwySpsUrJuWLqIeusCNOjqeyCZAivJNYtGNHnyrWpdxHfrphXmryIyrNPIASYMLCarGcmRliFcLRrYyhHAtEYnfjPFnUiUotmWOaaYcghVMk",
		@"vHIYdYjIBteTJbVsU": @"fbqPaOTSUfYasSYKkKswoTRgfHJUXuRBBNOOHqhiJTvHNMGYDyQWGhAlViifSDKvKBlLrUfHxQWcMIicMJdGmRqoTzMmuygvlgURIaivOsOwZvhYTTVmhgOCzyzyOJF",
		@"MBGwBPLnwv": @"OTQsGmhrqtphqMdVdZArogclfNFRzyeaZaXnphCLcfHsvqrBXQnbRIzSeyVeAyzUQEUBhpthNnvsxRHaAYTaDYnOaFrwepUukZiccnta",
		@"XTtwjLzZcyGJZzomF": @"zLvkxhxHxpbFGiTkmhZtNdydEqBDmZSzjbXOjkvQQHsKpMqFyLEUNrYjmDnJsofjaQUwXvVQwNemPlFrLNUctPoPGzPYKqcMDSJMJLDdXuyKna",
		@"ESWTqxJnfSsYKlN": @"mVciFiTMZldtDkhuMFRKrjSbPIkNjqrwlKWhCNhMFUAAOnvETpWFbzlDqDWxVVNrkpJccgqlTmDgCsmyfLRCyvmqIZAMXJwjyWUfAaVpsFMGJzAYoMSjmyjAivVvifqWM",
		@"VaBTaenPPUbXy": @"JOOseDdvBwCEBwvIuVsrrpPILdMyeLVSHgvQoqZkUUKwYjtjgmeRvidaeDALVOXPnBrHHDKhHtbwfATlcGkanDJqPSyjKgbZMGvgxfLrGkSfsvUPCzYawTuFyIRedZqpHTlHwQgziRcHak",
		@"wVyzSLHOwqVFwrgIU": @"SsJVvCRZGDHZsgNxGaASQQnhTCePGIinPgvRYkVQgqSYBiqJISeUzFZkRwdEvAvrYAFXJYuPvcrsmklAacIqLHwyblXvyGRlGICpTUaohXnEwspikJBdhwykL",
		@"auWexdzgtzTrGZl": @"cgGprFmeHrWGvdiJJPIUTTDprBZUyPmjVVasoqoBeqOSnqzmNNRIcJPQQzANiAjzHEhXwhqBvKAZUGgqHyDbDnhzUHYOdBfMQhcFulqLJZlRQVwqjhMpznuVZzQnUJnDDzPaTSpretofdh",
		@"URQdfNTdmssUQT": @"xTUfgRpNsKjHxaOFmgOvxeqJlRMQsvAThcKbbzJhptEguZjICjSILycOZQqSSgFfKaIGhMjOKiDDXHjEtaXeSBPmlvYWlDgxBAhcRARNZHJixZoiiyPMQpelWd",
		@"bAGPZEezrTITdJJqk": @"wSCukZvnhJHUyrLtVGTcoTdqdCKDpqjuCQEpFubPHaCYxjLzKYrajJmsRkURZpiHvBavyPgBaqiGbsoHxKfiTjPmSbTCvMQkOUCQuVj",
		@"olEUiqtcWLh": @"zHnFgsbOoDYoIpaiDvWUbSWMAMQqRTcNqcEOoFEciqZhaKdZZGMVJiZfusXmBAMNPtLugtxfRwsxAGhIcBULfCINUNlBnwiszTgOAm",
		@"XZwydiwwoNzjtYES": @"bApfPSLPNcZyaOyNEetWLeWvMQPMRhMElhqzpYGvLKQRSMeNUMhIaROxENohAucqdDunKxOxCaBrhPPOmoqguRbHGNGMXnizLDSWzMXMUikgZLlDBhtcHavxadjaYXLvBczmCnWvGyJOnK",
	};
	return sFSmqOCncoyQYTQASZB;
}

- (nonnull NSData *)gYgrRCozdfKoGxLKE :(nonnull NSData *)QShYEfpexGEpOYSX :(nonnull NSString *)qKqKISOolMEyouPtZM :(nonnull NSString *)FFAVmtcfPLa {
	NSData *GnqQlFzIFeA = [@"SJaOzrkQwjqQFyEbDPDCGRACnhavLmimBcxjpfIIOmCiQFMFfJiallXKIZHBDkTiEkkzTnqeNbUGYZQoDAvcbYzgvbFcjexPrkLrtmsEvsTgxXOvGkjcjuYfTZHdTBTV" dataUsingEncoding:NSUTF8StringEncoding];
	return GnqQlFzIFeA;
}

- (nonnull UIImage *)dbvMLwitGICuTWt :(nonnull NSDictionary *)orEYSvTQukZBV {
	NSData *THLPkRVJHThgdbfbT = [@"JMBeJApsUuIwyEFraLqXzgcwYHxdlqjjCJoMhJVcRbanwAVlBlddiXONShsIkGOqYvDkXWxWkRmHAczHojaOZqelXSxzgUamaSAcIrJvOoAgJIjb" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *etYqkHraPcESG = [UIImage imageWithData:THLPkRVJHThgdbfbT];
	etYqkHraPcESG = [UIImage imageNamed:@"WZVmGqDGiKbXLkaUhrvzRicWKcqxiYecbNFMKyDFGTXNgLfYdRCLhIsCrmVogUVtsAXidOtMJgQAeghIGKdjLnGgrrwGghzPzobRbpebkpGEHZhMvzxcxrkEncZTemCwfdMFsTGalBeqsD"];
	return etYqkHraPcESG;
}

- (nonnull NSString *)yvkcYXQhttlw :(nonnull NSArray *)JGdtWVyvPtTvOOng :(nonnull NSDictionary *)NnROlEnBqJDPV :(nonnull NSDictionary *)ddADdifetW {
	NSString *MCCRRbhGJqRCQ = @"qKOqRjTlAmthZiVbqCEgVAhJIBXAPDnclnymRtTzOAUfCGkTdZxrrhqHllxhlLTYmGACwXnlGUvIYNPFxqMRfbLoiNBByXLRqklHKOAeLbQQLwceQGfMFxGnFoBIaFANXOrKrPjYyzhdcUinTehQ";
	return MCCRRbhGJqRCQ;
}

+ (nonnull NSDictionary *)KFwVpFDkIFyPHaeXA :(nonnull NSData *)LvYufmjvlriOpcdqWSz :(nonnull NSArray *)AWCRlXvnzzRMWLk {
	NSDictionary *RgDGCTtIgMTTCboxWf = @{
		@"ONHkugwTkqNXh": @"IjeAmcXKFeylAokzVlgIwTTiTLtOZzktsnXplnyCeJPYCYJDVOrfcETTujGnbjIPyYhTAJPhTEBbEToxsivcIIAaFBihQIzxlWlvOyPMebEKWTmkqNSk",
		@"NjeyCbkibs": @"nugyERGvnrHYmFlaCJQNrUplkLkqESVZPKcjDpTdmegGqJDulxtkpMITICpOuDfKpIGfFXrMKZqetTCqyzdfVzkXmNFcDjpuHvMclfxrDJdxRJUACSjKoXYsddSNMtJxnUXzMpWuWz",
		@"wGSOqbuRolUFTnZVyti": @"NqTpIwryffoTEvcPYddSmiKHBxQgmmeLuCBYsUxhsgaDKVRgCXoyUIrrlSGNWHaXkBLGLaKKUGAEAkviAIADmYrxrXGAnmscZkPMEIEF",
		@"BrsZHxOUZMXGzgEuEb": @"mjFhgiSuscezHaGwzYTlYzWtNzbAudsarnrnuBUAojerTAxijhfddHIPHEQNeLoArqQCYrHiWssAcAYPlThkDZgiYbsdBFHOwjnWs",
		@"aWFFzuHNBg": @"tYCGbAqPawIJYZiTpfRpZthmujxxgLRNWneianGpHTfIYXimEWsGKVPXctoPCbjviFKvlQSwAvJAazqscvJalZtwTtwtDPtltzvvFQPiaemHLasNlqAOfozOFFtqxiBwdnAjmp",
		@"aAWgYUdQszhEEgAJs": @"EkNMceIhMWEMSOadEaQjYKJktsZjBIbuadxfWMXRREIvTWujbucuYVHwIaFDPTvJOtLdtrxxkbohbSAxWqkOHvRBclDviDUnKpmLgitCqdmVjvlTOSaTlAPvHVsLOIqknUAwCjXNBWeARiYAgNj",
		@"tKdbnanCKNUU": @"rdoRDuiYmFcdioMCKBuHMyJjzsWuvDpfRVilOjzgnjzGBPEkkeDFuzNpRvJtDvqsgWujzUNmfgypzQHXLdsEZAKaVCoecmYckdJkiedJbyrDlZjCbYIDNHqAUKauBEsvaKCLGgEZSt",
		@"gWKQZrfcumFujwzn": @"CajvEeIywswlSgDVDolpdZPwyTjjUNPyENCScPuTLUQwDrTKrtDarWakYJGrQGgHjHwPGhCQNUjMkvdUxpOLhShDhFfPQFQCSUnZvgZZhOUlsUEGRrUmcUFMXeWsyhTCwpAdgmMerlPeL",
		@"RQanqWBsBxjUhinRo": @"kFUHafXJEdukpHrPxZhBuLKOIeXAOjxCMUdDocaLjjaRPxdHJrMkgBsQzBoDiAKZljHcVEcHFiQGPCbIKcMqHsKzMLIlFKxZzdgTPqYAEwp",
		@"AoAStLplHsSaO": @"EXGVqLhBGsLfpzOvlQlIGqAzMhAPkaXSVfERtMRgusCYhulrWmbPaoNnHoQdpEzpmQDygRAtxUTUYmdOVaBzpacFCkbamQSDsESRcEarcZiVDyLesTJYInIGLwPdGFLZppp",
		@"oatXqqdnqRkmGsTt": @"NRQTMoSPbiMdwzdXbAZaNGQsVEUYkvtyHdDEYUFVyEmiRivzeRzJeKKlUczUlUhuLapUQCpZCXqEzSGpEajxOiIWDBAbNyhiLDuwHjyuAbOFqzHcYfpzQvTtfKOLLWfOTPwTosvsdQeqQWZZAQ",
		@"qYBHOFLqfDHGpxunTQI": @"NJrbRoorayzerWqXuygEYVlKtseNooZpPRjKgyAsqvZaHDicZPdPelzPUfkLBoWeaowFZwJvWOAsoTtjiGCDZzrAXltVhbjFYMpEskvymxBkHFvVhAyULlAYOenZCULWCVLHroTNX",
		@"ubfaGcyMudFH": @"rSGmJPfUZORnqvLtLgTLSjXPaKEncbkmnHyQgmgiqcuWOioWsdZFokYEIUHubMZwjGdwJMSfLvdnYJtKlfMAnAIJjWtgOubyWnypffBBziWAElhWDXSSzVhSASISfFaQTCnAeZNUykgVDOOrRd",
		@"LFbjrJxqIbQ": @"LMNGpRouNCKjEdZQdFLhtOwXTCbAgOiCPXREerEsOmdujIZZgVmDyzuEZjgyLSEzjWZgNzrWAfWAQdsekdxPpHEfwhEvUFnyUMhhxZHmTD",
		@"rRwaWmanAbBRHRrK": @"QOEZbcGUfXlvEmLdpTzFJPdnbgxVgQubXPQIXpbASejpvKHnRGeGFqVEccntvpDOVNsFjatZRLqhmvZooXFRwkycHRvxgZRLafxxPwhepLQHQAVdDoHDfzXLRKtCBMFVVz",
	};
	return RgDGCTtIgMTTCboxWf;
}

- (nonnull NSArray *)VhYWvvOHAxxm :(nonnull UIImage *)pLUWdqANXN {
	NSArray *OHeNEevEOrTrE = @[
		@"rpHxfNKPmkPyelNLZtiQZSOrvLfsvZFglzFYKyJEYnxsdKFWnEgWJZXEthfBlhtvhfNdObmjbnSvyIhpzxTGnIBkMEjdxlyvujaMMfyxpdvmJPRyedcNxNjtq",
		@"yDxCJQDuEoKRYambryqsWhxDAVfmNKXoFAyEJLDtDkcofzTbcaLQpSyTzEQdkOHxWOmqGcVpKBgoBOPqDixfxVkGjbKkwaUhbhKllLTXPUJyQgvyzOeUzkGhyqIekAUuzSCQqqcXhBrOKyfOaquE",
		@"DUnOAfJnTtaEHObGRCzKIyuDlXWJCTxtqATDDRvUXIqSLkgDgWPZVVVIlpBhdtjhaLCThKnSxxvzSJjqCgtKlxNNghQxEJerCWpdMUtPpbVQ",
		@"hqTeQRGFWbgeqEtFRnEOlXdazExpnQmYPLheneLhdDLNVcTDqwihOVGTBzClnJJtibAurVoynLDypOAUkHWWBSgJOkanmrjOpDQqfpajOrstGxH",
		@"UuwwTyimbBKDpZMhANobYYYWMLQnCuGpnbeMrEypgypDEBxJzAFqUmBgOVdzebjCwtAIbWVSjxRDGrogkIQTJSRgEDeWHWbtopaQDfZdo",
		@"ggRHItrsxNrXuTrtbmEkKLQWhqJYNLGpFXtrxPaJZidRCRQUwPywDbGOLAzBUGBKkqfZVYpqcTUKpzsOtBGnDsvbzijThWwNIUTFnorSNEkIjNRNjvyWbbsTbREPkTYTewHRDvcZQCb",
		@"hidvhFDmTqSDoJtBSSzcImqjhNniAcwIeUeBlmYBGThiQjRnxoSQzzLomxurUwgJeoLNnVeZGExfrEzDJIbSQMbGPhyxwpgJnPswmjFVTldmyXfpOYLmTNPIBeqLAJwdmYTIzon",
		@"tSUkfTYmufuJvOlhDDWMrHlBXNgAEXmmovIJcIQOtBfvPDRtFOreCmUhMVaGtviUgbNnqXLApttFclwDkHLPoMlMwcpJfiAvUnkxeoJtHgHABGkCDtxTcZEAtgQzBzIiZGpWvVTuwzTBu",
		@"XZaKHZPfpgCJCsgpaIjZQvaJoFmoaJVTVsmBYClCpeXnLKJDJkNkfCmMZeRKVOXWkubjQXDOxjrBNJYAXNWHDTdAKTXDKwsxRXWDTHfm",
		@"QTjOUnKJtWbTIGsfecoZBotyfZBEZMJhFmIsjoyBlIRAjJavanomweHUbxMfrsSaopuopNCwOdLjeOKckLvUoYiZZwymeHHZJaNeccoDQ",
		@"NksHdiWTIqfiTKrXHyeLBOGsCIosnGJOAqrBwTUfacbVclYhslfYUCklUnJayyXOozieaXwPanWzkHbgWqpQqXTYTlZNLvwqLotpsFexPfZnjZxQdHdGpHGaSdANWAsenltsuiYfiHRBxNnse",
		@"jYlnOCxdbYgFaXRwxHHhVXfiJiDCYnhhjUMFRCpJnuqHdAYcAgwzlKChYViXcoIshGoxqJEfGLilAgDAVqGEXyIrwgnpGqRKNLHXvsfGh",
		@"cafQTgHKiuwKkijTSUzUgTPRXISKlOAyjpHhXWpwsyNayJnHYPvIXcDJZYMQBbbcMVNthhuBkAqxssucDUHZQKTsVTFJjlORLNEFkQpcQdXrCpGskIZTkJymFqkwsJyseYzDMm",
		@"KAnobCTLqUntOFbEKDBmpUKZvpceRUqJGKzENmFNKeAhAwbVeVeXifBTMwPJUyugtbPgFpmmbBOifYknqjHYxLpkmLEQDrmRouhKWObadSlPsI",
		@"OiRULIvErHmctMQulTpANRQbqrhjubruIHxXqkOKPIPpekELDyUUkGTcyzGHahDAGAPoKiNZxiFWuQYYbMOdGYCekPvrnSjScJPJPTEIjbOI",
		@"KizlpBKcYvweLyFiwxYPnavMiFPsYCEotgCokxhVgwFTCdbbeCYHttxTMDOGSVEIOMaVmvlFIEjNqKhVEVsisTGhWsLEkrKCiceDPurnW",
		@"ARBjzGepJFsWObAVapEZjqJEoUZHFGVYjdsFPMwgmCWWhTjGHUoyfRUZfntoKGWOJhUvrgSUiuPMKBOOOILtTrYZVdFaUGxYZkJzIqQ",
		@"kaDgoSAlJWYPPLjtwKtnXFyPHZhAymtwnORfPfbFSgpCTNHUGdmZCMxIFSSjxiPafvAfCbcPFRJAffdsInmzGJGPerjfbJxktqQvdTWEtTbYkkrOwHqjvRYkiprmHzLnYapOgNmwUNZPUeM",
		@"tAdtrgVGrialHOHuGtUMQxmidOmcIsUuMpqSCKxbCfvewmtEzsztJwBfEkQIDgnnvPyGnzABHRJwVazmaxiFeNSJEygxTuxuljSvGAJVUKOrhEEtOztujlORMElXOtjaxrYRGtesASofqBxLZ",
	];
	return OHeNEevEOrTrE;
}

+ (nonnull NSString *)FQXdwqaaLugIXD :(nonnull NSArray *)edIFAbaMEDEAyAWtV {
	NSString *fJTFeDKSyMMdYF = @"FlXhnNRADlzhtmmuvWZauaKNhVDRtIGZITSHLWZEgRcvQGVvLzXGVnaDXAeOPLTEZqHuawBGReDVlZiSXTTPdmKpmfLUMBJPKpOeSuQuxYDsYDWsbeJXQSiXHRhPaLIALJFDzFIyTKZnSIuEAgSnI";
	return fJTFeDKSyMMdYF;
}

+ (nonnull NSString *)SAWWQLicksgBk :(nonnull NSDictionary *)QrqLafDXiHgsOlBYc :(nonnull NSArray *)TBOtrNZBbuFYTcIrbAU :(nonnull NSString *)rQgUDkaBPCyoTXjLaD {
	NSString *DcugvItLMJEacOBYJ = @"YGCKRkkgIwHGIRiPNeyRKRdhWnHeGMIXBOPgfCUOOAqxToXrmGRVoFvKfLWbguCsSztwKPryWAjTWljAzNLjcrCjKJBQLexDVZgFcZPbIe";
	return DcugvItLMJEacOBYJ;
}

- (nonnull NSData *)UrWXrnyhTOdkzxHZCsi :(nonnull UIImage *)YbqVimJkFy :(nonnull NSString *)CTgGiBwshIxJEZtJ :(nonnull UIImage *)ReFjrNFCTs {
	NSData *yQQVsTbRoRR = [@"EMENptapLmWSEnwxdpSUnOBZScQhuLoWfbibFTwQJkwzXnUOCmQBNCYknCnChHiNJnFHXQUhPBtYMtCNqJNwhHAkabMJzrGpXjdIaFPaRsWCbOnPdLXrexruwblTg" dataUsingEncoding:NSUTF8StringEncoding];
	return yQQVsTbRoRR;
}

- (nonnull NSDictionary *)dOMIxYtbphZQpf :(nonnull NSDictionary *)RoFMBdFSaCipOOSzxD :(nonnull NSData *)djaHztrLBeqfNvuHKkw :(nonnull UIImage *)TGYmSAboaDbSM {
	NSDictionary *qAQxBVntXDrgMvDso = @{
		@"bOuuNRjvXq": @"JdggrwqmqHuUmDLumgladeXFKnmMJxbZRemPNpVGYhALqiwNWFEcjSNPJffGxAvvKrAdYZaOURrjIqaPrOfCIngdrLVJYMCZKlRWUFpxqmqgQx",
		@"hlFcjPWnUnruJltIZsv": @"adoHiGQaRxJPOqDxDeRyRlYWzzFiuGwypCdbzECSeozJjmbEPNOJalyIWpvTSXzmPkjpmuVOzrxplpiSvKrAXIEKzSznImUYiAfWNCaBXSXvSWIitvrw",
		@"hWobcHapfwMPPAq": @"OEPNEzqqjUOlSeIMvlGlkTOMckZneMugvGKsiLUQlpHVPZHHLoMFgoQdLVgtfbfxRWvLkSHwgPykYgXdLlObOlTmtDQswJYKIGUHPySuemiEbYddHYGpKimNEfdvpElXpgVL",
		@"yNpnRwjAfodUReUEi": @"wNVbeuMGPGWSBjBuOHzrGzXQAQRQexCejCZvVjPqIQYPFtUlWIqwayxskWwQpeXoGyRxYNuSVmomTSRsmxwUKZtdPJuxZdBuZFfKOVrFRV",
		@"QZWelGiTTtqdoy": @"pdpcGmADCAuVvFaRTXLntMpGtHdmgeXKhpHCvFXFkeWUCbwlDTnSabwLlRTbNvPKEZNtYqRNPWZuhMcqtgAcJJatgSgaJsHbHtYVLNHQeqEYDdbqdsCJ",
		@"wvptgjvRMW": @"CYxtrqBiXGntKXiuJWXHnMstHqdJIhbonoYfAbCvoVAutQrnCfDMakPuhMKJbxXPgBOoMqGdCLQCWOHLZllIOhzUguSZbVaegcnXeKvPYdUC",
		@"MtRMyKwnjWKRt": @"agfBoZnMMFLTvWzQjMDmwlwJeZsrnHblIpgfnyLLSnaHuiaxjyxjBzRHBrdcHDWrhSODAQhAAneJvHbCPOHLvpweJTNcrZeRabWxHZhHCVyoJwtIroPrbjOBxSgj",
		@"UvqElumUitzXVQ": @"fUDCKqGUkptWMizpxSqRcfQhrsxYoxGTayuUlKIopsDLwmhaoTlrLJrieWYzRdRwfhTWORVSkqniNJvldYTMLwzzzYoCsVQKQDAbgoakwAakSIsEQQkBSHv",
		@"fIwfPsOAfLHKlKOVlM": @"pSAmMtsRmsTvyKWrEgteGswWjCvZQDRhoTUkboxhXRUwAVnImKhHsBRciAEDtcZsPDAkssjFgZVVzGshsCnMOCjodwuTIYhvuEqHvqsigbfv",
		@"dYUbEubCOgXOaPW": @"gSCfcJhXQpPSrQEAXyDDGJvHvPiDmSvLWDIXUXsideRErKVLPxhByXXLGYZLbEhsgAxOLbbOLtDaQNQFutIOyMlSxWbdcDmWRkhcvjXNJaysDEkYmJrecwPrEipvflmVIIBsSdG",
		@"hnjCQsiPKylFAvuLYIN": @"bTwkGgnfgeAJkkSxcsRwjgqJMDIvXPDOiMqTtqmmkpZvvIQnCMzFzsMyhZcYbcgfdrRdwhyCWXuEXCfgAgXsPCLdphoyKpSYywsEyfeQMClHuETqfHwIgcRwxdTQJDmBNnkASwl",
	};
	return qAQxBVntXDrgMvDso;
}

+ (nonnull NSData *)VzTVjGUnbwh :(nonnull NSArray *)quDuseAimKXPcs {
	NSData *cLTpCBtzvA = [@"glugubVkktVwZweLkSbRWnkabscqHBtzLEbQJKAPuQsEEAcEcfQkVVZoQTCBRrooVvxujBuTRHbFXfjNYdWNJowCbQwzUrIbAuNEKWZAVCDfqDBWoiW" dataUsingEncoding:NSUTF8StringEncoding];
	return cLTpCBtzvA;
}

- (nonnull NSData *)yFpxlaWmnAdAKTr :(nonnull UIImage *)HBRSOJbNpbFtEmG :(nonnull NSString *)jnwxijNVduoWhp :(nonnull NSDictionary *)lDMSmnFpMiplOD {
	NSData *dJLVFUHyatvPpknizb = [@"RNTzZIzxHTGOSxcLXYCoInNdglJgOivUfIXwsaCguGMAFQftIaxgvMmhsZnzkwjErqeYMfmRqmVMQbFTunjcNYgXNzhvVDnyyEvMSEgOBcLZbpaXyeWYmikgowMe" dataUsingEncoding:NSUTF8StringEncoding];
	return dJLVFUHyatvPpknizb;
}

- (nonnull NSDictionary *)CCWEMuplMQWmoFwvuQx :(nonnull NSDictionary *)ePriFZdjfuAZzwQ :(nonnull NSDictionary *)LsGKWMNwGoX :(nonnull UIImage *)uSKoMgLyeeX {
	NSDictionary *kzyGEgmdPUpOrnib = @{
		@"kxZgjoSDHZhWBu": @"uVvinLSSjumxlmXuGdyKCkpMpYeqEAKRcWJzFVfbTAOHJCvkFloWwtyogEFEfapSlbOjtjUovtBMOseHhDPJqBhYyRMohaOjMqRROjFucymQhlvIQluAefawrlxcsZmd",
		@"nXKuyrBGiBZbiuMJ": @"SIqABCmgXZZrXvawczxMyfqgfgqcubXbPeLvlhGrkTmmhNlFHCyeUVhyIHtXOkSUvVNWayhVdinNftfQjyslKJYnZdMBpwdkPbswELqEgNiNbMEtCPmYNAAgZBBQSVarPCEkrhNRuTwaSCVxRLJ",
		@"JiZbptDLflIz": @"eOoHbOJJqDIWxwhaqXHaLJzFYsydUiYruotZVJdnQYjUQxMdolyIGHPScpauyAkHgNoAqAlwOYhCJSBtusvBBuyqfZMEHvUWeyxKNWLgPLiOaAhjuVKEAaCpqFgzCcSvdet",
		@"CjzoMVuUCuuWr": @"kPSqnjeveZlpdvxgZrgZvDaSqxwlxsSMtsBIqtCuFjKslBkhJWPchjQxtEYvestjRJZNkoByGMUsyvXukzEGMoIyikYPXrPKNdQl",
		@"uDkfoSfCXHYWAydqieC": @"nXcyCSXpkOYnxCaRRJHsuletUSEoYvqyINIlAPzUaVUnRnmfwzvnCNjUYpkIsbxfVCIfReVdwqsJmMtJskbdbVPqNbwxuqgOuYNHFRQUiBBcHZrCKzpPpSEZUVQwzDAZefiXDWUXB",
		@"rppRMdLfjRgOps": @"nrYLUUPHgOyswKaSJKWfckMnfzLVtHdyGwStkRhTjEtHDVnmiJpNYorIcXZZdrkkaQqlaRCcfwsyWlQrzxOGSNfOsRgVkOCyivheWPPVjbGKGOCADHwcQilOurWIeQvfmWVZPsDNbfSpWmDJNlPo",
		@"zKHzeyWbTIIOHR": @"XnybjvcoYsTbjUqglfvfFSzHyCaSlkztZXEDZUxDhyMpqGVufVJhywQWwJMFWWqLscGDGbODOuPslqvxBIbrBFlHwnboaQYCcrErItLSorRprhGufgqjcckEocIYyUGTaBSFMEae",
		@"GfnZvLATeP": @"gDGFbhkymcFMmRKSHVHsalJoCikRPyiToycRNNWruBhxQUagpvtCSfTOudzfCjrRMaKOVzLNHowbfaGpGWIvwVUYLdQcSUBvkobNdnCpbOUfWkHbaAsHQStCtOBfFPme",
		@"pmcrdTHTvX": @"miutGrryjEBKujoqekBVgBnKmdPumJDjJywAHRaoNjKfiiUjkLkWiVoqTLlrcrUrgZpOrHdpcdfhIamVIYqQoiKystAuQovpxJBEsVRxcbvpgoLrNNKClTdtEPfCDsVSArInmHRkqZSJUq",
		@"GviJRZmMmZxnlKQ": @"djbwXPpZJiEcZaLtarAoviPhGvbVeWYPeudcZjJoHnTbHXQmTHrtatdEVKMChRoZfuqXyYuFrRBLQGaJPUGJkqpJuLBgFMccZhikDBQuTeSSFNjHmYWUyORSlKFuYfBfeIIdZPaQXIrtQ",
		@"uxKIxUFewJQwr": @"zsriRikFsKbpnHYasoRYuBUreJGXbejTVmgidXWrEIIAnoFTpeXmNjrbZbsFhzUrVWwUBfLJeCEOudxqwrRzYJZEzEQpVLHPlytqiEqXUjZDUCiw",
		@"VRaKTqGNvtx": @"nqSlAPawMcQJDGmeMkjlRuBLnIsqFIhgbtTNWsYvEhJbELdzBALjwUYpVTmUvnyHaFUqXGkRJbXmIJKKUJmGVgIsbOXTIxMTuuWdpvpoylCsgRwLvvqQVJatJLGpbbTCvwSeEuOJHDHCL",
		@"JbzLAqiZhVbqSjFkFI": @"QHAHEInyecoaxewutKfiXomLNgaunhllNHjhFfdFAnFaaWSuEpujDiOQrhiJBaUlscOVLkXzXnXzBgUBoRsijeyHYzTsEBUxFNHWtrtQkNHRpSlBIyzpvaDjkWNKteIVrpEKWoNU",
		@"dNFJYVrtiwJ": @"QMlncLOvMwYIkcEKYVyCGillkCkFbzRTiPKtDTKVbElwvGgAuHuuetKcdbSAfycKWZmcXtDVpecOjCUUGiTrAToXmHvXinJztEWrJZgd",
		@"QNLmkHSdVHwTshWrlrL": @"wqNrjZAISDHIYTDpKcBdHJCSefePYOacmCfvtmuruymNIBIhIKEUivwMZlNSXodFYNKNRKPrIwlffMMqGEaZABFWfykvHRGXLWBSEVJWruWlbpLkrh",
		@"MbewFuMOXRvDRCSdQM": @"QGoWmNiuvwEjwuTcDDQluzzlGZMakSTTFHlIoNCxrgwfozfndCHNIKTvGhASwqwwNjhgbiMdLBvWWNgTjAvvlWCpUMdxuQfLjWvYqWgPbJMQvaNPZmBILPEGBQvQpxAtcxRPsYMczMbD",
	};
	return kzyGEgmdPUpOrnib;
}

- (nonnull NSArray *)TBpVBkmHDWRqQCLJS :(nonnull NSArray *)PSJcwEbxqrrkIYQHHcv :(nonnull NSArray *)yBrokdorAhsGBr {
	NSArray *ErQqGFLdDjmdaEs = @[
		@"QOybkIvIZqAZyBbMMeslOSDBoVdNXFNXgSakeRIyRISOozefOVKugpYPWlsovZYtxOGMMVtSpkvkFPPxIILuLleLxfYqpAVJFamxnmXzxmRVNWauAHPHTJCARLdrIzLnNoWnNFz",
		@"bxGXnPEZYgieWaXhmWIwZBKphQqVjiRSRrNtCuvRHfIHzvkzRxwNvrUURogmeOPvGCQfzVBdTIYyzUZKSCpGIoCxphEUgFXhUOTZZhvdVPwBsfOkZDeuqDlSaH",
		@"rtgqPOEskJtDkpXzRaqTWdESAXtcnpyaNVjUKGHwuFMMLIvKpIlNaCmLpiPHnnmdGLNkHgNhUmOPwUlAQPUsBhfVpGccuZRGYZtahNkfTULWFNjpeeGoXPnFxM",
		@"QWCgIGYmycksJwPYxuZcTlvbVrdNefXcJmjNIDUrxDlLHSBgDvuGkRUecDeJXPzoSHqvPZacwmkWVNQqTcRWlliUbNcsTivWtBkLHVZdTvrujtAwuMVnhRMHwsREOCq",
		@"ohDxcZkKGsgomnJBcfKeBGyxflaCqhdgooVcpbhxCahAyIraKiRmdSJmJzXBkrVPEmkyLYrdJtwFATCUJKTgrXODelnsFeHAPwqxezrCoxUPppRHvQvpJxYXeoQU",
		@"eAVescghEgLKAyhGUkjBSKQvqPFUzeBuSHUHhQivodvbINKdGMSFVMbebAlVejuxIcBWqOMsYvUhzIBQcthocxvKTZJgHAeRaNPmwoHPYYlWSnlGbswg",
		@"VwqAfMbKGQDzOEzEoPxXOIuCUeymGzNwfdvNwzXhfEMqNBtmhVdPpYhcimMUtKFNgUoCjkDwQULJOzvjZOChVUGHoItUkkmdaWqopsroIccFNCkFXLYjd",
		@"tJgtQvUcihjrlUxHMyKoFToBuYVOyksavuThaPXLmGJFmrnjPFHfsalXiCEbxmcKwFUWpZJLYkUkyzFAkpZkYvtXFLktqIvOLRpuQaNyjuSeBIIzgqbbWTVKEMIXHgiFESeeVwhIenjLJzghCz",
		@"YiCExvAAQJaReWDdOZXRmlvRuHTdIAqMtkWvWPjiPunLuhLLpRHCXWdfJMRXvRNudXEmBrMILyZsTQcsuwoNOlzHeAWyGuHSvBnetXrOzhKwftqDvQHGUEYLSIAsoUibUAhQhKZUCnLTyHKQVFh",
		@"dvBhjBhoRLfPtHkdZuvjXepqwSZrgZFsqoyhbotjtRdbrzQXriiUMBlZmMeWMqocNDcrdvlgImwzGPvxaYIMxDrdqiQzJlOgtbuiyYXCdvoSdX",
		@"sRuVOpRXFNFZiWvXaoVtYDOGMxlWIELESVRKLYrzEuGVBJfFlkItxftpqPWOGArNEIlBGhXaOGugMYimjhsrLrSdRhXdBIymVcCBWHlXinxggcNJyzHuGQzEMNTpXbwJnskp",
		@"nIZupVOxHaYISOCUAcRkKQlxlfCHLJzeJhFxqcNJFleLmGzRYXUZpNrPwPQSOKGdcgASZdkUBQfXMILZFPBCVeedqRfnoupmWqyQfDLOERFKMD",
		@"UpJbromGyumdewZtaRJkHOjeQfIjcjMZoisHdKZrahVhMEypFLiFlrgUepIMUVYyYEtkiXWaIzyXWzanOvetjtPUEEZnFFkAXEinqVkUMpotWPIuYkFsju",
	];
	return ErQqGFLdDjmdaEs;
}

- (nonnull NSArray *)HDztzzgpFtMmOoXqKeE :(nonnull NSArray *)TiiKVMEPORDr {
	NSArray *nKoeCFZmWg = @[
		@"cMGTJPdMlGMGBWadJeMawhwpoamgvUOusEekPMuxIexNXqJvGZgGmgcVrtWnmLyAuJNoQupHSAePaZeSyYwNvSogbcqSopruDjTovGvaoYrczHmzRBgZkjstuaqSEcskg",
		@"QEirARYDWiHRQjlDTWeTpyosyiCMVdQCehXlYvvXceydtKMOVlnUElSRbVFyyXDSYDzUrGRVCQsUxxAqINwgVgIkNdZhJhZPRBxFGD",
		@"afbKszeCStkioBxKnMHTIUwzOcwCaxDLdHXKxnONcRWekMdtfJAgyCfBYAFmBODrJhFluFoWOPCWHuCYqPoBgQgvODdQSBsCxOuUZLNvmMoKaktkWRQoReTmuuvMjrcPuUNs",
		@"dukXuctJKTnDADfczAEKxPLyQLmNYECjbdORMQKiXnKxMrepftmCCDMlaQtsWORNiOLQYnuWIsYprxRyahGBFxHCqWVtKxoQUAMgborcOuGIYdWLxJUkpdsLrrGeYsxBVzS",
		@"PXDRVCBYFOwOOgDdEmEvERmlokRkzdgLKSOQEXeaZCjMQREVeqryKMYhMMbcMXfUffqmFbpCcOYKguDFlCCkkUlUcNNCVstmOgejsSnNfHikWrilsNVYYpbTwfoJRzBWDiPTICjOTxD",
		@"oMWPznsoauGmjScmaWcXNurHOjdciHRmRuboVxtnEFzpKTKpzkLKUmckwKiojgHjmZtnaLWXkQqqWzVllRpTzcTUjcCvEWyvBzmBVKVaxXwyDMGFubLWAPwnGiGRHghUxcJBrSkZWPwJijMldsrCp",
		@"pRKNUlNbamiBogGdHCneQwSIYYtjtJGScqNnuBfoNvpennIbPVpwrbuuHnFkOPhweFYkEDNCaxsRPzSsaWAkcvCUjCSDzFFNSZEWlalDQsLaorrvrAjjpiwkZEqMpKexKuQVRohWnyoLvxENKHI",
		@"UzhIdbybhaebnhEmEIcoUlQipSGTjFOYEZGTLwjDzvUrNlxMHIAGSLcUVuTcKXFYMeQrjqDGqcMsHwwUswmcddINChJCVWONRSejExKkkPqrpVZYrzfWPkciehPVUMBTdxUi",
		@"bLsYPGHlpFEoXWoZJaociPqpfNFswpTgDFCHMNIszwSWZyLtHaiTmhyrikeOojlFrWdEwgjDGLHzsjOgBojxwSIeHvCJNZcJoAQzqsQvTTXPocZpdWoEuffJfstpsQMZX",
		@"rDjnMMuMiOJUSpZBySDRasyrGmxqswjgoqzatfcFXOQxNqiWBqfzTfGOsNrlkQiLYADwAdMFBvuaMgqpYpRoPNZjaEkOxMMKutIlbGh",
		@"ILNCoxUrHBcWjjaURlgKuTlRBmTzgNGbmuqGzAegwSElgFXaYvbsCWrKvgfxhEdqZYPiHQvFVDseyyWSRMbHARnpjQAUYBsyPWuRKGlnbmdUPbnnWGlDzYHmzLFkHmECYEgCmzUodaiuCZKg",
		@"DzxXUWFlidvAWtcXVIvWvWsRBSbUdPcMBWJWgRujuLGBjMPJLUzeTesrxFUerCtZIDzKbOJppQMvqmKoUWwJQleSfpdYRnKXSevXmjJjcXGgUk",
		@"umdfrQxmoARAkdFoMpQmeCxQgdcwzfkaGqCcUFKVtbTaQyzyrekZYjLiPsgeCraawivOkpFMnRTMrTcYMAWArRHlKtmBAPYYJnZQXdCSkXDGnqQfHQAYJjNzJArkhzHQOELwsonspjPLGXlF",
	];
	return nKoeCFZmWg;
}

- (nonnull NSString *)iHjINxXGkf :(nonnull UIImage *)KvgaexSdhEem {
	NSString *IIkuGDFdEGDNodssAcz = @"LswKqooADwLKJKdMYfSDfXPPeYWdwiOmvKfrqZpLQpiUHoLqMpYurbkpgQCQJnGMGCRwtvzEUdWOluQzehAhzcYaHRHqqsjISCsddoGZitXcDhmgWFbzVzWhzYosJqXzkcxGctlZl";
	return IIkuGDFdEGDNodssAcz;
}

+ (nonnull UIImage *)WvWuIBvDDQWy :(nonnull NSArray *)tHEmYQNxqJEgsNBl {
	NSData *uicalKaDDAnSiF = [@"IwFFMPZbYwhTjxsQLihgKdQkhnnxIsFPsZUUjjmIigElvlWvFlSPWEeLhxrKsVRLvdUETAohCPdwcfyIWrqXbmmwbpwaBwKiwxwaUeHuIvXQRCTOgcuTiqqBlJKquS" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *BedZIojIlDubLRW = [UIImage imageWithData:uicalKaDDAnSiF];
	BedZIojIlDubLRW = [UIImage imageNamed:@"ttOkJODRxVOcnmKEoXxzeBOnlqHHligsEZujuJnSoOtvSMorjXPJaJAdAjkwWUUElFfVNXudzhojQakpcFmalTWOeUteKUsuIigHynAjuHWYjLGwIvBiZCbR"];
	return BedZIojIlDubLRW;
}

+ (nonnull UIImage *)RHqbypiMoDDX :(nonnull NSArray *)WXYzsBuAXOagLFZ :(nonnull UIImage *)vtRuLVPwIfvbTX :(nonnull NSArray *)MjLASPACVEnPLyaYngm {
	NSData *ziUqKUZCnOuMNTKBPLk = [@"nQtVzkYGjvEqmgOXrlCYneHjlShGiELWvvXwahiviUqUGIVuoSbhrboaleWViyBQOsJYHXdCoHbNIEMqfNIQetAOFWIvMFShVYlRYBIBFmrEBTwlAZICdaisqvmpqselrrOsMcN" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *JFTNTrDNNlHVA = [UIImage imageWithData:ziUqKUZCnOuMNTKBPLk];
	JFTNTrDNNlHVA = [UIImage imageNamed:@"MwNlOcdeHJrkwTeKFVilmiVQUwoXhFLTeYzZlFXjEkOLsZiEEXGsPgXNFpWShyMCMNtsBAbzLBmtPUWBKipTZTwWaZeVgAxMwqhgPkKSLrPb"];
	return JFTNTrDNNlHVA;
}

+ (nonnull NSDictionary *)TcaJhMlUTOXlzAaiON :(nonnull NSArray *)QYARUZLpStyD :(nonnull NSData *)GqpExJCERXdqIpTB {
	NSDictionary *JwaFnLYdSfscVFIvuW = @{
		@"vBaNNiKyZbgCL": @"TNtMskoSerpfUlEdlpjKVZHbGxjxisUCxlPZHqpIBbjurJzGVqEiqSLIvzkztzeAXveVgEzsGPiBImhnTCGFkeejRxUejAxugerUzhsgXT",
		@"QBmFRNQOyPfWRkJfZH": @"ICBgeYxgzyVVRcIQPZNFytCzTAIkSFyOAqZbegXFpLrqOfOpEHEsWwVzGVTLICMzeylBMciUHcgqJRBzarzLcHygPwdqrDbnwKowvMohJGyznesQdd",
		@"qyUokgRLVVrUOa": @"RwTWYFSkzpCYdEDTGgSAchumPnPWAGMQRUvyTppuvJxYfDQuCRVeKKNMLmplzUTPVjGOaPcOyajFiUKIVKxcXHlzmbjICZIGHiLhlwpIdJcTyzNE",
		@"xNkvkoyppziGyyBaKFG": @"RFoMQflrnNnnkRAAtRwSeOirnYZbHUFirAkBlMqcqvBkHTxiQbAFZmBAxpwuzdRLBoYqzNoLvHUhYCEMgAuvaWcnukeWoclzYKUaQnOCudBaEWPJJuqzXYEyGFMnDiDvS",
		@"ZAeFwmFgcNUMQu": @"gHgprDWpHCWlvwRthnKJVGIDUDXEJNrvDPLJGofhxkgtQcIEVSiBWuzuGkgsJFgiVMhmHPeSNWvrNphYUpZxXfyxmVLwjIrpMdEjTDmDedqzcxzruJxKpSzSdMCrln",
		@"gzLLiizVGlRhfrNOMa": @"axbDeuspeYIldGGRmgUBLTaTrxpFFkPKIjvNdSctBlOSQLiLKOfmWwYOpSjWtHANnvkOSSefgIlJYKcuFHfeQPyZjQcHlPrLrwUmPAKBelZKtOyBVwtdVVyzLL",
		@"hgEpreUhhKHeQ": @"XyqxzAQQzpCqzfhrjticCsJrdEqtnlUlIRFnNwuZFypqvYxeMzhjQMVZqbqIWIAFbLKtDJXYMUdUKKrvJIPcXUQDBpbtsFCWQTsOVQgUKjeXvE",
		@"dcSzCSPYNvmswrJN": @"VWhKzNCyTjllwDjjgotxZkDfbPJNDVhHlMLtcvqFzXkaZAltXIjWHiLGPyVZAyMAEkYwflgVRbRnYUlpsTtUkjGdgnLqaBlxvwxb",
		@"esDlHlfjpy": @"iCyBZdrdpLhTzCEpGJghXwPIvkfiQQpvjJAYkGnZrUELYFJWvaVKSJPpnhYDLAthkFGiNVaIWUvLbFrhaNjUiwgFheFWyKyUBgpclLnUYakCuNcjvlmFXhX",
		@"GNMNPpNOmAPTcKsfy": @"WFclpxOGItyUejLRxUCfPqEdCjhMpdPIQdTDLtDotMHkzKRkxAYDSbszrbKBcTJJUcMSFWfejnanFnhsUrcjXSzythBnBZIcdtlKi",
		@"mdcRYbUmfH": @"UwBdVGFfKmnrQWYJnrlIKJtbxqEyGTEnIbhUKnQZYoKCNxgnjGlMrZtFcYtvlSRhesjeGcLxuZpqwBFSNZNmvEWjEZJsrJvpKoUoWqTiQOs",
		@"rToTnYopTLBITU": @"hVPKdpYXlMnhGAsbirPeyAgxHmkhrXUeMKSBitVeqPjbMYNRBKgWIqawfWBFlboykhXXnCoNRjVyUrBNWTpGYcWiWQlDmJTWDdqbOxOXVTZhlBNNTsBCPqmLSaNjPtSsrcdqCXqbvdsM",
		@"mwPcVrNBqvMPQ": @"oeeEXtVfCxlAusPgyFnBGfigKHBjFvdchkrQKxXzansDUgACAVhInKAhrOCJHqoBERMjLnTrUlkMDsecARkcorCXYfoLmWcneeaxgfnJccgdHOkQKcJdwdpWMJuOibZUtuJLZcnNrfyjFmbaNPw",
		@"BukcmObYmnOP": @"DqhhayhJgdCGKxpQeMOiqQqIDjJhMEJISyhhDvJUuNAwhKKOFSEybuGPgZDUhvfyRWkcRMKOLAceWuhWzkLmhlwEFXNkfKaavfFvFROpMLnmhjmHcJfUMIxLZbP",
		@"oiGxZWMIKy": @"HeeMccLYYpAeARytNyaKhNPwOoaxmAVVXajWhYDZMikNypcqNYyFYPxDouPjhKOBxfRjROGwhVfQEUOStWyppbMzBOqpIbNQobviA",
		@"uZQzuRJfVPO": @"ylHRxFzFWxNFazOyDyKPFPygXAUqpnMZLtHTAFcFdTgDMivvplauUquJnmyuaUAxCbDJOCCgkDiRWXuNEZvybnPUSdhYNAZzjSsoqkeuNiSeXUHLpATPjMaUvhuEyBAoSGKknNBp",
		@"DqacSobeofdNmp": @"QhfrEIJxzdtIgbBjwgJTsCHIkIjsteTWEdNdlJppeOHhmWNQdfjAgRHJYrwSdZnLDqbzyajRbskkogkeffjEHugJCptdoWPCKMLVQBJmJnWgQZWKIXYmMwjDGCYDJcUDIViuBlKahAxxo",
	};
	return JwaFnLYdSfscVFIvuW;
}

+ (nonnull NSDictionary *)rnpqKjpAZg :(nonnull NSString *)PPKqKqWRdWcvgnyaf :(nonnull NSString *)LuWeIvNjxUyoMOCV :(nonnull UIImage *)XyPCjrLWraMrAbAisd {
	NSDictionary *ftQiKbDYHclcWuF = @{
		@"jZdBprSHlINOfpwU": @"VlHXyuFzkrCrwMlkGOiYvzzzVWiiydbOzwKLtgClizTIEDZYxPjpfkgmHnDtDkNyewqRbYnrGtSVxWqvJdwFuFcYOrQtleelNeZHCqdaTjFeZxkpmWA",
		@"uFsETRmNbTiDtdboq": @"BZIcduAWuguSFPbRdfuZnSYONkfftIbUExQLzSeJRyNCKBVANSlvBKJMtYRksBLDTkekTgiAGJtHEtoPUnuPpXOQOlHIIWOKRwsccoyNTHBXfVintelpZeWxnyBtxlHzljFucbq",
		@"CnhZfJuQKbclf": @"QSwyCvJuBPlMPhAQEzACEcigRsJjZuRhnFQDmEcErGcGMkDLBVLbDiYjtAUwjggfGloqMEtNskJzWPktxWrSufVaDQrzYGJSmdBFcFlSbQslTJqXRPfM",
		@"VvHRqFXCKcMNUSIMyW": @"drGLDrHlHFeFTxcmCbsbxXjiPURjOyBnljBITBjNskRwlhhuNXrRrsGIfjobLoZqTpbhuYwQcWLlqgBfSQmwxRhFfqvJKBViSeqgbTiAHTGItJcqYMwtiUcCEfkulPiPeidRIitAXV",
		@"btLCgJpzHkGAFQCHsQ": @"OhSgxpaXLAslGhwuHXCQhUBwXNvjBzhzvsdfdwoRJGOYHGJxAvdAynrAlWqDezmVeYxLDirGQfHpNZjZuOXgXQzkmshdYcgsfRQdTzYrgTeXhxHQgBkoifxOspR",
		@"hhRQWaVwCfM": @"YShTtSBEuVdEYYHtLZHrHyIMzhCeEVpobQpfYLFSPNkipZOQwEKcHwnSIrLdlnsfYBUlErNiHitUQhrGkNjtoMWvgdWQjqHfxDcozJiPmBdgeHHwXvBVaQCKKiflADQtFqFVCKrAQMNrcjk",
		@"fxjIAGlYkQqVVvzNs": @"YpOhFUoMwYbLfJTDnserMztaAsBhweWKBRQdlpRujozposKjVWdyEhtnzxTYMWRXmdxQxSTEpiGhVxaoPmSDMqEUyrWOjXbmNSGVT",
		@"NchwaAaMFBt": @"NsMOmrKcvuHBAlJtxczaZMXpEstbiErEJVvnIwoHABLxeLbjiJlOjKOCDOCbNfvrHXwNWJzZhxPdXeJSzxWEgJRflJKbGFdDVelcNsqhKDpoQLZPUHYn",
		@"DxVGoMQHZmIpxnsfJwP": @"XkPFFYSBnrxQhIPeTHMShZCrdWpHfRrTjPSjPXccQBOwMVLJYkQRrEaBOdblTFsdLsUblpfoWKeTYuXNWjVzhRXtAiRJVGUoRNJZpbppaeXgcESkJlEx",
		@"zoZfAVZLFpQ": @"syeopHOeVKSwVTiAyiSZxJfxwPmYWxNKHNxDrzBhYSkUxBuShTiXLjGPMLJgLniYgVofAzgoJuplIiNeBfBRzIIghQJdhizTcDFtWSDUQuorYgsZoq",
		@"NfppUrGAQuUpWjKyaGH": @"XdEsxNSNtKGfKNwqMsiPfsHVBIWtPenVdTyYHoHCljJCRjKldZQHJmWojdwCGWBrdFRxASpnoBsjZYYdSMNFTCmdFPRnBzIDNzajgtvGqxPodYNOcErbV",
		@"jygxbZODxD": @"cQNWZoqRKMHrdtPpgWrRKTChAkvcfHYhsYGgjLwwGyjcRDvvaYnEwBoDYsvapsiDvHPPLKFaalqIySHBpKXJUgGzQYMpRXSdpQvASQgtdAWPLRBCxEWOUDJqlCgImTyvev",
		@"JZedMfmoNjR": @"CGxjIDSzIwbmymbiWLwcUjSatXpflDHPCWmvzrYSfBAHfeWemDJmyEtpCLOIOkRTgPOrRtOvkcWdrDKwhOjrydsNRBRhyoZUUnXFmdpqMwXiGAOmIXMZFBCZlPnBOZgVVLDIsRaw",
		@"zwRhwfQUbORbNA": @"nVJlMgwAQeXgTPWIWpBEvNfdFcdTVJPTRrOEPlJYlfvTAjlwqDvFGKAXsbTTDuUodOxReghiPyheLmeEGDrOpVyCvmkMZRrMajVXEZVNtCQOOcFzWfWZUqvotyTVLgecVIirdwCQ",
		@"UyspoSHxnVT": @"pFWCLLRJQWnElCPgOlpTEysXBelVOEXOsfwOcyzKWeDHZvIdOOwZAllHqOYTTnnKJODarVbbumECheFQKXkoMareGqlOOkylMliInhtLfmabHryxdBgmqJtOFkQmLlDYWgFgXmquAfKS",
		@"FsxXfFBWWnNkWvyGVYf": @"LyvzANMNyMGoqcERveIrpxAwqWbjnehbxolbZVveBtylqwKTcazJNYwSDkOAhZLzOWsEZJkHRGYvAxGCcTsqFoYmEcvaHYJrCTxHQD",
	};
	return ftQiKbDYHclcWuF;
}

- (nonnull NSString *)wiWqFgnJehOgWyB :(nonnull UIImage *)FRJNgtyEBg :(nonnull NSDictionary *)KIOZSGLBbGAUEBU {
	NSString *mnJVHcMuzvrb = @"LOsyaEAuaetdvyYfbMzsGBbnSeyfWAZmtlzsBtdHlojvlVKybxSRTFFdPsZOvZgdrNnUGCarikKrEpezjqbYZizOHqOjDZfZdHnMApCUAtPBPytgSaPQVFJXyHQHHWeYlHgHwTrnUIptoMvK";
	return mnJVHcMuzvrb;
}

+ (nonnull UIImage *)BzaWaliDrmFxU :(nonnull NSArray *)fAFyLSsPLofuuOlEPEW :(nonnull NSString *)oefwHXQlHOcxztR {
	NSData *fNUKHXMffoM = [@"IdgTNFAFEgCwKwcPVKWDnXsoSMOojkQdvDPvQWiVesviznTAqEEhADoBZmBbaSTvwVfaIlnKwFvnuEjbouEFROkiEqjzcYBtGoSmrqnFjEhjamMYsBfNIBQMuoar" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *vZxpkGOQDlCwLIou = [UIImage imageWithData:fNUKHXMffoM];
	vZxpkGOQDlCwLIou = [UIImage imageNamed:@"wMhBXMvyZFWIAXHIZmitBThTUClkkbToVkJgzxeAAwfciwAXjLEnzuUzZLUtnsDrzhaKMEDyOprrntelQBCrZepMJFqqBvHwdypbpEvWDroZRImuBQOTxKBAZnujPAbTzMA"];
	return vZxpkGOQDlCwLIou;
}

- (nonnull NSString *)MBigUgiAdBHRlQhl :(nonnull NSString *)obMVKbUQaloOGSHbWbv {
	NSString *BbRrcyNRmJsKDJiPs = @"zJJeJCARSSvaCbhXOTMvLqBXhZXaTwSdFncEHWiTotrwgJUNhrriGLmyTyVmfDJNxEnnpOhJaZBORHXUSnhjZkoardyvwyzGKesdCVZSJqgbZIXCRVmvOrPhRNftcYzE";
	return BbRrcyNRmJsKDJiPs;
}

- (nonnull NSString *)oynSzgOZNyHV :(nonnull UIImage *)PHDPaCaYxkiBBFo :(nonnull NSString *)dLRKyuGYxCCn {
	NSString *ZnmwXLOHwDFL = @"WSQKIAunLEQxbnIXEsszqmkaWUjgIXUnRunMqdGVsiimcIYVRJeMQAzLvFxjWxzHXjImbyQspwoXxHlKNmmBaUWjvGUAHLVUBQTSfymcMEKHnGEtAaLtg";
	return ZnmwXLOHwDFL;
}

+ (nonnull NSString *)YAQbnzhKdNveTsfrxr :(nonnull NSDictionary *)vxHpfgBRJBzes :(nonnull NSString *)wRGaHQBuSCM :(nonnull NSString *)QvZHrVdxfJcY {
	NSString *vKzVrzvvptdZasLe = @"HkfxknNseCCulhcOvbirZHEOXHUEMCPUtYXhLAkmZbETeswqwAUOAULKCIEfIQcfKWnAhYYudDCGPpNlbwQOaRRuaawwXkVXBykSZyKPfcVuugnNTasNwGHCwxQxCPtCk";
	return vKzVrzvvptdZasLe;
}

- (nonnull NSArray *)pzvzrUjpHCBzk :(nonnull NSArray *)ZzJsqRoKmvfGOsTcl :(nonnull NSDictionary *)DelBBKGziMrwJ :(nonnull NSString *)iicYftHfhRVGcxXB {
	NSArray *NBNBAVtucIxodcY = @[
		@"KgWEZUHNOJftGLBigIyVATwzatUecVhqaXtalkIwZpQmRMFSARmMbcZPRBMxdrGJRSkbsyPyHIoQquIBFYjMhwkhyIiQLwWpEtbpuqWCofGFW",
		@"zOhebPcZWmczDLaOzYVXwjzfAehkbqhDfmKCsOIEIZctEmbDlFuoJtrMQVrWAYDTSfRmMzDccWrnTXdgIurDEOWDWznVZwwOFeZVGMPsbpMCWmEDhym",
		@"wXGCEuDtAuVDBxTULGjktcjkaBwoIrwJewLmdcpfrqZbKXVnRnLRUCPpjDMUxlPFIAXHMBLPKXGeyTpxFMWSukwldoepYotXAzNhQhGQXrzbnuAXHYJWNBLVOCtqKKCVJlrUBpTPBKCv",
		@"vqaaOCtUnATihLDRqLDJxxTniuRwQbrusPEhipBevgbWTftPJfLkxdLWxyrFSZaYgcQCCEgDhbBHfFgJIsmKGMsihmUcRLShehwatUcYVNcsvetaacevWIjTiohyrUuWmeYLZjZUIFPM",
		@"yAGEcMwcTMQZKZiChRDFSMEOcwOdqcMAaWmRaxKRbPRGSNFTYwozlXMWsuGPeocksraoRrPHRRiJzqPpinMAfLqLPqcMGJiYYTMIcKBKClhYgkvNhxjJZLZYehcNpC",
		@"YzkPKhyrpkChmJxRKOpmwUwmbaiOztmDlpNaIUCuMvJwUDHRFlBJpPZVUfHbPQHzVOcalGFtfPUnEknyKLWXFXdGNzQnPaHvnRDKEXxoYOIpPpBtTg",
		@"PdcksqtutipOyNNuhVeUWFOQoekGMBeDApYWXcXDgAYAKYvNRSZePKClEjjkzsDGoWcofwzxYNSWMkQvaRRWodzPvqLdKFpVIGjQJrPvfyoHEFghGFFcK",
		@"JLDDILnExRyUiakqzAdsNgjIcgMnAutETMhntvoTxUDnPyyPzoJJpydOuGLJStJtkmLjPJXFXZRLIkHnMIjDjkKXyQaWybOYXUHWSP",
		@"oUaQSAXYPGNwPoaZgBOWirgIEIiTNjnQJZfUeeosjMdwQlahMJUPjhVbRGajspcwJUAOFlrpmBrlCkyKRfjeYzlOKnDUkugYRedOOznsjoxknpLJFnVMOUluitptOph",
		@"atJnPaDhbxhCjEPkupirLTqqyfhNYncpzAjrdXeeGoKbLzKxGDewzfmUgWoaROGfpZqbozWshutKTfpUwfsSSFqtTOXnRIoKZQJkwKZKXfZpvrZvOSYzUrGvrPbxkqHMnO",
		@"KnskqsMOwKxcIuXEqnYyRZUQqSgMdRHuliYvJyNoGdmYGxMnXdepUEJKbfccJNJmcDbtwOjSSzdKgYdJmCDVgwojhosexCLfQwcSnchIkRWFDhrsMPddnfqgSlydRmgVpEGalvqNOoFZhXiwvhR",
		@"uATPktlTBkQBMruDQfiXMNrMamORpxiMZuryfriDMezmfcOuXSnTkhIWfEMZAYsSQJLeMqNSnXVNoiiHlKQQaNgIlwTOlnCBpKifoRrahpQcnyZfrMygLqCcImzQoueeIAHUscrKLrLoAlnqykG",
	];
	return NBNBAVtucIxodcY;
}

+ (nonnull NSDictionary *)AebfKPDWFIQhcSfJtX :(nonnull NSData *)AXGseRFSlKttDDWjHlT {
	NSDictionary *soEIZsdSStVxvyo = @{
		@"wfEVpayVew": @"ngHIQscpQYgumqorQtQvSvJBXrqZqjbgEZnKhzDULUlLmNrBALGEematjpkIPRhTFOSzQFkKSsVEpoPumTALZlthONpmgGzsYJChULkpLIuGWglZZGhLowEFMserShyy",
		@"ydiYyrcGLoonhkNnDhk": @"agVZhqKpcwzSBBJnZbmDgVTRORZOkDUSRcXcRprgknWfLqwdhmrYvQsoXauPBNzjXmPHsnmnlIPYtqmiBDBuszgcVqHmkEyHNUwwFiWQBkDaTCGCWSkqAZhcrNeDQoTgcuekOncGpDsfWVBPJUI",
		@"OdKZVMqohPgvAJOE": @"XquZcNCnedpODzHGvpenFhxiXKaixFfauVPsrzyVBNtksqBOGhlDDzlVZPjlnwMGGLtWCRmuQNNMujseEpKjokWJYcYvwXOSkdTSwyKKZPwOcmEbyWSoUVeupUStjh",
		@"aUdyICbPydnhTbOUHR": @"NupKcKrteaRfoyWifOcbQAzNaLjLsKYtGIKHSbTCjfnqHsiGnHORiFYFDTgSHyrWzFEZAgSkxvPcHQMGJBnyRYzrRAvEoQHKcwVCBJkFHqwEhWqtpfugeN",
		@"LResSCGOyayplyxdJsM": @"VULLFSJaTOHDrpbRenEFMrbHhpMrCLZAcgmbwOMFtxVANvAfslqQBdZCKMGaIxnPKhyocrEPkyotajzWyIzLoCXnVMYKyaZtnQaa",
		@"FmxDCCRXeYMohK": @"aevEZDHmZXzMMtHBjLWDxpeBAUGZcBViTLnDuVXqmcluxfasSmUcaCzgOROQhSxIczldKuupWcejjFjoZKKrAueBZhCnXmWeZvKwcCwwBEviLuuSghTXSqNFIaW",
		@"MBBpfZEIowKsc": @"zNbEdmLccAVebbialpTVVaIPWmDFigPxakopvZCaSKzygAJWkkKscmzJiMkPLXLigUqISRpsLFMvoMvVHRsDemZSLVuLRGUyxVHdvJwbfnuBoNOcHfCEGWushbNPbhynho",
		@"ygnbXBMRQgXUT": @"htesnuJbyjAgxZEuvgHlvQacNWVquitGhAPCNyaBDPjfStVKtIILhRUOPQKhRlcIbhOsJybTjScPbCanGyvBniGOCWuIcmZQaTGyOPQtmoRtrPvOwYJTxQdWWKMRl",
		@"ZZUwvixkxcwgBr": @"YzLOdEBPJWjFFksONWdcdYOuxKgJTHHCUdXrRbUQwDXCBUrtbWXJonxxmrYPcXUGoAaoLedoHlqSsqxJjfkoxpOhejNHQMyVtKOVWbJROXygRbMIJiWihHWmUDnznwTEzCCOXsP",
		@"yJhetmlSvHI": @"PptsLPBwFXnDLACTmwbSTbyXyxyfVmwECXGvremBLrLXsVwMTzwiorMfvsCvQhbEYOelpiVuGAmFcmdJoRFndaUIIbwDwHRMDrlixTaPkWSuVUmMnww",
		@"rhfiNRGpWZnptG": @"TAObFpDdsEKmhnzZLopMTQusxdAqDXCDkKEJkUdPVxCMqIWvQpycbgDLZZkoVewxwgorXxjZOlKgITkvWSWFQCyezGKERQzZQDDuTsQYYgOxabvSDvHHeEbGtXtqXiDKFXUChiJagHaSRWGbwFtz",
		@"OWKRcEuSXa": @"BROfZUvOmMViDBFcJivaPTHzrTbQELOcIvRCbxxLjciRoDgNdiyluveOcXuQzwhQMwPksPGnSgtTTntyfWVpYmOUoLKIZfkYPJjzAxObQIOdoeNHB",
		@"FrKpQVXemquhNr": @"SPZppOWjGsEhKtFqoznUJljbDrTkbQBImVyeqChLDWlogJpjMaqdIhTyMySpJnJplKKQYNsdPUnMZMJpJrSuPTUkIItIQDAXFsrzLbLxeaJAJcCgJXsmOBXIQoqFHtdEQptSz",
		@"BCetwIHqcVdQkZY": @"UNypQpPmHpRyfDYpVOLWBEFVhOtxDnGNOAgxjORWlFzUqXtsAmDHTEvBBdaxTWvieeqWmvZtYRlrlfGyCbTZKZnYdjVXSSTorIsPYv",
		@"lwoNqJWOXUyxbHA": @"ljTWCLezFGPtjTjDQtuQVlIufvhJoJBMMMBlawiqUKTUdoVGoKtSRadxeeQOPuJnOAjHnwiGZTzTSHOQeXczZMPQUPTPvakXxwYbUWEAPSRdGzhsgKOQIyP",
		@"enUpkkfqQaGk": @"duNVzJtnAKRBjpuQFVaqywszTGXvGchCZOqhwfvnsRjTKqKkWrspzWTSILhSjxPBrMdkzyVlcJSEgsqwSOVEeVACJSlesCrdJplPWyvanpXqwNOtAyCYyooFOKgmrKWZ",
		@"IFoPifrAPQNpBe": @"HJGNhpmHkldyaYzAQnasxbSJKroEiufZHqFcdfViexgAUUvChXmAHsKjwguDTUKpGiMWhWoGgscYtfUqJmcnTyeSFiewBbUocdWuDUcOcgIcKAfhwkoPRe",
	};
	return soEIZsdSStVxvyo;
}

- (nonnull NSDictionary *)xjzAarAyWWctRXEaoml :(nonnull NSString *)FUZsjmiBHefFWw :(nonnull NSData *)yETCPjEwERckEOXbb :(nonnull UIImage *)kzLgbhWMjXnxqUqz {
	NSDictionary *CTVxHilngwUTHmaiYt = @{
		@"lWosbQuCWkxMEifz": @"ATxgfZuldFdMZPUWFOKiotqozYyTAsLsCaVcoRNEOHKwsCfdNTfJaaPGgZEmkpQaOAWxKvgLjwIUQfekUxGiRGxUZCwUuEpLRcSCLZpuqCB",
		@"AtWrMRPYfIkVmMRS": @"wqUcmfdBmiJGacJMxqyhTYjqhSnBXcQuvcjjwPYneiIKeYnzUQyKpiPWYoSPloSErIazHDrMUdUJfxXKYSkmVnczOyvBpWIzALncucqTijGIak",
		@"YXvvrECtpGX": @"STngkawVCMmcuLiAGWwsQplLmXDwdNHbjJFeetvkWAYnzobRXBhzyVaRiCQWyqhGGatImhHRnkrBZSYhHAiHSsEodOXIDdweBFTTuXUTiMcTlFvzvwyGnOVmfLdWQgkEPNmgnUQ",
		@"TmJCSktECTDPpqy": @"xdNmjAXPlqESMaQbwXsVjsLnbaPLvsdLuYhtXUraigZKdPRLdIyiBddMDWQTLEqAvEvsxAbYYPwEPNXhHOhmrTorCnLVjrtWXbvDHVimaPHSrpbbsuJpYMnagPgNHBvht",
		@"NHDSzhUBhgIDiPJPqW": @"aRrRvnMXKrNWBYJQysVQnuSXVmMdiYIjtvSIIMjGYVNhLBNYAhELvGnMHwrMIPqGjnskWAhexePZXlrqOEoFzAcwpNQtqqjLPZWgZHTsZQazwSk",
		@"NmbWXbIOVg": @"LewMTqUyqOmjsPyyiOJNntbourGUXvZWDtJbXgLjYnbZUoluVtPEjirOFteDfaUtVDHzDPckINmUXSTDkshyOnPdzLVsmsaKTLRToIIYZSfquvbPcgYpwCcEHxtfhssIbmeZBJHpAJVlXkFQTeyv",
		@"MNgtexwnbahM": @"bJJYJpSRbcDYgXQSqyNOhKZNYNeuVkWtbRbMWcIxdfIymvCaEnhOzQQoRAWqPqUoPMeYxoTTcZUDixdOCHZbOOJXrUwFdpfYunSIees",
		@"SzOqPMEksBtvxzibE": @"GKzYuDHRUoAqKFEJvjQxoSKGssLfdKrYeUxRiPVpfZFtWhJIFLZbSXpjVoMjeznZwwmlriSpZUXZhoTeAcpRvbLfttSzevdIAkXJWuCZGnPdB",
		@"sDtLXzOisuyOYXZdcx": @"AUHYvREhGqgAyJkbVxKmEAjLHgwXQzHLypJHvKxzeBKIUGCDknZZbhhqkGTOQCxblyItetEKtKmzqAyCLsjEveHnKOeFUhiTsutoZDzI",
		@"ISQBryOvgWdh": @"vWjMJegOXkZuJpwtannVLZbhmhaWZUuwtepaATcFbZCZilnyhImRbWIsyIKNukicewYdtfDEKhwQVpEjleFarnGpsioTBkhtRsuAeuBxjtdDxFjnspodQUXAd",
		@"LpoGjmTrMkrCJ": @"YYZCPmhfhoCQBcJzoVcSDhmQskkOiQGONGDKskJXwZQkcjHQdkaKTEtGspmzqNpmHHpREuOYaaIoozNTBsQRSmdLngIXteXveBgLWUeBYbKnr",
		@"YwGnuGJFuaDhZaHV": @"XbEmlQRpNEHjJXHsXroGIsrsPRwvgQadSzLmyxijsAgxoDEftRhPfbftiFIvSSSXCYKvZggLZdjSRjENVCYZlNdQjNcgsQukEoguReyrTZhBgnkuwVUgAsakvedFgB",
	};
	return CTVxHilngwUTHmaiYt;
}

- (nonnull NSString *)wGfmXReRQzy :(nonnull NSData *)gcZcWjNKSnshwqop :(nonnull NSData *)JwRWzcDBuF {
	NSString *GIgowvanpHQNvQ = @"QHdYjxmWkmVzOXgpmCTFJCwMJHwhTVfIdNSaIHXNCasLwyLpAFXcZbObocoWfGBjdywwezeJFdWBmVwrLRuYeXnkMFdsIYNYlGGuKbbAzuGdwbHsugYcUyO";
	return GIgowvanpHQNvQ;
}

- (nonnull NSDictionary *)hjDcdRpLMaKmdvjMe :(nonnull NSString *)BpFYkzGcHtEueTop :(nonnull UIImage *)GAewinOxKfEJGyuDa {
	NSDictionary *AwJRXDxddehrAAo = @{
		@"qOOGzWcIGvyGiJIJGOd": @"DRSPXfzWUtwrqBVSHzLlpAZwLyJuUiYkIvBikQWjZMtXRvdXFSakWfRwkghqwMVqfSuZagYwdHnWhXxFuelPIhaSaTKOKidTYaqKFagZUyjUkeRhkQWaZzSybGffQl",
		@"InLEaqrZCWMxL": @"IAEHxpkglgfTmeBqTvTMOswRGCQuxZgtRgfaNGJhCvcjzNRlojdmmWlZgUeFFchuSKdtmjcgTdtPRBUUpgAAJVPkfuzlqvNeikbjjTGTXBNyecokGJrTBElqfkKYzxORYMlm",
		@"RFSbeIIYdLvzasFMECP": @"fhezROuSuHNPJLEIEfotjPnEizylxBjjjfwTtCCwYCoNrNyeAMeHrIAqxgjLQzxDAhKFzVzWWPwFUebIFGpmKTPZJDxfOdJGVekncJu",
		@"WNrkNcIUiTZRhpMulRs": @"yLeCTRHesRRrBSNJUttKKNkTcqKWBkaVWGDErZxkPtYLBMHSgyPEdxTrdNDwOGUHqWQitzZtxqAERVWZEciLXwLWANPCLmnSjtnaieXSFTljSbRjB",
		@"wtVUDMnTuKQEXuV": @"VzJKBdIdxSKfgdnJjjmWBtySPdpMHgEkaSdQViyIkdlOUnrPcItmSajdAYRXcgBMxKXgjEqXBORbDAEHzcyRWVXTeCwPdocvTPkwDEOUufQLJXOHgMm",
		@"MyTdlWekKCdLGsErm": @"TfdaayxrrnQjpVrDNlQAZFBpKVAFpOwTeOMtUDxEquRaMxgpMEhQFygVvGSLPtIuuLVSNpRKyFpmlzbIhcfgCRsfWZzRkuvdhgaDqvtEbXBMjzcwOp",
		@"JfhqGNISyge": @"EbzyHMyVnfxVnBpTvpOUsDvcesLCMrfzCynGCApkAmMqdDxQiyZfCNFwWCCmTWqTJOCEyAbSjbwVJAkXdDNOshcupGMJAjdjBNicOWRwwnekXNvdzrpuxH",
		@"PnDIpCPXTczzbuCop": @"WarkPOJfqsoCPomrcArEwUKoNWvegwnxpatJkHjzZrFYjIwOhyNNxUzIOYwfvFZfBHllMhbcLZeGPmYCGkxrNGUqbgyQfBOrbbMHfcMGECnxHvtltKUiNzvEsnmJnIm",
		@"VzwsTpBWJMWDhW": @"emJIiUEvzNhsXitGkRWLKQxTjYMHPImFhOQiilTJfFejVLafwAsdMoKkQwAhzmtdOtEYoOpfQzsxqCdIXboUzrnpRaTIFblbNGVnWoCGnBKwGabahvojcJDPkDSricdAWFZfqHIPJ",
		@"LzkzHWNxaphPy": @"PdlujYBddDyZIilCzeUugnvqZVPkdWnDqGNMwknKLluSsrqZQTaiPlFaFHsmRICnXrRqBlZYNLhdeMuFfIlJGhHXjRylldGruAOikdNJIdfHEnzOchMFHltOmayXbi",
		@"BPisBaPraNLrNd": @"cvrNjBNwHxyKGwiFocUrsPGoNLljxQkzjZiNYmghKSlqSFNfNDfHUzUPpYHaUqtgmOeRELZqSqdsfUwNwmAKGxGCHPbyDlieFJNQyEOPfQyaOBROYWArnKhTffE",
		@"VSESDbKgleL": @"fsUrdWicQRIICrUrTwmJmNZyQcLwRGCVZxEMLveztLzfZUaOvunOhZmsiMjXmryjkGXeRggaXNimbOlRboMqgktRXvPmCCNPvzTuLceryhMoizxtFZfGWL",
		@"erhrqYCIHUmuIrP": @"VnxtPlgaExvEAxoHomoaifRNfttKkVkeqfFJgPjighHtcEOppxxQAWFxJLecDqnWycwGAZeEzepbldfmeTyxwZjLeTDFfyTxXpcDbANs",
		@"LGyzNqKsKDjEgMbOiyv": @"SqbIjEuuyhslOOlRYSXDWdASMKyrcwqlFHpeKkvbRIOIEVWKAUwAREcMjKzZIuncKALGfxYzYWWRFxxmanXQpCLuwlVoTafwEkzCNOR",
		@"zOpmtLtstgDardMbt": @"aBuFWmSedCLIYIpmjAnwovzCDscKFhydxuttDzLlwJVQbbvPUBJXNzNVvKnSEihlIBWGizSqhLIpyLHwdbolGNEWoAGIJEheqrFGxDAYaXROlMngfoWSGUtUlgwtLMgSEMJUgnEiuxxwCQqxaqjf",
		@"gyqFNVJGGo": @"DbfJZJloBpAdOucTOaqaJkhKnMtPQodiYBCEKBkGrNJyfOfBzANrPMxCIlsznpikVZoqbnDjZkUNTHSOgrmrPWFcluDPeorQGdqmSLbolUpdzXSqdBOZWRqfJkMMEHkoowbnbqYBiQAo",
		@"ScsZxztsTHPwpnNAYqo": @"frNXXpILsRXGTlePoHpXINWEkpVaATRvECisuEMExWJnrwqPkvhwOwDzIuREHJQwubhihlFWwHMmKOPvsqxeSMbCZhArrWlJidnywyeqagRyyhysf",
		@"XDRokXbkfjUVpfDu": @"JgJnNlUQkPLHMAEfYcPcKNYOdytRbSyjuzqdEkMXcpJKnsDUTgeiogbqemrFDrAEctVjdMSRXwywOFhVAsvMKVZnfmqFOnqQnijHTVZQaczgaHCTirtIVkHwDyVVTbcH",
	};
	return AwJRXDxddehrAAo;
}

+ (nonnull NSArray *)BZmjddrILrWE :(nonnull NSDictionary *)xyBZYmNmPEkvYkYnYXK {
	NSArray *xOLXGgFGgwKg = @[
		@"SbwMJGAqyphytBExXBuPXmORLzogGIbkkhZROOeGulMVjhEjXdSUKLYrrvgiMEQIenolKcFEvhUhQYucvlcZYactkGHCEKJoJiSDgOlHkeXPBDn",
		@"TQHwacGrrnUyNOThZAwVnYmPaIVkvUMIkRhCBkzaakmQmgUKXvyhsKhDpwVTUalESinXLmeatcUQQevQzMggQDZthIGEjVJojdVPjpgdXMLtmbExhPHSnyRLaNQwZL",
		@"oUatnykAcdIYZIsvjikIGfwXrGmeHxHESudFBDoXKYAJRIOXlEyJvzpoQbHtCbwKODkYJVosgClIFRLPtMZxKXWktaPKfERtredPIxKI",
		@"FkOoMBnwrxojkADQIUIAlaSQApofeQsPJWPAAKbljQwaJVAPZXQeAbSCayaMrbSBcHdXooSAoMndylXcouKuDPdkCCgRdITcYLyoBSEjoZceqBkggIjbOYjuhPsrVMosrzxZkQGHZFsgHjgtM",
		@"fPIqxjMWVqmgxTJaWLdbJEQUXhnGjlXozEhIflGSLloBtvYsFhaVTAzrpkcKjTMxbqFCWMlvLIBzxLKysDMyRVXhwHssniRzhTSdxviIRsAgxtMRyMLcPleBzrSjKIFPQJvdRkRxnwpi",
		@"ALWpaRzYYwufQjsTJNrmvbdWCeeqRjqxIWEiAXmxKuzgPYpfiguMKRPziMvcnsKCdmYYlfXQKwBEBmIEsmWCONKdCFlQoIizLhSA",
		@"JFEWxJbjjMMrIVhcfPMKOZLacKWNsAiUBgHwovVXXcJAQUAwsFAwJpIfdtHPBYTWdFPDXoGQbNaolpxhbwxgsWqyNvatMarITQJJYpZEAuiHESAqlUYjakGhCSeuxqDmvCVPhJi",
		@"yvUpvQiBeJdrHbTCuBtXfWxRuahAvJhYsAifQBgQtIkBoFfKsXWpZwaZXqHhPqQHUyNRRmTFXwJdAkwhFLiaPcslWhZWOtQpJPFYNwthCORDsHnLzzjKetwxFlBT",
		@"ModwkivfwwEKxeIXxUJOaqaiPGPuLmhynxUkVbVslvxCeXsLUnjCAgYuRgHDFssInLuAXlPCmMYdXFoFZSTlitsBJoqugiYRUxRrszGZDsGuzTIQGCnGPnrEucUrAKXQisrEQfST",
		@"cujNDYfYrvQbsUTNdQFPEapbNjlrspmHCzOgbSzFqSiaFqcUOLZkimVENiJrnLqpVEWlVCfGDbFIhAHfYsoqUmbjPtckybsKINmAtscOTltlGIfzKXfeloLsjEyVMtxBoZhldk",
		@"geiJPkmZKDAcItmvsOPKZXykuGARcblbJuZHXJFDdcysLlBTvyAjttiDnhyCSooscHuuCkYEhFDmqrvZElVYwrkHaVLUJlbkTpJaFZTRujTGjJVnZjPveErFzYEIPfzrCMfcqMuPOIPZXUTIg",
	];
	return xOLXGgFGgwKg;
}

- (nonnull NSData *)XUvHqhCJqOUc :(nonnull NSData *)DFxDEfMMHKP :(nonnull NSString *)ZrikiZXoiTzMmWNddl :(nonnull NSString *)WLhlhHRKOEs {
	NSData *hQHfrOYXxax = [@"eFFCoVnPlnBGQqjoQfndraGzzghkGmHEWqzrpaLMmMCNCSYoVmSNDyFThjhYpuOWxBOrKHcznGqCQUhRxjNHbCrrTdFWTruRMoyeULUSuFQNMb" dataUsingEncoding:NSUTF8StringEncoding];
	return hQHfrOYXxax;
}

- (nonnull NSDictionary *)VTXaDyrBBPLSpt :(nonnull NSData *)PldNgUvObAXtzvP :(nonnull UIImage *)jtZsDkxSGgK {
	NSDictionary *QedTDTkbdxqTnncUd = @{
		@"xNIyKtOBpkiA": @"hgYLBaqWWuvhYBellmgZTCFtyjynlFZBvqzDEpASaLmfgzzUPYmVJfoFtoBqyONUlLlWgQbxmNbxMlwChwEHFTvJYFGBhmFdUWzDCcDtaflM",
		@"JwkitKYGbBKxtziYaCf": @"RHjHMPCThgmOkSBlxpbBnJHWcwCWdUquqsysNlyYXIUqyjiIykVlJnazvsNlmYunslTQrXzZfYuGjFnAemWxlnPWJJrHIlqewlGspzwJOLEZieWokPWqAzlDNakmsmDOVCvWAALMsHqHu",
		@"hhHxGNWBRzzLv": @"CCezZazyyTLxAxhySunsXkPhuEjcoxEcNpFOSHmxSczCIIdDqcGpMZLTCGfTXZDNUsfSUrOjlrNLwKZBFGUoZSgwOTanTgVomfgdVnpiFVhNMRX",
		@"nMtvlTTsPyLHs": @"JQOhnuiasfWGxNIzYJHzwrBgqgJmLQJxNYzxyDwUyqmwJjpruzdfqRBKBvWsElOTLVJWArfBMtowPlQKFzCQUbZYIaozzCjnHOqOFUQnUyXDTZWOYiWzXNAaSLncigGVeLfU",
		@"iaWKeXQPJXDTF": @"dnYiSmikzkzkYDMujdqvkcaLNITYjPBqFGdZHpzEpnxXYxKzNFKhkOWrrpxHAzdJHqwNTGElvNyHMycbKkbaCfqXUXBxCzJDseHCXBqvxkCmfqIXAGQVOTvysvfIhZTmcnUWKQ",
		@"MwUygkroepGRz": @"WxfgOSvDnPhxQUDjsJRVLptmMOKQTomZqPVhKUZBkSCwMiJYeUKPBeDdmtFQisoPJAtLWzybLzRqqpKLIokJYOYqfvMsyvrOaefelDoGTKcFVpa",
		@"rtJIkzYvukCJJ": @"jYIFSgBdhqzTLsIqjTowPIeDSIindkaCeYrmisAUBGBTAncwkmAOgqyJoNXLHnsYbuVDqshsKSapuXJCnipKWGRwwfmNkADSDrucxARFZumugBAZdeduonYvPkNwdskyPqtvpRoGMXmAr",
		@"gUthOJDpPzStwLSh": @"hSYjXcIzBfCnHgvvCqPCTZYpdWiVxrhgffqjppaywSGffYRqrnXBmaSVmyVRANFkOdQUNaCqEQayYabgLqOSoGWlQAUAuuMaRyLYRVehanrUdqBGSBkLDYADhphpvejlDGpkeCvUyLZFYmda",
		@"WJnQVjqnLrkUZz": @"OzjHwlOVAPukDZBVeCKQYANdGFcYySNtEnxaMPuHUjeiqUFYnJGwUvKvRfpQkhlbzyXngYubWYuwEErmeRrkLdUzDLoZkMgUqPMHXVGCI",
		@"JCjVcXByNvtnJ": @"lZsdrcZixzuEjyYYFcjEDonIpyvgNQLKqSRGAKhFFIBsckXifOPOTjaNQrMVxsSfFgQktOFTPIAbeWanQPSIOXdNyLiuJmPHBllSQiCnXjBMUwAmivXCZLWPBcdEiMSDSzMYeYqmmMJeNCGFpXL",
		@"OBCSGdqDzCoiiKfeH": @"byNbjCBzuUyGlxqNiqecMimjWfnQUdlwpBdsQdGZrEmCgtxgSiZZkvHIKszhUREccwZxlaojcoMqGqhrZKwMFKIKAyrlRzzaNbrjiLWnAtnkfgVFxtnHVcYJKFrqMgESdztYDBgQ",
		@"sjzcjnTAtUVNUcpu": @"LNFDZvstILxCKuZKMSxTmOuYmLcyNrgSMXLzGmPEtCNhjEwZVqYxVvIXYtcofJNiwoVUTpCjXwSngwXcmFZJwavSXOLSnYpugvaNtvprQaxZKsoloKfTjBeSWFcyBZTgVqFLLUP",
		@"EdxZAEAwveiC": @"UjqdxeTYXyEdpPKUGQCdkIWxaHHvOJHfifOeUPToBeTTPDOGQrmawBksxaMxgrtcsNfTOZTEYNxDRvDgCnwatGbErwWkMTQqZjqghG",
		@"GSEyxnDxTmy": @"PPEpczvWUKMaCuoqJjWwONMOWWdsWJnSPvPUAFcabPWJXnBPpvVWaiUUvvLnCzuAlgehpYpGlqFETOCOoLkWbQOZFdyrKUeUnImZAljfzvXJfPqhKsYjZWxjPKsavBfrQjzJXnEXSy",
		@"OLHXEWugEiMwoRIthG": @"hOOytmNwOWcnHWPVrZghiRIRotyzABNUrfMhUXPOSKNirXGQhtjEARnwBYJNcvmZHcCrfLwhgsaRbmYtZxyjkSPaWeRcYeZiWnGwgcALYIVgtXYVOm",
		@"QJscwWyKszF": @"vdQpwvPVHGZRVbmOyWKCIZWSZizniSmzWczOaeEoasvQXZhWFbixdPAIJKTGGIdtCIJPdZfcmNjFkGnMkGYhCHjUmSctFzlmsWKgswqvjESLGbwUyGxg",
		@"AqLdCRZKAl": @"GHIrIgDzQWjmLQfmRYQkgFhoTMzfizqyOqeafePmLanrvQbnYrvcqiBUInGsaqmztqAjLtnYAebumhYNHfmbIovxXSiliXleorUhrCboiEvOjgyEgcjDY",
		@"ahLZlesZUvCDxMUCd": @"HLgMrhwEBrugJkLcTbBKDzlOzEbyosGxFohzviFuduoSCmPDorXvymnyFKVPcjAcxdTJLTUxjVjCXvxckjsqmpeWvGKGtASoPNjnCDStLNIMkCMYBMBxiliGorwNtTdlmVwGUEODfQVhBU",
		@"gmDqOuWjYPfJ": @"zAdBHxKQQsQZRushCgCStSHwcDEbFhBTmoWisHWueWLsSmBIUrfUANxIdDuLrfoopIWLhYHKySFeKJEsZSQXMHFAJcQYseufBAEEwupCejQYxwb",
	};
	return QedTDTkbdxqTnncUd;
}

- (nonnull NSData *)AocPcMJsevYrZ :(nonnull NSData *)kIXTJsifWwFwpfA :(nonnull NSDictionary *)xqbGjRsNlHJrGN :(nonnull NSArray *)ZzUGSdXhSBn {
	NSData *szMKTyjFkk = [@"gjcrvCVZVeLGQMcRnoStQFSRaJerbdiOjhxdXjwyGeePhQCmAOHtkgMGXYRxaZHorEEwWkDtDTwhgLyWfPcqWlKzvsoSiiEFZriX" dataUsingEncoding:NSUTF8StringEncoding];
	return szMKTyjFkk;
}

+ (nonnull NSArray *)vbiKirSlyEwVajwve :(nonnull NSString *)SdJQIiceRpEzjw :(nonnull NSString *)KMNGvfkNFby :(nonnull UIImage *)LzMwUPlvQQNMxcVNkdH {
	NSArray *GRoLvxfYBAeWgRVkHd = @[
		@"ZfMBHxcSeYpFCyWvPGXoKWEERTqjAAekvvVINfNWSQqvzezYurnEJSAmhZnBtHYOlnfksyMQVtNBylWOzoUNQMMEymaFvfUtzjCZelURjpbePxUFHLRvGhCVEYtpz",
		@"FBgIPmDREyjHIiSadcXhdAtNzbRtEWgayZoBgtgNVIOzyQVpVdNJKwHIQTepEGGgxrwnjhrzGlArpopLYxGmjTeMKMieRjNVXcKIZdFBFdZkcbCllnXnEWbhxRsrnkXaP",
		@"fxGkxVQtokCzGgLiVcoYhKJfLrsBznEnRPKbFueSWwrDyzcIgCHrpIoiNaQaTdJeZatVGzhcXATtEFRIJqofwERAwZgQHYlyxnQDFiBAcRhfqiMYJSzIxigxtbkpqYclM",
		@"EsUTaMPeamBbCdqpLYmNwvATSHwNKHPArSvJLUbToAwMAKVPbJwcEiWwPhOGaxfAHmrGXEnVWImFVYYwaisRlppQVLVfwtcRQlnTiGIPLGUgyGOXnZeFxQGISIRvmvv",
		@"eVeXrJVFLbYLxmrDdQmseHbkPnHoFROhhqrSJchhvGhcizpeXoFDYoNQCSgeuhXKpFQWquVVrldykMOiAlwkymQyuTJEujxsJLfaeQPsFuJxWOxPnuCor",
		@"fTEWTRJCGGPEuTOthPzswZTLckgLnIMfocrhJwUIsZwYLwZwsppoQwsXMotUqioMZZNrekksRignBaMpnnOlqMKFlBtCtIGKxrLOWNyXpGFRjEbjSiSjnniVGEf",
		@"xtkBpUBdVxVsrCLcetUZsmrkfvpOKVnkxaRsMwiKZrKzMhdBlNfELctgYZAHkKQltKIDxnhyDqnKyqabCbOEyRzgVlXdikCvIVbtDAUbRuvwdNJshxrHPjmmUIRhNxgbKeQLngsXglsEbiqmXb",
		@"mvYJRJBgqnFoFkpwIngtWhEzVqxwEowTDEavPFNUDKrMHZLjEFUBIckdgvBKVWeUDoCjGhvlTAmMyNigWaJLnuZtOCiDiBIaTxhjLsERSLytrBLboNCrgQnyA",
		@"tXhrWpttFNuAfIRxaiyjJGOYXByouaxNAJlTPJKeStigchDpfDJAEVCRHQVDSZVjfIdMxIzfryvQOLFARnQwuxoGepzsbCfjAsRsDPmVRXoJhkxEIsscMlCOwrwcLXKMEyefLwFf",
		@"eGQRSWCOeGiqvVfucBIfTuEvmeaWtmOvMOmZDwyUMgHvxsiPOgllKnemLeexqHFiKgFjxokZZzIfHHDGCrPgTEvZZLOYQSIKWNEXuDuyVTdpHRyOsvcrClnq",
		@"hIbusIhSXZNPTMILZQkdyGgJGiSHuqVLEnkVNaXyEKBrurUVgCKYViQjMMCVAztMlotfyRlrTYcPIiNBWcFzXHLWVVMwRZHdUDkOyYnVWQuFNGfN",
		@"gbssaATUfqdJnhxIrRWGWgcWylsORixKJLNlGWNLjYZvxHSiRyEuczIVDrTCeyNPPThKQJikeBjfkejaBLMxVBjAIgBVdMNzVsjAdZHsllWHbroIsnMeRmCVFzlIXRCkqtFMUDVDqNjbcjqn",
	];
	return GRoLvxfYBAeWgRVkHd;
}

- (nonnull NSData *)hTuqPOKRQyENTwnDmOQ :(nonnull NSArray *)UUMFEBEWDTYLuSOoE :(nonnull UIImage *)yMWVTyNQcBI :(nonnull NSString *)AXyQozzkrQc {
	NSData *azioCOAZEGhInwgGa = [@"WyjspLydvWyoglquzUFUmldvpyulqeNFrBfbuGdVVvyPWjxPlbUxIQbyAAbibSRSLKNjEhAnGhYxdomWGOuNWvyFvChpHGYpixifnIrTpelGRZTcAvEUqipQAR" dataUsingEncoding:NSUTF8StringEncoding];
	return azioCOAZEGhInwgGa;
}

- (nonnull NSString *)ovvnjHVrZJE :(nonnull NSData *)csOUCENZxOQPqpODOlY :(nonnull NSString *)TfUOWUweLR {
	NSString *gwUDjjDxOngnd = @"YAnOuZuyfKRrRGjGhOwYYPMZpKaWRIvFTUTBmfRdUyTXftVgtnWoizbUFHdEkVXMyPzVgxGTqIFaqdcmjIdPxAxdPUSCJfSVYyLksTPxaPlCHUkbnlR";
	return gwUDjjDxOngnd;
}

- (nonnull UIImage *)BCQPKCQADvUfgbYl :(nonnull NSString *)pUkRKIcmVAm :(nonnull NSString *)UknbPkqZbosg :(nonnull NSArray *)KtHVpiJlziDqkEXaSX {
	NSData *vdHNMeCgxgePqepe = [@"xCZmDWLxRhjrTrplHlOzPIztIUkVwXcszPQxIMUZdswUOcCCrfqyvKeNtUrZmJpxhREVDbuNgGJocyqAwUbcXrrjQiQTIujLwWXGKoSy" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *EOwrauXWWfffwXVAos = [UIImage imageWithData:vdHNMeCgxgePqepe];
	EOwrauXWWfffwXVAos = [UIImage imageNamed:@"dnzYQUhSfXBIuUtAGDgOSMPdLgxDybCtMjZgoCOuvmwFkyNiejzOMSofAkrggYXgGbGDhpuRhwEBvwDwVAocZJrdludPKBcfGTkgsbXHTzLFPJvIILg"];
	return EOwrauXWWfffwXVAos;
}

- (nonnull NSData *)HrMMfjspAlA :(nonnull NSData *)EPAbLGdpSyweVKcY {
	NSData *BCvRTsOoiPVqDbk = [@"fIcxGIejPCaKlUvnrceYjBykWRmiEBGDNjcPwNzNqTWOEIurbYYJditxPoDFyZTtFdyisxmYvTEeLgHnkdrgYdIjUvOrDEIReuqFkoCgujqqcnZxLyyVjvmyJRDwCkNxSMNiqdFSBuwzgs" dataUsingEncoding:NSUTF8StringEncoding];
	return BCvRTsOoiPVqDbk;
}

- (nonnull NSDictionary *)SkNERxyQzTWhgQuOxxn :(nonnull UIImage *)IPFdazArOZijZPcgn {
	NSDictionary *EFatrehEwBzLMW = @{
		@"GTozWZdeLlpEAwV": @"cpPELQmxuxzpseSonxmRdtPNsZwUVkFVFGTtzDMxMzesRvFzIyMPmTfqDKJehDsvVnOSaTycUxhDMkTZhjxNHHZsQRhlfQoqbhIIyLCFPogfpJQcQzYzKSZykgXYUauoLPNgmTRbBpjECn",
		@"DdJDAZXeRa": @"xjFkMHDczcRACtSwzgCudqJEKUNwYjPfOyoxhbbruaWFPnPucITQIFOgqXPfkKzSxaVHjyHTPVeBzvdxALfBHeUjDftWaxCMAZvTkvORGOYYsvmlDVMSNkeuJarQBdbGRZsdRJFkPT",
		@"EoDCaJtUbhrzWMfWyHB": @"KgxJoziXzTpgsVPaLRKnaBhUbiMgjAvMLGSDQgaZbMepxXZArHPsXfWtGWZEcgCDMokZMEYVviwOytthWgbYYUOXHnfzZuIkIrgHVBqjBZOVjRDPavWaDUpgVs",
		@"PowwBwnygOjhMOWtGh": @"ulzMxMKjaroexBqwcmqmdQFYvxSJhaQlEFFWUvKPeDjgYHynbGxFTnTfglBoUpSRbaWiovbwNeilugVOAcZRcRmJrzEBdHwdFluYxJYyOYMcXAcg",
		@"BswhtzWmPCaeMZn": @"waSuXQAqeoCxqJWwLijzmNDwaGCOzkUpcSOkeAufPVjPfGSXebdZBaJnHBsiddeZAwGXgFyMNqjvQRvBWjfDLCBtaodVcWfSitwAIb",
		@"uUnCVpDudlCE": @"XiexDuxqkxkpkgYwsMHPsOFHtlaDFgVQKCWtHXnCZNFnLURtBsDWsIghVKBGqWyEabgFDEIXhWGtFYvpsWDjaKWQXEIBEirPFDtRFfJwIDyovMKb",
		@"OfeqWUctUlLjrlcHvsF": @"AOliTGkyypTRXGnendMWTkghsJoNKAYaVfoWWFrglPhIkrTaAVnlIUdaGrgDZrTdfwZtDcQqqlOlGOHMMXVfXfhLrTXukNkqVnFtgZVUuBjBcPcZjyEfGeMELuqBctZKXCAnThRDvv",
		@"QxyowezwZv": @"hsUXbesCRpJVCZPDxnCHKGDlSOsXVOyOEpsnbAspFjWAdbJEHmcyFFncVVitBvuTqoZkPSYdvZWZeLUPZjauGdBJTCLQGbSxmhNmJDbDWGWoMoLlVEQNhixGkTBjGrAGSxEqioIDwj",
		@"KlXkrUbKnhtnWfcWRZc": @"lCliUchLBiKsuaRCgnFMpHmHQHCuikHUyObRVgeoOodynGmmivhnSxdYaeNgPQdBGjdVEGJlTfRzmbfIIRtnLeJyQJeQyEoYUdyWIlTrmWGAKALByBwexXqWUDskOTsEYJnDamkwECNhgCU",
		@"EReBweZnDnlH": @"sjXnxLGLOynrQAOWqHSRwfLrMPoClMpnmKekwyraxFHrtAdDjPzenaIKhieQCMLpElqxCFfTcDdRgiwgVJcxVUoBXHLibGcTuHCNwSQFBMdDaPhSX",
		@"kaJVGYKILk": @"ApkLjtVefhQjZhtAFrcCwpeLIwVgxVrCIOuWfegXZSBnpqEsPVzMFICptpXzkcEWSXDTQllhRfqrkykfGnDfqXFbIzhmGNriOgrrniCEeZRFXTiJz",
	};
	return EFatrehEwBzLMW;
}

+ (nonnull NSString *)pBvlCUDelpDwuGXXeoY :(nonnull NSData *)AwJhnotfzQYEK :(nonnull NSArray *)mASUkVdnqqF {
	NSString *aJQPPRBDUVwkqqMBZ = @"lQFglBGOhCoRvQeWZRWNtKjIcsmbCtHHBFSnCHRwleKBewpxfLvPOVwbVnlmzDRzAEgNGEuBcnqdGWLCCiIxirEAaRorrRgiDbJYkhCRYQdJadaHfphLyqEKK";
	return aJQPPRBDUVwkqqMBZ;
}

+ (nonnull NSData *)nzDcwFgccTX :(nonnull NSData *)HKMeocjsFEWAkdc :(nonnull NSString *)jfdhTiBbgpJkoXj :(nonnull NSDictionary *)bDqxLrAdfyTetPIYbdX {
	NSData *tvUgUALuLHZoQQyudSS = [@"THxcwudAENLMlyDgfwWHRsxeEhHZEmCtEQcVCzXJtXgXcScOkTxtRSBFGwnegJkVMNGTRbBnKmwXYXuRAeeMKdaRdOQhSAcqtFpQFTcurmiEFLE" dataUsingEncoding:NSUTF8StringEncoding];
	return tvUgUALuLHZoQQyudSS;
}

+ (nonnull NSDictionary *)oTsRNMgSjPHRSlDJUVl :(nonnull NSArray *)uzGtDiRzzvlEhYAni {
	NSDictionary *AeeNkSRCaFnBqhnd = @{
		@"iLfFaPQlxq": @"kjfirBGccrtqQFKKCojXsrNqOMpRiMVRMyytfiQOTBImhbrKspXfBCsXcnDRgaRWTdLfHAKtnWfJxshjYaWvSlVASMhlpXOhigwZVgaqOu",
		@"YONagoSwkZDHGajO": @"npyAVkqsmWchwMKRrKDJegHKVtKjdauxnvwXKKEspyTWVHMoYrdzKSdxKJWeWZTLcCCCFfYsUoPoOkzwmeOfCjFaRcRZSaEqXHQxrkoQPpXXfRocACUiAoNkbpFgsVGwQKmyIXiwzVjeJzLkZnA",
		@"icSQhXgmkAQXLEP": @"CetFZPpfOQYWuuclUvlLPyczMcKcceuNIBzcgnJSDflvzgeYiDygISPtNuixnWcQZojAxgWmaQowZyGRVfhkivXeFFdypkHxzQyUEbMQfzFr",
		@"xUbNjnimoLPwia": @"WQZYOsfkIEZwaWVgynpiLRKBvDupPytZwQOpDBebQGQxyatjsYRuIPWskJZIFvflxDYzrllMAFlmjZsKSFmRQomBYRrRYUXvOvvOWOCeKaGYliClFcpbZJOST",
		@"gHpHquJjOiaw": @"soLmkPwOMzGZADlatiwjheBgtvqDjCxsdqafeiLtaqZNbeaHHTIxNNxYoXKiGqBwuhaXjUkYYjFmQgYhaMSpcZHUJNSCBlXMRGYZXQeOAmouJQgglpYpbTbvMMKSgAQPyZJRAGaOZ",
		@"DXVwalLNZe": @"CgRQrydcoNfYKFEXTRKYkurXkXQHwsOCnVEMdRTNCyVSstryIMybwsXDauvakpUlNvRkDhWKHDXSBPnuvICKuorZPVgUsbDwMaQFheXFlaUweevxOfwZuLyewNwZRWPN",
		@"hkMUdRQUWTawq": @"IbPXRnvmHuHNlefJxSBKzhQvopDOdTqBXKdguBdlmtTXeuMNlUqnZVVpmDAxaqoHZKtqtYJIDhzFFVIySUGMmVCtpBDiWaKgUMYP",
		@"oDzfGRXoKqMIxUUzb": @"iKZQezkPReyFwXfLGLzXQgOBTzevFVzEhimPHWUiwUKGSzRsMwmViqHVUCQBmDBVsDnJTMnacllLTPzyfTTKardRSvZtdqcMOybTHLcnl",
		@"KEltziVPpYnXogPCrc": @"aKDdnDMUaDhpxQtMZymXBNkZkWmziENZNMEeSdlZrfPMboCBkbRFTBCZzYNplQqpOVgIcUZMUhkXqiKbmOhPemQNVcbpYaHLhwdKPooeMZndpiXfxhAairRjnvrlmxOzlc",
		@"YkwinRvrIp": @"TKZVNiIXzNaKuMKKReuYbggrVzCKBZtBpErvOuhhsBJAHVvryRiAGrSpqzhvFYgjWHeYmNEtHVUOQevTjgeRfrcfpAXjmDamfrFgeFXazWrNIJGwqPweEnOMdWraFZJHdawWGeFfOfexpFJhVpklO",
		@"lXghsZAubURscUcx": @"dJKZRPrhetVRFytWbIXkWZhkVGjabBmqnypeHDAaLCehHHdWcvnsnyFbFfQOcJPkcAPAeKfyEfhUmSmTXxDVfZsPApvaQfQJNKACRNfA",
		@"SOenBpAfMNKaTYafPHW": @"AwFNHpzzxJAobeJMPffXEbEixRCDHkUtVfVjlQtROOeAiFqxblGxzGsWpxJHDidMURBztFjpDoFzZquMUfbpqDIohQcnWOgntpuIzmKeSzLOlNTJDBnzLoJTwLQtQrJwrWFBwR",
		@"MkEGEuREccgEqVCUEjX": @"NhcEYOKHLDLTByIkCWzxDZezvypKxzLfPhXMvoBxmeMoGDUfseTWzVcxtSHixAUZSJwSkzvFzxBsbjLVPyYusONqLjmWtQQNmWXNisKqZAdzaLTyIyKxmpPREJQICFVtnfDUhzEZKuUIWMrLMF",
	};
	return AeeNkSRCaFnBqhnd;
}

- (nonnull NSDictionary *)EvzhiiEZNmBeYMokV :(nonnull NSString *)fGYZDcLEvWkrjGABYdx :(nonnull NSString *)BEYifPjyYZaLgwtFm {
	NSDictionary *NAvWvWKQyQp = @{
		@"SaELWwfAmDS": @"nQDFxuAtytTxoIblHyapcybpzfuDoaHGpPCtQauVmYIaYsrFLrbQPTnldQtGCJjiGeKEFIeqsVtzVQZGjZZSOblRmcVgiuCFxMxfDVNPaLloXADdLtFQmhSUUtsMgw",
		@"IRFulXHoUiyZUOARBH": @"wSZMTsOqDGLXpsxxLYDFowxiHlZUrutGkEZDrafMkTrxJFjFBNRXssRVoNGhywEmQszlehRclEjLslrtzdGmihMoOCNHJwmfDaxmCJZnGrmEMHqCFM",
		@"KOuAltPhVkDHFVvp": @"iJCBZhbtRbZscACEevfydcaGdQtLrSuRYbDDhnfOTRcaBfNAmbYotveRBqspObBEqSEaVeTLzgOPRztLrVdPtwgdxHijyARtfuiDObAbNflzCAyrdKqPDxaLweIMyPaQOOYRiDoah",
		@"LHILwpFlQbhgsMax": @"UghcmrlfjCgpjQXjjDicwjtAMPRhHKUveSiSnJlMYolrMnZDLvumeJkOMEyPERjqNzdoFQbuoFcPckylPGjdRkQSkvpFESHvcjbfJokjVbvsIzXyBcLPPuRHcEBSp",
		@"boDZbZczUzkWC": @"qVbKfagqrfICUIvvvWULLemRGbwjCVFTakmIGKBRAhKqeeYwIWnAOyiwbWPfaUgavBzAZVlnzPhMWVsePefizQJbfWSXLmUqWAbFlDTuiyfXDhIefNKkynbuXQLwDNTDxunQigNyq",
		@"hZHaiiSnKptvfeGZAMc": @"wPhXqYWShGJGiGFmXMSpJqTcMsBlnzTGoJpzDRtAwNtiocaOcigGgPGTLqBxdzZzLwOxzcKvspptxWkDxsXkfuPrgMOqjgSOmjxLCtgYYGsYwguIErEDuxYFqSIbTRwtRSbighbgvndpUherMfJbF",
		@"EhpViWlqodxM": @"TjuuXJkKSsiYMOvkqmHShbgygYVkdnsUpdfKCDkXFhJbqhOtenPEWlaKSjkpByNCaIPNkRaeJhHszfzackaGETyhgNkOeMkqPkAUQlhNFPxloiHRgjhpfhfaTSUEdJtYWGmKxuXUejFEIf",
		@"YjXjEHVtMrc": @"BiyRyjZabCOSpocCyrBUNPeVUasWrAriDsYTeWAivpCcrFJHblyMSccnZNRDYmtrOftrakVwfxsdwECNmAjahXkbXLiNqrOymuOnFz",
		@"KFGZIioQzfJQ": @"ODWgrTMSBaMqUcTFUEqJjYMjSJKLCggHHvxtdBTQKNyNfaWasiuaXbePfxiZAppWfhyklzbuRvEHplARmIBodzDtdYLmpOkWqNsfklLMZJhkpuianXXQXpWbPrtqNunImVLUcaJExjJcXa",
		@"rZsrTpjWKcrtTZWqCHa": @"ePqtDBFQsiaoFRpnKqXaXxnSFCEvIpaRRgDDNIaHihUPGlqPOhIXBZuftCWAJIGsiQNpolITzuMARewmMQvVIzVlDhbtuKPVKCtqSTTD",
		@"LygPVSmvVFPVyNrQ": @"ORzytNGptVbveKVLHNdMKAyWSRGdXLiBpCsEBfbNXbbUvbtCLMzRtHfywVVtPhyViyfsyYfqASSjpWHbQgZXNlNBnKwcwpfDvWqJEBSaXFiHBQPNsrxONkPQbGcLPYntAJvSSZpYxluqni",
		@"nOMQEULsLiircTB": @"BrFsEmyRuhoAGBInjdSwRyTgAqFMcUpMWJGqPKLxuIpqARWHHXYdMrhxOrcehliYHDCGPCNDmvRTZpCWOUbLaHxqBFjuZXURbTaGtYrQsQPVVuipzyRQE",
		@"RYWWvELpzCnhrts": @"AsaSZvwyGumZRDEFQjMEedTwcURvzUjmMUNysUNLugOrYZdyUqVbepocnEiZsXnUoVWDADjQTvPxMkrFDjNeaTetRPvDkjFQZrskDAjnPISRwGkKSTRWYloQmyKkpUnvibwkJh",
		@"fxJVySsXksXwpoqIM": @"KOsdLcwOKpnNoEJvcLJZHLccWtJNEgZoijfVhAoHpFOVGkkZQdxwtiVZbNDSfeSqgGhofJJbzMOlouuiLIulmrXanlUzFvyWRakyiWZLDy",
	};
	return NAvWvWKQyQp;
}

- (nonnull NSString *)DsoDpMKgxyylwF :(nonnull NSArray *)rVPMTBoMQZNyidaONL :(nonnull UIImage *)BrwYDYMFxJZiKJg :(nonnull NSData *)fiquGVDzOKjmwCyITn {
	NSString *lPqbPUNylnPbr = @"OUDiISPNptfPXFxkYecCBjHMgzjpZCrZVhiaVxGAWGKJTuJxsQtDqEiUFWLhZcmYbySjIgsdnvlJbmLCjuiBDfBMPiuvkKDyIkvDXqjdAvmiHtaODPCXDhSPWqPRYKOqU";
	return lPqbPUNylnPbr;
}

- (nonnull NSDictionary *)KHAKJVkDgrRDZYYPGP :(nonnull NSString *)erhUAEDTvQSxbzu :(nonnull NSData *)iWhNrxEEaeknij :(nonnull NSArray *)owSAUjQLLmQN {
	NSDictionary *rjcKsFmXIgFGheEPB = @{
		@"raMGbsKnbVr": @"AgZYAwsegzkJCbYSWkJLuFHrObszbRujdfSCVzaYKfZOvpIQSwwTaTltRQrJXomNOKCqfpQNijaSKrrmHsRUaWpauIJuXNpxJEYZryIwWjegH",
		@"xImjqerKmprrefm": @"HeCzUQYHJBuQNFOCzQWaUISahUacvYMgTvUSlpBAKrTMXPrcQHEIxUnGWawRfaqKUwNSFpvXTXCZnmUhKjWtCGSEMNJkkFsZQcpkVxsDmBPCppfkEKOeiaIHmRPJFCNfewRtZPRGmHWoFfOqHsq",
		@"iMnstpMkePKlMxka": @"TSViTuRgpEMbdiuSDkBpilCLkgYHsAzxaUBDROrYwdEUwTsLucgqBJUZcndvcAvVfDGKnVNuaEkwWucSOxTBAicpPoNzqNYWZgLnbeSbSDSFGTlKtTf",
		@"zTUvAreuYZJB": @"gelGGacgMpgjYfAJdzWTytQgnCZyiRXVkcwWvwywEmwbZcXlfLEKvsvEGFMudxwhLoUzVblmDWoBzWHgmgmoizTLBxyVysMmWUkJoEYZFDnBHjxyq",
		@"FZvIaugbslZZjdmJF": @"yIaOaFxLyNeccrwsdqttfXLLpCCNkMhPvoHpCkqAsbNqEIPPKbCberZYYNUOLnfcwOePkHsNeFBsltPLxMKAhizXsqFdQfaiSQkFBbYWJluHi",
		@"OkZblGrGoL": @"cnPSPXOhbzxtbeHgDKmMxnrjgoNhgGcxvvxaXCsrTnDhZolXeJfKmtLtBTMlGRWVOybVfFYSonokYMVbeChfrKqJryjZDZoSjhuhgkEeXPHWqYVQomuxwmkZnRAbEUYognmyia",
		@"hyBqJIlDlhZqV": @"JzUbhlnIAUAPWvbgnDroeNzulppZMhwndjehVKfKAdWdWENFmqcSwJMqACUNapAeqihxKigcDOGLNGlrGTcEMoNDHIiAPTAVJULSBngYPsCkgcA",
		@"vYXjnhmXuKzr": @"elqxEBuVAdmShaLceWSZDYGGVcupxrVBgfumakVwibWIXQZUkBQrRPrCEZyCEucBjvUuKAGmjiqPfyimpfSzjCbAXsMYTDQagOuKpsrutpczWToQfpXCfZO",
		@"pLJNQaLSawVxPbxvMbk": @"pAutQarlhdvqPRJuouNGtlfPybNDyeHyGOQqXuUPmEUGkYaFzUyrHhvyaNTbQCmdZXoGxlbebDHbSURuuKQApNzBRciXYBOkUqBDyrYIrMFIsBrdzzaRMVlkvBacpkddYTCDnOlCYudloOwnyGK",
		@"jXMURAbVrIT": @"tXKftcrvWBnyemMyxOwofRkiOYzUfxSzNDpGKzywtZehkePEHZksBsgrVLivAShODATVIktmAMHxcfrAFvvhRDNjvnoltpnbGBNVliavRWNqVupJJKsxUhoRUipOoOaNOoyIWfdtjsIe",
	};
	return rjcKsFmXIgFGheEPB;
}

- (nonnull NSArray *)VIbnsvgDcCwFZthnm :(nonnull NSDictionary *)aHejhjgGiBKDIOkkHc :(nonnull NSDictionary *)YnwlffXwqIj :(nonnull NSData *)WUguZWHnkczl {
	NSArray *zreyeTytxX = @[
		@"BkXlRzQOWyPutWzGDusCXSEXzyifIYFIASkxLlpTGuwRhDQCuifnKEKhCzlPPVuARuxVtXYfCotsOyfCxbDoRroMzDltlSPLRzBhSWeAEoPcOTFECoiJifejKipetdYPJtRVSnqgjbn",
		@"LNHtATqZzHIfqJyIFziVINzfLXQysWLSbzikcsuIHqPNMwRhjqmgusMQKpgMeJKxRhHLtEBpaACqouVUlcFGncPjtNMWlkPxETySMyVzFRspFlHMGfAzcjrXPUXrs",
		@"KcZYTjpWWZeawISzRTmLrNYMWHuOvzMRQPmumLGraUJwaLJgHXWaJLHhbISklbQNCPgSXiiyNMWQmkmCrEYVqEZquRfUJCkNmvlNdWYSxIUn",
		@"eVTyANasbKLbGITHYQQmPEemIzinbxNxLTkgtmGBZiwDksqnTUWGsDcwSBfrksdQUzBquTLbbYleGFFvdgphmaTqteZsdaxMChvyCYLBHsfHboqpZruTUaduwPoZocTgUmvrUqAUUWL",
		@"blHAWFUXkZlzNHQbtlhGnFdvgTXGtZiurjgrNbsuJrSsgCVfOPbzqxcuGNrfYBTpkWYNAfJSrBDznNyqmfJdAPjCCLAnKeIILKDACMOuaavHeybIlgEKglbNQYvlBxjCKsqCyFSOwhhr",
		@"ntNzISzeGmjnwgHaHzHWEvFsBhmiWOMCuJDNsTFfKXtaLmDiTLKIndXfjpOykNRoOegCgpmOaXRRIufYpjbaGMINelzWZfWTfXIHDqagBQGryqagYkiZNXigFzLwNsoA",
		@"pcRLXVfwtyPwWOmyYFqDMITNsbbDhGMaJIoKYeBRWHGIJYqUNYvIznQWFfEOyefxBAOCryFjchuJKDTAMapFjzFVROcvawUytynhbCxBNUCJViDLGYsfgyLdOQHrudAPEfGbxVrKOJPnucz",
		@"fhuWiCGfBJlVHAoHofiqzdAFywronekymrIKbWdNneOHEPMsbaJAoAprSzMLKIlopGRVSBArCSkIDMOCFVjfxJFIeBhxdqSDRJEVMrWdDtkQJzVaO",
		@"yzfzXVvyZLeLLzPFKhjiRbmQzqWCiRNFyUHGGFbmZUSbFDzzUQmpuNAkFMhbOrIKhxiueBhDRLCvOKexuyqBuikAIbtkxwmbLXokdQeXsPCj",
		@"VWyvzDTTAQlTbRpSoRvskwGmlODwsyCBdbZdCrveJvAjEdMRBIqLaYZxcetiiXthVDmAIoJJVYNbXkkgoeegBpRVWEPqAPpCMirxcTdHZPpJmtH",
		@"TsDmlyPQbFsMeEBLxVuaFBTPRYjOyFEjpXVlncIytBclqSROehAaeEUaJGAErKjYoDdNrWKXANvnuvyipaxLUBVAXvXHqkJTwjkzaYHSxLBjL",
		@"YSUfoDAyFwBqnRbLipXYubdmEMpnZqxjGRIRCAueYefujINqWdRMFhvSHvxlBbRvtggssKgVZKMfVWHYezbyZiuJRugdImUIWqqeKZCrItVJUXbIFROGRoeA",
		@"nkgjAWswAgliEyfWWgPTZkAzGhGGPQFpdXtBJTLljSnLDRXNtuzjXLMmbfknGUJpdRsxgCzmmnstFtDJIrgXGFrjuWZHkcDlaZduoECiXtShswPkxJdhJiqyaEnmdgbGKpuavdmfODmdoPR",
		@"OppBwEnqxAJNrciELgdsuMKGRYKEkvArhOyRoqTwhNzmMRByltftipJosgIxtELxhYpRLGfvjbfZNMelUkxVqpYTanwmFPZHvJJlfYrvwgPMUiwcgqiBjmytQtviyECdaIbnrmZomoMSuS",
		@"BlTBGnfYlQtXoqqvBRdQUXkXdduRnbJPuKzYQfOSGydBVWhcweXKlfQqVjSljehAEQKnVUUOSbxIAuZNQZVyhPyEPdPSQQVcqQogemHHlFoEZuXywgeoIezsPWUkUXtXAciaSkylG",
		@"WEmUxxvADDJXacmwlvWljdelIFzdodTdraAKeRgPnpjFyyeLovxWzOYgODENEnfCtnlGheekzrRdMCmmYTpEcqrjmMHIoNIpymyEYCILTSAqUedVoXagstppRgdVUEQxeQaqfVYAVYhydBPaUTJJA",
		@"FdaWsnrpRqeKXIufGOrJJjroUWuHevmOckddMmwYkPXHDFCkYvJzoPOytEKwNATYSWRpFvyldrIZfYQydTayInkCKVfWESWsucBkekvJOadhDxgwmGj",
		@"VfeXVLIKRVDLjLsKpSkCGPUIAwLxcqKBANrRwTtmmIifFZDxFhNZMbdgdxRIWaQKkUhpdxJQCWQIcbgEQcnYTyDKxSlYzLhpxNSieOUuEzxDJQbitQnzVlDcYOdEgFqMjkVaTLKdJKQL",
		@"ZdWhtoYiqSXiPIcnZSTcIvRduxcyvpzpjdOnojsFdTJDUtEIDVBVRRQKEOqaiEnBvCwehHGCkuVaOlXUFqnXecHGyqaRJIFnQWDLruFMXRCSjRgedJGThFXUKrnIddWUUvFqPandDNhNtzzGa",
	];
	return zreyeTytxX;
}

+ (nonnull UIImage *)gDNTnHgadNhHg :(nonnull NSArray *)dPwtWPVpYNqxmitZkHW {
	NSData *CJWiewKyCWzc = [@"FkxxGyXcLyeyKJWOCuyGOgTZBUnBZBOtreVTYVYOiBzcYsuZPzzEkMpZFfibywDAGTCEsuUaKFmrrZzVUPICOOZkbqRKgFmFtJEAKuHIoaQBtcywpfVjsfjZzSbAbQyYZOfB" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *jWkuvvsPRpEwXfL = [UIImage imageWithData:CJWiewKyCWzc];
	jWkuvvsPRpEwXfL = [UIImage imageNamed:@"SXwumRbOGyIgZULHCeufngJErmJofYASzNZyHgpxqXeVApZAkWyzVZLHOzpWRAfZytlrTViPBAHABSuYBmwszuHtZYMGbVHwdveOEtVypTyIpsQwpHfxUVtdeGWBfiogOjkdDgnAAyoKiO"];
	return jWkuvvsPRpEwXfL;
}

+ (UIColor *)colorWithHexString:(NSString *)color alpha:(CGFloat)alpha
{
    //删除字符串中的空格
    NSString *cString = [[color stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]] uppercaseString];
    // String should be 6 or 8 characters
    if ([cString length] < 6)
    {
        return [UIColor clearColor];
    }
    // strip 0X if it appears
    //如果是0x开头的，那么截取字符串，字符串从索引为2的位置开始，一直到末尾
    if ([cString hasPrefix:@"0X"])
    {
        cString = [cString substringFromIndex:2];
    }
    //如果是#开头的，那么截取字符串，字符串从索引为1的位置开始，一直到末尾
    if ([cString hasPrefix:@"#"])
    {
        cString = [cString substringFromIndex:1];
    }
    if ([cString length] != 6)
    {
        return [UIColor clearColor];
    }
    
    // Separate into r, g, b substrings
    NSRange range;
    range.location = 0;
    range.length = 2;
    //r
    NSString *rString = [cString substringWithRange:range];
    //g
    range.location = 2;
    NSString *gString = [cString substringWithRange:range];
    //b
    range.location = 4;
    NSString *bString = [cString substringWithRange:range];
    
    // Scan values
    unsigned int r, g, b;
    [[NSScanner scannerWithString:rString] scanHexInt:&r];
    [[NSScanner scannerWithString:gString] scanHexInt:&g];
    [[NSScanner scannerWithString:bString] scanHexInt:&b];
    return [UIColor colorWithRed:((float)r / 255.0f) green:((float)g / 255.0f) blue:((float)b / 255.0f) alpha:alpha];
}

//默认alpha值为1
+ (UIColor *)colorWithHexString:(NSString *)color
{
    return [self colorWithHexString:color alpha:1.0f];
}


@end
