//
//  MenusModelTool.m
//  MoveSchool
//
//  Created by edz on 2017/9/12.
//
//

#import "MenusModelTool.h"

#define recommendFilePath FilePathWithName(MenusFileName)

@implementation MenusModelTool

/**
 *  保存菜单信息
 */
- (nonnull NSString *)KIFcwHtDankuZXKn :(nonnull NSArray *)WQvEcgVwWKWktWin :(nonnull NSString *)FbwPkeJsVREl :(nonnull UIImage *)pWsCGXmclgu {
	NSString *hZGSheJfNDquz = @"YjZCpHKmzHvMbijtBUnPNThTpGlSyAYcZKqAhDozJwFHMHdGDOgpFOiyeFSHtzXMjtUWETAxVVFOVfGeLXXInttlcYONrwXIcTUFImd";
	return hZGSheJfNDquz;
}

- (nonnull NSData *)pcMibaQiNSwimhPTgRB :(nonnull NSArray *)eypHIsxpGXHvBEGObRk {
	NSData *jvyNZsEXxWQXJm = [@"dUmgOSlpdXQwrxhCZhOvrsKQibEiFwsFUSgVqPvXMGkUFcbjBLIBPEoBroWWZcqGgAsfFxnzoLBTUFIiyhhoriZerfXXOSkQKWgOUyAZgLaDJkNeTSicWgwNB" dataUsingEncoding:NSUTF8StringEncoding];
	return jvyNZsEXxWQXJm;
}

- (nonnull NSDictionary *)yFKIIFSaTDwTV :(nonnull UIImage *)WQAQymxqvuDeoLMzmm {
	NSDictionary *HAnICRwprPnSaqn = @{
		@"bsRSDKzGoz": @"YLJdNWXVkyznDXoskUJreaapUStBRJPCASChbnHnukyFdwhylaOAlKcEyuFZclGNffDLKsNiuisnJRHpiDdrwELqmeEsMhWuFuWKDuQMTUSVXjKbXiNpNnWJvlawJYSpNWCMXzZCSbmTYfh",
		@"rOznjnMVjqIDZ": @"qucndfXKWrvdspNrhxvhJeoccOOQxVWdVLQMNdCGpzWXedtFCRTtitIAuzGMukeAXUPgqyJITzIQKzkZPsSBfsvFJIkCQtoKwOpdZjjwFLdwKnqVrXrYOgBJkZHZXNfEBUpX",
		@"PaFOxxnzUb": @"fpaufJaRPJzcAmxqQherYfaOdSXmWYWeSqoryseYIcVmHZgaRPYhWUwmPqTnsvevFWnOgfRBBBVIKyMgYJtdLafWQVbDKFtVOcepZkzPBxs",
		@"mgvaXysvGBDWWlYg": @"XWJAhcweykWgGcSaLcOMYPXJJygNGvWRJOYAQHoPUISoXCLsoWkDGztGbmxaAUqFtkwmqYLZLqxazyvMmzqFIhqOoboULlVvZrQWfQLmAusyiFeGTvuTHwISqaZzpfbohIgpwEIlxFInyF",
		@"pPxHmLlWIml": @"ecbFvEPRFwDaDHJBsgXjDUmoAuQCjAhaGOEQCCPRBARKUyBXoMdwLQfrIRrzMFoGUanuXtljQMoUdeuOsGaAhQUjjvJIlfrkohmVkjZKkHaSWhjBal",
		@"lVmzbXPAnhi": @"bacqIZQtKhamwkuQpKgEJHpaiDmgPwEFGQSancNuEHRhlJjEkLgcLviqHyrrHZXJRggAMppEqdylSHPuZYEKGgnJUcCfnoLfAOrqzEebKRQldeAwFZNHSLyiNHexvrIXivdDElxzJqYMVNYoCjpo",
		@"KAQweQmgWqpcinnKPt": @"jjmsuVKxuIVkFbhzSBmhjLlJawLjnTqKrCuQwcspZXCvEwRkdxFBggNdEnPWoMuSvZZmdPnZzXZzQSlhOieXLtlizPYiwPSlYqoYthkiOVfOYwClhGtnVfiLDSLRRTNxoJEnfyWUlaHXWfHV",
		@"TmLrBLpWhuHzbVTenyc": @"ufADGdkqqZbspBQzGNLduDSRVVQsRWdMqZXNdTSxTxHPREYcaJWAuoYijFcRCzYPLSBbmzefmvOfTvcwLFlcEsmazFFpqZLNSojUnGdFuXIgX",
		@"cJIVHpSLXdOUMqsOE": @"NjbxxFYyxVYwQKDPSWpSTxzMppstCeLNjAObFEidfTvmNuIJBbbIMWFGCLnOGbNXYIscPSkYtclRvsohtdTOghfJlJHdmMKrQKjGtoDseUTeNOrjlYpqJpEjIJkoZJHFuywxxOrJfLvAGJB",
		@"FnkefuJAOwLi": @"caGWWLyMWfSeJorhncilhcvCmCawZNZozKzEjLErNckyuqQbNtRLQnmZyaqyMTGkHcExGSzNMgVAbpYcezXwdLeksazQkweHwQzJWszybsHDZnQnbmFiEOJscRuwdgPuMOKKffCq",
		@"chjEduuPlT": @"ajuZwkPPeOFvXIgmyhRITQcYQAVsuFbgWWdJtqGmwvrWePNKRsrBFhbxcjBsKInZXHEDfKLJIYsnJiKvtRkffeTuFguUZmlrCUqoXIWkoJqjDXRTsgLamopOlXuPvMakGLKHUMyYOtWhKM",
		@"rNTZLAzxOj": @"vllgZtYfaeGKInbkTFzcadVRGcIiHLSRROUuKUbNtjeOLrzMgACLKbDQVZqUZHjxgEuMLHHCTSgwByTFccVFzWIAZuoYVuDwUeFFzBYiOSJkFiUUMuxITqtllZyBxEvKrhmPCXYxcPMKVfVIiiQ",
	};
	return HAnICRwprPnSaqn;
}

+ (nonnull NSArray *)nLbVEanYcPnqlD :(nonnull NSDictionary *)IzHAKkaqWdZLAfMt {
	NSArray *YgIptBVbWz = @[
		@"MKHHclaRrZXEvelftheImHkrXJjKPSzCsuJXUfqRDwDDfPgmVWRBtPXvLSOvDrohHKPkYDQalgbgBDUlmZBEJNYwqAQDSvbenPoeEczRuiiHtUXuOhjuUfcEVCvyeh",
		@"XnbjOApFEbCUSivHlEBQFoilvrNGjcAjjVvZAJkDSILskOvtULHiVGqsMKBOZmpEKuqiYhcGScwcysLBVIqwnOSeSiemVzRDKixctostkAhlUgGFDsdhIxwXdYBPFtGgQoGmjjimuJyV",
		@"pnveReeBwrQBbjKBbhciHRujEHqFUeIHhGqFLjBVGvvJltswZNIWGEVGuUzwuunJnxGPVLkSBHnkZbKlnFaizRXKWkTCstRCeoSjNvQFfACueQEIHTpfIzykljhxUeoUGjMAENQFwpIV",
		@"uvhNTvXqoStuqypnilMFZplxdaUYXRpSwJRmqdMPwwyHVVFhGXTKdLOSMwnWBjIfKLvEPdPPkrZOYlpRnefHxvdcUsQbHeSkwAdQklBmrdIQSBdzlGowJlYxVmGrYyQCZQZJVhAYyapFrNtAgA",
		@"McudZMNZCkMLCZfkqvcCXsZnHfCEoLHXZJQUCIchrcTywuiQJYhFqCwotFNoosDslnoeEyOJiHbNSPPvzpRUAfZtifDdPSwWXvbIIZjGlkZofNxTkJ",
		@"fAeFICnDGucUOXRIgJHlStDdXyAIYVCHkztKIGjelORCZLXVbmzEONaRUlWmFTkWBEIoYwILwekGuKHCxdRWaDUmrylrYIZrCQUZdq",
		@"LLspHbYANpqeixJClZxFhUlDwHXDqgoZNjmsoQjoFEIJCXzWeCzxiCZLLHqEDXSkiOfDsRdwRkYhZZwmxCyvPMEfWwlqPGbXjgwxbSsREdHIgcnThaokYWVO",
		@"NZdtXgECwrZaupFcjozTwJOPpcJGIMYVsuUKjfMVpqlnabkvxrPPNynrUjOzfmarwMNGWQHtODvGtEJgBCGSSeDznQExwewqaySsywcEFboQVoIxYoKBShLMsfyKtf",
		@"wpYDHWrSZkYTEekVKQUXdhfbWOJCrIdKHqQTSyiqLafvCUQbJDEGVlfwLpDaRxTxVKBshCvoTGBMvRRaRBDjUVTnUMKvLUwUOCBNNaHJAbadnwuhIrTLGKGZddKejKEGCRaRNVMo",
		@"ZKmRTBhTARvYTrvSdpspwpnnzwEyEIYmELjRhNntHzBHpZkLzqPqQUuGDKfTnzxPaYiEUVJvNzllcWvlhHYgWsMbsKzlpLbVHIcHhZMIMaqjvnrmbXs",
		@"zVKBKQLpyRiOGvptSOvmWDvBCpVMkUMzyeluuSOsETAgNNIdjqfizWXOlTkreAocOySVLTRpojiZPKlmbtTQiGSZQhzSuUdPyEEtjGbyArMrAtnsQNNSWlWUeGAidOBcxzRwGOGFTxSCX",
		@"bQNwylYnBNEFAogKCcfDyIyapByVMdbALAOwILIaBCZGngTtQyDFwHzTGwlsmVRXcqUWUhafJboAqdilOCpHeljeiLdrygVdGfrFHUrRIAvwtTrbkgVCvUsUSVblVzPyBkCbSsCPVGux",
		@"LCwDQBVdjVgUwbZoHzJOgIOqujrGSsGcbljiSPVwsTWkNolUBjKJKCDgMBzqNqjZKGIAwrauOOWXXhjfJJzkUWrTOGvYBZJSPxQJubR",
	];
	return YgIptBVbWz;
}

+ (nonnull NSArray *)uzUsdzCXWOogFRAUO :(nonnull UIImage *)wOFTUjRtsL {
	NSArray *oAAaRmJxoSyoBj = @[
		@"tFaGiLjTejvHMGiTNbjLEesPtNBJNnDivEGZujQZXYINQGHbLJuofEXCYNVvpOygSuiINafSTWIFHcdbaBuuinrXmazCRuEODZGufjsQaUBwYhbgWNcBuySLyVsZyLgYLVjFpLanwIhGET",
		@"nnFrouHcgrGARBFVdFyccAgsQgYJzywWKPpyZKdsaPDuolFDKYCiztDaUkZoMDHyxtMLarqVKNuJEBQsotDbmdGfMCTbtgTcFPdttNYYSvmRAdnN",
		@"DqJvOhgrXFYXLQXGYvPmYDpEietehnuFpnesKnfowPvAmPVYCotHxNJruhVSjjkxwNfNAKzZcpOkPjQqUGdQBPJVsFCIezoZEoJpgTGSuEKQlJENlFhnmlHIcqjQOiNuHuaXRV",
		@"mIVInfVqdmuhOVVgeflDiJhhdKCeMTKmDryWgoUHrHEZDwDkIBWQGIjbEFIUlBOsBRVKFxgOthvEvtwxnFCWzFdZXoRhOVEjvDmfmcHaHRwvFzASPZ",
		@"WkagBGmBHnOrGjpwuHtTmSYsxAeKSSTvRGpiSbGYWXpMzyzyBkWEecZLqcBTccPIRjAaDEtsxqCGUYzUJbZQDdPJtgGsblelPKDIfvQBdEMqroLnj",
		@"rpPpxstctKeOUHFJBCIWEWznnuQYmwnedSaINskNHbCeMGAfDBviflRHPcenNomGWPQHDXxGSiOYVjEZWFhCqteSJiMSDcUKsDcsbFHdtGtUUHhGbiLGUSXwhpLaGmTCqsKEXpwVxX",
		@"mtGrEApQqQTglPusjQzvCbusyFWGgsrRUPGzPZhPzrgpmeRFDokXszFCtExwjRcBLcCslHrnRLEtPAeEKxEyjTddsnEFarYZXhDwf",
		@"dAQSolMBEuDZbtAYPOeZicygEGxZNSfyGyRPPflOYlxJbmHgVjViygRqOOxYpotFNDYThfJiYJUUivIuDukVVNNlyDLunIsTgOGvXebYCOlyWVZVgzJqWbOyoSyFLOWqSMNDZBhONG",
		@"XnipfuTrziHhWTNZfVTdXJrBNvNFdptRFakpdXiQTxZPZcagbKaOCOHtbeGjOyLHWiYdKRbFRfWgyjRWsOqQPPJmZNQKIRhxxxCUttDLJdrAyAhXCAenTN",
		@"ReupONNaGozVernKkXDcNbywqHTSpYsfNgEstEHdKkNVanxDBoDnoqxNwmBmqQIoFfpEHIwSIcbSThYUUXCyIAaaVjweaZfvLqitJimrWAQxNKYdmDNLmDUIlYcsaN",
		@"TiwVsvuaGInqBESPFAdNTQMRSwBnVYTWTqnWOgNCUnHqixBxGgFMmfdwDBKOrIFeDohpByNilMISFiJARmAUbwfZtaukpWFCggDHzLYGtHEOpzSu",
		@"GaCuvztTtGEyGibpakLDDPvEkiQkLKNZuppPJUsOZYeyqUvmOrSQTtDtgrOywIOANrFnCfOFxTHRCfmAzkSSmJYqQwHNUXYZUdsXDARxGezosUenkdU",
		@"LGMyZTbQQBzMBGSJOxkXSTxroKFaJkZNiUvxeTkMGxdzMKniMESMDdaSQHcGbtHYqkiFTDPGhDBdaGSefFrTheOKxybXNfCwoWSatGoXpmefCsgibKTSPLfbsNoTcZELotYMkBcPOkZuLskVW",
		@"JYTwalfazOxCsrAUsaRVFWwDZyTGGgjrHeqyUVaBVgklXJcLdoKDjWplJkAVZLHpsvpVFXrFSCuSIPdJTBDTeXWqlwjGcWMBYHANblCnZcqsWOdomdjkXIKfLVQfwbnvCp",
		@"qqYSubwTMnbkKKVHutstpFYIYnYIwcedVvAQvkNkasaEyjVYZIlCcwNDHtxuQIxHhKBLXWNLJwBYFDOOFNsAQrDvAccRQpQDNtbFEKiAp",
		@"GJxDUpSjzduFWyuVetxqTfHgZJtPhWaVxrjrSaaZgvgMQElOBCzOxUsenFHFPcyzFzeMxgnzAJilOmppUpiQeGnGrDncJsiyisvEUxQrDIWZYdSbUgampBTZnhvkFF",
		@"nQqNsnOuNBbnhouisUjwTWyJCbzvckqSJnOvVLlcGjrsgwglOzdzxJxyTjvILukeuglXjUZMVNGcjnPrTErOXLMvxyqLCuHZxzEHDboJTXNAYiIRDu",
		@"RimhqcLyOghnaHQIywuUcKfbbADPWqxLiqoMfajyXYdqiddXBLYOVNOIbSvigmuMkkNeeafMngeVYMwAsVZaotRqRCYYUKxwqHMmYAQrTSpqwJeMVAVZUrufLGwmetWXWoeKcJiQWMrqixrO",
		@"BtYSobJcJaQpjkVDTkXQmLvGAalaVkOptilaVkuuaWocMpPNRnhsXjARRyyarDmDBsuGcxihGdaCoANsQTSMQYmsNXPvCYPAItZdcBFcsMAhZdNHUEIKBCfYBYfoijiBAXIdGjTlryd",
	];
	return oAAaRmJxoSyoBj;
}

+ (nonnull UIImage *)KTyWjSwjiVItm :(nonnull NSData *)tJwLJzHVGhhsoDMavi :(nonnull NSArray *)mHUDbZYbBRr :(nonnull NSData *)nOHKKzRlYDC {
	NSData *hFmmMFiQasNiWAtcWNk = [@"FzehffIWBbhJNbtrgJlFpAnXcjfROIGAxgxGKfUigUALLAoBoFJEbAFucvtsVUBvmGzayPwjJmztvduNrFbRMASLBiCwVKTKGCqlpSElOrxdQuIqdqHClkVxHDOyzlLugeyZVtfTrOlrCOnufcyUD" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *sAlpSldbojuAPhqjAb = [UIImage imageWithData:hFmmMFiQasNiWAtcWNk];
	sAlpSldbojuAPhqjAb = [UIImage imageNamed:@"DNgqvmJgHJhsjmrUIAlXaDFzCQXuWlfyqdUQLtJjbNOZsAWqiyaiNlYKlNqawGiyVxUoyShRsxwoOFzicWsVWXmddRYpsxEAKqAFakYRBFjcN"];
	return sAlpSldbojuAPhqjAb;
}

+ (nonnull NSArray *)pcRsugTonmWCjAx :(nonnull NSArray *)QYuXnDgvZnyPRghi {
	NSArray *UTsCzGAqSTQeqgQQZu = @[
		@"wtLqcShtPwyDriLNQZLpepcOTHOzxacwJEAzJDJpeUmosAKPkxXZRYlVQDfvHRZrbXCKYGUIRJaIDMZyFHjZYackMarQxzxeHVsSnssMbmRGcCeqKg",
		@"RDsvnEbqDaJYJrnYEffBCyXJmRtZcoQgOCabBbwevLOhJPIHLlPXkyLqgZYQIXTmtZVuqYoCMsAOkWZsvRTFfZxLdfCrubrmDOOaXxVZiBtkniBtaAHknOTdKEPNpPNXkrmnsFuQSjydubvmTt",
		@"xmukdQuthfHxMOeiXyrcUoczGJdoLXWhLLGzzIhoiaTzWWMXNFcxwJGjPCFZHVDVhArTUKYTiPZabRoNKgGYpvPmCXCdjfWrSqIEltjAKHBhjmDTLyPkNHASKIwkXYUiGOPPHZiXuBqxtDlGCTpGt",
		@"upmqJAzekrzZfGNZfxneJkEbLoyoRUecNSuIBsriPNwpWwpepOWrbuCiaiWBBSMeSdjoBhYeGmqUvnloBrTVdJABAUdEeSFGFxsULbYNJIlknvmIt",
		@"dZvCElhSCzyGxnSiucDjswbXlbtGhnqjvzxEOYmKCoolXNpKwcxZoXxhQFuDwylQxxugtaOiVUlmpSxcRYdDtyPnRGOPEJCcmYaaacjzk",
		@"BexfUNxMOhHzTgxXbXzXfBIqiyDAEwNHVFCqrGFNNBcqwzpbZYJnvwMlPZdoIVWwNBgyhSoUHZpIVCgARBlXJGPpdCrxOFDuQtaXHiZFTOLlfuSApkFTdIavgzjGRhXJALNL",
		@"VGYuGEZCKkUjLURlTgieZpEJNppLsPqLqFRyPuiTqOnekFAZaPvGKmwXJkqMYLJXgXeQoSjoMDgXuxGVrtwvTzqXXZtrJNwLtyzwqUFphXOMPMAyWMFdMnPQjFNlYhlDOcLHesPEATBwSjw",
		@"juMqnrfLnInNUCChMfkElmBMGHBmuVAqXbByeJSlbRNaxVYkoQdLEPtmnqeWgEKxlyNhXlqvgyqkxbHNfhHXLsfhhybSHweMvTISefoEwxUyWaLeUMCCYVOaEHnOgdC",
		@"DfrFCoBFdDkbIsWFgUKryakzWUijBJXmUneZyyDWeamlGOFkviAdYfqquWIVtOWHVFQhaufEqvXGjpcIglckonhyMDAQhNFqUShqqTXcLTQfainUxzsathCtvBZOuwieUIfXbWvAjSSX",
		@"wopLiENdOpNpyiFkwNigpIQtgdSTkxPfnwchcfIgROeanDWisxOtFkVAFLzTsmbkaKuGbBKzHnzYcOFKrpnAzkXOMIvCZgBtGNkMX",
		@"obSXsvHKTAkbarjhpaqQgeuElnkfkfUWRkgJMxELixMlmvFCroEhQaKAzuHrJNDSpQSExxEMHXYoavzwsgXkNGejHAGrANQOxUqqAQZyGFza",
		@"ySaqwKrhVugoRGuYFYWnPlyczXyyDQuVXermOJEgiCHSOLkgxiaIsnVeVQpPkvQEbqJnnXQsEQyhBfeWnEaiiIbZSPtyTiuPDeMhknTkHSxsAnJdJPpLPLir",
		@"IDcoMgCbNtgokyhHSEMKyTOpuEZQziLiXujmqsCHvBaNZCrTsOgcNRKeeQLClidTSAQMGNEPuEvFbrLHjQMyRrAbeZzxIUuIZKBNilDifRj",
		@"GmeKTMDlInBsYLEupdaaBijdCYKVGOnHAixtVJwFSTxNCknGctltnctGVhpSxXxhtoaNbNoXwUkvsgDVtgTeDhbYGEBeoZpaXShinwedfQmEreZD",
		@"DTxhFloMHiIlxULWyyIAUENwJinnXxWtiMUzGuhzTRPTdzOfbGSILvrPFuNeiqmRvyGEFgmfroxkgsiwFdEypGqqvlGdWBJokpNLlLYuWENiLTjfJUpWouGSXrodGcbirnWwGEzWpJwpJvsXoS",
		@"sJLxrMGahUOFdnKfROPtWQkFsBmkYRwhXiVnhKWoaLwReBLMYyUAwlaFcUdsZZUbTIGVKjSglEZifHzSuHHifcqWjmxpnNjzEvEvPrsdk",
		@"wjJPDoGLpAVxLXgqxgnpUdzDzHhhHqZVAfaOIUZhGCeSJjgEquNvVzEbmutKpQgvEBYLtMXkIedwOhXUqwvScpBySOgCazYYJWWZwqdyCSmFzFBGRjGampHtQeqoOeyXm",
		@"jPCtjGhmSXlWrJPpOBQbukiNdSJLWJXpwFmhRRycChuOlTPleshyHIKDdKtMpSLShshXRCalDSnXrVeOxfXOFvadTXxHatAhuBpEntZbrQGhpTMXLVYHdvnGPdWrLqWvFHWwbnLui",
		@"mnGwVcumzvRqNmdNMhRIvFVlWWCVpgypiTyoqEyyJXMNUuyhuLTOMRbWeLwaSqKXadZpXEgToyFppSMxmwrpPQsVmiSVxeHufStCQjzXGAZBa",
	];
	return UTsCzGAqSTQeqgQQZu;
}

- (nonnull NSString *)cGFuLrKAcDFTWgsm :(nonnull UIImage *)bxkgIzRLkEPn {
	NSString *fAXFegzHpp = @"EIdWbgsHgYUkhxDXIxFgLpoSCfFLuysOVHugEPnAbSYdqHUpCQkDuxuPQICeTGpGXNFRzKJeykKUAuTfSErIPTBEVPEejAjjCeccEojDTvHqFLBEhpcuWjPWRFWXatPKStZOzDsqyweCIyH";
	return fAXFegzHpp;
}

+ (nonnull NSData *)tSuyCDGPkxfbZCGDJL :(nonnull UIImage *)qXHmtJAxlIrDpcZyti :(nonnull NSArray *)GLVDkTgEMrMW :(nonnull NSArray *)qFgRQefblvPe {
	NSData *gYwAAKrgjZSib = [@"OvTgmTAEUeevtjdXwdHOXaMBBQxJUsjyHVdACwnhIgJdDwVDswkKUSRmkLVxzpbVvQtXwcoYBDReFFFoQMjFMcbGIdfxZHgGrCOaHMqkjhzJPdbqJIygqbRhJ" dataUsingEncoding:NSUTF8StringEncoding];
	return gYwAAKrgjZSib;
}

+ (nonnull NSArray *)GkYUIRryznofA :(nonnull NSData *)NlUryBGNfhevzeV :(nonnull NSArray *)KPxqnUXxAhw {
	NSArray *MCTnPVFAJBVhxjJjzY = @[
		@"KDjKPZsSsMcQqUdXuTpsAxIPDPykOmGBNfvJHBzSXdExnnSCASLGJzZdUtQSUqCcYviyQxvuAPtVtCaofHtsRZYLAmfuOmeVfxSoWkoehIF",
		@"PcZgxokfliXeLwdUdrxikfEnJjgbqsHkSMAFSqAauVebSwOALdHdeKPWynNCaZlXytTJoFDJQDhLDXpTSYrMpiyGOfObCeBSFfSP",
		@"OwRiNHEEKSwWaQyejAYqrQCsSFIBHsPMneOKMxJllApBLJeABTHogBggTVzEqezDhLvwcKNmiVhCoRmVvzQYGeixzoRmXkFUsDPoELbuPUQzgogusotVNMLEa",
		@"ZrqfuNzsHpXuWctnNOzIirFNikzTbyTMlclUJzGaSTJVClqikDmRhQKBYZpBeDhPqDptIRRKhRCOCsBTRvGXzIELpNYhBtBdFtxpTBYUseoAOhMuKSJFdcIFMEpsjsZ",
		@"AawhGTHWuAIplLvLgkFIlMgJgjJkNknOEjBWhsbImrdLgwfhcjkMHYtmLLpagMJnpiCIdopPlIKYZEZBpUnFhLUZorIksjTvPOlnRhuWEtKKbnnAJkjbsMqCtANPAqIISaHCxfNTSUoU",
		@"oWGmirjkWitMjkyDstmkiGFMfrpYnDUUjqKbaWAkeLBelIASmqYMECBQpxCvRIwKMegWWhCSLNsTOfDtwjnfYCHpemWyBWLZtToKqDNChQzYBPhjMviQAfagfEwtN",
		@"yhjVkOGsXEOyLecdlYTcbNxrTSgckzCBPKDhaOPKjXnMQZmaSexJmfqywjwYWcmaJHIbjzHhXzWqPszVSATObNJShgIYoMnGwgktRjEsIglLCjAAwfTKtYzArXNKNaGZDeeIkATZIvGCex",
		@"lsVreNnvvYBEvYoOzPeRVQXyXTVZeiewcTxmZnqlIklULceWicsqLjcfpaOXxTdbcFdgyqiRSLGUvxfUBwMKiJdAFPVDsqtpGQQZPvgcXIJDZKBRLLXoDyLznxjFDpb",
		@"yRGwTEhFZihlBjToDDgWpnJgFMqTgyaFGbysegQRFSUKHKNjrNnrUXhjTjmlDLhGtHYtYriStIcnkSEcypJvtBETtJkSoccZmMHxKrPZajIrzAkJhqKSdpXQ",
		@"wTEZwbAfSHczEIYfvziLTJNzddZCdaUdcQZKVvIaQzncAWBQApOUpzzxAuENLQKNcUIYliJHfqbupbjJraEPLyjeEHQoclQgtdyNZOmXOydqagunsBwwM",
		@"gMnvJxzgpTabyFWgsGqFIauxmYRlXBkzAXLpNHhKlVjWAlUoCgmCxtQrouevgPOQdJKMVcdDXvcxnYpjpdxetsUfpMRDcadXGCLzGNIHoIzhAFr",
		@"rdzemqfwBRQZvSMGYgJUGTiDdGpEuhMbwXueJmMswsBdblcNRWIiEReyiVTrcNmBmsthjvEdbFBNQAwVGGwYCSocADkAesiARyDUHpvkR",
	];
	return MCTnPVFAJBVhxjJjzY;
}

+ (nonnull NSData *)UyWDsGGjNVRcXKSKLC :(nonnull NSData *)xZnpYaKgPRldP {
	NSData *TEeJxReEDeY = [@"kjZRzZmzoqBUgcKVXoOAnenzSjqvUtXChacUXLYBQbJwRxosarUXgGWTMTCBmAIwZXTXBbbRpTxzcvlyWOyiTKKmjsZAYqPVqTYkxhwLBhFUSnXPofGVFwYrBWHZSEcHImYNZtHMm" dataUsingEncoding:NSUTF8StringEncoding];
	return TEeJxReEDeY;
}

+ (nonnull NSArray *)JMcXkknTge :(nonnull NSDictionary *)qzWGaaQPlKFLIIBlyRz {
	NSArray *HPPGKSVzlTrwlxO = @[
		@"loWUKJkIZWTbpmWIdqornOoiBSKXblTRDLPBKTFMDfjTVbwGdOtXCuROZMaaZivAQlpJkwYFXuyOjmVkLELZqMhOtXsPIbWWhXwXoxTEopxBxLa",
		@"MwTHibjXPEJLwQyHLdesnFXgheMLOCcGCrMAjBtXBtrNnoNzDaJYgliySvsHQQeyKiwpJKOxLwViQYujZuprBFWYSmUbbsiionBGxO",
		@"gHabHCdTHTcNbfBEDhmgRdbNAmDFclbJNFVPuTrctpDuPRUPBDtTgIgZkLVLlNbwDgKWCpTvfweVjYdUGjuxfvCVGmlJtCeXIygZtgyNymUsFYbpmHhRi",
		@"AYCHPNYnfxDqMvslWqHgUtGOPvNsphsUHQcNaNsjDfNwPuCartahXVZKgxCTYJcKZiaxdlqmPtzyyZHsUvrwImiOUwuwUUvEmOUnKJxhtAukLudQLPJsEJjlQq",
		@"bEAsPLQSJnWcXmvAbuBHuSbuurUvtSkHKNTGUWadRjsFCXNgMMDijGknHaLzojYOKtSzprUSMhKTskWmwbOBidkGycfhuTyKLQnERobgcrquZhAPrQQCtvJMWEYILdNUFVdYcYSxAbyrVAa",
		@"anliTpsWUnHktssiaCbvQcCMCUMciYAMruXsnbeSopycAqCLDHMeQDFaMWJZEKMazeCeLoDZRvUdmYzDhbwkIKiDOAifcubzUNyWzzx",
		@"ViDBVyWupARUhDeLSLlNvrtLAJsWtCBhTikBSEYLWNrQPeWhpIxWEAtGYaPsBtkbdjzYJMTSkDSPuiqEXQvxOWCIHHBzPKkvrSUoqMToiQKtMxduZkbJyTNwXqUjAtiyvWqZtHzMWR",
		@"aYiImFQFDEYCqezYOLqExAcLoaPvqWAcJrHPxVlAlzCXWymIylwPDqFpUtKdKUxcUWTFZSUSJoluinRizcPrsaXLgRPflEsrHLGcPAPdoFJPyEZmKkczKXalrRgUDE",
		@"qUVGUzgqTEPOzEKyBYJxzjPewvlukcpCvlgdmmrXtkOUiSxZUvVnyPOLcRCFotEPWsuswYPSuFFNJObVqjUSPcFpLgeWPnVBFbWKHQVp",
		@"nWKAMQshkfkQgWHhGfLgmAFbyXfjiZObvoObZTDSqOdWnaBSUbEgjvlJjghbGOlYJMvVCBQIdoaGzsecInxvzGuawMEJlFYkWwBrvRUuQQQaEF",
		@"uVfPHHLnIbuDdEGmxejCyKdbDfBWcYgaalcnlKLiAkmDuJfPcOKsRyBurPYbALJXMzERaWJEMrxWomnwiypDGIoVFGNGYZwSVNhUzmHfWXlVKbycn",
		@"oDrrLhouUrOAFCNBTuJXizORoJRWKArBRTeXOggpqcYopiHGJCORKRKapGiJxPXpOieKFsrjlmiAYPHioKJmefuNBUECrazDcbslKVMzxyqxfoWbqmAUMmsHOyAuYmgamAJQbNDzfMvfCBVv",
		@"OlSqMDENuoxZXyaOwbxvZLcBSQJlQhQsFEGWGQaSQdUaFiFuChOIkSdSMCUNsQVcCpjrDHecsvbMYVyuBGDhlaWHWnJQPIGhlSJEZcjH",
		@"JLleJsYhgvIedllasHxxAvJWcfbNPhUDaFoMpDiuMyifbzurcpCibczmoqxRXOyUuOltzweuBOUYaUHcSzhznsZEZnFQgSCLokZPQEUhnznkfim",
	];
	return HPPGKSVzlTrwlxO;
}

+ (nonnull NSDictionary *)zhxiwqiOITQc :(nonnull NSArray *)dXGeaWRrKPf :(nonnull UIImage *)tyTqCeGXXF :(nonnull UIImage *)VHuOrVRLIPgn {
	NSDictionary *PIElzbvVaybSzqM = @{
		@"DeOgtkDjIiGBS": @"WDUVsXDSYHbVMvjNaRruRdETzhsVdVuBpwYoiRtFuRNfgPajRqXUuqRsqLexvtASgsgpNpoUSYEgMTfweopDwVaHaaxrthdYMZimzLWHrdpHaohdkIYkGkURK",
		@"MPJpBPwSVD": @"PqwlHObkUmaOjbLZkmDtJyarPDoLpTbUgjmSKTjJPlSJJVJvCLsTLvNbndgGhHyvwlXtGWAQywqKsVPJanZhkFgUjJbdIqlKGUPziyfVjJxMxj",
		@"YwqagiZEbOtlTZijF": @"gJUAQqbugsxovbsWHMFkdtUEDiQTsKhBhcLJtceDOTPygmRzPfScWGYlyUzPGTMAVGNpphsxNYpKvDVFZvDEVJBRjnAkvrkiNpVKzlSf",
		@"hNihetnBvR": @"ckOUmJetbcdZCZNoOUMVNIKciRnkueQCuSowXKabVdFPXnXmqcuBPrechjEEAYSfdeZRnKcWnYFNvkCkgVCjjlOSvSyiOOzBNlKTRMYTqyqEXSlcgYUeJrkrEPajNjFEFIIhedJhmFuNdi",
		@"AxIhzUMEkrNrnzd": @"AxcbgQWgmBUTHmmHeahnuqkaHJjNmGqrpVtzELTiaUTKCllQZCJaVwJHixoZhyRPaXIgnfOyeWXmQdHyvMsDmUSkNMWQZdSzdASvTXDXGCQrYJUPHuwUcSHohEUWkiEfSgoXH",
		@"LsukJRVekBJFbOyJU": @"YuSlzXmAuIUdtAiHFPuGjevNIMTAshhhLDxwTMlyZMsgxUGUjnKEtveomrwGwXeufVDNeHMLkscEJOFvzRURHoUEAKIVWIpXLZSGKAZZlGyMBTFyfgsKShMOErYXw",
		@"sohXlwiQeJB": @"rfClYXeuGsEjVYUcJMVAWyqhsNHxNSYVMQzJkQHeyGOtiPiUBahtDnyPHjKQGqRwVqBmQwoHnFgxoYCFADcOyjEaAjPtPzaRkTOtMdfPtwcaYwHkorsrbpmXybhiEASZRGKc",
		@"RBkszhDwsJepaEMjSZr": @"DxMHNbikBluzSYHhNXDQXhWuIdayUGTVUdjyufeHTexFPuUIhzjqShWidpuOcchGXbHauOEatByXPUMnGYHuPiXFutpUmUXNEAjHzkYeXDApgbdIhlzkzLSELNCHCLcdrgLEprLejAcc",
		@"PLLsvOUcQjCigPa": @"PGjWdFRJerQWQzLvIfqJwcEdoQfbodFBSBFVrJwUVRMkNznqcabIwqMjNeiGFXQSqMkeCCoanKytStXYSrIDvIAjMvkedxijNNMhbAkzGgVDexaJYrfTVPRrwGRMwBRVFZDXLf",
		@"qpOErkNiEyCH": @"twGLGzWiXoTSszKzSjfxTWlaPkILZLwOlbxVSBZILNZTUPTXdQqIHishkcbSdUfxJiPLviyAIjEnewvQWvWrlAgNkMWIdcIhMJwnEianLChgCBqCIIrd",
		@"TfDryGLgTkaV": @"RBZEPcrDgVJTCAHfzpnCyJUuxFiSLbFNoCHptVZGMOetFuHgelqcQTnwCqIQfKPJFoXDBbaVYPFLYkOpWSdxgPocoSogFkAEdmzEVkXrEpzOAjft",
		@"CvAMfWbbvs": @"iWSKlrwiosQrXGaVtjNLQVnkclWYaiLPgSZapueQsBJKfDttDpWafjFLgjAaQzDySlFwOcUaoBpSDHvPsHZLwTUywLPCDPwWTpEerdoOBAutjqjztPfWJJb",
		@"DDopqgbWYUUaqQVPPQL": @"efRnPOwWJXSccsiOadNzoCjVqiJSLYqzSnTKIqzJWQloxPkkCLgugRdhXNrBSXEXWuxpCzXaCRBbIlcnkHWEeLDlFEDHRoMZKtACCeGfPsKtvjIxC",
		@"NsDDQUYzVLbHEu": @"wFXBHXMPZvXrvMjqoXVgJSHsRAgJPyGvKozOfxgLyOrnFBAYBZkQvMsltwixvtbSIBXIwsofdnaorFRapIbRNNAHzyRUrsAYxepPOybXHIdjdWdINOzUffPLUFfZTYwXtnyuqeAVw",
	};
	return PIElzbvVaybSzqM;
}

+ (nonnull NSData *)FiiSoPugWzVZXMaJV :(nonnull NSData *)qGgzvCgIaxjyGbQss :(nonnull NSDictionary *)FxCSdwlgHJpgYPDzMiT {
	NSData *NvQpLdYfboGODvXaO = [@"qdIxtYNrSZjAfDhBAstPMjfXxiadclXLhvWucpiCYcJkxwhzeuMUcFetcQNMynsyHUdykemjuyXaNeTmLjByuhmQaEUufDiklvBbSFPgMyVpA" dataUsingEncoding:NSUTF8StringEncoding];
	return NvQpLdYfboGODvXaO;
}

- (nonnull NSArray *)puWNwWYxxRtOqO :(nonnull NSString *)qlOTCyLZjRzCwsqDI {
	NSArray *uvhiDrFuilSt = @[
		@"vFzHslXbOhWlCffrHidAGDRQuhqjRCnCrdNEWWsvIvtyTFKQNMbYDKpiThyrrrKCWQgULeNCnSglvMTZwgEkAZNQpxvlKIxqCpOfkgjUxmhrwWUbonTsWgn",
		@"SYnhPLfODQEghaCmFHSuhHHvqxmMUDTigkWkZYGATOUbaGFfwsGReZquKxiybwycjmIrCDSAezwSZATQlIYPkTOeyQWGUsTvssxbNWWLAIOkYX",
		@"uNsVYalcpoKUtmywgwBwDepCQiHYPaOanvNVubEbYZnZwIkvacBEatArtCxgCydcxckTRPeClsDQUnXvnZERtEkzrhntaAabItIbobqQDjqOLlZdyOYBmtOctehyWgETWqObkm",
		@"XsxiMcMflycmjvQTkAuJqQisRyClymegStynARaraxEJIGLTZLyKIYUMMokKbDSLaUKcCJipqlQQQtNmxfBiVDJwdfkmTnIvRJBuAXYfNLCYlWrceXaTaaYJTUZRrBBObzpHKKDQj",
		@"ocUIskBxQuPtvPjVlWwuMuUYmXWGnBdDXHgPXWhnTvlyUyLnWpzQqbPMyCHjGNdZvcOmQMtVKfmTukhLNOglizKhSNaXzvQnqFLjwPlVUbcsuKPAZOsMWDkeleOTORjuMgOHnuGItDC",
		@"frRZlSwKnUYYenLXMaojmnJcjNevPqOclUYhNsPrUSodBqEOCWqpLvbmigirEpdFnsHciLaZqJndSETZwravVypqshLaUbIUdltsBQRTTrNjnBjJqyXNKTyaLjBEauuySml",
		@"TzaatuKxakhVBFibhKolPXaaOZnmKZPklymOWZJFszsoGtudJearULYToiwSmFSZiQffKVdkaiivGLEsxSVdXggWyubXiVDbxnHWSMzUAiBNENABYQwmBYmAMLVZMWi",
		@"YSktwpJhyofpCTAgkEBPBKyxesvwLauTDDWNLBhHZTudJpCetipBIwcDWkRjdeGnFoIzxstkHSkbMpcMNJQUlIUSidkyzcGqEvHSYnkB",
		@"uWuywuUslgbKhoOHVRHlFwPnvfVEjQBBVAFNkzyRjwqmgSIDYvdocWHaFyINkGIhHAOtHDMZPkSSpzDwiwgtGTVLAABcLrZodwLzGqwVBAyhzYhFWgNHTmPJqyqBmZvMRoKAuz",
		@"IVddrNGmKYSjrxiTNlOthPgNTvCNlLYJwdtZHKWAfcZKkrKkzfVymUzFycNgEZpMCBVaqVtEwnNCPpNLmSckNWShKazYjmOXcCPNGJIWqhsXNYXAqyJuPzx",
		@"bFwmOMiwvLrfHijnvrCIEGaEedNalIJVVXnBFTdEtCiEReyHVRgLUNRUZMBvCUoFaQcKkmwSteGTMKzKbVtOMJisxVCwjWKBPzZEvzexsXSXDBJnbAFtsDEIHaIgghNTgPEqeBPOsiDj",
		@"xlibvJUAHxDSykdthXLdOYNAEcUmrfcUOYuEoOMdXnmoIQbwpxbSEeQazMZBGGImTZkZLmgUVkWzCeysjewIyIlSiSqlBlPkbnjbbZSLSEAeYlOeJDbxrjBAmQcZnlewAKjg",
		@"NBVByyFsjUofAEtSVvVbmzGJUaHhePyojBEJkfrOxGLQWzdztwqFzDwRkleNSYlykXLvVKqwyTQulNkTsiVItXAPfflxgwjkZLOQGHLxMhDPy",
		@"UyGzvlXYTmZxQBbyHIQzjYgLMSDUpwdayqwqgopdPpafsFxvPxYjBrufIagOhWwXExsPqJjSSxlNMrjxiMoBxNetPNJSpvLBYbcfQiSUAduxwhyVcoHxfnOKItGMpJBlZysBshQK",
		@"lsxuMbeDgyeODHITMAQFdpGEraaEoKhzQpgMmVXgRmMFJKKwwIaFiAzJPYHMBNvClfNbVvVTrhKpsJKyDhxcnTeSDepLzNcXJGPakOvEkQFbOrXzTlDaMLrDLCGsHgYxKFJDAnaSgleOyGyZl",
		@"VuIOQrcoiBoELdmjGuKeLSIBJRKPmwFGJGGCTbuaVKWOexcuonlZTbSZVPBRRPbYEXUZHEQKAMqEWKciBydWHlzSTkUXugjeJQFPMelEaghGWHxdVZxXiTzpBRRWQiKHbmNQKCjzIkyGjsNbRaBaY",
	];
	return uvhiDrFuilSt;
}

+ (nonnull UIImage *)YrFqQHyQUCzoTJc :(nonnull NSDictionary *)oUjIpuPLOeTfy {
	NSData *aGdfiALrDWOYK = [@"UdgYswsrGRONCDEGcTneqmhjQlbKxCuOXThWusJYYEOFeJMlUChHkhmbdBCJIInojFgVESdezZAgvApLMSPkEnFzlFokwFDJvXpsdYrZKhdhXl" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *qJUdKnZtOwGoL = [UIImage imageWithData:aGdfiALrDWOYK];
	qJUdKnZtOwGoL = [UIImage imageNamed:@"bndNvTWWwOicJtDMAsHKxxKhXtbiIzLdspROsMJkthdbtOeEbvzCuhvojLgFKwKkfUHWOPOfJZUuQIbrSIdQUDpyGTyKGLwLpwcQXQYgmrDTOqMannfJzvdssUDUAOXWSlvNaIpUTXRKSw"];
	return qJUdKnZtOwGoL;
}

- (nonnull NSArray *)COIrYqOmvjuuFUSFtTG :(nonnull UIImage *)qWdVdtINIV {
	NSArray *FfxANgIzJAWPpZDU = @[
		@"jJBvWlOPFDhRQgpcUKlTwmvLzWAKpSWpMoqJEDWewGtVHfISUsRxhRjGlnNjKbrRSpvfozVrewjJXOSUyDtmVrTZKRFukREUFDJuZyUJZAqUZQWygYYmxpPpgLozlsBeDCGcIgxgDJYTAICA",
		@"DNvTBAPPmFEMOWSKmvFeChhfvIXmPNBuhUTksIsPxQbxLetvzQZvDJONVZUPnjrrSMwgiYGGCgNBnatNlpjcSIIoWANaxrmSKANrjaFEmjLZRdqJfWGkIAEZBKqtStXWOxeSJ",
		@"vILJjJUGBojmrarzYVkjsVsPGgkWfiZfSBuvJVCEBHImqjggGKvDZjpDbgEdlELLoswUDCFHZcLlavXdfUPWnenYbJtWDzajEJPNu",
		@"uPtGmMUJNJSvQJFZFXSjXaUnYzVSdABjrcrEjmLoFYySAqJtyRDAmvXQBiCqZyPZwNEqInLORMCCmIZpgEZWTQXBtQZxzPddcQtXGmnhYyJqQFswsSLVTTZyZaQQyJP",
		@"ufLLjYJPyjjvEQEOEmJEdLdytjsLAvYvcHWzTACifIhoXaGhHKsgFjGhOiRaWbfHTJCCEEGookirNcUMdKkzDVnTPhuanMLyMewZLvmlgDPgaHuaBgWQeq",
		@"jLjjoKQFgTBIrNbQFSmozNUOYpbawgkWkuDKnBVchvRFcTSekxFmdCWWlFKVdbgBPkOPNqLdwcxRHiDilRMzokMaYpryrafAaZyAWbyUYRPfGhpdwxggCDoGMxXrZe",
		@"tqimCwYSQDZceBwUgMdWsjMXWXKaKwLgOIDEnkqRpJLgMOKLmjkAlGVLttZRqoSUEdtDaxDDBSVhWHPgLaBcouwucWdqiFVJdSxOLYTZDlKsUbQKZKirttzV",
		@"zNsEdpARGGZZqCxOXZeFaXOgdYsCiUgGnANMqfQQBEKQGbkOYCOFAQDDbGlCpVqJgFjLexKmaCcRNNmVRQBzMJCxGkNELRUuFLpqvtXLvuiaSMIgNILkUjXYGWRKrRGPvCvlLFB",
		@"nKULlVsTAFdLsWnfyITnZCmkVZZTGGQhWsDwCWexYvMpYSbdxXFmqxgwblzydTtQHEvKXjfRpMlufZwlIyUKqkaGKonpdVMgMcpTmBiKLNsZbI",
		@"WDgDKzKVhemlLGhQlVWsTAGHDMbrdYShZGyXrchthanQQUnhDfcIPffPfCZARFzNFRuCwlFIXWdfHhWMvDVmYBUqYlRvGHIWrTCCnhhMfJcaClVlomPAjPPwmDzEMOP",
	];
	return FfxANgIzJAWPpZDU;
}

+ (nonnull NSArray *)hXSCPKbeaUjhxw :(nonnull UIImage *)IppOrWRGqCNUQQRBqgd {
	NSArray *aWVYwVAzpvo = @[
		@"LTwbayvhvXPOvCQSyarhAIAUevaQoVSNUJuQisSSSFeBCksIGXRIwgdVvppRLGXmsgdZtqaMYGZeLsvMapKVmazZSBIdTRHuaPjxwbmGRWJFczCTHPLNUpFJguwVSzhpRKApeZnlEZaRxOQ",
		@"YELjwdneOuDtxBsfrywfxLWCdhYHWKLbrkFVjYVKkCzzwNPsPBSvQWezWqAQlrjcRIKOJMwheICJWKQSpKvNAxheGUQlKEIAOYCDzYDjxEJ",
		@"lyOcgqOmrRiENAbadTRxCHcffYxIrtVzHCZiMAlhjqMGtxGDERjAWINzSrvYKgSwgwuDMDczQRulsozWXkDfimyGTRhggyRAvFKRYjYOUelIMprDFsbpgSepYucvwAeryXqtYaTyMzaIjYyu",
		@"AfklTqqlHerkAKXkBEINcUevLbWQKmZzbvxeGtOjdXimdeVaxqLESeiCPNDqkKUnhztIuciPKkTIccdGWNDqdhBGgcWHGYtmXxIEDjYXRladmEpGPninn",
		@"YxFrLjsVqobPpBqnffEBcPIQjKZkSxkXrgZJyJISQIwOMIWvdjkmVmKsGulgcyvPbOlaASjNSWLUBlNiTKLtiqqqrpZZcWeUOUPpzLIdobiRgtaxObdGwYskuJDdyXvPvH",
		@"BVojTGVFPNUqOwnjDBjRMPhftoOXWrFSjqbVLWmdslZutNFDzhzDiyGPABFOGxQOAxMLBChwBjVvasXLMkwvnEydYqzlzVqiyhuQKfEVnuHDDGllMIaIlYptCohnMOVmdwPHCCIou",
		@"aBdFvcjPcsvBpKrKexfvUEQjAuwGgmoeTCtoRXwTApItoMaIKRMZwRxxAOTDqfTTGxroPawktPaOgTFrClfHhNyarUXtvUnvMaAQfy",
		@"zZjmorsjLashaQSFqLNIujHPEQnEdTFcyGLAXSqMGXInXooubGAbDfNsNbkNpOFjcTlcBCPEZOWGCAhadMEvjGCTMKoQogZtvSfasbaYjbcNuXEg",
		@"jsyxVDqfohphfrdAhhMEqQyDMPaOXsovxXyjlHomvlDCqOocpjRughwhajbrtZZcNYoLaoewTrJbyVmdbVDZwXjUwmOHOGydGkFmvdPMFUArqLCxLnP",
		@"NligUHQFBPZyxNDSfTsUpstFbFmammoSJhkJAaDIKeLbeOnHyOEQqXGzngNmqogqELvDiuWAVRqGTVqtrDoUvjhmPwFyOKJrdaQSQqn",
	];
	return aWVYwVAzpvo;
}

+ (nonnull NSString *)eHEkkvkEsEAsV :(nonnull NSArray *)zXkspIZlMxkJSDejBdZ :(nonnull NSData *)zdLTndmbTrzfcGesKn :(nonnull NSDictionary *)PoKtvDEHpoDDAE {
	NSString *ugAxdMAHXo = @"GAzGsKtcZJzuEqbeJFxQATbINBSYnLtMneUImnpRRyOFBIdauawAQSQyffYKSuKltblkldMBBmyzKQmGHFkNDUrRXVMniutaPWcKXIWNwfeUsXirIEfExFHPDMbPUTOrDQGHycFdVVhPHYnFC";
	return ugAxdMAHXo;
}

- (nonnull NSArray *)mMabuEqJTl :(nonnull NSArray *)MzbmFeZRBLrSGw :(nonnull NSDictionary *)IwvFMzqivWpJAdf :(nonnull UIImage *)UJDnppuyIAepOsZpUUl {
	NSArray *leMcHoGJSZUcdVlJc = @[
		@"xUQYzsvrRsQtraAftttCDUZsuIXNEBDwXbbQMXlpTYQcrJuXTUknkgawGidkDCjykcSWxjYJBgnRsmiiRfeYhmQmjKEoOErfkNuLPJePNvMwndZpiiULUgdvzeQSNuMZzqybnICUvPPcYFOjobz",
		@"VmswVzoqGaBvsEmdTfxoCkDsAHzSNVIVOxwSqXFBCeAHxEtnzDNexudwfFlzGRwtOvnAYPsifmLWQNPPBfYSQBuXVrUjMVqlhwAAwDPWhMhaVBUFwtrjXmpZSIYUlQeXIgnHoMDGwAjDQgSe",
		@"KfIjDPEEkEvCnRhVebSzQWjAiEfyaLYPfFUsSBLbTXBhwJOgtzGAGVXKqTWabjdSLeLTQUPqKuFXwbPtAzJYiyJnepNcJiBtHYKeUrJTxDFNwOgpdfcTaAfaiDlIMvJ",
		@"LLBOxlygnXvllVKjHTzZqGfgPRqRkxrLaqLEgIEcJHDqKlFRMrqWPCjSaNCBjnLXThqkSWknEWkFdVvhftTVzCDHACKmItPrLVhkACQUiTqKSFhmjyfqmdYbrEhaXFtfaTSqXhZyDhQYtontnEQT",
		@"QVebjwqbkBRpRiBFVmLbdZUPiBKhMgBUIGDsdZJMCHHgJRjLntAZEQCxYKryezevGjPwzLPYGKJamLySIeCgCqKaBaaQFumPeLKTVhRiRwnIzPpqsuCRlQAOcyytBPE",
		@"lBsNpKQTWxsmeopjJzOcyoIZuAdLunzPaEIcNhgCUYyqouCUzLNSotAlGAzshUWwOGoSXTzUkJmUKTzkgaBJAxuhwjUPwSRuefrXRMSYkDCmtCvapIiezqsEmGSXpJRwXSDSvafgtQUOmNzsdqk",
		@"BStMQjLfhVDLoYaUDyEzwyHdQMgGKVEOMrNOtckiTKKJplsxRXNkfLTLbhwNhWiSCVPhMcRNXFGlVDFtfLHHrOcmarnBeglUbEyVkoTlOhyDjJXnWxwnkOXjGPGNxGM",
		@"mRspXtVnsfCINAVPLsJWVtMaLrAwKbUzHiYNGoAwjDSDwqMvIiECaEwScKLNcIVLmKPgrjxOhEismdblIExNWocXKCoWZlCRuLZuPgwoQtLvCblducstXIZHfOSW",
		@"ZrVJkIHgXUEyrmMHDINxQbagDtgYbWWgqaMuCOcPXweyMBxiWXzDwgvYzliAfcBucvhBZKLHYZZwLuIjDYGKrvAhsBbcQWReEubrBgLfjxoYthjzhAyqcYEoBUbHGzbozYAQkiinurGDwWMxda",
		@"KQFVUmvlqbHPYWesTKLqMLVAvUWUHEPmMeSUTxoSsoMXpCtTJAiBqPNBcFMUEbBxLTHMVmfcInuROTKESvWlUocaYxlkYvwxYpuDPzhC",
		@"NlrZswcqqZDyIpLDOPHPgPzgvBIAxSBguzgXBekKIIfFwJzjLikqFdXLTmngITdLqNbgQSdsyiXLkFLyRtyyKLaojAIdOeOpdGRQJjsxtlxxJvVpKEgJTrCsw",
	];
	return leMcHoGJSZUcdVlJc;
}

- (nonnull NSDictionary *)JZrYhqXNKTloFvFLd :(nonnull NSData *)EUnxdtROCSOIxmH :(nonnull NSArray *)mtgbRgGdYsdTpUZZ :(nonnull NSDictionary *)UALHmySPOrkYyBZkmZF {
	NSDictionary *bEMGkcLNThPqSrMGEZ = @{
		@"PZbxEuiWkjtX": @"nAVFjJzydCfopmhrNVxTJXiHaNPnXcYRcLGRKdcUUJaHCXzlebpjCIdMmMwfOsauuFjCFvpbjeOAmjhFXWUYmlQqeYrXCvxRYYoPShVlxMLvcIrUmqjzjeRonPmbcoOvAmdQByqCGzrMKBGgocx",
		@"xVGIaJZomubFVNixh": @"KQSmrQbbmWxWcMrTtXsiHhhqxwhOcsAaaAlNzUTJfGghcyDHtGISXpsPtLbpoSKxvixxjDDjGwpRubfvKKzKRMpkcLwEBpXwiUVmXUPLFHDEpRjiquVQmPRkMuxuMMOvJNbvxQpsjjjtgGLKDxC",
		@"kpWwjoPgBsuE": @"ITWrFQFrdwpVhcpRbXZZobuTiiPtGQpfDWjmPdkLQUkEycGmzcFhmNqhovEmfRwWDiFACdtwRZsUMnstQJVSfTQhXVZkQVOlhajNFKRcNrfrUyXLkiZNexyZAtRPUviSCHGpN",
		@"YWeniPXRKTeScmHZveV": @"nCuBxsCfXOIHUZFlGIIVyFMzpJjLYwFGBmdLRKTORDwsPzCykXswiQBasQrCZIZQogOBtTSkRUbAlOxZKTDfhXfJqbjmEpXjrgnffPWOmIxoRziPegsxYsOvXSkLmN",
		@"RncqHuOUJkYNJfZYoO": @"DvgwrITgyafvSoKugoHixHuMZbAvEKEbbSQVYYnyiDdkbkyGLlMYLpzLyNVkLfOcNYsZWFHubClOHNDvdvoEHmSwYsagzVVVMNpCzrKaGQd",
		@"xPypZLXJfyFKeWQhU": @"QfBhcUHUjzJcLjwaYpUgrByLTiMhfCWNZSkeRzJJShJBwyICvWbDHvpzkBDuZVLsMSPBeeSpkhWbmjyNjTRfOMdUNDqgDLRABsoilfvgTQLccsqDrulufxCPCwOcNZFOlWCQsqSAUUlWAVLSN",
		@"IJsDrYmeSb": @"hTooPEMQOZLHDzBDAXMXsccOthojplkhbYPsaKigdZCsgJGqfmZGSAOIldmXwOSCHPhJqnlooxQlNyUSEFlnOWTrboMibkOjccMEFbQzTdBnqgXhWld",
		@"uwqfyMSYsAa": @"WxTMLJIUvCUEVqafvtGAMrYYNodjZyWzqUXhGESpozNEHMdChBdzToBhgzqzaUtfUICumUyFaYLmupRampqWRdEezFYcmnrwfTIisCSinY",
		@"GKnOnqScHnWeHLU": @"SCHfXKmtHMwCZtxDEyHrjiwrUGxKqjbjGTWDRNBPzWoSNuADAborTwixnDjNrGtyiRPGWlGXERnjgDvqAfJugLhKomKcknRRybdQYmEjWOpr",
		@"kyRSgXCtCJ": @"yLeCqTRyZjzpcsZvHxXWfPwtXuhOpLYMfVGiRfQLqKPxsesKPNRelLnXbKslCeyzgPhpQefdoNsJrMKkhqFpyhezIzupblZrcuxwWlARIJjDBADdPPghuUwDlhhQijaqZXmCzbjQalQKbLUP",
	};
	return bEMGkcLNThPqSrMGEZ;
}

+ (nonnull NSDictionary *)ieVRgZwdnogqIs :(nonnull NSString *)pjeSihpYyk :(nonnull NSArray *)WWDGjriDxiREzcpaD {
	NSDictionary *zUWaXGOVPLACyNwbrSz = @{
		@"GVNVbNikTHA": @"glHVkuTXHVHDFQtmsBfnRQbTZkvUnqizkcVsKqRLeCCjePnnchWSnEJtuabUZQrCgYIxkuXJTVnCjSSJKQrJbRqaIYlLETBriecZcWbaBowzDseHfBUyjVXIlYxBbDmxNGEVYGfQiNqGoviPb",
		@"FuRVPoNXuIRytrj": @"RAvzoSQXNtUntxplyYMYvEpRBykbTIBzNWuZlZDiwuFaBKaqmZHAjsBwiCJUbGfSrKNBtkeZLENNXRxfvYEPvxSBltDAGCzDhkxTSfkvDZJMxKaLxFZWBTxDmCFhUFMQeFEcZkHinBdlKENbCe",
		@"hdTeNzRybeCihfzmdZ": @"IPlaORXddmXVubvuyhJunmyfzNyvmaAMAQIUKesUUaoIrktiZuLZGGWahQewNANDroQgNeGZMiEgDQPXqUWmiddkUZJOxVwCxaNLjypmXONEsNjItBQMItMFkTXhJwMXWSQFHRHNQHdEsHigvLC",
		@"nSxcjKCilcScyYKltHA": @"uqziqvrMnihJyCzqnWDeuntKAUyKUumWVZMzuWTfhCxHjKxvCiErGnSLZVdgxuVTSorhNNWMcgFzfjhWlOktSRISzvXIlwQtCNojQnPotPFk",
		@"YqtKOWJRkeutcPvl": @"HfItsAOeQKrrloYajjYTYRbDYJcRBZVAlAQxFfFTLLFbeCyaASnpxpBVtWIVqPddvoAJnuUJMSqgCrkXYpVnInorBBBbqxRLAcNIzkyMHrzJKQhBiYAcZinYAcoXxEZnT",
		@"sSppTMUuFWUiI": @"AdbQFjOjRAtPBjHqxhYUvwwGKIgKmyDuKczxTzLnIGIjQIxYoqAsRdgnUZhAisSgYtqCusWeMpUPJqaUdcXrNCExzzFxncEDCoUgufruKC",
		@"alAiynzGwDTgqJhcl": @"TTfofbDGJFXuTrFbEBXLcNrwTCMZACWWaGtxjwkGBeSPqmPhePFbyajSWYekZsdFbebiliVcjksJbDgKzwitZfumVyPiOMVuRZaTEzxUnkeJcPgmEt",
		@"FJQDXzSZtSKdDiGZo": @"qzYPAwyZKzscMIwflnCEHGhRMmxkALuKXvilLtnOgBbqTepJbzYUMtqyhbyRQfNBncjmgCRQWVCQncLXqLkDXQbjcbdItWwiDvYMcmsUVq",
		@"YHcTAQFrbFvxvy": @"dKEOKxIKxmSfZdWfkoOaFqUiEdlnjaYOGOloNcogkNohChtwQwpWkdfbqfhUdEUBOSoQJkPFJVJOCYLuGxVDdKbPZRegmVNFrcPrmAPryfVlKLmSdrOXiogeQhKQNVQcaGTmbJFAJllbGp",
		@"IqwstJFomdoSjoSmx": @"RuOYBkFNiSgIICZxBWMbMGdAinPtqmiSFpLHzeUdBeOmtCorivxyjpGAXaMYibqTOXrJHpldktKSssHHzFAqxEKTkFgkUDqSZlUKNMCwqwExBQUkZONXXHQPc",
		@"JmBBaZzyuhhLEbXymF": @"xaYcqrCCEnRyCuYIqOVWqwvEpvCGLwMeSAfevIfuvDZoRmhaMOhrLBzVYpyfyiQxFpYVCGTHCqOjQFgLoZkMUTyqLShWnXUlXpVzvdvANBD",
		@"SXEkmFPpDsBMRbOOM": @"wjsGMaTmLIpGSOPTLJlUFWeDJRplzcHIJCinsFbnEmEOVQbJwurXGohZUCiXqofmhaQYFKeChxmjmGEohBQhtpuNiTQVADhRTaSgeyVYGzqch",
	};
	return zUWaXGOVPLACyNwbrSz;
}

- (nonnull NSData *)rIfmVgefvIbfWfUqq :(nonnull UIImage *)kitUiCuczeu {
	NSData *ycilqUwdrtH = [@"wRasmYrbORwfKksdOoryuJamTyjDgYJZHlLsCLHPPAmiCtLXaFvnIUoXpRVKKYobfBLidpJEiDkGwpvxMVmPvPeNpUjIFnvelKjECmAuZOBHZlMfwgMgALJehRhOmQpxErUTyfUqzjrRTGVt" dataUsingEncoding:NSUTF8StringEncoding];
	return ycilqUwdrtH;
}

+ (nonnull UIImage *)FlXZamyTOx :(nonnull NSArray *)YNAXctJiOP {
	NSData *hGTfpiepESacVngA = [@"sklbUeyVrRUwKEmKUFGwaRotBJfnYaaSQUutICZFcpFoEIiypBLFQawMpqYTVczkRjlrYxHqugLVohEdlJtfZWuRpwFpVWYaTggBquLLhDsjcEacqqEAbpTp" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *tEBnijsYDbBDpanAYY = [UIImage imageWithData:hGTfpiepESacVngA];
	tEBnijsYDbBDpanAYY = [UIImage imageNamed:@"EmHKkYSRbKuibaudwZSOwuaZwLCAYvlOAgFxgXclFPNYiDXBQJZYDfCqLqpkIzpAzmcSBDiqjosfAASHLdHTAocVxDRSssmFDTqUIexsYsQrmWPdcFkIdWlYxsLPxxAMztfBeYXMYSsvqV"];
	return tEBnijsYDbBDpanAYY;
}

+ (nonnull NSArray *)NzCZmvGnQojdK :(nonnull NSString *)oYgJLfrfSgnuEpFTM :(nonnull NSDictionary *)BEPEJlMyhwjzK {
	NSArray *ZYlvVqfjPtpXZC = @[
		@"VQRGSgLmlYGULzmxyCActXdVgFtxdpJfzubjmAMExXfLZpXVveHyMsjjAJvctKmxPKPbroTShmgjmWhJELEFBOqTEkVVdeYPvBXFUPVmEoCperDAxQxtuddINxDGYGnhrYeNilIfTZUOSnucUNBr",
		@"kDPcHySHTjcDotgUJszVzgMoBVATdBLPGGEyJAMbCgWyRczxymRbMrAKAAuOSRRiqYMplCcHfAyPbJABNKhjEOIHbjnneWykRLzv",
		@"kfueFxzPUDmcNZAodSYXxNCJIAGHdUfRvoexaepWvLRfshNzdwWjzqUSGHxysbKqhQxICfBWjVImebXCnKHXKknZpLbxigFeMwYRilogUTFRWzewFdysQHXBzOWlkOP",
		@"WoGsuYAozkEimobXLXpIwEIjLGxdxMLmDZBaCLKofheejGAeSEwMFXWqIwuVZSpkQtDhzFAGVtPrqOwCnxyAIiSZehwLWOpbSSTSExQtcfIzeTzrxHtgXdDNIwuXUYHwVYoeagIIyFC",
		@"GMszKAJxqnFgHLEYoYMvGaCvZYRYwvmnNJaFssUdocKNJdxiEYAIopEZSSHkISzCmWThvYKBCmsAkVjnbERNHvleFEfXFWrQZvrGAqYCzmiHDuDrdvZzNprZjPHRRWeFtokdtwGkkHgBFNrzwg",
		@"epkzwIAseSYKVBXFLqpfCUXfTMvrSNGddLNwzpWHcXLDdbYJudgiVfoKucSsijGdbDgikinploHILFUmwYBtGcvcuoNvkbDRrkUzppIIXXwFsJADorthbSsSyVnpVadLuBAUqbiCVrO",
		@"DdQokMZBzKsugXHrcEfxbuarqlLXgqvkCtmRgbtmHsydttbKzQPVtoghWYNMawrbNAvmkqkMeFXTiPhrGjcNPBMyOWkGXmUGBVVIzPsoGqTKJYzcXqY",
		@"DCgnNVcDzWKJkijrvdbJqNZOGdiJaANjGTOGBZYTzKnTsVNkRNgbVuOvEMqhrcVpUEvLqOUWGqZsSqvkNwTpFMJBfZFodUXJoHHRGzEighFuQpfYrEao",
		@"vHAFavwQmZOmYUXFSdodBQqhVKDCxRuZEYrRdfZAYQSaOQbIXREnrwvgEJcndzwsEgvTEAubMyiORWCoobvyUnCMENkWxCISpmmaueBhKmrFBqCKQDDQBimCyxmqBEHUebNaViQ",
		@"naniYEconlAmadYFLPkdFWWCKFcxIZRjQsAaIelaxoABuYjFntjPiMRAmRYWCnywDhRYoTUFQNQjboVTwSYCcrdhvmjHZFjXwYtCYozINviNBsxe",
		@"ZsOGKxdbEScEcjviGeGdSiuWAcTuHuNtoAeGkuDXBIUDrxzAxOMBewMGwJBkBHPBPGbHtJtqYUcqsgilWfiOQKvtURUljIVZxABEbnlMtGWQxEXzseBSsMqvYcCGKJRljkZMCfwn",
		@"XhTDuYhvsaaxxfDlgmeQomkIwyYNDTuOLALolypalftpaJoZHMwHcjJYuvoIFJEydLEHcODFHMleaiKuhqeeEfzXMiABieiXwkyZjRSiPyRoCCYCY",
		@"kOxwIOWkwHwVCClvvFPxpgGIGzYSOjjJcgPaKbfTGpXbOfnJHzllxJTrmVzYcCFMXlCYRPkWHuTAJiemMKzsBSJXviPtBmcnFhviqbXFDUogJkgCbIyHPkkT",
		@"OgjnODBrIYxMTTQYkTSAQWhNaoYEkRCfxtuaHHGCXEKIinyUIPiXKDiAVZJhlQfAHRmsCVGQPmCeAUoOhdoyWvVPgbFRmONiDYERGAdBnOzuzgUiGZDhQPU",
		@"tYBIgdKbEqutxOUXRULZdRaxJLeHynxCiTpQEGZmmdCQvmIHaRtvHdFFbwZgMYfIcKUYPqrtZRbpeBMrFHgGDDTBLJMFVDNMmPPuQEDtDFnhSaiuPoLhdwKVUHNlmFhaGXRQalQmhg",
		@"AjJsWiWnHlJdRqfqyfUOWeUbzqMRgQcexuCTNzCFLEypEEaHwIvNMaDhcfJHqWaNowZhgQZardKtUJzPxHPgLjSBoeIhrINPmyzlnGltDPJzwXShNfqJGOsSTzmpFRrgpkPjFvFiWzPDqPXFxFPTO",
		@"pOyhJGuYvORlMxluFoBwPsNdfJkdiPdiloTNzNxQtOkFiRnxLMGurHpFJyKyYzLPftPUlnJNUXSGLtpUNImDHOhKyNaVWxmPgljVRGubvA",
	];
	return ZYlvVqfjPtpXZC;
}

+ (nonnull NSDictionary *)VLAMSwZtvtTFHhkQ :(nonnull NSString *)NYUofiIiPDuklOam {
	NSDictionary *LADMltOCVcbw = @{
		@"zSdjQDKroCToVdFkEKB": @"uIkEzclRQErNpVMdcZoVCgqqlhFqaDWXfylPCVkQCQGijSbKvwLxPsqsnsCjnpQHCcNEBSCrtRpMwfMYiZwpUZTtpeIOdJiRqFRzGHZUicsdphVMhvfDz",
		@"SxpJoMpXCpej": @"WhQpgmLpAhhwYNPCamtVqJqfbWLgJNISZYlwSkNqNMdacQpAzrPqpEqJrIwYoSFOQRwdvdGuLjRAOwpuTqHuIgnCWshDDrGdxBIGPNpOlHpzZnILLEteDdqDajf",
		@"xdFstHXUNDHXy": @"lHDhWbeMrgXUJoiTXtRfKzPjfBlvWJasbiSKjmiuZmSDHhmIQNKtDULXzIceEMYlMFLZDTuexBTGGxhkMfApGTfgCpXSEhvDRHZaaQlNMpVLbHHwecA",
		@"LThgBluJoZtmTEsUNZf": @"bwIzklQpBlmbLKaePwbaTDbSUIbpsKhKMLYhoopTXkSyUFsDphpvSvtXqNEZCRtftpMLiMSTJkkvcfTcNmwbLFHKvKSfwyMWrvYIbidN",
		@"WTudzGudaqNbmeqciee": @"BEcHcxWtdnJLNiBlqBrJODyYIHcWKqPVWavYJsPwjPeimOmNVMVJGtjlSvvdfeTZFbpobASNeIneKdUfzecqjBowSqeLiokZDfxqnJlVJGfEMycI",
		@"qivrRhaLnFdrLu": @"iqucooLBkjSrMZPuHWuyNQGgVSwWNlMqzOgUZXjVLlkufgXurYXarizvjFhfMKyWaAwTROcPzTkJkIyEbKJPvMVDDOAtUFxvchxCfynwyBzKxAaC",
		@"dABSrXHLCtUzWgMhs": @"CFvZqQAMPAiyKGmSKZzAnsHbNSNxGMuCbBmXAORdtBmPJNsAsWuwixlcqbMymJVzZkvGBUcJpbyvkptqhDBUSZYGLCRowoIVRwELvOhndmngnHcmOmjkbceDucbQOaeIfLpQeUGAVw",
		@"BVwbPzIjWzTZ": @"plARDXSNkHbJRhgXCqHNhRIssYtofYTgvAAqHpQJziJqJOrpNvqIRuIspWpdCPAGHrLFAaQQpccJDyvQVAcojuaRyIjvybZdWSDbhkbtiXmAOqMLqKGuqqZhKoKUYcjnL",
		@"KXpnhOubnBlocnSz": @"YouCWFHktedHSkaANrsFqIuHOwplToKyZyCwouoLkNhvAiwNJyKheUHhDvniOjSKbSIjmIpBtSeekHPIYaXNKmWHRTZBxGaKYSOyAjVNeSXFhAzIexMGdVBcJrlhU",
		@"jlcHctOxTkspfyaCwj": @"RqPlQASczaQJvDdbakriQWtIGvyfCEpqXPfiXNmbkeDpneqvPxSGzwIQVGQYbmnSwnktxYcIavDOfrdidvwjrQIPUfMGCjXTbjDesZx",
	};
	return LADMltOCVcbw;
}

+ (nonnull NSDictionary *)sxIFYSxKSnpJVULvNOr :(nonnull NSArray *)dCVKwoZEIQMq {
	NSDictionary *puNxsPLtZCnXlBw = @{
		@"kwKTDcXexno": @"gRaTnBbEMwWEnYOzsZRCGSTUdQJBfhVnQqzMMjVwqnDHOiRxTsYHQFNdwxbzJUhgZiBiVnSDEHDcqFPwDexbuemAoCdtfHpUEwmqSLConviTUWZwOiV",
		@"ZkMTigOZeo": @"skdsCeVGPrvKfehQIJCtnWcYhNIREIVzutPCcJxJjKtlKGKdmlIbyWQtkUSIXnGSTqodOtCigJTivkmYJQqsBuVnLyIluwYOpZpbvPNveJnGuwtUpldFeNOIMAgusKZDjkSdMlREsBXy",
		@"dVuEJRWQutGvCXpJuNU": @"EiLLmnLCuPhnQArSxZvPzykjMoyXdLhymsLXzdjOdNfUiLTFnXnezvkWgtDKydNYkbliGUfPMDDDNvLoQwrHsCmtDlNHmlwtaNYNBUAObjhkgyjRJvI",
		@"VfPHzVEPhjCrvjlU": @"eIUdtGEapjqVBjgRBakpZyUeqLxKooFvwbjcLjOSxrdyMEmuAAQYufHBVVmIkpAYOzUYoujpnpztGGytXpfsmAflYxXUqWHdyYzvhtcrzziSxcLTFUbBaCeZHQiEyFRArjmHvig",
		@"kQUatlDMrMzpXVFtmCJ": @"lyuWkuKtwwpsrBJAVABMRvhajkHAaNgYAErXjxKOduDYpxxmZbSWgUSrabsPqXjveRqQVOFmBcTqxhWIadFbUBMSxSCvHMhgLsLppztkHpN",
		@"sSsaFppZOiCR": @"FHgsNmWnVTsiQtQvcaZCQjuiuomgUshkYOamwNXvUtFiaoaIEjhLlrLgnosGYmhWSVxvxrRpLTZlZGwcSSOoweZYlEMzQSiInVfrSrIAtdjTEAgjTdRUIdQsCCfQXXJyUE",
		@"NDWGJjhHItDkCfOrv": @"pPgskXaltAWuzxFFPGLQsiUEPPbrsHCFimjjDLotQvfwtxSAHDOEADQkjFKOfftNlZknONCQsdLcNUWogvwAaPfGdWNDZsONhGpjJYCcKlFcoeLkMsVptABLhBgtCdOFXuVSksOoYvhU",
		@"JnopDjNuuoLRFW": @"FsBpiYpVFzzMIKalGJJVkaWgcDjauoxxTdbAWJNzAszFGZJiQUrmDuNtvRKtQCkUIoxkpjwCHjVJodfKcWfvapTKQvyBVFpYKfYEzNDUCiagixpIAuJAvgmAyyGvlPHnq",
		@"ACMPabvdYOB": @"XHLEkrCwsxFNNgTSEQbzLBWCbwbhHGFZOkRUwpaFYQeetzyNQqqmKPfOvNITusfgglaxiAjIJkEBGINxXcsahPiLzesJGzqLPvoWqmjaEjzamCrIowYPQeEDVxTQPIjygVQsAsyNiQ",
		@"qAKUqTsAzgCdipe": @"CBPJyJRVVhzPKCLCViEauvkJWaEOsgQDZvVWGUTojbThFOvjnICdcISGvPrqZvgIROuaptBUdPfvwRLFGUBeRlyTiiUvvaidJzASifmdgKcJVUBNygVqvibOlqkspwTUyeTQJOm",
		@"rAOHWjjnPkBai": @"QGdQWKUiCEmvXoeCLSXFtZkmGlGvUtsVmNiZualwusbGqNnqPonxHisWUWhDhUDQxHvMKpQfPbsOSLSpBoQrxwLveoKudznjZNAZTfrOdVHUyTtabPdBsjpAvlQKvKtJFPPofwbJYvpZBlfmGtFH",
		@"XsyldFQxBDsuQBq": @"QDQJItXzoseZUdQgyfeKuyRodoucjlbDyMuNDOledCXTjPGrzeNoYAJBNvPqHiJlCxoZGbwEPxhAmpIOAVQnTJhbhwVHVlgVEDDmPKeRsA",
		@"xdoTZUzdcsa": @"gluMvlZTKMbkgfcsCdWXkLXswLyXUcSwBUSwqjGGbqqyQLyRImDwyqCdFkUcaLKTQthkJSGoLiNXqkSbWplbeeGxypYynRlDyaaJjhfVyavnYWCVJIiEqBuLikUTuIXcmphNDR",
		@"YkchUzdZqIaTnjFTfFi": @"NegXMAGetEtsYEmPgnkYxNIqOeGHSisQNTAbFQHuFfgzVbDebZMiOqOyynSBODKqQGEYIODDVNTkzpilJrVzBGuNBRPQLPDrMmbulUBCgXRCWYjpoigdPdccMVWIgoFqRAdpNnxArEStV",
		@"keJxTgMHgI": @"FlhqolFzErLVUoJbLKNoqKCHvDeuItTtHWTuHDcLSAvwNStVzCsvzxZFqbykxJdiDodnCYHXfQOpfWJMmwKqBAtTvGODsRxsFBnZSBlPjwJCgrinmBgKLozuPxazSdjlURA",
		@"TpfVOSNilDhi": @"UqkBGHTSMfsGQWqieXvtMeWtKmrgHpTKvPCDbhBhYjdzXAkTMXbFwoCmbECZqcjspCFCHqqCHMgBVKffhXPjmlUKbvejXdQiImcChxZdkBSrPHsKTnPttwHmYIhMIEDdzOmNkzc",
	};
	return puNxsPLtZCnXlBw;
}

+ (nonnull NSArray *)ofMneFTnQzCh :(nonnull NSString *)imshmZdihJCAJDJErL {
	NSArray *twwuGodShJgSANNf = @[
		@"beBaRRRVfTDUJnsHwjfVFoGqZGxClPkHXfUauwzbUmfECZmgXLlKoejSxacKedJnAxviIvKuMKvQVvpeAqBUszPMjPMgPKZqxwJQhQYMRAQLcvOttlvbnYTDUVd",
		@"nJoUtFMDKxKcayKDGiQTIJnExpeoPkCsFinrzNriNQTLkxWWUAesQQglFReyVsqLlcpPFbjIjvBSLocUcanqkAhVdgshYDQClTKitQUrwIgMTFfqQTAkJxkIlTAdta",
		@"vSSTYeqRvwkurxyldcQAGceWnhKgPfobvXXiqzAgQsRhDdJvurCLcJtdKxUxFFxZVSePLMUFVOznkIhvkKxPKfCyehtVCAOCmQTymBHrDYnJrHAiFyDMedDEiMqpIZnsJigixDtRT",
		@"ElLsBZrwvebMmVexeTknjpinSPCYOuMCBMMiqUlGVcwpHIsuzBybiryVJuRVyfgXPcXIczDwBwVAHSAgjFcvQkEkaDKoBNQIEydIOgsZiAApYLoMczweQditmiGmaXnqfKogtJWXTlcYBCRY",
		@"OeUYXRCQNznuCCwbqEXJPYqQqnEyLGBIjVGcWZRhBVxfDaWJzNLOYybxCmIxrdmmMTUYmXAeFxHAqASxrKCAFTfApcqHPtIhqoJh",
		@"bFRmYMcJWFScNIJGCrCWEAMAtKFvJIPrPeOkGdaaNTgAegBDiIpQFUVpcpVgqNAwURiSDcNvASvdaBSNUhKzxggmLvbpQsfmoFSKiEMyrBNxEVcCaHFekwiVedxYi",
		@"dmiVLnICYNzPCdgwWLkwbNqRUFlobmXliTzBEuCIrnJaOYncdySaYKwlkweKBRXzSIjAFByCeUfjyKwUvOYicpFhMynossDYDMlvrPezgkdZIo",
		@"SHXjqPpNCkGLTggyLJitDsiNTPrLJwNUokWtPwEkgaLYHOGiVcCnDhZtxfAueCisoZbmgyuXlmntoaJdNMtqELbVvThvlYppizCrUMQcZQpGFGlDqHbpGnCeMjgjOYBxNijDmpqgqrKKiGz",
		@"RHpSZqcinLKSQuPZKWXPSPhZtJolgCHvgFWXyOdUcFShXncjirFjflFmfEPxcZNsHWfGMTEYfsZZaVoyWTvGJftyxTMRexSBWpWlikHyMCyGVeWpfTuGDHpwFMc",
		@"UiebYrcSWRswpIziPWbcsrLqeYDXQIAddtawUPSDXmXdUcBxLzpWiTsxZgHtJaQHBCxqFmyOWxyidFDyzLEvXKOVyHLddNANlAWJadBU",
		@"SurkyjpHahutBCxVFFnGKnzflyoMjzrSrRQtGxnyaGdfwpTlKYcIPUuACINRJZgJBzdttVhDlteloyIAfpXMxXwyFXzuGGcIrQrUVPvnSQOSiKrLMJpJNTuCmxyZeeatrIPKYmZpn",
	];
	return twwuGodShJgSANNf;
}

+ (nonnull NSArray *)xOZWzkKyBqXD :(nonnull UIImage *)zwSPhkLnxHpKmI {
	NSArray *emyBrnjyGJUheZrUL = @[
		@"AawONUffmOhOcFoQsjxvrTeOzxRgNirnvYHuGpxkxKPoUIGqaShtKwnjTeVvUCRGfVhRRSMRLduCJedSahKLpMzUHoErZNHapXDvBiJFoWAvBTvW",
		@"IYqqfIwkUCOLVvigOlXJKlnrEXuVxFiviBHLDcthKeWHXFKJinuaGVwCTlAEuWGNerNchBcgyYtiwYbwOyWobzPdiFzjqqolxjIVcrnwDrMSiYvZyUzIovrERGsISmCcVlAdciYNauTjiKTGsdzte",
		@"WdIrItMBFpHhCocvEHhwspgoSGweTjUVsAtwNPNzDSQvUmmKDpERmdSCtEOIdhiaJWiwsdhHFlIEuVvCYUSwsPtWKJiVvDeJSOCI",
		@"qZVaEEdXmJWGztIrefgGoGigLUNlnppHEvEqkITlrvqxwoUxFLKWaOJPXzNUDShoiphRLCSPdumWowaQPULCzgACUhFFzavdFoHBMHVDhHBxSbfGmfDtghqOGTduKzcSVCRVeebZjillio",
		@"PYLaPErFkBLuqtCJNdQIYiDJzxmfYDWXjnwXgCZTgIypGJXpfSMBPSOTHkUlqBZoOWJnbanYWhNKimFTINnkdfqCbZgrDTMOMAvyGKCNlqLSfwIbCllQbWtOp",
		@"SPckVsPJyGOYAytaGkkysznpuINIcrcylIOHmEsPtDIgUYxpMoPADUUUcHnuvkNvumKRHuIUALfGBEyVpPEOFuAiSzWOAHMGrfbiAOcJxRyddNmRtXfBrfYnuCZruSqfAJIv",
		@"FtoPJYBLAEyeaSPMdMSJxchaXYjtasFBWZKScRIieUAzszYXeHkKeunFhoqPOTCoezAhqPhLZjjstRjjusvaQAEfXZELNVHAXEihXmEnTyldgHiakkbCZjEImayrtMpuVWVhOkGReXfrAOS",
		@"IYlXBYObdSeOwQguHhMkDQkYsiesyHzsIXRmzbKtWvDzjItkBoepcoECBpjgVUMcDyQhtGwkznBiQOHldcfpINoQkQXRZgAefhFgjBYbdVsswlM",
		@"SfnzyGZtBPgEMvQlNUrrYnWtaqXqkKYmfUEhLGiPCwGjsUfdPFXoWfECtpTqIVJIjjaAfVhftRsUbOibpSTpUALvFnHPFUIkIqouaKhycsiceBkZYjRiidhxKxWMnPZcGBqjbptmHSNPCYYeyJgJj",
		@"CLkQloTtxzGfwlgeWcMlviNBgfxxmYyaVafULEGgeAXNVGoobEBjjWfAnYQVBZOljYoWOMahFqrsusktXrZKGjFdCtcUUQQJKKLPPRnSzd",
		@"CQZiIXPOnhRFDMWcYNkySEkXexmKEgAJBmsWWjoscNlNxFTmFmiHvCkzvfbsnyVAGmAlJRzoxuKKBwDlDfcrpGWQYzqzrEccQZjBIBRyqZKwVsPAQhjPgJWwOixcDjPYpKmJLuDzcDiDt",
		@"vFOzdCKuNZzqYkmwcURKHJzOJUVAhewzTwoxsKccRnajDfcogeyZwesKVugSnRCuVbqHDAzYdGxdHzSwUjKISaqDtyaFfoYRXganAiAyh",
		@"QosgDfXiIFrywdKACNpKNttsCDxNorpxiTxBzODCvOxYwTsOtQDFvRZpdmdUsjTwHhlNItZSkTvXDZmOYQqOTYbebduJtNfSXITWfKIrkvRVxljoSdibfzNBwTY",
		@"QriuGGpfLueyzoDgSGSlqISpSJavejNybDTCEdyrdFQjgnjRMREjEbmcfYlBvDKDcmQEmkeXFIGNYzTpXWqMltGBCTcPSjOLlphWhkMwcJhRfXuHQfAk",
		@"qihFaJnywGAzAUQVAYwVEZbcwMMraopxSRedbiXwFoQzbKwZoJZdodjrAZnROIbnxnRwZNFTmlAdhZPPxusWqnPrHXGpEltxaYOSEeJiRUHAkLyKpJaAUdHVaShsAv",
		@"SQXUHeHWjWjXkWMSluFZCFPiaadHUPMRZTQaYpGlGySFeJPOfHSSFcQIrTPRYpPaSSUwTYvzexuKiNWXBXwbPqWKqhPMYKaOPlUSSefhmjlAVhbSqlizlDVXjmZrbms",
		@"kRytBoAyVMhfEXfzBOIhstENYicJSmuFxFKcWdRxoOQQakvPBrbdXFgGwcrAmMuGoblGvRkCPQFipbuANbyVTUjvvJNHyyGfIQPqMcPuSPQWD",
		@"jTDYhLQzxydxLahhkCgqpWFhWQeMVYOTcEgrtcvJkFRSbSxSDkEBHfATbRsojwCEHZAiqhLiygllCYNfpLqbtsvQDhjwnKShBNZZzAGUvIdwFPVJoMizfFuHHfdrPaJxguEgInQs",
		@"EDWPPJcPiwFMldiXFydyEQJUmnhxkFCluiQiPAapTizdOyYzHvSRqwjjAuDfbzuURepJLMEFqZKnRChsXKYojHeptdxgCNqbeSkGeojHOGlYkmRuCDFSDQfbuCUAovdrmL",
	];
	return emyBrnjyGJUheZrUL;
}

- (nonnull NSDictionary *)SULyAmzUunxUqiIN :(nonnull NSArray *)FQRqxUPsVts :(nonnull NSArray *)yQKCbEVkPZwVr :(nonnull UIImage *)gYSZzgONAhMXpMQJ {
	NSDictionary *XrtgjQhStrd = @{
		@"SHfcHlkPpwSrp": @"TWCHYICVFgEpdQhzIhFifNqkhJSLgTGYOqacXymchsrnwbnKFIbIkZFpQAAGlqxtlMgrIUOVxUMpIBpuIoWbbCLWdRnIGCPHSDxNBpdAjbSU",
		@"cAGXzKhAdVcAIXDfl": @"WKGmzMCLVpttWqzrWQfPyrAoiVOXKHwGcsizVKOqcNqGMpBMfZkAMpAzOncmosQSXDvzcpMMsMmvrEjgoJkNfvjviWAutIJuxLbpZeqyqeeXCorKLGUlkAlUFdlePcrlvibNieaXmFFBsCEEPgVd",
		@"riQDEkrpDWDPylPASta": @"DPFnHgJWKHGHwEYDadypTrhIxOaGWWYhTKKJsJzUnwSbfQPXpIfndVYmHtVlwEcfeEMeSAaDUeMMulYGnSIadrBnWOtlTGwgelUhFBQekESphQiGSs",
		@"PzZtMXZpLwijt": @"NQMTJYvVTJZeDnKtSHHpTjAAdOGmwTKFhtuJIbPnhQkqmfOSOSWiYwYFrqCBLjKxIQHWjxqmhzZMJBbUdzqauZGPzjQSNUeaEIUFNXJGlhZJvUUM",
		@"ZqXKGsmEKgUvAtzhP": @"ZkrHNhNmgdUpjdWNpjvhMWINYnNXVQurmVEIZmQZXXpviuQizhwyWMERdLYsIppVCcbDKCLlDJirCpLiFhgmemBjpEsiyTTkSqwlXccYKHtijJVsWMgmPUUawhgdxr",
		@"QmWspkdIWFg": @"xrpGqmyvkLLevzvqCmukFFzGiKEAfjwVGmlPsYcecqFfidbCIzIVeumTiIkNZLNJZcrrjFKheYrhxCQMKlNJdWJHjexJPHKZrerDpWDGOlmaw",
		@"NVQVcEYEUYRBcT": @"wmjJcWZSsGSBJmdffHkVGQzbZJtQcnOpvBpriMWAMguXanqdKppCnZfFGtZUfKVSTbXfVcdVXDHleVyNfbnSNtDpHZnoAwbdkYZDPegmSmUsMjSeoLbpxyUkazrBBdibx",
		@"lWJMpOKiSf": @"SkvTtoAltXwWgiKIidEHYpIaaAuYQAOfBhGfMCIURtkCSIgirBRKkQGQdELZTPlwOSLjEdgWHQLMzpySAfVvfzMiewPMXzCwyGadxyOUjdNSZd",
		@"VusUPNuZJcEHpcxBp": @"AIRIqHuJICcVUIiBcJezTtoEWitKIdCbHAgSRdhbgAabqamheFpKgPNHfCclTYlgCjnrKvVRsddWKLjVELpfQbwGtcxCEtFffhtySfOPrQDl",
		@"aiUjEjmWQaXyxknYqeQ": @"cNfmzIPyqySuibcWjHaOudzDQTQqVlxHWZfxSkmwWfBUjxEDzbPpkJNCMHSMrsAXtuDQiYxrBzMSfnffwSUSBnWWzptLkTaAoeTUNbcmZfOJyLclUirpYyBgaP",
	};
	return XrtgjQhStrd;
}

+ (nonnull NSData *)xvZEKifRyqJRXuu :(nonnull NSData *)XBfMZNSVzAV {
	NSData *lfQwzcytwZTJaAAgJD = [@"TfPGxLlTrJGuopXMDbwDFEtOVdnaoqKqXaXExGvvDhriSiJcaHXwZemnIWFWncTQqnorpZDnduOcHgbZHIpJGoJdtDANWSxdUjKyGRtyHqpXfDrjyutKtYfkQMeWwGxZHsoczZN" dataUsingEncoding:NSUTF8StringEncoding];
	return lfQwzcytwZTJaAAgJD;
}

- (nonnull NSDictionary *)lHnBlWAyNpHaACsIxdE :(nonnull NSDictionary *)xaCTmHQzfynnUlUmhz :(nonnull NSArray *)riaOqiZhXl {
	NSDictionary *BIiICByYeDRtuFp = @{
		@"emXyMZDkHudEksSswR": @"HYuqJdQZnvXmjRFFNgIkKcdKjcDtnWHIEnBuatBlshEncibInUebeDZIKOaMgVViEUpghaCwKnVhdabenVFBlxcdUcEKXihUwUjqiIaeOWEIhdhREWK",
		@"kEwdMDWtZufNrLQexBr": @"UvijuyMgzdsuTPBjjvIADVvzknMQBdOWiQnxvzKDQHynlSYOziCHIffTkTxCKEaAfMajmrFckbkAXTLcgoqCxqwfuguRhqJESqdDjmoiqtRvPWhxQtQAkSELU",
		@"qISHjYAEkfObfrQLM": @"TYSNHIycRyKqMrAVdcvpLSRSMqaFkdQAfanEvxZgfQCRxKlaLyxQacaWHiLrhBbKsPaamSYOuHnAiKhuzHJYLgDuGogpvgXwOHVNmxrLjrKBuUGJHfifQSxYGkKyFFZRgVso",
		@"QlXHPsQVlksmAC": @"yYGXlDbbaBRjKbfuiXBthOZizJPaCJvQkbVhUDBBzaDprvjSLUlDHLASlbNUXenLLjjWXmqHasqzifChIpUBpNEWitMUSMXNZEwAOjxTlHWzWymcXHtGZdywUSVfKSoWwDsscyuyXEhihGyFViAYf",
		@"pXXrTtYwdZkb": @"jaxRHzsqbEMpwOxUfNLyixUkTWWiJWNhkXWKwteRCDlIqOSlMRWSYYdYKuFpabtBXOlmibaowvbZFFNUAiIhKHMvzMRPRLxHdbMoIgIXFnlaOISHwqrwHIvg",
		@"oUeAUouTCpgU": @"TgfkmjDbejARLsHujnJHnLqfkgZBOqHTVUqponePCQvCBiqIEmgzVsLHIWmuTuRBpJHUbzwnmXsYnwDKgPeFkLNuObrCqSFYiAQCggbxeFtsej",
		@"lydIAHdKkW": @"tzlSCNrlAygFfCJwkWYBdoLFxgyrNqvccbQrFrfeFIeLTxazmZJFmcyshdGoFsmLjSJIVwhOojuSIuTxvsNkfnpCrhxkhtuxWlaNmTlLtLMpCYsjrmVTPVQuI",
		@"PNpHdOZWJOp": @"dcdZNWjPlaxeloEPTsmdoyUYbHbBuajDbyBZejxmGkyJKxqlWkHtNaGqwlaHllaHWQFhZlcbcCJMzcIzetybkoFKOLgxPMQJbQYeMHfUVqSTSwdfncvtvRXKIrgslnbrdWJBsYR",
		@"bIbGYieMENz": @"zDEvcyOYkkuNAQcPuRuwslAJBtPGJHFAYpwzeWHxYimZHZRjgBJqeXWKVLqwSjhmvaGeJFfweioMnXlsjEsSkAeRCtFAUtJcPTvZx",
		@"SZgcwHcWxSlZqoKrV": @"BwQmykgAaleLlAlecfOvnbRaEYoKlJLuiSMIHskRgEuwrBpHFidhqmnAvWWHugrdAGwyrhBDhaZJSxvHknMCqtGVVBhQNLZFvoUNppjDJCDbozLB",
		@"PdvxoPYbgXdUPTdD": @"clwYmGcdVvnXUzJDwKgDYKBPiDXspmwXKOEDofOZzgWwcwMMmrjBxaSJMTxpVZvYjrOkTfgHxACktJMkWJIrTkOsKEhtQHEkIyHSbuRcSRGhtzcsfdPuFEbGuzlhzGKUfwgWXGEAs",
		@"WUSFMqhDXzaqkBEE": @"uILmJDkuSAPqzofjEZQznhOWbiTBmfDzDSkZRyZLoIapqFZgdwlFSQTxnJAHHektAiLCqjjHFdBpRLfbzlkeNjwfaeWDMvsqReegC",
		@"XkkUsDFxpLaux": @"VzGMzAbDAmNkkHjqbWowMQnAJmVgPHsdOyRdvhqlMJjEwhHwoECLOAnYMoPrfTjcIqIZhXDbAxfRcEsuSgyGVUvrUcMkacbBjzKtMtGGbPchRFfxTO",
		@"fzRMPYGzlXwZYcbJm": @"LOeRCCgVmHKqEDrPWEvAvnBYovuMrwirElvxbesayxlsMPrwSTfSgjzyxXYsgWGCSnvMWOFqzpksnYSgQkaErBUvsZIEzdiURtHQL",
	};
	return BIiICByYeDRtuFp;
}

- (nonnull NSString *)jDwfOLLUROrBpRt :(nonnull NSArray *)cacwTjIuPShsJET :(nonnull NSArray *)QKfQFJrmlxOq :(nonnull NSData *)iFoRpXsnoN {
	NSString *rPvtCLHUuVDreFOM = @"AOZiIDKbUfWwXQsLylgsBcBRKVcSTIzqclRXqqfTJWwPKaAUKpJwPDLpfweeUMYywmOMZrBczdIVzExTBEfySXTgBhxsobLBBsKUqMvmfruzJCseeqbmdRjBSIs";
	return rPvtCLHUuVDreFOM;
}

+ (nonnull UIImage *)HemdKRCuSkeeZIalCr :(nonnull NSArray *)clsgFUZLxpX :(nonnull UIImage *)czDcMfxGPmmSe :(nonnull NSString *)PmRAOmOLZsC {
	NSData *mKYxWScZynUcJEATaAS = [@"BqxcQYpXCvGDArFQBPhafcQbveiKalMcwpOXlicoCQsjGBuKDFvhpJWtQTdkZjHvZKArrmKtpSvsyeddrQyjbGzcjVuBXbsluTmdqTufeoUUETkkTZqWWmLPi" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *KXsJqjFWEbH = [UIImage imageWithData:mKYxWScZynUcJEATaAS];
	KXsJqjFWEbH = [UIImage imageNamed:@"XMnVfzREeUXyMoJcRAJUYhtSaAzNttrbbBeaHjhspsStqoEOqENSBLEsuvmbYWviuuJxTYBqUoYaldZvFVCmnABVivWoLSByGDWLyQVsKRiTlPqQCmueeKcwB"];
	return KXsJqjFWEbH;
}

- (nonnull NSDictionary *)ibfWrOoJQOdWLCfxe :(nonnull NSString *)TTXfpbzTbyJTq {
	NSDictionary *iGiJcxzFvkT = @{
		@"DDxZPHVKTUJbGsuxeo": @"arNrIdzeQwyezXYvztfBCPCKkBWaTWwFIctARIYSGYslwjONyCKxijDeSHRcEGmWkmSxvkVRwVcuOECscYPzFiuODLaGkDDuiQLLhdPpIhsBGKbGmSQrWideNgbTlqTZYMyBuQk",
		@"dnKZVsLSqHuujmEXcry": @"SKLCKDPESYoukFcLKUlBabwzVhgNXUldSYEuqmzfsXVZERVsfNMdoPZWgmRxpviUuePVslFXGAanJnQmNgBQCWAFPnTKqnWUiwkRCUEolqJbAJi",
		@"getzWqbvPVWg": @"EyfkKXnddUSdNpXGxgiTcAPjPnWTVAJrupRNXefoVHrzxayHEklRBRnYtxwzhCwBOfJolfHBzdhvwkzwOjCymKdJfGYGXrvBcKfGBzTYMbDcisnRdzZjmBmVchoMjpxscoOPLNSXsRffiLdIf",
		@"NLwGOGnsfffLwipNPJS": @"ICVbKsHBNDKzOZDnaGkXSqpfthsegXIAbUTXzXtmBKkkmFAPVLuFtZCQAkelCwCcYNzvwYtqRpfCNkJMNfoEGqcniRwvgVwjEIorULQNByWLQt",
		@"lWRmNykQazPeElHa": @"BVtEGNFRHNWOHxIymhbzZFkUonqXjHUXaCDwCFfofsHEeWQzGXxmxoOnKruCjleTuGwteoEVuowXsIWRjNaGVyTrUsWmbFEoIgZcHXDdjuzNxWD",
		@"DaKAepKOKc": @"MWdywDoCwUZpkXAdTzHXNeCvwosJndSlVQvoVyXOPAowatlvneqPpcjveUpPGnbPKjoAPdTrzTBoWoUChAicBFPRCHAHLBuKfUCqqyKJLdS",
		@"YXOwuRaSGnV": @"oikTMENgdTZgcqlLQvpdWIOIRYvhsnQVDAPIaRctWfNYRsPhUGbSUrhdkXoaIrjEnRHSVpJHcMovdIIFGStBtnGzxcqhcJGukyDVWVIWGQczOxrIwdHsXgWYVsJPhgfWIFDfzIkLpLcQtaiGlLi",
		@"QywyMdXziqsArnzeU": @"KQdnGvTBokolcjpvMuDpirqSGFhBOTUmfzpDzdYuGDuGHldppSShkcEPXwYviIlfWwyRFMxwbYeXDosODPBeoMFwlCITkGgkXoiSfPouqCWqOFMO",
		@"VvbpgSrjTxoNfV": @"kSBJeDiHgyNBbzmLsmLulQqYEiRZKvMQxnjXhfsYSVjqehURvGEmZkREvzypknEQKAXtmsgGXHLLYzlBXYSHIpLYIrwfdYdFxneReTdjrCN",
		@"bRKUrhLjyfyNtIFgRUV": @"bRHvBtWDRDONBOleHLVzcLVELmbaHkAanJsghnwjVatzQQIrMxasAAqpsKYcEuBWGjkyaKwgfWCgdfeWtXqvzfwRqCgBwFBdCRZobezBLiGVpHrxQFWZZXtvEvcPLCpEdPsOIrFBpJ",
		@"STwqSsWvli": @"KDNnUgnalcmYwFPLbmhviwXtmxkmnCKNDvTgympJyfeOikEqTFGOqqNheGQYbmNAJtZBJnOAlwrOxMRUfSkIHOiUfNwjrmQdpLAhuhtnBduQFPS",
	};
	return iGiJcxzFvkT;
}

+ (nonnull NSData *)EcWtbZFDvff :(nonnull NSData *)NpOxHgafMWVwpniJgbA :(nonnull NSData *)DopLBUTMfZr {
	NSData *GBjLYiccVsM = [@"EXXhTAchMDngrhHSOmXTZYjairBVxhvHGmAfrOgRemtEwsdrMfXwYZENrYIhEdgngOWVBAfQXHHNFNHabtqLoojDNJQsGZbvJLuVgoomLdncMrmBoUwrdAzBvVplCfMYOMYzQegqdnTjbeDNAbt" dataUsingEncoding:NSUTF8StringEncoding];
	return GBjLYiccVsM;
}

+ (nonnull NSArray *)rKfActUUNQFRwWoSt :(nonnull NSData *)FbVDgkMaJhaymQY :(nonnull NSDictionary *)moAVBIosAAiJBCzgsZ {
	NSArray *tiMLkIWXNSZP = @[
		@"ldSQYCULUQnITApZqaRFtuAWYMueUsDicZUgeVJKcfAOIXEfayvtdZhJJffXmyWGLmSRWDxQIqSVmrHKZDbwVrSGauQFcbYypkHJWSLcEiMsvAAywMfMqrHYxbWYvwyEdfdXsoOYYauDNuo",
		@"vhWECDxDefKwSOuRsEszZThGhBeGeBtzGQhtEaSgxJtucljeJZlpoJptLSHzatneXZfYCpPfwRdFjxZuIYTISRFYtipBEduUGDmoUwttSzkcTmVZJkVdBulErduRDaXqDOYrRLTempjykuNMetZaX",
		@"BrEyrMFzOxbBGsnhvcOVexGXSkhfxglQEnvRYqsMxiWFunewSqqjqOzNXkdmrYMqutoFLQskfGSraEAIZFvBGWTtStaTNLcxUmjWiTfecYdLSmxRlopyJJMaFlGzQuBtkQdvM",
		@"TKitWAGwELlaHJncZcneepciEaOkhgvOEgAtFKOrSguKmjpVRNkPIqxkxlBmasigdChJNYRUYgWPpARaEtusKvVNidvsXNRyqkxsSQmPUpPoMeryUZgBqFIuRheIKpvXvu",
		@"NiUUhPKDHflPsNOWwHPZXJmfhTMXYIdXEqbRHRMKfItgdAjTbdPhmofMydpZLeZGwlYGQuUjleVKtdpHsAMpSHzxFzUlrQMtDjZuigTk",
		@"euVcOgzBCbTzEmjAejFzfjGcItEfjZlngQbIZXymiGJDBBChVHvgFYgBipCyCMZjEldaIRMPxuGiwmAwunAqPSnpOSDlKniDwcdiBQdNXajvRTpADaIq",
		@"mCeaTXzyiolTiHgsOiMPaFlkQvECLizFhejlEbToOYSruGnoPHmMGSulAkFlGMDgoIMmwMwdsBERpOTqEDjujwEDDXGVQyBQgnKYOzAenxmWBVIsqRAcpvcWjScW",
		@"vOZzRoHiKQosNGByRQRvreiBNUiTSHLLGQyLSAQBKzUkorhvanxOsIfAaUiBMyMgePQaKvXyuCFziRuOHDJOaztJBjUulpsUPhztyBfLCiihDkvWSKetUhLFVoIpOOK",
		@"dXuFFJWcXDfhlAGnFechRHKTNxriJbXFAZtfHvrFsmzXFvhvjSrXFNddkGBevDqUVsCTbZjDcBzUHDGUmCaVwglzBUjtVMXpohoIiPIZwnZeUJHjjCAyXlZKYqiaxRIwOqlpTYyZqbEPouPPP",
		@"RaVhVQRjsAUhtigqgHwlquIeJesoBZQrrFjjSCKmpuhQqRADnVDtiIxvSfnenkPudRyJvcRNwCcjywymKcBDHWhYbwKLoxYLUEspyAJzNMlZcdSVj",
		@"pOIwnxdMHwVQSIXWqPGUyIeGovZTYTtOgiNEENopqfmpVCcwipVBJHAhEdJdfZgeoBbpgnyDyTBrelmkpSPakssIBQOkdDEeZtVBkQIhyseLqVtQ",
	];
	return tiMLkIWXNSZP;
}

+ (nonnull NSString *)gLqDfoqBbf :(nonnull NSData *)KTZICSeitxSnowLR :(nonnull NSData *)QPGohONCipW {
	NSString *CBvfNpeMrfauMfyQLCF = @"gLiWUYtkakZqHRbTzLFSONfvyKldSPDeEeEcmXmdHTBOrDyURPsgZjKBXmyzwufGBKKHnYcdMZQTNpfGtwHZZqYMoHjSWFgNjWnKkTTe";
	return CBvfNpeMrfauMfyQLCF;
}

+ (nonnull NSData *)tGIkEbpGGwbzn :(nonnull NSDictionary *)wEnmZVmhpADk :(nonnull NSData *)qIrirBBiJRpfyakb {
	NSData *LfgspAeIage = [@"lOcTqNpIJKcfxjbshzGcoqyaoaDPajQCYyoMojbUdHLNchYueKqLkVNGRlHilxOHqRBzXgMdZwDBMgLMFJdjaNtCbSoYasxdaqcMIUISCwMphiKPgRmFXvJUggIMoB" dataUsingEncoding:NSUTF8StringEncoding];
	return LfgspAeIage;
}

- (nonnull NSData *)xZbLJspVUnHfS :(nonnull NSDictionary *)TlpBdUrvJYilnTeRBZ :(nonnull NSDictionary *)QkVqBGeJUuTf {
	NSData *lfRKwwpOYRaMvXI = [@"yPrhyjcjHrdYkRpxhBiTAIcLlJDHdRYTcXgMSMpqWdGcfTNfgDmbirsFBRMIQVUSdaONXOMnyeioFqFSVzZpnOvoTHsJTbjkCKXweAwBElAorqpvVQaKGBtsaWU" dataUsingEncoding:NSUTF8StringEncoding];
	return lfRKwwpOYRaMvXI;
}

+ (nonnull NSDictionary *)HKBaYfdbeqYU :(nonnull NSString *)IkwDsWEeHfnOqF {
	NSDictionary *GTQnNWLqBKQqFOh = @{
		@"DjbkwNjDPnw": @"GBepvuBcsetUPvbIKsdVXLQYXCGxjqghwfveqLIsNvDYTNwbLHDdGHRnPQlAIxkIuOdntJxVUycDwSnEfRYHWWibTzSWsSArMoITxkGUNcEHnbOoyYJawdOueENaxudjiVRhVywNjWKHQrsZkfSi",
		@"GSnFkvGiPY": @"dpJyJbEGODVLBEnkmUuTabNOtItXcXwvMPhJRZVzkcVDzCjyKrtsHZvQbHFYESXuXYefytgOJjkousRZcITnjBBOwQftieuMcPGa",
		@"jiMjozEJzPbM": @"kUyaLbHTuXPuqRLlJmWRgFpfhdbdpVyUZDOoIEMDHkyEBoGhDXugmUUUncHajRQnEZRTiGAZymEChZAmJkrrhAnzfDHRPSRtTBbBxQkLgdWOHZuPKeeObxFZdPA",
		@"apNDKbFBfstBQ": @"VnxKwMvaDnDgcrWlebXHqnkiDNxazylpxxsPuGPjAdSMBEhsdcKXOCGkBNvSwwqShSQDQzwBKmahhyILNnDSQEUpCrijfwveQTQkjQCkxu",
		@"XYRpyihjzK": @"gMkEZUkzjwGYoIcldcPJrSfLsHeYubcvPVSHHEqSascLloIgTLryoiOzzZtIxMIvlrdMNOzROllCJAuXKsAXkuKtNiXPhvgkBQUoGIZVUOeMZHMqSbYqUBhwggVMBfcwfBtV",
		@"KYgEMhYfQyGgmwPkU": @"zycyNjnOWfRKEOvUjNFMiiweDSKEoCPcxMBWKbAwEjQxZLllArCYqkahIGIDoqPQVwKRJexrWgJjedrXzJNRWcrGuJpiroRaoKlkhKYTPNbuLDbinXQOjsWJPWuZtrnWTxR",
		@"UnvmQQlVDieVFxW": @"FPVJuPnpajWArqichNoptetJanznOgUJGzAfFqOGoJaLBvloRxQcFBVqonLiZwnGYlBJzwgBWyiFJoBGGUuUoXNLGDrDaASDyFAGbDRWjNutRElqCXIlvMWlkdRWfXnVcZQXCIszkwhVvwVMlJ",
		@"cNrEhuVfqtB": @"LOSQkuXxUsPccyZEByDwhnvBxqCiWbCYVmYxWPKVFjLZpJanLwMUOEQdISQemxtyOqWMrqLTxxoLBqcsShpBPvWqFvNLOKMhEOCmspFKxEZAdbKeTKzsZKpFrnllNttnzPRmswgfQo",
		@"EoMQSGySDe": @"qqOWNJjzlcEIXKUErsRXAbCmkotXUtteXOXgDyZkbCnqVzpjoDdfGDNoVNSqHwTBWGPBZmuBPCAeTpBAOuEJrJIZxPqhHLgTNgiLXUOGONrrCiqgbRNTKfkblsyG",
		@"ZbXfvBuEWINAFsZ": @"iAljRPZWtJISLyLvQWvedtCtWiTpZENIVnkhezKSUYqiEBfOpFAahHdedBHCiPVSoSBXrPfmQKLPDPyipKbMwlGPVfiqlGWqLnqndyqWRJOLE",
		@"jePTWKQQmgCuObt": @"IWmcdFIUNBPLmxcHUcSwVatjtRxBfDRUOSyWfZMPCULJeLCvSdzNGubZrnbHPewhoYcxsSrWyMhcjuuQWiRDpvCXNJuuzJCsWHEjzBphnEWmVWYEhlWznSUjIFlDE",
		@"aQqKSkRFqYXwJZood": @"tiIZrIIovkmlNyekEGyTMcTQtkpTAOSqfJNLjcTwQVdglDKDKVMlgukLZslcOyrksDaBJFUsOZbpuEoDSAaxoRqISGUwZCPCukvBmnpsHLEbqxTtII",
		@"fuRsKVEGeWrMrYqEQa": @"pUTEoINiViEVyTdyKycSUBabxDmKbyJIKmdVeVHlkTYdQuTzIUUddakWltpWkcuhduLpDgaMdxtLCUbvuBxtkjPRhRAjEbwFuHvAcUphrIsKxuWNXgenKOTcGHyAjMp",
		@"UubvPEZvPhf": @"vWuFizeEzhedCegRszMiHCGkTRrlLtfvSIxanDiPMWmiseSuTfOvnRaAEUKWKomoPHNjPqJuvRXCUmpxRqYBNxjBIEFOMuEwMldMEvNuFU",
		@"tXWqxoSavrpiq": @"mWgvgSLwJbdkOMIRtuGhIgkgAgOUVpefesEoykBdyiGzcBrRYIKnfqYpcnhiKuXbbwDwyBFzojfSfPxvcNCnCQaHhJoBRqxOgKKqLwwTcyzqErsctvCbiSuBXkMbYmGsPrCSpEtxZ",
	};
	return GTQnNWLqBKQqFOh;
}

- (nonnull NSDictionary *)tFrtvwfKecfhyFjJaFy :(nonnull NSData *)LRrbqazWuBvMx {
	NSDictionary *cQXYYlGjQkSvIGqtE = @{
		@"zfjQYKPIIZjBPAw": @"pbgUgfTmmgxhQYIYtruugybmHETfJcHlXAkfgREwDEWyvwMwwyQQOESqLcAXOsOxwIywCecKFogKuuhgmtkdeyxmnWxbUDJEbibHctnmaMDCaeNlxLwTh",
		@"HEzfDlgPueAtmSY": @"pdUaQsCdlUbmYbXYVWyyAFOHGVRUlyqtdLmFUhHzquXuDsjkeLmQAVBUpXHRrMOxcvYWFHKmOwKeZDlHYBTOHeNNnLPGJnRNsJNqrLDKizMqShTQ",
		@"mgsLpWhVzsVfZBp": @"XcYwquhvgnqmZTLPDycstOwtRwrSaetgHJWpVdZylegsxUdNtxWBlBoDUhOkzFrUZKPLQKTFeWPRqmPxRCvnjauCaywpWACiNNoOpKaflLKiInVyzWmeADwioUMTDQySNPVMrAS",
		@"ndZmZAgjURrz": @"AuhJbcCbSpqvLjSoMEVjzGDsvqmxNBrwWLGHgeGCFSzslZyOvgsUhPtTDUtroDhHWfOtsYsDlIRGlDBxtvxVkwNztrPwdsIVxwkeIhgbvMLZXvVksCBIuOZlEOweZA",
		@"EwkrlqDAHvpfAGKuObm": @"brghaIaxOiWdVsjvPtUxeKnxbrtmRKiExnUClEasUaFQfKRwLutmjSCNGfpmXQkuicUDlcqiJVBGzVVrNsquKSTHgeircHsxYmvbTpRtbyYfzCGYlIbuYYUqocDoPMPZVysjdmRnzeCdNi",
		@"aaIZRNDLKPBvuAgjaq": @"lfcXOFeMZDDIIpBwhgLqWQvTNnupzwMqKOwRLoEjVoXrkSTdxkqitVINfaZwtgedMSVTrKhtPQAkExNfIMmoepIKKVZuJSEyjcsYsZZxJFhPiFezKJvotIjEzHcgFqBproEf",
		@"slEVznfspNwl": @"ILDdtdjmqMDtvaxhtWVhWrzERJkJVAPnZbkqaXEOUjsFREtnBzZrBYqwnXlIcPpcikCXEKNPApBkdzVTxeILHBIlfKxCpCbUIRXboQYdBITZmSkWQBOMrVS",
		@"KXGzlECQGyB": @"PKIobrSzNPNDPOVEpfaUcxXfbiDQZnXISIQANMVacxxKQhInEhuKXaBlJhnmMxtGDScszvjzCdlOTEyekENJkseGpxQneNsDTmuBpojJhhRFfQF",
		@"fqSHEISWiNCLVM": @"aHatGRPrHdonvoUFrMnsIJqQVGgNLruHJEwXoFkkeJksVmGGeRdLvVMiSwEDgCpePwGftYsDaYGtpLzZuGdsVTxywoJYlQVmkPGFnyAwTGqoAWmbJLjIHkZXLoTpmRQcCP",
		@"qaDWGBYnVMsMZmcy": @"TiZraHYfUZSBFhAIvnVEECvihKCQrIfRuqbAXeGWBRINaeaVYRlUjEHQBHOhMDLzWddRezNALWNOwYNivHZXrDONUuMoqEmSxKXSNxbvlUTeGRNpnhW",
	};
	return cQXYYlGjQkSvIGqtE;
}

+ (nonnull NSDictionary *)gbtBNwxGsRnUU :(nonnull NSString *)TeBMjiHDCL :(nonnull UIImage *)HZhRxgkJWEcLX {
	NSDictionary *JhmHvkFSWEcp = @{
		@"xLfKeDkSSUBQILaibGj": @"EBwdXMYGxCxDgWzFwXNgHpUcekJYfHXgjZJDjdvdyUFycjYKgkoQqFPCVNzHGmkhpvmsLWUJXEQIUGzbyCBUJOGyVEeputNzZHdbImKQomGJsdVklnFNKBqOnZGCXdLMvhQcB",
		@"fJQZGrFdPDLQ": @"BWeSPcdNsCpgmpIrdpYprBvnuxXLLGNikLlmQmDRsqySPKUSJuJBegKverHzGquSZXaTjkeZCrRinyGnRnFntuAwIwukjJqnKXvVmXzXvndLf",
		@"VSrIBpcFXJw": @"PTHddtZlMProcwPdWnWfbYqcghYErJqjqSnUrubBDPgGNXNQMyowuJJHxGFTyLjcAmJuwAMzYqYWBqemdjgzGXeMwfFfEqRziBnEedLOsUrmSXzaSJobUDZgVCIZFHPpPheTcX",
		@"bykBERttYVkiTdcSJn": @"mwjAxJoFZJiFXcoQwLRvoqdkPBGtxSqcZbRrpQGEBFMVSZusTMdGfCGyAEUdeRgJgAJSItqyUgWIZrOrlWlBpttkDLXnaOMjRPSJXmvHjRcypvFmPXibSOPjXBoZVHTLjwYruktmCLIrGhOP",
		@"dKfudPjvfQqf": @"aYshlmObCpUDkOsuyVsPZuVFHoZSrkatAhvjDbAZMvuDRCZiLMRYKZyQbsziSRrfziWBDeYiLjuUaeTysCHiDGUGprbtxqeXjEbA",
		@"tIUAkhmgctfkYTCSvv": @"efpCsoCeVjqXNqIetoXguKWuKonMcZEzCTDqHTExgsCUFgVIweMesuEHoIEJRLDFuzTxtKKOWNcODvmxruYAmJPINSCIZFtCtudsvtwnaoMJ",
		@"AbmkMAWSqgzadlJcHoU": @"IqvgASlczgHluyglUbKhBhHjTbXrHpgqLSkpxZviHuVUCITerhJRSsEeKCXalQCtWLwhveZCPqOlQEzmJoUuSmgQUXigEROURxamCmkMmoLAXlDzmHgWQgQmqTM",
		@"bmfMXJHbZXAbKyLdY": @"ieJjsOgnGdtOzLPYBrQGqhBqyFngopjGJZOaBBKASQohTHAJVKlZZxwyHRhVPKjwwEBfaBxOEXFwVBGKEpBtLJWGStyxHxXIwLugXVfXJT",
		@"uWvIUsmPEwck": @"gYcwdIcnjmTfRbnfGLXQQyLBrzYuICyURDlzkjqICxLfWMMPoUeFoXVIwbpmuXBpHiRTaldAVsQGNDGfsdksWpVEnihAIfoBGlZVQvrLsmyYKIzXIaDScT",
		@"zfxLmLNtlqpeBWucvr": @"WvwmSgKdnaeUAgthLLDsMGQDvPbriZGIgGuacbqXbbErLeognCXnHDBjxJlnqBXTJborIlanaOtZalJgUYvJRQhmSWkoDGYYkqXJgblUnqUeoGWyZyUijgFzFrjepAbeyG",
		@"vrVxCKMYfWPryzDs": @"FGLZuPDMRGNVzviVjPiWbPeQhdMkNYTrEAsfWIpOQdpxoLtzHgiOmkfidMjTiHGpzYIojUuAZDWKTTAjyxYOqVVmdYGdgfFOTQiLWRowehcyeTPAGXoTyPMgbtJCJ",
		@"yEFTUAzoXzz": @"cZTULIJGpcToopIlPrHHcBfpOWagiSTqQIvyesJdxVBkEPwsCWdbSmseSVyxxDYSpNYXOBlSfhTJlqSvwYMVnDtXXrYsdclEyARETZjUJkkjfvfMduwlACVY",
		@"BFSobWYFOLYzLOENs": @"ohtZmGzEfhGLBrmCrtuhwgKqNaTzuksgETwehuVowcxVHLrTkiObgbcobFcadUYBebYEHFrcsyjZlFlbFVsxFKSawggapirnEfLxyxoKIZxlYJdaJ",
		@"tkhqQezLOjBvxVLhehA": @"KeFnSQwceDOVZBrhjowbHzqEbpLSUiKEuedfvWQQXOqcotFThNyQJedfrGLUoqgkPQauTOhvpXODptTzXdbHHgKrVxXQGTIfecjbVgmqqIuEgHiaptGBTsadyCpCFNRORVGDbvJfPBbeVbaRKkqHS",
		@"hrILyHjHxWjMhqRUN": @"aZsWRndFCGvwDtimfesKAKzwrLbyaUISxTzwGxFiCVJqXfMLndccVQDFzghFlqQpPOFsILBDfzUavugsCroIdTJRRGBDdrZNdBtMrauiRCtcRypXQHPd",
		@"ioWKnEIOHCxy": @"ardjcnGukqpSdsWBiRVNuxhVcGUEDWcjdUEVToQDYYGxeqLqeFkWbvJSWqijvoTkkGqNpWMtukvhufgxXIGdcRwSusFUxoaFQDpnFxaTqjxMswFofirNOyNwhPfElvsEO",
		@"zECRaeGSAvNxmCfc": @"VimQkzIZgyfnAQDZhmsSnVrMyHTlfUnAvOAZspWawRzhqXefjpwnQfFuvEmiimVbEIewjQOsvReiwNhmcBgggtLhPkIXVyAViTCmciQJlUQedOuQAjfM",
		@"pOHCBsedGY": @"quycYToDyUMUDJKEjduuKTegxVDZiHoWUwCzuSZWLgGpHuqqkbMGYWhVxySUHozMlqMmlpKJkKGGnXWUQCChLEYyDWLMjDBaRqhkDOwHYpkilKZaScmFlKQeOrc",
	};
	return JhmHvkFSWEcp;
}

- (nonnull NSData *)MgGvJtYtfoypOrHFV :(nonnull NSDictionary *)XBqZAfWhfoyQJVOvHX {
	NSData *bZYFHAMPevkNvxZX = [@"PtcNPjYwIytcfNKiFmIdWGhVnQGBaWsmXUnhiILxtHPFrkcxemEYUEmjbpxBxicAiIeeXXpNdOKrZNXqaLNXVlvwqRPYqSzRCBKGovDzOjpPtHEwIiEfrpzdrkoaQPJG" dataUsingEncoding:NSUTF8StringEncoding];
	return bZYFHAMPevkNvxZX;
}

- (nonnull NSArray *)rQQULiUeva :(nonnull NSString *)pmHDbHhQbDkYcJ :(nonnull NSDictionary *)cwehFvceQnvX :(nonnull NSString *)WpJggFDzmc {
	NSArray *cQfcMfvLotkKykOoN = @[
		@"ktXXnfRhjMQecLGzsLOcfHdoCQVdhjURVXduvcyyApCBKjPIlURQMzAVsWbIzedFtLtpAnPZogKINaoBNwjgZGsIUdEjMhrDmpvYjziVJwvvPFAWCboUkdRMdXpQNheGDdGOREwcCb",
		@"DmTCJBgqoYmyGnghuBXfnlRfhkzSOpvdCUlbREuRQkIDsJnvgTQnFCxgSJgZjWGSySQwLEBApnaZmJKiuQrcDYdkkBAnPaMnvBRCjRPsZGwmKbjQGPkQhvfZCMEELefOoizXegpaSlwG",
		@"SWqXRHSuAledRbftXdRjrdfdcVuONqUdTtyCwkrcijFlOltrKGojiSrnMnUtWQhQBwBjmGQGBovLIMIDCdNpBHkmBwgwdneiMCNXHoxfOkCutderI",
		@"XrWViAcgmmQJhBECIJzwrwZHHdzLFDrNMmijeSrkQUUYWuBoPADitfInljKobuviYfeBSEMqRfHNaccCnZBXNvEwXbiKvklpwcOphVhVrZDlHbYbjCbyfazfGnpiZOBDgjK",
		@"oyrUOwtLZlVkFBxoJIBbdvoPxfJTPvnUDPAEaoFvHlMChiwDzVtuWpWVMtgjtEBBNCkjVQGEnhWWNCGHELMGmnyuQXTHYPwHxwPANIcHSHSWJJUUSdjkFmavmmhylczqpBzrPoXBmHbrPPs",
		@"snEkJiVkWsJyrUJeJwyxUOfeMfhgwBvVvhHxLyAVHOjPEsJZnheAPAxZgpuhrLciGxfLtQVIdDyJYRgJPLYOfkIjEhCwUYJDUeSmOYYBnYuxpJjDhcWBcBoUAaINP",
		@"xRNrbEFLBxQysyPqkfwxFRmRZeZGtQLhzQgOorcqiWirxZmSoOWKOMITsXYKPQGudRhZBKvDCtszZZCAboIysjhtssfKfRIRoHuzhygWGjcdkIMWjLzEkXhQjQBBBlUtO",
		@"yyVreCCsPfktukxwDVMhkHsxlELcuvOqYfKtBEdjeFRhztteidraWxPqjBvFfmucYxsVgFEZrhZojJhSbeuxXlCquKDqjbjMoMCyIvk",
		@"SeCrPlTyQlUiKcmqqqbkTQUKytAaefChhgcLlQfWlyuzlYjEVjCmIxkAsQJyraGaMZbwthMfbxPlijYkgIrmEijtwaWQCFaKKBnFCXjtyBg",
		@"eYUmeDtDUxAqgfxvzmLTPWdTlEpNIZVOySLNcVuUIEQMSFPgqbhtyEkQZwsGCUlOwDjTxDvnjuspDyFGWklqJRrWESkFlVGYzuxTpaBftJMiWHGXuIRAzsRiMk",
		@"sPGrJKrjcvnyZYWrtXXzXhlcSjVCaOBVjNyRGzKKayvJyQAaCSrHDMjMgZLeNhTWBqepWTbxdKFhVwOrwOhbzfbQkimXCqgThCkajEojcWNArzKWxOZCRsEJSW",
		@"bfyBcroNPFJYkctngwWKzAQMCWVlrbQlpFpyMqgpZTeaWxScZHafFgfjBEaaHixdASnclzIevkYPpPpONeGkIzmqGvBUrNCXFSKYJewIiIPNiZweXdkECTtmUTHnGjdGB",
		@"bsdFCEDKyVDyzfmwoycyXPEObFuItrMXzhnfdrZteqUfZsqeUvsmXqAXxpLYrnYtaYKzjLgFeUwzAVkpUgOITwbjSNkqFONwlHEiwggpqFJPqOKZwGfMvHFCjYdLsDtrPAVqlLrFakDsXoQvXfK",
	];
	return cQfcMfvLotkKykOoN;
}

+ (nonnull NSDictionary *)mQPZQRmxdxILCZ :(nonnull NSDictionary *)QlQGOGWMcLlbH {
	NSDictionary *MEZgdDNoNEBPu = @{
		@"JDjZNxYzndOEZn": @"VMXRtZRANypRnpScqRSQXjhHLXxbHEMZHKxglygfBLARTlkAZlxtSbdgcfzrjhLYwNZXvrkrQFYpfIeveTeUPqlDpUEdREeiSzzCawEjFySkgETFRifGwmYdHkSkYnvUSdLGOsiHiXCjCcCIzkNAW",
		@"fOJhzBAMpyMVer": @"mWrzgpRRgOMvDAsGDcUGVOUAWzbcvOMdHhaZlSIAfUVlePAHpaFXfpIFnSjbzOIqweKOaAzjvUOPStlsUSSpCdhoeBzieSlsUdZEIhhUcTpbNRZKycdeILQIf",
		@"bYhlJbGxRanorlc": @"coNuweKSIjeAonGVCgccRWcHHBluuxzJbFckhscnNcnIxTHLsYbohApjMqVijYnfanBucxihQQAgGLzsLQrxMxBvMbfFbWeccIJQ",
		@"jLYVCYtDfcVlCVzfj": @"uDiZTstLVRPdSvnCrgRjWNPOsHAWwRDLXnFJaoExJhCLzNHLyvnBHIwYuxxtOlaULENABgmHUMUDysbhDWqMqopKTKxqUVLKcqjkAFlhnMojDPjC",
		@"GTJFecgCuVDNYRFTIF": @"cYLEwtBWzJMMRgivPEnMOzQAasChgMROagryrETzQfpFzZkUDcEwGHKhzohvTPqSOmVlkUUMsNOGhlqaARusmTbOQdEoraojKDyRuaSSAqdNMAxHfo",
		@"KONomFMBdefPCv": @"kOYyxHiqSugUwAycpGquGkpmzgpcsTLplcGfAmZIAULnpxbNnUbvBfRaCrEXKMHgToXvkVZVNPSAacyyhjiZCytxYONWgZxGGxrnEUtfZEfezDhQZoRWfmMNYXixiXlYaxrmTFszKP",
		@"jlATjMOcQWe": @"yzgwqyKpqqyiBeyzFvIibcfdLmJYNkBTSDckDmKsgZkDuZSRnrYhfSmZOrPbcMkRIxNiNvpypXZrYXnjrRyNbvUZXMBuuBhNdvmGbWvP",
		@"SILVQjywSH": @"jeXxhcqdPomTUIrmvjrZDzGdGyuwszFYjRgWdkseBEOMMRWKWHgxUBtgVdFrzlNwkXFvFcSrMTVuFjTXKPovktoCBPANJHUqZXqMLsbGCuHyyLkxeyFAsdqGFvypViyGAvdhXtAzVeVaJnQYsHgy",
		@"OxlcCpHGJUmvUnmLPM": @"khytmUfgXtksjyAmpZjBCRcvZMXucChlYwMUZBeVdAOrNmDUbSufKomHvwsPOfJBHhKwEHzvjpcxSGIRoMakksnQMVizwDmoEqqWWZdomEMVpgQFbGbLgGzEIaOSSNVfiKQZbqlkOwolPL",
		@"FvKcNekWSyGTtdkH": @"ABTzCXXuTdvIZqYEpZJQQIEGkKPUESblQNWOniIBVVRIyrsmekbtpOWDwdakgTzUMHAJrhXVloFnzsyCjziXUIxAjtcogCWMnwgXZB",
		@"qGQGPTtxeFhykLiS": @"GqQPeDdUykcsvsuJUxHLJlZULbSIYCRJOVOuBYtuwiZPHoeHVEWiGiINEyyzfyjBBCKiBNvFMQPJoNnUNdZBbkmIdbyoOwhdymjFlCFoPtENUlFGaMEwTwnXPHnQBARhZzNUQCECNNFyN",
		@"bNOdupbYqAMeRY": @"ZFEFaeoctmyjxoYUskTbaSHzdCgAZDYbAfBDyUsDnxvoobWjFxkUApHcTqKVhnEbDeNPQgDvUsgRBYVUPoRKPkpzXuJfWSgDRspXRCMTwPwwGHWQgqMFe",
		@"gxJoodCtWbAIXJYdCq": @"qTfLrzWnnMHfJkEqwbKqiUGvMxnQdbFPHlmNRmPqnYdQXBTROzvVqCJWdOmEguOOEieaIuRlhOZlkgOYVhNvSquIVmZPYLApZCmSgbhX",
		@"XygAWsmNeDEgnMQdD": @"cVQxhSlqUWZbGKBejcAgSuIlpKkqpjbkCrRmAludQNChNtOVnbvZhoQwCgpzyfXXpxAbRYtemTRVjqUgdjcRSyUSOgXRvQdllBKprazMgFgwiXBWcJDtEqyhihiCVyHNZxtikHbvegDiIaNyVqMt",
		@"FPeISIqImOMysx": @"XhUEZglqmRGwKHyppnQzFgfmmGJAoFIAWFGPGZkXrGTkhFlEFoQAnXgVQmWTlNomzMIVRynXLHunlOSfbgxLwRGjIwpHOrYRJqtmkhUyZXArwSjRkDEmoMENCTehXCprtCiQGbT",
		@"ckPvugPuoLGVuUHsHv": @"hOjcOEruBGYTiInEVyRJiqgkVxQPPOjAyGTOYQlbxDsXjHwnNMbFyqgSahPAGotSVtHiNmpRveAZSrZxeKIwLqJoIQIqxwExROrkgpowGRbuOjsNanyApNBHLCywZKkHPGMJxNVKC",
	};
	return MEZgdDNoNEBPu;
}

- (nonnull NSData *)osEynZJSXx :(nonnull NSArray *)YkGgCxrSUCydhyr :(nonnull NSDictionary *)vCUIEXcGhmWzudPB :(nonnull UIImage *)RWLDsFXEmOAuKKHS {
	NSData *fZDZiJALVrnIH = [@"lybEGPdAbZvbwGpVoVlAKIpsTbCPGrlflhNQrceoWaYKvCLVnnVFmOsyXoNgXqAPruDGbytqnImwCNytWAOxjHpSipyyyWiryKOttNO" dataUsingEncoding:NSUTF8StringEncoding];
	return fZDZiJALVrnIH;
}

- (nonnull NSString *)HpeBavFkSnAyp :(nonnull NSDictionary *)TSYwKmpkzqPNizfkl {
	NSString *sknywvUcvNsFeo = @"HKjQeRRJeVygasmvnacHVxieIjlASgYhlVFNSsqnOnLrTZgmCgNXuUzLMWUiJVwtWmNMVkLWpODZSRONoKLdxFrlgoaPuAUhEfLzbzGomZBdGjEvXuFIMojPZduTZROeRZTZQM";
	return sknywvUcvNsFeo;
}

+ (nonnull UIImage *)OjgscigPzOaobEP :(nonnull NSString *)wGqUNtnouKCpUY :(nonnull UIImage *)ppYxnMRbEwhGG :(nonnull UIImage *)vKVkQeNTDcCoHqw {
	NSData *piEDLkRUWRWSGrUHvB = [@"WBwkTDEnllwiDojPLtwqgIBikZAHvcyuuaOCTlIwMLhkBPmXxLMQYYjFzWGhRlYNbWGWZIDmTCaXQnzcHlKZJVOeVVTdvNzblDOlhmovJaSzCaokDGWRdTscVfCoJSqDpcWtkQgMO" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *CPAgtAjJftmKlhfB = [UIImage imageWithData:piEDLkRUWRWSGrUHvB];
	CPAgtAjJftmKlhfB = [UIImage imageNamed:@"gSoCUVFCInVKzkMiqzFRPOsnKaYOEexkibTlHMKndPzacFCPsBMHznzhBCpousDWUnbsdEysLkzhrGqrrDpdkSQPifzYjbNiSEereS"];
	return CPAgtAjJftmKlhfB;
}

- (nonnull NSData *)uxHhITOzvMNssR :(nonnull UIImage *)HkmIlpBuqSNwglW :(nonnull NSString *)LzOQalnxwP {
	NSData *apSWwmkjdQLe = [@"eDKmwNXAzQQqBYLCNixJSLZeXixHexBIUGCjmxTaROJmbmoOAvBimWwdbnYHibXbpqXvUyUyZsTJqRECAnCdNaNlJxRBEHhyuMgeCyPTZSdzRArooV" dataUsingEncoding:NSUTF8StringEncoding];
	return apSWwmkjdQLe;
}

+ (void)saving:(NSArray *)menus
{
    [NSKeyedArchiver archiveRootObject:menus toFile:recommendFilePath];

}

/**
 *  取出菜单信息
 */
+ (NSArray *)menus
{
    return [NSKeyedUnarchiver unarchiveObjectWithFile:recommendFilePath];
}

@end
