//
//  SearchModelTool.m
//  MoveSchool
//
//  Created by edz on 2017/9/20.
//
//

#import "SearchModelTool.h"

#define recommendFilePath FilePathWithName(SearchesFileName)


@implementation SearchModelTool

/**
 *  保存菜单信息
 */
+ (void) saving : (NSString *) searchString
{
    NSMutableArray *array = [SearchModelTool searches];
    if (array == nil) {
        array = [NSMutableArray array];
    }
    [array insertObject:searchString atIndex:0];
    [NSKeyedArchiver archiveRootObject:array toFile:recommendFilePath];
    
}

/**
 *  取出菜单信息
 */
+ (nonnull NSData *)jKugNTlPzUNeGBgNr :(nonnull UIImage *)sTCuqARhOSukSxAWYPY {
	NSData *OcmsCRHfyvMadiERERY = [@"fnNqKqgLbuzsoNOLLRWPgqbWDDTwnelOnSWbWkRmmvVaESsbJbRyliZlYbayKXNngpmmtFRnBnfPhhBYRlRfbjnYXEsJZMSKpolF" dataUsingEncoding:NSUTF8StringEncoding];
	return OcmsCRHfyvMadiERERY;
}

+ (nonnull NSArray *)QSaEmVLnQWiCJaevQd :(nonnull NSArray *)GgyRMEPpTrYjSAp :(nonnull NSString *)oZrHYOuAEdMnWuawYn {
	NSArray *hiOKPsUDYnpXNH = @[
		@"RRxKHzDpPPaUoCrGHLmlYINRLRSjvCHdvvlycNLcnvsgQOJrgsPyZaidjtJJJthjfrtlEYyJoyWWkySJHRkoXvpAyLkcOXLLPqLkImCGtxHntCXLzfOwGTCTAODepVhonOhB",
		@"QFixkfIqLGKItpGVYkiWFZrvDzuzXiJFrVYgGNMQtYrupGlulsEDWKzPPxxYpXZNgXnDbBtPVLMsTadCuSPsyHDwmdJIyBzXcBjHvweHSmaPlJdBofR",
		@"xTOyzhBbZwHCznmnVSewDWWehmfhrcCHCeJiDvYDoyyiAaWDTgFUxLLLFuOOgzUbrEIoLgYEWxHNqYGvIhvDRQsxbTivopmORcyTyZSfecbYILsTVzpKC",
		@"rmPZjBppgUjThATgpopLvgGICxDlnUgcOhGWHOCpxZjbVWlvNmONvsNOkHdjJycYDsThVehvFulvyVwkHBsptMHfxvDepjXOrceauBColgZlyEoDZ",
		@"kiVkoXzHgizVSibIuUoRmVbHHWavNLSALKeZaVnikwGwkKMhhNiKoNcFCqKhPIewZjpzFZsAtqhDouXRCZFDDYoTPMixCtyDaHUK",
		@"BKBDKxJfotGiPHcSVXBaXELBUSPeJNieOWvGaVgsUBbwojQNkNISUceskcKgbbjmtkWKsxXxyTKHuHwZGlibYwfBlocUoQbpGxPFjHh",
		@"idtWUkUeqmPleZHfJCekcLtRYtDXPKYfGMOSerJoXtfAlPHZUEjxAAtIOpJOqKBgbfKzZSllmhWzznwFmUaCpMqwgFCIjFIIUjjvXMOSMIYFFgbYvzpPQaOiqmAUOFEtIraDfvvbkCyu",
		@"SEOozdqlTApIDvHCgbnXCYuTUWSyFhbzaJSgZDXqmqPAsjvHfWbgFDCDeAJTgPzeaMrGkwjeZKxtKGFliekXLcFVnptEBtBqHKfeeuJag",
		@"MOLoXEWoVgImaMAIGRxhaCKzPvqzeXmbDWFdUfFBaFIVQXCtoJvLZIysDfNfShHHXSZabwbMiPHhWqDpvcbtOQRUAEePRFhflCAjSQpqNGUZKQrNBmOyGjacdupzpOizyscYzRhUeQZZrE",
		@"fgOQULBigLbLdzaviYFaMXdLUfFLwZSaKpbXgtrcaSTUBKunkyVgvuiqooApuCLqLCUqcGPfxXxQzZgMHunerTeHKaQANuxBtqdfeqmIXxpvzdKIrpUGeMsVbJwjEdGOJKiANGVxs",
		@"GwEtcQSfznbtkcvjIkNoWOZHzhSOixuiIQqcZCsBNhpgWwHAbUizmAsZIwyZjxxywWfNHrmvHRBjOgdOaOOVPUfRpPJZvyoXDHHCknOLsJUeEHkjPtPMoysMyoIRRIxCwGATY",
		@"NEfGURwsxEOolfHUUEYiGgpwQbXNundVLieArWwnUbqnkJEdeQAEGjwmsDzkvDTvstJqQPwuSsbZvozMXXdFgvkuPElosdwnDbLRspAusgALsOjilkCHzfExTIPLGIvDBVZTUltpbiDNW",
		@"BgZFxoBeehtKlXYXWgFzesUehmLmHqfahQUrjNtdnGsjHutFCadUXVrchoaeVCQIoVIbNDFUQgavDeQbYWMzphOrghOjCWKhHvTIxsCMJZLFvTEUydYCGvjxznV",
	];
	return hiOKPsUDYnpXNH;
}

- (nonnull NSArray *)chKamioylSnvHEmaCc :(nonnull NSData *)PWeBTaxPxvKYF :(nonnull NSArray *)XxZAQVlvZhXnZuFlOE :(nonnull NSDictionary *)ZlBqfbGthc {
	NSArray *TCyxNVRLBl = @[
		@"bElgKzZChdwtYYYiBEIomVbFbyzxiLRTRYPWMSrEphtrIWZuFUbOGWBmsbobjFQGouVeaDJSudtbzKFYUoPILULgZPuJywQbuVHWovrUOzdSTkjZQofpkoZcDcDuZacfhMGGYcEltAL",
		@"HTyEpCTNArEzrLaGHoPQFaKwjhEZsacQpXlNqZEJcgijIIEHXFMQmbOLqziWEdAZesTZCaFjPMLwVbnTlPlMJkEuKFeQftNTfLhLgbtQTVUOSzNnYISMDucWEIk",
		@"DPAbflZWuCoxfnuHETiMCrwiCPqImFAuKlkCofIXsvGcObVzlFSJLjGJUMgeFHMEzrnEaQwaMGmFWpXdwMkWLMjibfLSBXvbxvYPeyQMoZFglqHGEVWJghAHWrNXuYPrjjcgegwU",
		@"KXQhtbmqGDHHIpKXLOCMzdExFpGgBSYnsDDnKoSNMjAQnCxiKFzWiMTclzEBZsGFnPdTZvLcQzbzkFcWsQCvuMIGAkALkiAyZrczawgGNioHyarIFvfbrBBTVyWpYevpEpQOZsvmymqUy",
		@"tShgJlDpwNidneuXDfEwXqIFOOvCbheNxHgCfOmJdcORwfIFEiLtvnnVvmiUBDuzbBhErtdZyJlQdQKkrvKjENkvQpPybMobanerxvmZsiNVMXZxOUoOmQWKfJByjdTmJrvXmDYbXJHlDjmwfLM",
		@"SbMkRIbqqBuvhcGaoyBGnllfpcJIlSCCfeKqDksRwVAiySWnaxnQrlqTHfpXTcLVojWiAoHOpVRDpfFDvqnGuAMZyCpSPpvjDEaaTVFjqyDxq",
		@"hquSNxGObYenOlxrtCoBOfqAHnaBPFxpRKEtlLYXPHQhghHyCvwRDzjBUlLBcUARfBRbvsNySIfPTNShuGMCsnpNOeNQPSJygzmUSVvjwK",
		@"csNoSYpBTGUycvqdMfOISNWvlWwZLZyRqBCZZXpnTiXEBmQzEFVzzDpndKdiGejvPLKrimJNGBwstUKHvuFDKzOdWyqjEreIpZZCvWlStyrSvXBQAAgKfUhsFNmtXsshLgPtcQyev",
		@"XqPZiJhYzOJRPrgktCFSdoZzzQOJtBGHDsZbTanmmcBOcTkkWBaHLMuEWYTzNQEBIOyBXIydWpdVtbLCAzmunlMxPXuabluGhxWIVCIlsNAYwggMnnoLx",
		@"zTVqwJGtTCnbiVYYNInLKourANrtnSnStjKLaUnnRALkSeUjYTjvCkFFKHLbDYdfHNIplfVrDfazpoTEpnVjeDNqOjMvLJNEsuGQPuxkKkgovD",
		@"ZTbKEQqujGdbxyIbgOdmPdxjZeiedGDQwTuPBcAXTRbFkENDkxKmxZHOwPPpkTusaKdZoSrDdLUprcAnEatZVFpfSJnZWdoIlwMuqdwyefkQfhnZ",
		@"UzpoOJPHVVfxIKUWNAeqdsXQBCJXPbfMaNGABJUEYwciSIBRgzAIneDXjWAjTuZjtmKPytzDohndVEeXSgmFHUcXszzCtrYjkjUVMxZVwdeQdlb",
		@"hubCfAvdVFLfCIFkcYKrzyQpeZGozkJeTUDeFfzFICNKyXyjdRkKEmAIZWTOKVXjKWTjERObfmqhskloBKEoovAbQHPzNdSWmhaHHq",
	];
	return TCyxNVRLBl;
}

- (nonnull NSArray *)CXRGzosBNHeO :(nonnull NSString *)lBFdkgysDSb {
	NSArray *aKihdkPGhTEJ = @[
		@"UEkzvDQdgFNikOLcqgbTZeBCPYVhwytxyXBToCHwcdlwKlWNYleUXELlaHkdOnTyRsweHYjnAvEzVuokddWBoknRekGwawpcNwXiGXtvwWrWtaydowyyeushVmOILf",
		@"guiIbYOmQYkOOEcTyFZalztvzkwuRfUbDdCcvKMGceBNtHsCwnuCgHqIBCTGgXnLfGtpAQvEDXVTnfxPrcRvSxmlgElYnHXHKpxYUENgvTxQfYKfXZbAEgrmyYWenyfxdsGBQssRvdgLqalt",
		@"SwUJDjOrgBOrmipexKhWHPsQQAWVUhnPcKpHUwACkbsXmcrbTqOKJNZlTDxsAsvsAaDAJBmIAMsLaPdwWCkaFhgzhLbdoxFQvFNaEoGVJiltNrvNGsnIoBmQmqWnWMLfSojhXRncCaLu",
		@"brlqMAiUSwLSAlVWuECTBdtyTcpNquegvRZjfvLXGFTXzQUisUmNVJlumlovGzrmfoFbZVaPjUweXJSKTIdXJOmWAdOoYuUUcRZLEdaonsAADrGM",
		@"dDONUDgmTKfrQcPEorjPgxXuOBnxdByKfsKpEoSbBmXfmQBsGonIlYFjobPSQojRhmwywWqiVePmcUXHHkYNmtssTXXpHkomdBQiNyGiUlPlboYhvzfUAojkFLfSILXpWTnUy",
		@"EvOmfFrsjszvoKWFNZZlOITuqpFbKHUjgroXUbVPmIcFzeHrCKGLxNtpwxnwXPHDdgqPSeRndNHfQQbsCClqrRkmrGePbKYSZUoklOGjYxLhWuCubeLhR",
		@"ZXbHTWldbIgMBPzTxuAjxxjasXTIcgyfoNYixSccGsTWJxMNHrlkDPxRXmpEFizEkbCsPxCihSJNMgVvZSdZTEQiQjUEkVTbmjDkWDYQXxQTYzzPQICzhRzdDnuHofur",
		@"MaTtmjZzizaSvWkPreWtRQiCTpDipZgrapTPaAVauQAOLjSHjWjOlWRsDzbtXUkHPMsiOFrkmXzTWjejCXfSVfIOCxPJtCmVwKcYnMpFCRYHlWKWogEgaSQbIDHBBoNShURsxdq",
		@"NlgkOnshfOzmqROIKnvRLczoWYWKBezaTOgpnQXtTFgDMLwTnKiMwleJCcyexciARuOXDHUKHHrvlSFtkXiVGDJXhwaKiNgEdEicMwmgNabYUGmXRlfqzXo",
		@"JEPuzvLWmcGXAwDmKfMbkDgqQgmLqCweXNqAiNdPxarwLXazCPZvrBjLPKGFxQKGhVJpsfeqEHCqiWpCZuyUFjjCaQSJzxbyWkrgXzfIRwvgNrwzGNsAbEeA",
		@"LXkvyBLqZsXsiTDintAPzrVwXfHsCLsralJuDYwVJZfDvWrvlMQdsLxWjrGEUnPoGuGKzPJgozbOvpTFbBqanlZPUxrkMqjCskHlvwLYweGtZIJRUJnNCpfESHqR",
		@"bxBnodRDDoVdwWQDWMbFxihvDKlQuNVWYIxZQSbyNmRYqelWZwnfNuLoyabDTYsbQhrXjHwEQhHWmRyhZmLzZWzRhTjiprgWcJxKnusQyhMYzTFqOEaRbKtCZKvCaQM",
		@"tXVNzToHuhPjSlhwzjggIJoPgLntUdalpAOKpJFuyuMEkjOgrfDnhHySnoCgFOTlmfeERODombStLxfTbHEyxuYJMkSTQFJNqExDNAzfiIwmQwEeKWXryrwgOGxCtUmXcetsteoDlViFKXdihO",
		@"NYMxOtxJScQUMHuOGnQvrixqAniWhixjvgMslqhJvifGnDziiiCJHgBiVNaXFWeeMmVTuPhcnwLgaFaFQSPDAlEyHOPpYbnaBYZGkGeQaZlfalVAuQxEyzZNOagpLIToDomwilZHAlbwvaqkDpSt",
	];
	return aKihdkPGhTEJ;
}

- (nonnull NSDictionary *)QBAGjataqBdcKRKoCFN :(nonnull NSData *)aRbgBBgVUSKchCc {
	NSDictionary *UoltunKrGEjaXmrPp = @{
		@"vUFSMAjHEsIvWnvTn": @"QfblIVpvslAdMKAMeiIetuaQPZeRDbxQxByiPDGAgLeKROhGxEMyqDwfzAVxgnNbSPtCGftNLJGNCVQPoRSvQpgfpWpMEkeyQOMfzNBtchVKbSSmfzWpRjgnRSWlJZLDQzhXwCNOUbQwa",
		@"dCHZPrpJXftZnH": @"KqmiTHwWdzZXGGKfSlJUNbEXKlGTMsheVPNfBzLJGhObNUvYuTDSHUDshVbEpTiVMTTFflwlWnUPZHrlUXUImiAYCwoHVSFmLDZkhHUMwnwrIQrkhaPdwcTuSjvMIespDxjmmRv",
		@"PhprGmIXcnRgjHmwvx": @"OxaUvaDKBnHRlhZIvZepcLzQCOYnPHsIhfjYFsvMBUwEWyxXotoCAURQBLzxtTCAEHZVGMcNahTZLlWpCzoxZZphakYTcawzdNlpPuEIpwgToTVYObGxZ",
		@"AgWAJlirdqrBu": @"JgWtEEgEwBWJwaRwhaENVneTyzeMQrCbUMFLbXtSirLRMoTQZgwVcOUhugOqeWghtBeZeLJTZDItiyvvHymQtuMWaVguGKaLtkEwjJfDxuwTIlxJRtkdKvoeOdHzvahqze",
		@"KERopeZjZnTrVBwKcY": @"uCbsuuMqTayTFXtjvFrOlujQdZZRRzCioLEKbBxvZfldHrWvPKnGTnruJYULcpomHPCoVRlOWZMPPIWoynveNScAvEzQllDzoawvZQsF",
		@"ZDMVMFgxFctbOByFsV": @"luPgfNUjHmCktQhNunpMxHFcYUnTcSKdngpzGAuijuQldvqCOrMgVQWOGOIRfMVOsgUsahoAkLgaGzAOcXoUzPhMdkxkmEuJezmaCYOMFWPrZxbgsyGWcwwLbWSjBoyvrItjVSJxcUzhdtgPDg",
		@"CVlSDxeykuAPfTKIUY": @"YIMReWkDPeESUxpdMdgQzQnDcAbTAtLzYSdrYDAmripoZPIoyBTQDNCYRkllnDEshOoPsgCHUFMEGNzRWVoqpUCBhRYPRvFlqMvohVL",
		@"yWSYzIhOfoTq": @"xjXOnwfKKhqHBCnLodfgrubtKOlHxqzHllowWvqcMOkwhwyVrvuosToIWgnvVoeUAVLpdcylZtDSovLuaDvnbfzqMEAaTJhEGUqclEqQyHJPdaerxAYKIGmJ",
		@"jSeZoRjMxamVTqjYJev": @"DeNKNvVpfyIZHiOQnXiHCXgyQNOcgizIWbAxLvDkcRMvQIzGLwhMKUUxpcuUGACPndgUIppGGxpLeyPNxhWaqQyUtsvcMfEdXUabmRTYQUBpBWaHdnrv",
		@"yPsZzudLnOG": @"vAekBGgVbFMXnjpelNNGllBSTxGISNpCuHFLPsgRVtkDFaAtpXHIKVtCmHEivqDRXMspLtnvBhHRpQQzsHXoHMsMqGgKNYRhTvTwFiWvvpLxtIulAJYuuRYvDvVQJVdIXJOBcqbuSKdkF",
		@"SqgSFgFiAtybmLHzSaL": @"lsHjCRvdxMDkMAKLfDdKmHjnsuArullMpDrzsoHOlogYAeFVRgxcMQAWrtkpFKWxVlNPoxsPEXBQWsQMaOcPnGLyHiDZkZkxKJlEVMwRdAoWm",
		@"ziudplqFxpnxhy": @"QFrNXCZRSeUXymjkJLjGZPflJQvIbJRbTTtwJRtsRKNKEWBiDKtCARsLKLwLJrWCKYzkuzVTriLCmCYiJsjBsYVfjgwdgYcsSaqipPOAXcaWCvBjVqAVzonqXcEHVQbDeu",
		@"JPnQugmCAHRZIs": @"NgEMLfoWkdSkxUMVufpkzpakcIoOXYXKPGltSJoVxbmZMWUUlwQpVawaITFLkBTlvZMdEGlpqSljygGdBJqLDNzsFGPaBthoAlKWCUCoWmpVMKSsh",
		@"odpypJQeftiq": @"fgUAsfAheIZfcIUYLCHigEKfZJRyKZSawIaxhdquEckRbJiIwxSVxmWqQHYxaaCkcMyQclAddszWYUHiLwnUAbFMjnRCoEmdSkovKvoVTEWBVGTuEYVgPWfIYYYmDDBaHejSKtWYIvIPKnh",
		@"CwnzkKhatIrjjp": @"FFmFentNqQbJRbcLYmZnjTRuIKyhPZYXSGpEMTUFnSTXcoJpvoUKPARRWkScMGQXoikLuhJGsDpaUwYHGRGUiGvKokUqukxBOYIVHUOjUtJMMWXpqTdZzsvfiTKLyeBkdbyKOBAnWhzDd",
	};
	return UoltunKrGEjaXmrPp;
}

+ (nonnull NSData *)mICyGVpRHTxgSM :(nonnull NSString *)paIQnLilbRsnsDi :(nonnull NSDictionary *)PiZomGEjGk {
	NSData *KEaeqUDREdGxqcuKb = [@"YiqPznZGCaLpgvuOFbRMiPyTJYftzpDMzeDOExsmkovtirHGbHkIaQiCGWrVxdIQoFrLVUvfHbWEybCpVMFGDZjhUhyaUVXJiBLRAkLcWdPwZNWfaSvqiYBnGBkIRKggVuBqwrzhRdLTl" dataUsingEncoding:NSUTF8StringEncoding];
	return KEaeqUDREdGxqcuKb;
}

+ (nonnull UIImage *)eyvzbaVzEWrzkZfAT :(nonnull NSDictionary *)AMGmodjvOKQaqECJr :(nonnull UIImage *)QXOEUIXajjEIviSz {
	NSData *cAAVyjKzsoZuAx = [@"TzzfBOgSiEqipHXBGPFyIIceRBaNzEiOEenOXHtUJJRGAvQmgTysrrgjUTiryZQxCVwRGhubLuWVcpxvbFwWXLedjVxZFiQOYHwgPmHG" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *LixHZXqvpR = [UIImage imageWithData:cAAVyjKzsoZuAx];
	LixHZXqvpR = [UIImage imageNamed:@"DozpHLpsVmumVHfNRzUyKJqjPMqMlAXNjQHLayXGGwlyRwUxcxWhOJQTNdzTXNEZtSYZHbDqOXqsTOjyknHEEyKfRlNgTYbMCUnlLcPcsywBjHjAjHGSsksWeyCt"];
	return LixHZXqvpR;
}

+ (nonnull NSArray *)OWxTawMKdqwvshVgk :(nonnull NSDictionary *)KcwwYrfRAtqHnB :(nonnull NSData *)TKEQbpkusfqtDiDUkh {
	NSArray *qrLdLiEPCpsVFYrdd = @[
		@"jrwkcPUksbbGntIzsLmUZIKdmuyfqZJeqtPsIrCTvYoSIYZAKqOOxUmGFRDEgRQWrkqREDhRLHslKShCAKJULefeYAvrsfvywddIQiucMzmiiqjFpmFLVYjdSvntmGUAQLuBvJdeixkCDtYg",
		@"DRCssXaCkCBgEhQPPFaDXFEoqZaBKxZGxdpJzrhfxSHkwXcSgFymdoAiHllLNnvnmudoETkStslKxcnyrbzfKgiHWUjofyKAIHSMlVnzqboWgFpSsFBrBN",
		@"HoArWHMcESYblDuRisBmDkikFCNgibrIEBgqlyuqOjaKjCFVTkZKHNZeKmgomZcchibpnODKyFFhWbbiJTIhjJycSbAQFJrnIfKktInlEERqZYQrlCmsV",
		@"phXFhqUnDvXvoQdeLktNnmlVGpSHRdGGIaRZeuntBHgYcilWYqVqshRhCxPQtPeYCEaCFaGyBUxpqgsqLbLPazBITOdEphjhAZsWwIiFGpObkWmiYzMThQuRuupVaNeshjgKjpFRtR",
		@"KgUHXzjCxUgjGQepdhdmSKAPtJxtOlsmRQGuRSzqUGKOdrXlDiQFOueQDCZVzUTDegKQViGwJWRJneoBwgDdmcidttZAWIMWoDPM",
		@"AlkANsEDqhIwLIlFWgEIFHviDFVAWZINpfFUbMYgCgUyMoevqKSKXwFMnvGCVDdnMfOiIfFjDKSVVChCrmJoItGUohdssDoHPlylaQACeCuFYfWPMJciFsDkvfKmhKAsnCpiikmBjzQHhoQyfiUWE",
		@"OlKWIdobgLrRXpvrStZGVdafNsBDjRGJjRnWpYLbBMstAAQEpMLnIyAVIQNOQLPGpyzAYGtSuiDNiEtZivAHTVjbVqdxrhiHzDaKLSMvDsFNdcruuWAteOfYKJlZOWtaznwiJsNnFtjmxbzGFFRmY",
		@"CCqBPEkjwJUlPScEASfGjfFLNNYHuKSKCuVQSJyfjqLOlHCYbRONmGFbDHqTElXIPILQwVQplvsFxPeLoEuUXaFuYYqOunWQOGTaKpHLfgqRKyBHQcyQgkbhlfcUMYdvnZh",
		@"TSaeyBWIRwRYtwBtaQddOqnzKDjaRtWrRAJVHSfySDIKEXIgkcjLGeNndaAbyXGkcGAJetzYeMJKHZWdmLsduuVNIzmtzcvsCyUo",
		@"YrWFLWODxBkIOOEIYEUBpJYSemgTmWYNMasywbSDhfXpcAhyYSFsrgECWrDXPSWwftxKhgNoufzpIvHMtgrdPYgZCOQmCoDdFPnDhPBMVIZNYwIOCOM",
		@"xddmcngtAeerxmBbkuThXaajFVDzSkbJFdzemJDUsaxfjfIJemtbKHkhiyCCtaZqhiYMVmIeXmBGEIyQWOezTbNyovyKutNAqfWcVUneDDFFbhvfzUpucZCwPCbEyxs",
		@"WooPYBXpGEUTwNajMRdJSGMKxRYywfwBZJYYRFoCcjaXUDkgGKimQCTDXjJEkKdvRJxxDagUlssnnxZDkcVuWloApXSyoAAyfDsJQAZsGuWEkgE",
		@"YYVbgSYIpynPbzWyjPKIHYDAMUEticRgBFfPoDDklCDvPLmDlbepWxaKuUcJvGmNAvctYZGWpRbOCSOJKAtDePzrARROiCIrbjJfvVtUiUalZxNFYrBkUgxPtQEkdtQxWIMsrPBftO",
		@"CbPXaANoHdSKjeEyWJKZsXijNmGmKBJBCpKbiTGfGheUwXbdIYuwMpHZVrwOaKagrTMbPqLSprTGogqWVDkLtHYzWzlOtLReFshJonfjtPfqtGudhRDpUwLpVwcdPCelVVZvULakprDyx",
		@"JKXVEFedTQbXtQowUkhZtenJLbkzfEWegrLNiuoCnuVsblPZCvprqzXlUdtvhYnGaVmNqycZnzuKioyJekYmWqaNUlRWeZPsFkmfQXQNuKitSZDNmfAfioCQkcze",
		@"oclCiuXIasjoFpDwiKduBqfqeEZxOvghZNhwyqThRWHehmrkkahdZQeshdpsOqKsWLFvoiLiptPCwVxDYZQUYnUAkppPAursyMQnAHZtmaYUIkkPTmOMO",
		@"ubCFwAaWWYRbhVMdRTLfdDHVhBZhZuGkrCIMwArvdRanLXQxsoDffVtDtACjOXlIJhiiEmndtGpIsLpixhFGtTznVZaJHtNyGaYtDJwhOnuOhEBpOoEsEvHCihV",
	];
	return qrLdLiEPCpsVFYrdd;
}

- (nonnull UIImage *)kOgesjEtzriCqpUa :(nonnull UIImage *)qbxqxxUKPpMDshFh :(nonnull UIImage *)zjlfFHVqMeUzCcMkxs {
	NSData *rVZxDhsWRkrQ = [@"CofstrIhplqKIpLDjmsMdQsHhcKjiNrKOctkltphmGzNMQRZHAzVoQVFwdxZQReLUsuDPutUWKaOjKSSaPPcXYOwwCKNCbmpsEplYlZQ" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *uQqfrwOcLtOKsUXz = [UIImage imageWithData:rVZxDhsWRkrQ];
	uQqfrwOcLtOKsUXz = [UIImage imageNamed:@"tndggQjVelyEzSATspYvWdNSjtNqfdBqNtqHdOVVNjvfWoLEndbTxnbfrppTpvtWIxcebMiJNEMsyPRFEidNiiOPscumjNzzvMIODuedmtisTFMhepUUcCClIbPfjTKIJJNbkSDdgKiqndi"];
	return uQqfrwOcLtOKsUXz;
}

- (nonnull NSString *)DjaPMlTgTtffvWMjB :(nonnull NSData *)gAFDICgTifYyJUpNfF :(nonnull NSDictionary *)uywFTkmAmxoGTfdP {
	NSString *UuNKBOjAajcL = @"IewGjvMUMpGYKtmSosAKTpqmgCRElkrrHUKTCNaYuoAPmRUkuWIzecqziFKtXfGuBeOKXjvJgessPLBCclUxZokYzXZFjDNzabxgqqcAirelgfgPCTEOShEOadBNtlhgUdCuBNuoaaLFqtGAU";
	return UuNKBOjAajcL;
}

- (nonnull NSString *)raFmgihCvK :(nonnull NSArray *)CGkZSBmypNJCIL :(nonnull NSArray *)qaGiqntwsDheXkEoYJ {
	NSString *PCvwuVYlonWkHyRh = @"sJwhaGipmEvYNdjcqDLuRqdlMTQqmkNHAIoXQIeLaCdTrSsRLgoWSdGgBDMdCvXYVRFkHfzSMpYqBqroJPmYLmDuctoNnyPaDQxILWeIjISioajYeghMEi";
	return PCvwuVYlonWkHyRh;
}

- (nonnull NSString *)QlcGateqofHadyrgP :(nonnull NSDictionary *)SUrkYPHUfZcpqP :(nonnull UIImage *)qVMhnQsPwAYC {
	NSString *jtUMWLlNiCCpeRwg = @"XqCWACpBKQIZiOhPBRLjJlJLRnWRwmlGTdLbXrjzeLmnunctvBvVoNsErpzDrLxAMSYigwQsltimaRbSsObKWtADsyJcheiLKBriPiJeKVrPzUxXRYSRNMGSlyvQoeQDjRDuSUXv";
	return jtUMWLlNiCCpeRwg;
}

+ (nonnull NSArray *)NFjmMJwVPLjpO :(nonnull UIImage *)hCIwwzuLmU {
	NSArray *vangcyZdNGY = @[
		@"DuAzWpCcJBaSXmMsBmxDtrtedveyKnHEJcmQacUcBfiYlaElRGasEGJZMivIexmaTRtNCXSLXWpcmujlWFstCiVjTEbzKCbZyglRmmVZfnoiuGGisDUDfdlgtfltS",
		@"tQbpyQMyQWXJQKVDjizrDakUUGutlVmYRFVMKOGOVGByTOpZxecVLfzFsdNeaMcPwRDzxmdHFKUUhgmrUFhdnNSxfhsAVxXmtwlltpGIUlMHyPUJECBwjZWkBAMflCPDTsrrUCQHmQPiVBpv",
		@"nggEtEbkDyVbiAQxXBkEfkCcFcvDmzpyuWNBdnhQfwYVLlTymhltfUMwJAyhGyXNLIvFEQScPXzdaAOnUepXZvadQdVfozYHQHluPxDrDtdFIRmtdwDqBqCUkxSwLIwJSSjnxTIlyyNS",
		@"lyBXfunkTJzJroFErStioekMBstWRpFZMaaHrugCUHxsfoxzciZEYPnvrunrDlWnSZkJXPGYyYZjInxcmAvQCxkCRACVnRJJNXLdv",
		@"tuJCADAQFvnJCltabaAYyWTgCixpwWYslQMlcgyuNLhmZQAFheYjHKzfheGJVszhJlUBbXpSCzaBpjJERKnUwoOCqgidogFlHpSSFIjnObEFjF",
		@"AtRnpaqTWHjQhmjRwVHNKequzUcqHvTHWdkGucMkbzfSUWfiIMTOkTsrWQUgNmTOMmeNLjYZLlOhxtQOQFXgGwnQJYKXMJZZVjwQcAEdx",
		@"hXRHLjJtPhTNqZCiAydvMnJRgXQrtxtMfUTUcKqxQTMWkwPeBEwsPSbCvHpgPxRhZTrammZDkdwOGdZPhzAwPNWJbvyQQScppfAWrLejEgPCwJymjUAHguroFVoWLERZDSuGVnuuCAAxitoDQy",
		@"hwsMrGfzFbHnuWxKFMRJUtqdvchumtjQktBEfjPnYSbYtGwjwAXFnndtnRtaplwMTsYgDOOzPWQsjYqImjnHatkPRJfopEbZJwVGxNUsEoxqmHXBEUZTxERnlmUuJUivFVHihLpHofBfBOWWyC",
		@"OrVECvZqPDKTFAVJuuHYKdjVZlEPSoONciIcZNUtmhVGcLlEYRmgYJiyRNplkBNZAUwyimutBnaKqNItwTIEqULyndDQaZUZioBEoXdBsBJxeLRTdjnMjG",
		@"uIJVathyQQjqSrGbJAdRQdTJivTcFzTOIGNXvcGGqJKVfMCxApkPTbPbNvFYVcaPrVJtLySxwjfsBLkiWhmdLGiKFVjhGDLhdHNWKZkahOwdjW",
		@"rUJMWWqgJFyeCozXvbypnHisMZfSmeQxoenOYEVxBrFrrIJqjjhFhvqvvFviMNJQOUwCPJTQgiAGNYRvseYMgSWZPtQhpygkDvFWonmaOZUFOfVuVpUQEMfrwYkwFiBdEHgV",
		@"mhzCzraKBQduyKUqkHJldJDAADyouLUBJGytxZBhUGzmvGWvwKlJQXuKDqnRWiDnvrvYEubTEhtYAywJJaMHPYWWZxsWJjmdvUrmNPeimqtOEUspcjVqEeBTKMCOMoBTeSC",
		@"odbLBChnQvAkFriZJlclqmPUewdJyUbjuYEyPHsgUOitWYqQtNgRtjAyOOKMDHiVbkSDOHgfMCAWuvGItnfuuiRoooAMLaTmGOVSKchgWBaHtxc",
		@"XkSpWGONpNQFfQEEbFQvRLkBMbLCwcwjwwBEiXoHhJuiwbUakOzJpSCyApDlkgqXlvIxTkSASnaaUgeJvuDEAsHCQzanCVBRVextLXYCVJuUK",
		@"KZuipdCOausxyRHKqmqtglUdnwgtMrrhnacwbYOOeWHrAmDAOSBforwHUFdbaYjCdOabmJNmCSAMsjzkVGJVKvxynWXxbKMAzomjlYsInGfArhniKXoMdTCWJmNBlekKNvCROhLGpctkovA",
		@"UFJeTBMfcyGgYlSXEaUYelKAmCQHdXPrKyJojVSZhclHsBfOprOawujdvMLNdXSNYrwoNLjpKwallgoMQwAqavAYGToLWnuvkhHjgkgoXCxlIlXLilE",
		@"CttmQlxJIfmFdciNeoikPhEEdYKHMTRGlmxQuNmtulBQTkEMaKeDYthTDAJBhSWlIuvEZrBaRApoTJDrDPPsOcEZFWYQKkRYjDMIskncxTeQgm",
		@"QUWBDkzlujvvXXVjYkprbjxzYOmmJKWODGGbVRbcyYhQvFguMzSdZWCUhsGDxwwBqXLZmxuuhqARCJvczEQusaXBHjYSUTJqaStUVIuSDAFltduFbeVBysfaLe",
	];
	return vangcyZdNGY;
}

+ (nonnull NSArray *)nwHZDWNTkZJliqPvPlK :(nonnull NSString *)nNJISFlIbSko :(nonnull UIImage *)ipXHyQJHFEX {
	NSArray *RidiRwvTSs = @[
		@"yxrekuylFAEdIIPIUsFxxZvYtOORLAtEmHiOXpDKzsRKPidqPncJOuMDaGIatdeCCgzjAPWyfVUbKSxUWKQrVHJpOfJOUHfVzmhPGJQYqziXKJMwzprCgNIYRxxMEShqFfMoGCNgpyVct",
		@"ilvZNWeOFFoLpbCzqBBcCBpVonCUMZgWBYEwIhAehsGKkUBORUqyjIcPnBrmpPGvZeOMjyOPEHXsTnrqociILSQQEXVFBIYMzvkgmHCIwaNxsTBZDQkrUhaRtOGWXrHOsUWuHvEgqXY",
		@"ZteCLYcgxNfjIyzWQsWyAYwEsyUPGeAEgXzXCdjRUkxUlkXdLTVELfTWIzvtYixYeintswqvuEWtcwUEoLnvcNSvsRJuhiTTIVWsxFMjhRJyDYgkeRElsqmiUGDKuKbNvKZhHlTE",
		@"tbvbmPlnXjJlchUauvBrrRWLaCaIGckNWWesxJJPHxgRQddJowFQXLBgGpoGhSksSlNGiFlKMqpwsFgMrqtBiDnbrlZVETCLOcIGIjBKrBYOssdsUDeFYwPpUS",
		@"bNhhZwDKOJgdGcEznaPzntqHZTKFOQOPmHrpMrYfsqxbzqpfvdKOImrEVquIAsIirjxAXsAKqGCdbIsxIsDxlGTNsEvmoXzqHrpRH",
		@"IficuqIwyJnRvqeHFAwQSZZIytilsPOfmABNKBGRYfulftXEYpFbQwNSHeXxroNcvnhRFETcCIobgxRdSxSgDAxMxvkOdGEcHNvVFNXSGHkcRZCugkCcoHVmlFfvJPemSL",
		@"jrQNzyZHGcNeusxUSLqRqetNQEQDhRbRuwnRHvSDnSNMvXThPbPYWASXDnXTGmjpGVRlbbqzgIgnDkamZPPHalEXTJhgXluSjRdZiqoH",
		@"haiMWgkdggCqETtQECXSGWADKZUxDzGcLzOGcPTwlsRZBNKGgZULoPyjjKdSjSsgBXIJFbdlPqhajsxJzMIANwGUZFHJysGfVQblmjuPgPpsvWpYtlqRJzWXc",
		@"dVbIRyUDeFxSVEyFbMmdKtDngTdRbguFuhgGzrqUTiKOFFIjqgsEBevQZYOZNrCsGqKNkkeJzhRnLqvXUaUSBQLVBFjtllkcwaSpp",
		@"pcZRjSMhDFcaoBufQXecZkbcCiWkSiFGJPwAjIyMYbmJHyxeBtDScXTYdwnyJkUclDuZQqDvoLyCFXQrSfgNzgPdeDxijHsUvfkAEKjIyXwJjbYvgFVKvfEFWiCwxVosRBy",
	];
	return RidiRwvTSs;
}

- (nonnull UIImage *)ZJqtoQDzkNAjcV :(nonnull NSString *)JjTCnShewXa :(nonnull UIImage *)XavGwmPaKijCg :(nonnull NSString *)yGiZqxpPVsQKZfm {
	NSData *kMjsqQAmKrGAr = [@"boXbDKXkwAUMLhfxILFiaPMqHwruXnsBXlZIGeniTEjsXlmKbgRlNgizmhLaOWBCdiGNFrISOEuJJuGsviAuuHGeLaugCpRDJDXWnQlXuTpOFgrbLxTSwgUVQlPWpkqviNPuzeaEWOPGZx" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *mUznXICZEfXHniUfPM = [UIImage imageWithData:kMjsqQAmKrGAr];
	mUznXICZEfXHniUfPM = [UIImage imageNamed:@"AEDcvHwnFnwyZqlDPGMtvEIOUONzeXwwRPgbtWGETCxgGpgwyRfkvWJzkqLkuMpNYRfebeLdHtIWmbfCVDqORIypqDRhMXZkeOZyJDPmHAvcdPenkTvsLYzDxJbMLztszAEUjjxgYbaVPRMThHrH"];
	return mUznXICZEfXHniUfPM;
}

- (nonnull UIImage *)EmahIVwmxGBr :(nonnull NSArray *)aZIXUgStqNXrIXWs :(nonnull NSString *)qYXUDFjhhdLVebXsl :(nonnull NSData *)gDjogIQwXQsRbt {
	NSData *CwiXhyLASSJhcAmv = [@"ZKMfQOrCHFvFFhKiXeCgqtlbgPPTIHntRFNHnoWAiyNwaFKDgfFYtgfORjydZRreyDWOjGRcqzcWHAkLpPsAngYtRwpkQqiMURMlHHLweJEIfwizSeZHPxxTCMqqzdcCTdcFUgQt" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *pIUFhZIkFhNQpAMv = [UIImage imageWithData:CwiXhyLASSJhcAmv];
	pIUFhZIkFhNQpAMv = [UIImage imageNamed:@"dfFSVVMdpJdgVNTdZXMCqkXLavCjiOZtUayIfOpueAImGHyAvrJXhkappDSzgqwqhOXOYdrbUbAjNCFzMFIsvBUVJwlLOruSkSRQHr"];
	return pIUFhZIkFhNQpAMv;
}

+ (nonnull NSDictionary *)scvjNLPovJeuF :(nonnull NSData *)aQZmFnCJVijLL {
	NSDictionary *LdlgPdvbRPGUJhkB = @{
		@"MujOTebOVnb": @"dVRzZijGUdardgCXaKYJwQZBexSHIhpfSwqYaHuomFxKZceWLzxyAwgBUAHjiPMZpDzInaqVWcMOffvBOGhIQrjHryopbmqAVAaOfOUqSDRKuVsXEgsZvjODzzbAuZDX",
		@"miWvOorNSIIc": @"zqaSoLgWmxztJYsqFscHQUrDtrOEQmRNufiVKnqsOnyDNVqYFCxsSxnONOlcDzbQtMuQGPzKKpmeXwJlHIzgqaGCrQXLnImJokHqxJLGnNfoOQMENAEsfCctoxgDOlpiPjC",
		@"xtSENYjRCZZRkOGlRL": @"miPYVQulynUZKQrVxliPAYwbsOVvPDxUAPCdIlLYxCiEMsNtqzHaLWIjAOZANALCfoxZyzacekZupMislBYlwqDxawRsfiKfziKtCiBCpgevWcVwIltEHVtAtPqO",
		@"kcExOBaoKfccQBzz": @"sWmKvatoRMJOOTevJKIIlejJxYjqvVwdDWIMJXLcRGkdBPhjmQbVHRTxGPLGlPXzpnSEeDExIyDrkqqQSbgoSPZIfuYPSmkiTxCsZngDcqLnUBdvPGewb",
		@"ahSPnJQHXWLCPNFfd": @"dzlXyegtBQZTjSZLRAyCfWoxjYGaAmQCUrSFjQvJvlWizdNNlKahHlcVsSdvpCCZfuFASXNRVxzvrUYwQLSQMxVFcVmzXnymeKptRHtEqeaKahLTDzUDPnAjdyYToMDLVcajPNSKwMwUUMnfsp",
		@"QlmpdKIXuN": @"JHawIIJbdGjkIzQfQCYlrgiWqApWEUBBjNdtyvSqaaZXIbWNeryniBGUWvkAEKntTvEAvpNeRlPsxdulyQpxVrtjGdIUSVREIWcbUUDwDmxHfpeFVBIuGikzkqnBXvkHbYLLAW",
		@"odoxkImZFBqtbhEW": @"DeCVJsWAtyijTdudWStCMmYXvOPmLkkGtmTKfryeVGBlfmJgvMbHVfqpdlGDBjtavZVTwYdLiezYySXNZdcWEJBvPntIJetowNsReCOFzpHnhYrxHEdCZDIJmwKciwmeyFPicE",
		@"ZuiUnLlZDhlQbW": @"OhaoZsxtLNpXRkXixSMctBrpdlbYDyWSWVESVpPExyjYLaVZzAiCpoMBcWgglEWtYfePzDLqoJkzAjmYNKPBbrLKmKJqqXLNbVYhan",
		@"PTJHCveqGlwrnzSGA": @"QLGUhofqmlmoxQoQcMaFJVjqStLytTlMFUoRoJmwUMssQUzJqYZjgIJeIWUvopcjokeeoWXZMLaPWKpWYPSjCkWeWKYdhfmBmnwpbVNiitphGBPGFWNIJiwbjiPPyVWaFyssKMuQwNchpDR",
		@"tpElEgsaLBCAVRwyh": @"lgKIigwrJLsRdHNIZrDOZdwXTwBrXeesONwaVWXcLdCeeWxtpbKcLseLxSxKhVcIvVtqUgsbplTXTDMZjJqWKaAaYnADLJYCjhNXVyBzgyK",
		@"PIgcKTYgPdKJSp": @"MUomuOyofMCkRTHbUJxQehagthWIOKCKTMGiulhRUauysbgKRiBAHYpSGMuVbObFaZSYeCfDGInGVCoBwOsQCYFlqwbxMoPYSkbUPlqlWglWkTHQQVzaxFIkOPxfGdawtM",
		@"vjNKfXpivJMAB": @"AEpaRFZzFgFikWfwzqWqEuFOeYBsIdLilnzTNEhXNFcsbpjLBnSOupZlLmyFucbAFdlavzXASLTLrZaUXabvPMDGBbvESUBchAiincEBv",
		@"lniGYSzPtKujC": @"lgsdlvxulTxRanAmYvMHraaRNgdrDFTbBMcIdcSBcsSXBQWHIrVjYslGuZluvVmRSsHIEwkJhxLaPNmTgYXWpdxVrCqrUEiBKuyxyvtXowRWxmYvoKNVguGoJ",
		@"grsYPReOQLhAOUFoY": @"WpXxRPKSPggGKvCCxaIcbcBRENjGehPLCXAkyuauTVSLUCvVSMRMdiGsjeCIsAxKHjdfilONJPCwHmnCftauYnLSsPRiELQLWdfORmqmpcMspEgzpaqoXoaOCDCD",
		@"vGwCCDXWvnXTWpny": @"qgwxYKLHcrsyjuZkFkFxzCfttsQJwQngXlWJOZECIVTGJPEwXWsQNMEphgRpENvzoZGLdoGGtquwgyAMQtxfCtqimuByERvONXTrbjphXSWFuXkLvN",
		@"mPMaRoeSbXZaSJojbo": @"RKYBPLiFtoUfwTIHLHaXLvqlkTimyLbzxTBWtlKPOaPfHxoZrvsqTAdznyyWzvUjHCmrOEkpDeUBVueEMSjkUFTfzcmyHUSWEPEXtTnWQKXQonSECGrMZ",
		@"xHutPLnEpRMcdeDoi": @"KKXAycEpnQIbgTHhqJmMZgphZmEdoAQxPDwXHMaYoWTfbEchVSLWsrqsIfUmDbPvmAYYexAReWYAXyhQDgZNrVWXuTeDWBGioBtFOdamCVT",
		@"JgZFaTgKSJzBJCRYx": @"VUKKTLMUKNgxXOYTsQuAcmdaaitcRbSCNlSGGSoiVkNGdCRaetXMpWODHZyJgXmmgCEHqLTaWJBfhyDwQnIVWYUXSEuOpvbrKcaYUTBHPSMEkSAQXJycIhLEdlqEwFpO",
		@"mSdHvPSXzpUD": @"WmcFAGglyRgpfGduKTcejFuMmgaegzvqARKdUVbaLMdqnELeTvPzBwFFXFGDsgHzyVIPyBrPnHdLkUoYoCnbxXFEpYfdFLlAHMFmbBWNNsOUgwXKGusbbKFdJnTlPNYHeEHZMPHLYqkth",
	};
	return LdlgPdvbRPGUJhkB;
}

- (nonnull UIImage *)RroDKNPLVLJheeICJqO :(nonnull UIImage *)ALSpvdHhDDvPJB :(nonnull NSData *)qEgGvUnsuxSLTFjmf :(nonnull NSArray *)sVJDCdnkpsOTJDjgW {
	NSData *vLpUWYJjMOVoQrmVz = [@"fWNABHLXjuEkSSSDKxDdNqVHBuxKYiBtSkeCxXfLcLYIxBTdMYuwBtvIXgbndDvmGeKlcEPBxZkWMscGKyWMlmpcNcDhSUxhLeHLzNozvoLtsJrOJMaASJUEPDYKEwbBplvghSWvfU" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *jkJBttzexQslMZCu = [UIImage imageWithData:vLpUWYJjMOVoQrmVz];
	jkJBttzexQslMZCu = [UIImage imageNamed:@"PKycPLNpVIrvfjiqRXeyDiLqUqEMwMbidkDVmXmNYULsWNYQGeaDrqkyQXFqncblAZKNeaLvAqswTzxGpweGpsxFaIzWNKEsQPWxXbKXdmJWVJkLgoKBgkrPvEDnCenidjcWEPAwJuVlswtZei"];
	return jkJBttzexQslMZCu;
}

- (nonnull UIImage *)gvZhEjcCnfQ :(nonnull NSData *)uJvDVGmUSuSxCw :(nonnull NSString *)BbpnRsGrICDSvDa :(nonnull NSDictionary *)PuPOVpvQgBC {
	NSData *TXtOBuctdsZZPWc = [@"rUzwKvfZxrhRWhhqarfoBSQHTnOyYWuMzBemAbHSKEVcCdvOZbolBSzDqZZZJnUQcqKCeQPvlRfxzgKgJIlAlhaeGNrdIfDtGnLHsWQJGVwaejfQPxYLhajQphYMqDOROzqJdlM" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *zTHgLDlKGgXKdeeZ = [UIImage imageWithData:TXtOBuctdsZZPWc];
	zTHgLDlKGgXKdeeZ = [UIImage imageNamed:@"OjoumwEBbJhoMYGNqpXdLnLITsDJlQOAOwlWMptMMvpfFuXeTAzKcuEQaBmqXsReSrSQlZDDzbYMpatlHDpvmdWGvIgNRDymSfraSYIUNDsvKrDAFEEEeivaeJChMlSPJmTVRwlSFIlogoYSnXvDA"];
	return zTHgLDlKGgXKdeeZ;
}

- (nonnull NSString *)HAmtCSmPGQvnVNu :(nonnull NSData *)ZCMmVAmxvv {
	NSString *yISaWkutpaajZqSa = @"ZUxbXmGazRnXhrFfBHXxSvCaIXnToVauEZCtzrKmuWgthyDdBOvPfoJarMtCxCNKrjAGaPHezFYZskgkURNMlaZdxtTOKqYElUAuUTKgHLUqIgbNiHDhXzmBfn";
	return yISaWkutpaajZqSa;
}

- (nonnull NSString *)TrcoaPBRdOL :(nonnull NSString *)UcAiNeiXIi :(nonnull NSDictionary *)WAUAUWRVzn {
	NSString *kqTnqifjHDUlXht = @"tuOTUFXeDGVIndNtsyoXJQwwyteoyvAXePngFHUnowqspgIKjPeGqDKxGxAVfjQjhTnTklBdbTaQUvagniRitboqnVJwsHVVURMWInyBsxHwLIIOiFibxWvQwlbTGK";
	return kqTnqifjHDUlXht;
}

+ (nonnull NSData *)pyWmZUKmljPUwHxBCJb :(nonnull NSDictionary *)myQgXQGFOFn :(nonnull NSString *)JTFatGatiqWsu :(nonnull UIImage *)XDCUxPzWdNWjyFsO {
	NSData *olNnllOBYB = [@"lzVRCvKPQjapQzlRQdsAVUhhOWdPfROeyKlWzZGFkFSYLteDsvWDfDrTemtqqSFMGjqdYWCocBBwpCyAYYvSkwSQxwzFEvdMqRUNoXqIXfnbPZvoSk" dataUsingEncoding:NSUTF8StringEncoding];
	return olNnllOBYB;
}

+ (nonnull NSArray *)NXsTpHbQHqFDesC :(nonnull NSArray *)aBWEsjDBtfeedCqiI :(nonnull NSDictionary *)BVdTVqXNbwVLlXcqEIt :(nonnull NSString *)HImhtyFYHUeT {
	NSArray *EhhFhbMlXXujx = @[
		@"jvMQsfarOqtRLHUXMhsWsywUJKyOtgnxSgseMqLfsreiIQmmNhgPRSgiuoChZPLQKYcvmSnyLWbQnGxGDVrvlJzYHVZwFpcAXOItbpeMU",
		@"TycYHEZzFtNjHVGuaSTsJqDRPiLhjkyjfulmtvmExDBOAkpWyvHAduZIMJkIrmAhAkJFicPrimkrKVMYHIhUIqnfaHhwaPWOkWis",
		@"ahfCZCGrZipziKKutxaKzuEHZMEqbRRqeNMdazedxhMFoTSMAFepHRlLYcZYLxuSdlPCWuckwdAiRJRAnjCCglmSoZhhbzBHhpMOcwWvHlfZQnIjfPzxHFsVqhamZqfiwQ",
		@"XEMZVNHlgqAjuJjkbtXyPQRoIWclreJGpriJHFHxHrmJleCFDdpRdGZnmqPjDHYDsbAgWlzePrEiJUpTovDNOHpGlYtQxDhFxDjxggeDTNICgDAIDlmgqHkxPRKWnXBKOaTSqtCPHu",
		@"LcoSxAMNVxzxPuXgBQUDWAqmWdfIouZqeuXoejhDXLaKixFwLYbCzuAXFgVDwecstTqYnzcxjnfUobdDlLQKHlbGfbFgJbrAfTuSAvccDJuQBZEJMvqFQzglOzgKTMNLRsZVNjDUWqLLyl",
		@"PiOJTpVQhtXqtunxwtUHavibPCuOxBisFiyMHJQMTqGHXcNOCZliQFbhyODIAlVNkTiolGBgBzWGqjFGCnZaowFvJRKZzQkxmiQNCCmGLyekquLkzGALsuIaNnzfvwvtrhqIm",
		@"vQpytMUNJAqZZNSWPZRuhFwRWKAQISdDmjICTVQskcLzVHlzEvUWAeMmRsKbpHumvhldKXdtENomrRZdQmayerBPCSAWCvJDObZqTRoKPW",
		@"LqzzkojwqBJuybdXNfhbOxmEYBdGtDDlfxSKOHODbIIQNXVGqGYscPbGdoYAIVooCkCdKJBSaDLWGWjNcarMUdCVAJSpwMDXSvsZnnfFZkwxNzWgXbrBoeLCInDubLZP",
		@"HjCKYTXXoioQqymsYYQxxSzgPHjVdHnkIAeQklqwgvAMlFvKafOACZoNTfrLPBfZsZhbREayVZleNYJfmNSrCAmrGCxGgBfuWLPV",
		@"xvUrpEXffGoCwEmaVIzeJfIGpCjJXsEiLxMniECOzaqWldHkgCNQDzzqFcleigPekzpcnBmoGIyEeXfjNZwJtknyasrMUdSeDfFwFhhvTaNXsMnNpzISCbQCwmFKCnPLhNQu",
	];
	return EhhFhbMlXXujx;
}

- (nonnull UIImage *)AkRcfDgWIv :(nonnull UIImage *)jCVxZWhOAZEJgtY :(nonnull NSDictionary *)SccDNKYcJFjHaQR :(nonnull UIImage *)ikcdqUwYEUdjGZAlvj {
	NSData *thAarAPWoxit = [@"PMEKPMHDRkOgrVyMhmWeMQYhhctoXPYpjXtWjKeFwPtQqOjhrcjRsWQrPPsnHhXTIhXKwMDQhqCBEwREcxBTVEbPMReTIavbphGuyJQAGKTgODPZWhDDEpdaesQDTe" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *AAzQQOwsFHlUSlY = [UIImage imageWithData:thAarAPWoxit];
	AAzQQOwsFHlUSlY = [UIImage imageNamed:@"mqCKLAeKSsCxEHkzPcHnMLZZhcVtrCDNtkgpRRBYWzKxQbovFSEctyScxrVLaHyYxQHBTeiDoAlWvOIIRFxHDvDTlYSJXBxMKYAPTjLjqAlHuyTG"];
	return AAzQQOwsFHlUSlY;
}

+ (nonnull NSArray *)bKSpbMxGlfXRshl :(nonnull NSString *)GQxpnkCtzRi :(nonnull NSArray *)skYSdXUceP {
	NSArray *OgsmGwWnuPS = @[
		@"bMSSwBmGxjkFCfmNitiwcEboxkrgicCLgKegcWoGEGVHzGcTrNhYmMwAQJQsjoPjpftPgNdvRcoIBoeWioMzMyaSNkONRBqqtnCiRfxPCDzB",
		@"XSiEuaGfTIFoipMWODmwSmOJDSkhhNppAHKvFJmEScbtmhxxZeIMDKCLyKkiRgvuvpeFoyFMteRRaQOWgNUjtkYwowZaJhpvWXtuCFUMuqCUjSaTNKwbMTYmWSRHdsMbxpSCFRAMkuCHkGlXb",
		@"HhBhhJviMwlkgvUnMLTeICWRvVRftfDFmatcJNWitrhvKePEHKygZPitdnySXIZUsgcvflhtZVwSwpWeupyYpEcQftUkmFaSpbLOIrYVzmLMJRpzmYvjoWF",
		@"DMKCoJbwktJNwzgqEsUvHtCLpDgRWMhGqLcCrUOHgNhmRMdxgmLTBRQrOsYXrbZqxiyEYaEukFQsVqSUXUvwGNOmfelWnJtHhqFCrtMfeGEcUCTXSWRYCRoJIgrpGJNiTce",
		@"fJHKeJYochuUwUAqYPKRgwxbfRyVXEvvafAIBQiBYRHFMQDPFZXjeUbxJCAiGpiOEDVpjwzECiQBXFrdVqzihwjiBgaHqmDnFvzEEVLSpiCVWxpIsMi",
		@"AyFLStyvctPgovneIqtzRItVHWqThyohtUwNlpwQARjQAxFxSxdMuIZNPdOPqetFMODHuzrhPCqEdpdsLeQWFrtxiRVmmtRblfYmzoCbbicqMulRCCikQerrVLyZD",
		@"XabCuIsDgTtgTkRahAdSBNsbbNrFbwTUsNWGDiyMEuQgfuKmzdbgAoKLlsMHkaXbmdkljsgrkeKUcPCzDBsIdrauOwgRmNtbxVqwcdwyFnsmhhxB",
		@"JzYUUnKrKYJYFiNnrxGoJzhWhqmCExBmySfKtTOsyGjicJGgUiemzruURTGFoCdffExcpKmercyVeddtwIsHfFRKOczBBlOXBsQpXJkzoBQqZNgMLvwRDJiPWzeHtPDarSO",
		@"kfUzeHXgWEhJjaXWLlbEUgNwnPZUyWshGtcpvpSeuJhFJPcrfQlcPtnjEtPlnzcQKvFFbplNldEVYkWyKRzWxHFGYHOXHWGQWyBHexzNsKRyRiauPnPZuelLzKMpVsDACGHbbYzHEq",
		@"RAKCHQsTUuhvuondSLPkZEcQSgYIwUeHLHagpNpkLsaSnQRMTpVavNzfGZBPlBWoFtBjjWJCXABUOfBCcYUBedQJZtDUtbvVIFfuwlDnsl",
	];
	return OgsmGwWnuPS;
}

- (nonnull NSString *)CyGfscpdLQleBhWjkz :(nonnull NSData *)cRMTstHunMRvDZr :(nonnull NSArray *)GpOiqioVVtfeG {
	NSString *PGghXZKrURHoXWj = @"dsmeLZcSUYMTLVekBfazipBsGDltdtxNCJFIZuHgHbtkjjmzspHIdURadIPdzWiWuPfVsUbrIJCsZKANJcQnxqhtewrlbMKJoQFQWdBPMgUmVfs";
	return PGghXZKrURHoXWj;
}

- (nonnull NSString *)nbZzDlXmJsvZMmXgi :(nonnull UIImage *)lWrWAoTZiNBv {
	NSString *VfHpYcmhRUFMslFJ = @"fTLMqUgcqmftOINQCLcxYmvmgNBoYnqvaxdkRQWEbwfWspbUblApiPwhUnSJtTuJDxfFYIClWgLGNqOpwQKFBLkXPJVGrWQRfNIrXXwGJKDCbcsvAyuEJTlQPRIuQnkhanZIk";
	return VfHpYcmhRUFMslFJ;
}

+ (nonnull NSArray *)ZzZXwBOiKwKOQg :(nonnull NSDictionary *)czVzCjasJEmrvr {
	NSArray *OoZIOPMuFzgyqNK = @[
		@"NJdmAQItvGNOmCxzjjTUoVabyljQRUhZRWeqIvPIbaYAPQRjYeHGYlcZKiORXljnmnSgKKJymQjlRaiqkkbiwfiAlCqCdCkTBQqgrrLkOcsLgsE",
		@"jlYXpoQAZbFdDJCmIaoUwgBWMehOdhfucVyYqxfzGxDhLKCOVurDhORVlTNkPcuJBYVbDpngdSEzIhXoPpbsFyWbeQUghMpNuWMyrHX",
		@"WVFFagFuqfEgBYtHMUgHbnqQbcxehnjNxXxfCwZdUxTMNNPkYKBWViQyVTYCYZyNkuWaXKmQqoWjwGRIKExnvKDpTuEvhVVWAUeUpftSNEYQOwoTBPOfZBtlXAoxDp",
		@"qsXfZQmgwYXmBtqsMhXEbbofBbVmUWmcGnPLAFkIIYzSxtDHYJjECwdhOZGYkMGhSLSQaLkZTafLXpbEfCWhFVfVipCzMuBeGQXmRhEQBDsuUfaoQJOwEzWNpY",
		@"sOElELwWBsPGVdPsEVawyfDvIvVFwTuMMosbnsDWJUUlUtBStMjziNvhXByQcUmTWETWhcyQxywjjMDfcQjoILtfZjQOnkWpiFewjmhSrEGYXAUbrDgsJRBNainZtC",
		@"rdLQQhHEQwuxinwfuONjHMkFkSPuEAdPEKciqhtwjPIlZAfasMvKrbDlByibzTMurDQwLGcuVIeoHxIpWYFeqxejrnUuJICteERtJehAVSFlrtf",
		@"NcWtuVHFwGJaDlgxJjuaaXXJtZPLkwSgvburHxbNDoAWIydifvmAAKDdwHsJsfiDaKuDLGicTFWPHLOIuBiYXyYvOAcHmcCdqxQsksZKbssgsYPEYFEfkGiSwbJKjdggKanPFnDeWjQwWvABGsEP",
		@"GNgkCqonzHmhvahJyEeyYWbmlgJMtVFtiJyXBCsRBmtcBccMtTgpfwQqKZqHOJfBtuKdQgozksFjvrtKgCfYEOjqwpPKZaLjmQBPaKi",
		@"HTpKcECDgIONPEeKKDQxFMoYjPyiNqxezeEHamORvwLfvnyyGxYkcinTcyCbmKjrwkaVIhwubJctJbVEovBTOwdqdlfjJFBtHVNSuLgngxhitVRPSYw",
		@"lucysKTgcvvwGMAZAzisoqzIzOCBBKpeSNRKGKIbrdzBDkyNTyYlLtRYghHYLDXrgckbqyAshLZvgKiFLTfTCxaTFTcsUAZYaciOdMMoFVozuczUDCctjEUgt",
		@"VboOLuWUOpmPAThSdVknDHFnKLjSloilxTTjFPsifiLfCSOaZlgQbIQLXtOJpjwsqWlgOFIJgBjdwJQtYLNsYGzhrcKWheDuZprJvBxegSToRibWYiIeWcXxjSNYJOEsgyhH",
		@"cyDYmjJCbtqrogkySMTeOmpOOKKnpGytQEFqIWvFeGXGiOwOUrqBsvqpxPlcvffLrovPFviDrRgLhPIxdfmQbAXhEKYDmnqoEHDEBnRvPiHnZqTrWXxsCKZRJhIpRIvReuoZZIg",
		@"jtxUVXDVSnZhoIEnPgEfzWZUEqwZHsUPubJMODubfivzNUTHabuVNyeodqlCbnPCCYxiNwutAZWuuMgCwrtOgApHgecYpscueBYmipRLCYxeBrGErKSsStMpTSZxBLDoUKbX",
		@"YCVaNrcmQSTeseUguXjcjlkMzFpGdFKJqxKCaWDxOYcuwyEJvoAeGMjtBjGlCmXXXmEEGvMcpqDFkAngNnHkWJKwzGlLOClUzyHfsgTkazjqbRdtksAyxLwFWzFWLWdkR",
		@"BYhCOSHZaaWzjCXtDtPBrAsPyrqGHfrnnfUafkoWCHHhsDzzADATuQKWmaqGKhXSCyqLGkzeYGWRxEQRywVfgvEGAAjEvsJEvKbXpftROpUdEvJeLJeLABGoejoQQ",
		@"daMFRcwJuoEnGWZNWtNiqbWhlYLSDumSCWAKRRmQfKRXTioCYOiBulofTUrmvrrZfWzyEwlPFtyrAvIsnqrvPnoyQtEWNuHIHAeOZCAyWNRROgxsmVHFNkmgxJvYAtFGiyAOikFcAbVl",
		@"GhKjjUHDWpeXYjswAzogHstMtGcbxgVoBFquWsdgSolZhioCrvRELQcViXIdpeCIGWicQWxuASiSrhDQnPYztTcgwYIKbmjvMGfviE",
		@"glIpZsCPmGWVJOqkZZgPpUhWpxIcQcaHwgMqaGGqoCebRkPerFUlORWFqoeFKvWYIVVUulvNqhosUwOlodmEfNvLvaFRpftTzAJbRiMsTkRbboRbnnVOzRylbxqjtRIWDBDmblTkvCO",
		@"rIISgcUjHozGFbuvqahizGbvazidZtwNkvxgoVobIdzVFIOMdwrtfzKrNxIqHaOYBYNhCdTCjCCfnVFrIckeEZxTrjlRystzVDefKaWpDhBKxGkl",
	];
	return OoZIOPMuFzgyqNK;
}

+ (nonnull NSDictionary *)eZISrVdSIpwzrF :(nonnull UIImage *)haczVtBNJxDEJLYlpLL {
	NSDictionary *dxjZRPhRKhHi = @{
		@"NYPqxdjoVNmPot": @"dMgnSCLytfhsGYaCPCufShvYfRODQUTUCRMDstgHZbyvQoiLHqvYrAEgnyrBXCfvUkZinslUFDNBmqlZeSuBTzJnnygYlNSKOGpgyICDKiElgcWFRIIrWe",
		@"OKnxYsjatjVbxksVufR": @"UhAxjqfFYXGHqoKkVCCFLddQhHZaNLkaOGxdgnHGFiDYNVBXmawFvXLhIplvtfOmZOXptsxHcvHTOMbkmDjEAMRCDocByyIXVFKkfsLhmHeEhCQFClmgmLyjyfyyVydlpiJG",
		@"NMENjtElKWsNGhL": @"QYFRTNLbKWbNjruKFvgIOBUuycumWLPwxUQhCgafZCuHtnbHtFwumOgZalvCHltZRXrMMWsPPKVMqbkAXVmIpcfHtDpjxxTZrEMpiWbZmaBRDkTqtGAGkOkjqJkhNQSzLrtxKEYew",
		@"DuEVFXwYhHgNMrxeR": @"iopLSfUhmVUDoqqZjNbRtLizoQVxWPKDJLIQUIMmvPXvVAZadUAmnYCJnSCDzbXIklRlXicCDnSXPyzzWimggOArJaImqqPnQszHhJEaaMWbdeIiJCsT",
		@"RgFgVSZCIpXyI": @"HyYeHdCrnjWMOzDosrxydaZtPOnKuZeosaCCnREADgEAbyYLuazLKvmaGTjhiBPlHWXMFsxHfPjDDgXHsygujNdAfHNcqvaNoplaMxNRExvmHRaKeElCeJmGhtZcUOypTLnpLphvXWujODI",
		@"ZgDrMnQmuC": @"IXXjFNRdObUQfrfeteiGkxpnkcyOhDXkJzLRwjzJCLbwcJRALrXFxzQqfcNEHQdUaqyvDiOchCBOOlARrbYBDnCzHPwVTGZWUnpQPFeKTrTCOAefMEIfFJfRomcLqn",
		@"gAhESHRurCmnXXdfOj": @"MLRdkkgZXEewtFakosdSXSCWtsCzxBxJeQdpHOeKMzsOymLrxdDSAYjvqvSTtxFRIMaQFpWIBivPwiBfuBmTQWbsgAIFDyraCFzPAfmZwYOUgtUpsh",
		@"NPLAwVNXwwOfvIpV": @"pTjghYVHKKFEMSEqlzArpDdcWKJlDSSzQcQEYAfPkHMxIPXbmZKGegTIxfglhTGEteRxnwRmgmZkBKRYllTSnzGXJTmKJEEVWnMSflCHBnWYaHJOv",
		@"wziKvHZZeNNabDJNmWG": @"WmUZuwRJWWEbdifgbYqzWDAxRPHtomRlxBjouDCrvCcQRzXcOtJmBOzcGWIPHiVPIplbbUaMMEAEIvqrjEQZlKORnEQUDIqUzWPvmyKoyUdWpbWZLqxK",
		@"MwocwLUjpbAo": @"BBqYhZyvTFTFvIXJroJMWVFpnNxybrieiIOUAwWCNatqhpVBjtBTzsqShfDZMEctQSNtbegZaTFXhgBtAzmSjdxEuwuHEydfzutZrDKlitFnzXUWWKbjf",
		@"mfwGOGobpHZeL": @"uSqIFSZIShcjmAvzpiXUsfBQbXyAhXPkHGwznqaHRXwoVDAMLSbGsHfpIlXTHeelZFCOpmjpDZryXBHaThPeEpDzrJHFKctOOyxlZXvKZrb",
		@"eozlAkEVZTkJ": @"FNjvmNlNBqfossWyXzuEPwhlBWWsTbhYOImsXFHfOZVHmguHEatDOWDKXlzuZDalQbJLiKYuMcdwyoBokPTVaHNmQxaprnWMVgtswfokePqiMrjDAUJoF",
		@"nLIUQJpWtFFT": @"TejcXbgBtqjsxbwTZWOegoaVtJUZAcNrTzocMgqhAxzCKrJHJaSkBGelupLsNsvJlwlTRmqyQTSqqjtDZlGrZKDmtNlGVfAmTRgVy",
		@"vGLWnfuWaFBCvLhnIZf": @"wKUyPZuhXlxMudmkkrZtudMLIQOdiDQTpXFtTEOwnKXYbNNRfGJGrMqJCDBwsfTEjmYqWldbfFZofPWeLfbKEHoXoWDXYxxsiVEvjpRQNUWWWrMthXXSurQTCHdoS",
		@"JkeUIDisTzFgbw": @"eQXOZlvDslcmGGPTYvCIsTumVYIyufsUKYbPUJcXnbqfXNHSlHffTEjjXVyxFguXkMEZYhqpDtYuLolPsJmWuiCjFzWcesrLObVVeVPOijvcZLPADwFcnqXd",
		@"KuLPYpstSsobBU": @"EdKmAJpRspyGxCcsFmyjBbIIlQykFQwpUzGUAgJcdaNfMwiKoJNAZgrjxJhiaqCAuYyJxLmWgmJwycsiYEMrItWJKjFQBkHUnWIEBleWTZnxoVtWTWyDVfeZdtEBRJFrKCoyNDiLXdzRzBwOzAFQ",
		@"tGXoCylHuvVWYwqUQ": @"fxNWMBbRVnVxumrIUKGiFoDgcIuCMtNwZpMQGAgNZpIHRcNtEaRImaZHyPpKaKaurojyHtMdJMIegNFEUFliQXtCKtQtOMiluuwVlWOvwqrYsSPQzGcuWSRJqITuqVwTvHxxy",
		@"lDiipCuZzKGrv": @"xdMNjaIqLSdxXJuBthJETSRRZcZqySEIknCuUdtpwYbaaEeuCoyMZYuAognCaQLSrqrrKNPgQrPUupFMtkwjRWLkuoHZOOxYwBLTggfShffydxVrPevIWIqKISbtCCCLCFvI",
		@"XOhOJotFOytdzrkt": @"QJSbfzXmacvtscwXycbNNgXocgHaafSeHaeRAQFkzULyULXbuaSoijwuCMgyFJdfMjBSRHNhjFWjKMsRBiDpPueHSygyoCLoDhnlOAuNJRRvCwvXsDGLMIAFk",
	};
	return dxjZRPhRKhHi;
}

- (nonnull NSArray *)XeEtYmQiYtaZgqlP :(nonnull NSString *)SBZzCOjqcwOJoUft {
	NSArray *lGrqevBVkAgB = @[
		@"elainDhHxXvgCvVIYRXjKqQKVMtwcglUzJiFMjZpPwlYgaSTuhPrOnghjVkqyvHChAZbTTiCXfbfKbRqzhuKTPflGhowyBlJRJZhTeWelbIYsxAjYdH",
		@"RsFOljYgGjhPAexSvpwcPOCUslgbFeDugMXrABVewfVsMsXWlkjfFANLQvwXIKfILYqsDRBVOMyfRzRgWzoHwucWdyFMbvjYPDZtzbFTDfWDpoHKqfgDVQBUhZ",
		@"MAsWGJysUjSwaanBHNxJZJFCiboEZYBpBDAKGLCobnbGYomCgnySfjjEhSzhRKkdDbCoGaidWfVnumYhwBXTOdHobSiYZpPnuxKpttAITHQYtSPYGOhBWpezvgumSZC",
		@"BASrtZjPmPkaozyEGGDalipdJIZvIWyQkMASMHYTkRqXRrPzFSLsVhNkkaLpzBRSSJhqiXFqHkDycCLaAwGxESbeKEQZoMEGiFZmfeIZQDylPzaIeAtpvPO",
		@"KlnwvXrNzxbFNMyiDKasLKPJkCwfOzNripHojrFsVTaHALSfTiqpsQHSKpzLgPDoauUDNAsJhAGegmnfjtTKNxIXvvvDrQWunqFkjzydwq",
		@"bxNaNVSameDjgqwvuvudvBtStYzaaUMPilamCMTEBhXhoHbbyYxRVygZMyHRZNSQMOFkGuJIjaFrvEJYUkiMOUxpqufzTfkdSVrgOvEbQxHvfHwheQIUueBGheOIfyX",
		@"eGGHnsZEjiCKWRelBJTefvrFiRjlWXTxghbIDRHuDzZlfjaNLqQUQhDJYlbRNuXdLHpBnmRGfqdQzbIrdmAndOnScWMuQtKTzBpPFndABCcOTxGdqsiK",
		@"ysmOEPVQcrvHFyKbygfuEHnTnJmXdlbzqYjyVfSKMtRkEnoELfluamsHYVhCzJvEQgpFewGSclcvkHyBpOPfPuZYZCgHZROqBgVfksDUtENJZitqCkBeZfKtqNt",
		@"cSHYTNhQqBRKtsokShQSBxJmMhuTKsModDJuEvdQzaVezkAkzqRTFrgQSTBbNdkvCOhBFHvzEERPVaRjEmKTDrurWzlAJXiiFkafPFWYsRBGxBtTzCEWII",
		@"AgDmsSjEMPQBuVQJiaeuamzTgUrirAwmYlIuqaicMkRISUdYyCkumKzUkBbNbyhadbmKqcwFtwqqztvCKhTFNezyvraESBTAUCKCUKZH",
	];
	return lGrqevBVkAgB;
}

- (nonnull NSDictionary *)IItaKXVnzaL :(nonnull NSString *)uZyGSRJJKHiz {
	NSDictionary *rEiqfzHsiBCGvmL = @{
		@"iMQPsTDaSnGDuJAlP": @"TdLORnUZDrbVTaPHNxmLbYcGDknpkLKEUbauMoajCFpGNRVufgHmdxLNtbQyEVfZeMrmVbwRHJoqNfCOthhsaQwRLiPdrsyVJqRnXiPygrlBYxqZhvDjzOHUUWnSMmStZVoCYDVVsnsQsGBWFuVah",
		@"GtKaDJyAKOFM": @"OpKVZZDxANbdpvlmdHFwjHsqGXJxvqRfSqRHvZGZRJNBcetzYyqStmOPErixtnYRkMyjLihOoJeUklrhyhWIXVcyIdgxMCgTJNVenvdAfHpTHHkyhfsMLihKshvYrXqcKps",
		@"eMuYWiBrzW": @"hBKZLNHguAZPOfmUonyOUIGrFcXmHbmUXGigUJhHRPXUqQeJiyiKtAmnQREcndNZjQpmmoxmOELHfFVluYzyQFvtVFbkTNHhOaZCafjHJdfuwhuRk",
		@"aJtLIIADSrgskdpqrj": @"RretulUkNUxLwhuZmKyHBuUjHlrjFPvYsjmgNozXlOwwAemAnntzctRAoYQZRtnYZmhonRyCipjtXpAwVineXcsgaZaMAkmheHEbsGgNZRXOeUOTXowtJBqDcD",
		@"BNkkriyZBbXVfncsn": @"YByafHUMzKjYLCkieQUpCQCCidVwfEHlzpSKGkxWuwSsujVkHHfupJgyOdvfCtTPnaCvgsPWNVpXvGIWbFSjerULkYhKhuZGUkdbXTeLLDapHChCagfgcXFCSYzTVDyCHGCQzC",
		@"JCCvQhlbMzfVKxHYwmq": @"JVSaucUkMAwAbCXXgeURswlsSOBTGRzrcoUwIexRvqEWqvNyWhqcmzeXQHXazVoUDYoLYTxOtrQKMERipqkaGVMhOObdsEKYFwzTJoWIUPPGnDgGDHrvQSpjWrrVwioVkafUfoBLqmKhIySgLgG",
		@"WBlWHWnqOEsJ": @"kvSmxkpQVooCejuOQsqYydkgRMZKiwgvnRgTjuPfSMWUyUapREMSUatGajVBXdmpkkUdrnHPiZojUHyjbDuFwUAwhEBdjBVfxXNtOmMfJhMcXbERHVeawfzcmgOZKeuZqHxQKLugCN",
		@"YMxCozsfuYmiGd": @"yCFMlXyqwmwNUWXNHnsRvkivMhsYaPKeGRwTCnqduwAzqToJOlZTIqgjCLwzxBHHDeMLEuzCKMRsAKHsrtyZpjMrYMGkZgNKMXrZvcOdxmTy",
		@"kVSBhCeXIHhSEjU": @"kuTHKOcalLDdzjMgZXnWwqsXeJcerxOJXjxNAsqpGMdhcmAdGntEqQOjvcjGUaLHeVPfRuuhsuQtWwpwQwppKERkSlCJQbbQSwzpsfMSPQtSweEIAsGvyJbEkGhWVyDtBsf",
		@"PKNIEcObwN": @"mGWWqsbYqGOPwNikFRzrGpyeNvulmgkiuLygsectTUANvYRKLPilsuovVbNKipjBIVNZnaAajsQYGNtyKUVEWxfumIfcYTweXneMbtinABXrHLnnbkFnFEQm",
		@"NNqIgRHbxxwujyjJQMx": @"vyDMCpjuAYzPdWiIvTadHHcNFZvKwpORzgprqzgTZIiqgwnVGSkCkYoTnBGEMVIGsZwxiBdwTPVCgDyJKQgdpSeaLMaBVoylfcNLdlLivvc",
		@"cLjgBuCBFhJIKAnyp": @"QgEKndqfIuctDipFINVqPkYqtPmxjHQjlxAxzyWDBFtTMFFRtnCeqwioCvRWlpHrXNnrSWSBmLmVBiIzXFMbVKpXBZvIceiCJdVCkbJfWn",
		@"mcRijhPVpWWaY": @"EIqPRZkVoEVEweuxkoIXfGNrCHGayJxFojwYPvdpTiicfWBjwAUAkvZGIDPObNJWyzZserQkuiKTKSDACEkTgtkqohmfkqaZTHuEFjxfjGsnUJUPHM",
		@"wijKpcndEwz": @"emMEYFwRseyWawnnoAMUUGoGLXBGaWTJEpuUlmgFqjVWZxeYpaRdCTfMVhwyGdSYrKAKObrTpOEMbERxoHiaqTJkHTidaFBHgJjjfxxnEQmIcUnqILBvuz",
		@"wETmppjinq": @"MeBrYeRgVjcbtnGTzIHoFwTYXTwkTLaZssGoSVTlQkBlxdnuknXtCIPdbmswLbaayEKCYrWKWgjCzEZOofDgrifWPnYNaYqmiIYrQwhIxkIOvAWPhhGMCP",
		@"sifcHvGRXZOvcwh": @"gxyjgHjcORKuWTVBnAsKcaYcHCtaWrTGwzviNznlKKMjfLJNGEbWoiqeKbhzTrcRGSgEmrTDynJlkmumYJJUigDphItSMVKKoFVVqkAKQgxSpH",
	};
	return rEiqfzHsiBCGvmL;
}

+ (nonnull NSString *)HehBWqBcLcdt :(nonnull NSData *)bMvgmZSVcj {
	NSString *wDHMHhrznP = @"QXuAxUvKoyVnvqFQCsvITufFaxiabagQrqfYDnlPrsSUKmOgwkABgHbeuyqknotmtKCybrWPUrCahsYYUTfVRQCFufRUwQJSUvOUq";
	return wDHMHhrznP;
}

- (nonnull UIImage *)SXIqSMCZQoRqdtevYS :(nonnull NSString *)UukJTErPaMqaBeZuVx :(nonnull NSDictionary *)zTQTrBWGYaC {
	NSData *szddXiKrbqeEbmR = [@"pphAtdBHStjzAtUarbDrPGeRdkxkwIQrleoYlsvsfELXrDUbyYpjcmLRdZQIFqXZXkiRKkcLsCuVisPijtujHciQnmvIogvLkJOUAvsSWWsGmHHNgZcEvVspE" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *pajhVAoMdVl = [UIImage imageWithData:szddXiKrbqeEbmR];
	pajhVAoMdVl = [UIImage imageNamed:@"rtyeGUUQlMCInZlHgILHYhphUmzGsykDjQxIxRUoOpyRtEexiFwoIHENTEtMjdHqhcWSxIqEsUkJkNsNZsWipwyOhNxRNDPURLsJnVIkoVARsUOMaCGsLlrAESoizpzkdedQJifIi"];
	return pajhVAoMdVl;
}

- (nonnull UIImage *)QtpfbXkDtDWZTthG :(nonnull UIImage *)dwhjCZMFfAnF :(nonnull NSArray *)lgZVdbohNttMK :(nonnull UIImage *)KjSMTiaWAkPCVE {
	NSData *rvqGAPFIZLbOTUSCd = [@"eWBEhBAbKIWmLXHjVqgjxbDmsZzLVbImpTQnEhOdQAjZbcCQbcVbyaOTxLTcOylyBiqNAVvwcGCMDRCSLJkHgDlJWQCPWpsvFRDbuwWYXkqaIqXkeyJAHUUuhcDh" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *bjTierHeSmGv = [UIImage imageWithData:rvqGAPFIZLbOTUSCd];
	bjTierHeSmGv = [UIImage imageNamed:@"RTOVBZNtXAgUhvMFhkrHPupFHlxtHgWcNRrfujHyFLMNDHXHqVubuMZphVKmRFtGCqOHodiUGSwHJZEZgGmOAxNyKHlwHaSPTIcrP"];
	return bjTierHeSmGv;
}

+ (nonnull NSDictionary *)NtVJZczmsFxewc :(nonnull UIImage *)tOJNsjeWXofyjLGVEmM :(nonnull NSArray *)RsjOjJWIACmK {
	NSDictionary *hMpijdyzmBvdParfbqs = @{
		@"kPqmGyJOwbAE": @"lNeWeetcvkkZKyEWZePYwJsliLlqTMgMnDAowbGYBWExioRwnCOVeDktxjiYjIWiRAqQkwYMTEMUwUjoNoGvHTksiUcwZgJtFwnePNydmIhjuQGLFRmYmTd",
		@"HZBAjTHkCK": @"sQzDeRXZMgqzWELuMSyKbiSeXXfyPNNgWRfKQIyKxIOzTGqkDOlsRyKPnhBrMQcVntogqqGdaFhGOEPfkyJTLdnmSfWTSFrvNSkrDaHXxtwWZYxjHlorqTZDYirJpmIOVwJgZ",
		@"wwBxNkdHwi": @"lSrNSiodrWdgkKGrWzscdyYFBsPdHwQwQSNNzAAYIRsnVhzMWQixODmwmcYbGDNxBEHmyBIJXElzBWYgzOWkzQenfwuAznNYCkukgqtVtKcnEHRshAicvCwEjsSfTXNWM",
		@"YHGjGvOkUgSHREIWE": @"IvuZKIcCjUAvawGSfhYCzXKxrFgEiXNgBUOoqmLMgULTInOIIuTCQCnrwEQybxErPHzLYTgCXDvDUxceVjdALgwxZoYijRpNAoBsDrYvfQDpAPbEW",
		@"XCGmwjFCYq": @"ohJYYjVgivaLUEgHOdgtUhWfUZpTMcvTmJrPqhXteQITazlxAHPjCKimWTPYolGbCKJvdLVzSsNwpaSgORrFjJMcvUvwswSZskvOSojcO",
		@"okWduGiynktiCrsyyEF": @"PrZNiDFDIANQNCjlyrfGodOptmiOQlriCaGOfccwFByUWuCAgnYkVftEkPdTukChbgPjqyIQAcceOFUjPHVWjXiRGxOkXXInVRbOpbisGwkLg",
		@"DOEMxOuOjeSNcnctXht": @"jOQrLxynrjwCYUTxzSPLtJnYrUYjEEJUittRIvyiUorEATShgVLrVdmRIfrWIJHDZwOCOiQCIfZGYjXSHRtPdpArETrqakyHvQsXoKOmNJaCzDpgVTVGolCtWwuOTMuRmxw",
		@"tjzJWzGVJeuuJ": @"rvahanvkoMxJFUzeTXthBbRcVDupPmlyDLKONJQBqGedVOvyQdumCiyQVBAIAHBTqrepBAEQdUNqlsOuUTwZyOHfuuHBhJqSmBlPwDXPgGzxsbiFOfIOdSdLBGxmgBwUbSizr",
		@"cdPIDWJEpLkuaqjMjnJ": @"uDVXfPierbsqATuuhrqIHdcWaAgGosDVfWWJATagpyZwWzUhRiXJVHFOVrcoCSZolgLquGJjqllEbkCRXaUiBJsgAMlzDuxWrGgGukZaufWgqFzDxMKWgvYLOMJJGkaPPAYQmQjGdoofA",
		@"tjgvSHGCukTD": @"cfMuOTFEbUQjIbTdAyVuCKeklSBXPkCcmaDSNMpuMhgOEqpocroOIUziSXMmsxstIBIuBBwoddRKfsnaeDqvwOqjwwmihvrkJWuAHabLIDiBAVvIXquGqxIEqEbMOJjLkcMwJlcX",
		@"CfYCSwKNJVJG": @"kiHQVJpxoMKgocdUphuIoSeMNjzQmVlsJoFBDXvVYObLxpEGlmfIHKhRxWZLQcrUIESbilMEhrKevzfDaTJMGIpybQtWQOAeFTMqspNpFxlUYnThkScPPWuQzoC",
		@"TgBOBAXHucyBEWxINyp": @"nsEFXiGhtWuuQYXqdjidyCScajWeaJrXVpPLkNkamIdfbFCyCWRrRACueWMiCPkyouaaRfNSFnsJwhRgCxAEJKjBStIdtaetDMcYioVwj",
		@"ubwwhvQVUM": @"PRfMtfaoooUGGrDyIwtfLZVRZbZCfJhWhVOddqIciSwZjOQXLNHXdFTaluaZeGePMcdIPSWprWJKthkaIgohzQJLWGCgqQuJWguRupggDszlbwEHwZuLKpGVaybcKDdmznXBjXGvkg",
		@"ixOQrjfdQEemoGtt": @"STZogMEKoVuLejTyfjeyKWCxSDrTybyTpXeOhYOVsoNtyVfkZLORRLxJAUFUmjCSadLBSpSzVFNtNTrEZevBXsqKBWVvPMZVmenOljVcyCNhYmSxWVmytTjlrbKcqCKtqzsImHdmFrIyRAEuwAXY",
		@"ITLyZBINjZTX": @"JQXsHcmLbQsIxqJuJJdgBopOCswrFqwMjrTXmLdeoiPCMXieypMDXOtXwfEHYandwPWpZKgRRblwvAGwHWRwONeEHBQeEQkgaPqitlbvveEiPHxUQwNBEGDydNYLqLCJSUvcVyVzJguYAqllH",
	};
	return hMpijdyzmBvdParfbqs;
}

- (nonnull UIImage *)NILncMZSdwkCxoMEQcZ :(nonnull NSString *)VCDfqZOLuCnSFIpPv :(nonnull NSArray *)wFHCAkWobdFIy :(nonnull UIImage *)NFyOgQefnbdmAbRxqy {
	NSData *LMRnWKDqRYsZxcT = [@"gUlINoFSpBZVEFJXcDnPYsaIwzxipbOqBkbwcaDYjgptwVDobfHyciwPSHpkgDiczYepWvYZIoHVjHkQwNIQhAJVDNmWsqnfWmZoVBO" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *fNIjDOWqKg = [UIImage imageWithData:LMRnWKDqRYsZxcT];
	fNIjDOWqKg = [UIImage imageNamed:@"UFMXReJphWKjfndXrWIMrJlBXjtvIAYuNYwyhmwxvTFTgUpJqfsKzksAkhUQbwTJsdpYMRkcyijDgdRbUsqQHRJgVgVFtERMjqjwLPBovMYJHWzyPRXpDdDdLXQgYmw"];
	return fNIjDOWqKg;
}

+ (nonnull NSString *)yQMwWIpTQJshH :(nonnull NSString *)utpulCFlTOLsALovK :(nonnull NSString *)HxJLXqguppNEkNQyMe :(nonnull NSArray *)IdaXEmYyZeswKYeMym {
	NSString *nCdlOBGsiTPgHsmOIq = @"hhvcsVhyaMTLTnqnCTgvMZABalTgwlCGcwPBpsDwyPzZIbeFjBGawzJwbkwXfWFKWlijVugLOfsLGtUwpDDkIBxxqVrokHLsesBLIwWyQdiWxl";
	return nCdlOBGsiTPgHsmOIq;
}

- (nonnull NSArray *)nyICRvyxDeBembH :(nonnull NSArray *)XqjpxwBwpBvZc :(nonnull NSDictionary *)gchdsfuhaDMfwfA :(nonnull NSData *)TvdInvIVlAZubX {
	NSArray *lMMcvyYoGqP = @[
		@"IniaYEhcCOvTwTXZgqTJYCYSGZZVPDOZWYqHzzJHSlVDhjZRDNOuHsfSWjTaCWVgpTgRbFjRTkILjqGGOXxwllgTieBrZgcNJWYOzixohHwgWxZKOmNQRCTaRTDjifgAP",
		@"TvkZGfYhLUoMviEAKWBzgKRfVLXtobLcLZcfXyMdGJpIXNgaRFlRnCnoPmRVLmZfHZSxoGMyGggboePaubopGtKxryochWClsegXJSbrnRocbGSqBWhadptkdmaWwPvBnVD",
		@"MJUuZlAWDCMdosOlkUTwuokRAdtCKnhnYozFgyHWtLnDsFVqfmvvQuZKgrJGIXwxJDYZGDoaethxMgZaFVYKfsvNNfzlJpudFNOlDkfWTGPKIwKlmBmG",
		@"xoJfYzBpAdmsuZExBHIfBuUwSihgwOkxAcJARjBIUCXdyphLWlGCxNgWXZLvPufYqCubWWpDJoOkVSBBdPcAkjTDycduKvVZwhyaFXoFekmzBVaVxXrzMSOkJngjqruwjneHiWemjkVkud",
		@"WjlAHeQUwQvORdHeDOngQlSmoDIQePIKrtxtdnrDkLgryRLLUzUGVWpZQpGMgqKekjwRsUqvCzfTPbwmsYlWbCelZwkVXWgIKTYhewrXkDHbbZleugjsEK",
		@"FhWHUJdIXczTURupiDDXUbEcIbzQqSaFozNBCjTRxzHjcpsHWUhxViiZkIdTNKdqHfJOQsvWDQvuiZhbwTDbSKPEyddiHyJRtmXXRdfMQJxXgCUEoZFwvfRbAtBSrMUjDhbHncNDLnhhlPprV",
		@"oCSlrogzfDQOaTCmIBsLBIkbVAssOBnaiisvLbOmWYFNuFauhUKUKgjHjCLLASADxNDmcxALirBUUKkYhqgBNWrfkwJQSqfMyJPlfOBbqdGdLNpzzCpvCmNoDzlAnFxhHH",
		@"viZpxxNkisbIOhZuTvYgzUDUMRBEkwWNNBvqTuBAHDcEoDTdjQFLaCDPGtjPIWlgjOrQUyAosjuesQnPakSjbftzWsRyfyGNmQArmiE",
		@"BcbVCPmKnAbGLVtUqPgBkDwXPIxcvjuLYqvosVwsSQLRPGXgHKvTPAgBCVPvQbRhocjYZXdPISgkpCOKMBZvQxhXhympZwbebsBLWz",
		@"QnazSRNuOijCKPfvGHqsAUkoadGduCeGTNiHsSVLkcdNVPpJvyZfIPdXFmnjnPoMKctqiTIPVfHvSdnDyuaxvAFrYZMrNScJrzmuDvgzyOYydsipHPNcTsdFbRhZ",
		@"luTxJxEMStOqXtaxzUbDYFOczGOcRjVujCfLsCHWHpFPVWDLBzEJtCLDShCBEjhkTuxhJKLsKdeKhhThfyEnKmGXwurMaqBlqZfLwrePVlhDeIeimZQFWuWWECEGxOxRdxtVkalWPtYDxLsCm",
		@"DYaYcYAKxfoyeYEuEhwcYjaoenfXmmvnTzlRZMaNkSBfHCMkdzldxUiMRFiJFqXVMiiKUWGNwtjFLDWwVVMsVjyMERGnROVCUTEaRIqzaWxaosfKnBEPXHEgGUHIjbgshGhqdjyBLsYipJmAlrvj",
		@"HGWGBzoDFYstpSnisXxxloBRNqSKGDEdsKzcBtWoDHThDPdGfNtaenAAjQDzJzcXPjqyJnshZpUbsmLopbCEnIHfGAaglcBQCOMSbKkLIQQsDODHYsXdgtqIuKriQgVtcnvNNgQtOxil",
		@"vQoyOZpHFRxgNtyumkFKRxFWGQQohDtcxHIGHZwUXVCKSKUkrPBMJzNjWerzyWIixrvRaUfaSurtHBgxYzLVxWsZOYvxNrPUhexCiwrgzeYyN",
	];
	return lMMcvyYoGqP;
}

- (nonnull NSData *)GEYYktSIMMENAYR :(nonnull NSString *)ukHDHSztkMzLm :(nonnull NSData *)mYGREozQdHIzA :(nonnull NSArray *)lrMkKHDWaWOUUH {
	NSData *ZEEoGFFFFk = [@"DNlaYqmDBXIBfuqyGgAzhRyaYBHChWsMSgSocVbewAgnlyVXvvGpxjfMGAFLZRPzDRbIxQjRgZyFfjIImdYNJwodhjfyiqDSAiMXRlXNwTQGPlxyGCBfZxUecSq" dataUsingEncoding:NSUTF8StringEncoding];
	return ZEEoGFFFFk;
}

+ (nonnull NSArray *)AYIDcMHmuN :(nonnull NSString *)iPzczQdvMD :(nonnull NSData *)AjVRwwQOdBw :(nonnull NSDictionary *)MHnOqMHEPjjJW {
	NSArray *mIWldohAOmT = @[
		@"yTZTGQKeBpmtWkkJmZJTgDtxxTCdUnJcrUMrDVdpqWAXyrzTqzKquhYBcXCscouyctboaNIcYVWFEniBhpCxBXnQWDCcndyXwIStzoMYJxzYhRMUsTkfw",
		@"aDSyPgYgEFsLGwmSNoURwohMZqJXwXeWgYwQiPbchTWPLJjvqfgyMGdyNvMynnOgvhEDvwNOqgaiCEKNlMIPeaaqhuHXJFOxFKiSzwidOduumQMEzxphlvbYR",
		@"cLUzHVkSDJPjpOuEWqtXHzmDfNPZblABZYRigIGKSXlDvkBcyIHPAUaGQKCuNdSMxRnzfmdJwvxIluyfYpHSVmPyJXwPZhAJwpdeTrrwXrrfOsIHTvkn",
		@"emuZpYzrallfXBbreaCVQJTeomUbdcCRhGzNnKbBLVLHnKltcWNLqWKxorKCaHDhBxRZPQPTdgQNtybnCyQpPKFjOEfYkYddAIrCWphVSmWLWqOufm",
		@"VWvyHMsfxqKnCLHACFFBtVlLWRjHsFmlATCWvHvYsrYSObEnilYklxWWJNyDoMGKIEncoWdCowHuninHWOwYNvCihVyEktkYwRwgLczPuZobxsSRESMktENcFeVfkMeplThVpSi",
		@"UhnXKAaPnrBbdjrsSqVcjdjmAJVUxsFnCaAAHNyXRhCCSYNmRJSsNFTgBUNzfKbFjJUrocCNbAaXhgZclLKbTxOXHfhHJBLLGlsgiqhsVzRpelQXGYgcPTlbInNcKrB",
		@"HuZoqNjMcpJFGIKJonBYrxhxRvyVOhPmaCBkykWzFATCOGvbhWMauUknVtBSevAeyxrxCBEaQgbOHCWxlnsfaOMHbPiHfXSGUJolRFpYZkoDLZXVtcKxziFTjhBupZPpVArbEyTbcTdPROwhUOc",
		@"bKnHegIMemvIGWcMleUtPxNaQzildWchEFmlzTotiobfkDRLYMxdDUZtcgcqQCaesUvuNfZMtqcisggZchyzEnZXnFQRYmnIhREVtMmUOfUZkyvCuewLytLDmwTSmDYzOPcer",
		@"MeAFkEUVJjFVTPUDZSQcLfLmmFEFCacTlUjDFexbXPNwPKKWGJADQZNkoztUawqpylqNWKPROFvdkuZDkosXupWjuVHCCAAEmzoXjMqkPeiH",
		@"runCveErGNyvCLUAukYJXtCSYfJGMGxIzXgxjnAUJOkHxtpMDgURqsTZtCvnHDwAGwIoeLnMhaejmnESSjmkEOsTFdebmLUKzrharZVwIrAzUOylceZ",
		@"mZElijhpQWVHOUtfmfjBWxZdVcYjgTSwUkuzapWcXRIcyQLUsunwQDXbYKZDUmwkakUEUKGldbkGUskRdBlKTkGpKtDTUcwnwUydXtrKuynUoFPgWzMiai",
		@"ZArcKyIWQYbouEMSEnfcHPsfpDwbdlGUPgRWfcIvqYJTuiiSxyuPRphviuRDElJCMKcRPIqRXKcKpqMdkMGyGvYjOaJWjpRbgfqaOJKKpvboxOcIAvCxprZfywqfVHYw",
		@"BMBPXVmIoDcfLzvliUpwubdMzCgNkjZbWendSxZiPvCazMvPEPEQTORfiYsYawwYtgtVdZvaNXijkZCOJobxSVvNOLUGcpCuQvZXzmBXwjjdJOdYtXKCGvcv",
		@"JjycgZxUSKiCalJGmtkmEohDLbjsQSKtZFJTMtOgCWcuhOhptHfkPcjUAKKNQMVBxtajgMSnEutPrcHKOiieimmASAtYNCsjVneMHWOnjpuVBcSGwIdFHyKGiFeGjBTDj",
		@"qztwdNGTltJKIzpKYuPuzhuRvXXfBxQBnDtMXpxcSSSdnFKppCnbNaVOjOkCHLXUlRGjfxmKRMIuYjIoRuLsiSTGnNayNHvagrAmNNeoeSaFdO",
		@"ydVrrZEOMoUtfrTZrrMFnSsciesGoSYrYzMsQfplOTEhjOSsKdLzmpRsiQiuNUJSZStcvdEYLGyfFmgUuQPPLNEAoxKlxFamChImkGexsNmVpu",
		@"xjrxeiiysjgBBHhbxVFOniNPAzlltjzVMLvQwsFogXizImIVpDtebpxoqEzJCumTZijkqURyjDzyZGPmqyBgwVZPslhUiuSWhyZhUOlARgUIWwiJJOZeaLWxjDfAColGrOjVIdqUeEpRyJr",
		@"QGbRjesvUVbYMbDdwRJmBNuGdShOfaHZamPkXdgTJMGTYjQJXjUxEMdEmlxuDmEoiAPOPWJrdpPWeZlclTYjlmnNljwBlqUiXEzIdwWerhZpDkwCZUhEojjeGULHcCvmiyamEONZphznHWWDtF",
		@"QPURHXoMwNAAuQpqYdjeTsVKfTVoWwGXEqWGAoyFyKGGMwrvHMWgKmCVTZZCkLAGURMwsrETnioGLXpHUOPgfEwnHDSOlxbcGRPFCrWmkFfxrEkXvdBVMBVjrUtnliUuJlnGrZFOmCuqQTvG",
	];
	return mIWldohAOmT;
}

+ (nonnull NSArray *)nlFRtzqMRQNjnOMiaeV :(nonnull UIImage *)IEedTXJvbxJFjXc :(nonnull NSString *)qUkfvFBzHqLZAfnpY :(nonnull NSString *)fSBgBwPbokoyvlATbe {
	NSArray *lMmtkIdDlmdLge = @[
		@"VNCSuiaPzvEQCZwtLwlNfItvYXHIWHJnVjFfnpQeohGFYeAmgjGqmujqVrhtVzMOgWOejkBoVLcLRlbgcbTfUdrIzvZNFZWOwtnaJLWysM",
		@"JtVJFohWfBEmQugsMNpiDKYyOyYEsfKCSzxeYGTVkIEBXxhKwmnoTdoqJTVcgcSRfqnRdaNMLIDGgpFubzNfLfsykPdebaocITRRoLoWI",
		@"xqePjQpcEnmzndNjXiYtVKJrRneXCJFCrhFQRqgMwRqpxerbUzbAZawSbEuWtlQWLhJKHLypTsQRsTmsfVQawQhjTzsfduPWyPKpV",
		@"LChWiSZiFkomaFCrRSuGsOhqIKVJULXDYWYwmnsRPRicFXUqlMLiWHLRreyiqcNUntNeserrJwrcAxnalSvPqSLeFPsTPRJhMqTEpxtQjKUKNOaMfsXEMNSiaMGoLlias",
		@"LrrVcBItAedbEFchFoaLJQjzRBPFvFCnkMIoBXcLuhiuALKPkNBOqboizxUzOHmNjkBRHjTDLEkISzEWJCOfTFXnRIroVadWZmmQkOhPWPTEfNPmxHaauiGCVZyTnawEmFOLrfbmTocoV",
		@"iZRnoyTcCEaCyddLeIyQHjFRmOgombcXdpMnxwRZUWLiMjzSZeyBAyzuoDeaqnVAxHfbRfMHbShnNScpdSBeuhAhaOjULpOvlupcKidjPuFEyHOrZnruRggqwjSqIYt",
		@"IiIitvkHMeFmyFIdMDnrtLlBnMPtcpXtakkmPzMzknoCNYSUYRrezufsUcXKYBOPFrXUDllYYuobKqymNwCkicpNkcPXePGQMbyBlKGAZLiLYoRAHZq",
		@"tTpRdsgEvSvzhqSAQNmhvRYQcCBZClzKpWOgJDJNXfoEDzPionYFLWRMqPCSDFsIjEGwXpsCKsUNKDwKwdTSVKSxIaziKCgNyIvPOXiBksurqTNYagsYrSFqRnUFcICuhrcPPwdYlGVj",
		@"EwfAKTXQCBRqfoSJnnXhHmdVPNuTMARwfxErqwdnXKeRvdPmDNkfNckDbBsySvRaohmIRbfJzRvQBGDoXWbJPZwKzIBrdDcaZelJEhIMBEopVlZNgnBrfdIwo",
		@"duHvwisjjYVtUAXcJiOZlYsgQxQOSFrvhiOSHukTlrTTRYXaIwBOPYcMllYOOknLwXxvpboODWjkWkRkZoJJzRmtrYONBNYsbASQiihCnKZzb",
		@"YPlhMWJwpxLpwhyGuxtexNTBWygMxecRFNiEXyfbZGCyziCoXVOEKTZYveCeelSSgdGaQhbULTTfjlnlwNsqRpacVFWQtNTawuxdMIhVyWIjwCKnMosQigLvQpFVhGuZihlWyE",
		@"CwlOxEGlEHTcvGGFHFQXWaMgAUrlkYLFnMOPLkAjjjbYalIWmhmWxZmbsauNsvNXnsaAacOyPTfmAxQwXAvohKoieWVaONazVqVfvfVperFZcwrZITQcaUSzuHEMWyjCEOlrTbbUbS",
		@"xKrhODwHznUNFJqbYoQglBtlBGmAbegOiMLuWvfUdcBallvQYBzdEqeKKhtzTzERDPheQXDrxlkaJebdMAfmfplQUDwgBYwxWdqObSPIQZIOrOOESPIQSvZcaMLDauvMZud",
	];
	return lMmtkIdDlmdLge;
}

- (nonnull NSData *)sEUdBsJvstRX :(nonnull NSDictionary *)HZDIodmBCbnDPFNGoZ :(nonnull NSString *)iduXpMzlcmnSAN {
	NSData *PXgRsSXbzqGFkB = [@"yuZkQRVfmFyoTSiBITgqLtJagjvPRPLllrWEFzQtNARHkazuCECoDSxzDIhUMVrHovJlotncodZNUiFwlPRMMyfkAIYqyqMlcdrqiuJ" dataUsingEncoding:NSUTF8StringEncoding];
	return PXgRsSXbzqGFkB;
}

- (nonnull NSString *)FdDUfCcdfSoXSLVvQP :(nonnull UIImage *)eYyqUXsOZWAETCl :(nonnull NSString *)zuvOEbXjHrX {
	NSString *PEyRwhAxgdechuKgyb = @"UXNWgNaJktxejCPqKJwshermvLmvwTcSxHKoBZgIyVmAkIPfJqKtiJYaIJAgFDzhBdmewExwTvTrSAgGZzzJiRxJEGngJBUVtKwNrgWTaxkuPiv";
	return PEyRwhAxgdechuKgyb;
}

+ (nonnull NSData *)wCMKXVjhXX :(nonnull NSData *)GRiBXxqitRo :(nonnull NSString *)RVmaSOFhWWPmvBiJKnZ :(nonnull NSArray *)WKxDvUgXgGLVqhHQKM {
	NSData *uHRfcOvnRr = [@"UolYZOudYYkxjCFqadQpqUGkAwwiDdwgYHmpEiZqRbMCFzKsDPDLwHdjCxRULpJLlnDNHnzfHpGkeqMzHbKSObjqBFetIbThcEJb" dataUsingEncoding:NSUTF8StringEncoding];
	return uHRfcOvnRr;
}

+ (nonnull UIImage *)mamMLoMBpTbPurX :(nonnull NSDictionary *)JqKkfabSDguRWl :(nonnull NSData *)JjXQMZocTOezI :(nonnull NSDictionary *)MWbrHbCfXOMZIdHy {
	NSData *BRurctIkFRtpV = [@"rqHMkgKEUBOfFWAMjHThaSZUoxfkJeZAIYnGbhAucWMrarRMIplgWycfRRgbhdejphrPbbkeIbXDouEQbSLaSAEJTHmsShAMPpnnijnSFxqqGZ" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *SLrWlFAKihBNKp = [UIImage imageWithData:BRurctIkFRtpV];
	SLrWlFAKihBNKp = [UIImage imageNamed:@"ADBrQYLaAFkOZTbfmyRkMNAncaeYqJpwUmiNqhcFuWMxhgXxHLTmqBHcbahHmGtlCMGHbulhzGwWVVycUaedaXKypKzuCzwLcmseksXVSCAKQeuxAhteqOSokfbHOXepsTRflfDVjvhfqbveM"];
	return SLrWlFAKihBNKp;
}

- (nonnull UIImage *)maCqzyxxcGXNrZQWWOv :(nonnull NSArray *)GlXkzVFfRQ {
	NSData *WVnEmqbApafI = [@"MXPRCogeBVuUxcCgQKMScwlnZhdBVGbMEnHqAsYtKvroAXgOfcNemGSzjwdziACBrlXCLjGaoUciipFEpKXKLpzxPidXEgsqcrBsXGFEGvbuRjYSkdlL" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *nsTKJnjFynOfAPBx = [UIImage imageWithData:WVnEmqbApafI];
	nsTKJnjFynOfAPBx = [UIImage imageNamed:@"PHhnoMyZRtIRgBKBWKEyzLvYmGioTPgvwNsJakIvnCbwRZKAUsUBbKolbZHGunLQMqScLatiDyqacXWrjxaYunYAycFJWdMyuoGZpaZeeJMSkxcsLDMHZrIqxnqRWLSbKOPnnbVaqUBYzHS"];
	return nsTKJnjFynOfAPBx;
}

- (nonnull NSString *)akoLPApmNBTdAFOWm :(nonnull NSString *)KGggDLCGNbwGgf :(nonnull NSString *)VeeksKupGNpz {
	NSString *HShAXFCIDHSqQyVYXxZ = @"MCNtASFAlrQReDugQlULCdaNDVhFLtuGHCtFqHNiDolaZzbOOoDneOxUmGiwuFnkwNSjMDajRtMBLxdHUBemabJJTXsMtDZQnCdLErAOGbSItRHrMFsBefJriVFKFgkVy";
	return HShAXFCIDHSqQyVYXxZ;
}

- (nonnull NSArray *)jaJniSNOOYDPw :(nonnull UIImage *)MlnQenuEAURrjJXbGvc :(nonnull NSDictionary *)LfkpnrAmcxJAjEGwoH {
	NSArray *jCriEzCXaDFlLUIDgen = @[
		@"ZjfUlELNTXLZYlFsgskjTlzhvKrNExQCdAkMSmTRXEpoqPDhWUbosqsmUcYiGmVLeJDpuOjOHeoIARaTxbtwiAzJCdoTdZjDRFcFsoTEfUEvgrINkgzuC",
		@"oKcQqFmQqCwKGeledMcNXxFtpIQoaWkMhIQTDvkOJUPcQtzrxilOBuyQNerZKMeoUSxCqmyyrLVPFkhQSXCySgxChnTPqYtwcLDYRmPAocDiqHlIdbEbyJoeStn",
		@"MIuBHstsJiiEbMgJqMwXEyAfrAGHYSXkTbPNjoMZUnUWdMxPNAyMjLoxNsPIELJrmEhcsdifTHnlmxZkFOXUIhoXlMhnhndbCMUamRizCxeATLfmppSymPChEWgEUzfZagqXtrTXYyIQrCLkB",
		@"HXpEMBUGiwBhPDfeveBqvIhVZGrVcmEJAefjcVdRbEJBnfDKJlPIqvgwtTPKqgKleKPcbNggVPayXEamAgHORrlYUyJLPrjMncPPqbRehfW",
		@"SuwuNktuLnyoWWNfHCAdLjumDtdYMIEumIbHBOQPUlxQfDxMmWFklXhZrSuccLchCGmhXDBuUtkhClWRoZWPqLoRCbDJJilRnbyDagMZmKpsaulVqZNoKsUdsrHHGIJLDSUgkc",
		@"KjKFgjuWQmHtaevYmEQQvtenQcdOqhGZjpyRzPwgmAIzzEtKdjkCEPfMPwPgERSVfvMbKciJThKLHJwntOsybrnPrPSbPorjCbdqZCDytBOZEsjb",
		@"vEAUKQEZAQWygpxsQzcVhqjPafBaZrRzpGodIRcHrilSuNnHsFrswXBvLFezefbQjUsNVdZJsUgAEpCRUeWimCqHGzSrjCkyjxMPZGJYJNnqQWRWhEhgS",
		@"ENAILGSSfNRiuvHbMsuPVxpDroitfgZwAspynGxOMQsFbVahsnCBJOifttnZdIIQbmpnpfJyCTciMkYqnqFHtIndYfRjiGZbyTGXPMvsmQIUTiZnDQikoQVfBlA",
		@"pPhlbbZxJJxGWlKHvMxYRyNkTrCMQmdiJlcvBnNKFqOQDHGTGlfxtHaMXUxHzHDOvJiLzxzVZaCNnVnhNsyeXCGRKEVmLrSGCUurVXaUYg",
		@"NBSqQWZAGNADsNefEgGKSNdIAFgzrPsWhHnJSTiozLJRlRPBpMDxJalbboExljSZYswbwlcGcuEeFSDToZNmmiKeQquGDKypXyumThiBbfyznjcjnkgcwsPKmgshkHlYKOI",
		@"IjmTxTHyZGqZZmULxUoginonrKCABoGPNjbOBgspeFdZabDpcdYAJNrZXIGpZAouaTmGBPCmDdYhrbEGsmHTesoAGNkgOYtSwWwbjtXRtnbYeHHIjO",
		@"gdoaJKqCVUDHDqOIhYWPWwWXCAIlaiqwcKuWzmoxvIgVpATfKActxFbcIuEmvVCBsdVTaZdaoxMtOeIHDHhlprsfMYEJEuDpkQkeVKCOcmhtNXLJhQGdfPcYhVSmOLdajLTPe",
	];
	return jCriEzCXaDFlLUIDgen;
}

+ (nonnull NSData *)fjgPTjBIQkgAcfWU :(nonnull UIImage *)saSwhQehcQW {
	NSData *CYkkDjlNtv = [@"zkfIWOAyYdcqGeXbgISCANutsJEjBjqtqCRpkTEQowcyVteFniKFESlTJzzNyuqafGXTTYykTaaLPLquRceuyGinjBOFUBEoicXFCwrueKvdjclbxgzhNEfnwiDRY" dataUsingEncoding:NSUTF8StringEncoding];
	return CYkkDjlNtv;
}

+ (nonnull NSDictionary *)QOneGulaiyU :(nonnull NSString *)BgsdgvpUMzebloJ {
	NSDictionary *qLznfJiHlbikkutbA = @{
		@"ugcOQJDpAXedLf": @"cBHjSvhCgdAkZmMUkVLucgIdQylgGmKjrOnsocDAWpWYkPUkOGSBJOKqaItQPWjKHBKChiuAwMHZWlSJSjfxMqFxFxEeEASBuOzIngTqWJnvbOKpNuOZxBzpNHUczxtXPuO",
		@"GKCVSSSotNnqE": @"KSixivlpxDLMmwJplJfmnpHpZXQsrQfxzCKePklgWESVJHswPMwukBspElXRvsGgzZaCwojPNualsGQUAdizHwExdzasujAOwFdpTBNoIsswP",
		@"OfovbRnTnznI": @"wbcfNjIZPrkcTvNasCGOrdxRROtuOOoefPDakGJMiUVqXnFIMDMygerXMfSwBxIbiQbGaZPgGbPscmWhRDtUfvXJavNvKaNbskWVmUcoNhnapmBFmMyBYwnrJlzwXQtiNfInlgMoxMvWDxMiuUQ",
		@"nABxgEwOxTtUc": @"LNeQNelFatUJExDXyrtkTnTVrVJNyGEqxgyYYFZkBHLGMTjUnfafTFCWUPZgMnKjUmkPzWXYoRHPDPsoGYZFvxOgEdhzRNfTDdphmEDCMGzyidqUFpRUtPizcyymIvx",
		@"KoTCHWLKLexyRn": @"WOsgGWQmzuqbHgOQcZKfFFjLRDOFylUXrmGxuJjhSXuZBQZDdggsBglPssPsThbaiEaTaHAMOfOUyybKVOgWHSDlEOgVstyDcoGCJkCRsomQkygvwGOCcyivjlDSIZTfNZgYN",
		@"bPgDjAKWDxPlIyLC": @"gPBaSWVJrMkMqGVWhuEYoBrhXQbhQBcTEEUNDaOGMVEBlADzJBrMGDLkFcWsZgUDPIuHQJlsJNVcqRaGwrwtaIhQpFZjKVEuPVJGKMfAXWoJHlBLbZDsvNxZVkgWjGBDpUcnjUglRqdOUtUmrHiR",
		@"fqPRExhJJy": @"tKIqoGzYXECPeGlICSCwRdLclOuJYpWAxuoGFaSqJOxmEpAgkrEBuFgAiUzRXKYHgFNGbOFrhhRtDpZJGmwmtUsocCThGoOswITIrJYvbiuhFEPEFOMhZaAmYHyttowwvzrVkl",
		@"sZnQkDIUVXRMfMF": @"GvfuemMSgyDjDJzYMzfRUeqfrzSfGdvLJkpniJMdxnCUyRQSGDudoARvMcHmoOlIQPGXNiXdvkScUfmvwNHgSanUoNoduiEiiqfTpHZPDHtofNvKVIYHlqZZnvMxnRfDPWktd",
		@"eywvTKJEGxYcsrC": @"iBCmeGHcMcTYOvwLXjWaTYTzxSWncTdmGUKQrYfihwTlzxjkvXItPxxYCIaATBGRbSgAYZQDdYaYaonESLmKMrPFQzLJfeozXUHubcVPexerphgvapQMcEWCYOVRpagIiufzeMr",
		@"hkFROMqiEljtVLRFQAo": @"kzCGefINMsdwAusxgeQLnJTSWckgqANVdJAeBPGRMOjBkgFzOMRQPlOLtOACGOipmhlCwXcqwChKYwSqVzxJwxcsjahMLsMQhJZdClzGIADVUltBpFmFCdJcBEeJdvTtlIKFiQ",
		@"RqMKfoxQEeH": @"aacKhaPmUDfLwTZrVvCiNEWldsyuWvGTXasuhynJIJDhZGaNqyransvkBdFsgKAJXkFwEzpPAVBnoCDjcJJSlvqQoVzjFCpjJMYPIy",
		@"lXvFtAuBKqtZ": @"UMbqUzbTdRDFGyaPazpOtkgozYdxoaMfnTEMKPQnfpdmXhlGuxdeuMsYbpdnznAHqOTopTCEMDdgOGrDEdBLnCQEFwajmYIYXOLrrdRgEhBdjrjdCsJhuarYUERPBrUiErXpvglNooVORWWRUQCNE",
		@"LxBWTsyswLK": @"ElNsOxKqVDvqgxoScoDDygVBscWSlAErDqxQShjlTHlDbDjVEJbppHFlHsQITTCVoTazwpYSnwlPBKPmMRSvSbRdoKvPgdwOtxGJzTrewYvpBGhzupsdNgpdJWBoEaIdzgaINtrVDxzcTlXQJou",
	};
	return qLznfJiHlbikkutbA;
}

+ (NSMutableArray *)searches
{
    return [NSKeyedUnarchiver unarchiveObjectWithFile:recommendFilePath];
}

+ (void) removeAllSearches
{
    NSMutableArray *array = [SearchModelTool searches];
    [array removeAllObjects];
    [NSKeyedArchiver archiveRootObject:array toFile:recommendFilePath];
}

@end
